### ISSUE TITLE
PROCESS: Figure out and commit to quality-ensuring process

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#1]
Given the stakes of these pages, it is highly desirable to establish a checklist and run through it often.  I suspect we'll need two checklists, one for new pages, and one for changes to pages.

## For New Flows (e.g. new forms, new donation flows, new payment processors)

- [ ] Dev: GA tracking in place with the right code (currently `UA-35433268-12`)
- [ ] Dev: Webmaker Referred ID tracking as appropriate
- [ ] Dev: Optimizely snippet in place
- [ ] QA: GA tracking showing traffic
- [ ] QA: Optimizely dashboard showing events
- [ ] QA: Webmaker referrer dashboard showing events

I don't know that the above are the right checkboxes, but I do want us to have some and clone them for each new page.

## For Pushes to existing pages

We probably want some lighter weight process that happens e.g. daily to catch regressions, and we want more test automation.

- [ ] step 1
- [ ] step 2

**Comment by simonwex** [comment]
Old ticket, closing.
