### ISSUE TITLE
Who'se working on what?

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#103]
@cassiemc says: I think it would be cool to see an overall long list of names & what people are working on. It helps us know everyone is covered & active, but also good for letting people self-manage. Who has a lot of work and needs help? Who has a little work who can probably help me? Who is getting lost in remotee land that I should reach out to? What is everyone working on? Who is doing something similar who might have insights for me?

**Comment by cassiemc** [comment]
I think we can close this, it is now out of date.
