### ISSUE TITLE
Figure out better handoff process for designs

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#108]
We need a way of indicating that designs in Redpen are closed for feedback as they move into build stages. Currently, feedback often continues to come in after a design has been R+'d, which is rightfully confusing for the person building it.
  
One option: Upload a final redpen image with a stamp on top that says 'stop comments' ie. 
![closed-comments](https://cloud.githubusercontent.com/assets/1186326/5365204/c76b8a66-7fb7-11e4-952c-1a47c691f436.png). Designers then upload final designs into Github to kickoff any 'build' bugs, using annotations (as necessary) for notes that might've before been left in redpen. Previous versions of the design would still be available in redpen to reference old comments, but redpen would NOT be the prevailing design guideline for build work.

There are issues with this. Redpen could still be a useful tool for communicating interaction ideas between designer and developer. We potentially lose that. This is also an honour system. People can still comment on previous versions of designs in redpen. 

Regardless, agreeing on the convention that Redpen is for feedback while Github is for documenting final designs and instructions, is a step in the right direction.

Other ideas? @xmatthewx @vazquez @flukeout @simonwex @gesa @thisandagain

**Comment by cassiemc** [comment]
+ @secretrobotron @k88hudson @iamjessklein @sabrinang – This process might be helpful to you as designs get handed off to devs.

Gentle reminder as well to @xmatthewx @flukeout @vazquez – we need to be clear about when to stop feedback on design so we don't hold up the dev process.

**Comment by thisandagain** [comment]
:+1: thanks for the reminder @cassiemc !

**Comment by xmatthewx** [comment]
Hi team. I created a series of labels we can drop into the 1st square of Redpen to announce the status. Feedback? https://redpen.io/p/cp8696f514c3503dc1

![screenshot 2015-01-13 15 34 46](https://cloud.githubusercontent.com/assets/53411/5728655/d7466f26-9b39-11e4-9fec-0725b2a2d7da.png)

**Comment by gesa** [comment]
:heart_eyes_cat:

**Comment by k88hudson** [comment]
i like to prefix related labels e.g. design with `design-` since it makes them easier to find in a list alphabetically (e.g. https://github.com/k88hudson/githubtraining/labels)

**Comment by k88hudson** [comment]
OH SORRY I THOUGHT THIS WAS FOR GITHUB ooooops

**Comment by k88hudson** [comment]
my bad

**Comment by iamjessklein** [comment]
I like this a lot. I am testing it out right now with the privacy day project. 
I like to have the designs and comments as a record of the process, so this is a nice way to support that approach.

**Comment by cassiemc** [comment]
Seeing Jess' application, I'd prefer it to be tied to the design in question rather than the whole project. I think I prefer single long pages vs. multiple shots though, to be explicitly clear about versions. I find Redpen's "18 new things you haven't seen" + the back and forward arrows lends itself to confusion around which version I am supposed to be looking at. So if these were at the top of the design in question, that would be more clear to me.

That said, this also seems high bar to me. I like that you can't miss it, but maybe an easier bar would be to just update the title of the project?

**Comment by cassiemc** [comment]
Another thing is that when you look at the repen homepage, having these status images dominate the grid prevents me from quickly finding a project. We could ONLY use the red one for finalized artwork, though. I don't see a huge benefit for the other statuses.

**Comment by iamjessklein** [comment]
Good points, @cassiemc - another thing that I am noticing is that it might be difficult for the developer (@gesa in this case) to see which of my iterations was the final one. I wonder if it would be useful to add a mockup at the end with some sort of indication as to the fact that the mockup represents the finalized design.
