### ISSUE TITLE
TEACH: teach.webmaker.org MVP

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#11]
Design and stand up a new web presence for teach/mentor/community material and programs.

Phase: Design / Build / Ship
Owner: @hannahkane
Decision: @thornet
Lead design: TBD
Lead dev: TBD
Quality: @LauraHilliger, @ldecoursy

**Comment by hannahkane** [comment]
Repurposing this as a parent ticket for the entire project. First child ticket: #180

**Comment by hannahkane** [comment]
Killing this, since I now realize parent tickets aren't necessary in this repo.
