### ISSUE TITLE
Need more unrestricted funds, and more people aligned with the mission

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#119]
Optimize the EOY donation flow and run the funnel + email campaigns

## Problem
Need more unrestricted funds, and more people aligned with the mission

### Audience
Firefox users and mailing list subscribers

### Success
$1.75M in the bank by EOY

### Vision
A highly optimized donation process

#### MVP
A less optimized process that we can iterate on quickly

### Risks
We shouldn't spend more on this than we'll make.

## Preparation Checklist

 - [x] Kickoff meeting scheduled.
 - [x] Deadline and flexibility established.
 - [x] Localization plan created.
 - [x] Milestones created.
 - [x] Maintenance plan created.
 - [x] Analytices plan created.
 - [x] Scope creep avoided.

## RACI

* Phase: production + iteration
* Owner: @simonwex 
* Decision Maker: andreawood
* Design Lead:
* Development Lead: @ScottDowne 
* Quality Verifier: 

## Details:

See https://wiki.mozilla.org/Foundation/EOY

**Comment by simonwex** [comment]
Um, we killed this.
