### ISSUE TITLE
Launch "Explorers" community user research program

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#121]
## Problem
Launch "Explorers" community user research program

### Audience
Community members who are interested in helping us conduct user research on a locale and scale we can't normally reach.

### Success
20 people responded and attempted program before Jan 30

### Vision
Materials, communications, and wrangling to get the program started.
Existing teaching kit: https://michelle.makes.org/thimble/LTE0MTY0MjkzMTI=/webmaker-exploratory-research-workshop

#### MVP
A teaching kit, survey, and blog post, with assistance from community team to wrangle people.

### Risks
Ideally, we launch the program ASAP (before holidays). That's soon, and lots of other stuff is going on. Laura also needs to be around to respond & drive contribution form the community while she's in India.

## Preparation Checklist

 - [ ] Kickoff meeting scheduled.
 - [ ] Deadline and flexibility established.
 - [ ] Localization plan created.
 - [ ] Milestones created.
 - [ ] Maintenance plan created.
 - [ ] Analytices plan created.
 - [x] Scope creep avoided.

## RACI

* Phase: Build / Ship
* Owner: @secretrobotron
* Decision Maker: @LauraReynal 
* Design Lead: @LauraReynal 
* Development Lead: @LauraReynal 
* Quality Verifier: @thornet

**Comment by edrushka** [comment]
@secretrobotron can we close this?
