### ISSUE TITLE
WEBMAKER: Gather Webmaker user profiles

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#122]
Gather user profiles for Webmaker to put on build.webmaker.org.

Phase: Research
Owner: @secretrobotron 
Decision: @secretrobotron
Consulted: @thornet, @LauraReynal, Hive
Lead design: n/a
Lead dev: n/a
Quality: @thisandagain 

Relies on profiles in #58 and #59.

**Comment by LauraReynal** [comment]
@secretrobotron @iamjessklein  New version of the graph featured on #59 and designed by Andrew ! 

![userjourney_20141223](https://cloud.githubusercontent.com/assets/8261945/5615290/ebf9f4a4-94f1-11e4-813f-56d07168fc5f.png)

**Comment by LauraHilliger** [comment]
Loving the progress! Sweet graphic <3 

Small nit - maybe think switching the "Exploring" over the left column and "Participating + Building" over the right to just saying Web Literacy and showing advancement along the continuum? Just thinking that the WebLitMap is complex enough that you hit competencies/skills under every strand at every stage (e.g. you start hitting participating skills in the "basic usage" area, and you keep improving exploring competencies as a "super creator").

**Comment by thisandagain** [comment]
Nice work folks. @secretrobotron good to close given the `/audience` content you have to date?

**Comment by thisandagain** [comment]
Tracking work for `/audience` in https://github.com/MozillaFoundation/plan/issues/74

**Comment by secretrobotron** [comment]
:+1: will follow up with people here to hone in on profiles I chose.
