### ISSUE TITLE
Prototype "MakerFox" Tools for Firefox Desktop

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#124]
Stemming from meta work in #123, produce a prototype for Maker Tools targeted at Firefox Desktop.

Phase: Research
Owner: @secretrobotron
Decision: @davidascher
Lead design: @xmatthewx 
Lead dev: @toolness 
Quality: @thisandagain 

ᕕ( ᐛ)ᕗ

**Comment by OpenMatt** [comment]
@secretrobotron / @thisandagain :  will this ticket require design and/or dev resources this heartbeat? (if so, can you add those labels?)

**Comment by cassiemc** [comment]
@xmatthewx still assigned as designer.

**Comment by xmatthewx** [comment]
tracking build of prototype here: https://github.com/xmatthewx/webmaker-addons/issues

**Comment by OpenMatt** [comment]
@secretrobotron status?

**Comment by secretrobotron** [comment]
My bad. We can close this. New ticket to reflect new scope: #267.
