### ISSUE TITLE
Dribbble Debut Shot

### ISSUE THREAD

**Issue by vazquez** [MozillaFoundation/plan#132]
I think we've been designing some awesome things, and I would love for us to showcase our work to a design community like Dribbble. We have a key advantage in that our work is open! We first need to talk about the debut shot.

While in Portland I came up with an idea that allows us to begin to mold the rebranding of Webmaker in a fun way, and allows us to express our unique design styles. Think of the Webmaker Logo:

![logo](https://cloud.githubusercontent.com/assets/1119821/5412659/a8c081e4-81dc-11e4-8dd1-18cb302ae5fe.png)

I was thinking, what if painted the white background with a pattern, icons, monsters, colours, anything that would make the icon represent each other? We can do a series of these shots on Dribbble one for every designer on the team, and introduce ourselves, our passions, and why we entered the design practice. I feel that this would give personality to our online presence, something that other Dribbble teams haven't done.

Let's start the discussion. 

Logistics-wise, I would love to book a couple of hours of 'workshop time' where all the designers get together and design their respective brand mark. This idea helps us open up with each other as well, getting to know our strengths and passions.

cc @cassiemc @thisandagain @flukeout @xmatthewx 

Jess and Sabrina are not on the organization it seems, I'll look into it and add them to this discussion.

Let's discuss!

**Comment by thisandagain** [comment]
@cassiemc Is this complete?

**Comment by cassiemc** [comment]
Yes, we're going to post the shots on Wednesday then I will close.

**Comment by iamjessklein** [comment]
:+1: :dancer: :dancers:
