### ISSUE TITLE
Iterating on design & approval process

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#135]
A few of us met yesterday and discussed progress of a couple of projects that are in motion. Some confusion about pressure and desires and some ideas surfaced which I'd like to write down here for wider perspective and historical purposes.

This is how the design (and peripheral) process feels right now:
* A bunch of people discuss what would be desirable in a design
  * They make some slides, or draw wireframes on a whiteboard
* A designer (e.g. Ricardo) goes away and throws together a design
* The designer uploads their work to redpen (or whathaveyou)
* The designer asks for feedback on design, copy, structure, etc.
* The asset goes through umpteen iterations in redpen, as designers, copywriters, and everyone else involved has independent feedback
  * This uses a tremendous amount of the designer's time
  * It's also hard to keep track of what's happening and what's happened
  * The design assets don't progress in a controlled manner, but attempt to accommodate everyone at once
* When everyone agrees somehow (no negative comments in redpen?), r+'s appear in the corresponding bug

##### Some questions
* When a designer publishes something in redpen, and then asks for feedback, they gets comments from __everyone__. Is redpen the optimal place for all of that feedback?
* Need we use the designer's time to change bits of copy and upload revisions to redpen? Not only is their time used, but the design (all other) reviewers' as well.
* Might those copy change requests be easier to read/write/analyze on github or bugzilla? Nobody needs a designer (no offense) to make those copy edits unless there's a real need for them to be in redpen -- or even visualized -- where they're less accessible.

##### Suggestions
* It feels like design is something we should do in semi-formal stages
  * e.g. get design review done, then iterate on copy.
  * Then we can be clear about what phase a piece of work is in, and who needs to care about it.
* We should find ways for copywriters and other interested parties (e.g. Marketing?) to scribble on and otherwise edit assets without the need for a designer.

##### Worries
* Am I missing something crucial about being able to *see* copy in a design? Do we *need* a designer throughout the entire process?

**Comment by cassiemc** [comment]
This has gotten much crisper with the RACI and TPS process and the design team has also gotten much better at driving how well we ask for the feedback we need. Closing. Let's file new issues if needed.
