### ISSUE TITLE
Consolidate badging requirements into a single doc

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#14]

**Comment by hannahkane** [comment]
Draw from:
https://etherpad.mozilla.org/badges2015plan
https://mofoportland.etherpad.mozilla.org/mentortechreqs

To be stored here: https://wiki.mozilla.org/Webmaker/Badges

**Comment by benrito** [comment]
We ought to ensure a meeting next week with @anmechung. The IMLS conversation very tied in.

**Comment by anmechung** [comment]
agreed

Here is another etherpad to draw from: https://etherpad.mozilla.org/contentproduct

**Comment by OpenMatt** [comment]
Suggestion: 

* have Hannah take a first pass at synthesizing these various documents. And consolidating into https://wiki.mozilla.org/Webmaker/Badges as she proposed. 
*  surface key tensions and questions. Part of that can be Hannah surfacing questions and unknowns in her draft.
* then schedule a stakeholder meeting. (for next week, or week following.) So that all the stakeholders can review and discuss the doc together.

**Comment by hannahkane** [comment]
That sounds like a good plan, though this is a P2 for me, so I think it's more likely that the stakeholder meeting will happen the week of the 19th. I'll likely be asking ppl questions in the meantime, though. :)

**Comment by hannahkane** [comment]
Will schedule a kick-off meeting shortly.

Would be great if stakeholders could take a look at this draft of a proposed roadmap for Badges 2.0 in the meantime: http://mzl.la/1AxcmUq

@anmechung @benrito @thisandagain @davidascher @omnignorant @thornet @amirad @leahatplay @smithisgeneric  + claw and kathryn, who's github names I don't know

**Comment by dajbelshaw** [comment]
Could you add me to this please? :)

**Comment by hannahkane** [comment]
Sure thing, @dajbelshaw. The doc should be accessible to you.

**Comment by dajbelshaw** [comment]
Cool, will comment. :)

**Comment by hannahkane** [comment]
Thanks to those who have commented so far. The kick-off meeting will happen during the next heartbeat. In the meantime, the doc is still open for comments.

/cc @LauraHilliger

**Comment by OpenMatt** [comment]
@hannahkane shall we mark this complete?

**Comment by hannahkane** [comment]
Yup. Next phase is #215.
