### ISSUE TITLE
Get people not on Github onto Github

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#140]
Currently we have some ownership listings with names that aren't tagged (presumably b/c we don't know their usernames or they aren't on github). We need to make sure the work is visible to the entire team, which means getting people not currently on github onto github, offering an introductory training, offering support, making sure people have the tools and skills they need to work collaboratively. 

I'm not sure who these people are but Andrea and Paul come to mind + the teach crew

**Comment by hannahkane** [comment]
Closing this ticket because so many people were added, but I believe @cassiemc is going to file a similar ticket for people who've joined more recently.
