### ISSUE TITLE
MozillaFoundation needs an avatar

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#141]
Right now we are just purple pixels: https://github.com/MozillaFoundation
Let's design something sweet. (gvn's idea, woot!)

**Comment by hannahkane** [comment]
Removing from Jan 15 milestone, since that's nearly over.

**Comment by cassiemc** [comment]
@natalieworth can we repurpose what you did for EOY stripe interface? Just needs to be a simple mozilla logo we can add to our Foundation profile page.

**Comment by natalieworth** [comment]
![avatar_final-01](https://cloud.githubusercontent.com/assets/14876567/12397635/4deb4064-bdc3-11e5-97ee-3cc2e1a85e69.png)

@cassiemc I altered the logo from the stripe design to accommodate the github profile. I'll add to redpen here in case anyone wants to add comments/ suggestions: https://redpen.io/cy41ffe31524dce811

**Comment by cassiemc** [comment]
@natalieworth Left a comment in the redpen.

**Comment by OpenMatt** [comment]
status?

**Comment by cassiemc** [comment]
Hopefully @natalieworth can wrap this up today, if not let's just go with what's here.

**Comment by natalieworth** [comment]
@OpenMatt @cassiemc Just adjusted the file (to fix centering) and exported an .svg and png. Files for this are here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0N1NoRmk3Z0hWU1k&usp=drive_web&ddrp=1#

**Comment by cassiemc** [comment]
Woohoo, thanks @natalieworth! Update is made: https://github.com/MozillaFoundation

**Comment by gvn** [comment]
Yayyyyyy! :cake:
