### ISSUE TITLE
Contributor training for engineering 

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/plan#142]
Let's do some training/talk to some people about code contribution

Todos:
* [ ] ask some people to talk to the crew
* [ ] talk through common problems/issues
* [ ] talk through goals/OS contribution

**Comment by k88hudson** [comment]
Hey @ednapiranha, here are some questions: you *definitely* don't need to address them all, but they might give you a good idea of some of the practical issues we face and problems we need to discuss (WIP): https://gist.github.com/k88hudson/2b4765eb3d73739848a1

I was hoping you could speak to us some time at the end of January/beginning on February

**Comment by ednapiranha** [comment]
Sounds good!

**Comment by edrushka** [comment]
Closing this but feel free to re-file in the engineering repo if it's still relevant.
