### ISSUE TITLE
TEACH: Update "teach" content on webmaker.org for the interim

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#143]
Augment the teach infra on webmaker.org to better suit the transitionary period. Mostly copy and slight content changes.

Phase: Design / Build / Ship
Owner: @ldecoursy
Decision: @edrushka 
Lead design: n/a
Lead dev: n/a
Quality: @LauraHilliger

**Comment by thisandagain** [comment]
Just a copy change. @secretrobotron to handle. Removing need for dev and design resources. Thanks folks!

**Comment by secretrobotron** [comment]
Landed :). Just waiting for a prod push now.

https://github.com/mozilla/webmaker.org/commit/48bb7808e9f3d8ae33d7bff0abad97efb0a643aa

**Comment by LauraHilliger** [comment]
QA note: badges are lost. They aren't at teach.wm.org, they aren't on wm.org  
Nav under teach links to https://blog.webmaker.org/badges which links back to badges.
Explicit links from the Mentor Page to Skill Sharer and Mentor badge exist.

**Comment by ldecoursy** [comment]
Good catch! We wanted to link to https://blog.webmaker.org/badges as one place to see all badges however now the images and links seem broken. @secretrobotron let us know what we can do to resolve.

**Comment by secretrobotron** [comment]
Yeah, good catch. Looks like it's unrelated to these changes though. Let me do a bit of digging and I'll file another issue.

**Comment by secretrobotron** [comment]
Peeps are on it. Thanks for notifying, @LauraHilliger.

https://bugzilla.mozilla.org/show_bug.cgi?id=1118718
