### ISSUE TITLE
TRAINING: Schedule "How to use Github Issues" open training sessions

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#146]
I hear that @dajbelshaw and @edrushka have some excellent material already.

**Comment by cassiemc** [comment]
Suggest we reverse the times for Jan 9 and Jan 13. So:

    Friday January 9, 2pm PT / 5pm ET / 10pm GMT, and 
    Tuesday January 13, 7am PT / 10am ET / 3pm GMT.

@thisandagain @simonwex Would either of you guys be available for this Friday's Jan 9 session to help answer questions about Github workflow? 

@secretrobotron @k88hudson Would either of you be available for next Monday's session to answer Github workflow questions? I'll aim to be at both so can provide some continuity between sessions.

**Comment by cassiemc** [comment]
@mmmari When is the next all-staff meeting?

**Comment by k88hudson** [comment]
@cassiemc I could help, yes

**Comment by OpenMatt** [comment]
If we're able to lock down these training times in the next couple hours, I'll include it  in my mail to all-mofo EOD today. Would be a useful add.

Friday January 9, 2pm PT / 5pm ET / 10pm GMT, and 
Tuesday January 13, 7am PT / 10am ET / 3pm GMT.

**Comment by cassiemc** [comment]
@OpenMatt Yes, let's consider these official. There will also be the regular GitClub on Wednesdays for people to jump into if they want more. 

* weekly Gitclub meetings, every Wednesday 9am PT / 12pm ET / 5pm GMT. Gitclubbers of all skill-levels most welcome. https://etherpad.mozilla.org/gitclub

**Comment by thisandagain** [comment]
@cassiemc Happy to help! :+1:

**Comment by OpenMatt** [comment]
Andrea is looking for more info on where the trainings are happening (what Vidyo room, etc.)

**Comment by OpenMatt** [comment]
Oh -- just saw it's all here. I think the confusion was just with the other GitClub etherpad, above. 
https://etherpad.mozilla.org/githubtraining

**Comment by cassiemc** [comment]
These are scheduled. Details are in the above pad. So, closing!
