### ISSUE TITLE
TEACH: evaluate software options for Learning Networks

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#15]
Phase: Evaluation
Owner: @hannahkane
Decision: 
Lead design: 
Lead dev: @jdotpz 
Quality: @simonwex

**Comment by simonwex** [comment]
I added a RACI to the description. I'm happy to help beyond QA/Review.

**Comment by hannahkane** [comment]
Thanks, @simonwex. Putting myself down as the owner of the eval phase, and will definitely call on engineers to help evaluate from a technical perspective.

**Comment by hannahkane** [comment]
Evaluation matrix here: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1tEYcrrNhLJjLyS2pDVHO6rY5Q343j7XiVDUZpkh4_zE/edit#gid=0

Please add any software you'd like investigated.

**Comment by hannahkane** [comment]
Round 1 of eval matrix complete - reviewed 18 pieces of software (some more in depth than others). Next step is a meeting to discuss the findings—that will happen next sprint. I guess I'll keep this ticket open? (Unless, @OpenMatt, do you think I should close this and open a new ticket for "making a decision"?)

**Comment by OpenMatt** [comment]
@hannahkane: yes, let's close this and open a new ticket
