### ISSUE TITLE
BUILD: Improve user experience and IA for "build.webmaker.org"

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#150]
The `/now` `/next` pages could use some styling, the IA needs revising, and it needs among others:
 * a welcome home page that explains the site, who it's for, how to use it
 * pointers to things that aren't on the site (e.g. the wiki if we want to keep using it
 * a process whereby Design and Engineering handbooks either get slurped in and displayed in this site or just pointing to them whenever they exist.

Before that, I propose that in particular @thisandagain, @cassiemc and @OpenMatt figure out a scope of stuff that _must_ happen before EOY.  Hopefully it's not much work.  Marking `status:WARN` until we have scope defined.

Phase: Design / Build / Ship
Owner: @thisandagain 
Decision: @OpenMatt 
Consulted: @cassiemc @simonwex 
Lead design: @thisandagain
Lead dev: @thisandagain
Quality: @davidascher

**Comment by OpenMatt** [comment]
* I have some bandwidth later this week that I'd love to contribute toward this effort
* In particular: want to make sure this synchs well with 2015 planning pages. And also: clear zoom-in picture of Q1. 
* Also will need: good internal communication and documentation. For how staff and community can make best use of this (awesome) new resource

**Comment by thisandagain** [comment]
@OpenMatt Sounds good. Invite sent for Wednesday. :smile:

**Comment by OpenMatt** [comment]
Notes on IA and suggested next steps in advance of our meeting:
https://etherpad.mozilla.org/build

**Comment by OpenMatt** [comment]
Andrew and I updated the wireframe based on our meeting today:
http://mzl.la/build_wireframe_2

Next step: Andrew will do a design pass

**Comment by OpenMatt** [comment]
@davidascher : I believe we've also addressed the notes you left in the pad.

**Comment by OpenMatt** [comment]
* Note also that "How we work" will include:
** Engineering handbook
** Design handbook
** Product & Process handbook
** Tools we use (etherpad, wiki, IRC, etc.)

**Comment by davidascher** [comment]
cool. only thing that still feels off is we're fuzzy on scope between
webmaker, learning, mofo, etc.

**Comment by thisandagain** [comment]
Quick design pass below. Screen-lapse available here (need to find a way to time-lapse my sketching ... also have fun seeing what music i'm listening to): https://www.dropbox.com/s/2t0xnm6f2a4lhry/build_000.mp4?dl=0

#### Splash
![splash 2](https://cloud.githubusercontent.com/assets/747641/5689857/a4785762-9823-11e4-9403-9f4877748a9c.png)

#### Add Project
![add project](https://cloud.githubusercontent.com/assets/747641/5689859/b4223d5e-9823-11e4-9260-555457fc623a.png)

#### This Sprint (Now)
![this sprint](https://cloud.githubusercontent.com/assets/747641/5689861/c3b09b44-9823-11e4-9512-393390e68577.png)

#### Calendar
Played with a few different layouts and landed on this 90-degree rotated option of what waffle provides.
![calendar](https://cloud.githubusercontent.com/assets/747641/5689862/d662d568-9823-11e4-9d9e-dd29b7d7f978.png)

#### Change Log
Proposed template for embedding a blog within the build site. This is the content from my post-launch announcement email from earlier this week.
![change log](https://cloud.githubusercontent.com/assets/747641/5689864/e2a43cb8-9823-11e4-815e-9cd032ffb7c5.png)

#### Navigation
Navigation would always be expanded (no hamburger) for screens wider than 980 pixels. This shows the structure as per the information architecture with just a few small proposed tweaks:
- Now -> This Sprint
- Next -> Next Sprint
- Backlog -> Calendar
![navigation](https://cloud.githubusercontent.com/assets/747641/5689865/ef07b228-9823-11e4-9b24-073063b9cafa.png)

/cc @OpenMatt @davidascher @cassiemc @simonwex @secretrobotron @k88hudson

**Comment by simonwex** [comment]
@thisandagain, this is looking great.

For this mock: 
<img src="https://cloud.githubusercontent.com/assets/747641/5689862/d662d568-9823-11e4-9d9e-dd29b7d7f978.png">

I'm not sure how important it is to have the contents of the Heartbeat be fixed-height. It might make sense to let it flow and not obfuscate the number of items in the list. Thoughts?

The "Add Project" view I think would benefit from a progress bar, a list of steps or some other indication for how long the input process is.

**Comment by thisandagain** [comment]
Great feedback. :+1: on both suggestions.

**Comment by k88hudson** [comment]
idk, in terms of visual design i think this is definitely a step backward from what's currently on http://build.webmaker.org/

**Comment by k88hudson** [comment]
:stuck_out_tongue_winking_eye:

**Comment by cassiemc** [comment]
@thisandagain Mind if I throw these in redpen? Just easier to respond to specific elements there and be super clear about what I mean.

**Comment by thisandagain** [comment]
@cassiemc Here you go: https://redpen.io/p/tc87e54ffcdc2981c7

**Comment by cassiemc** [comment]
Awesome, thanks! Left some feedback.

**Comment by OpenMatt** [comment]
* I love this work. Plus just took a quick spin through the RedPen. Very excited to see this ship. 
* Let's guard against scope creep and push ourselves to ship. We can always iterate and improve next Heartbeat -- especially after testing a bit with colleagues. 
* @thisandagain Andrew: what's the best next step in the design process? Let me know if you want to do a quick 15-min stand-up this week.

**Comment by thisandagain** [comment]
Wonderful. Thanks all. 

@OpenMatt I'll address the design concerns raised here and post an update later today. Once that's up I'll get started on the build tomorrow AM. Goal is to push this as far as possible & have an update on production prior to demos on Friday. Would love to to a quick check-in tomorrow afternoon. Will send a meeting invite.

**Comment by OpenMatt** [comment]
Sounds great.

**Comment by thisandagain** [comment]
Updates for tomorrow's check-in:

#### Screen-lapse
https://www.dropbox.com/s/zvcoy1hkko9w1fh/build_001.mp4?dl=0

#### Redpen
https://redpen.io/p/tc87e54ffcdc2981c7

**Comment by secretrobotron** [comment]
Corrected screen-lapse: https://www.youtube.com/watch?v=77dbYg5zOBc&feature=youtu.be

**Comment by thisandagain** [comment]
Resolved via https://github.com/MozillaFoundation/plan/pull/222
