### ISSUE TITLE
Create a shared repository for user research results across Moco/Mofo

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#157]
I recently spoke with Bill Selman at Mozlandia about defragmenting user research across Mozilla. Good idea! At one point earlier this year, a bunch of Mofo designers spoke with Cory Shauer and Tony Santos about creating a shared user research repository like this. Result of that conversation: it's a challenge. But there is a lot we could do, and lots of smart heads to put together on this.

## Objectives: ##
* Make research results more widely accessible across Mofo/Moco
* Ensure research insights are folded back into the product work we do across the org
* Prevent duplication of efforts
* Share successful processes & lessons learned

## Questions ##
1. Where do people involved in various research initiatives keep their results? How can people access them currently? How could this be better?
2. *Can* results be accessible to anyone at Mozilla (and wider community)? Are there legal or logistical complications? 
3. What are the ramifications of choosing to share this data (e.g. more time spent erasing identifiable info, or cost associated with hosting large video files). Of course this is an exciting opportunity and seems like the right, open thing to do, but would like to be realistic about the cost/benefit.
4. Potential places to store results:
  * box.com
  * GitHub
  * Google Drive
  * others?

cc/ @LauraReynal @thisandagain @adamlofting

**Comment by hannahkane** [comment]
@LauraReynal @secretrobotron - is this ticket still useful, or should we close?

**Comment by secretrobotron** [comment]
We discussed a little bit with Rina. We can more meaningfully share documents and other material after regular discussion. Will close for now :).
