### ISSUE TITLE
Allow existing Webmaker users to liberate their data

### ISSUE THREAD

**Issue by toolness** [MozillaFoundation/plan#158]
**Note: I have no idea if this is the right place to file this issue. If it's not, feel free to close it and move it to a different repository!**

As Webmaker evolves, we don't know how long we'll be able to maintain our current product offerings. Even if we can maintain them forever, it's possible that users could "grow out of" our tools and services as they gain mastery over Web literacy.

To this end, I've made a very simple service that allows anyone to download the publicly-searchable Thimble makes of any Webmaker user as a ZIP file:

http://webmaker-archiver.herokuapp.com/

The tool is just a prototype and has its limitations:

* Because it doesn't currently have any authentication, there's no way to export one's non-publicly-searchable makes.
* It only exports Thimble makes, not X-Ray Goggles or Popcorn Maker.
* There's no `index.html`; one that indexes all the user's makes and includes metadata (thumbnail, description, etc) could be useful.
* It's not particularly well-integrated into the rest of the Webmaker experience.

I'm not sure how high priority something like this is, but it doesn't seem very hard to productionalize and could be quite useful to our relatively small but passionate community.

**Comment by LauraHilliger** [comment]
> In all cases, we strongly recommend you visit the gallery today and jot down the URLs of your favorite creations. We will also index existing Webmaker users’ makes and make those available to all users.

Would it be ok if we share this prototype with our community? I just downloaded a zip of my 17 PAGES worth of makes, and am glad I didn't have to jot down the 204 URLs of things I made with Webmaker ;)

**Comment by toolness** [comment]
I'm fine with it--at the very least we could say it's a "community-provided" tool or something, e.g. we can't provide support if users have problems with it, though they're welcome to file bugs in the GitHub repository.

**Comment by OpenMatt** [comment]
@simonwex will update and re-file as needed

**Comment by simonwex** [comment]
Closing this issue, work will continue in #339
