### ISSUE TITLE
Figure out better user support system

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#160]
## RACI
* Phase: Research / Design / Build / Deploy
* Owner: TBD
* Decision Maker: @thisandagain
* Design Lead: TBD @cassiemc 
* Development Lead: TBD @simonwex 
* Quality Verifier: @thornet 

## Problem
We handle our user support through an email-based system today that generally gets delegated to a handful of people (or in some cases one person). We need to have a way to make sure that user support issues have more visibility to the entire product team and have a solid support funnel in place for when the product "falls down".

### Audience
Visitors & users of webmaker.org

### Success
Visitors and users of webmaker.org have a clear path for reporting an issue or requesting a feature. These issues are visible (and assignable) to members of the product team.

### Vision
A number of off-the-shelf solutions exist: uservoice, zendesk, etc. Of the available options I suggest we look at desk.com as it is a part of Salesforce and could integrate nicely with the rest of our CRM strategy for next year.

#### MVP
As an absolute MVP, I asked Lucy to share regular findings from her user support activities to help resolve the visibility problem. Beyond that, I would suggest that the MVP be rolling out a user support system and adding a link to the user support intake form in the footer of webmaker.org

### Risks
All of the off-the-shelf solutions require some monthly hard-cost which is often tied to the number of "agents" that you have. Today, we would only need perhaps 3-5 agents (Lucy, Amira, Michelle, Andrew, etc) but could become expensive over time if the number of agents increases significantly.

## Preparation Checklist
 - [ ] Kickoff meeting scheduled
 - [ ] Deadline and flexibility established
 - [ ] Localization plan created
 - [ ] Milestones created
 - [ ] Maintenance plan created
 - [ ] Analytics plan created
 - [ ] Scope creep avoided

**Comment by OpenMatt** [comment]
@thisandagain still want to tackle this Heartbeat? or push back?

**Comment by thisandagain** [comment]
Pushing back as to keep focus on MWC.

**Comment by OpenMatt** [comment]
coolio. mile-stoning Mar 13 so we don't forget.

**Comment by LucyeoH** [comment]
I now have an even more sophisticated help tracking spreadsheet: https://docs.google.com/a/mozilla.com/spreadsheets/d/1s9AXcLZAzi9SOErBwCsS8OeOOO4Dfi04Ck0bwlt6K_M/edit?usp=sharing

**Comment by errietta** [comment]
Potentially use RT - https://www.bestpractical.com/rt/ to track support requests? RT is "email an address your problem" and it creates a ticket which can be tracked, assigned, etc and you can also do stuff like different queues per address

**Comment by thornet** [comment]
The BuddyUp pilot by Mozilla SUMO & QA teams may be a support tool worth monitoring for our purposes: https://wiki.mozilla.org/QA/Buddy_Up_Pilot

**Comment by cassiemc** [comment]
This one is pretty out of date. We are using desk.top with @ldecoursy and @KevZawacki. Let's file a new issue if any work is still needed here.
