### ISSUE TITLE
India Field Research Trip 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#163]
Prepare and execute India Field research trip 
--------------------------------------------------------------
**Preparation Checklist** 
- [x] Get a visa 
- [x] Plane ticket
- [x] Determine research locations 
- [ ] Book intra country travels 
- [x] Reach out to Mozillians in the different cities
- [x] Conduct India Desk research pre-trip
- [x] Engage India partners 
- [x] **Refine personas and participants choices**
- [x] **Refine research methods**  
- [x] **Refine research questions**  
- [x] Hire local help 
- [x] Recruit participants ( target 60%)
- [x] Rework different research assets 
- [ ] Order and deliver phones
- [x] Budget 

---

- [ ] Excute the trip 
- [ ] Check-in with prod team at mid-point
- [ ] Write 99% of the report on the field

**RACI**

Phase: Research
Owner: @LauraReynal
Decision Maker: @thisandagain @davidascher 
Consulted: @secretrobotron

**Comment by k88hudson** [comment]
- [ ] Make a fake gmail, create an account at https://login.mofostaging.net/account
- Set a password on https://login.mofostaging.net/account

**Comment by LauraReynal** [comment]
- Make a quick "what do want for dinner" survey template
- Laura to write scenario questions for testing the input, data, submit, counter blocks

**Comment by LauraReynal** [comment]
Hey @k88hudson I have a research account : flowerwebmaker@gmail.com
and it has a password as suggested.

**Comment by LauraReynal** [comment]
By the way, why did we need a pwd for this? @k88hudson

**Comment by thisandagain** [comment]
India field research is in-progress.
