### ISSUE TITLE
Reduce Front-End Technical Debt

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#165]
When building out new or modifying existing features on webmaker.org development is sometimes slowed due to engineering inconsistencies and a general lack of composability between various different parts of the site. 

Examples:
- For recent revisions to login, two different approaches to the implementation needed to build built for both pre-angular and angular versions of our various tools.
- For recent revisions to the information architecture & splash page, we had to build / style many elements twice as some pages are rendered with angular and some are not.

### Audience
Staff and contributors to webmaker.org

### Success
Thought experiment:
If someone wanted to add a link and change the background to neon fuchsia on the header of webmaker.org, that should require one-line edits to 3 files (HTML, CSS, locale).

### Vision
I'm not really sure and could use some help here. Regardless of the technology at play I'm curious if focusing on *a* solution for 2 weeks could substantively improve turn-around time and quality / consistency.

#### MVP
Improve consistency between various parts of the "core" of webmaker.org (not including tools).

### Risks
The biggest risk I see is if this is best done incrementally and not particularly well suited for a 2 week sprint this would be a waste of time (and typing). :smile:

#### RACI
* Phase: Build
* Owner: @simonwex 
* Decision Maker: @davidascher
* Design Lead: n/a
* Development Lead: TBD
* Quality Verifier: @thisandagain

**Comment by thisandagain** [comment]
I share a number of the concerns that @gvn raises here. IME trying to maintain a style-guide and a "living style-guide" (UI component system) in parallel is usually an exercise in futility for all but the most large and process-driven organizations (it worked great at General Electric ... but literally nowhere else). I recommend that any future style-guide be done as light-weight as possible as a means to build the component system and then use that as the canonical resource.

In terms of enforcing the system, it really does become a problem the more contributors you have, but this is where having a strong code review culture and even linters / style checkers can help. For example, in `Objective-C` I've used tests that would look for instances of `UIButton`, `UILabel`, etc and would throw if found (instead of a PR using in-house components).

Retrofitting a new component system into a legacy project is quite a bit of work, but the alternative (re-write) seems risky as it puts a tremendous amount of pressure on us to finalize branding and visual design before we could (reasonably) start that work. Given that this debt seems to be accruing quite a bit of time loss and the risk inherent in putting the branding in here as a blocker, I think I would like to continue to ask for recommendations for incremental changes in the architecture as per @simonwex comment above. No doubt, larger changes will have to be co-ordinated once branding and some of the larger product changes land.

**Comment by gvn** [comment]
Agreed. I wouldn't recommend maintaining 2 style guides. 

The static guide should only serve as an artifact of the first design phase and subsequently the built guide serves as canonical for both design and dev.

**Comment by thisandagain** [comment]
Now that we have the example app moving forward I'd like to bring this back as a P2 suggestion for this sprint (Jan 30). One additional goal I'd like to suggest here is getting Optimizely working correctly at least for our splash page and top level navigation.

/cc @simonwex

**Comment by OpenMatt** [comment]
@thisandagain should we add a "needs dev" label to this one?

**Comment by cassiemc** [comment]
Very excited to see this moving foward this heartbeat. As far as a living style guide, I see that being another adjustment to MakerStrap, which we can point to instead of the design handbook (point taken). Is that what this ticket is mainly about? Let me know how I can help with design, if that's needed.

**Comment by thisandagain** [comment]
@simonwex to jump in a redirect this towards a smaller scope of work that is focused on reducing debt. This issue will likely be re-cycled a few times until we get this under control but updating makerstrap / style-guides isn't a huge priority until branding is moving.

**Comment by OpenMatt** [comment]
* question: do we still think this is a good thing to prioritize this Heartbeat? (given MWC work etc.)
* If so, need to fill in the RACI

**Comment by thisandagain** [comment]
Moving to after MWC

**Comment by simonwex** [comment]
I'm thinking we should leave this as a P2 this HB and escalate it next if we don't get to it.

**Comment by thisandagain** [comment]
Sounds good. Thanks @simonwex

**Comment by thisandagain** [comment]
Lots of progress has been made on this in various different efforts over the past few weeks: login, testing, etc. As we are moving into the build phase for the next version of Webmaker, I propose we close this and follow-up with more granular tickets as needed.
