### ISSUE TITLE
Feedback on Webmaker browser tool

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#177]
Hello! We are testing a browser add-on idea for Webmaker and would love your feedback. 

**Problem**: People who like to re-share content cannot easily edit or make new things from the content they find on the web. They might not know it's possible, and even if they do, the tools can be difficult to access. 

**Solution**: This simple add-on will... 
 1. meet people at the moment they want to re-share an image,  
 1. give them simple edit options,
 1. connect with their usual social sites, and 
 1. offer a doorway to richer making in Webmaker. 

**Try it**:
 - Desktop: http://marvl.in/3e4jif
 - Mobile: http://marvl.in/26a1di (prototype works on desktop, better on mobile)

**Questions**:
 - Is this a good idea for learners? For mentors? Why?
 - Would you use this tool yourself? When and why? 
 - How could it be better? 
 - What tools do you currently use for quick image edits? Any you especially love? (add-ons or apps)

Thanks for the feedback!

cc @amirad @LucyeoH @thornet @keyboardkat @LauraHilliger @secretrobotron 

re: #123

**Comment by thisandagain** [comment]
Keeping design / dev / feedback consolidated to https://github.com/MozillaFoundation/plan/issues/124
