### ISSUE TITLE
BRANDING: Document roles & next steps for branding re: Webmaker / Mozilla Learning

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#179]
## Branding Phase 1: Congruency
From the meta plan here: https://github.com/MozillaFoundation/plan/issues/152

### Objective for this heartbeat
Gather all loose threads. Get the wider team on the same page and determine the scope of this branding exercise. Break into multiple branding exercises if necessary.

Ultimately, success will look like this: Webmaker/MoFo properties will have updated branding that is consistent and cohesive with wider Mozilla branding. Our branding (and accompanying documentation) is up-to-date, reflects an intuitive relationship amongst Mozilla initiatives, and is aesthetically and structurally forward-thinking.

## Phase 1: Congruency

Meet with consulted stakeholders to discuss how Webmaker fits in with wider Mozilla branding plans and identify the most imminent needs. This group will also identify team and owners. We will scope to individual brands and answer the questions:
* What is the right order for the Learning / Hives / Teach, Webmaker refresh, and Mozilla branding exercises. What can we do first?
* Does 'Learning' branding fall under MoFo domain (or MoCo's)
* Do Hive and teach.webmaker.org need additional, parallel branding work – or can that come at a later date?

**Deliverables:**
* Revised scope document (bug #152): answer Q re scope of work: Webmaker / Mozilla Learning / Teach.webmaker / Hives ?
* RACI for phases 2 & 3

**Suggested RACI:**
Phase: Research
Owner: @HPaulJohnson 
Consulted: maryellen, geoffrey, claw, @OpenMatt, Lainey 
Decision Maker: surman
Design Lead: @cassiemc
Development Lead: n/a
Quality Verifier: @thisandagain

**Comment by OpenMatt** [comment]
@cassiemc: can you title this ticket in a way that stands on its own as a headline? Let's clearly telegraph to casual readers that this Heartbeat is about clarifying roles and scoping the plan. 

* Gather and document the various threads. 
* Get the wider team on the same page and determine the scope of this branding exercise. 
* Break into multiple branding exercises if necessary.

Could be:
"Document roles, scope and next steps for branding around Webmaker / Mozilla Learning"

**Comment by cassiemc** [comment]
Thanks @OpenMatt , that wfm.

**Comment by cassiemc** [comment]
@HPaulJohnson Hey Paul, can you update us on what's happening with this? We haven't had our kickoff yet and it seems the meeting has been rescheduled twice. Are you having trouble wrangling everyone (if so, perhaps we could narrow the group or come up with another solution?) Wary about time dwindling away in this heartbeat.

**Comment by HPaulJohnson** [comment]
Sorry, @cassiemc. Some key participants are out sick so waiting to hear when they are back full force to join us. I'm hoping tomorrow or Friday but don't want to reschedule a 3rd time without being sure.

**Comment by cassiemc** [comment]
Ok, thanks for the update @HPaulJohnson!

**Comment by HPaulJohnson** [comment]
Thanks, all for a productive discussion on short/long-term branding needs and opportunities. Here's where we landed: 

- Assume that the product we are building to launch in Q2 is tightly defined as a "making" tool, then it continues to make sense to call it Webmaker. 
- For the learning network/teach, we still need to reconcile user's understanding and the relative value of Hive vs. Mozilla / Learning vs. Webmaker. We will conduct some fast, light-weight research to assess:

**Comment by thisandagain** [comment]
@HPaulJohnson can you create ticket(s) for the next phase of this?

**Comment by HPaulJohnson** [comment]
Inspired by @davidascher email today, realized I'm long over due for an update on this one. Also adjusting to fit work of this nature into the sprint format. 

Main update is that I had a long chat with Mary Ellen this week about overall brand architecture and in particular reconciling branding our Learning Network program(s). She is going to help co-lead a process to sort this out with me. 

We are going to break it out into two parts: an opportunity analysis for integrating or at the very least more closely aligning Webmaker product with Firefox brand. I've started some research for that and should have a better update in the next week. Mary Ellen is going to tackle, with tight collaboration from us, the programmatic learning piece and how it aligns with Mozilla branding efforts. "Learn" is one of the central value propositions for the Mozilla branding she is building for and she is highly engaged in helping us figure out the best brand positioning for us and for the larger brand. In terms of deliverables on this, she is on PTO next week and we are reconnecting week of 2/9; expect a more comprehensive update then. 

In the mean time, starting a ticket on a Webmaker focused messaging experiment Adam and I are designing to take the next step in honing our maker/learner focused messaging (building off testing we did on splash page project). 

Happy to field any questions/concerns in this ticket or with a quick check-in next week if people would like.

**Comment by cassiemc** [comment]
I'm updating the milestone for this so we can discuss in today's TPS.

**Comment by cassiemc** [comment]
@HPaulJohnson I'm leaning toward closing this issue and moving forward with #209 and #238

**Comment by HPaulJohnson** [comment]
@cassiemc makes sense to me - i'll know where to put updates next time where people are actually looking. as owner, i think you have to close it.

**Comment by OpenMatt** [comment]
@cassiemc  can you close this one?

**Comment by cassiemc** [comment]
Weirdly enough I think it's already closed. But let's be clear. 

>>> THIS TICKET IS CLOSED <<<< :)
