### ISSUE TITLE
Conduct user research on a new IA for teach.wmkr.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#180]
This is a child ticket of #11, which is the meta bug for the launch of a stand-alone teach.webmaker.org site to house all teaching/mentor content and features.

Relevant background: in #143, we're developing an interim solution by porting all teaching/mentor content to a sub-section of Webmaker.org. Eventually, all of that content will live on its own in a staff-editable CMS.

The scope of this ticket is to design some possible IA variations and test them in a lightweight way.
We can start from this: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1teLmdRnCz4if8raCAnyVIp0IbBqelOG70WcpXDQ1Sxk/edit#gid=0

Outcomes may include:
 * design and execute a user test (card sorting?) to understand users' mental models and test IA variations
 * start building personas specifically for the Learning Networks mentors (if those don't already exist - @cassiemc, do we already have personas specifically for mentors?)

**Comment by LauraHilliger** [comment]
Hmm I see 
* Teaching Resources
* Professional Development
* Clubs
* Badges
* Get Involved
as top tier. But I wonder if we should have a discussion about organizing teach.wm.org around the stuff in the [requirements doc] (https://teach.etherpad.mozilla.org/requirements)

Namely:
* Home (our global story, CTAs, social activity)
* Community (local stories, groups, personal and organizational profiles)
* Events (including MP and Mozfest)
* Resources (curriculum, assets, badges)
* Training (portal to online/offline professional development)

Just brainstorming here...

**Comment by hannahkane** [comment]
Hey @iamjessklein and @LauraHilliger — the items in the spreadsheet were used for the interim solution that launched yesterday. 

This ticket is for conducting some user research to determine a more long-term solution. I'd love to do a card sorting activity with end users in order to better understand their mental models for organizing information, which may line up with how we organize internally, but may not.

Started drafting a methodology here: https://docs.google.com/a/mozillafoundation.org/document/d/1rv-bxkLdHo7McSnDjyfeL7x30jxDPtwbfTrEjqb_XbY/edit

Would welcome feedback, though I don't think this is a p1 for anyone but me. :)

**Comment by hannahkane** [comment]
Renaming this ticket. Name didn't match the scope I was thinking.

**Comment by hannahkane** [comment]
User research project is underway. Starting to collect participant responses here: http://mzl.la/1Blyf8v, but will hold off on any analysis until more responses come in.

/cc @ldecoursy @LauraHilliger @iamjessklein

**Comment by OpenMatt** [comment]
@hannahkane: moving this to Jan 30 milestone, as it seems like the work is ongoing

**Comment by hannahkane** [comment]
Actually, I think we can close this one. #214 captures the next phase of this work.
