### ISSUE TITLE
APP: UX / UI improvements for field testing

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#182]
Clear UX & UI issues from [backlog](https://github.com/mozilla/webmaker-app/issues) for field testing in India.

Phase: QA / Build / Ship
Owner: @k88hudson 
Decision: @thisandagain 
Lead design: n/a
Lead dev: @gesa 
Quality: @thisandagain
Dev: @alicoding 

* Edit by @k88hudson*
Tickets: https://github.com/mozilla/webmaker-app/milestones/UX%20/%20UI%20improvements%20for%20field%20testing

**Comment by k88hudson** [comment]
@gesa @alicoding the list of tickets is here, feel free to grab any you have time for.

Check out http://webmaker-mobile-guide.mofodev.net/get_started/README.html if you need help getting set up

**Comment by gesa** [comment]
Now that I'm set up and exploring webmaker app...

@k88hudson: how soon are we transitioning from Vue to React? Is there value in me taking the time to learn Vue (and webmaker app in general), and taking the time to close these issues, when we're about to re-do everything anyway?

**Comment by k88hudson** [comment]
@gesa I expect we'll start the conversation process in a month or less, so, perhaps not. If you *are* interested in doing one and have time this one should be pretty much css-only https://github.com/mozilla/webmaker-app/issues/670

**Comment by thisandagain** [comment]
Nice work on this ticket folks. The milestone is down to a single issue. :smile:
