### ISSUE TITLE
Add a partner page to webmaker.org

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#183]
## RACI

* Phase: Design / Build / Ship
* Owner: @secretrobotron
* Decision Maker: Lynn
* Design Lead: TBD 
* Development Lead: TBD 
* Quality Verifier: @cassiemc 

webmaker.org needs a ~~better~~ place to showcase our sponsors and partners. The ticker which scrolled through them in the footer was removed as per the last redesign.

* __Audience__: Principally, partners and supporters.
* __Success__: Any support we receive from another organization can be displayed and referenced for public visibility and contractual acknowledgements.
* __Vision__: The Maker Party partner page is a great example: https://party.webmaker.org/en-US/partners
* __MVP__: A page, linked from the footer of webmaker.org, which displays the logos and categories of support and partnership.
* __Risks__: Minimal build and maintenance effort.

**Comment by OpenMatt** [comment]
@secretrobotron: should we propose making this a P2 for Jan30 train?

**Comment by secretrobotron** [comment]
@OpenMatt yep! that's works fine.

**Comment by cassiemc** [comment]
This feels too big a scope for one heartbeat. Would recommend breaking it up into just wireframe or design. @secretrobotron

**Comment by davidascher** [comment]
@cassiemc really?  More than two weeks for a simple partner page?

**Comment by secretrobotron** [comment]
:+1: to what @davidascher said. Hoping we can just throw together something that's almost exactly the same as the maker party partner page. Just a list of icons with webmaker styling.

@cassiemc were you thinking something more complex?

**Comment by cassiemc** [comment]
"simple" is always a scary word. There is no wireframe, no content, or assets that I've seen. So to get all those things integrated and launched on the site with localization and analytics and copy review, yes, I'd say it's much more realistic to focus on getting the design finalized.

**Comment by cassiemc** [comment]
Besides, it's a p2.

**Comment by davidascher** [comment]
Analytics shouldn't take an hour.  I'm ok w/ localization happening at
whatever schedule that naturally happens, but I'm worried if we aren't able
to go through design + copy + implementation of a not-even-front-page
static page in a two-week sprint.

**Comment by cassiemc** [comment]
I'd emphasize we need an updated description that fleshes out what "better" means and what we're trying to accomplish with this new page. @secretrobotron can you help? If copy and assets can be gathered in a timely manner than I'm sure this is doable.

Assigning @vazquez as designer (p2 this heartbeat)

**Comment by secretrobotron** [comment]
Yeah, never mind that it says "better". I've removed it. We just need **a** place. Right now, all we've got is the one attached to Maker Party.

**Comment by secretrobotron** [comment]
I'm encouraging Lynn to join in here so she can help :). She still needs a github account.

**Comment by cassiemc** [comment]
Ah ok, we can work by email and help Lynn document it here, if that helps. A first draft of content / list of partners would be helpful.

**Comment by cassiemc** [comment]
Made a quick wireframe to help the discussion along & clarify scope of work.

![partners-wireframe](https://cloud.githubusercontent.com/assets/1186326/5809035/174f6bdc-a002-11e4-9a3e-b6be41db8361.jpg)

The Maker Party page, referenced in that image, has a TON of partners, so the grid design is not all that effective. It gives the feeling of being overwhelmed with partners, part of a crowd, rather than something special. 

An outstanding question is how many partners we need to list on the Webmaker partners page? If lots, do they all need logos, or would a text name and link be okay (as per the old footer)? 

Also, re a call to become a partner, do we need as many text paragraphs as are on the MakerParty page? Would love to simplify that copy, but will need feedback from Engagement.

Redpen is here: https://redpen.io/nr2d8a5de11aeb8b55 Would love thoughts @thisandagain @secretrobotron

**Comment by secretrobotron** [comment]
Scope things to discuss tomorrow:
- ground-game partnerships team: do they need to be consulted (hope: no, followup another heartbeat)?
- just a list of partners and some text to say why that's cool?
- "become a partner" in a different heartbeat?

**Comment by HPaulJohnson** [comment]
@secretrobotron would love to be in the loop and represent engagement team on this one.

**Comment by secretrobotron** [comment]
Cool. Thanks @HPaulJohnson . So far, Lynn has been my engagement team source, and, with her, I'm trying to keep the scope down. Just sent out a meeting invite for you two so we can hash out a plan specific to engagement, and then move into design & impl here.

**Comment by secretrobotron** [comment]
##### Header
Mozilla is proud to partner with many organizations to promote openness, innovation & opportunity on the web. These include....

##### List of partners
Canadian Internet Registration Authority http://www.cira.ca/
The Ford Foundation http://www.fordfoundation.org/
Google https://www.google.com/intl/en/about/
GSMA http://www.gsma.com/
The Helmsley Charitable Trust http://helmsleytrust.org/
The James Irvine Foundation https://www.irvine.org/
John S. and James L. Knight Foundation http://www.knightfoundation.org/
The John D. and Catherine T. MacArthur Foundationhttp://www.macfound.org/
Media Democracy Fund http://www.mediademocracyfund.org/
The Charles Stewart Mott Foundation http://www.mott.org/
The National Science Foundation http://www.nsf.gov/
The National Writing Project http://www.nwp.org/
The Office of the Privacy Commissioner of Canada https://www.priv.gc.ca/index_e.asp
Ontario Trillium Foundation http://otf.ca/
The Alfred P. Sloan Foundation http://www.sloan.org/
Telefonica http://www.telefonica.com

##### Scope
- just a list of partners w/ logos
- @HPaulJohnson will re-visit in future heartbeat to make a more engaging page for potential partners

**Comment by vazquez** [comment]
Are the logos available? Vector preferred

**Comment by secretrobotron** [comment]
@vazquez I'll collect them. Likely to have few vectors though.

**Comment by OpenMatt** [comment]
@secretrobotron are we planning to ship this this Heartbeat?

**Comment by secretrobotron** [comment]
@OpenMatt yes, I'm hoping to do just that. Need to scrape together logos from web sources, since we don't have a comprehensive supply.

**Comment by secretrobotron** [comment]
Logos acquired: https://s3.amazonaws.com/cubbyhole.robothaus.org/partner+logos/index.html

**Comment by edrushka** [comment]
Closing. Re-open if work is still ongoing.
