### ISSUE TITLE
Web Literacy Map needs an update to v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#184]
## Problem
Problem: The Web Literacy Map needs an update to v1.5

Details:  Initial testing (Q3/4 2014) around 'v2.0' through interviews, community survey, and community calls. Consensus that we move first to v1.5 and then v2.0 later in 2015.

Current status: asked Webmaker list for suitable time for community call http://doodle.com/nwknddmsdpubeine

Read more: http://bit.ly/weblitmapv2

Deadline: End of Q1 2015

Responsible: Doug Belshaw

### Audience
Mentors, teachers, partners, staff

### Success
Nine of the 10 Mozilla Manifesto principles link directly to the Web Literacy Map. We need to keep it fresh.

### Vision
See above: participation/contribution arc at http://bit.ly/weblitmapv2

#### MVP
MVP for Web Literacy Map v1.5 is a change to the text version (i.e. at /literacy). Ideally, need updated graphic as well ASAP. This could be an iteration of the current grid so wouldn't need lots of design time.

### Risks
Low risk as an already-established resource.

## Preparation Checklist

 - [x] Kickoff meeting scheduled.
 - [ ] Deadline and flexibility established.
 - [ ] Localization plan created.
 - [x] Milestones created.
 - [ ] Maintenance plan created.
 - [ ] Analytices plan created.
 - [x] Scope creep avoided.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier:

**Comment by thisandagain** [comment]
cc @hannahkane

**Comment by OpenMatt** [comment]
cc @thornet cc@ldecoursy

**Comment by OpenMatt** [comment]
oops: cc @ldecoursy

**Comment by ldecoursy** [comment]
Hi @dajbelshaw, do you need specific help (copy and/or design) to make this happen? Depending on timing, our team may be able to make some changes ourselves once teach.webmaker.org is ready (closer to end of Q1).

**Comment by dajbelshaw** [comment]
Hi @ldecoursy yes, we will do please. I've invited Sabrina and Matthew to the calls themselves to get their input from a design point of view. 

The feedback from the community (see http://bit.ly/1wVErUD) was that we need better contextualisation of where the Web Literacy Map fits in terms of the Mozilla mission, etc. 

Would be a great thing to launch with teach.webmaker.org. In this new GitHub system, what do I need to 'file' in terms of copy and design?

**Comment by hannahkane** [comment]
I'd love to start attending the calls and work with you to file the tickets, @dajbelshaw. Agreed it could be good to launch in conjunction with teach.w.o, but I don't have a very good sense of the scope/effort yet.

**Comment by dajbelshaw** [comment]
Cool, well happy to schedule a call to get you up-to-speed @hannahkane. Also, we'll be going through it on the first call next week. What would you prefer? :-)

**Comment by hannahkane** [comment]
I can wait for next week's call. Thanks, @dajbelshaw.

**Comment by hannahkane** [comment]
part of teach site build!
