### ISSUE TITLE
Ship first draft Product & Process Handbook

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#187]
The process and product concepts which drive webmaker need to be documented.

## RACI

* Phase: Write / Build / Ship
* Owner: @OpenMatt 
* Decision Maker: @davidascher 
* Design Lead: N/A
* Development Lead: @secretrobotron
* Consulted: @cassiemc, @LauraReynal, @thisandagain, @OpenMatt 
* Quality Verifier: @thisandagain

The process and product concepts which drive webmaker need to be documented.

### Audience
Staff (current/onboarding) and community who want to learn/copy.

### Success
People can learn about how webmaker gets built from a product and process perspective. It gets used to guide the thinking of other teams and is easily replicated to facilitate that guidance.

### Vision
The Engineering Handbook is a great example. It's easy for engineers inside and outside of MoFo to adhere to discussed and agreed-upon conventions.

#### MVP
Part of build.webmaker.org (or a link on it). A gitbook based on a repo, just like the engineering handbook.

### Risks
N/A

**Comment by cassiemc** [comment]
Related: https://github.com/MozillaFoundation/plan/issues/194

**Comment by OpenMatt** [comment]
* Updated the RACI on this to make me the owner and @davidascher the decision maker. 
* we'll use the new Webmaker GitBook David made to do this
* Comment here if that seems wrong.

**Comment by secretrobotron** [comment]
:+1: love it. Excited to use a gitbook here.

**Comment by secretrobotron** [comment]
http://book.webmaker.org/index.html

**Comment by OpenMatt** [comment]
Here's an updated Table of Contents: http://pad.webmaker.org/book

But I'm not sure how to implement it.

**Comment by OpenMatt** [comment]
Just submitted a change request to update the front page, using prose.io (which was amazing) 
@davidascher let me know if I did it right

**Comment by OpenMatt** [comment]
That worked. Updating images with sparkleshare is not quite working for me yet.
@davidascher : I get this:
https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/f2hhrq6-.png
* I wonder if I don't have the right permissions set for that repo?

**Comment by davidascher** [comment]
@openmatt for TOC look at SUMMARY.md and let me know if that doesn't make
sense.

**Comment by OpenMatt** [comment]
@hannahkane @ldecoursy here's how to edit these pages
http://prose.io/#MozillaFoundation/book.webmaker.org

**Comment by OpenMatt** [comment]
First draft is completed here: http://book.webmaker.org/
More work needed. But let's mark this done and file a new ticket for feedback + second draft.

**Comment by thisandagain** [comment]
Seeing lots of broken links (404s). Where do you want issues @OpenMatt ?

**Comment by OpenMatt** [comment]
@thisandagain: I'll fix this up tomorrow. Let me take a pass and update here before making you file bugs.

**Comment by davidascher** [comment]
And for the record bugs should go in the book.Webmaker.Org repo
