### ISSUE TITLE
WordPress workflow? Alternatives?

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/plan#188]
Excuse me for my loooooooooong post :cold_sweat: 

Currently many MoFo sites are built in WordPress:
eg. [Hive Learning Networks](http://hivelearningnetworks.org/), [Advocacy](https://advocacy.mozilla.org/), [MozFest](http://2014.mozillafestival.org/), [Fundraising](https://fundraising.mozilla.org/)... and more

### Current Workflow (definitely not optimal) ###
1. Fresh WordPress install
2. Create a theme and build everything in the theme code.  (ie., minimal or zero widget usage). Almost everything is built as part of Theme.  This means site content is coded as HTML **within** the template files. (ie, we are **not** pulling content from the database)
3. Create a Github repo to store the Theme code
4. Push Theme code to Github
5. ssh to server(staging/production) and do `git pull` there.
6. Push subsequent commits and repeat Step 5. 

**Pros**
- Easy for dev (that's me :open_mouth:) to deploy from local -> staging -> production via ssh & Git commands.
- Version controlled.

**Cons**
- Since everything is coded in PHP/JS/HTML/CSS and no widgets are being used, it makes site edits extremely frustrating for site admins(non-devs).
- Also very troublesome for devs who don't have WP set up locally or ssh access to server to make changes.
- This leaves me the **only** person who can make changes "easily".

### Solution? ###
- We could try widgetizing things as much as we can.  So our Theme code just does what a "theme" should do and site content gets created via WP widgets(either 3rd party ones or our own creation) and stored in production site database.
- The good part
  - This way site admins can make edits through WYSIWYG editors / widget settings and do not have to ask for dev help.  
- Concern: 
  - (1) it takes a lot more time to build a site like that (me no WP expert nor PHP pro :scream:)
  - (2) content syncing is hard (not sure how we can do it, do we db dump every time?)

### Alternatives? ###
- I heard Ghost is good and easy to use.  Wondering if it could be an alternative?
- Other suggestions?

Thoughts?

**Comment by mmmavis** [comment]
@simonwex

**Comment by thisandagain** [comment]
cc @hannahkane

**Comment by davidascher** [comment]
For a bunch of these sites, I expect a static site generator with embedded
disqus comments is likely just fine.  e.g. Jekyll, Octopress, … Combined
with a travis hook to publish on github commit, it means that simply making
a push of a markdown file can update the site.  It's also easy to setup
prose.io to make it possible for people to edit those files in a web
browser without having to learn git.  I'd be happy to show you next time
we're both in the office if you want @mmmavis

**Comment by cassiemc** [comment]
<3 that you're tackling this @mmmavis. Besides also addressing your pain, which is important, I would love to see how the solution to this problem can help streamline ux & design across mozilla properties. One mozilla ftw!

**Comment by toolness** [comment]
I personally really like using WordPress Admin as a backend for CMSes because it's both easy to use, fully-featured, *and* tons of non-devs are already quite familiar with it. What frustrates me more is WP front-end/theme work, since like Mavis and others I'm extremely rusty on my PHP.

For a pro-bono site I worked on, [lifeofthelaw.org](http://lifeofthelaw.org/), I wrote a node-based [front-end](https://github.com/toolness/lotl-site-prototype) that talked to a WordPress back-end using the excellent WordPress [JSON-API Plugin](https://wordpress.org/plugins/json-api/).

There were some pitfalls to this approach, but one particular advantage was that it allowed the site's content creators to continue using the same WP admin backend without needing to migrate data or learn how to use a new user interface.

**Comment by jbuck** [comment]
If we just need a way to edit content, https://prismic.io/ and then we can do whatever we want with the front-end?

**Comment by gesa** [comment]
+100 @davidascher's comment on Jekyll, Prose.io, and Travis. I've done this several times for clients and family members, it p much *always* ends with happy users.

**Comment by alicoding** [comment]
I would suggest https://ghost.org/ since they are open source and it's written in JavaScript. The benefit here is that it's really easy to use and it also supports multi-user. Writing a plugin or adding anything is just like using any other node npm's module, so nothing new to learn here.

**Comment by mmmavis** [comment]
Hey guys, thanks for the great feedback.  I'll have to do lots of research before I can start asking questions again.  If we can settle an improved system it will benefit our future projects a lot!!!  Fingers crossed!

For our existing WordPress sites, since we are kinda late to the game and have no resources to port everything to the *new* system... I'm gonna see how I can make use of this popular [WP plugin ACF](http://www.advancedcustomfields.com/) to make both site admins and my lives easier.  :pray:

**Comment by mmmavis** [comment]
@davidascher cool I will find you when I go to the office next week.
