### ISSUE TITLE
WEBMAKER: Improve webmaker signup emails

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#189]
## Problem
The emails users get when they sign up (and other activities on webmaker?) are old and unappealing.

### Audience
Learners, visitors, community.

### Success
People use the emails we send them to re-engage with webmaker in ways we can predict/test.

### Vision
Better emails. The emails one gets for the new login system might be a good example. They're colourful and their intent is obvious.

#### MVP
An improved sign-up email, with proper styling and current instructions and information.

### Risks
To avoid another situation where our emails feel outdated, perhaps we should add a few milestones to planning.

## Preparation Checklist

 - [ ] Kickoff meeting scheduled.
 - [ ] Deadline and flexibility established.
 - [ ] Localization plan created.
 - [ ] Milestones created.
 - [ ] Maintenance plan created.
 - [ ] Analytices plan created.
 - [x] Scope creep avoided.

## RACI

* Phase: Build / Design / Ship
* Owner: @secretrobotron
* Decision Maker: @HPaulJohnson 
* Design Lead: TBD
* Development Lead: TBD
* Consulted: @hannahkane, @edrushka 
* Quality Verifier: @thisandagain

**Comment by secretrobotron** [comment]
Would love to use the templates that @sabrinang is working on: https://redpen.io/qtc78342c819f42537

**Comment by HPaulJohnson** [comment]
Me too! Can webmaker emailer send HTML templates?

**Comment by secretrobotron** [comment]
@jbuck do you know what sends out webmaker welcome emails right now? Is it BSD?

**Comment by jbuck** [comment]
@secretrobotron yes, it's sawmill. Current email content can be found at https://github.com/mozilla/webmaker-mailroom .

**Comment by secretrobotron** [comment]
Thanks @jbuck . Should be alright to use HTML then, @HPaulJohnson .

**Comment by xmatthewx** [comment]
Is it worth thinking about how emails are queued and managed to make it easier for @HPaulJohnson to iterate and experiment?

**Comment by HPaulJohnson** [comment]
Yes @xmatthewx! That's what we want to get to. I think @Kellijk has this in mind when thinking about the eventual transition away from BSD.

**Comment by simonwex** [comment]
It's important to note that there are two different categories of emails we send, bulk emails and transactional emails. Bulk emails are those that we send based on our subscription lists, such as the Mitchell email for EOY fundraising. Transactional emails are those that we send based on user-actions through webmaker, such as sign-up.

We don't send any transactional emails through BSD or Exact Target.

I think the most productive first steps would be to:

* Separate the email templates from the webmaker-mailroom project
* Provide comprehensive documentation on which emails are sent when
* Provide some facility for previewing modifications to the templates
* Provide a mechanism for A/B testing of these emails
* Run some training for non-tech members to enable editing and coordinated testing of the emails by non-engineers

**Comment by davidascher** [comment]
I'd add

 * establish singular process for testing the HTML (HTML in email is not
like HTML in a web page, and different mail agents treat them very
differently).

**Comment by thisandagain** [comment]
Tracking in https://github.com/MozillaFoundation/plan/issues/242
