### ISSUE TITLE
Net Neutrality Campaign

### ISSUE THREAD

**Issue by DaveSteer** [MozillaFoundation/plan#191]
This has three pieces: updated web site, petition, call congress tool

### RACI
* Phase: Design / Build / Ship
* Driver: @edrushka (for site updates and petition) @simonwex (for call congress tool)
* Decision Maker: @valianttry 
* Consulted: @DaveSteer, @HPaulJohnson 
* Design Lead: @sabrinang (for site and petition) @cassiemc (for call congress)
* Development Lead: @mmmavis (for site and petition) @ScottDowne (for call congress)
* Quality Verifier: @DaveSteer 

Hi All -

We're ramping up a net neutrality advocacy campaign to launch on February 5th with inclusion in Snippets, social and other channels just as the FCC is likely to vote on rules late February (and the cable industry is already mounting its attack, alongside a new GOP led Congress). Mozillians have been fighting for strong net neutrality -- it's time to stand up and take net neutrality across the finish line. 

Beyond the policy state change goal, this advocacy effort serves an important brand and community engagement purpose. It creates an environment in which 
a) we can reinforce the value of Mozilla to the existing community (especially post EOY fundraising), 
b) we can grow our community of people interested in fighting to protect the Internet and 
c) we can grow adoption of our tools and programs by demonstrating our brand thought leadership.  

Here is the link to the project brief: https://docs.google.com/a/mozillafoundation.org/document/d/1IOjvypPZP2FHiItwyicsH3LKgqzc7SeTGo22MSJroSU/edit#

This will be a XFN MoCo/MoFo sprint, but hoping it will be fairly lightweight by using existing templates. I'll be scheduling a kickoff shortly to include: @HPaulJohnson, Andrea Wood, @Kellijk, @edrushka, and people from MoFo Policy, Engagement and Comms. Please let me know if others should be included.

Thanks!

**Comment by edrushka** [comment]
Here is the wiki for this work: https://wiki.mozilla.org/NN-Campaign

Studio Mofo is updating the petition https://bugzilla.mozilla.org/show_bug.cgi?id=1121783 and the advocacy website https://bugzilla.mozilla.org/show_bug.cgi?id=1121786

Oglivy is being contracted to do the rest of the design work.

**Comment by cassiemc** [comment]
This needs an owner and a fleshed out RACI. @DaveSteer / @OpenMatt - outline below if you want to take a stab at it.

@edrushka is this on @sabrinang's plate already or do we need Webmaker design resource for this?

### RACI
* Phase: Design / Build / Ship
* Owner:
* Decision Maker:
* Consulted:
* Design Lead:
* Development Lead: 
* Quality Verifier:

**Comment by edrushka** [comment]
removing needs dev and needs design labels, as Studio Mofo has that covered.

**Comment by cassiemc** [comment]
@erikad said in IRC that there are many pieces to this ticket. "@sabrinang is designing the petition (95% done) and the updates to the advocacy site. moco hired a firm (ogilvy) to do all other graphic design"

@DaveSteer are there any other design resources needed from MoFo?

**Comment by OpenMatt** [comment]
@edrushka : do we still need this ticket? Or can we close, given the more specific work is happening elsewhere?

**Comment by edrushka** [comment]
I don't see another meta ticket for the NN campaign in /plan so I think we should leave this open. Work is happening here:
Petition (currently in QA): https://bugzilla.mozilla.org/show_bug.cgi?id=1125438
Call Congress tool (currently in design phase): https://github.com/MozillaFoundation/movement-building/issues/10
Updating website (MVP is done, nice-to-haves are next): https://bugzilla.mozilla.org/show_bug.cgi?id=1121787

**Comment by OpenMatt** [comment]
Needs RACI

**Comment by OpenMatt** [comment]
@edrushka : can you clean up this ticket? As I understand it, this is a meta-ticket gathering three pieces of work:
* petition
* call congress tool
* an updated web site 

is that correct?

**Comment by edrushka** [comment]
No, there are many moving pieces to the NN campaign. 
I am PM of the petition and the website updates.
I don't know who is PM-ing the call congress tool.
Andrea is "owner" of all three.

**Comment by simonwex** [comment]
Updated RACI with username mentions.

**Comment by edrushka** [comment]
Update:
FCC made announcement today.
Petition is live here: https://sendto.mozilla.org/page/s/FCCvote-net-neutrality
Advocacy site has been updated with ^ petition: https://advocacy.mozilla.org/
Call congress tool build is being expedited here: https://github.com/MozillaFoundation/plan/issues/263

**Comment by edrushka** [comment]
Update:
Campaign launched last week with blogs, snippet, tiles, social channels, email to MoFos and more. 
Petition is performing well :) http://note.io/1y7JhZ3 
Call congress MVP is live https://call.mozilla.org/  but has not been pushed publicly yet. #263 
Comms plans for Feb 26th (day of the vote) are underway.

**Comment by OpenMatt** [comment]
@edrushka any data or early metrics we can share?

**Comment by OpenMatt** [comment]
Update from @edrushka :
* Call Congress tool: MVP is live.
* Advocacy site: Has been updated with Call Congress button
* Petition: Call Congress button will be added to Thank You page today
* Current work = Victory planning

**Comment by edrushka** [comment]
Yes, just got an update on the weekly standup: 
Current data: http://note.io/1L8N8yj 
Signatures: 147,000 (10K signatures per day)
100K signature just from the snippet
More details in this pad: https://etherpad.mozilla.org/nnadvocacyfeb2015campaignkickoff

**Comment by davidascher** [comment]
It's not clear to me what is left to do on this, esp. between now and the current milestone of Feb 27.

**Comment by edrushka** [comment]
To Do:
1) Link to the Call Congress tool from the petition thank you page.
Status: Design and build are ready. Awaiting @valianttry's signoff to push it live.
2) Respond to emerging requests for graphics, such as: https://bugzilla.mozilla.org/show_bug.cgi?id=1133828
Status: Sabrina can do these quickly but due to the rapidly evolving nature of this campaign, we don't always have warning about when these requests will come. 

The Victory planning, currently being scoped, will likely result in some additional action items for this team (design, copy etc.)

**Comment by edrushka** [comment]
Update: The FCC voted in our favour today. A joint MoFo-MoCo team put the victory plan into action, which included:
a blog on the Mozilla blog: https://blog.mozilla.org/blog/2015/02/26/a-major-victory-for-the-open-web-2/
a video by Mitchell: http://youtu.be/I-UPyuW5j9o
tons of outreach on social channels and via email: https://foundation.etherpad.mozilla.org/NN-victory-social
and more...

More than 9,000 people used the tool to make about 23,000 phone calls ahead of today's vote, while the petition drew in 300,000 signatures. Huge congrats to everyone that helped make this victory happen, especially @valianttry and @DaveSteer 

Closing this meta issue for now. Can refile individual tickets if further victory work is required.
