### ISSUE TITLE
Debrief EOY 2014 Project

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#192]
Debrief process should ship:

1. Specific recommendations for improving "rapid iteration" build-cycle (e.g. getting better as a team at executing a fast-moving, metrics-based campaign);
2.  Prioritization of the needs in [this document] (https://foundation.etherpad.mozilla.org/EOYFR-2015-Ideas). What are the things we can build during 2015 that will improve fundraising / advocacy infrastructure for the foundation?
3. Identify overlap between the things in (2) above and the plan to migrate away from our current CRM system.

Phase: Debrief
Owner: @valianttry
Lead design: N/A
Lead dev: @ScottDowne 
Quality: @simonwex

**Comment by valianttry** [comment]
Debrief process should ship:

1. Specific recommendations for improving "rapid iteration" build-cycle (e.g. getting better as a team at executing a fast-moving, metrics-based campaign);
2.  Prioritization of the needs in [this document] (https://foundation.etherpad.mozilla.org/EOYFR-2015-Ideas). What are the things we can build during 2015 that will improve fundraising / advocacy infrastructure for the foundation?
3. Identify overlap between the things in (2) above and the plan to migrate away from our current CRM system.

**Comment by valianttry** [comment]
For **1. Specific recommendations for improving "rapid iteration" build-cycle (e.g. getting better as a team at executing a fast-moving, metrics-based campaign)**:

... we are meeting on Tuesday as a team. Each person will be able to share their specific feedback on process using the agenda below:

What I think I did well (30-60 seconds)

What I think I could've done better (30-60 seconds)

What I think **we** did well (30-60 seconds)

What I think **we** could've done better (30-60 seconds)

Specific next steps I'd suggest (30-60 seconds)

**Comment by simonwex** [comment]
@ScottDowne can you add anything you'd like to add to this?
