### ISSUE TITLE
WEBMAKER: Direct logged-in users to a different splash page

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#193]
When users who have a webmaker account arrive at webmaker.org, they should be greeted with a splash page that caters to them as they already understand what webmaker is, and have likely already made something. This will be distinct from new users who are asked to create something and sign up.

Phase: Design / Build / Ship
Owner: @secretrobotron
Decision: @thisandagain 
Consulted: @edrushka, @HPaulJohnson 
Lead design: TBD
Lead dev: TBD
Quality: @cassiemc

**Comment by secretrobotron** [comment]
New strategy: point logged-in users at /explore.

**Comment by cassiemc** [comment]
+1
