### ISSUE TITLE
Document our label and milestone conventions

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#194]

**Comment by OpenMatt** [comment]
Part of this should include heartbeat milestones for the year:
* Jan16
* Jan30
* Feb13
* Feb27
* Mar13
* Mar27
* Apr10
* Apr24
* May8
* May22
* Jun5
* Jun19
* Jul3
* Jul17
* Jul31
* Aug14
* Aug28
* Sep11
* Sep25
* Oct9
* Oct23
* Nov6
* Nov20
* Dec4
* Dec18

@cassiemc

**Comment by cassiemc** [comment]
We should be using 'milestones' for those, no longer labels.

**Comment by OpenMatt** [comment]
+1. All of this should be documented and linked from build.webmaker.org next Heartbeat.

**Comment by k88hudson** [comment]
i like to prefix related labels and make them the same/shades of the same colour e.g. design with `design-` since it makes them easier to find in a list alphabetically (e.g. https://github.com/k88hudson/githubtraining/labels)

**Comment by cassiemc** [comment]
Nice point @k88hudson about color grouping. I'd hope the color groupings would be intuitive (and not too many colors) but we probably need that documented somewhere. I liked that you pointed out the 'assigned to contributor' label. We should be sure to incorporate knowledge of mozilla-wide conventions, like that, in addition to our team's bespoke needs.

**Comment by k88hudson** [comment]
also `help-wanted`, that's kind of the github community's convention for 'good first bug'

**Comment by k88hudson** [comment]
some projects have skill-related tags as well, such as `front-end`, `android`.

**Comment by OpenMatt** [comment]
If I understand correctly, we should be using "milestone" for our Heartbeats. Did I follow the right convention for that on this ticket, for example? "Jan30" in milestone?

**Comment by thisandagain** [comment]
@OpenMatt Yup! Thanks. Still need to move all the remaining tickets to milestones.

**Comment by thisandagain** [comment]
Tickets have been migrated to milestones and the date labels have been removed.

**Comment by cassiemc** [comment]
@OpenMatt assigning this to you as I think it'll be covered in your blog posts and documentation. We may want to move this out of the milestone and treat it as a more granular bug?

Here's a start:

### Webmaker process and planning labels
* `p1`: Initiatives that top priority during their associated milestone. They are expected to be completed within the heartbeat.
* `p2`: Initiatives during a milestone that are second priority. They are not expected to be completed within the heartbeat, but it would be AWESOME if they were.
* `needs-design`: This ticket needs to have a designer assigned to it. Designers can assign themselves, or @cassiemc will regularly triage issues with this label the first Monday of every heartbeat.
* `needs-dev`: This ticket needs to have a developer assigned to it. Developers can assign themselves, or @simonwex will regularly triage issues with this label the first Monday of every heartbeat.
* `process` – An issue directly related to how we work together in Github and/or across the org
* `engagement`, `teach`, `advocacy`, `desktop & tablet`, `badges`, `communication`, `metrics`, `mobile`: these labels are used to identify the teams associated with the work. There are other similar labels – `branding`, `makerfox`, `curriculum`, `localization` – that serve a similar purpose in identifying larger scopes of work, but that ultimately will be used less frequently.

### Mozilla conventions
* ???

### Github conventions
* `help-wanted` – the github community's convention for 'good first bug' – an invitation to contributors who would like to get started.

We may want to include 'helpful tips' around labels, such as Kate's tip about adding prefixes and color-grouping similar tasks, when to use a label vs. when to use a milestone, who has permission to add or delete labels, etc.

Also, being new to github, I have no idea what other Mozilla & Github conventions might be. @k88hudson @humphd @jbuck might be good resources here!

**Comment by simonwex** [comment]
Minor edit above: Developers can ~~assign themselves~~ comment if they have interest in working on specific effort

**Comment by cassiemc** [comment]
Oh, good point @simonwex I don't even know where that came from. Same for designers! I'll edit the comment.

**Comment by OpenMatt** [comment]
@simonwex @cassiemc @davidascher Question: are we using "help-wanted" as a way to flag bugs that are good first bugs for potential contributors?

**Comment by davidascher** [comment]
This would be a great thing to publish in http://book.webmaker.org/github_faq.html.

@cassiemc: I haven't seen us be very disciplined about it.  What I can offer is:
 * if we are more disciplined, it's easy to query those bugs and promote them e.g. in a page off of the 'get involved' link of build.webmaker.org.

**Comment by cassiemc** [comment]
+1, I like this.
