### ISSUE TITLE
We don't have enough Nilla wafers! (We need them for the Mentors)

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#195]
## Problem
We don't have enough Nilla wafers! (We need them for the Mentors)

### Audience
Mentors

### Success
Mentors are full of wafers

### Vision
80 boxes of them!

#### MVP
79 Boxes of wafers

### Risks
Wafers go stale

## Preparation Checklist

 - [ ] Kickoff meeting scheduled.
 - [ ] Deadline and flexibility established.
 - [ ] Localization plan created.
 - [ ] Milestones created.
 - [ ] Maintenance plan created.
 - [ ] Analytices plan created.
 - [x] Scope creep avoided.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier:

**Comment by thisandagain** [comment]
P1. :wink:

**Comment by secretrobotron** [comment]
Please note that there are, in fact, several types of Nilla wafers. Might need to A/B test across locales.
![](http://static.caloriecount.about.com/images/medium/nilla-wafers-mini-59330.jpg) ![](http://static.caloriecount.about.com/images/medium/nilla-wafers-59710.jpg) ![](http://ecx.images-amazon.com/images/I/51XTTC0AYEL._SY300_.jpg) ![](http://dollarstoremom.com/wp-content/uploads/2011/03/nilla-wafer-girls-420x280.jpg)

**Comment by ldecoursy** [comment]
I'm a nonfacetarian
