### ISSUE TITLE
ENGAGEMENT: Update footer in Private Eye activity page

### ISSUE THREAD

**Issue by iamjessklein** [MozillaFoundation/plan#196]
- [x] Add footer to https://webmaker.org/en-US/private-eye
- [x] Replace content of the Badge CTA to join CTA

[Join CTA](https://redpen.io/ex9929c3c4930738e8):
![red-pen-fdd832f4-978f-48ea-baaf-7f96921a4c24](https://cloud.githubusercontent.com/assets/535012/5711413/463571d8-9a78-11e4-93e9-723958a78513.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/MozillaFoundation/plan/issues/226
