### ISSUE TITLE
ENGAGEMENT: Add the promo content to the home 3 splash and to the new onboarding splash

### ISSUE THREAD

**Issue by iamjessklein** [MozillaFoundation/plan#197]
Add the ad to the home 3 splash and to the new onboarding splash. This will require implementing the following mockups:

[Desktop](https://redpen.io/mb7ff3e5c2effb91d8)
![privacysliver-ui-1](https://cloud.githubusercontent.com/assets/535012/5711493/0160f770-9a79-11e4-9e27-2e287a419080.png)

[Hover](https://redpen.io/mf54aecfeb200cba0d)
![privacysliver-ui-hover](https://cloud.githubusercontent.com/assets/535012/5711502/1726c8aa-9a79-11e4-97be-edd540484def.png)

[Mobile](https://redpen.io/hzfc1693eca3d1ffd0)
*requires animated gif
![privacysliver-mobile](https://cloud.githubusercontent.com/assets/535012/5711509/25055694-9a79-11e4-819d-3e26c481d607.png)

**Comment by davidascher** [comment]
The type of the "OUR VALUES" sections seems off.  1) ALL CAPS? 2) the type looks more vertically stretched than the rest of the page's copy.  Am I wrong @iamjessklein ?

**Comment by iamjessklein** [comment]
@davidascher that's correct - I mentioned in the redpen that I took a stretched screenshot. In fact, none of the styling or content in the "OUR VALUES" section should be modified. It should look as it currently does on Webmaker:

![screen shot 2015-01-12 at 5 08 22 pm](https://cloud.githubusercontent.com/assets/535012/5712134/b1330586-9a7d-11e4-992b-9c35164fca8d.png)

**Comment by davidascher** [comment]
Gotcha. Sorry, didn't see redpen comment.

**Comment by iamjessklein** [comment]
:+1:  thank's for maintaining typographic vigilance

**Comment by thisandagain** [comment]
Tracking in https://github.com/MozillaFoundation/plan/issues/226
