### ISSUE TITLE
Write Learning Pathways whitepaper

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#198]
## Problem
We need a follow-up to the [first Webmaker whitepaper](https://mozilla.github.io/webmaker-whitepaper/). This will be useful in support of grant writing. After consultation, we've decided to write it on Learning Pathways.

### Audience
This will be public on the web. We're aiming for it to be referenced in the academic literature, but mainly by partners and educators. The aim is to associate the Mozilla brand with innovation and learning through making and doing.

### Success
The whitepaper is of high quality and is referenced both internally and externally. We should discuss analytics to ensure we have numbers (which we don't have AFAIK with the first whitepaper)

### Vision
We (@smithisgeneric & @dajbelshaw) have made a start and asked for feedback: http://goo.gl/yB5FFB 

#### MVP
Google Docs version. FuzzyFox created a template for the first whitepaper that we'll use for this one as well. Once it's finished we'll transfer it to GitHub pages. We may need some design help for this.

### Risks
The whitepaper may reference assets that may not exist by the end of 2015 - e.g. http://discover.openbadges.org. We've asked for clarification on this.

## Preparation Checklist

 - [x] Kickoff meeting scheduled.
 - [x] Deadline and flexibility established.
 - [ ] Localization plan created.
 - [ ] Milestones created.
 - [ ] Maintenance plan created.
 - [ ] Analytics plan created.
 - [x] Scope creep avoided.

## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier:

**Comment by dajbelshaw** [comment]
Pinging @iamjessklein as a heads-up for potential design input on this whitepaper (esp. sections 3, 4, and 5!)

http://goo.gl/yB5FFB

**Comment by dajbelshaw** [comment]
Created repository for this. Will add milestones, issues etc. 

https://github.com/mozilla/learning-pathways-whitepaper

Development will continue in Google Doc, but we'll look to port it to this repo once done (as with the [WebLit whitepaper](http://github.com/mozilla/webmaker-whitepaper))

**Comment by iamjessklein** [comment]
:+1:  let's set up some time to talk about this when you are at a good place.

**Comment by dajbelshaw** [comment]
Thanks @iamjessklein! All of the issues are milestone-enabled so have added one to talk with you towards end of the month: https://github.com/mozilla/learning-pathways-whitepaper/issues/26

**Comment by iamjessklein** [comment]
:+1:

**Comment by ldecoursy** [comment]
Since this issue (for writing) doesn't require design or dev, closing this issue in the /plan repo.
