### ISSUE TITLE
Document when to use Github and when to use Bugzilla

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#199]
A question that people felt was unanswered after the github training.

cc/ @OpenMatt

**Comment by KathrynMeisner** [comment]
cc/ @KathrynMeisner

**Comment by davidascher** [comment]
BTW, @KathrynMeisner -- If you want, you can just hit "subscribe" in the
right column of an issue if you want to get updates on it.  Same effect as
adding yourself, except nobody else gets an email.

**Comment by cassiemc** [comment]
Oh, that's a good tip for me too @davidascher as I told @KathrynMeisner how to cc herself :+1:

**Comment by KathrynMeisner** [comment]
Ooooh good to know

--
Kathryn Meisner
Director, Hive Toronto <http://hivetoronto.org/>
@KathrynMeisner <https://twitter.com/kathrynmeisner>
@HiveToronto <https://twitter.com/hivetoronto>

**Comment by hannahkane** [comment]
I think we can close this now. Doesn't seem to be an outstanding question anymore.
