### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#2]
Re-design & implement user profile to focus on a user's "makes".

Phase: Design / Build / Ship
Owner: @secretrobotron 
Decision: @thisandagain
Lead design: TBD
Lead dev: TBD
Quality: @cassiemc

**Comment by davidascher** [comment]
I have no idea why I created this issue, it was likely just to test out the plan repo.  Should we close it?  @thisandagain ?

**Comment by thisandagain** [comment]
Yup!

**Comment by secretrobotron** [comment]
:white_circle: :whale: :money_with_wings: :astonished:
