### ISSUE TITLE
Where should general, non-project-related issues be filed?

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#200]
Unanswered question from the Github training:

What is the best process for filing evergreen projects that might have to do with engagement CRM or emails, even studio-mofo-esque tasks? 

Should each team (listed here: https://github.com/orgs/MozillaFoundation/teams) have its own general catchall repo to file issues against? (I lean toward Yes.) If so, who should create those repos?

I think in the meantime it is fine and good to use the Plan repo to file stuff like this until the process is worked out.

cc @OpenMatt

**Comment by davidascher** [comment]
Good question, I think the answer is up to how each team wants to work.  So
Studio MoFo currently has a process, and if they don't want to use github
issues, I don't think they should be forced to.

What we want to avoid is creating a place where people file issues and
nobody notices / cares / or where they're not wanted.
