### ISSUE TITLE
Mobile App Co-design Activity

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/plan#201]
I'm planning on doing something here in Toronto with a Hive-affiliated organization:

Target audience: teens or adults (depends on who can host)
Objective: use co-design, paper prototyping, design thinking exercises to build apps. Focus on solving for the needs of local communities, students, women, etc. – whatever use cases resonate with participants.

I was planning on using some techniques from https://dschool.stanford.edu/sandbox/groups/dresources/wiki/welcome/attachments/11df7/BootcampBootleg2010v2SLIM.pdf?sessionID=bae8cbd0ea857214816671fab19c3ba1353f1e78

Undecided about whether to ask participants to design for themselves, or present research from kenya/bangladesh and use empathy building exercises to solve for a few pre-defined problems/use-cases.

**Comment by k88hudson** [comment]
tbh I have pretty limited time to plan this out and I wanted to do this pretty informally, but happy to tie in any work/suggestions/resources/asks from @LauraReynal @thisandagain @cassiemc

**Comment by k88hudson** [comment]
cc @KathrynMeisner

**Comment by hannahkane** [comment]
I think we did this. Can someone verify - @LauraReynal ?
