### ISSUE TITLE
OAuth Permissions requested from Github login are too broad

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/plan#202]
I don't think it needs to read "All your information" and "read and write all public and private repos"

**Comment by k88hudson** [comment]
+1

**Comment by thisandagain** [comment]
:+1:

**Comment by davidascher** [comment]
I believe https://github.com/MozillaFoundation/plan/blob/master/app.js#L51
is the line that needs changing.

**Comment by cadecairos** [comment]
https://developer.github.com/v3/oauth/#scopes

if all we need is access to public info, we can leave scopes blank.
