### ISSUE TITLE
plan to implement 2-3 Hive Toronto privacy badges on Webmaker

### ISSUE THREAD

**Issue by smithisgeneric** [MozillaFoundation/plan#203]
I am looking for feedback on which 2-3 Hive Toronto privacy badges would be of most interest to implement on Webmaker for Feb. 21 for our Educators' Training event but also for reusabilty/remixability.  Here is what I am thinking:    

- Data Trail Timeline 
- IP Tracer 
- Coach (very possible to badge people who attend on Feb. 21 and acknowledge participation)

- Alternate = Anonymizer

The [index to draft curriculum is here] (https://docs.google.com/document/d/1nYVVyPKm9nLJwv9k65KnSy7XmVJouhiMX705ZzuCgI8/edit#) 
Feedback?  @dajbelshaw @KathrynMeisner @iamjessklein @toolness @keyboardkat @LauraHilliger

**Comment by dajbelshaw** [comment]
Not sure of the goals of the event, but I'd go for **Anonymizer** instead of IP Tracer *(esp. given latter is only at 80% completion)*

**Comment by smithisgeneric** [comment]
IP tracer will get done this week :)

**Comment by toolness** [comment]
Karen mentioned that the IP tracer is something kids get *really* excited about and I can kind of see why... I vote for IP tracing fun!!

**Comment by LauraHilliger** [comment]
Hmm I actually think the two that are applicable in multiple places are the Mobile and Coach badges. I like the idea of privacy in everyday life, and you know how I feel about recognizing mentorship :dancers:

**Comment by hannahkane** [comment]
Wondering if we can close this ticket, because it seems well-documented elsewhere. @smithisgeneric ?
