### ISSUE TITLE
Localization improvements & quality review for Webmaker App

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/plan#204]
While development has been moving quickly for the Webmaker App we've let our l10n efforts slip behind. The focus for this sprint is to do an audit on our l10n support across the app and file tickets / resolve as many issues as possible for our 4 target markets (listed below).

### Audience
All non-english users of the Webmaker App with a focus on:
- Bangladesh
- India
- Brazil
- Kenya

### Success
- Identifying areas of the app that are not localized or localized poorly
    - Missing strings
    - UI that is squished / un-even / etc
- Resolving gaps in localization
- Checking to make sure our l10n tooling / build process is correct

### RACI
* Phase: Design / Build
* Owner: @thisandagain
* Decision Maker: @thisandagain
* Design Lead: n/a
* Development Lead: @alicoding 
* Quality Verifier: @k88hudson  

### Milestone
https://github.com/mozilla/webmaker-app/milestones/Localization

**Comment by thisandagain** [comment]
Kickoff scheduled for tomorrow at 11am PST

**Comment by OpenMatt** [comment]
@thisandagain status?

**Comment by thisandagain** [comment]
Great progress by @alicoding . Still wrapping up localization for Swahili and Bangla (Bangladesh – India is complete) but that is happening async to the UI work for this next sprint. :smile: :+1:
