### ISSUE TITLE
Get the first Webmaker Club curriculum module ready for testing

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#205]
In order to test the curriculum we're [building over here](https://github.com/mozilla/webmaker-curriculum), we'll need:

* [ ] Agenda for Club Call on January 27th
* [ ] Finished Search session
* [ ] Invitation text for testers / people not in the call
* [x] [Questionnaire for Credibility](http://goo.gl/forms/gnrTJ3d2AW)
* [ ] [Questionnaire for Search](https://github.com/mozilla/webmaker-curriculum/issues/88)

cc/ @ldecoursy @thornet

**Comment by iamjessklein** [comment]
Is there a plan for outreach/recruiting people to test?

**Comment by ldecoursy** [comment]
We have a co-design cohort - webmaker mentors, hive members, maker party partners... So a group of those folks are willing and excited about helping test. Can pull together that list this week.

**Comment by LauraHilliger** [comment]
@ldecoursy list here, maybe just needs an update: https://wiki.mozilla.org/Webmaker/2015/Mentors/Clubs#Club_Creators

**Comment by ldecoursy** [comment]
Yes, that's an outdated list, and also there are specific people within that group who have noted they're willing to test the activities with learners. Will have that list final after all 1:1 interviews are completed.

**Comment by iamjessklein** [comment]
:+1:

**Comment by thornet** [comment]
Completed on Jan 23. http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/
