### ISSUE TITLE
Publish documentation on "Git Hub Issues for MoFos"

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#208]
* GOAL: summarize what was covered in the recent training
* Be more explicit about MoFo process. How *we* want to use Git Hub issues together going forward.
* Address the most frequently asked questions
* Force clarity and decisions around parts of our process that are fuzzy / undecided
* Work closely with Product Group + new Program Managers group to spread the warm light of order and harmony

**Comment by OpenMatt** [comment]
First draft is completed here: http://workopen.org/github_howto

**Comment by OpenMatt** [comment]
@simonwex: need your help with the CodeTree section. And in particular: suggested links / ways to use CodeTree to get a better view of all tickets assigned to you across repos, etc.

**Comment by OpenMatt** [comment]
Once this is done, we'll 
a) ship it as a blog post, but more importantly:
b) ship it to the "How we work" section of build.webmaker.org. As a permanent piece of documentation. It will iterate as we go.

**Comment by OpenMatt** [comment]
@edrushka: can you add links to Studio MoFo bugzilla intake, plus Ops intake, if you have it?

**Comment by edrushka** [comment]
Done...although our form is currently busted :( 
I don't have Ops intake.

**Comment by OpenMatt** [comment]
Cassie let's add to the draft here: http://workopen.org/github_howto

I'll move this from etherpad to a Git Hub page we can easily edit and revise / synch with build.wmkr as we go

**Comment by cassiemc** [comment]
@OpenMatt This might be helpful for you: http://www.ianbicking.org/blog/2014/03/use-github-issues-to-organize-a-project.html It is not the same process or conventions, but may cover some questions we haven't yet discovered.

**Comment by OpenMatt** [comment]
shipped to build.webmaker.org
