### ISSUE TITLE
Draft branding plan for Learning Products and Learning Networks

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#209]
Draft a Q1 / Q2 branding strategy and roadmap for our Learning Networks and Learning Products

### RACI
* Phase: Planning
* Owner: @HPaulJohnson  
* Decision-Maker: @HPaulJohnson  
* Design Lead: @iamjessklein (consult as needed)
* Development Lead: n/a
* Quality Verifier: Geoff McD

We a had a branding kick-off meeting. Key outcome was: Paul will own for next heartbeat or two. And will work to turn output from the stakeholder group into a branding plan / roadmap. To be completed by end of this heartbeat or next. And then shared with the group for further feedback.

**Comment by DaveSteer** [comment]
What is the scope of the branding plan? Is it for all Mozilla Foundation activities? Or is it limited to a certain pillar of activities? Would love to see an overview of the effort. Thanks!

**Comment by HPaulJohnson** [comment]
@DaveSteer the scope of this exercise, for now, is just our teach and learn programs and products. Happy to keep you in the loop regardless.

**Comment by DaveSteer** [comment]
Thanks for the 411, @HPaulJohnson. Given the scope, no need to keep me looped in, though will be interested to see where you land.

**Comment by cassiemc** [comment]
@HPaulJohnson Let me know if you need to consult re. design effort.

**Comment by OpenMatt** [comment]
@HPaulJohnson status?

**Comment by HPaulJohnson** [comment]
Left an update on Friday in the master ticket, #179

**Comment by cassiemc** [comment]
I added a RACI to the top, with Jess on this for design eye as needed (it's her p2). @OpenMatt @HPaulJohnson Can you guys flesh that out?

**Comment by OpenMatt** [comment]
* Updated the RACI above. I think @HPaulJohnson is both the driver and decision-maker for this one.
* I think Geoff is the quality verifier (Paul: update / edit as you see fit if that's wrong)

**Comment by OpenMatt** [comment]
(We have a few  other brand tickets -- I'm confused which one is the master.)
e.g. https://github.com/MozillaFoundation/plan/issues/179
https://github.com/MozillaFoundation/plan/issues/152

* @HPaulJohnson : **I'm treating this one as the master,** because it's expressly about *documenting a plan*. e.g., writing some stuff down. Which I think is what we need most. :) 
* Let's make sure we pay some formal attention to this one in next Heartbeat. Threads we need to connect:
1. Conversations about naming / branding in NY work week. 
2. Design work. e.g., on teach.webmaker.org

In particular: moving out of side-conversation mode and back into plenary / all stakeholder mode feels important.

**Comment by OpenMatt** [comment]
NOTE: @HPaulJohnson is the Driver on *all* branding questions. He'll make sure the various decision-makers are consulted, but Paul is the Single Voice of Truth on all questions of brand. To avoid chaos and miscommunication.

**Comment by OpenMatt** [comment]
@HPaulJohnson is there a document we can look at?

**Comment by HPaulJohnson** [comment]
Finalizing a presentation deck with Mary Ellen this week. Meeting scheduled for 2/23 to present. Based on feedback from that initial presentation will blog to document and present to a wider audience as needed.

**Comment by iamjessklein** [comment]
question: is this a plan for a plan or the plan itself @HPaulJohnson ?

**Comment by HPaulJohnson** [comment]
@iamjessklein v1 of the plan itself

**Comment by OpenMatt** [comment]
status of this one?

**Comment by HPaulJohnson** [comment]
The "big" meeting is finally happening tomorrow, 3/13, after many delays and reschedules. Objective is to present recommendations (MEM + PJ), solicit final feedback and gain consensus of branding plan. 

Assuming progress is made at this meeting should be able to formally document something for wide distribution as a next step.

**Comment by simonwex** [comment]
How'd it go?

**Comment by chrislarry33** [comment]
It went well. Paul has the most info and is on PTO.

**Comment by HPaulJohnson** [comment]
Productive discussion, mostly around branding architecture. Main objectives were: 

- Determine brand attribution for Webmaker software products 
- Determine brand attribution for Webmaker learning & teaching programs
- Create framework for consistent naming conventions

See MEM's deck here: https://docs.google.com/presentation/d/1bEXABUxVVQVOhRPtpvSTIn7MKYuyH7Nq8WwoIxu1XC4/edit#slide=id.g8dd60ced1_183

Where we landed was consistent with the approach we've been taking in Q1: 

- Webmaker = software/tools aimed at mass market of makers and learners
- Mozilla Learning = programs/networds aimed community of teachers and mentors. NOTE: naming here is generic at the moment and still subject to refinement. 

Next steps include: 

- Amplify Mozilla in all existing Webmaker and new Learning Network branding. Working with Cassie to get this incorporated into new designs for both Webmaker and Learning Networks.
- Explore naming for Mozilla Learning Networks and Clubs. We are moving forward with generic naming for now but will be conducting a brainstorm this week to explore alternate options ahead of public launch. 
-  Revisit FF for Makers use cases with more of a segmented lens; identify common "maker" personas and build use cases that solve their problems. Meeting with product team tomorrow to discuss next iterations of prototypes .
