### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#21]
Initial release of the Webmaker App to Google Play and Firefox Marketplace stores.

Phase: Design / Build / Ship
Owner: @thisandagain
Decision: @davidascher 
Lead design: TBD
Lead dev: TBD
Quality: @cassiemc

**Comment by cassiemc** [comment]
More details about what design work is needed here, since @vazquez is on PTO this week?

**Comment by cassiemc** [comment]
As discussed w/ @xmatthewx, @flukeout and I can support design work that is needed this week until @vazquez's return from PTO.

**Comment by OpenMatt** [comment]
@thisandagain should we just close this bug?

**Comment by xmatthewx** [comment]
Closing. Tracking progress toward 1.0 in #443
