### ISSUE TITLE
Give Matt the ability to add and edit labels and milestones

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#210]
How do I do that? Do you need to change my permissions?

**Comment by davidascher** [comment]
Probably worth using this opportunity to review the team rights and memberships.

**Comment by davidascher** [comment]
issue was that you need admin rights to mess w/ labels, which seems like a
real limitation.  Gave admin rights to @TPS group, though so this should
solve this particular issue.

closes #210

**Comment by OpenMatt** [comment]
Hi, @davidascher -- I'm still not sure how to add new labels. It might just be a GitHub fail on my part. But still can't seem to do this for Plan repo tickets.

**Comment by davidascher** [comment]
@OpenMatt: Can you get to https://github.com/MozillaFoundation/plan/labels
? is there a New Label green button?

**Comment by OpenMatt** [comment]
ah yes! thanks david. sorted.
