### ISSUE TITLE
Document our Q1 / Q2 plan for Training

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#212]
### RACI
* Owner: @ldecoursy 
* Decision Maker: @thornet 
* Quality Verifier: @amirad 

GOAL: Need to plan for how [current training platform] (http://training.webmakerprototypes.org/) aligns with larger vision for clubs / local organizing / badges. Also identify roles.

Also see [https://github.com/mozilla/school-of-webmaking/issues/239#issuecomment-70118163]

**Comment by LauraHilliger** [comment]
Personally, I think we can find creative ways* to integrate training aspects across the teach site, and the online mentoring model is a part of that. Will look forward to working with @hannahkane on those big pieces!

In the meantime, I've put together this etherpad which might jump start the conversation. 
https://teach.etherpad.mozilla.org/training-redux

* [This likely won't work anymore](https://docs.google.com/a/mozillafoundation.org/document/d/1DQzHLAHjQ42o8hSeifhOuajYjC56Uzr-9e7_zeIyCnk/edit#heading=h.zb9fufcxfc53), but by "integrated training" I mean matching training content with other types of content so people can level up as the are consuming curriculum.

**Comment by ldecoursy** [comment]
Call set up for Tuesday 1/27

- [x] Identify core decisions/key questions regarding what we need
- [x] Begin aligning current training/PD offerings we already have
- [x] Scope what we need to build

Part of this can be prep for our NYC sprint in early Feb.

**Comment by ldecoursy** [comment]
@amirad @thornet and @KathrynMeisner met for initial discussion on 1/27. Next step is for @amirad to put together a proposal for how we can best integrate training around clubs, TTW Talks and email outreach. Then meeting for workweek Feb. 9 to make key decisions and identify what's still needed to build.

**Comment by OpenMatt** [comment]
@ldecoursy so will this plan be written / done by end of this Heartbeat (Feb 13?)

**Comment by ldecoursy** [comment]
@OpenMatt That is the goal! Per above comment, should be answering some key q's around this during our workweek.

**Comment by amirad** [comment]
Notes from last meeting in our pad: https://teach.etherpad.mozilla.org/trainingQ1Q2 
Will be revisiting and flushing out plan during Brooklyn workweek. I've added it to line 267 in the agenda pad https://teach.etherpad.mozilla.org/brooklyn

**Comment by ldecoursy** [comment]
Moving this to next train - want to allow time for synthesis of notes/plans following meetings in Brooklyn and upon @amirad 's return from PTO.

**Comment by OpenMatt** [comment]
@ldecoursy is on vacation til Monday. So this will need a new driver. 
* @amirad @thornet: anything to report from NY work week? Should we keep working on this, or punt to next Heartbeat?

**Comment by thornet** [comment]
Updated plans in progress: https://teach.etherpad.mozilla.org/brooklyn

**Comment by ldecoursy** [comment]
@thornet @amirad @ldecoursy to connect when Amira's back from MWC to synchronize above with https://teach.etherpad.mozilla.org/mentordev2015

**Comment by LauraHilliger** [comment]
happy to participate if you like.

**Comment by thornet** [comment]
Meeting on Wed. to look at team's roadmap and refining this ticket based on that.

**Comment by ldecoursy** [comment]
Closing this ticket, as plans re: training are being fleshed out as part of updated Clubs roadmap https://github.com/MozillaFoundation/plan/issues/364
