### ISSUE TITLE
Plan a triage plan for "plan" issues... :P

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#213]
Some feedback from the Github training – a question arose as to how general issues (normally filed on the Plan repo if using the intake form from build.webmaker.org) get triaged. What's the best way to make sure issues are not-lost?

We've been doing a bit of this during TPS, but we may need to have a better process for this going forward as the # of issues grows, esp. if we want to encourage more contributors to file issues.

Simply best to incorporate this into the regular Wednesday bug triage meetings?

cc @davidascher @thisandagain @simonwex @OpenMatt @Pomax @alicoding @jbuck 
Feel free to update the issue name for greater comprehensibility :)

**Comment by alicoding** [comment]
We'll probably need one more Bugzilla Triage and then we are done there, so I think we can use that time slot to triage issue here instead :)
