### ISSUE TITLE
Design & test teach.webmaker.org wireframes 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#214]
Let's make use of the user research project (being tracked here: http://mzl.la/1IP6chM) to do a first round of IA wireframes, and get them in front of some users for testing.

Context: v1 of the teach.webmaker.org site is where we will house (or link to) all of our resources and programs for teaching the web. It is meant to replace the Teach tab of the main Webmaker site.

(Note: I'm using the needs-design label, but it's more like, "needs-UX." I don't think we need to do any UI design yet.)

**Comment by cassiemc** [comment]
Needs a RACI. Some suggested roles:

### RACI ###
Phase: Design / Build / Ship
Owner: @hannahkane 
Decision: 
Consulted: ?
Lead design: @xmatthewx
Lead dev: n/a
Quality: @thisandagain 

Assigning @xmatthewx for design, though I wonder if we should make this a p2 given there are a lot of 'teach' planning and roadmap tix this sprint as p1s. Thoughts @hannahkane @OpenMatt @thisandagain ?

**Comment by hannahkane** [comment]
Yay! Excited to have @xmatthewx working on this. I'll set up a meeting for us. 

Thanks, @cassiemc, for the RACI suggestions. I'd add this:

**RACI**

Phase: Design / Build / Ship
Owner: @hannahkane
Decision: @claw
Consulted: @ldecoursy @thornet 
Lead design: @xmatthewx
Lead dev: n/a
Quality: @thisandagain 

Re: the priority—most of the 'teach' tickets in this milestone don't require the product, engineering, or design teams, so I was assuming we could have more p1s without violating the "one p1" rule for engineers and designers.

**Comment by xmatthewx** [comment]
@hannahkane - I did a first pass on IA. Some questions and more whittling required. If you do your own independently, we can compare and contrast. https://mw.etherpad.mozilla.org/teachdot

**Comment by hannahkane** [comment]
@xmatthewx - love this! Just sent a calendar invite to you and @ldecoursy for Monday to discuss next steps.

**Comment by hannahkane** [comment]
Update: 

@xmatthewx will build a wireframe based on https://mw.etherpad.mozilla.org/teachdot ( @thornet - any comments before he starts?)

@ldecoursy and I will work on scheduling some live (via Skype) user tests to run during the next heartbeat. The beginning of the test plan is sketched out at the bottom of https://mw.etherpad.mozilla.org/teachdot

/cc @cassiemc and @iamjessklein for any feedback on or ideas about the user testing process. Thx!

**Comment by hannahkane** [comment]
Started sketching out a testing script here: https://etherpad.mozilla.org/teachdotusertest

@xmatthewx and @ldecoursy — can you please take a look?

**Comment by xmatthewx** [comment]
[IA Mockups on Redpen](https://redpen.io/p/tcd5fbcae44ba63df9). There's a lot of info to wrangle, so this will likely need some iteration. 

High level feedback on how the parts are organized and labeled will be the most useful thing at this stage. Smaller details will shift based on those decision.

**Comment by xmatthewx** [comment]
Curious how we want to mark this as a subdomain of Webmaker. Feedback and other ideas would be helpful. 

![subdomain](https://cloud.githubusercontent.com/assets/53411/5961854/6b0946aa-a7ad-11e4-9bb1-821ead3f3d19.png)

cc @HPaulJohnson

**Comment by xmatthewx** [comment]
I posted two clickable versions. Identical beyond the nav and logo treatment. 
 - http://marvl.in/b0ah39
 - http://marvl.in/11ji896

Ping me with any problems that will interfere with IA testing.

**Comment by hannahkane** [comment]
@xmatthewx - these are perfect. I'll send you invites for the user tests in case you want to join in.

**Comment by hannahkane** [comment]
Closing this. The design is done for now. Testing will happen next heartbeat.
