### ISSUE TITLE
Finalize documentation for Badges / Credentialing 2.0 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#215]
Current doc is here: http://mzl.la/1AxcmUq

Acceptance criteria:  
 * document stakeholders and decision-makers on wiki   
 * hold a kick-off meeting w. decision makers
 * resolve all issues on document; reach shared understanding
 * Badges v1.1 tickets are ready for the next heartbeat(s)

blocked on: no consensus on stakeholders/decision-makers. Will ask Claw to designate.

**Comment by benrito** [comment]
The link appears to be Doug Belshaw's Spotify playlist. A good a plan for credentialing as any ;)

Real link?

Please consider including me in the kickoff meeting, would love to participate if there aren't already too many cooks (which is possible).

**Comment by hannahkane** [comment]
That is amazing, and feels impossible. Correct link:  http://mzl.la/1AxcmUq

Ben, you and An-Me will be invited to represent partnerships.

**Comment by thisandagain** [comment]
ROFL :laughing:

**Comment by dajbelshaw** [comment]
I vote we just go with my playlist. ;-)

Apologies - that was almost certainly a copy/paste error on my part (into bit.ly)

**Comment by OpenMatt** [comment]
hilarious. @hannahkane: note that you can edit comments. I just updated the link above.

**Comment by OpenMatt** [comment]
@hannahkane : status? 
(+ please update these plan tickets more frequently)

**Comment by hannahkane** [comment]
This is not done. One group conversation happened, but not all stakeholders were able to attend, so we weren't able to make final decisions. 

Plan is to publish a blog entry this week with the latest thinking and allow for a round of feedback. This is likely an ongoing, evolving project—not necessarily something that can be completed inside of a heartbeat.

**Comment by OpenMatt** [comment]
k. please update to next train when this happens.

**Comment by hannahkane** [comment]
Update: will post blog entry tomorrow + update https://wiki.mozilla.org/Webmaker/Badges

**Comment by hannahkane** [comment]
Wiki is udpated: https://wiki.mozilla.org/Webmaker/Badges

Work is inherently ongoing, but I'm closing this ticket.
