### ISSUE TITLE
Ship updated documentation and TOC to book.webmaker.org

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#225]
For how we do Heartbeats, documentation on Git Hub issues, and engineering and design handbook. 
To the new build.webmaker.org "how we work" section

### RACI
* Phase: 
* Owner: Matt
* Decision Maker: @davidascher 
* Design Lead: (not needed)
* Development Lead: (not needed) 
* Quality Verifier: ???

* We can link from build.webmaker.org to this: http://book.webmaker.org/
* Emphasis on:  http://book.webmaker.org/heartbeat_faq.html
* Repo:  https://github.com/MozillaFoundation/book.webmaker.org/issues

**Comment by OpenMatt** [comment]
@secretrobotron hoping you can help me with this :)

**Comment by secretrobotron** [comment]
Sure can :).

**Comment by OpenMatt** [comment]
@secretrobotron: let's schedule a project kick-off on this for tomorrow.

**Comment by OpenMatt** [comment]
@jdotpz Bobby and I had some notes here: http://pad.webmaker.org/p/Product_Handbook

did pad.webmaker.org data get wiped?

**Comment by jdotpz** [comment]
Oh dude, we were not supposed to be storing things there while we were in demo/install/test mode.  Yes, it got mega wiped, and is bound to do so again.  I'm super sorry, and there's not a thing I can do to restore it, because it was in dirtydb mode.  :/
Sorry!!!
![wiped](https://cloud.githubusercontent.com/assets/1373628/5845616/150e36dc-a183-11e4-9aee-7930dcb975ed.gif)

**Comment by OpenMatt** [comment]
np! my bad. Sorry Bobby. but there was nothing in there that was mission critical. We can just carry on.

**Comment by OpenMatt** [comment]
@secretrobotron Here's what I'd propose for next steps on this.

1) Ship the documentation on "How we do Heartbeats" to build.wmkr. As our first test-case for how we want the process / updated IA etc. to work.
2) To that end, here's cleaned up copy & HTML for that doc: http://openmatt.org/heartbeats/
3) Can we ship this to "build.webmaker.org/how/heartbeats"? 
4) With a clear link / instructions on the page for how to edit / update it as we go? e.g., by submitting a pull request / editing a Git Hub wiki / whatever you think is easiest / best?

**Comment by secretrobotron** [comment]
@iamjessklein on design review: http://jessicaklein.blogspot.com/2015/01/quality-assurance-reviews-for-design_27.html

**Comment by OpenMatt** [comment]
* We can link from build.webmaker.org to this: http://book.webmaker.org/
* Emphasis on:  http://book.webmaker.org/heartbeat_faq.html
* Repo:  https://github.com/MozillaFoundation/book.webmaker.org/issues

**Comment by OpenMatt** [comment]
this is a duplicate of 
https://github.com/MozillaFoundation/plan/issues/225

so closing
