### ISSUE TITLE
Prep and execute Data Privacy Day campaign (Jan 28)

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#226]
* This is a follow-up to the work we did last Heartbeat. https://github.com/MozillaFoundation/plan/issues/175
* Seems like a communications plan & punch-list would be helpful. So that we can write and assign specific tasks for teams and individuals
* Engagement campaign, TTW call, Twitter chat, etc. Co-ordinating the various pieces.
* @HPaulJohnson: does that exist somewhere?

### RACI
Phase: Refine / Deploy
Owner: @HPaulJohnson
Decision Maker: @HPaulJohnson

**Comment by HPaulJohnson** [comment]
Content and plan being finalized today and I'll put together an overview for distribution early next week.

**Comment by thisandagain** [comment]
UI and execution needs QA prior to launch:
http://sleepy-ravine-9799.herokuapp.com/en-US/home-3

/cc @cassiemc @gesa @iamjessklein

**Comment by cassiemc** [comment]
@OpenMatt This ticket needs a RACI. 

I'm happy to help with quality on this if needed. Assigning @iamjessklein for any other design support.

**Comment by thisandagain** [comment]
Proposed RACI above.
/cc @HPaulJohnson @OpenMatt

**Comment by OpenMatt** [comment]
* We need some clarification on this ticket.
* Seems to me we have two distinct pieces of work here (each of which should be ticketed separately):

**1) Finish up & ship the production work.** Some design & front-end tweaks to get the execution looking great. Then push it to staging / prod when ready. (requires: design / light front-end dev) 

**2) Document & execute a communications plan.** How we're going to execute the campaign. A to-do list with talking points, communications channels, and tasks. (requires: engagement team. assigning specific to do's to others, across teams)

**Comment by OpenMatt** [comment]
* I suggest we make this ticket about (2) 
* @thisandagain / @cassiemc: do you have a suggestion for where should we track (1)?

**Comment by simonwex** [comment]
I think we should create a new P2 bug for (1), and I'll do my best to have it completed in this HB. Otherwise we can P1 it next.

**Comment by thisandagain** [comment]
@simonwex Just note that the engagement folks have a hard launch deadline of the 28th for this thing (in prod on the evening of the 27th).

**Comment by HPaulJohnson** [comment]
Update on (2): Mary Ellen will be sending a campaign overview to all Mozilla soon and I will piggyback on that with a separate note to MoFo with more specifics about our piece of the plan. Should be later today or Monday.

**Comment by OpenMatt** [comment]
@HPaulJohnson can we close this? if so please do

**Comment by HPaulJohnson** [comment]
This can be closed. Github newbie question - how do I close a ticket if I'm not the owner?

**Comment by OpenMatt** [comment]
you don't see "close" button at bottom of ticket, next to "comment"?
