### ISSUE TITLE
Show where we are in a sprint

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#227]
For people not deeply involved in the heartbeat, it's not obvious what the actual deadlines are / where we are in the cycle.

**Comment by davidascher** [comment]
Also probably should lighty explain the heartbeat concept somewhere.

**Comment by thisandagain** [comment]
Agreed. I think we might even want to do that (explain sprint concept) right on the splash screen.

**Comment by cassiemc** [comment]
This no longer seems a priority.
