### ISSUE TITLE
Crisply document all MoFo Q1 goals and KPIs

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#228]
## Goal: put all our Q1 goals and KPIs in one spot ##
1 We'll start by staging them here: https://wiki.mozilla.org/Foundation/2015/Q1
2 Then we'll come up with a dynamic way to post them to build.webmaker.org
3 And work with @adamlofting and others to surface them through a dashboard 

### Notes ###
From kick-off meeting: https://etherpad.mozilla.org/Q1

### Deliverable for this Heartbeat ###
Get goals and milestones filled out on the wiki for:

### Mozilla Learning ###
- [ ] Learning Networks
- [ ] Learning Products
- [ ] Leadership Development

plus:
- [ ] Engagement
- [ ] Ops

### New Communities ###
- [ ] Open News
- [ ] Science Lab
- [ ] Advocacy

**Comment by k88hudson** [comment]
![crispy like bacon](http://33.media.tumblr.com/tumblr_lsitxlhSFC1r4994ho1_500.gif)

**Comment by thisandagain** [comment]
:laughing: :dancer:

**Comment by OpenMatt** [comment]
@thornet: hoping you can help with this for Learning Networks piece, working with Lainie and Hannah

**Comment by davidascher** [comment]
@OpenMatt I have some ideas -- let's chat =)

**Comment by OpenMatt** [comment]
* Will sched a project kick-off on this for Tues. 
* Recommended attendees: Program Managers (me, Hannah, Lainie, Drushka) + David, Michelle, Bobby + anyone else who wants to play (please chime in here) 
* Stub with some early random notes chucked into it here: https://wiki.mozilla.org/Foundation/2015/Q1

**Comment by OpenMatt** [comment]
@secretrobotron: adding you because I think this relates to some of the other work we're doing on build.webmaker.org this heartbeat. 
+ cc: @ldecoursy @hannahkane @thornet

**Comment by secretrobotron** [comment]
:+1:

**Comment by adamlofting** [comment]
I'll follow this closely, but don't let me be a blocker on scheduling the call if my timezone causes pain. 

:clock1: :clock2: :clock3: :clock4: :clock5: :clock6:

**Comment by OpenMatt** [comment]
* @adamlofting: we already had the kick-off meeting yesterday. (Should have invited you -- but forgot that you were back at work! apologies) 
* notes from the meeting are here: https://etherpad.mozilla.org/Q1
* pulling drafts together here. I worked on the Learning Networks portion a bit today as a potential template / test model:
https://wiki.mozilla.org/Foundation/2015/Q1#Learning_Networks
* curious to hear what you and others think of it.

**Comment by OpenMatt** [comment]
* got some feedback from @hannahkane on it today.
* curious to hear from @thornet @ldecoursy and @davidascher as well.

**Comment by OpenMatt** [comment]
* once we have one good example on that page, I'll invite others into to help flesh their's out as well.

**Comment by ldecoursy** [comment]
Thanks @OpenMatt! I updated this page last week https://wiki.mozilla.org/Webmaker/2015/Mentors and think we can pull some narrative from there if you think it's useful. Tomorrow I can help sync language re: people/cities as measures of success but also don't want to leave out that growth/goals are tied to providing value and empowering the community (that part seems missing from current draft).

**Comment by OpenMatt** [comment]
Thanks Lainie. So the main things we need to ensure are well represented are:
1) providing value 
2) empowering the community

**Comment by OpenMatt** [comment]
still working on this -- but doesn't need to be in Heartbeat process, as work is just on me to complete at this point.

**Comment by hannahkane** [comment]
Closing because it's so old
