### ISSUE TITLE
Finalize UI design & implement editor revisions

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#236]
From our field testing it's become clear that one of our weakest areas in the Webmaker.app is the editor. Thanks to @flukeout and @k88hudson we have some strong ideas and prototypes for how to improve the UX. This sprint is finalize the UI design and implement this new UX.

### Audience
All users of the Webmaker App

### Success
- Primary
    - UI design finalized (R+) by Thursday EOD
    - Updated design implemented and merged to master by end of sprint
- Secondary
    - Template updates as per last sprint
    - UX / UI tweaks as documented in the milestone

### Vision
https://github.com/mozilla/webmaker-app/issues/607

### RACI
* Phase: Design / Build
* Owner: @thisandagain
* Decision Maker: @thisandagain
* Design Lead: @vazquez 
* Development Lead: @gvn 
* Quality Verifier: @cassiemc 

### Milestone
https://github.com/mozilla/webmaker-app/milestones/UX%20Improvements%20(Phase%20II)

**Comment by cassiemc** [comment]
Edit: assigned @vazquez for design.

**Comment by simonwex** [comment]
So I understand correctly. This week is about design with someone from my team in the loop and then implementation next week?

**Comment by thisandagain** [comment]
This is about UI design from tomorrow (kickoff) to Thursday and then implementation of the updated editor from Friday - end of sprint. Quite a bit to chew off, but gives a few days for @gesa to get up to speed and much of the UX is already defined if we'd like to get started early.

**Comment by thisandagain** [comment]
Kickoff scheduled for 10:30am PST

**Comment by thisandagain** [comment]
Ricardo is tracking design here: https://redpen.io/bwb858f2a4b53017ac

**Comment by thisandagain** [comment]
Milestone updated and initial assignments should be all set. 
/cc @vazquez @gvn

**Comment by OpenMatt** [comment]
@thisandagain status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by thisandagain** [comment]
Editor revisions implemented, but not quite up to spec (see: https://github.com/mozilla/webmaker-app/milestones/UX%20Improvements%20(Phase%20II) ) moving remaining items to next heartbeat SOW.
