### ISSUE TITLE
Add retention and quarterly goals to dashboard

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#237]
To provide a good high-level picture of health for Webmaker we need to add retention to the dashboard. In addition, we should call out the four quarterly goals as per the 2015 plan and highlight them at the top of the dashboard.

### RACI
* Phase: Build
* Owner: @adamlofting 
* Decision Maker: @thisandagain 
* Design Lead: n/a
* Development Lead: @adamlofting 
* Dedicated Reviewer: @cadecairos 
* Quality Verifier: @davidascher 

### Audience
Staff, partners, and contributors to Webmaker

### Success
Staff and contributors have a single link (build.webmaker.org/dashboard) that they can use for daily tracking of Webmaker product KPIs and goals.

### Vision
- 7, 30, and 90-day active user retention figures are added to Geckoboard
- Q1 - Q4 goals with current status are added to Geckoboard

**Comment by thisandagain** [comment]
I'm not certain if we will need development support on this (cc @simonwex ). Will confirm with @adamlofting

**Comment by OpenMatt** [comment]
See also: https://github.com/MozillaFoundation/plan/issues/228
Where we'll be working to document some of these, pulling from the main 2015 plan.

**Comment by adamlofting** [comment]
I can do the development on this (it's well underway already) but I'd appreciate a code review if that's possible.

**Comment by simonwex** [comment]
@adamlofting, @cadecairos can do reviews for you. @cadecairos could you prioritize them as they come in over the heartbeat? If this isn't working for either of you, ping me and I'm happy to lend a hand.

**Comment by thisandagain** [comment]
Wonderful. Thanks folks. @adamlofting want to catch-up on the status of this during our 1:1 tomorrow?

**Comment by adamlofting** [comment]
@thisandagain yes, let's talk it through on our call.

Here's a link you can look at what we have now: https://webmaker-metrics.herokuapp.com

This is real data from the last 7 days, but the hosted app is not connected live to the webmaker integration db (it's all coded up but I need to move this hosted site into the mofosecure infrastructure before putting creds into the production version).

I'll get the repo moved into mozilla account ready for @cadecairos to look through, and I'll write up some notes about what it does and why to support this. Repo can currently be seen here: https://github.com/adamlofting/webmaker-metrics

---
Next I will:
* Move to mofosecure hosting with @jdotpz (there's a few things we need to configure here)
* Add in 90 day retention (I don't think we had this as a KPI yet but it's easy to add)
* Expose the bits of this we want for access by geckoboard

**Comment by cadecairos** [comment]
@adamlofting : send word when it's ready for a code review

**Comment by adamlofting** [comment]
@cadecairos thanks! :hatched_chick: 
I've filed a separate issue for tracking the review: https://github.com/mozilla/webmaker-metrics/issues/6

**Comment by adamlofting** [comment]
I'm just flagging that we probably won't ship this in the target :heartbeat: 

@jdotpz will need a bit more time for setting up the hosting, and is juggling a few other tasks at the same time.

**Comment by thisandagain** [comment]
Bummer. /cc @simonwex

**Comment by simonwex** [comment]
@jdotpz any idea how much effort this is?

**Comment by jdotpz** [comment]
Yes.  We need to setup a new puppet server, new jenkins server, a new controller server (for running of cron jobs), a new autoscaling group for Adam's kit.  This is a few days of effort, not two days.

**Comment by jdotpz** [comment]
I'd also point out that right now, we are not functionally limited by where this is hosted.  We don't want to run this way forever of course.

**Comment by OpenMatt** [comment]
@adamlofting status? please move to Feb13 train if this work is ongoing.

**Comment by adamlofting** [comment]
@OpenMatt yes, this is ongoing. But I don't have `train moving` power in this repo. 

Could you update the Milestone for me please (or my permissions, if that's better).

**Comment by adamlofting** [comment]
Thanks @cadecairos :smile:

**Comment by cadecairos** [comment]
:+1:

**Comment by thisandagain** [comment]
Moved to the next heartbeat and added @adamlofting as an admin. :smile:

**Comment by thisandagain** [comment]
@simonwex given the Call Congress and other activities do you think it is reasonable to get this shipped? If not, I'd rather re-classify this as a P2.

**Comment by simonwex** [comment]
@jdotpz could you explain why Adam's code needs to live in mofosecure?

**Comment by jdotpz** [comment]
It has access to all of the data, including some PII (email addresses, if they've signed up on specific forms/petitions), and we will likely be bringing payment info (no stripe data) into this integration database that Adam's code talks to.

**Comment by simonwex** [comment]
We hold email data outside of the mofosecure environment. Can we stand this up on our normal gear and transition in when (and if) we need to handle payment info?

**Comment by jdotpz** [comment]
That's not much different than the current setup, but sure.

**Comment by jdotpz** [comment]
Infrastructure is all setup.

**Comment by adamlofting** [comment]
We are live :boom: 
* [The public dashboard](https://mozillafoundation.geckoboard.com/dashboards/F62088172D822E2A) as linked from build.w.o now includes the KPIs
* This is [the metrics app](https://metrics.webmaker.org/) with some further graphs, and where the number crunching happens

:warning: The 7 day graphs for the retention metrics will need one week to settle. This is because retention is a tricky metric where `what happens in the future` changes `what we've measured to happen in the past`, and our data is not granular enough to backfill the daily snapshots fairly. [Notes on retention calculations are here](https://github.com/mozilla/webmaker-metrics#about-webmaker-retention-metrics).

FWIW, I don't like those Geckoboard custom line graphs for the 'Last 7 Days', so I will upgrade them to [custom highcharts](https://developer.geckoboard.com/#highcharts) at a later date, but I didn't want that to hold up getting the dashboard live.

To confirm before closing this ticket:
- [ ] @thisandagain Does this meet the requirements?
- [ ] @davidascher Does this pass the quality threshold?

**Comment by thisandagain** [comment]
Excellent. Thanks @adamlofting

**Comment by OpenMatt** [comment]
@davidascher : can you sign off so we can close?

**Comment by davidascher** [comment]
LGTM.
