### ISSUE TITLE
Align Webmaker & Mozilla Branding efforts

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#238]
MofoDesign needs to sync up again with @mart3ll to review Mozilla branding progress

### RACI
    Phase: Exploration
    Owner: @HPaulJohnson 
    Decision Maker: @ TBD
    Design Lead: @vazquez  
    Development Lead: n/a
    Quality Verifier: @cassiemc

MofoDesign needs to sync up again with @mart3ll to review Mozilla branding progress and ensure the direction still meshes with Webmaker branding. It's an opportunity to help define a Mozilla direction that is in line with Webmaker's goals.

This would include:
Review of current Mozilla branding progress 
Asset brainstorming + how those assets would be applied
High-level exploration of how new Mozilla branding might impact Webmaker

### Success ###
Deliverables include:
* Refined Mozilla color palette that includes dominant Webmaker colors
* Mozilla+Webmaker moodboard that includes a few background patterns and other adjusted style treatments
* Mockup of Webmaker.org landing page inline with new Mozilla branding

@HPaulJohnson, I don't see any blockers on this, do you? My only question on this would be around timing. Not sure what Moco's timelines look like or how pressing this is.

**Comment by cassiemc** [comment]
Assigning @flukeout for design (remember it is p2 this sprint)

**Comment by HPaulJohnson** [comment]
@cassiemc no blockers from me. I think this area of work can/should proceed even as we pursue some of our own research about naming, etc.

**Comment by cassiemc** [comment]
Fantastic, thanks Paul.

**Comment by OpenMatt** [comment]
@HPaulJohnson : what's the deliverable or work that needs to be done on this this Heartbeat? 
* and: is the RACI up to date? blanks we can fill in?

**Comment by HPaulJohnson** [comment]
See update in #179. TL;DR for this ticket is that I met with Mary Ellen last week to scope out next steps. She is gone this week but we agreed @cassiemc and I can move forward with syncing up on the design-specific aspects of Mozilla/Webmaker branding (look and feel, etc.). I will set up a meeting with @mart3ll this week for the three of us to discuss this week.

**Comment by cassiemc** [comment]
Re-assigning for design on this to @vazquez as a P2, but please keep me posted!

**Comment by OpenMatt** [comment]
@HPaulJohnson status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by HPaulJohnson** [comment]
@cassiemc and I met with @mart3ll last week to sync up MoFo/MoCo efforts. Lots of good info exchanged. Two next steps: 
- Schedule regular check-ins for MoFo and MoCo design teams (monthly)

- Cassie and Sean are going to work on creating a collaboration space where design ideas/updates can be shared between both teams in real-time.
