### ISSUE TITLE
Clarify how to file meta vs. granular issues

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#239]
We have a lot of meta bugs to track overall initiatives and prioritize during TPS, but it's not clear how to get into the granular issues from the meta issues. 

I think most project owners are using separate milestones to track those?

Perhaps we can ask that project owners document inside the Meta issues how to find the granular issues? Or, should all owners be using another label that lists ALL issues for a sprint? I definitely don't want to triage every single issue during TPS!

I'm :confounded: :weary: :fearful: though. This is one of those things that seemed easier in Bugzilla with the use of whiteboards and filtering, but is blocking me from feeling super comfortable in the new process. Maybe there is a workflow I'm just not aware of, yet?

cc @thisandagain @davidascher @simonwex @OpenMatt

**Comment by OpenMatt** [comment]
I have similar questions. 

* I'm going to suggest that we take this and related issues up this Heartbeat as part of shipping documentation on how to use Git Hub:
https://github.com/MozillaFoundation/plan/issues/208
And then ship it to the build.webmaker.org "how we work section"

* In my view, forcing ourselves to write and improve draft public documentation together is the best way to take up questions like this. Even if we don't have the complete answer yet.

**Comment by cassiemc** [comment]
+1 @OpenMatt, thanks!

**Comment by OpenMatt** [comment]
* I could use some direction and guidance from you all on this
* Hoping we can bring proposal to vet to @davidascher's staff meeting. 

* I ~think~ what I should be doing is: 
** Create new repos for things like communications, process, documentation, tooling, etc. 
** As opposed to what I'm doing now, which is: filing everything (including granular stuff) under "Plan"

* Is that correct? 
* This is a frequently asked question: people are confused about where to file stuff, when they should create a new repo, etc. how to associate granular bugs with meta-tickets, etc.

**Comment by OpenMatt** [comment]
cc @simonwex

**Comment by OpenMatt** [comment]
We might also want to spend some time reviewing / optimizing / cleaning up this page, which lists all our current repos: https://github.com/MozillaFoundation

**Comment by davidascher** [comment]
In general, I suggest as few repos as possible.  Managing across repos is
just a bit harder than within a repo.  @OpenMatt can you think about the
set of issues-not-related-to-code and suggest some groupings?  It could be
we just need a single such repo.

**Comment by davidascher** [comment]
(oh, but yes -- let's keep "initiatives" in the plan repo, and come up with
another repo for smaller-grain stuff)

**Comment by OpenMatt** [comment]
@simonwex: could use your suggestions here as well.
