### ISSUE TITLE
Create / restore moderation functionality for /explore

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#240]
As we are starting to drive more traffic to `/explore` (formerly known as the gallery) we have a need to keep that content regularly updated. The existing content on that page hasn't been updated in quite some time and after talking with @keyboardkat and @cadecairos it looks like part of the problem is that the architecture of that page and the features available within the [MakeAPI admin](https://makeapi.webmaker.org/admin) cause some serious friction.

/via https://github.com/mozilla/webmaker.org/issues/1098

### Audience
- Moderators & staff of webmaker.org
- All visitors to webmaker.org/explore

### Success
All staff of webmaker.org are able to easily add and remove items from the `/explore` view within Webmaker.org. Users of Webmaker see regularly updated content.

### Vision
We have a few possible solutions outlined in the webmaker.org issue listed above.

### RACI
* Phase: Build
* Driver: @simonwex 
* Decision Maker: @thisandagain
* Design Lead: n/a
* Development Lead: @cadecairos 
* Dev: @alicoding 
* Quality Verifier: @simonwex

**Comment by keyboardkat** [comment]
Have now added initial user needs to #1098.

**Comment by cadecairos** [comment]
@simonwex & @thisandagain  we should discuss the requirements @keyboardkat put in mozilla/webmaker.org#1098 

What's a good time for you guys?

**Comment by thisandagain** [comment]
@cadecairos Most times tomorrow work for me. Happy to find some time today if you are blocked.

**Comment by cadecairos** [comment]
@thisandagain  If we could chat today, I'd appreciate it. 

I think I understand what features we want for the  moderation tools, but I don't want to get started until I'm sure we all agree what/how we're building this thing

**Comment by thisandagain** [comment]
Ok. Invite sent.

**Comment by keyboardkat** [comment]
Didn't get invite, but let me know if you want me to be there.

**Comment by cadecairos** [comment]
#ProjectFirehose

**Comment by thisandagain** [comment]
Alright! We've got a plan:
- New service created at `firehose.webmaker.org` that will provide an individual and grid view for latest makes that are coming in.
    - Admin-only
    - One button to "feature" a make for inclusion in the `/explore` gallery
- `/explore` gallery will only show makes that have been featured sorted by creation date
- @thisandagain to provide a simple design to @cadecairos 
- @cadecairos to build the app and make needed modifications to the MakeAPI
- @keyboardkat to tell us if it is terrible or not

**Comment by simonwex** [comment]
@thisandagain, @cadecairos this sounds great. I would love to see a stream interface where we could hook the firehose up to IRC _if it's not significant effort_.

**Comment by thisandagain** [comment]
:+1:

**Comment by keyboardkat** [comment]
plus one @thisandagain - love it. thanks again for doing this, guys!

**Comment by thisandagain** [comment]
Alright ... here is a quick design for the GUI. As @cadecairos and I talked about today, if we can only pull off one view this sprint, I recommend the single (1-up) view as it eliminates the dependency on https://github.com/MozillaFoundation/plan/issues/76

#### Redpen
https://redpen.io/p/xf764a3b2d9b1b5b8a

#### Screenlapse
https://www.dropbox.com/s/awg4lxad9d9t3hg/screen_firehose_000.mp4?dl=0

Drop feedback in the redpen! :cat2: :cake: :boom: 

/cc @cadecairos @keyboardkat @simonwex

**Comment by cadecairos** [comment]
> Screenlapse
> 
> https://www.dropbox.com/s/awg4lxad9d9t3hg/screen_firehose_000.mp4?dl=0

I'm not sure what that was, but I liked it.

**Comment by thisandagain** [comment]
@cadecairos LOL ... I have a habit of documenting a little bit of my process by making timelapse videos while I'm working. For some unknown reason that one seems to have stopped about 1/2 way through. :disappointed: Added a little more detail on spec in the redpen for you.

Assets are available here (SVGs and PNGs available in the `export` folder):
https://drive.google.com/folderview?id=0B-1AZgKn5Nc7Z21VNk9RcEUycVk&usp=sharing

**Comment by cadecairos** [comment]
Alright, I've got enough set up to start building the React app: https://github.com/cadecairos/webmaker-firehose

**Comment by cadecairos** [comment]
filed mozilla/webmaker.org#1177 to update /explore

**Comment by OpenMatt** [comment]
@simonwex status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by cadecairos** [comment]
Webmaker-Firehose needs code review, and deployment to staging, prod.

Before that can happen, MakeAPI and Webmaker.org patches will need to land and get shipped. ( mozilla/makeapi#234 and mozilla/webmaker.org#1177

**Comment by OpenMatt** [comment]
k. when work is ongoing, please update to next train.

**Comment by cadecairos** [comment]
I have this running on staging as a heroku app:

https://webmaker-firehose-staging.herokuapp.com/

You'll need an admin staging account to access it.

Keyboard Controls: 
* left, right - navigate between makes
* spacebar or 'f' - feature/unfeature the make
* delete or 'd' - delete the make

view the featured makes on https://webmaker.mofostaging.net/explore

**Comment by simonwex** [comment]
I did a QA pass, the first round of issues filed here: 

https://github.com/mozilla/webmaker-firehose/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22February+13%22

**Comment by jdotpz** [comment]
From wex: **@jdotpz, where would you like tickets filed for deploying this thing to production?*
https://github.com/MozillaFoundation/mofo-devops por favor!  Thanks!

**Comment by simonwex** [comment]
Status update: We're continuing to chip away at boogs here, and are getting close:

https://github.com/mozilla/webmaker-firehose/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22February+13%22

**Comment by OpenMatt** [comment]
* @simonwex : please update status before today's Heartbeat Planning meeting? (1pm ET)

**Comment by simonwex** [comment]
This is shipped, the admin interface is available at: https://wm-firehose.herokuapp.com/

We shipped with one known bug, which is actually an express 4.0 bug. We're waiting for an upstream patch to land.
