### ISSUE TITLE
New user on-boarding improvements (Phase II)

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#241]
After initial sign-up new users are dropped onto the landing page for X-Ray Goggles which has high information density and dry content for remixing. It is conceivable that this may be contributing to a relatively low rate of engagement after sign-up.

https://goggles.webmaker.org/en-US

### Audience
- Users of webmaker.org who have just created an account.
- Visitors to webmaker.org that enter via `https://goggles.webmaker.org` directly

### Success
Primary: We have a positive impact on the rate of engagement for users who hit `goggles.webmaker.org`.

Secondary: We learn what works / what doesn't in regards to information density and on-boarding messaging.

### Vision
To keep this experiment sprint-sized and easy to measure, I'd like to explore an option that keeps the scope of work isolated to the single page that exists today for X-Ray Goggles. Ideally, the prompt for making would have some continuity with the on-boarding work that was done as part of: 
https://github.com/MozillaFoundation/plan/issues/60

### Deliverables
- Design to be finalized (R+) and delivered by Friday
- Build to be completed, QA-ed, and shipped by end of sprint

### RACI
* Phase: Design / Build / Ship
* Owner: @secretrobotron 
* Decision Maker: @thisandagain
* Design Lead: @xmatthewx 
* Development Lead: @Pomax 
* Quality Verifier: @cassiemc

**Comment by OpenMatt** [comment]
@thisandagain may propose dropping this to p2

**Comment by cassiemc** [comment]
Edit: assigned @xmatthewx for design support.

**Comment by k88hudson** [comment]
FYI it might make a lot more sense if you're rebuilding this page (https://goggles.webmaker.org) to do it in the webmaker.org codebase instead

**Comment by secretrobotron** [comment]
From @adamlofting:
> The Goggles workflow isn't tracked in Google Analytics in the same way as the other apps so we'll want to give some thought into how we measure this.

**Comment by secretrobotron** [comment]
Going to schedule daily meetings at EODs throughout heartbeat so we can roll through these tasks:
* EOD Wednesday: Sketches from @xmatthewx, review
* EOD Thursday: UX mockup from @xmatthewx, UX design review
* EOD Friday: @xmatthewx and @cassiemc finish UI, UI design review, (demo)
* EOD Monday: progress from @Pomax
* EOD Tuesday: more progress from @Pomax
* EOD Wednesday: functional QA script and staging link from @Pomax and @secretrobotron
* EOD Thursday: QA bugs ironed out, bug queue is [on its way to being] empty
* EOD Friday: demo, hands dusted off

/cc @xmatthewx @cassiemc @thisandagain @Pomax

**Comment by xmatthewx** [comment]
Thanks @secretrobotron. Let's plan to demo UX on Friday midday, while pushing through UI. Will likely handoff artwork on Monday.

**Comment by xmatthewx** [comment]
In steps 1-6 on the [existing goggles page](https://goggles.webmaker.org/), 5% of the words teach html[1], 95% teach how to use the tool. We can edit this, but we can only rebalance it so much without adjusting the tool. 

Question: Goggles can become difficult when the modal editor blocks the instructions on the page. Is it possible to modify goggles slightly for this page? For example, can we have users edit html in a small tooltip? Or is that way out of scope? @Pomax @secretrobotron 

[1] ...image location (or "source", written in HTML as "src")...

**Comment by xmatthewx** [comment]
Whiteboard: https://redpen.io/p/ck93d8580c6c32e1a0

**Comment by secretrobotron** [comment]
I'm inclined to say "out of scope," depending on an eval by @Pomax. I'm worried about unlocking goggles code/design bugs as a result or changing up its UI, especially if we're focusing on THE UNIFIED TOOL™ soon.

Can you explain why rebalancing is so hard?

**Comment by davidascher** [comment]
I suggest that @Pomax and @matthewx play with this problem for an hour
together.  I suspect there are easy wins that could lead a less "take over
the screen" UX and would be fairly trivial to implement.

**Comment by secretrobotron** [comment]
:+1:

**Comment by xmatthewx** [comment]
@edrushka - It would be great to have your keen eye on the copy in the [mockups on redpen](https://redpen.io/rw825a9bece366d9ed).

**Comment by edrushka** [comment]
Made some copy notes on redpen

**Comment by cassiemc** [comment]
@xmatthewx and I just hacked together on some UI tweaks, he'll post it here soon if you want to look again then, @edrushka

**Comment by xmatthewx** [comment]
I've posted [revised page UI](https://redpen.io/rw825a9bece366d9ed). Nearly there. 

TBD: 
 - on mobile, do we [separate the instruction block](https://redpen.io/xm0da921f7ffec7e62) so people can access background? 
 - link to setup Goggles should probably lead to a video instead of text.

![goggles_landing](https://cloud.githubusercontent.com/assets/53411/5883488/d8b289b4-a320-11e4-8a06-7defc4d9d80d.png)

**Comment by xmatthewx** [comment]
TBD -- After a user makes a change, we need a success message and prompt for them to publish. Do we reduce the magic by changing content in the instruction box?

**Comment by secretrobotron** [comment]
Bugs to chew on:
* Goggles: https://github.com/mozilla/goggles.webmaker.org/milestones/Webmaker%20On-boarding
* Webmaker: https://github.com/mozilla/webmaker.org/milestones/On-boarding%20Experience%20v2

**Comment by OpenMatt** [comment]
@secretrobotron : status?

**Comment by secretrobotron** [comment]
@OpenMatt design & build went pretty slowly last heartbeat. Will use this one to wrap up build, finish QA, and ship.

**Comment by OpenMatt** [comment]
* ok. moving to Feb13

**Comment by secretrobotron** [comment]
Needs to remain compatible with https://blog.webmaker.org/hack-the-news.
cc @ldecoursy 
Can probably test with clubs on Feb 10.

**Comment by ldecoursy** [comment]
We'd like to start testing this activity https://blog.webmaker.org/hack-the-news (starting Feb. 10 for two weeks) for the Writing the Web section of Clubs curriculum. We have 10-15 community members–teachers, librarians, etc.– who would be testing the activity with learners, to provide us with feedback on the activities themselves as well as the learning outcomes. 

Wondering what the timeline is for the new X-Ray Goggles - if they're not ready by the 10th, we'd still like to test the activity with the existing tool. 

Please keep @thornet and I posted on the timeline, or let us know if you have any q's.

**Comment by secretrobotron** [comment]
Aye aye. Thanks @ldecoursy . We're meeting tomorrow to discuss when the build will be done. I'll let you and @thornet know what you can expect.

**Comment by ldecoursy** [comment]
PS, Hive Pittsburgh is running some activities with X-Ray Goggles through their Digital Corps program - they just posted this today: http://hivepgh.sproutfund.org/blog/2014/12/15/pittsburgh-project-youth-get-hacking/

**Comment by secretrobotron** [comment]
Been chipping away at pieces of this all week. It's been QA'd, fixed, QA'd some more, fixed some more, and loved a little bit. It also has some analytics in it now.

I think it needs one more set of eyes, and the it can go up to prod.

**Comment by secretrobotron** [comment]
@gesa will put this up on prod on Tuesday. We can see how it fares!

**Comment by secretrobotron** [comment]
Need to make sure everything is on prod today. Then, I will close.

**Comment by secretrobotron** [comment]
Prod'd!
