### ISSUE TITLE
Design splash page for Mobile World Congress

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#243]
Sabrina is on point for this, but could use some input from Webmaker designers, as this page will be hosted on webmaker.org

### RACI
* Phase: Design
* Owner: @edrushka 
* Decision Maker: @HPaulJohnson
* Consulted: @davidascher @benrito @thisandagain 
* Design Lead: @sabrinang 
* Development Lead: n/a 
* Quality Verifier: @cassiemc

**Comment by edrushka** [comment]
Still learning how to use meta-issue in Github so not sure how to connect this, but here is the larger issue: https://github.com/MozillaFoundation/plan/issues/234

**Comment by cassiemc** [comment]
Needs a RACI. Here's a suggestion, based on the RACI in #234 (which doesn't quite match our production RACI). Adding myself as design quality & removing the 'needs-design' label, since Sabrina will be doing the bulk of the work.

### RACI
* Phase: Design
* Owner: @edrushka 
* Decision Maker: @HPaulJohnson
* Consulted: @davidascher @benrito @thisandagain 
* Design Lead: @sabrinang 
* Development Lead: n/a 
* Quality Verifier: @cassiemc 

@edrushka please feel free to adjust as needed!

**Comment by edrushka** [comment]
@cassiemc thanks. Could we hook @sabrinang up with a Webmaker designer at some point to advise on what current visual requirements are for webmaker pages? Or is Makerstrap still 100% current?

**Comment by cassiemc** [comment]
Yes, she can connect with me at any time, but Makerstrap 100%, currently. 

Probably good idea to have a kickoff, @edrushka. @thisandagain may want to advise on best practice here.

**Comment by cassiemc** [comment]
Hey @edrushka, I see some milestones related to this exercise in this etherpad: https://studiomofo.etherpad.mozilla.org/MOI-splashpage-kickoff (Line 137) 

    Deadline Feb 23
    QA Feb 16
    Launch Feb 12
    Code Review Feb 5
    Build Done Feb 4
    Build Start Jan 28 **<-- concerned about this one**
    Design Finish Jan 27 **<-- this seems like it should technically be the end of this heartbeat, Jan 30**
    Design Start 19
    Copy Finalized Jan 16
    Content Finalized Jan 16

Worried that we're trying to compress the design cycle here, which will be hard on @sabrinang given she hasn't started yet as she was/is finishing the net neutrality stuff until tomorrow. I may have misinterpreted the timelines, but I think it would be great if we could just focus on finalizing design by next Friday, which would sync really well with our heartbeat. 

I *will* try to help move this ahead a bit with some wireframing, so we can do this speedily, just wanted to flag it. Let me know!

**Comment by edrushka** [comment]
@cassiemc  Agree this is tight and that finalizing design in sync with this heartbeat would be ideal. By pushing everything 3 days, the milestones become:
Milestones (revised Jan 22)

    Deadline Feb 25
    QA Feb 23
    Launch Feb 17
    Code Review Feb 10
    Build Done Feb 9
    Build Start Feb 2
    Design Finish Jan 30

That still gives @mmmavis  the same amount of days for the build. Work for everyone?

**Comment by edrushka** [comment]
Oh jeez - I'm making a mess of Github! 

@thisandagain HAAAALP! ;) I want all this information to go in this ticket on mozilla/webmaker.org like you showed me https://github.com/mozilla/webmaker.org/issues/1167

**Comment by cassiemc** [comment]
@edrushka sounds good to me! I'm not sure exactly what you're trying to do here but ping me when you wake up if @thisandagain is busy.

**Comment by edrushka** [comment]
Guys, I'm going to paste this thread into the correct repo: https://github.com/mozilla/webmaker.org/issues/1167 and close this bug as the /plan is not where this work should take place. Sorry for the confusion!

**Comment by cassiemc** [comment]
@edrushka I think we want to keep this issue open so it appears here: https://build.webmaker.org/now Think of it as the Meta bug.

We can continue to track the details of the work though in https://github.com/mozilla/webmaker.org/issues/1167

**Comment by edrushka** [comment]
This work is almost done. Awaiting decision on video which will be made Tuesday Feb 3. Design will be locked EOY Wed Feb 4.

**Comment by OpenMatt** [comment]
* moved to Feb13, since work is not complete
* added RACI to the top for easier finding
* @edrushka is that RACI up to date / correct for this Heartbeat?

**Comment by edrushka** [comment]
Yes, looks good.

**Comment by edrushka** [comment]
Design is locked. Mavis has started to build. Closing this. Thanks, everyone!
