### ISSUE TITLE
Get pad.webmaker.org ready for widespread use

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#244]
@jdotpz : this is probably filed in the wrong repo. Let's fix that in our Kick-off mtg Tues.
* Goal: put a shiny new light sabre in the hand of every MoFo / Webmaker community member: an etherpad instance that can do things our crappy ole etherpad doesn't
* Some notes we took on this in Portland: https://etherpad.mozilla.org/build
* Next step: make a plan and file more specific bugs.

**Comment by davidascher** [comment]
I suggest starting by making sure that it would meet the needs of our
folks.  In particular, there is AFAIK no team support in etherpadlite.
Let's make sure that sort of thing isn't a deal-breaker for people, so they
don't complain if we switch.

Suggest we start with a bit of a survey re: etherpad.m.o and what people
hate / love.

**Comment by OpenMatt** [comment]
Sounds good.

**Comment by hannahkane** [comment]
Thinking we can close this ticket.
