### ISSUE TITLE
Blog about MoFo's 2015 and Q1 plans

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#245]
Communicate more widely about our 2015 plan. Dig into specifics around Q1.

We'll do this 3 ways:
1. **a blog post series.** From staff and community. Fleshing out specific aspects of the 2015 plan. And what they're working on in Q1 to get there. 
2. **Q1 goals and KPIs.** Document our Q1 goals and KPIs in one spot. And tell a story about they key deliverables that will exist by April 1. 
3. **establishing and polishing permanent homes for this work.** At build.webmaker.org, https://wiki.mozilla.org/Foundation/2015, and other places. polishing up the design, UX and grokkability.

**Comment by davidascher** [comment]
A radical thought: the plan is currently both in wiki and in gdocs/PDF.  I
will boldly claim that both of those are terrible ways to read and
understand the plan, and unpleasant reading experiences.  I would wager
nobody but the authors are likey to read them again.

I think we should create a prettier, easier to read, and better-connected
reading site/page.  Could live at build.webmaker.org/strategy for example.
It should link to past initiatives, current initiatives, dashboards, etc.

All we need I think is permission from the authors of those documents to
have their words mangled, their typography skewered, and their pages turned
into links to this new thing.

**Comment by OpenMatt** [comment]
* Agreed. Had the same thought. Let's do it.

**Comment by OpenMatt** [comment]
* I've staged an HTML version of the Mozilla Learning Plan here: https://blog.webmaker.org/2015_plan

**Comment by OpenMatt** [comment]
* Not sure what to do with it yet -- will update this thread with a proposal tomorrow. In the mean time, wanted to surface an HTML version that we could publish / move / re-purpose a few different ways.

**Comment by OpenMatt** [comment]
### Blog post schedule
Here's a draft blog post schedule: (Please edit / add to this list!)
### Jan 22 / 23
- [ ]  *Mozilla Learning in 2015*. (Mark or Matt) Publish the Mozilla Learning 2015 Plan in prettier HTML version. Tie back to Surman's earlier posts. https://blog.webmaker.org/2015_plan
- [ ] *Working open in 2015* -- (Matt) -- invite staff and community to write and reflect on the overall 2015 plan, and what success looks like for them in Q1. Summarizing the plan to do a series on this over the next week or two. 

### Jan 26
- [ ] *The Third Era of Mozilla* (Matt). Embed the video and transcript from Mitchell at PDX on "The Mozilla Process." Alongside Mark's keynote on "battling Goliath." Stress: open, agile, radical participation. 

### Jan 27 - Jan 30 (if possible)
- [ ] *How we'll measure success in 2015.* (Adam?)  Metrics. Stress two key KPIs for Mozilla Learning: relationships and reach. + early thinking from Adam on creating the 2015 equivalent of our "10K" dashboard. 

***A series of posts about Q1***
A series of posts (from everyone who wants to write one) about a story about what the world will look like by April 1. 

#### Learning Networks 
* Multiple posts from multiple contributors. Co-ordinate with Michelle, Lainie, Hannah. 
* Potential topics:
- [ ] **Webmaker Clubs** -- (Michelle) -- a story about our vision and plan for Q1. 
- [ ] **The Future of Maker Party** -- (Amira?) -- its future. how we're evolving it into year-round activity through Webmaker Clubs.
- [ ] **teach.webmaker.org** -- (who?) -- how we're improving the web sites we use to support teachers, partners, clubs and networks in Q1.
- [ ] **badges and credentialing** -- (Hannah) -- surface our finalized documentation as a blog post 
- [ ] **training** -- (Laura?) -- a story about our vision and plan for Q1. 
- [ ] **Growing Hive** -- (Lainie?) a story about how we're going to grow the number of Hive Cities this quarter, empowering more people to start Hive Learning Networks through improved documentation and support.

#### Learning Products 
- [ ] -- **Reaching learners directly with Webmaker** -- (Andrew / Bobby / David?) -- How we're expanding our platform to reach a broad market of learners directly. And some of the early results of these experiments. 
- [ ] -- **What we're doing in mobile** -- (who?) -- setting the stage for MWC and beyond. Tell a story about where we hope to be by end of Q1. 
- [ ] -- **User on-boarding** -- (who?) -- what are we doing in Q1 to make it easier for new users to make and learn something quickly on Webmaker.org.  

### Feb 2 - Feb 6
- [ ] *Leadership Development* (Mark?) -- flesh out the overall vision and Q1 milestones for the Leadership Development piece of the Mozilla Learning plan. 
- [ ] *Community participation in 2015.* (Humph?) Our plans for working with community, with an emphasis on code / localization / com sci students. Vetting our processes, tooling and communications from a community contributor perspective. Our plan for doing that better in 2015. 

New Communities
- [ ] **Open News** -- who? -- a blog post linking to their 2015 plan, plus fleshing out key deliverables and goals for Q1.
- [ ] **Science Lab** -- who? -- a blog post linking to their 2015 plan, plus fleshing out key deliverables and goals for Q1.
- [ ] **Advocacy** -- Dave Steer -- a blog post linking to their 2015 plan, plus fleshing out key deliverables and goals for Q1.

**Comment by OpenMatt** [comment]
### Feb 2 - Feb 6
- [ ] **How we'll measure success in 2015** -- (Adam?) -- Metrics. Stress two key KPIs for Mozilla Learning: relationships and reach. + early thinking from Adam on creating the 2015 equivalent of our "10K" dashboard. 
- [ ] **Leadership Development** -- (Mark?) -- flesh out the overall vision and Q1 milestones for the Leadership Development piece of the Mozilla Learning plan. 
- [ ] **Community participation in 2015.** -- (Humph?) -- Our plans for working with community, with an emphasis on code / localization / com sci students. Vetting our processes, tooling and communications from a community contributor perspective. Our plan for doing that better in 2015. 

#### New Communities
- [ ] **Open News** -- who? -- a blog post linking to their 2015 plan, plus fleshing out key deliverables and goals for Q1.
- [ ] **Science Lab** -- who? -- a blog post linking to their 2015 plan, plus fleshing out key deliverables and goals for Q1.
- [ ] **Advocacy** -- Dave Steer -- a blog post linking to their 2015 plan, plus fleshing out key deliverables and goals for Q1.

#### Ops
- [ ] **2015 plan summary** -- Angela? -- a blog post summarizing Ops plan, and any key Q1 milestones.

**Comment by thornet** [comment]
I can do one on clubs for next week.

**Comment by hannahkane** [comment]
I can start the teach.wm.org post, and get input from @ldecoursy @thornet and @xmatthewx. Unless @ldecoursy or @thornet would prefer to do it?

**Comment by OpenMatt** [comment]
@davidascher said he could take the "What we're doing in mobile" one or "User on-boarding"

**Comment by OpenMatt** [comment]
emailed @humphd about his potential piece

**Comment by OpenMatt** [comment]
@hannahkane: should we move the badges and credentialing one? when do you think that doc will be finalized?

**Comment by adamlofting** [comment]
This looks great. Thanks for wrangling this all @OpenMatt and I'm happy to pick up the post with my name against it. :chart_with_upwards_trend:

**Comment by HPaulJohnson** [comment]
I'm in - I'll do the marketing plan post next week.

**Comment by LauraReynal** [comment]
@OpenMatt I'll do the one on research !

**Comment by ldecoursy** [comment]
I can work with Simona on one for Hive for week of Feb. 2- I think we might want to push training back until after a mini-sprint we're having the week of Feb. 9, possibly Maker Party too.

**Comment by hannahkane** [comment]
@OpenMatt  - I should be able to do both the badges and the teach.wm.org posts next week.

**Comment by thisandagain** [comment]
@OpenMatt I can take the "Reaching Learners" post. I recommend @k88hudson or @vazquez for mobile product and @secretrobotron for on-boarding if they are up for it.

**Comment by vazquez** [comment]
Hey @k88hudson, let's write the blog post together :)

**Comment by secretrobotron** [comment]
Happy to draft something.
- Any kind of outline or points we want to drive home?
- Length?
- webmaker blog?
- Just using this ticket to coordinate?

**Comment by OpenMatt** [comment]
@secretrobotron: it's totally up to you. I was thinking the main point of the on-boarding piece is just to summarize: a) the goal of that work. why does it matter to users? b) what we already did, c) the early results of that (esp.: data) and d) what we think we're going to do next.
* you can just post to your personal blog. And we can cross-post to the webmaker blog when it's done. 
* whatever length you feel
* yes we're just using this ticket to co-ordinate

**Comment by OpenMatt** [comment]
* there's no "deadline* per se -- we're just trying to make this week and next a period of open reflecting and writing.

**Comment by OpenMatt** [comment]
Here's a draft outline I put together for Surman to frame some of the overall work:
http://workopen.org/Q1_blogging

He'll probably publish today / tmrw

**Comment by k88hudson** [comment]
@vazquez sure, sounds good.

**Comment by hannahkane** [comment]
I posted the teach.wm.org to my blog (http://hannahgrams.com/2015/01/27/a-new-online-home-for-those-who-teachtheweb/). @OpenMatt - do you want me to cross-post on the Webmaker blog? If so, when would be good?

**Comment by hannahkane** [comment]
@OpenMatt — I don't think the badges post will be ready to go this week. Too many outstanding questions. Moving that to next week.

**Comment by OpenMatt** [comment]
I've updated the blog post list above -- lots of great stuff already published. 
* @davidascher: still able to write something on mobile this Heartbeat?
* @hannahkane : can you publish the badges post (with a link to your document, preferably in HTML form for easier reading) this week?

**Comment by ldecoursy** [comment]
Will have Hive ready to post this week too...

**Comment by hannahkane** [comment]
Badges blog post: http://hannahgrams.com/2015/02/04/building-better-badge-tooling/

**Comment by OpenMatt** [comment]
* I'm going to move this forward to Feb 27, to ensure those last few posts don't fall through the cracks

**Comment by hannahkane** [comment]
Closing this out-of-date ticket.
