### ISSUE TITLE
Finalize production work for Privacy Day Campaign

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#246]
GOAL: Finish up & ship the production work. Some design & front-end tweaks to get the execution looking great. Then push it to staging / prod when ready. (requires: design / light front-end dev.)

Communications plan for how we'll promote this work once it's completed is here:
https://github.com/MozillaFoundation/plan/issues/226

### Needs to ship on Jan 27th EOD
Because Privacy Day is Jan 28th

Owner: @secretrobotron 
Responsible: @HPaulJohnson 
Design Lead: @iamjessklein 
Development Lead: @gesa
Quality Verifier: @cassiemc

**Comment by OpenMatt** [comment]
@iamjessklein : assigning to you, as per conversation with @cassiemc 
cc @HPaulJohnson so he knows when this is done.

**Comment by OpenMatt** [comment]
moving from the other ticket for reference. @thisandagain said:

UI and execution needs QA prior to launch:
http://sleepy-ravine-9799.herokuapp.com/en-US/home-3

/cc @cassiemc @gesa @iamjessklein

**Comment by cassiemc** [comment]
This project needs an owner and a kickoff, since it's p1. I think the previous owner was @HPaulJohnson but maybe I'm wrong? Still needs dev, too.

cc @thisandagain @OpenMatt @simonwex

**Comment by iamjessklein** [comment]
:+1:  In the meantime, is there a qa checklist that we can pull up to start getting prepped?

**Comment by OpenMatt** [comment]
@simonwex: are you able to project manage this one?

**Comment by iamjessklein** [comment]
Just talked to @secretrobotron and we think that we should break this into two parts:

* Week 1: Design QA and finalizing
* Week 2: Functional QA (Tech) 

In order to do this - I am going to clean up [the checklist that was used for onboarding qa](https://docs.google.com/a/mozillafoundation.org/document/d/1UzVUmOEoiF09ciFzsAM0btYuE99-JEisVwTE89SseYw/edit#) and see if there is a checklist for design qa and turn them into a form to send participants.  It would be great if the form could be like [the intake form on build.webmaker.org](http://build.webmaker.org/add) - but don't need this to turn into a whole project.

**Comment by thisandagain** [comment]
Hey @secretrobotron sorry for the late notice, but can you own this issue?

**Comment by OpenMatt** [comment]
* I've updated the RACI above, because I filed this out incorrectly to start.

**Comment by secretrobotron** [comment]
@thisandagain :+1: on it.

**Comment by OpenMatt** [comment]
* Thanks Bobby. BTW: I don't need to attend the kick-off or be a part of the RACI on this ticket going forward. I just filed it. Now I'll get out of the way. :)

**Comment by secretrobotron** [comment]
Haha acknowledged :).

**Comment by secretrobotron** [comment]
Tracking progress in a webmaker.org milestone: https://github.com/mozilla/webmaker.org/milestones/Privacy%20Day

**Comment by secretrobotron** [comment]
Zero bugs left:
* https://github.com/mozilla/webmaker.org/milestones/Privacy%20Day

Pages are up on staging:
* https://webmaker.mofostaging.net/en-US/home-3
* https://webmaker.mofostaging.net/en-US/home-6

**Comment by secretrobotron** [comment]
@HPaulJohnson @cassiemc wanna take a final look to see if anything can be fixed before tomorrow EOD?

**Comment by gesa** [comment]
@secretrobotron I think you misspelled “Zaroo Boogs” 😉

**Comment by secretrobotron** [comment]
@gesa good catch. thank you

**Comment by HPaulJohnson** [comment]
Everything looks good to me. Thx.

**Comment by cassiemc** [comment]
A couple things but no deal breakers.
![privateeye](https://cloud.githubusercontent.com/assets/1186326/5912762/c3b8d0b2-a5a6-11e4-95fe-c5b427581f47.png)
* the corners on the hex don't quite line up, and the edges still look a bit jagged (i'm looking in ff 36 mac). I didn't take a screenshot before but it does seem better than the last time I looked.
* I think the animation would look better if it was two shapes (same color as the bkg) animating up and down over the eye (like real eyelids) vs. stretching the eyeball itself. for future reference if there's no time to adjust this now.
* when the static animation transitions to the version where the eyeball follows my mouse there is a slight jump. not sure if anything could be done about that.

Looks really good though, it does the trick. Love the text, color and pattern updates. Nice work everyone!

**Comment by gesa** [comment]
Hopefully this looks a little better on FF. I'm gonna ruminate on the eyelid thing. Idk if I'll get anywhere with that, but it'll be on my mind.
![gukev](https://cloud.githubusercontent.com/assets/782056/5913720/98e405ae-a59d-11e4-8f2c-55df8f2e9e11.png)

**Comment by gesa** [comment]
Okay. Ruminated. Played around. How does this look? http://snaps.akibraun.com/blinking-eye.mov

**Comment by cassiemc** [comment]
@gesa :revolving_hearts: :boom: :heart_eyes: Looks awesome, you rock.

**Comment by iamjessklein** [comment]
Nice @gesa - solid. :facepunch:

**Comment by secretrobotron** [comment]
@gesa will push to prod in 2 hours. :deciduous_tree:

**Comment by gesa** [comment]
![](http://snaps.akibraun.com/ralph.gif)

**Comment by iamjessklein** [comment]
It has landed!!!

![giphy](https://cloud.githubusercontent.com/assets/535012/5930475/0c1f8ed8-a65e-11e4-8ae2-5cad0dc05c12.gif)

**Comment by gesa** [comment]
I wish I could “favorite” a github comment.
