### ISSUE TITLE
Optimize our donation form

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#247]
This is a tracking issue for private issue: https://github.com/MozillaFoundation/2015-fundraising/issues/2

### RACI
* Phase: Evaluate / Plan / MoCo Coordination
* Owner: @simonwex
* Decision Maker: @valianttry 
* Design Lead: N/A
* Development Lead: @jdotpz 
* Quality Verifier: @ScottDowne

**Comment by OpenMatt** [comment]
@simonwex : status?
* (as a general rule, we should aim to update these planning tickets much more frequently.)

**Comment by jdotpz** [comment]
@OpenMatt Please see https://github.com/MozillaFoundation/2015-fundraising/issues/2 for the update.  This is in our private repo, and discussions about status of this project are not to be public.  Thanks!

**Comment by simonwex** [comment]
This ticket will be closed today after the last legal bug is filled out.
