### ISSUE TITLE
Heartbeat planning should take into account QA and polish after a prototype heartbeat

### ISSUE THREAD

**Issue by iamjessklein** [MozillaFoundation/plan#248]
When a 2 week heartbeat is done in such a way that the first 2 weeks are devoted to essentially shipping a prototype (conceive, design and implement), then it would be great to plan for the following heartbeat to be dedicated to Design and Functionality QA and polish. It would good to go into the prototyping sprint knowing that you have the polish/qa sprint to follow up.

My example for this is that [we just shipped a prototype for Privacy Day](https://github.com/MozillaFoundation/plan/issues/175), and now we need to [dive into the polish](https://github.com/MozillaFoundation/plan/issues/246). 

cc/ @cassiemc @thisandagain @secretrobotron @simonwex

**Comment by davidascher** [comment]
Sure, or (when we can), do both phases in a single heartbeat.  But yes, we
should ack that polish takes time.

**Comment by secretrobotron** [comment]
:+1:
I think we can work on timing. Some projects won't have 2 or 3 heartbeats at their disposal, but we can still line up QA for design and functionality that meshes well with any schedule.

**Comment by cassiemc** [comment]
Tagging this as food-for-thought in #652, otherwise closing.
