### ISSUE TITLE
Set up a server that serves up Twitter feeds on request

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/plan#250]
(sorry, I'm not sure if this ticket has to be filed in a specific format)

Using the official [Twitter Timeline Widget](https://dev.twitter.com/web/embedded-timelines) is probably the quickest and easiest way to embed Twitter feeds.   However, there are concerns around privacy/tracking issues with the use of Twitter widget.

A Node.js app with a suitable existing package can probably help solve this problem (thanks for @Pomax & @alicoding's suggestions)

First question: do we have a MoFo owned Twitter account that I can use to apply for API keys / tokens etc?

**Comment by mmmavis** [comment]
@davidascher @simonwex @jdotpz , think you guys might know?

**Comment by jdotpz** [comment]
No general mofo account that I am aware of.  Each group has its own twitter feed, however...
ala https://twitter.com/opennews

**Comment by mmmavis** [comment]
The to-be-built server that I have in mind should serve up feeds according to a hashtag, Twitter handle of requester's choice.  That's why I think a general Twitter account should be used to apply for API related keys.

**Comment by simonwex** [comment]
@mmmavis if it's read-only, I think we should have a stand-alone account for it. Feel free to create one and share the details with @jdotpz via lastpass.

**Comment by cassiemc** [comment]
@mmmavis @simonwex can we close this?

**Comment by mmmavis** [comment]
Yup yup this is kinda obsolete now. Let me hit the Close button.
