### ISSUE TITLE
Research Pootle and compare with Transifex

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/plan#251]
Lets do some research on [Pootle](http://pootle.translatehouse.org/) and see what it can offer that Transifex can't since there are a lot of contributors not really happy about Transifex as our translation platform.

### Audience
Our translators/contributors. I have spoke to few translators at Mozfest last year and also few of the Mozilla-l10n which suggested that using Transifex really frustrated them sometimes and they are asking if we could make a switch to Pootle which is a project that I've been looking at since Mozfest 2013 (I've met the team in person back then)

### Success
Come up with complete list of pro and con for both Transifex and Pootle which can lead to a result of either sticking with Transifex or switching to Pootle for our translation platform.

### Vision
I would suggest that we try both at the same time to see if we could at least solve problems that I've describe earlier and then from there we can see if this will be our future platform for localization.

### RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier:

**Comment by davidascher** [comment]
Good question.  One of the things that has felt magic about Transifex is
the number of people who "just show up and start translating".  Given that
we don't have people specifically dedicated to enrolling, communicating and
managing our l10n community (apart from you @alicoding, but you have lots
of other stuff to do to), I'd want to make sure we don't lose that magic in
a tool transition.

**Comment by alicoding** [comment]
At this point I don't have much knowledge about community in Pootle itself and I'm actually wondering how large is the community there compare to Transifex and if it will help us gain any more contributors or not. I might just ask few of our current translators who suggested pootle to find out about this. I think totally changing might not be what we want at first but checking it out and find out how well it will work with our project might be beneficial?

**Comment by simonwex** [comment]
@alicoding, this looks like a better first step, building some sample code with it and pairing it with some of the React/l10n research would be good.

@thisandagain, can we prioritize this for post-MWC?

**Comment by thisandagain** [comment]
Yup! Sounds great. This has come up a few times in the field too (particularly with the Bangladesh reps).

**Comment by OpenMatt** [comment]
@alicoding : status?

**Comment by alicoding** [comment]
Ah, sorry I didn't see this was flag to April 10th's milestone and I didn't have a chance to look at this because I've been busy with the new login and other projects. I think this needs a better scope and some more research, so I will leave this to @thisandagain and @simonwex to decide when we want to start on this.

**Comment by hannahkane** [comment]
Is this covered by #424?

**Comment by alicoding** [comment]
We are doing it at the same time actually. Atul and I going to test few other platforms (OneSkyApp and Pootle).

**Comment by cassiemc** [comment]
@alicoding can we close this?

**Comment by alicoding** [comment]
I think we have come to a conclusion that we are going to use Pontoon for our next projects.
