### ISSUE TITLE
Centralized logging for mofo apps

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/plan#252]
Right now when there's a problem that needs logs to solve I SSH into a box, kill the service, and run it in my console. Works for me, @jdotpz, and @cadecairos, but it doesn't scale to more people, or multiple instances.

We have a semi-working logging system that I'd love to have fully-working instead of my SSH method.

Specific problems:
- I don't know what the URL is (http://loggins.mofoprod.net/ doesn't seem to work)
- I don't have any credentials to access the logs
- I assume that loggins never works, because @cadecairos needs to bug @jdotpz on IRC to fix something before you can view logs. Also, all the logs got lost while the thing was broken.

Help me obi-wan @jdotpz, you're my only hope!

**Comment by jdotpz** [comment]
Logging is boned right now, I'm going to fix ES today.

**Comment by jdotpz** [comment]
loggins:
![-this_is_it-_by_kenny_loggins](https://cloud.githubusercontent.com/assets/1373628/5841066/97d2e4ba-a15f-11e4-989b-9d7a5cb22166.jpg)

**Comment by cadecairos** [comment]
loggins-> :man:  :gun: <- @jdotpz 

> I don't know what the URL is (http://loggins.mofoprod.net/ doesn't seem to work)

@jbuck kibana is a bit janky, try https://loggins.mofoprod.net/#/dashboard/elasticsearch/DEFAULT%2520-%2520ALL%2520LOGS

**Comment by jdotpz** [comment]
Nope.  Just go to loggins.  All data and dashboards are gone for now, and after I'm done raging, maybe I'll recreate them.  But we're getting logs.

OK, off to go chain smoke.

**Comment by jdotpz** [comment]
OK, so before I start, know that there will be a wiki page for how to use this upcoming.  This is *not* intended to be a tutorial or wiki for general consumption, but instead a quick "how to" for people in this thread who are most likely to benefit from a quick run through.

* https://loggins.mofoprod.net (search your email for loggins password for the basic auth)  **NOTE: We require https, so http will not work**
* All apps have dashboards, listed under App: appname-env
![screen shot 2015-02-12 at 3 40 38 pm](https://cloud.githubusercontent.com/assets/1373628/6177590/8e5ac5ea-b2cd-11e4-8792-51ab12755138.JPG)
*All app log dashboards have multiple rows of filters you can use to filter out what you don't care about
* All app dashboards show a full length time series chart (the top chart).  This will help show you the % of errors vs 200's.
![screen shot 2015-02-12 at 3 42 22 pm](https://cloud.githubusercontent.com/assets/1373628/6177623/c57641b2-b2cd-11e4-941b-f60b97e3dd85.JPG)
* Time filtering happens by clicking the time filter up top, as shown below.
![screen shot 2015-02-12 at 3 43 27 pm](https://cloud.githubusercontent.com/assets/1373628/6177658/fbed73be-b2cd-11e4-86e3-8a8b965789c6.JPG)
* To run a query, use Lucene query syntax (http://www.lucenetutorial.com/lucene-query-syntax.html ) and replace the "Your Search Here" in the query bar.  You can find this by looking for where it says "Your Search Here".
![screen shot 2015-02-12 at 3 45 17 pm](https://cloud.githubusercontent.com/assets/1373628/6177687/3152d2d8-b2ce-11e4-952c-ad9b6f0d15d1.JPG)

Assuming loggins never works is an incorrect assumption.  It had problems which were promptly resolved, and I've additionally redone all dashboards to be more useful.

**I am available to walk you, or anyone, through this system to make it more helpful, but I count on you asking for said help to reach out**

**Comment by cassiemc** [comment]
@jbuck Can we close this?
