### ISSUE TITLE
Move mofo app config from S3 bucket to a repository

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/plan#253]
We've been bandying about this idea for quite some time, but I think we need to move away from storing our app configuration in an S3 bucket to storing it in a repository somewhere. Reasons:

1) Who can change the current configuration? Oftentimes I'm the person asked to make changes on behalf of others.
2) Who made a change? What did they change? When did they make it? Why did they make it? If I'm really determined, I can use the S3 API to look at previous versions of a configuration and diff them... or can use `git diff`.
3) The mismatch between deploying to staging and production, and changing the configuration on staging and production means that it's very easy to miss changing a vital configuration somewhere, and having your entire process go down for the count.

We can argue out the differences between having a secret repo, or having split config, or encrypting sensitive configuration items... but we need to improve on what we have now.

**Comment by jdotpz** [comment]
imo, we should go split config, and keep secrets in S3.
It should be pretty rare we're changing secrets, right?

**Comment by hannahkane** [comment]
@jdotpz - more to do on this ticket? Should we close, or assign to a 2016 milestone?
