### ISSUE TITLE
Remove current content at badges.webmaker.org

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#254]
The page at http://badges.webmaker.org currently lists badges we haven't issued for at least a couple of years. We've had bugs filed to do something with this before, but nothing's happened (probably for good reason, I just can't remember the details)

Perhaps as a holding pattern we could list the badges we have currently available? We're pointing people towards http://blog.webmaker.org/badges in the meantime.

-----
Stimulus: [this conversation on Twitter](https://twitter.com/OpenBadges/status/557922849126895616).

**Comment by jbuck** [comment]
I believe the reasoning is that people who were issued these badges lose all data about them if we remove the content behind badges.w.o. Probably the right solution here is to generate a static copy of the site.

**Comment by dajbelshaw** [comment]
Thanks @jbuck! Could you unpack 'lose all data'? Would also be good to know how many people we'd affecting...

**Comment by jbuck** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=949061 has some context for the last time we did this.

Hilariously enough, I see that https://badges.webmaker.org has an invalid cert and I've seen no complaints about it.

**Comment by dajbelshaw** [comment]
OK, well... paging @cassiemc 

Suggest we might want to explore a solution where we use https://badges.webmaker.org to foreground our [current badges](http://blog.webmaker.org/badges). We could then a little 'archive' section at the bottom of the page for those we don't currently issue (i.e. those that are listed there now!)

**Comment by hannahkane** [comment]
Wondering if we can consider this part of the project that's being scoped in #215 ? I'm expecting that that project will include re-imagining the way badge offerings are presented.

**Comment by dajbelshaw** [comment]
Yeah, good idea @hannahkane - the legacy pages are confusing people!

**Comment by ldecoursy** [comment]
Closing this ticket, as noted above, @hannahkane will flag as part of ongoing badges work.
