### ISSUE TITLE
Update MozillaFoundation org description

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#255]
The MozillaFoundation organization description is currently blank, but we could craft a couple sentences to help direct people more smoothly into the desire process. I think we can use it to help solve the "Where do I file this?" question, for people who want more direct access than the intake form.

* easy navigation between MozillaFoundation and Mozilla team pages
* descriptions of when issues should be filed in Mozilla vs. in MozillaFoundation (building vs. planning)
* link to build.webmaker.org, little description of what you'll find there

Anything else we need there?

cc @OpenMatt @davidascher

**Comment by davidascher** [comment]
We should justify the org's need for existing.  There were two IMO:

 * to make it a place where people can learn about github etc. in a
friendly space w/o feeling like the world is watching
 * to create a place where we can create private repos that are only
visible to mofos.
