### ISSUE TITLE
Localize Welcome/Transactional Emails

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#259]
Initiate a process to update welcome emails for non en-US and identify how to implement in Apostle post completion of issue#242.

    Phase: Write / Build / Deploy
    Owner: @HPaulJohnson
    Decision Maker: @HPaulJohnson
    Design Lead: 
    Development Lead: 
    Quality Verifier:

**Comment by cassiemc** [comment]
@HPaulJohnson Should we update the milestone here, or close?

**Comment by HPaulJohnson** [comment]
Close. I think this was for Webmaker specifically and we never moved to Apostle nor do we have great transactional email solution at this point.
