### ISSUE TITLE
Allow for Heartbeat planning (and bug triage) across repos

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#260]
This might be impossible, but it would be awesome to solve the problem of:

"I filed this issue in one repo, but now I want it to appear in the Plan. Do I have to refile it?"

A good example of this is a bug like 'Build Call Congress tool': https://github.com/MozillaFoundation/movement-building/issues/4

Could we use a label, or some other marker, to pull bugs with certain tags from across repos into one central triage list – or is the best thing just to refile Meta tickets under the Plan repo?

cc @simonwex @davidascher @thisandagain @OpenMatt

**Comment by simonwex** [comment]
I think we should create the issue in the plan tool and link to the existing issue in the solution section.

**Comment by thisandagain** [comment]
:+1: on @simonwex 's suggestion above

**Comment by simonwex** [comment]
https://github.com/MozillaFoundation/plan/issues/263
