### ISSUE TITLE
Ship slide presentation on Gates grant work

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#261]
Concept work and framework is done. Next: ship it as a presentation.

### RACI

* Phase: Design only
* Driver: @chrislarry33
* Decision Maker: An-Me
* Consulted: Mark Lesser and Meredith Summs
* Design Lead: @adiladiladil
* Development Lead: n/a
* Quality Verifier: @iamjessklein 

@iamjessklein and Adil have been involved with a Curriculum deliverable for Gates Foundation. We need a plan for wrapping up this work, and for this to get triaged in the regular heartbeat process. I think Adil's contract is up sometime in Feb, so ideally we can wrap this up before then.

### Success
A happy Gates Foundation with the work they need!

### Vision
Here is the work in progress: https://redpen.io/p/jbb5a2d65bef590573

**Comment by davidascher** [comment]
I believe AnMe is decision maker, and someone else likely should be owner.

**Comment by OpenMatt** [comment]
* Updated the RACI
* @cassiemc : is the goal to ship and wrap this up this Heartbeat? If so, can we update the ticket title to add a verb and be more specific?

**Comment by OpenMatt** [comment]
* @cassiemc : is this a proposed P1 or P2?

**Comment by OpenMatt** [comment]
@cassiemc try to update prior to Heartbeat meeting

**Comment by cassiemc** [comment]
My involvement here is only to get this off @iamjessklein's plate asap. Jess, can you update us on where this work is?

**Comment by iamjessklein** [comment]
The concept work has been completed [here](https://redpen.io/p/jbb5a2d65bef590573) 
The [slide deck framework](https://docs.google.com/presentation/d/1RzJXMGPyujSclMSmQGyf-e1RKdGZbLAH-UE0TfiwYKI/edit?usp=sharing)has been constructed by Mouse
By the end of this heartbeat @adiladiladil should deliver a completed slide presentation. 

I should be QA

**Comment by cassiemc** [comment]
Great, thanks @iamjessklein!

**Comment by chrislarry33** [comment]
Thanks Cassie

Chris Lawrence
Mozilla Hive Mentor Network
clawrence@mozillafoundation.org 
http://www.clawrence.org
@chrislarry33
SKYPE: chrislarry33
Mobile: 718-757-0843
G+ http://bit.ly/gclaw33 <http://bit.ly/gclaw33>

**Comment by OpenMatt** [comment]
* So the specific deliverable here is: by the end of this Heartbeat, @adiladiladil will deliver a completed slide presentation.
* @chrislarry33: I assume you've communicated that to Adil :)

**Comment by iamjessklein** [comment]
:+1:  yes @adiladiladil is aware of this and is going to do stands with An Me and Mouse as well.

**Comment by iamjessklein** [comment]
Update: 
Slide deck [draft 1](https://www.dropbox.com/s/scptj9ld54pmm65/Gates%20Slide%20Deck.pdf?dl=0)
deck is provided [here](https://etherpad.mozilla.org/gates-slidedeck-feedback)
![screen shot 2015-02-06 at 10 12 16 am](https://cloud.githubusercontent.com/assets/535012/6081590/d52eab1a-ade8-11e4-8020-692093ae306f.png)
![screen shot 2015-02-06 at 10 12 51 am](https://cloud.githubusercontent.com/assets/535012/6081592/d730394c-ade8-11e4-91f2-4b8ec49a0440.png)
![screen shot 2015-02-06 at 10 12 36 am](https://cloud.githubusercontent.com/assets/535012/6081593/d86f7908-ade8-11e4-80d0-2d3be8301790.png)

**Comment by ldecoursy** [comment]
@iamjessklein Chris is traveling - do you happen to know if @adiladiladil is awaiting more feedback or submitting another rev?

**Comment by iamjessklein** [comment]
@ldecoursy - @adiladiladil [shared another update](https://drive.google.com/a/mozilla.com/file/d/0ByGu6IwBft5mbUcxeXR2aHotRU9RTm9uVmtPQjZhcUZNbVZV/view?usp=sharing) and An-Me, Marc Lesser, Meredith Summs and I gave feedback on Wednesday. He should be submitting a new iteration this Friday. 

Feedback can be added [here](https://etherpad.mozilla.org/gates-slidedeck-feedback)

**Comment by chrislarry33** [comment]
Is there an update here, sorry out of the loop

**Comment by anmechung** [comment]
This can be closed.  Presentation completed.

**Comment by ldecoursy** [comment]
Thanks @anmechung - closing!

**Comment by anmechung** [comment]
FYI - completed Feb 19
