### ISSUE TITLE
Hive directory theme design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#262]
Complete the last bits of remaining design work. 

### RACI

* Phase: Design
* Owner: @ldecoursy 
* Decision Maker: @leahatplay 
* Design Lead: @adiladiladil
* Development Lead: n/a
* Quality Verifier: @iamjessklein 

### Audience
Hives. 

### Success
Implement new design for https://directory.hivelearningnetworks.org/ 
Coded then linked from hivelearningnetworks.org as well as individual city sites

Final edits to complete this design: 
https://redpen.io/p/nc006adb3a6d09c802
- [x] Need copy for homepage - https://github.com/MozillaHive/Directory/issues/1
- [x] Pull footer from hivelearningnetworks.org
- [x] Remove "Our Tools" from homepage
- [x] Block out expertise tags on individual profile pages, and try staggered buttons for expertise exchange vs. grid. 
- [ ] Finalize icons/pictograms for front page of directory

**Comment by ldecoursy** [comment]
@leahatplay @jvallera 

I'm happy to be owner, but know you two have been working more closely on this. Think we're close to wrapping it (before Jan 30?) or we can add to next heartbeat.

**Comment by iamjessklein** [comment]
I updated the RACI to reflect changes. 
@adiladiladil will be demo-ing where he is with all of the work on Monday.  
He has started posting his work on [redpen](https://redpen.io/p/nc006adb3a6d09c802) that could use some feedback.

**Comment by iamjessklein** [comment]
Based on our check-in, here is what we are committed to shipping by Friday, January 30th:

- [ ] on landing page: decrease the size of the "node" field
- [ ] insert orange navigation on every page of the site
- [ ] make styling consistent
- [ ] clean up the expertise exchange page : create more of a stylized list/directory rather than image/icon driven - add expertise tags to individual profile page
- [ ] change name from Hive Hub - to  Hive Directory
- [ ] file implementation tickets for future heartbeat :heart: 

cc/ @adiladiladil @ldecoursy @leahatplay

**Comment by ldecoursy** [comment]
@iamjessklein @adiladiladil All comments are in RedPen. Do you want me to also add here?

**Comment by davidascher** [comment]
@iamjessklein any update on how much was done by Jan 30 as you mention in a comment above?  Any of those checkboxes tickable?

**Comment by ldecoursy** [comment]
@davidascher We have a call at 2:30 today to review and make sure changes have been made.

**Comment by ldecoursy** [comment]
Just had call with @adiladiladil @iamjessklein @leahatplay @jvallera to review latest redpen: https://redpen.io/p/nc006adb3a6d09c802

Here are the final edits to complete the design: 

- [ ] Need copy for homepage - will do a separate ticket [to come]
- [ ] Pull footer from hivelearningnetworks.org
- [ ] Remove "Our Tools" from homepage
- [ ] Follow-up from above list - block out expertise tags on individual profile pages, and try staggered buttons for expertise exchange vs. grid.

**Comment by OpenMatt** [comment]
@cassiemc should we move this to Feb 13 milestone?

**Comment by OpenMatt** [comment]
* I tried to clean up and edit this ticket a bit based on @ldecoursy's final to-do list.

**Comment by ldecoursy** [comment]
@adiladiladil copy is here: https://hive.etherpad.mozilla.org/directorycopy

What do you think of using the Connections, Skills icons from below?  Maybe keep the chat icon currently in the mockup for the Discover section: 
![hive-platforms_mockup_03](https://cloud.githubusercontent.com/assets/4885898/6043663/cecae6be-ac5b-11e4-8ce5-adac1d687327.png)

**Comment by ldecoursy** [comment]
@iamjessklein @adiladiladil I think the latest redpen looked good, so only remaining change is to decide on icons and add in draft copy per above. Should we try to check in quickly on Friday?

**Comment by iamjessklein** [comment]
@ldecoursy agreed - I would decouple the copy from this ticket so that we can finish the design theme-ing and then handle the copy edits and such on it's own.

**Comment by ldecoursy** [comment]
Latest redpen is here: https://redpen.io/ue61afa56796613219 @leahatplay can you review/approve icons?

**Comment by ldecoursy** [comment]
@iamjessklein I'll be on PTO starting today through next week, would you mind closing this ticket if pictograms finalized by Friday?

**Comment by iamjessklein** [comment]
Will do :+1:

**Comment by adiladiladil** [comment]
@iamjessklein latest redpen is here
please take a look and let me know if all looks good

https://redpen.io/xz5ec75b96ae8763a0

**Comment by iamjessklein** [comment]
whoops @adiladiladil  - I think I looked at the wrong ticket. Yes it looks great to me. The revised icons look perfect. :+1:  :shipit: 

![red-pen-0fd53ed4-2d99-4ac9-f3da-5293fceea22d](https://cloud.githubusercontent.com/assets/535012/6234856/ea62a8a8-b6ab-11e4-8673-f5bb62f71691.jpg)
