### ISSUE TITLE
Decide whether to allow issues on webmakerprototypes.org repo

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#265]
Per email conversation to all@, should we direct issues on the [webmakerprototypes repo](https://github.com/mozilla/webmakerprototypes.org), or should we point them here?

**Comment by davidascher** [comment]
Plan issues are one per initiative broken down in a heartbeat effort chunk.
Detailed issues and bugs still belong in issues nearer the code. Hope this
makes sense.

**Comment by dajbelshaw** [comment]
Thanks @davidascher! So if I understand you correctly:

* technical/procedural stuff should go on the webmakerprototypes repo
* strategic stuff that is broken down into hearbeats belongs here on /plan

:)

**Comment by davidascher** [comment]
Maybe, I'm not sure what you mean by the latter.  In general, the `plan/issues` list is how we coordinate across activities in a given heartbeat.  It's 99% about resource prioritization and scheduling.  The actual meaty discussion happens in other repos.  That can very much include strategic discussions around purpose, benefit, etc.  And when it's ready to be scheduled by the production process, then it shows up in the `/plan`.  Does that help?

**Comment by davidascher** [comment]
Anyway -- in general, my stance is that any repo associated w/ code which a) is not dead to the world, and b) isn't tracked in another bug tracker should have issues enabled, and there should be someone who monitors those.

**Comment by dajbelshaw** [comment]
Alright, I think we're in alignment here so will close this and encourage others (including @iamjessklein) to post issues to the [webmakerprototypes.org repo](https://github.com/mozilla/webmakerprototypes.org)

**Comment by iamjessklein** [comment]
:+1:
