### ISSUE TITLE
Teach the Web talk - 4th installment February

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/plan#266]
Starting new issue around the next TTW Talk in February- with @LucyeoH 

- [ ] review Januarys call and feedback from community
- [ ] analyse all comms channels, discourse, twitter, wiki and hangout
- [ ] Speaker shortlist required
- [ ] Date for Feb talk confirmed

**Comment by secretrobotron** [comment]
@LucyeoH !!

**Comment by Saallen** [comment]
These guyse?- http://100cameras.org/

**Comment by LucyeoH** [comment]
Yup! Amira put us in touch with them. Original plan was to talk to them about telling stories of your event through photography.

**Comment by hannahkane** [comment]
Moving this to the new mozilla-learning repo: https://github.com/MozillaFoundation/Mozilla-Learning/issues/49
