### ISSUE TITLE
Finalize first MakerFox prototype and present 4 additional concepts

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#267]
To meet our goal of presenting 5 prototypes by the end of Q1, we are going to continue to refine the first prototype that @xmatthewx and @toolness have built as well as begin exploring options for 4 additional concepts.

### Roles
Phase: Research
Driver: @secretrobotron
Decision-maker: @davidascher
Lead design: @xmatthewx
Lead dev: @toolness 
Quality: @thisandagain 

### Deliverables
- [ ] Finalize first prototype (#124)
- [ ] Present >= 4 additional concepts (paper prototypes or even rough sketches) for review
- [ ] Communication of progress through blog (on webmaker.org?)

(Edit: @thisandagain on 2/2/2015)
(Edit: @secretrobotron ᕕ( ᐛ)ᕗ on 3/2/2015)

**Comment by secretrobotron** [comment]
Helpful framing from a meeting with @davidascher: https://etherpad.mozilla.org/coolstuff

**Comment by davidascher** [comment]
5 prototypes is a Q1 goal.  We should break it down into a 2 week sub-task IMO.

**Comment by thisandagain** [comment]
Edited title and description to have clear SOW for this sprint.

**Comment by simonwex** [comment]
When adding devs to the RACI, please leave the needs-dev flag so I can work it into my matrix.

cc @thisandagain, @secretrobotron

**Comment by secretrobotron** [comment]
### *Update*
* @xmatthewx and @toolness will find some time soon to finish off initial prototypes
* @xmatthewx has had some conversations with colleagues to generate some ideas
  * he has recordings and will compile ideas/conclusions from them
* they are having a well-deserved coffee after a no-doubt delicious lunch

**Comment by secretrobotron** [comment]
### *Update*
* @xmatthewx needs someone to poke at the current prototype; wants it to become a real add-on
  * test interaction: found content -> making a thing
  * @davidascher to check out http://xmatthewx.github.io/webmaker-addons/ to see if it's on right track
  * http://xmatthewx.github.io/webmaker-addons/reference.html
  * might be worth pulling @flukeout's code in because it's pretty nice (and does the same stuff)
* @xmatthewx putting together list of principles that makers would want from the browser
  * e.g. "make with my hands" -> what are the implications? -> for firefox/browser?
* cool ideas that @xmatthewx should write down here!

**Comment by xmatthewx** [comment]
a marketing benchmark worth discussing. watch the video: https://thegrid.io/

**Comment by jgmac1106** [comment]
This was feedback I think on the earlier ticket about the image editing prototype wire frame. I really like it.

Late on the feedback but just wanted to add in my two cents:

- My primary way for doing quick image edits is either Skitch (though I use it less now that it kruffs up my Evernote)
- Snag-It for Chrome (both the extension and app)

These are more for quick tutorials. Snag-It for Chrome (especially the 20 sec gif) have become essential in my workflow as a teacher and webmaker mentor.

For more artsy stuff I use something like Canvas.com (desktop)or FontCandy on iOS and Video to Gif (on Android)

If I get really stuck I have even build things in Thimble (movie poster) and then just take a screenshot

Based on the wire frame it seemed folks were shooting for a similar tool such as Canvas or fontcandy.

Not sure what the other tools 4 tools you will be prototyping but screencasting in Chrome is awesome. I haven't looked in awhile to see if there are already extensions in Firefox to use but I would dig it if one does or will exist.

**Comment by secretrobotron** [comment]
Filed follow-up in #335.

**Comment by xmatthewx** [comment]
@toolness drafted a plugin to leverage the prototype. It's working well. Just a few things to tweak so it  plays nicely with the dom. He'll iterate on the UI to bring it in line with reference.html. We should be in good shape for a demo on Friday and testing soon after. 

I feel good about the evolving state of our concepts. Slides that convey each idea in a screen or two still needs work. I will dedicate a bit of time in Toronto on that storytelling.

**Comment by toolness** [comment]
[The addon is here](https://xmatthewx.github.io/webmaker-addons/addon/webmaker-addon.xpi), and it's also linked-to from a section of the repository's [README.md](https://github.com/xmatthewx/webmaker-addons#firefox-add-on).

**Comment by secretrobotron** [comment]
@toolness do you mind summarizing how far you made it with the prototype here? We can continue work  in #335.

**Comment by toolness** [comment]
yep i have an errand to run this AM but will do this first thing when i get
back!

**Comment by OpenMatt** [comment]
Cool. Please try to update status before today's Heartbeat Planning meeting. (1pm ET.)

**Comment by xmatthewx** [comment]
Summary of concepts: 
 - **Writable web**: navigate to any unused page, domain, textarea and use an intuitive GUI to create new content 
 - **Version control**: bring visual version control and collaboration to any site
 - **Find, make, share**: collect text and images, add your mark, and share as you please
 - **Visual dev tools**: an intuitive view of the code behind web pages. tools for collecting colors, fonts, libraries, and snippets  
 - **Custom  viewports**: readability for visual thinkers. render pages, navigate links, and collect browser history with experimental user defined controls 
 - **Hackable hardware I/O**: Build usb controllers and displays, programmable with javascript, independent of OS. Provide UI for 'things' on local network.  
 - **Paired browsers**: Pair browsers across FF accounts. Use your mobile as shortcut palette. Leverage the camera and accelerometer as paintbrush to draw on desktop. 

Next step would be to choose the strongest options and run them through these filters and then prototype: 
 - A browser for who? What do they make?
 - Why as the browser? (rather than an app or a device)

Slides below also [on dropbox](https://www.dropbox.com/sh/2d0n1tl78focgz0/AACz72kd-dGqZrHl2s4m2LJGa?dl=0)

![makerz](https://cloud.githubusercontent.com/assets/53411/6232912/46e52754-b69d-11e4-8802-0cb42ab2492c.png)

**Comment by thisandagain** [comment]
Awesome. Thanks @xmatthewx . Tracking next steps here: #335

**Comment by toolness** [comment]
Ok, here's my share-back.

We made an "Image Maker" add-on. The GitHub repository is at [xmatthewx/webmaker-addons](http://github.com/xmatthewx/webmaker-addons), and you can [download the add-on XPI](https://xmatthewx.github.io/webmaker-addons/addon/webmaker-addon.xpi) to play around with it too.

The add-on puts a sidebar in your browser that lets you play with any images you encounter on the web via a "+" icon that appears as you hover them. Here's an example of it in action:

![basic-usage](https://cloud.githubusercontent.com/assets/124687/6233566/b2a7c06a-b6a1-11e4-8ac6-7f209b714a7e.gif)

**The composition in this sidebar is synced across Firefox accounts.** Thus, for instance, you can start a composition on your desktop and finish it on your laptop.

Once finished with your make, you can click the share icon at the top-right of the sidebar, which gives you a few options:

![share-dialog](https://cloud.githubusercontent.com/assets/124687/6233584/d4e88da8-b6a1-11e4-8660-0d6310569aee.jpg)

Clicking the download icon gives you a PNG of your creation:

![cool](https://cloud.githubusercontent.com/assets/124687/6233588/ed011dc4-b6a1-11e4-870a-3a92785533fd.png)

An interesting feature of this PNG (including the one embedded above!) is that **we've embedded the original source information about the make inside it**, using the same technology that powers [baked open badges](https://github.com/mozilla/openbadges-backpack/wiki/Badge-Baking). This means you can drag the image into the sidebar to continue to remix it:

![drag-and-drop](https://cloud.githubusercontent.com/assets/124687/6233637/54e36dca-b6a2-11e4-8bd7-5f1166b46e0c.gif)

Finally, clicking on the Webmaker logo in the share modal gives you the HTML for remixing your work in Thimble:

![thimble](https://cloud.githubusercontent.com/assets/124687/6233667/97fb9c2c-b6a2-11e4-8bce-053e54fd9cc5.jpg)

That's about it so far. Today I'll be fixing up some rough edges in the add-on, so it might not look exactly like the images above if you use it now.
