### ISSUE TITLE
Implement timezone.io for MoFo

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#268]
I came across [timezone.io](http://timezone.io/) via this week's Remotive newsletter. They use it at Buffer to help with timezone awareness. 

The code is [on GitHub](https://github.com/djfarrelly/timezone).

Would be awesome to have just to quickly grok who's where and when. Not sure what happens when people are travelling, but it's a start. :)

**Comment by davidascher** [comment]
Neat!  Agree that making timezone awareness more ambient would be lovely. I may play around with a tweak to that approach that uses github teams to figure out who to display, and some easier way of updating timezones.

@dajbelshaw: apart from the fairly amorphous "awareness," are there specific scenarios where you feel it'd be most useful? scheduling meetings, … ?

**Comment by dajbelshaw** [comment]
Yep, @davidascher I reckon there's a few occasions it could be useful:

* Scheduling meetings
* Getting a sense of who works together where*
* Showing geographic spread of Mozilla to external world

If we reduced the icon sizes, could include Super Mentors / ReMos too? :)

\* More important than you'd think - explains many things. ;)

**Comment by ldecoursy** [comment]
@davidascher would this be better served as a ticket in the github playground repo? https://github.com/MozillaFoundation/github-playground/issues

**Comment by dajbelshaw** [comment]
Just to say that the Open Knowledge Foundation saw this after my blog post and have implemented it: https://remoteworker.wordpress.com/2015/02/12/time-team/ :)

**Comment by cassiemc** [comment]
Tagging this as food for thought in #652, otherwise closing.
