### ISSUE TITLE
Bring 'Views' data from Google Analytics into the Product

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#269]
At various points on webmaker.org, and for admin tools we are building it would be useful to have a measure of the `consumption` popularity of any given make.

* Show a user how many times their make was viewed. 
* Show an administrator the most viewed makes (even if they haven't received likes and shares)
* Help a user search for content using popularity as a sort mechanism.
* Teach web literacy skills around popularity as a feedback mechanism.

### Audience
This first round of work would make the data available to devs to develop further features with the data. In the long run it should benefit all users.

### Success
This data will play an equivalent role to the views data on YouTube (for creators and consumers).

### Vision
One solution would be to periodically cross check our database of makes with the data in Google Analytics and update a totalViews count in the MakeAPI.

### RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier:

**Comment by davidascher** [comment]
+1  This is what motivates at least some of our users, it's important to
share that back w/ them.

Q as to whether GA is the only way we can do that, or whether there are
alternative methods (and pros/cons).

**Comment by thisandagain** [comment]
Thanks for filing @adamlofting 
Prompted from original discussion here: https://github.com/mozilla/webmaker.org/issues/1098

**Comment by adamlofting** [comment]
@davidascher I'm sure there are lots of ways we could do this. Though if we roll our own, we can also make use of the historic data in GA.

**Comment by davidascher** [comment]
I suspect the dependency on the MakeAPI isn't actually a hard one.  We want to answer the use cases described in the initial comment, but the MakeAPI need not be involved.

**Comment by hannahkane** [comment]
@adamlofting - what do you recommend we do with this ticket? Assign to a 2016 milestone? Close it?

**Comment by adamlofting** [comment]
I'm going to close the ticket but cc @xmatthewx to put this in a relevant road map if it's needed in 2016.

The architecture has changed a bit since this ticket was first written.
