### ISSUE TITLE
Prepare Canadian Webmaker app product demo

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#271]
@msurman and @humphd  will be at an event on February 17th during which Webmaker app will be demo'd on FFOS and Android phones.

### RACI
Driver: @secretrobotron
Decision: @davidascher 
Dev: n/a
Design: n/a
Consulted: @thisandagain, @k88hudson 
Quality: @humphd 

- [x] Acquire 3 FFOS phones (1 per human + backup)
- [x] Acquire 3 Android phones (1 per human + backup)
- [x] Install Webmaker on each of those phones
- [x] Test Webmaker on each of those phones
- [x] Create demo script for @msurman and @humphd to use to show people how they can make apps
  - This is probably very similar to the MWC script
- [x] Deliver phones and scripts

**Comment by secretrobotron** [comment]
Depends on #72, #78, and #235.

**Comment by k88hudson** [comment]
Note that the specs for devices should be as follows (this is what we'll have for MWC):

```
Firefox OS 2.1 / Flame
Android 4.4 / Nexus 5 or Alcatel OneTouch Pop 2
```

**Comment by thisandagain** [comment]
Confirmed on Nexus 5 running Android 4.4 for MWC demo

**Comment by secretrobotron** [comment]
Demo script should have some talking points:
- problem we're addressing (what's going on the mobile world and global markets)
- why mozilla is involved
- why we're building an app
- what you can do with the app
- virality
- tada!
- join us

**Comment by secretrobotron** [comment]
Got some phones, and script is underway. Just waiting on @benrito to help craft some talking points.

**Comment by secretrobotron** [comment]
jlin made this nice tutorial for flashing the phones: https://gist.github.com/jlin/f60a7a6c0b75c2c9aee9

**Comment by secretrobotron** [comment]
Having a bit of trouble with package-creation for the FFOS version. @k88hudson is looking into it. Should be able to just flash it onto the phone with dev tools if needed.

**Comment by secretrobotron** [comment]
For testing: https://github.com/mozilla/webmaker-app/issues/874#issuecomment-72544047

**Comment by secretrobotron** [comment]
ᕕ( ᐛ)ᕗ everything's delivered! Sent an email to @humphd and @msurman to let them know what to do. They can get in touch with me on Tuesday if things go wrong, but there should be more people around to help out anyway! :boom:
