### ISSUE TITLE
Create MWC product demo script for Webmaker app

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#272]
### RACI
Phase: Design / Build / Ship
Owner: @thisandagain
Decision: @davidascher 
Quality: @cassiemc

Produce demo script for Canadian audience. Can be a beta for the MWC script (#235), and involve many of the same ideas.

blocks #271

**Comment by thisandagain** [comment]
Can we just track this in #271 ?

**Comment by secretrobotron** [comment]
:+1:
