### ISSUE TITLE
Design Web Literacy Map v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#275]
*Adding this manually as https://build.webmaker.org/intake seems to be down right now?*

The Web Literacy Map v1.5 update (#184) is an iteration on the current version (1.1). Per last week's community call we'll be retaining the competency grid view, but also experimenting with other ways of representing the skills under the competencies. 

Exhibit A: @LauraHilliger's [Web Literacy Learning pathways](https://laura.makes.org/thimble/web-literacy-learning-pathways) prototype

To do:
* Create updated version of competency grid view *(new/altered competencies)*
* Explore new ways of representing all of the skills contained in the map

We should have everything finished in terms of a review of skills by the end of February at the latest. We're looking to launch v1.5 at the end of Q1.

/ cc @cassiemc @iamjessklein @sabrinang

**Comment by thisandagain** [comment]
The link moved: https://build.webmaker.org/add

**Comment by dajbelshaw** [comment]
Cool. Could we get a 301 redirect for stuff like this @thisandagain? :)

On a related note, the URLs for the Web Literacy Map resources section changed this week (added a /literacy/ in the middle). This breaks a lot of links that exist in teaching kits and elsewhere on the web. Would be great if we could:

* Add redirects / update .htaccess rules when this happens 
* Give those affected a heads-up (or even better warn in advance!)

**Comment by davidascher** [comment]
The changed link on build doesn't seem like a big deal (the audience is
tiny) but we can add a route. The link change on the weblitmap worries me
more from a process POV.

Agree we should fix it. Can you please file a new issue under webmaker.org
in github?

**Comment by dajbelshaw** [comment]
Added a **March 13** milestone to this and pinging @iamjessklein. Let's talk at the end of February about how we should approach this. :)

**Comment by hannahkane** [comment]
Happy to have this in the March 13 milestone for now, though when that heartbeat planning meeting comes up, we'll have to look at this in the context of the other work that's in the queue and resources available.

In the meantime, I think we can "groom" this further via the Web Lit Map meetings, so that when it does get loaded into a heartbeat it's clear and scoped.

**Comment by cassiemc** [comment]
sounds like a plan. and @dajbelshaw if you want to walk through how the scoping process works i am more than happy to jump on vidyo with you at some point! opaque isn't ideal and you can probably help us make it better :)

**Comment by dajbelshaw** [comment]
That would actually be awesome, @cassiemc. Will send you and @hannahkane a Vidyo meeting request for next week - let me know if it works for you. :)

**Comment by iamjessklein** [comment]
:+1:  nice!!!

**Comment by cassiemc** [comment]
yes, thanks for setting that up @dajbelshaw, will be there!

**Comment by hannahkane** [comment]
This is a task within the teach site design and build, so I'm closing this here.
