### ISSUE TITLE
Design features to enable mentors to organize groups

### ISSUE THREAD

**Issue by LucyeoH** [MozillaFoundation/plan#280]
School groups that use Thimble to teach HTML set up generic Webmaker accounts in case students can't/won't set up their own accounts. These accounts become littered with with <a href="https://mozillafoundation.github.io/plan/images/alot.png">a lot</a> of cruft that other users of the account shouldn't have to sift through, nor should have write/delete access to.

## Audience:

School group leaders, mentors.

## Success:

We design a system that allows for the easy organizing of makes created by many webmakers who sign in as a mix of guests and authenticated webmaker accounts. We make these makes easy to find and re-assign (when created by guests) by mentors.

## Vision:

The solution, I believe is a few parts. 

First, allow the creation of guest accounts on Webmaker. These would allow users to publish makes organized under an event or a mentor's account, tagged appropriately.

Secondly, create a landing-page generator that defaults any makes made within a time box to be tagged with a mentor-specified tag. 

Third, surface those tags in an easily-organized display for mentors and give them access to re-assign/ expire content created by guests.

## RACI:

* Phase: 
* Owner:
* Decision Maker:
* Design Lead:
* Development Lead: 
* Quality Verifier: 

### Original ticket:
<blockquote>
We received a feature request that I thought was kind of interesting.

A group that uses Thimble to teach kids HTML in schools in Canada has setup a generic Webmaker account for schools to use in case students can’t/ don’t want to set up their own (not an uncommon practice). So, they end up with A LOT of projects in their account.

They wanted to know: 
"Is there any way to create folders? And, is there some where we can add a “note to users” in our account? We would like to let them know how long their content lives in our account and our “honesty” rule - no sabotaging other projects!"

I think it's an interesting request in and of itself but also is indicative of how educators are using the tools. (I know of other groups that do this "generic" account thing). 

I wasn't sure where to file this so feel free to move! 

cc. @cassiemc @thisandagain @simonwex 
</blockquote>

**Comment by davidascher** [comment]
Interesting scenario.

My guess is tags and tag-based searches could work as well? They're way
easier to manage on the design and dev side IMO.

**Comment by LucyeoH** [comment]
That's actually what I recommended and is how Ladies Learning Code manages their generic account, though I've also seen them have some trouble with it (it can be hard to get a room full of kids to all add the same tag). I wonder if there's a way we could incorporate a "teacher account" into the new tool? Just a thought!

**Comment by hannahkane** [comment]
Just a note that this is very much in line with what we're envisioning for Clubs on the site—basically, the idea of connecting individuals and their projects to a "Club" asset. See v1.2 and v1.4 on the Learning Networks product roadmap: https://wiki.mozilla.org/Learning/Networks/Product-Roadmap

**Comment by simonwex** [comment]
I think a tag approach also makes sense for the underlying architecture. It makes discovery surface in a predictable way and lets us build many user-facing features without significant underlying changes. This doesn't cover the user story for an easy way to add those tags, though.

I think the deliverable for this planning ticket is to do some design and user testing around group and bulk tagging. 

I'm going to rejig the original ticket to reflect this, holla if I miss something, @LucyeoH

**Comment by hannahkane** [comment]
Before we move forward on this, do we need to have a larger conversation about how we're supporting legacy tools? Thoughts on that? @davidascher @simonwex @thisandagain @ldecoursy @claw

**Comment by simonwex** [comment]
Yes. These changes would primarily impact our login system and the MakeAPI, and hence only have a minor impact on specific tools (thimble etc).

I would think the UI would actually live on the clubs functionality and so I'd like to see this part of the work you're spec'ing, @hannahkane.

**Comment by hannahkane** [comment]
I'm tempted to close this ticket, as this issue will come up again when we're building out Clubs functionality later in the roadmap. Is that alright with everyone, or do we need a band-aid fix in the meantime, @LucyeoH ?

**Comment by LucyeoH** [comment]
@hannahkane totally fine to leave this, my main goal was just to create a record of these kinds of queries in case they're useful for the new tools team. I also have a spreadsheet where I'm keeping track of them and I can raise them when we're looking to build this stuff out.

**Comment by hannahkane** [comment]
Thanks, @LucyeoH. Closing this for now, and will discuss again a little further down the roadmap!
