### ISSUE TITLE
Write design brief for HiveLearningNetworks.org web site improvements

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#282]
### RACI
* Phase: requirements gathering
* Owner: @ldecoursy 
* Decision Maker: ???
* Design Lead: not needed this Heartbeat (@cassiemc if you need a pair of eyes)
* Development Lead: not needed this Heartbeat.
* Quality Verifier: @hannahkane 

**GOAL:** document strategy, goal and requirements for incremental, "version 2.0"  HiveLearningNetworks.org web site improvements. Focus is on adding **dynamic content.**
* **Audience:** MoFo designers and developers. To understand what's required, who the user is, business requirements, etc. 
* **Success:** clearly defined strategy and reqs colleagues can understand.

* Note: no design work needed this Heartbeat. We're just prepping a brief to give to designers.

**Comment by OpenMatt** [comment]
@cassiemc heads up that this is in motion. no design work needed this Heartbeat, but could be good to have a designer involved in the requirements gathering. or: to use a design brief template you already have / prefer.

**Comment by cassiemc** [comment]
I think this is actually @thisandagain and Product team territory, but happy to lend my eye on any briefs if we need design feedback.

**Comment by ldecoursy** [comment]
@cassiemc Previously we'd been working with Studio MoFo and @sabrinang to think through where new content would live on the site.

**Comment by cassiemc** [comment]
ok cool thanks for the update @ldecoursy

**Comment by ldecoursy** [comment]
@cassiemc is there a design brief template or any key details we should make sure to address?

**Comment by cassiemc** [comment]
@ldecoursy I don't have one onhand but could put something together tomorrow. Wondering if @edrushka already has something though?

**Comment by edrushka** [comment]
No, we don't have a design brief but here are the questions we walk people through on our intake process. Some of them may be useful. https://docs.google.com/a/mozillafoundation.org/spreadsheet/ccc?key=0AorEOP1A0tc0dHl6YVd6dU5Da0pwVlVCaG5uNWNkaVE&usp=drive_web#gid=2

**Comment by ldecoursy** [comment]
Thanks @edrushka! Simona and I started a draft here in the meantime: https://hive.etherpad.mozilla.org/hlnv2

**Comment by cassiemc** [comment]
@ldecoursy @edrushka Both those documents are great already, thanks for sharing. It was helpful in whittling down a few more questions out of my tired brain. No doubt the other designers will have feedback on this (I filed a new issue here: https://github.com/MozillaFoundation/plan/issues/300) but in the meantime feel free to use this to supplement your brief (but certainly don't feel chained by it!)  https://docs.google.com/a/mozilla.com/document/d/1E6lhyYjty_eNUo2xVAKcde6h7Di2zI_iShcIcmlz9aw/edit?usp=sharing

**Comment by ldecoursy** [comment]
@cassiemc thanks for the additional questions/framing doc. Here's the updated version of the design brief: https://hive.etherpad.mozilla.org/hlnv2
