### ISSUE TITLE
Add 301 redirect to Web Literacy Map resources section after URL changes 

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#283]
*Filing per @davidascher's [suggestion](https://github.com/MozillaFoundation/plan/issues/275#issuecomment-72229097) in #275*

This week, URLs for the [Web Literacy Map resources section](https://webmaker.org/resources) started including an extra /literacy/ component. Clicking on an existing link without this dumps you back at the webmaker.org homepage.

This is probably an improvement in terms of URL structure, but the concern here is that there are links all over the web linking to discrete competencies (e.g. [Privacy](https://webmaker.org/resources/literacy/weblit-Privacy))

**Could we add a redirect?**

i.e. https://webmaker.org/resources/weblit-Privacy --> https://webmaker.org/resources/literacy/weblit-Privacy

*(this would need to apply for the entire section)*

**Comment by davidascher** [comment]
And when it comes to the future, see
https://github.com/mozilla/webmaker.org/issues/1207

**Comment by davidascher** [comment]
moved over to where the right people need to look at it.  https://github.com/mozilla/webmaker.org/issues/1208
