### ISSUE TITLE
 Test teach.webmaker.org wireframes 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#284]
Schedule ~6 user tests and report back on results and present in demo. 

### RACI
* Phase: requirements gathering
* Owner: @hannahkane 
* Decision Maker: @hannahkane
* Design Lead: not needed
* Development Lead: not needed 
* Quality Verifier: @ldecoursy 

Note: didn't get done in last heartbeat, so I'm P1'ing it this time.

Draft test plan: https://etherpad.mozilla.org/teachdotusertest

**Comment by OpenMatt** [comment]
@hannahkane please update RACI

**Comment by hannahkane** [comment]
Three tests completed so far. Two more scheduled so far. Will assemble notes shortly.

**Comment by hannahkane** [comment]
Four tests complete. Notes started here: http://mzl.la/1zhj6UQ

**Comment by hannahkane** [comment]
This round of tests is complete, so I'm going to close this ticket. Results/analysis here: http://mzl.la/1zhj6UQ
