### ISSUE TITLE
Conduct engineering assessment of badges platform

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#286]
Ensure we have a plan of attack on how to evolve our badges platform for the purposes of the Learning Networks goals.

### RACI

* Owner: @simonwex  
* Decider: @hannahkane 
* Lead dev: 
* Lead design: not needed (another issue explores UX I expect)
* Quality: @davidascher

Step 1: Meet with Hannah to discuss the requirements for the next iterations on the badging platform.
Step 2: Dig into the code to assess the state of it. 
Step 3: Make recommendation about how to best move forward technically to meet business needs

**Comment by davidascher** [comment]
Made a couple of edits to the description.

**Comment by OpenMatt** [comment]
Key decision for today is: should we start this work now, or punt to next Heartbeat, based on other engineering team priorities / MWC prep etc.

**Comment by OpenMatt** [comment]
@simonwex : what did we decide on this?

**Comment by OpenMatt** [comment]
@hannahkane @simonwex status? recommendations on whether we should tackle this Heartbeat? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by hannahkane** [comment]
I'd vote for removing it from this heartbeat. I'd rather focus limited resources on the teach site.

**Comment by OpenMatt** [comment]
K. pushing to next Heartbeat.

**Comment by hannahkane** [comment]
Marking this as a P1 for the March 27th milestone, because we plan to start work on badges in the following milestone.

**Comment by simonwex** [comment]
@hannahkane do we have the next-gen requirements explained anywhere?

**Comment by hannahkane** [comment]
https://github.com/mozilla/teach.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3Abadges

**Comment by OpenMatt** [comment]
Prioritization considerations discussed in today's Heartbeat planning meeting:
1) tech debt
2) teach.moz.org badging requirements
3) ensuring we don't fall behind on this file

**Comment by OpenMatt** [comment]
May be useful to do another kick-off meeting with key stakeholders here. + @chrislarry33

**Comment by OpenMatt** [comment]
@hannahkane: please add me to the kick-off meeting invite on this?

**Comment by OpenMatt** [comment]
@hannahkane: is this still the main piece of badges documentations for our 2015 strategy and requirements? https://docs.google.com/a/mozillafoundation.org/document/d/1oVGZcdearNxH5G2eF0D4dciaXxFiFfUkolYSdC9ufy0/edit#heading=h.ay9hvkzgtonw

**Comment by hannahkane** [comment]
Just sent an invite for a meeting.

@OpenMatt, that document is still accurate, though I'd like to focus on the needs immediately in front of us, which are articulated in the badges tickets that have been written: 

https://github.com/mozilla/teach.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3Abadges+label%3Aplatform

**Comment by OpenMatt** [comment]
Got it. Thanks. 
@simonwex and @davidascher : I've reviewed those tickets -- the scope and feature requests there are clear.

**Comment by simonwex** [comment]
Great. Something that we need to clarify is which systems and third parties are relying on what parts of the current badges platform. The outcome here will dictate how quickly we can evolve pieces the teach site needs.

**Comment by chrislarry33** [comment]
At this point there are nobody other then ourselves relying on this badge platform. Even theoretical deliverables in grants in house have no opinion or dependency about how we issues badges about our stuff

**Comment by OpenMatt** [comment]
@k88hudson joined to help us with some of this assessment

**Comment by OpenMatt** [comment]
More context on future potential badge feature requests: https://wiki.mozilla.org/Learning/Networks/Product-Roadmap

**Comment by OpenMatt** [comment]
* We should also include an analysis of a third-party option like https://credly.com

**Comment by hannahkane** [comment]
@k88hudson did awesome work here: https://drive.google.com/a/mozilla.com/file/d/0B9Spnx3qAl7pclBXWXBoQUppV0E/view?usp=sharing

Still to do this heartbeat: make a decision about how to move forward! 

Flagging @simonwex for next steps, including perhaps a discussion of credly as a viable option?

**Comment by simonwex** [comment]
I've requested a walk-through of the credly system. -- it's part of their sales process, but I've asked for a pretty high-level of tech. I'm hoping for it to be scheduled this Thursday.

**Comment by simonwex** [comment]
Meeting with @toolness, @k88hudson and @ScottDowne on Thursday to discuss tech. I'll update this ticket.

**Comment by hannahkane** [comment]
@davidascher and @simonwex - are you ok with closing this ticket, given #408, which I just added?

**Comment by simonwex** [comment]
@hannahkane yes, knowing that if credly isn't the path we end up going down, we'll open another issue.

**Comment by k88hudson** [comment]
:dancer: :dancer: :dancer:
