### ISSUE TITLE
Learner-focused messaging test for Webmaker product using Google Adwords

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#287]
The splash page project provided some early insights into topline messaging and value proposition statements for the new Webmaker product. While those insights proved useful as we prepare a go-to-market strategy for a new mass-market, we'd like to run further messaging test on fresh/new users by running an Adword campaign to drive traffic that is less aware of Webmaker's offering. 

### Audience
Mass-market of makers and learners with low to no awareness of Webmaker value proposition. 

### Success
A top-line message and value proposition that converts traffic into accounts and onboards them into engaged users. 

### Vision
Step 1) Setup and deploy a Google Adwords campaign to test messaging that drives traffic to Webmaker product. Adam and Paul to develop testing matrix and content. 

Step 2) (If necessary*) Setup a basic landing page experience that focuses primarily on top-line message and value proposition. Ex. welcome.webmaker.org template used in previous landing page tests in 2014. 

* It may be possible that we can gain necessary insight within the Google ads themselves - measuring success primarily through click thru rates - and be able to drive traffic directly to webmaker.org without any further changes. Still talking through best approach to get most meaningful results and open to input. 

### Measurement
Click thru rates on Google Adwords campaign, account conversion on webmaker.org and any other relevant, existing engagement metrics. No new tracking and reporting is required to support this test. 

### RACI

* Phase: 
* Owner: @hpauljohnson
* Decision Maker: @adamlofting 
* Design Lead: @flukeout 
* Development Lead: 
* Quality Verifier:

**Comment by adamlofting** [comment]
Thanks for filing Paul. This comment is mostly to CC myself :smile:

**Comment by cassiemc** [comment]
Adding @flukeout for design resource here as needed (p2)

**Comment by OpenMatt** [comment]
@HPaulJohnson status update?

**Comment by HPaulJohnson** [comment]
Adam and I have scoped this out and implementation will be limited to Google Adwords campaign. All traffic will be pushed to webmaker.org (and not a specially designed landing page). So no additional support is needed. 

Pushing implementation of Adwords campaign to this next heartbeat. Should be up and running by 2/25.

**Comment by OpenMatt** [comment]
Will probably finish in this heartbeat. Need to connect w. @thisandagain and @davidascher on product roadmap. understanding what the unified tool will look like, and testing those value propositions.

**Comment by adamlofting** [comment]
@HPaulJohnson do you want to assign this to me to drive this for the next stage? I can check in with @KevZawacki on your discussions about this so far.

**Comment by HPaulJohnson** [comment]
Phase I (setup) of testing is now complete. Will open a new issue for phase II and analysis.
