### ISSUE TITLE
Update webmaker.org get involved page

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#289]
GOAL: make sure the main on-ramp for contributors is up to date.
https://webmaker.org/en-US/getinvolved
* ensure it doesn't suffer from information density / decision density 
* audit the main pathways / flow to ensure they make sense and feel good for contributors
* make sure we're using metrics properly. data to guide our decisions.

**Comment by OpenMatt** [comment]
* We also need to think about linkage / flow between this page and build.webmaker.org
* High level:
1) get involved page: high-level. the *main* on ramp for contributors. with calls to action that are simple and well-packaged. 
2) build.wmkr.org: lower-level. More detail. Focused on our yearly, quarterly, and heartbeat plans and scopes. 

* curious potential contributors shouldn't necessarily have to dig into the vagaries of tickets and roadmaps and metrics right away. That's essentialy for *builders.* But not necessarily for all early potential *contributors.*

**Comment by OpenMatt** [comment]
cc @davidascher @thisandagain @cassiemc

**Comment by dajbelshaw** [comment]
Tangential but relevant: status of http://planet.webmakerprototypes.org (as tool for helping potential contributors immerse themselves in our world)

**Comment by OpenMatt** [comment]
* Given MWC and teach.webmaker.org work, I'm going to suggest punting this one to next Heartbeat

**Comment by OpenMatt** [comment]
Going to punt again. The fact we keep punting this is telling, however... I really want to dig into this with @humphd later this quarter

**Comment by cassiemc** [comment]
This doesn't seem like it's going to happen. Please reopen if I am mistaken.
