### ISSUE TITLE
Implement Hive Directory theme

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#291]
## RACI
* Phase: Development
* Owner: @ldecoursy 
* Dev Lead: ???
* Quality Verifier: @chrislarry33
* Consulted: @iamjessklein @leahatplay @adiladiladil @hannahkane

## Audience 
Existing and emerging Hives

## Success
Implement new user-friendly design to https://directory.hivelearningnetworks.org/, prototype created by @toolness 

## Vision
New Hive Directory linked from https://hivelearningnetworks.org, serves to better illustrate who is part of Hive, connect individuals and organizations, find and share expertise, etc.

Designs here: #262

**Comment by OpenMatt** [comment]
needs a quality verifier. not sure who.

**Comment by davidascher** [comment]
I predict we'll be in a crunch this heartbeat.  @ldecoursy, any specific deadlines that this work depends on that we should know about?

**Comment by ldecoursy** [comment]
@davidascher No specific deadline–I put as P2 to keep the work moving if possible. If we need to move to the following heartbeat that works.

**Comment by ldecoursy** [comment]
Moved to next heartbeat per notes above and since we're still finishing up design and copy.

**Comment by OpenMatt** [comment]
* This one got pushed back last Heartbeat, so should get special consideration this time around. 
* @ldecoursy is on vacation, so will need a new owner

**Comment by OpenMatt** [comment]
Also: is the design work done?

**Comment by OpenMatt** [comment]
Note also that @iamjessklein has limited availability this Heartbeat, because of design work week

**Comment by iamjessklein** [comment]
Yes the design work by Adil is done [final design on redpen here](https://redpen.io/xz5ec75b96ae8763a0)

Adil should be involved in the implementation from the design side. 

![red-pen-0fd53ed4-2d99-4ac9-f3da-5293fceea22d](https://cloud.githubusercontent.com/assets/535012/6234774/770041f4-b6ab-11e4-93d9-daebf3f6ca41.jpg)

**Comment by hannahkane** [comment]
@leahatplay will be the acting owner while @ldecoursy is on vacay. 

@iamjessklein  - can you clarify what the next steps are?

**Comment by davidascher** [comment]
Is this purely a visual refresh, or are there new capabilities specified in
the redpen?

**Comment by iamjessklein** [comment]
I believe this is a purely visual refresh. The theme needs to be applied to the wordpress site. 

cc/ @toolness

**Comment by leahatplay** [comment]
@simonwex we'll need a developer assigned to apply theme to wordpress site. @toolness has been doing this work to date

**Comment by toolness** [comment]
I'm happy to do the work myself, or show someone else the ropes (it's all vanilla django, and the developer will mostly just be touching the [templating system](https://docs.djangoproject.com/en/1.7/topics/templates/) which is pretty easy to learn).

**Comment by hannahkane** [comment]
Process question for @simonwex: for P2s, do we have to wait to assign developers until we know we have time for it during the heartbeat? @toolness - are you currently assigned to a P1?

**Comment by hannahkane** [comment]
So, @toolness, as per our recent chat, you're available to work on this now? That would be rad.

**Comment by toolness** [comment]
I think so... I think this week I will be helping with this ticket and helping jbuck with https://github.com/MozillaFoundation/Mozilla-Learning/issues/75. Leah is pinging the designer now to get the assets to me so I can start implementation.

**Comment by toolness** [comment]
Hey, just so it's documented here, I talked to hannah on IRC and my priority this heartbeat is  https://github.com/MozillaFoundation/Mozilla-Learning/issues/75 and related issues.

I also wanted to note that the new directory "theme" is actually not *strictly speaking* a theme, i.e. it won't merely require changes to CSS/HTML/template files. It will also require some changes to underlying database models; for example:

* Each Hive org listed on the front page of the site will need to be "found" somehow, e.g. by adding a boolean flag to the Organization model for "is primary Hive HQ organization for city". The individual members listed on that front page may need to have flags for whether they are to be listed on that front page, too.

* The City model will probably need to have a latitude/longitude added to it, so it can appear on the map on the front page.

* The organization listing in the new theme shows a square image thumbnail for each organization, but there's currently no explicit field for the thumbnail in the database. (Some existing orgs do have an `<img>` tag linking to a logo in their description, but that's not quite the same thing.)

* Similarly, in the expertise exchange, there aren't thumbnails associated with each expertise. (Also, it should be noted that the new design will make it harder to implement https://github.com/toolness/hive-django/issues/52 .)

Those are just some of the back-end changes the new theme will require, I can submit a more complete list if you need!

**Comment by davidascher** [comment]
Turning each of these into an issue on the right repo would be good.

**Comment by ldecoursy** [comment]
Quick update that @adiladiladil has sent the final design assets to @toolness @leahatplay and I.  

Think @chrislarry33 had a few thoughts about this - will connect the dots then work to get the issues above into the Learning Networks repo.

**Comment by hannahkane** [comment]
Pausing this (i.e. removing from milestone) to allow for creation of a plan to integrate Hive tooling into broader Teach platform.

**Comment by chrislarry33** [comment]
Agree, pause here.

**Comment by ldecoursy** [comment]
@hannahkane Just checking if we should close this and reference in another issue as part of Q2 planning.

**Comment by hannahkane** [comment]
I'll open a ticket for Directory planning and put it in the next milestone. Will link to this for reference, but let's close this for now.
