### ISSUE TITLE
Ongoing updates on Mozfest progress

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#293]
Revised ticket to be an ongoing place to update Mozfest's progress. 

Document the broad strokes of strategy. Draft key strategy questions we need to ask. 

## RACI
* Phase: Planning and consultation
* Owner: @thornet 
* Decision-Maker: @msurman 
* Consulted: MozFest Team

Start working on them asynchronously where possible. To maximize use of New York work week time with Mark Surman Feb 9 - 11.

**Comment by OpenMatt** [comment]
MozFest 2015

    Deliverable: draft strategy and planning questions we want to answer re: MozFest 2015.

    TASK: Michelle: draft what questions they needed from Mark. Bring to Ops meeting Feb 3. 

    TASK: meet face to face. In NY Feb 9 -11 when Mark is there. BUT: let's start now. instead of just waiting til then. 

    Key questions: what changes (if any) do want to make to the model. Conceptual design / strategy. 

    e.g., series of minor league MozFests?

    week-long mini events?

**Comment by OpenMatt** [comment]
@thornet : trying to push this out of email and skype chats into the open for easier high-level tracking. 
next step here is, I believe, for you to draft some high-level questions we need to discuss and answer together. then start the ball rolling. 
* NOTE: ** they were hoping some of that could be started in time for Feb 3 Ops meeting. Possible? **

**Comment by OpenMatt** [comment]
CC @ldecoursy

**Comment by OpenMatt** [comment]
Update from Dr. Claw 

### Dates
favoring Oct 23 - 25 in Ravensbourne. 
alternatives are the weekend before and after. 

** Decisions we'll make in NYC next week: **
* **Determine the overall structure of MozFest** (the tracks, the main highlights in the agenda, the duration) to determine how we best service our current needs. For example, we may want to extend the festival by a day to have a bigger community meet-up, a la last year's Hive Global one. Also, leveraging opportunities like BBC"s Make it Digital campaign in September for more fringe activities. 
* ** Identify key milestones in the calendar** where we're developing and preparing Mozfest's program. 

This includes how to tie Webmaker Clubs + our campaign(s) to Mozfest as well as internal planning meetings. 
* Settle on core team roles, including Aspiration's. 
Next steps after NYC: 
* Kickoff call with Ops & Engagement teams.
* Send a Save the Date.
* Recruit Space Wranglers.

**Comment by OpenMatt** [comment]
* This was discussed in NY work week
* Next step write down the plan somewhere

**Comment by edrushka** [comment]
Adding myself to this issue. Looking forward to reading the plan!

**Comment by thornet** [comment]
Claw is presenting date options in Ops today. Sarah is summarizing our programmatic plan by Wed.

**Comment by thornet** [comment]
Update: Ops and Mozfest now leaning towards Nov 6 - 8 due because it reduces costs and we'll have full access to Ravensbourne. 

Also previewing a program architecture of Lead, Teach, Make. Meaning the first day will be dedicated to our core, leading community (fellows, regional coordinators, facilitators).

**Comment by thornet** [comment]
Meeting request in progress with @msurman and @Saallen. 

@Saallen: would you mind setting up a wiki page with our latest thinking, esp. dates and the Lead, Teach, Make arc? Can link from: https://wiki.mozilla.org/Mozfest

**Comment by thornet** [comment]
Moving to March 13 Heartbeat since our chat with Mark hasn't happened yet due to MWC.

**Comment by Saallen** [comment]
Hey @thornet 
Have the Roadmap page mapped out already but was waiting for a confirmation from all sides on the date for this year.  Will get it all on wiki this week :+1:

**Comment by secretrobotron** [comment]
Interested. Leaving my mark :).

**Comment by thornet** [comment]
Talk with Mark scheduled for Mar 18. Moving this to March 27 heartbeat.

**Comment by thornet** [comment]
Reviewed strategic outcomes with Mark & @Saallen: 

* 1. Rally around a common cause: "Help people wield the web."
* 2. Experience the Mozilla Learning vision.
* 3. Be systematic about bringing, celebrating and up-leveling leaders.

Plus organizing goal: Document how we do Mozfest. 

Week of March 30 reviewing programmatic allies. Goal to prepare a briefing with Ops and then publish results on the wiki by Apr 10 heartbeat.

**Comment by OpenMatt** [comment]
@thornet : any next steps here? can we close?

**Comment by edrushka** [comment]
Let's keep this open. Currently @cassiemc and I are investigating a contractor to finish the website design.

**Comment by thornet** [comment]
Preparing a retreat for wranglers and core program partners in June to further develop themes.

**Comment by thornet** [comment]
Invitations to program retreat sent. Save the Date out. Website in active development.

**Comment by thornet** [comment]
Changing assignee to Sarah who can continue providing the top-level updates on Mozfest planning.

**Comment by Saallen** [comment]
Festival 2015 update
* Festival retreat and stategic goals added to our [wiki] (https://wiki.mozilla.org/Mozfest/2015).
* 90% of partners have responded and will join us in Scotland for our narrative retreat.
* Website still in development with Sceduling app and registration platform in final stages of analysis
* Bi-monthly Ravensbourne meetings have started around contract negotiation
* Ops meeting requested for budget approval and hotel confirmation
* New roles in development for the festival

**Comment by OpenMatt** [comment]
status? do we just keep rolling this one to next heartbeat?

**Comment by Saallen** [comment]
Yes please- 
* We are just starting the development of the MozFest Retreat program
* Bugs ongoing for Sched.com and TI.TO secruity and legal reviews
* Website in final stages of build

**Comment by OpenMatt** [comment]
@thornet will do a quick update here

**Comment by Saallen** [comment]
After a really successful [MozFest retreat]  (https://wiki.mozilla.org/Mozfest/2015/Mozretreat)  in Scotland  and the launch of the [Mozilla festival] (https://2015.mozillafestival.org/) the program team is working on building learner pathways through the festival weekend with specific personas in mind with the help of those in Scotland.
