### ISSUE TITLE
Test localization strategy for Webmaker Curriculum

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#294]
Test out HTML <-> Transifex localization strategy for Webmaker Curriculum as a potential model for other Teach/Community sites.

#### RACI
* Phase: Deploy
* Owner: @hannahkane 
* Decision Maker: @hannahkane 
* Design Lead: N/A
* Development Lead: TBD
* Quality Verifier: @thornet  

#### Context
Recently, @thornet asked if some community members could easily localize pages in the [Webmaker Curriculum](https://github.com/secretrobotron/webmaker-curriculum/tree/master/WebLiteracyBasics-I). @alicoding [threw up one of the pages onto Transifex](https://www.transifex.com/organization/webmaker/dashboard/webmaker-curriculum) (under a new project), and Sayak from the Indian Moz community volunteered to translate into Bengali.

**Comment by secretrobotron** [comment]
Suggesting @alicoding for obvious reasons (esp. since he took the 5 requisite minutes to set up the experiment). Could use another dev to get used to the transifex system though.

**Comment by thisandagain** [comment]
@hannahkane did you want this as a P2 for this heartbeat? Feel free to drop if not. :smile: :cat2: :cake:

**Comment by hannahkane** [comment]
Does this require a dev or is it something I can learn to do (put content into Transifex)?

**Comment by secretrobotron** [comment]
@hannahkane probably just a bit of @alicoding's time to review what happens on Transifex after Sayak does some work.

**Comment by hannahkane** [comment]
OK, well, I'll leave this as a P2, though it might come after some of the other P2s. We need granularity within P2s. :)

**Comment by alicoding** [comment]
Just to do a quick update here. Right now we have 0% progress on Bengali, but for that `index.html` page that we upload last week now we have 100% for **French** translated. We can do some testing live to see how are things being translate using this `html` format and if it is good to upload other files using the same format here as well.

**Comment by hannahkane** [comment]
Hey @alicoding - is there an update on this? I'm not quite sure what's needed to move this along. Please let me know if I can help.

**Comment by alicoding** [comment]
I think the next step here is for us to take what we have on Transifex and test it on the site to be able to conclude here.

**Comment by secretrobotron** [comment]
@alicoding how can we do that? Just take the file from transifex (assuming it gives you a new html file?) and just put it in our github repo?

**Comment by alicoding** [comment]
Yep there is an option to download the file then just put them in the repo :)

**Comment by secretrobotron** [comment]
Nice! Let's do that on Monday.

**Comment by hannahkane** [comment]
Is there an update on this one, @alicoding and @secretrobotron ?

**Comment by alicoding** [comment]
I helped @LucyeoH upload the file few days ago and not sure what else is needed in this ticket to move forward/close?

**Comment by secretrobotron** [comment]
It would be nice to get some confirmation from the community via @LucyeoH that the localization was successful (e.g. people can read, understand).

@alicoding Did we just upload the one language?

**Comment by alicoding** [comment]
@secretrobotron it's still on @LucyeoH's fork and didn't have PR up yet, but yeah only one language right now.

**Comment by OpenMatt** [comment]
@hannahkane status update?

**Comment by LucyeoH** [comment]
@OpenMatt I'm waiting for review https://github.com/mozilla/webmaker-curriculum/pull/147 so it can merge. 
Feedback on Process: 
It worked very well on the community side (Sayak found it very easy to review) and it was easy to set-up a webmaker curriculum section on Transifex. The biggest problem I had was pulling it on and off Transifex, I had to get a lot of help from @alicoding with this part, and we did run into a small problem with the way Transifex dealt with the header, but apparently we can do an easy work-around for it in the future.

**Comment by hannahkane** [comment]
@LucyeoH - once we merge, should we close this ticket? Is there a new ticket that needs to be filed?

**Comment by secretrobotron** [comment]
@alicoding can you r? btw, why is all the indenting wonky? https://github.com/mozilla/webmaker-curriculum/pull/147/files#diff-e231fa28333552bdac8ce6c0879571d9R40

**Comment by alicoding** [comment]
@secretrobotron looks good to me. The indentation I think it's just Transifex can't keep it the way we have it originally? tbh I'm not sure about that part, but I could just try to see when we download them.

**Comment by secretrobotron** [comment]
Cool!
- @LucyeoH merge it! :boom:
- @alicoding yeah, can you check that? Also, I don't think there's a way for people to find translated pages (nothing automatically switches to the right locale). Can we support that somehow?
- @hannahkane depending on @alicoding's answer, maybe file a follow-up ticket to add that automatic locale switching?

**Comment by alicoding** [comment]
@secretrobotron We could use something similar to this? https://github.com/mozilla/webmaker-language-picker but we could hardcode everything to be the URL for pages we supported.

**Comment by secretrobotron** [comment]
@alicoding maybe there should just be a list of languages then. Might be easiest to hold the list on http://mozilla.github.io/webmaker-curriculum/ rather than individual pages (because there're no templates here).

**Comment by alicoding** [comment]
As long as we can maintain the list and making sure we do update them plus match to the browser's language preference then this wouldn't be hard. The only thing I'm a bit unclear here is the person who is going to maintain this part needs to know about locale and how to update them without breaking things @secretrobotron

**Comment by secretrobotron** [comment]
Me too. Good call. I'm hoping @LucyeoH @thornet or @hannahkane has an opinion about that.

**Comment by hannahkane** [comment]
I don't think I understand.  :( @secretrobotron, are you suggesting we add hard-coded links to translated versions on that Curriculum page? If so, I'm not sure what it means to update without breaking - or rather, I'm not sure what the breaking risk is.

**Comment by alicoding** [comment]
No, I'm suggesting the other way around. Like have list of locales something like this

```
[ 'en-US', 'th-TH', 'bn-BD', 'da-DK' ]
```

The risk here is just if you are doing some syntax error which could cause a problem or if you added a locale that is not valid like typo and such which would also cause 404. This setup is different than our current infrastructure on Webmaker.org and that's the only thing that worried me.

**Comment by hannahkane** [comment]
Thanks, @alicoding . Do you or @LucyeoH have any sense of how often we'll be adding new locales? If it's not that often, maybe this isn't a huge risk.

**Comment by LucyeoH** [comment]
Well this was just a trial but the plan is to use this method to translate all the webmaker curriculum activities and we're thinking 5-10 in Q1.

**Comment by hannahkane** [comment]
Is that 5-10 curriculum activities? I was actually asking about how often new locales are added. 

My instinct is that if the risk is typo-caused 404s that could be fixed after the fact, that's not a huge risk. Would we know when something 404'd, or would we be relying on people reporting them?

I'm designated as the decision-maker on this ticket, but I'm afraid I don't have enough background information to be a good decision-maker. :) Happy to follow the recommendations of @alicoding.

**Comment by alicoding** [comment]
@hannahkane as long as we do have review process of every activity that related with localization then I wouldn't worry about 404s at all.

**Comment by hannahkane** [comment]
OK, sounds like a plan then. Should we close this ticket and open a new one for expanding this beyond the test?

**Comment by alicoding** [comment]
I would say this ticket is done as far as testing the process.

**Comment by hannahkane** [comment]
Cool. Closing now, and will open a new ticket when we're ready for more localizations.
