### ISSUE TITLE
Design assets for Learning Pathways whitepaper

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#297]
Repo here: https://github.com/mozilla/learning-pathways-whitepaper/issues

Suggesting that @iamjessklein might like to spend a heartbeat thinking through ways we can visualise the different types of learning pathways we discuss in the whitepaper *(forthcoming)*

**Comment by hannahkane** [comment]
Moving to Mozilla-Learning repo: https://github.com/MozillaFoundation/Mozilla-Learning/issues/48
