### ISSUE TITLE
Document & streamline our sales / partner management process

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#299]
Make sure we're clear on how we manage key partner relationships. 

Driver: @HPaulJohnson 
Decision-maker: Claw
Consulted: Geoff
Informed: ??? (Paul: please add)

DRAFT: https://etherpad.mozilla.org/salesintakeprocess

**Comment by OpenMatt** [comment]
@HPaulJohnson  says:
* Most of the pieces are there today, with a few gaps that need to be addressed and are mostly in progress. 
* These include: 
- [ ] consistent entry of all leads into salesforce, 
- [ ]  a regular sales check-in to review leads and assign account managers, and 
- [ ] development of a packaged offering and intake form. 

Leave comments and can organize a follow-up to formalize.

**Comment by OpenMatt** [comment]
next step:  Paul will set up the weekly sales standup to start going through actual opportunities.
*  We could use first meeting to walk through this process and cement the process by running through some real life examples.

**Comment by OpenMatt** [comment]
@HPaulJohnson status update?

**Comment by HPaulJohnson** [comment]
Kickoff meeting to happen this week, then bi-weekly on an ongoing basis. 

I can update this ticket one more time, post kickoff, with any additional info and then we can close it out.

**Comment by simonwex** [comment]
@HPaulJohnson can we close this?

**Comment by OpenMatt** [comment]
@HPaulJohnson ?

**Comment by HPaulJohnson** [comment]
We can close, yes. 

First kick-off meeting happened two weeks ago though most stakeholders were not able to attend. Having 2nd iteration of meeting tomorrow and from there we should be all set for this to function as an ongoing process.
