### ISSUE TITLE
Design three Hive Toronto Privacy badges

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#302]
Planning ticket: https://github.com/MozillaFoundation/plan/issues/206

## RACI

* Phase: Design
* Owner: @hannahkane 
* Decision Maker: @smithisgeneric 
* Design Lead: Ashley (contractor)
* Development Lead: NA
* Quality Verifier: @cassiemc 

Deliverables:
- [ ] "Coach" badge
- [ ] "IP Tracer" badge
- [ ] "Data Trail" badge

As per #206, Ashley, a contractor, will design three badges for the Hive Toronto Privacy curriculum, making use of the existing Hive Community badge template, and using Font Awesome iconography. 

Design resources can be found near the bottom of this page: https://wiki.mozilla.org/Webmaker/Badges

**Comment by hannahkane** [comment]
Assigning this to @smithisgeneric who is working with Ashley. Feel free to change that if Ashley is working in github.

**Comment by hannahkane** [comment]
Hey, @smithisgeneric, can you update this ticket? Has Ashley had a chance to make progress on this?

**Comment by smithisgeneric** [comment]
A revised Coach badge (whistle icon) is expected today and the IP Address Tracer (magnifying glass with numbers and possibly a new alternative) tomorrow.  The redpen comments were positive for the data trail timeline (dotted path icon).  For the team's awareness Ashley is working part-time hours on this only and is generally occupied 9-5 EST.

**Comment by OpenMatt** [comment]
@smithisgeneric: is this accurate? 

1) "Coach" badge -- updated design expected Feb 10 
2) "IP Tracer" badge -- updated design expected Feb 11
3) "Data Trail" badge -- design complete

**Comment by smithisgeneric** [comment]
Yes, you've got it @OpenMatt, design review then needed

**Comment by OpenMatt** [comment]
@smithisgeneric : any status update here? designs ready for review?

**Comment by smithisgeneric** [comment]
Designs are up on Redpen 

IP address tracer iterations
* https://redpen.io/zv0d00fa9d0ac12e82
* https://redpen.io/ps0400aa7ce917e879

Privacy coach iteration
* https://redpen.io/zn6e892e88d046953c

**Comment by smithisgeneric** [comment]
Ashley will be out of town next week and in a low-connectivity part of the world.  Design review from @iamjessklein today/tomorrow would be helpful and I have shared a Google drive file with @iamjessklein @OpenMatt etc. in case the designs need to be finalized by someone else.

**Comment by OpenMatt** [comment]
@cassiemc is the lead on quality for this one, so let's flag her for design review.

**Comment by cassiemc** [comment]
Is this actually two badge designs then, not three? 

Left some comments on the redpens, we should need one more review to finalize. Just a few tweaks to make sure the forms hold up at smaller sizes. Would be nice to see both a large graphic and a smaller one side by side, to see how it will scale.

I like the mag glass + pin for the IP address tracer.

**Comment by smithisgeneric** [comment]
There are three badges @cassiemc.  

- Data Trail timeline https://redpen.io/mfcd045ef271a4f1f8 (I previously thought we had sign off from jess but looks like I was workflow confused) 
- Privacy Coach https://redpen.io/zn6e892e88d046953c
- IP Address Tracer https://redpen.io/ps0400aa7ce917e879 (leading choice of location marker with magnifying glass)    

Ashley met with me yesterday and she is out of time to iterate before she leaves.  @iamjessklein can you do the next round of iterations or @OpenMatt do you have a suggestion on how to proceed?

I have asked her to file the editable art files in Google docs asap.

**Comment by OpenMatt** [comment]
* if Ashley is no longer available to complete this design work, then we'll need @cassiemc to advise on whether we have a designer who can pitch in on this today / tomorrow. Or whether we'll need to wait til next week.

**Comment by cassiemc** [comment]
It's a little close to the end of the heartbeat to pull another designer off their work at this point. Is this still a p2? I don't see the milestone label anymore. If it's elevated to a p1, I'll complete this myself. @smithisgeneric Can Ashely please share her vector files with us? Thanks!

**Comment by OpenMatt** [comment]
* Yes, this is a P2. Planning ticket is here: https://github.com/MozillaFoundation/plan/issues/206
(This is a sub-task that got filed in the wrong repo.) 
* This is a P2 this Heartbeat. Will be a P1 next. 
* Our goal was to have as much of the badge design work and copy completed as possible this Heartbeat, so that we could hit the ground running next week.

**Comment by cassiemc** [comment]
Cool, thanks Matt! Based on that original planning ticket, I think we're still on track overall. Let's make this a p1 for the next heartbeat and I'm sure a designer can wrap it up quickly based on Ashley's work on this already.

**Comment by OpenMatt** [comment]
k sounds good

**Comment by smithisgeneric** [comment]
The art files are in the shared Google drive folder accessible to @cassiemc @hannahkane @iamjessklein etc. https://drive.google.com/open?id=0B9uMTH-WLGjdOFhZVXBRYXZTX3c&authuser=0.  I am happy to add anyone else who needs access.

Note: the art was provided by Ashley in psd vs. a vector native format and that is what is available to work from.

**Comment by OpenMatt** [comment]
@smithisgeneric so you're saying the updated design work for all three badges is completed, correct?
@cassiemc can you sign off on the designs as quality lead? And then close this ticket?

**Comment by smithisgeneric** [comment]
No, there are still changes @cassiemc wants as per RedPen.

**Comment by cassiemc** [comment]
Yep. Keeping open. Needs one final pass.

**Comment by cassiemc** [comment]
@smithisgeneric Just want to confirm that the 'm' tab is not wanted on these? See https://wiki.mozilla.org/Webmaker/Badges

@iamjessklein Design R? https://redpen.io/xsdc940776d2fb9b56 Note: I updated the colors to match the templates on that wiki page. If the darker grey is needed, easy fix.

**Comment by smithisgeneric** [comment]
@cassiemc I'm okay without the "m" tab but if it needs to be there for style guide reasons, no problem.

**Comment by iamjessklein** [comment]
@cassiemc @smithisgeneric great work. It's much more polished. I dropped a few minor notes on the redpen. [As I mentioned in the redpen]( https://redpen.io/xsdc940776d2fb9b56), regarding the "m" - I believe that it should be included as we think of Hive Toronto as a "Team" vs. a "Community Member."

**Comment by cassiemc** [comment]
@iamjessklein R? https://redpen.io/tre2cf534d72a1a5b7 I added the 'm' tab and matched the grey in the style guide which I hunted down after your comment, so thanks for that!

Does this work for you @smithisgeneric? What's the final format that you need them in?

**Comment by davidascher** [comment]
The m is supposed to be a marker that it's an official mozilla or
mozilla-team badge, as per
http://emilygoligoski.com/2014/05/07/introducing-mozilla-visual-templates-for-badge-issuers/

IMO any Hive or WebLit badge qualifies for the m marker.

**Comment by iamjessklein** [comment]
agreed.
@cassiemc R+ :+1:  :shipit: 

These should be exported as png files so @smithisgeneric can drop it into the wordpress site.

**Comment by smithisgeneric** [comment]
I've gone through the designs and they look good to me @cassiemc and @iamjessklein

As Jess noted, I need the PNG files but I'll also file the EPS or editable files in the Hive Toronto project folder.

**Comment by cassiemc** [comment]
Just wondering about size. I'll do a basic 500px-ish and @smithisgeneric can resize as needed! Just ping me if you need something else.

Here are the final assets, including .eps vectors: https://www.dropbox.com/sh/epep6cvv2soi5dv/AABnM5MeRC6G51blZjBxx1PKa?dl=0

![hive-toronto-privacy-badges-coach](https://cloud.githubusercontent.com/assets/1186326/6250139/edf7648c-b759-11e4-9094-31a4be841a81.png)
![hive-toronto-privacy-badges-data-trail](https://cloud.githubusercontent.com/assets/1186326/6250140/ee053652-b759-11e4-9314-e60050c8ead5.png)
![hive-toronto-privacy-badges-ip-tracer](https://cloud.githubusercontent.com/assets/1186326/6250141/ee0e93b4-b759-11e4-8e77-ca425937bafd.png)

Calling this baby closed!
