### ISSUE TITLE
Improve demo calls

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#303]
People should feel engaged and inspired by seeing each other's work at demos. It should be fun! Let's come up with some ways to make it even more so than it already is.

Basic improvement ideas on the table:
* Time limit for each demo, circa 5min
* Rotate facilitation
* keep longform discussion/ Q&A to other forums to minimize the "lull" in presentations

Some other possibilities:
* Could try different format styles, a la ignite
* Potential training around how to do great presentations
* More agreed upon 'rules' like no multi-tasking during demos =)
* Recognition? for best demo? best emcee?

**Comment by davidascher** [comment]
testing (ignore)

**Comment by davidascher** [comment]
asd

**Comment by cassiemc** [comment]
Some suggestions from @LucyeoH: 
* Document how demo calls work on a wiki page or something (linked to from build.webmaker.org) with information about the call. "I had to ask a developer to find the etherpad. It's possible that there is one that I just missed, but feeling like you can read about the format of the call and what to do if you're going to present (i.e. instructions about adding yourself to the etherpad with your topic, name, and relevant links at the start of demos) would make first-time presenters feel more comfortable." 
* Also, "At the beginning of each demo, have a quick review of how things are going to go at the start of the meeting, for anyone whose joining for the first time. Little things like how you can ask to present, where people can find the etherpad, and how to ask questions (though I realize we don't do that so much anymore) would be really helpful.'

**Comment by cassiemc** [comment]
We've got some other improvements in the pipeline including updates to URLs and Vidyo rooms. I'll plan to send an all@mofo email about the changes soon.

**Comment by cassiemc** [comment]
this is pretty much done and what isn't is captured here https://github.com/MozillaFoundation/Design/issues/85
