### ISSUE TITLE
Update Makerstrap for Web Literacy Map v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [MozillaFoundation/plan#333]
Makerstrap (https://mozilla.github.io/makerstrap/demo/#/) currently allocates colours to competencies from the Web Literacy Map v1.1. These competencies are changing slightly with Web Literacy Map v1.5, so Makerstrap will need to be updated (see http://literaci.es/redefining-weblitmap-skills)

### Audience
Everyone using Makerstrap.

### Success
Makerstrap reflects the latest version of the Web Literacy Map.

### Vision
We could version Makerstrap, or we could make changes directly. We should probably inform users either way.

The descriptors should change according to this image: https://www.flickr.com/photos/dougbelshaw/16481543205/

### Measurement
N/A

### Roles
 * Phase: 
 * Driver: @hannahkane
 * Decision Maker: @dajbelshaw
 * Design Lead: @cassiemc?
 * Development Lead: @k88hudson?
 * Quality Verifier:

**Comment by hannahkane** [comment]
This will be included in the teach site build, so I'm closing it here.
