### ISSUE TITLE
Redpen :(

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#334]
Given our struggles with Redpen, the design team decided to try InVision for the next heartbeat. While Redpen has worked well to encourage feedback from a wide range of staff, it obviously falls short in other ways.

I'd like to send a note to the makers of Redpen with suggestions. Please add your thoughts below. 

@cassiemc @vazquez @iamjessklein @flukeout @thisandagain @sabrinang

**Comment by xmatthewx** [comment]
Redpen feedback
 - reduce lag and jitters
 - view all comments at once
 - set status on a project to disable comments
 - clear unread comments
 - view versions without leaving the tab

**Comment by cassiemc** [comment]
* archiving
* built-in status indicators to manage feedback (same as 'set status to disable comments' i guess)

**Comment by vazquez** [comment]
- Limited ability to organize designs effectively
- Showing how hover and click states look and feel

**Comment by iamjessklein** [comment]
* Create folders within projects
* versioning 
* Better ability to order images

**Comment by thisandagain** [comment]
- Fix performance issues (seems to be related to notifications)
- Fix layout issues (particularly when navigating directly to a design)
- Click to clear all notifications
- Ability to disable comments
- Ability to archive a design / project

**Comment by davidascher** [comment]
* better URLs
* more informative emails.

**Comment by davidascher** [comment]
* better mobile view

**Comment by k88hudson** [comment]
+1 to performance issues/layout issues

**Comment by xmatthewx** [comment]
Ok. Feedback shared. We can try InVision next week and discuss in Toronto.
