### ISSUE TITLE
Translate Webmaker Automated Event Emails 

### ISSUE THREAD

**Issue by LucyeoH** [MozillaFoundation/plan#336]
Put webmaker automated event emails on Transifex to be translated. cc. @jbuck @alicoding

**Comment by OpenMatt** [comment]
@LucyeoH in future, can you file granular issues like this one in another repo? Like Webmaker.org? https://github.com/mozilla/webmaker.org
* this "Plan" repo is just for high-level meta-tickets.

**Comment by LucyeoH** [comment]
Sure thing @OpenMatt
