### ISSUE TITLE
Ship a landing page for International Yak-Herder Day

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#337]
Design and build a web page on webmaker.org to support our Yak-Herder campaign. 

## Roles

* **Driver**: @openmatt 
* **Decision Maker**: @smithisgeneric 
* **Design Lead**: @iamjessklein 
* **Development Lead**: @ScottDowne 
* **Quality Verifier**: @cassiemc

**Comment by iamjessklein** [comment]
I hope this is legit.

**Comment by smithisgeneric** [comment]
I like the Viacoin font awesome icon for the yak landing page http://fortawesome.github.io/Font-Awesome/icon/viacoin/ 
![viacoin](https://cloud.githubusercontent.com/assets/6931814/6174748/d91d7276-b2be-11e4-815f-b9d0a3465b9d.png)


cc: @iamjessklein  @OpenMatt

**Comment by OpenMatt** [comment]
this was a dummy ticket I filed for some documentation I was writing. closing now. save the yaks.

**Comment by iamjessklein** [comment]
@smithisgeneric :heart:
