### ISSUE TITLE
Organize graphic assets for DAM

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#340]
Organize MoFo graphic assets for the Digital Asset Management project led by MoCo. 

##Roles##
Phase: Implementation
Owner: MoCo (Ty Flannagan & Liz Noonan) 
Driver:  @edrushka 
Decision Maker: @sabrinang 
Design Lead: @sabrinang 

CC: @davidascher @cassiemc 

We need to organize some MoFo graphic assets for the Digital Asset Management project led by MoCo. @sabrinang can you note which assets they've requested from us?

**Comment by sabrinang** [comment]
So far the Maker Party assets have been requested from me. 
Also, Ty has noted in an email that: _"There will be more assets needed like event photos, and anything else related to foundation events, but we can discuss that in a few weeks"_
... so I assume more things as the DAM progresses

**Comment by OpenMatt** [comment]
@edrushka can you say more about why this one is a P1? It feels kinda housekeeping-ish

**Comment by edrushka** [comment]
There is a deadline from Ty. MoCo is demo-ing the ops call for All Mozilla on March 11.

This is what Sabrina will be working on this week. Is there another way I should be indicating this other than the P1 tag so that @cassiemc can see what Sabrina is working on?

**Comment by cassiemc** [comment]
@edrushka Ideally we want to link smaller granular tickets like this to larger meta tickets, but since this is a standalone I think we can remove it from p1 and the feb27 milestone. I'm aware it's happening! It's a weird half-week anyway with work week in Toronto next week, so there are a few tasks like this.

**Comment by cassiemc** [comment]
Just read my email and sounds like @sabrinang has already completed this.

**Comment by sabrinang** [comment]
Maker party (2014) has been organized now.

I will wait to hear back from Ty on what to do about outdated assets and also wait to hear about what to do about other foundation assets that I have in our studio mofo dropbox folder.

**Comment by edrushka** [comment]
This ticket is a good test case for when MoFo is doing a small, granular task for a larger MoCo initiative. Going forward, how these tasks should fit into /plan ?

**Comment by cassiemc** [comment]
@edrushka I wonder if @hannahkane has some insights around this, having gone through it with the teach team quite recently.

**Comment by davidascher** [comment]
My suggestion would be to create a repo where the team involved in the
discussions will naturally find the issues and participate.  So maybe a
MoFo-Engagement repo, where @edrushka can organize issues however makes
sense, set deadlines which may or may not connect to heartbeat milestones,
and link up to a high-level planning ticket when it makes sense.

**Comment by edrushka** [comment]
@sabrinang did you hear back from Ty? Can we close this?

**Comment by edrushka** [comment]
I'm going to close this for now. Can re-open if MoCo has more requests.
