### ISSUE TITLE
Produce initial recommendations for MozFest site improvements

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#341]
RACI

* Phase: Research
*    Driver: @erikadrushka
*    Decision Maker: Sarah Allen
*    Design: @sabrinang @Roberto-Cruz 
*    Dev: @mmmavis 

Steps

- [x] Conduct site research 
- [x] Conduct brand audit 
- [x] Conduct user research 
- [x] Synthesize research 
- [x]  Review team needs 
- [x] Create a list of recommendations 
    
Kickoff notes here: https://studiomofo.etherpad.mozilla.org/MozFest-2015-site-plans

**Comment by davidascher** [comment]
Changed the description to show @edrushka some of the power features of markdown in github ;-)

**Comment by edrushka** [comment]
Ohhh! Checkboxes! Bulleted lists! ;)

**Comment by edrushka** [comment]
Done!
Recommendations for site are here: https://drive.draw.io/#G0B4q3TCz6z_aJd3NManZtYU1kZUE
For schedule experience are here: https://drive.draw.io/#G0B4q3TCz6z_aJN0ZsTV9QSUNTU00
