### ISSUE TITLE
Research registration platforms and tools for MozFest

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/plan#342]
Short list possible platforms and tools for new registration process for MozFest
with @quakpac 
Main requests from new platform/tool
* consolidate registration process  pre festival for different user groups 
* allow festival onsite process to be faster, accurately recorded and easier to manage on the day

**Comment by edrushka** [comment]
@Saallen I'm going to label this P2 so it doesn't get lost in the shuffle this heartbeat. We should also chat about getting one (or maybe 2-3) big MozFest tickets in plan, and moving the more granular work to the MozFest repo. I can help you do that :)

**Comment by Saallen** [comment]
Hey @edrushka 
working on this <a href="https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1EsdWh3UgJWs21EBzNIKJh0XYYZDYcRPGcgMIxv0NGwk/edit#gid=0/" title="Title">
google doc</a> 
but would like to build it out more. Which I will one I can access draw.io :anger:

**Comment by Saallen** [comment]
Can we add these items to the meeting agenda for tomorrow night if you have the time @edrushka ?

**Comment by edrushka** [comment]
Sure. I could only find half an hour tomorrow so we'll likely need to circle up again on all this stuff, but let's add this to the agenda.

**Comment by Saallen** [comment]
Puuurfect. I have moved these two pieces over to the Mozfest repo so can close this one now
