### ISSUE TITLE
Research Travel management options for MozFest 2015

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/plan#343]
Working with becky @quakpac to
**evaluate the potential of working with Egensia w MozFest specific account for flights
** short list 3 other possible agents for travel management
** @saallen to evaluate in-house option of accommodation management through hotel direct bookings and contract negotiations

**Comment by OpenMatt** [comment]
@Saallen same with this one -- please file elsewhere? as per http://book.webmaker.org/github_repos.html
And ping me in IRC if I can help with this in any way.
