### ISSUE TITLE
Build Calendar for Learning Networks community events

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/plan#344]
Using this etherpad : https://teach.etherpad.mozilla.org/events2015 I will build a calendar for all the Learning network team to use.

Location of Calendar: TBC
Working with : @amirad

**Comment by OpenMatt** [comment]
@Saallen: Awesome! But can you file this ticket here instead? https://github.com/MozillaFoundation/Mozilla-Learning/issues

The "Plan" repo is just for high-level planning tickets. 

More documentation on this here: http://book.webmaker.org/github_repos.html
