### ISSUE TITLE
Document our partnership and new geographies plan

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/plan#345]
### Deliverables
* [x]  [**1) Partner criteria for Learning Networks**](https://docs.google.com/a/mozillafoundation.org/document/d/1qukGywwh1zY8eIPa75_AnS8Piu9KUxWGXpgu4N6gGAY/edit) 
  * driver: @thornet consulted: @amirad http://mzl.la/networks_partner_criteria
  * status: **done**
* [ ] **2) Partner criteria / strategy for Learning Products** 
  * driver: @HPaulJohnson consulted: @benrito 
  * status: **in progress**. post-MWC. e.g., Partnerships as a means of getting the app distributed
* [x] **3) Lessons learned from UK debrief**  
  * status: **done.** discussion happened, raw notes collected. but there's no document -- we're going to foll what we learned into the forward-looking plan. 
* [ ] **4) Weighted list of regions to focus on in 2015** http://mzl.la/regions_matrix
  * status: draft in progress. Needs further update based on MWC. 
  * Driver: @benrito (consulted: @HPaulJohnson + @thornet)

### Vision
Weighted rubric for determining whether to target a new market; with distinctions made between product and learning network expansion.  Clarity around “what it means to be in a place” and a stay-in-market checklist. Include "what makes a good partner" and job descriptions to support.

**Comment by thornet** [comment]
Includes: 

* Lessons learned from UK debrief
* Weighted list of regions to focus on in 2015

**Comment by OpenMatt** [comment]
@ Michelle: you're the driver on this one, I believe.
 Can you fill out the other roles? as per http://book.webmaker.org/roles.html

**Comment by adamlofting** [comment]
CCing myself to help with TBD measurement section

**Comment by OpenMatt** [comment]
@thornet what's the next step on this? Can you have something documented in time for next Ops meeting Feb 24?

**Comment by OpenMatt** [comment]
and: are we still thinking the core strategy is: "follow the heat" we already have in India & Bangladesh. Plus: weighing Brazil / Kenya?

**Comment by benrito** [comment]
It's more multivariate. Some thinking has been done already:

https://etherpad.mozilla.org/global

We will develop a simple criteria chart. 

Brazil is already in; we have staff there.

India, Bangladesh and Kenya are the GSMA countries and would score high on our criteria.

**Comment by thornet** [comment]
I'm re-writing this ticket to be about "Determine partner criteria for Learning Networks." 

I suggest @benrito @HPaulJohnson @thisandagain will want to do a separate ticket for "Market criteria for Webmaker product" as this will have separate requirements.

**Comment by thornet** [comment]
Partner criteria for clubs, written and vetted with Learning Network team + @benrito An-Me: 

http://mozilla.github.io/webmaker-curriculum/about/#rollout

Partner criteria for broader Learning Network work, inc. case studies, written by @amirad and vetted by team et. al:

https://docs.google.com/a/mozillafoundation.org/document/d/1qukGywwh1zY8eIPa75_AnS8Piu9KUxWGXpgu4N6gGAY/edit

**Comment by OpenMatt** [comment]
@benrito : what deliverables will you have ready by EOD today? How do you want to be involved? 
* my understanding is: this is split in two: 1) Learning Networks and 2) Learning Products
* Learning Networks is done. Are you the driver for the Learning Products piece?

**Comment by OpenMatt** [comment]
@thornet : I made some comments and flagged some questions on the Google Doc
https://docs.google.com/a/mozillafoundation.org/document/d/1qukGywwh1zY8eIPa75_AnS8Piu9KUxWGXpgu4N6gGAY/edit

**Comment by OpenMatt** [comment]
@thornet : I think we should aim for a single merged document, instead of two separate ones. Can you roll your Clubs criteria right into the Google Doc? http://mozilla.github.io/webmaker-curriculum/about/#rollout

**Comment by OpenMatt** [comment]
The Learning Networks stuff is strong work. My main question is: where is this?
* Lessons learned from UK debrief
* Weighted list of regions to focus on in 2015

**Comment by OpenMatt** [comment]
@chrislarry33 : Chris: do you agree those are the deliverables we're looking for?

**Comment by OpenMatt** [comment]
@HPaulJohnson @benrito  do you have any status updates for the deliverables with your names next to them in comment 1?

**Comment by benrito** [comment]
IMO the short version is:

Brazil (tentpoles: LAN house project, state money)
India (tentpoles: strong community, Digital India, 2% CSR mandate)
Bangladesh (tentpoles: strong community, government, MNOs)
East Africa (tentpoles: MozFest EA and Equity)

We should also leave room for a pan-African demonstration project with Orange, if the analysis bears out that it's a good and workable idea.

After last week I think that "which regions to focus on" is overly broad. We might consider specific analysis on each:

1. which countries to focus on to hit our Learning Networks KPI this year (500 cities)
    > this will have to do with where there are volunteers or partners who are ready to start Clubs
2. which countries to focus on to hit our Learning Products KPI this year (250k users)
    > this will have to do with where we have channel partnerships that add to our app's organic growth
3. which countries to focus on for expansionary fundraising 
    > this is where we can start to leverage 1&2 together, and also add fuel to both over time
4. which countries will help us to build impactful Mozilla U stories and scaffolding
    > as above

I've moved the core part of the https://etherpad.mozilla.org/global Etherpad to:

https://docs.google.com/spreadsheets/d/1Uk8CwB5gUUo9GXJAUi1GqJqUwh3gJDPINHmShNEuBIs/edit#gid=0

**Comment by OpenMatt** [comment]
3) Lessons learned from UK de-brief = done. Geoff confirms we don't need a document there -- just roll what we learned into (4), which Ben is working on.

**Comment by davidascher** [comment]
I'd like to understand the UK experience better.

**Comment by OpenMatt** [comment]
Unless anyone objects, I'm going to close this ticket. I believe next steps are on @benrito. But this has been kicking around long enough.
