### ISSUE TITLE
Develop email list management tool

### ISSUE THREAD

**Issue by jdotpz** [MozillaFoundation/plan#346]
Our bounce rates have gotten to be relatively high.  This started in earnest between Jan 1st and Jan 5th.
  AWS hasn't contacted us yet, but in my experience, around 2% they will usually start threatening to shut SES off if bounce rates are not improved.  To get ahead of this, I'd propose a mechanism built into our apps to be able to plug non-existent / complaining emails into a suppression list.

![screen shot 2015-02-17 at 10 28 17 am](https://cloud.githubusercontent.com/assets/1373628/6232185/f680e0d0-b68f-11e4-8d8e-1a9b84a62607.JPG)

![screen shot 2015-02-17 at 10 30 55 am](https://cloud.githubusercontent.com/assets/1373628/6232219/2f1fbe84-b690-11e4-97f8-1b36090a96d3.JPG)

Example bounces: *Note: I have intentionally replaced email addresses with removed@privacycounts.org*
webmakerorg-email-bounces-complaints	
{"notificationType":"Bounce","bounce":{"bounceSubType":"General","bounceType"...
9:19 AM (1 hour ago)

webmakerorg-email-bounces-complaints no-reply@sns.amazonaws.com via mozillafoundation.org 
9:50 AM (34 minutes ago)

to devops 
{"notificationType":"Bounce","bounce":{"bounceSubType":"General","bounceType":"Permanent","reportingMTA":"dsn; a8-81.smtp-out.amazonses.com","bouncedRecipients":[{"status":"5.1.1","action":"failed","diagnosticCode":"smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try\n550-5.1.1 double-checking the recipient's email address for typos or\n550-5.1.1 unnecessary spaces. Learn more at\n550 5.1.1 http://support.google.com/mail/bin/answer.py?answer=6596 e188si907429qhc.102 - gsmtp","emailAddress":"univresengc@gmail.com"}],"timestamp":"2015-02-17T15:50:24.050Z","feedbackId":"0000014b983bb186-5b37fce3-a581-4af0-8d38-fa08864fc3c5-000000"},"mail":{"timestamp":"2015-02-17T15:50:23.000Z","source":"Webmaker <help@webmaker.org>","messageId":"0000014b983bae4b-9df1cf8c-5750-421c-9d3a-fbc27f7ca4d2-000000","destination":["removed@privacycounts.org"]}}

webmakerorg-email-bounces-complaints no-reply@sns.amazonaws.com via mozillafoundation.org 
9:53 AM (31 minutes ago)

to devops 
{"notificationType":"Complaint","complaint":{"complainedRecipients":[{"emailAddress":"ramos_0126@yahoo.com"}],"complaintFeedbackType":"abuse","arrivalDate":"2015-02-17T15:03:33.000Z","userAgent":"Yahoo!-Mail-Feedback/1.0","timestamp":"2015-02-17T15:53:33.000Z","feedbackId":"0000014b983e96f4-2068a2f1-b6bd-11e4-a35b-9dc7b84ace98-000000"},"mail":{"timestamp":"2015-02-17T15:03:31.000Z","source":"Webmaker <help@webmaker.org>","messageId":"0000014b9810c6a8-a99efe1d-b8ec-4b49-af0f-59778101ec3e-000000","destination":["removed@privacycounts.org"]}}

webmakerorg-email-bounces-complaints no-reply@sns.amazonaws.com via mozillafoundation.org 
9:56 AM (28 minutes ago)

to devops 
{"notificationType":"Bounce","bounce":{"bounceSubType":"Suppressed","bounceType":"Permanent","reportingMTA":"dns; amazonses.com","bouncedRecipients":[{"status":"5.1.1","action":"failed","diagnosticCode":"Amazon SES has suppressed sending to this address because it has a recent history of bouncing as an invalid address. For more information about how to remove an address from the suppression list, see the Amazon SES Developer Guide: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/remove-from-suppressionlist.html ","emailAddress":"removed@privacycounts.org"}],"timestamp":"2015-02-17T15:56:46.383Z","feedbackId":"0000014b9841873f-93338a55-b6bd-11e4-abc2-2fbafade0344-000000"},"mail":{"timestamp":"2015-02-17T15:56:45.000Z","source":"Webmaker <help@webmaker.org>","messageId":"0000014b9841858c-a9ce5df3-dc1b-4ea7-801a-0359d485808b-000000","destination":["univresengc@gmail.com"]}}

webmakerorg-email-bounces-complaints no-reply@sns.amazonaws.com via mozillafoundation.org 
10:24 AM (0 minutes ago)

to devops 
{"notificationType":"Bounce","bounce":{"bounceSubType":"Suppressed","bounceType":"Permanent","reportingMTA":"dns; amazonses.com","bouncedRecipients":[{"status":"5.1.1","action":"failed","diagnosticCode":"Amazon SES has suppressed sending to this address because it has a recent history of bouncing as an invalid address. For more information about how to remove an address from the suppression list, see the Amazon SES Developer Guide: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/remove-from-suppressionlist.html ","emailAddress":"removed@privacycounts.org"}],"timestamp":"2015-02-17T16:24:24.093Z","feedbackId":"0000014b985ad29f-6f442eb0-b6c1-11e4-b70d-9fc02a01768c-000000"},"mail":{"timestamp":"2015-02-17T16:24:23.000Z","destination":["s67725@stu.org"],"messageId":"0000014b985aceff-51802c4c-8934-4a92-9c18-29b85b0d1a4d-000000","source":"Webmaker <help@webmaker.org>"}}

**Comment by davidascher** [comment]
Good to know, @jdotpz.  I'm surprised, I assumed that BSD managed unsubscribes based on bounce detection.  I expect @valianttry, @edrushka and @simonwex need to see this to inform the CRM plans.

**Comment by jbuck** [comment]
Specifically, this is sawmill, not BSD, for our transactional email

**Comment by valianttry** [comment]
@davidascher i've asked @simonwex this as well: Why are we building an email system when there are hundreds to choose from, including ExactTarget and BSD (both of which we can currently use)? I realize it's probably a legacy thing, but it's painful to see us building functionality that is available out of the box for $0. Should we spend time migrating instead of building? /soapbox

**Comment by jdotpz** [comment]
These aren't the same thing @valianttry .
This is for the servers to be able to email transactional stuff out, like "Hey, you signed up for an account, here's the link to verify" sort of thing, not email blast list stuff.

**Comment by valianttry** [comment]
@jdotpz ExactTarget comes with transactional email functionality. It's not just for large email blasts. It's called Journey Builder and works on event triggers: http://www.exacttarget.com/products/journey-management/journey-builder:

"With Journey Builder, you can create a truly personalized experience for each and every customer—whether you have 100 or 100 million. It’s never been easier to form authentic brand relationships at scale by responding to real-time individual behaviors.

You can tailor every interaction based on specific customer actions to deliver timely, relevant content that reaches customers when, where, and how they prefer. Leverage pre-built integrations with email, SMS, mobile push, and Predictive Intelligence—and with our API framework, expand your reach to channels like in-app messaging, call centers, connected devices, and even offline channels like direct mail."

**Comment by simonwex** [comment]
@valianttry do you know what we pay for ET? This conversation is actually happening over here, too: #242

**Comment by simonwex** [comment]
It's also worth mentioning that MoCo has written [Basket](https://github.com/mozilla/basket) which is a project that supposedly makes up for ExactTarget's many shortcomings.

**Comment by valianttry** [comment]
The ExactTarget agreement with Moco is that we pay by the # of emails mofo sends using ExactTarget, and we've already banked plenty of email in our estimates (including Webmaker messaging and other projects like Open News emails; etc). Overage kicks in if we've under-estimated. I don't know how much the Basket customization would apply to our implementation since Basket was built at a time before Salesforce bought ExactTarget and began a deeper integration across both. We're implementing Salesforce along with ExactTarget, so the integration might be simpler (I don't know for sure).

**Comment by hannahkane** [comment]
Is this ticket still being worked on? Should we move this to the current milestone?

**Comment by jbuck** [comment]
It's being worked on in the sense that @jdotpz's original request of "lets reduce our bounce rate" is being schemed in https://github.com/mozilla/id.webmaker.org/issues/283#issuecomment-97994035 and several of us are doing Exact Target training next week.
