### ISSUE TITLE
Discuss, decide and document our Maker Party 2015 plan

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#347]
Surface key strategy decisions, de-brief from NYC work week, get the stakeholders together, and document a plan. 

## Roles
Driver: @amirad 
Decision Maker: Ops team
Consulted (team) @HPaulJohnson @edrushka @LucyeoH @ldecoursy @thornet 
Informed/strategically involved: @OpenMatt @hannahkane @chrislarry33

**Comment by OpenMatt** [comment]
* Will have more on this by eod Feb 17

**Comment by chrislarry33** [comment]
Taking plans to Ops today 
You can see documentation here: https://docs.google.com/a/mozillafoundation.org/document/d/1zsYZebqJybuYbl2mEF0m6pNazwpVpJM5C6N90d7ibEw/edit#heading=h.4rwjkws3rk5y

**Comment by OpenMatt** [comment]
cc @amirad @thornet please add others

**Comment by chrislarry33** [comment]
@hannahkane @ldecoursy @HPaulJohnson @edrushka @LucyeoH

**Comment by amirad** [comment]
Meeting this week with Erika, Lainie, Paul, Lucy, Hannah to further flush out plans. Notes: https://teach.etherpad.mozilla.org/MP2015

Next steps: Myself to draft quick MP 2015 plan and offerings. @HPaulJohnson to draft marketing plan and timeline. Then present updates plans to Ops team week of March 9th for final review.

**Comment by secretrobotron** [comment]
Interested. Leaving my mark :).

**Comment by edrushka** [comment]
Amira, I'm going to label this a P2 so it doesn't get lost in the shuffle this heartbeat.

**Comment by edrushka** [comment]
@HPaulJohnson @amirad everything still on track to present to ops next week?

**Comment by chrislarry33** [comment]
Amira shared this with me: https://docs.google.com/a/mozillafoundation.org/document/d/15VRGwqzBYqi-11It3SqEzyqmYHSNeXDR-CI6My4DELI/edit

I haven't dug to deeply in yet, but wanted all to have if you haven't already. The expectation that Amira and possibly Paul would present to Ops. Could punt if we needed to but,, would need to communicate that soon.

**Comment by HPaulJohnson** [comment]
I am going to work have to get to this on Monday. Laptop was stolen so hobbling along in Barcelona on my phone only. Hopefully still on track, @amirad and I have been discussing this week.

**Comment by chrislarry33** [comment]
Barcelona, the world capital for stolen laptops...sorry my man

**Comment by chrislarry33** [comment]
Hi all, talked with Angela today. We are going to delay presenting this to Ops until 3/17. This was not b/c we weren't ready but b/c of scheduling and agenda issues with Ops. Thanks for keeping at this.

**Comment by OpenMatt** [comment]
@chrislarry33 @HPaulJohnson @amirad : I assume this document is now ready to share with ops
http://mzl.la/campaign_strategy

Let me know here if that's wrong

**Comment by amirad** [comment]
Just working on cleaning it up and seeing @edrushka can help tighten my copy today.

**Comment by OpenMatt** [comment]
ok. let's aim to send EOD today, so folks have time to read it before tomorrow's meeting.

**Comment by OpenMatt** [comment]
@HPaulJohnson I think this is pretty much done -- great work @amirad . can you take a final look?

**Comment by HPaulJohnson** [comment]
Looks great. Nice job, @amirad. Ready to be presented for feedback from Ops tomorrow.

**Comment by OpenMatt** [comment]
nice work team. closing this. can open a new one based on any feedback / next steps.

**Comment by chrislarry33** [comment]
Share away

**Comment by OpenMatt** [comment]
there was one hanging thread on messaging w. @edrushka -- but we can take up the specifics of messaging when we get to the message plan document. so, all good.

**Comment by amirad** [comment]
I took out that messaging for now as we focus on what just the ops team needs. It can be shared now.

**Comment by OpenMatt** [comment]
Outstanding work on this. @amirad can you update based on the feedback you got today, and update here when complete?

**Comment by amirad** [comment]
Thanks for all your help @OpenMatt!!! I just updated the doc with Ops feedback and concerns. Think I'm good to delete the ops comments unless we still need them?

**Comment by chrislarry33** [comment]
Amira, I think it might be worth posting to your blog, post integrating Ops feedback, even if we flag "still thinking about this part"

**Comment by OpenMatt** [comment]
@amirad looks good. 
* Agree with Chris -- can we move this out of google doc now and post on your blog in HTML form? 
* Can your cross-post to the Webmaker blog as well?

**Comment by OpenMatt** [comment]
Something that came out of this that I thought was helpful, in terms of understanding the production (e.g., design / engineering) dependencies for 2015 Maker Party success: 
1. teach.mozilla.org (tracking to May 1)
2. badges (esp.: improve existing platform vs. move) (work we do on badges will have MP impact -- good to be explicit about this) 
3. events platform (less critical than previous years -- but still important to scope / be explicit. and co-ordinate w. the existing Product Roadmap / make sure we're aligned. 
4. great CTAs (well-packaged, fun, ready for widespread use) (we should make design and light-weight dev resources available to help w. this where needed, also) 

@amirad @chrislarry33 do you agree? if so, we could do a kick-off meeting on this next Heartbeat. To make sure all teams are clear on the Maker Party plan, understand the dependencies, and have a solid look-ahead roadmap to deliver.

**Comment by amirad** [comment]
Yes to talking through all the product/team requirements now that we know the plan. Will need to heavily loop in @hannahkane for platform discussions

Did a post on my blog here: http://amiradhalla.com/2015/03/18/maker-party-2015-the-evolution-of-a-year-long-party/ 
Will cross-post on Webmaker soon. (edited it a bit for public reading and took out specific team members names/roles)

**Comment by amirad** [comment]
Webmaker blog for MP: https://blog.webmaker.org/maker-party-2015-the-evolution-of-a-year-long-party 

Before I close the page, do we want to set up additional issues for the points @OpenMatt mentioned above or meet next week and go through them first?

**Comment by chrislarry33** [comment]
Love it, thanks all

**Comment by hannahkane** [comment]
Can we close this ticket?

**Comment by amirad** [comment]
Boom!
