### ISSUE TITLE
MWC messaging: make sure we're on the same page

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#348]
Make sure the various stakeholders understand the key messages, have a shared set of talking points and CTAs, etc.

Driver: @thornet 
Decision-maker:
Consulted:

**Comment by OpenMatt** [comment]
cc @thornet @davidascher @benrito

**Comment by OpenMatt** [comment]
my understanding is that @thornet and @benrito still have some work to do to get on same page here

**Comment by edrushka** [comment]
CC @kevzawacki
