### ISSUE TITLE
TEACH: understand requirements for Better Discourse

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#35]

**Comment by thornet** [comment]
cc @hannahkane: will this be reviewed as part of the teach site launch? Are there more recent tickets to be helping with here?

**Comment by hannahkane** [comment]
Not sure if there was a broader intent for this ticket when it was initially created, but I think the immediate needs are covered in the "Teach Like Mozilla" tickets. As other needs arise, we can add more specific tickets.
