### ISSUE TITLE
Standardize and Implement Automated Testing 

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#351]
### Audience
MoFo Engineers

### Success

MoFo Engineers understand standards and best practices for automated testing across all of our priority projects. This includes server-side, client-side unit and integration testing. All of our priority projects have a basic set of tests that can easily be added to.

* [x] Compile list of projects (with repos) that require test coverage
* [x] Choose and implement testing frameworks
* [x] Add linters from `mofo-style` (npm module)
* [ ] Add tests that validate three recently solved bugs
* [ ] All tests pass (Travis green)

### Prior Work:
https://github.com/MozillaFoundation/mofo-example-app/issues/33

### RACI
* Driver: @simonwex
* Dev: @gvn 
* Dev: @k88hudson 
* Lead Design: N/A
* Decision Maker: @simonwex
* Quality Verifier: @davidascher 

# App Matrix

[click here for some delicous spreadsheety goodness](https://docs.google.com/spreadsheets/d/1rvRZ9pkd6ET3TTaVL0snEORK4wiCIC10gNS3lG9jYPI/edit#gid=0)

### Events

- server component: express server
  - test framework: none
- client component: angular
  - test framework: protractor
- test coverage: estimated 5%
- JS linting: yes (jshint)
- JSON linting: yes
- CSS linting: implicit via LESS
- code style enforcement:
  - JS: jsbeautify
  - CSS: no

### Events Service (API)

- server component: express server
  - test framework: custom tests (`should` + `faker`)
- client component: no
- test coverage: estimated 30%
- JS linting: yes (jshint)
- JSON linting: no
- CSS linting: n/a
- code style enforcement:
  - JS: jsbeautify
  - CSS: n/a

### Webmaker.org

- server component: express server
  - test framework: casper/phantom.js
- client component: angular + express (templated, `require`)
  - test framework: none
- test coverage: estimated 3%
- JS linting: yes (jshint)
- JSON linting: partial (rules don't catch all .json files)
- CSS linting: implicit, via LESS (note: in middleware rather than as runnable task)
- code style enforcement:
  - JS: jsbeautify
  - CSS: no

### Profile

- server component: express server
  - test framework: custom (`should`) in theory
- client component: angular + express (templated, `require`)
  - test framework: protractor, in theory
- test coverage: pretty much none
- JS linting: yes (jshint)
- JSON linting: none
- CSS linting: implicit, via LESS
- code style enforcement:
  - JS: jsbeautify
  - CSS: no

### Webmaker App

- server component: no
- client component: vue / browserify
  - test framework: mocha, phantom
- test coverage: unknown at the moment
- JS linting: yes (jshint)
- JSON linting: none
- CSS linting: implicit, via LESS
- code style enforcement:
  - JS: jscs (validate-only)
  - CSS: no

### Login

- server component: express server
  - test framework: custom (`assert`)
- client component: minimal
  - test framework: custom (`assert`)
- test coverage: unknown
- JS linting: yes (jshint)
- JSON linting: none
- CSS linting: implicit, via LESS (note: in middleware rather than as runnable task)
- code style enforcement: no

### MakeAPI

- server component: express server
  - test framework: custom
- client component: no
- test coverage: unknown
- JS linting: yes (jshint)
- JSON linting: none
- CSS linting: csslint (no precompilers used)
- code style enforcement: no

### teach.webmaker.org

- server component: no
- client component: React
  - test framework: none
- test coverage: unknown
- JS linting: none
- JSON linting: none
- CSS linting: implicit, via LESS
- code style enforcement: none

### goggles.webmaker.org

we kind of need to either redo, or treat as immutably locked down. Ignoring that, goggles would need:

- server-side test for the HackPub API part
  - unit tests
  - probably API input (fuzz) testing
- client-side tests for the library
  - unit tests
  - interfacing tests
- JS validation (lint + style)
- CSS validation (lint + style)

### thimble.webmaker.org

lacks pretty much tests of any sort, and needs:

- server-side test for the HackPub API part
  - unit tests
  - probably API input (fuzz) testing
- client-side tests
  - unit tests
  - interfacing tests
- JS validation (lint + style)
- CSS validation (lint + style)
- dependency tests:
  - Slowparse has its own set of tests, and I'm not sure we want to apply the same kind of test pattern that our apps use.
  - Friendlycode doesn't really have all that many tests that I know of, but if we're going the Brackets way, test-encumbering it feels like something we need to do on the brackets-using-project, not in thimble.webmaker.org

### together.js

not too familiar with the actual code base but this will need developers before it even makes sense to talk about test harnesses. It doesn't feel like a thing we're supporting, or intend to support.

### appmaker

Appmaker does use JS linting, but no style checks, so we're looking at :

- server-side test
  - unit tests
  - probably API input (fuzz) testing
- client-side tests
  - unit tests
  - interfacing tests
- JS and CSS style testing

### Friendlycode as a project

Friendlycode is a pure client-side library without any server-side components of its own. It could do with tests, but it's... pretty complex, really, and parts of it are getting replaced with the work that's happening on Brackets. That said: Friendlycode has no tests whatsoever, other than the occasional "use strict".

**Comment by davidascher** [comment]
FYI: https://github.com/facebookarchive/huxley

**Comment by gvn** [comment]
Adding PR to revise `.jshintrc`:

https://github.com/MozillaFoundation/javascript-style-guide/pull/4

**Comment by simonwex** [comment]
While we're touching the many codebases, it might make sense to kill this bird too: #369

**Comment by Pomax** [comment]
Running down the list of apps I'm most familiar with:

### goggles.webmaker.org

we kind of need to either redo, or treat as immutably locked down. Ignoring that, goggles would need:

- server-side test for the HackPub API part
  - unit tests
  - probably API input (fuzz) testing
- client-side tests for the library
  - unit tests
  - interfacing tests
- JS validation (lint + style)
- CSS validation (lint + style)

### thimble.webmaker.org

lacks pretty much tests of any sort, and needs:

- server-side test for the HackPub API part
  - unit tests
  - probably API input (fuzz) testing
- client-side tests
  - unit tests
  - interfacing tests
- JS validation (lint + style)
- CSS validation (lint + style)
- dependency tests:
  - Slowparse has its own set of tests, and I'm not sure we want to apply the same kind of test pattern that our apps use.
  - Friendlycode doesn't really have all that many tests that I know of, but if we're going the Brackets way, test-encumbering it feels like something we need to do on the brackets-using-project, not in thimble.webmaker.org

### together.js

not too familiar with the actual code base but this will need developers before it even makes sense to talk about test harnesses. It doesn't feel like a thing we're supporting, or intend to support.

### appmaker

Appmaker does use JS linting, but no style checks, so we're looking at :

- server-side test
  - unit tests
  - probably API input (fuzz) testing
- client-side tests
  - unit tests
  - interfacing tests
- JS and CSS style testing

### Friendlycode as a project

Friendlycode is a pure client-side library without any server-side components of its own. It could do with tests, but it's... pretty complex, really, and parts of it are getting replaced with the work that's happening on Brackets. That said: Friendlycode has no tests whatsoever, other than the occasional "use strict".

**Comment by Pomax** [comment]
I'll be doing inventory for all our `order=1` apps in https://docs.google.com/spreadsheets/d/1rvRZ9pkd6ET3TTaVL0snEORK4wiCIC10gNS3lG9jYPI/edit#gid=0 first. Report-out will be in the original comment.

**Comment by simonwex** [comment]
Hey @jbuck, could you add a list of services we should be adding testing infrastructure to?

**Comment by simonwex** [comment]
Status update:
 * Team met and prioritized apps for first pass
 * Stand-ups scheduled for 11:00am PDT, 2:00pm EDT
 * Each of us has research to do, longer-than-usual stand-up tomorrow to get into the nitty gritty
 * Bugs created for each related repo

**Comment by simonwex** [comment]
@ScottDowne did you make any progress with the login & makeapi mocks?

**Comment by simonwex** [comment]
Important notes from @gvn https://gist.github.com/gvn/4a69e18da27b929da086

**Comment by ScottDowne** [comment]
@simonwex No not yet, I was finishing the mofo-style thing first.

**Comment by Pomax** [comment]
I'm currently writing a quick and dirty (hopefully working) mock for login3 (basically an `testingmode` option switch that loads in "yep, everything's cool" responses to all the login API requests instead of actually *doing* anything)

**Comment by ScottDowne** [comment]
@Pomax is it something you see being usable for local dev too? Or just tests.

Example, would you switch it on for default env.sample files.

**Comment by Pomax** [comment]
If, for local testing, you just need "a generic user that is logged in", then yes. If you need yourself logged in, then no.

**Comment by Pomax** [comment]
I'm also running into magic testing errors atm where I've commented off everything *possibly* related to auth in webmaker.org, and it still generates magical 403 values instead of 404, and adding the `/verify` route in with a simple console logging handler does not trigger that handler. So... :tableflip: and I'm out

**Comment by Pomax** [comment]
mocked login has been implemented and works quite well, PR pending on https://github.com/mozilla/webmaker-auth/pull/23

**Comment by simonwex** [comment]
Significant progress has been made in this heartbeat. We still have a ways to go, though -- bumping another milestone.

**Comment by k88hudson** [comment]
Tickets for teach: https://github.com/mozilla/teach.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22Automated+tests%22

I'm using an "automated tests" label

**Comment by simonwex** [comment]
A lot of work has been done here this Sprint. This spans many projects including the new id.webmaker.org and teach.webmaker.org. Sharing out to the Engineering team; myself, Kate and Gavin will be hosting a session during the engineering monthly meeting next Wednesday April 1st.
