### ISSUE TITLE
Remove Privacy Day content from home page

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#352]
Official privacy campaign day campaign has ended. 

### Audience
Visitors to webmaker.org 

### Success
We did not a/b test with and without privacy so we have no benchmarks of whether this helped/hurt homepage conversion. We may reused privacy assets in the future and at that time we would set this up as an a/b to evaluate. 

### Vision
Current version of homepage without eyeball and vertical panel promoting privacy activity. 

### Measurement
n/a

### Roles
 * Phase: 
 * Driver: 
 * Decision Maker: @HPaulJohnson
 * Design Lead: 
 * Development Lead: @simonwex
 * Quality Verifier:

**Comment by secretrobotron** [comment]
@simonwex think we can accomplish this task in this heartbeat? Or wait until next?

Since we're just reverting back to what was there before privacy day campaign, we
- Don't require any new design,
- Don't need new copy, and
- Don't need new engineering

The only thing we should do is a bit of QA.

I don't mind driving.

**Comment by simonwex** [comment]
@secretrobotron let's touch base after demos tomorrow. I'll see who might have some spare cycles, but it seems reasonable to get it done in an afternoon.

**Comment by secretrobotron** [comment]
> seems reasonable to get it done in an afternoon

That's what I thought.

Sounds good. :family:

**Comment by HPaulJohnson** [comment]
Checking-in on this. Any eta on pulling down the privacy content on webmaker.org?

**Comment by OpenMatt** [comment]
came up in Heartbeat call today -- status?

**Comment by HPaulJohnson** [comment]
On a related note, is there a way we can think through a better process for future promotional content on the homepage? In an ideal world marketing/engagement would have a way to manage content directly so that we can swap promos in/out in more real-time. Realize this is probably a separate ticket but flagging it as food for thought.

**Comment by thisandagain** [comment]
100% Agreed @HPaulJohnson . Would you mind creating a new planning ticket to track this specific need?

**Comment by HPaulJohnson** [comment]
@thisandagain done. issue #389

**Comment by HPaulJohnson** [comment]
Any update on this ahead of Monday's meeting?

**Comment by simonwex** [comment]
I just submitted a PR that removes this content. ^

It'll get reviewed and pushed on Monday.
