### ISSUE TITLE
Mozillians Community

### ISSUE THREAD

**Issue by vsskanand** [MozillaFoundation/plan#353]
A mini social network for mozillians.

### Audience
Firefox student ambassadors, webmakers, SUMO.....every one who is associated with mozilla.

### Success
A personal profile ( just like mozillians.org ) where they can create events, push notifications, assign job to FSAs ( by REPs ), Stats of the work done  (like events managed, organised), badges earned,  Report of the contribution done.

### Vision
Personal profile for every member, Project management like creating an event, issue notifications, invite members to be a part of it. Just like a mini social network.

### Measurement
A satisfactory amount of contribution is done by every person who is associated with mozilla.

### Roles
 * Phase: 
 * Driver: 
 * Decision Maker: @secretrobotron
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by secretrobotron** [comment]
Whoa, thanks @vsskanand ! This sounds like a giant project, warranting lots of services and designers, engineers, and coordinators to build them. However, your idea also sounds like it's an amalgamation of disparate tools and services that already exist inside Mozilla. e.g. Reformatted a bit, this idea might be well suited as an extension to the mozillians.org project. I have a few questions for you:

- Where did you come up with this idea?
- What software are you/reps/FSAs doing now that doesn't accomplish what you need?
- Is this a need that lots of people/reps/FSAs are identifying?
- Do you see this as being a part of Firefox, Webmaker, Mozilla, Mozilla Learning?
- Who actually benefits from the feature set that you outlined? (My guess is principally reps.)

cc @hannahkane @thisandagain

**Comment by hannahkane** [comment]
I'm going to close this ticket, because I think these ideas are very related to the work we'll be doing in the Membership track of our 2016 strategic plan. New tickets will be filed!
