### ISSUE TITLE
Image localization

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/plan#354]
Image localization solution throughout Webmaker.org and its tools.

### Audience
Anyone who doesn't speak English.

### Success
Images with localized strings for each locale we support which will help bring the message from the image that we are trying to convey to the users.

### Vision
Solution to image localization which heavily rely on design assets.

### Roles
 * Phase: 
 * Driver: 
 * Decision Makers: @alicoding, @simonwex
 * Design Lead: @cassiemc, @iamjessklein 
 * Development Lead: 
 * Quality Verifier: @secretrobotron

**Comment by alicoding** [comment]
I would love to discuss with @cassiemc and @iamjessklein sometime next week when you guys have some time.

**Comment by iamjessklein** [comment]
:+1:  yes! let's do it. :camera:

**Comment by edrushka** [comment]
Fundraising tried some experiments with this with some success! https://github.com/mozilla/donate.mozilla.org/issues/812 Closing this - future work will be ticketed through advocacy team.

**Comment by alicoding** [comment]
@edrushka actually this is not the same, with the ticket you've pointed, but we have done it for the "This really helps us" image/font, so yes this is now resolved and can be closed.
