### ISSUE TITLE
Developer experience on webmaker-app

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/plan#357]
I'd *love* if we did a developer experience improvement two-week cycle on webmaker-app following MWC if possible, in order to address some of the key pain points we've been collecting from our own developers and some pitfalls in our process. Some examples of what we could focus on:

* Merging cordova and webmaker-app into a single repo
* Killing web-app only deploys
* Improvement of documentation, especially around mobile dev set up and common problems people run into;
* Further improvements to ops/deployment (versioning cordova, plugins if possible)
* Automating icon subsetting
* Improvements/tests for gulp or replacing gulp with npm scripts

Also based on the work he's done so far for us it would be cool to have jbuck on the cordova side of this team, as well as anyone else who's interested

**Comment by k88hudson** [comment]
cc @simonwex @thisandagain

**Comment by davidascher** [comment]
Can we move this to the webmaker-app repo, and get back to this plan (via the `http://build.webmaker.org/add` flow) later?
