### ISSUE TITLE
Pilot "Open Product Development" Program

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#358]
- product development isn't closed, but it's not accessible; hard to contribute design, plans, etc.
- lots of small tasks are time-intensive and desired diversity is unattainable
- we want volunteers who aren't necessarily coders
- projects need key contributors who can commit to time/work

### Audience
- community members: people who want to get involved, but don't know how
- contributors & staff: people who work on Mozilla daily, but need extra help in designing/building/thinking

### Success
- A generalized contribution pathway is defined for MoFo-specific projects for volunteers and MoFos (maybe a wider audience; reps?) who are looking to help and seeking help respectively.
- When we have a wacky idea for a product, need good documentation, localization leads, copy-editors in many languages, QA testers, extra designers, etc. etc. etc, it should be easy to ask the community for help and have an informal contract to complete a task.

### Vision
- A collection of tasks written up à la GSOC proposals from product/engineering/design/ops/devops teams
- A pilot program in which  two MoFos to take on volunteers committed to projects via "contract"
- A "volunteer posts" section on build.webmaker.org
- A feedback form on the posting section of build.webmaker.org

### Measurement
- feedback on feedback form
- traffic analytics on the postings page
- if both projects within the pilot program achieved success over the course of a quarter
- people start to use the system unsolicited as a way to engage with the contributor community and attempt to lighten load on intense projects

### Roles
 * Phase: 
 * Driver: @secretrobotron
 * Decision Maker: @secretrobotron
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by secretrobotron** [comment]
cc @k88hudson

**Comment by jgmac1106** [comment]
Here is my general thinking

I am new <2 yrs as a volunteer contributor to Mozilla and most of my work as been on the webmaker side of things but I am more cautious when it comes to the issues/tickets or even commenting on Git. 

I feel like it would be like some random weirdo sticking their head in my office while I try to work and saying, "You should do it this way."

The other issue is that while all of the issues are public on Git a lot of the design and feedback happens on private gDocs that public does not have access to. That makes sense you need to keep soem dirty laundry private but it makes offering feedback on the development a little more difficult.

In terms of testing out products I am a more than willing to be a guinea pig, currently undergoing my own workflow analysis to do a pluse/delta for returning to Firefox.

**Comment by secretrobotron** [comment]
I agree with the "random weirdo sticking their head in" analogy. But, what I'd like to do is develop the opportunity for those people to becomes less random (and hopefully less weirdo), and devote some amount of effort & time where results are expected from bother parties. My goal is to build some higher-bandwidth, higher-commitment relationships with volunteers. I think that might help the private document problem too.

Curious though: are you cautious about being active on git issues/threads because you'll feel like you've intruded? Have you had negative experience doing so in the past?

**Comment by jgmac1106** [comment]
No. Everyone has been very open and welcoming on git. I lurk on many of the
etherpads/git forums. I am more cautious because I have a loud mouth and
don't want to intrude. For most  of you this your 9-5. For me this what I
do when I am avoiding my 9-5.

Agree on building higher bandwidth with volunteers but I see most
volunteers communicating on pre-existing social media channels rather than
formal channels (git and discourse).  For the webmaker side of things
Twitter is way more active than Git or Discourse.

Hopefully with the refocus of the three year plan volunteer involvement
will increase in official channels.

**Comment by davidascher** [comment]
When you say contract, what do you mean?

**Comment by secretrobotron** [comment]
Some specification of the task(s)/project that everyone agrees on. What's involved, who's accountable. Somewhere between (but not including) very fancy bug and loose job contract.
i.e.
bug < this kind of contract < legally-binding contract

**Comment by davidascher** [comment]
Ok.  Wanted to make sure we weren't talking about adding money to the mix.

It'd be good to understand why a bug isn't useable for this, given that it
has a lot of cultural currency, and we've been known to successfully
stretch bugs to include a lot of things that aren't code at all.

**Comment by hannahkane** [comment]
@secretrobotron - what should we do with this ticket? Assign to a 2016 milestone? Close?

**Comment by secretrobotron** [comment]
Ok to close. I'll revise with new ideas when I can.
