### ISSUE TITLE
Find bengali localization contact

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/plan#360]
For Webmaker app, we need to either hire a contractor, find a high-quality translation service, or find a volunteer who is willing/able to do localization and localization review. Requirements are:

* native bengali speaker, familiar with modern terminology in apps/on the web
* able to do reviews/translation with relatively quick turn-around (< 1 week)
* access to an Android or FirefoxOS device

This is something that could be served by https://github.com/MozillaFoundation/plan/issues/358, but contractor/service is fine IMO.

**Comment by cassiemc** [comment]
Pretty sure this was done. @xmatthewx please reopen if I'm mistaken.
