### ISSUE TITLE
Work on localization and localization QA process

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/plan#361]
Some points to discuss:

### Project Planning
* How do we determine which languages should be shipped to prod/which languages should be prioritized?
* When should we not do localization (e.g. targeted campaigns)? When should we *not* upload to Transifex? (e.g. prototypes)
* When should string freeze happen? 
* How do we deal with strings that get added after string freeze (this inevitably happens sometimes)
* How can we build in localization quality review to the heartbeat process?
* How can we make sure all people responsible for project planning are aware of these guidelines?

### Community
* What are some significant pain-points for our current contributors? What actions can we take to reduce those pain-points?
* What are some ways we already recognize contributors for their work? Can we do more of that
* What are some new ways of recognizing contributors for their work?

### Technical
* How often and how should strings be uploaded to Transifex?
* How can we automate/detect when translations are out of date or missing from prod/staging infrastructure?
* What else can we automate to reduce human error?

**Comment by edrushka** [comment]
The fundraising team did a lot of work on this in Q4 with more to come (and proper documentation) in H1 2016.
