### ISSUE TITLE
badges.webmaker.org goes to dead badges 

### ISSUE THREAD

**Issue by LucyeoH** [MozillaFoundation/plan#362]
http://badges.webmaker.org/ currently goes to a page of old badges that you can no longer apply for. We should redirect this page to blog.webmaker.org/badges even it it's just a temporary measure until we get a proper badges welcome page set-up. We've had a few emails from confused people. 

cc. @hannahkane

**Comment by hannahkane** [comment]
Thanks, @LucyeoH. I added this to the webmaker.org repo for triage: https://github.com/mozilla/webmaker.org/issues/1326
