### ISSUE TITLE
Document current systems, draft redesign

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#363]
### Success

Current systems are documented including overall systems diagram. A plan is developed for a refactoring of systems. 

Here's a tentative checklist for documenting:
* [ ] MakeAPI
* [ ] login.webmaker.org
* [ ] sawmill
* [ ] lumberyard 
* [ ] webmaker.org
* [ ] badgekit
* [ ] TogetherJS
* [ ] Basket
* [ ] BSD
* [ ] goggles.webmaker.org
* [ ] thimble.webmaker.org
* [ ] Webmaker App
* [ ] Appmaker
* [ ] webmaker-firehose 
* [ ] webmaker-profile-2
* [ ] webmaker-events-2
* [ ] webmaker-mailroom
* [ ] openbadges-backpack
* [ ] openbadges-badgekit
* [ ] openbadges-badges
* [ ] make-valet
* [ ] badgekit-api-client
* [ ] mozilla-badges
* [ ] friendlycode
* [ ] badgekit-backpack
* [ ] CSOL-site
* [ ] openbadges-badgestudio
* [ ] Slowparse

### Prior Work:
https://github.com/MozillaFoundation/mofo-example-app/issues/33

### RACI
* Driver: @simonwex
* Lead Dev: @jbuck 
* Lead Design: N/A
* Decision Maker: @simonwex
* Quality Verifier: @Pomax

**Comment by Pomax** [comment]
Slowparse?

**Comment by jbuck** [comment]
@simonwex https://github.com/jbuck/mofo-architecture/tree/master/hsl

**Comment by Pomax** [comment]
that is a *very* fancy diagram

**Comment by davidascher** [comment]
niiice.
​

**Comment by simonwex** [comment]
List of things to make bugs out of:
* In order to reduce number of app servers for our client apps:
  * [ ] Allow direct client access to login.webmaker.org API
  * [ ] Allow direct client access to MakeAPI
  * [ ] Allow direct client access to BadgeKit API
* [ ] Create api.webmaker.org
  * [ ] Move x from x.webmaker.org into path /x * n
* [ ] Add redirection service (oath2 with whitelist) to login.webmaker.org

**Comment by jbuck** [comment]
@davidascher @Pomax @simonwex https://github.com/jbuck/mofo-architecture/tree/master/current

**Comment by Pomax** [comment]
@jbuck that is an amazing bit of diagram... and should totally be HTML O_O

On a more constructive note, I think this is still missing the http-on-https camo proxy that thimble uses.

**Comment by jbuck** [comment]
- [ ] screenshot service

**Comment by simonwex** [comment]
@jbuck could you update this ticket with the latest versions of the diagrams?
