### ISSUE TITLE
Prototype Unified Making Experience

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#365]
From the Toronto work week we have a good sense of how the prototypes we've been working on will port to mobile, but have quite a bit of prototyping to do to have some confidence before moving into a UI pass. This sprint is to develop simple InVision prototypes for a unified experience across platforms.

#### Deliverables
- Prototype of core making and discovery experience on mobile
- Prototype of core making and discovery experience on desktop / tablet
- Benchmarks and direction for UI design to be completed in the next sprint

#### Milestone
Desktop / Tablet - https://github.com/mozilla/webmaker-desktop/milestones/Unified%20Prototype
Mobile - https://github.com/mozilla/webmaker-app/milestones/Unified%20Prototype

#### RACI
Phase: Design
Owner: @xmatthewx 
Decision: @thisandagain
Lead design: @flukeout + @sabrinang 
Lead dev: n/a
Quality: @cassiemc

**Comment by flukeout** [comment]
Link to "Themer" prototype screens - http://bit.ly/1vTEwIj

**Comment by cassiemc** [comment]
Adding @sabrinang here to help with additional UX/UI considerations.

**Comment by xmatthewx** [comment]
Here's a quick recap of the work week that impacts this heartbeat. @cassiemc will likely share a more rich and complete summary. Hit me up on IRC for corrections and omissions.

## We considered content

 - We asked: What is webby? We found [answers](https://cloud.githubusercontent.com/assets/53411/6446839/c2bc27e0-c0db-11e4-99ca-102dab2ab4a9.jpg).
 - We listed [types of content enabled by Tiles](https://cloud.githubusercontent.com/assets/53411/6450217/5f3792ea-c0f4-11e4-9c25-cd00d3f15686.png).
 - We took a first step toward creating examples of lead user content. (link expired)

## We tested prototypes

Key takeaways
 - making while mobile invites a different variety of content than on desktop
 - deeply integrated collaboration is interesting & valuable, but complex 
 - simplicity begets understanding, but can also put a limit on imagination
 - the power and flexibility of the tiles paradigm is not immediately obvious


## We iterated on tiles

We produced lots of [refined & annotated sketches](https://drive.google.com/a/mozilla.com/folderview?id=0B_rbDAen9prkSE0ydS1rNWRHV00&usp=sharing) that cover:
 - navigation 
 - aerial editor
 - tile editor
 - element editor
 - code editing via UI and/or keyboard

We took inventory of [elements and attributes](https://cloud.githubusercontent.com/assets/53411/6446785/4e95576a-c0db-11e4-81cc-05a74709d11d.jpg) to help identify the most viable set of features.

**Comment by cassiemc** [comment]
Here are all the sketches I scanned from the workweek – @xmatthewx maybe you can help figure out how to make these most useful in this process, if they are at all? https://www.dropbox.com/sh/5sd3imrguvkn94f/AAAjlYM5mmahKw_KM2jOHSeba?dl=0 

Worth calling out this pdf specifically – it's all of the revised and edited and most finalized sketches for the tiles concept: https://www.dropbox.com/s/4u9lme5disvw707/final-tiles-sketches.pdf?dl=0

**Comment by xmatthewx** [comment]
Thanks. Link I posted above points to an edited set of the [latest Tiles sketches](https://drive.google.com/a/mozilla.com/folderview?id=0B_rbDAen9prkSE0ydS1rNWRHV00&usp=sharing) as individual image files on gdrive.

**Comment by thisandagain** [comment]
Really excellent work done in the last heartbeat. Latest progress and notes for the next SOW can be found here:
https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g7537eac12_832

Tracking next steps in #377
