### ISSUE TITLE
Draft next research schedule and reporting plan

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#368]
Going to work with @LauraReynal on firming up process for scheduling, doing, and reporting research as we move into another round of it.

- [x] recap
- [ ] schedule for more research (Chicago & UK)
  - who do we send?
  - designers? how many
- [ ] updating audience site
- [x] figure out scheduling/process for building reports
  - time estimates and resources
  - remove personelle bottlenecks
- [ ] the "big one"

#### RACI
Phase: Research / Build / Ship
Owner: @secretrobotron 
Decision: @LauraReynal 
Lead design: n/a
Lead dev: n/a
Quality: @thisandagain, @davidascher

**Comment by LauraReynal** [comment]
Adding : 
- Big reports, synthesis of the existing and future research => Define scope and timeline 
    * GSMA "emerging countries report" 
    * Webmaker Report synthesis of developing and developed markets 
...

**Comment by LauraReynal** [comment]
closing this => everything is tracked in other tickets :smile: :ear_of_rice: :tulip:
