### ISSUE TITLE
Implement git-flow style branching standard across Webmaker Apps

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#369]
![image](https://cloud.githubusercontent.com/assets/25260/6260599/23a6ccf8-b796-11e4-95f8-b8bb25408213.png)

http://nvie.com/posts/a-successful-git-branching-model/

When we do this, let's make sure we also:

* [ ] update necessary documentation
* [ ] add "hotfix" documentation
* [ ] send out communication where possible to help contributors adjust workflow, and help contributors rebase their PRs against the new dev branch
* [ ] switch the default branch in github to be dev (note that this is a github-only convention, this concept does not exist in git – so we may also need to help people adjust their git commands, and expect that people will do it wrong sometimes)
* [ ] update any githooks or bots that reference master where needed
* [ ] update travis to use the dev branch for nightly builds in all repos.
* [ ] *insert your step here*
* [ ] ...
* [ ] Profit!

### Child tickets:

* mozilla/webmaker-app/issues/1223

**Comment by gvn** [comment]
**Note:** This has been recommended to me...

https://github.com/petervanderdoes/gitflow

**Comment by OpenMatt** [comment]
status?

**Comment by OpenMatt** [comment]
got a status update @simonwex  ?

**Comment by simonwex** [comment]
@OpenMatt bumping this, we made some progress but haven't been able to dedicate multiple days to this and the impact it'll have on devops.

**Comment by OpenMatt** [comment]
@simonwex it's that time again... :) status update?
