### ISSUE TITLE
Prepare and Execute Chicago Research

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#371]
Prepare the Chicago research trip :earth_americas: 

RACI

Phase: Research / Build / Ship
Owner: @LauraReynal
Decision: @thisandagain 
Consulted: @cassiemc 
Lead design: n/a
Lead dev: n/a
Quality: @secretrobotron 

Tracking in https://github.com/MozillaFoundation/research

Proposal here https://github.com/MozillaFoundation/research/issues/14

**Comment by OpenMatt** [comment]
@LauraReynal status?

**Comment by LauraReynal** [comment]
In chicago currently - closing
