### ISSUE TITLE
Update Audience page on build

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#373]
**Goal**: we have more research data and we should combine everything and update the audience page. Also current design of the page is not adequate regarding the information that needs to get there. 

##### RACI
Owner/ Driver : @secretrobotron
Decision: @LauraReynal
Consulted: @thisandagain 
Design: @vazquez 
Dev: TBD 
Quality: @cassiemc

**Comment by cassiemc** [comment]
Assign @vazquez here (p2) :+1:

**Comment by LauraReynal** [comment]
Hey @secretrobotron  @vazquez - Im defining the scope here and we can discuss it during our Kick off meeting today :santa: 

Goal: Update the audience page 

*Content that needs to be added*
- Personas from India => @secretrobotron and @LauraReynal to choose 
- The research Map => Integrate the MapBox Research map somehow 
- The detailed research reports ( Bangladesh, Kenya, India, Brazil, the Synthesis)
- The new Webjourney graph, and its legend 
- The learning Scenarios 

*Design Work* 
- Rework the way we present a persona. (bigger photo, possibility to have 2 pictures per person (one portrait and one environment), possiblity to show where they are on the map, or have a country icon) 
- Find a way to display a learning scenario for each persona,
- Design the research map => right now the icons arent great and neither are the colors. Would be nice to have Webmaker palette. 

Other suggestions are welcome.

**Comment by LauraReynal** [comment]
![screen shot 2015-03-17 at 11 00 29](https://cloud.githubusercontent.com/assets/8261945/6685785/e1696c38-cc94-11e4-93ee-aeebd5f01b6d.png)

**Comment by LauraReynal** [comment]
![screen shot 2015-03-17 at 11 02 58](https://cloud.githubusercontent.com/assets/8261945/6685807/32d029c2-cc95-11e4-8cbb-1ec1394fccf2.png)

**Comment by LauraReynal** [comment]
Ticket for the map: 
https://github.com/MozillaFoundation/research/issues/19

**Comment by cassiemc** [comment]
Hey @LauraReynal , this prep work looks great. Just a note – I didn't think we did kickoffs for p2s. @vazquez can let you know if he thinks he'll have time this heartbeat, given the teach stuff which is his P1. Not to be a downer. Hopefully there is time.

**Comment by LauraReynal** [comment]
Oh sorry I did not know all of this. Chatting today with @secretrobotron and @vazquez 
We can always reduce scope or push it to next heartbeat if needed. 
Will update the ticket - thanks @cassiemc

**Comment by vazquez** [comment]
I sketched wireframes for the Audience Page as well as a Persona page.

###### Audience Page

![audience](https://cloud.githubusercontent.com/assets/1119821/6901846/0d0e36a4-d6de-11e4-8cc5-e1c6616afd3a.png)

###### Persona Page

![persona](https://cloud.githubusercontent.com/assets/1119821/6901852/15fa112a-d6de-11e4-9cf2-d5d3202f318c.png)

**Comment by thisandagain** [comment]
I think this is important but not a blocker given existing design and development priorities. I'm also curious if this would be more efficiently completed after the Chicago research trip. Thanks for moving to the next sprint @secretrobotron

**Comment by secretrobotron** [comment]
Thought the same thing, @thisandagain . Don't want the work to escape us as more profiles come in from @LauraReynal 's research. Think April 24 is still too early?

**Comment by LauraReynal** [comment]
After Chicago sounds good - so lets move it to early May xth, because I wont be able to provide content while im out there doing interviews

**Comment by OpenMatt** [comment]
proposal to close this for now

**Comment by secretrobotron** [comment]
Proposal accepted.
