### ISSUE TITLE
Create MozFest 2015 website

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#374]
This is the meta-ticket for the MozFest 2015 site.

Driver: @edrushka
Design: @iamjessklein and Adil (UX contractor) (@Roberto-Cruz has done initial work)
Dev: @ScottDowne 
Copy @kevzawacki 
Decision Maker & Final signoff: @Saallen 
Consulted: @thornet @HPaulJohnson Misty, Spike, Gunner 
Informed: @amirad     Please add yourself :)

**Comment by edrushka** [comment]
##What has happened so far:
- [x] Site research 
- [x] Brand audit 
- [x] User research via survey
- [x] Meetings with MozFest team to review their needs
- [x] [Recommendations] (https://github.com/MozillaFoundation/plan/issues/341#issuecomment-75680689) for IA 
- [x] Initial wireframes

##What will happen next:
- [ ] Sarah and Roberto to discuss wireframes with MozFest team and will integrate their feedback
- [ ] Revised wireframes will be presented to design team for feedback @cassiemc 
- [ ] Preliminary discussion with dev team about functionality @simonwex 
- [ ] Design (details to be ticketed)
- [ ] Dev  (details to be ticketed)
- [ ] Launch

**Comment by edrushka** [comment]
@cassiemc, @Roberto-Cruz and I would love to get some feedback from your team on the MozFest site wireframes. Whatever format works best for you: the weekly design call, a meeting....

**Comment by cassiemc** [comment]
@edrushka Usually for design review, just pick someone and mention them in a comment for design review, so... "Design R? @cassiemc". If you're not sure who to pick, you can always tag me and I'll try to find someone if I'm not available. 

OR you can message the group in #mofodesign on IRC, 

OR you can join our weekly design crit on Wednesday afternoons. Though your time for feedback might be limited in that venue b/c there are 6 people's work to get through. Lots of options though!

**Comment by edrushka** [comment]
Handoff from Roberto to @iamjessklein detailed here: https://etherpad.mozilla.org/mozfesthandoff

**Comment by cassiemc** [comment]
@edrushka is there a milestone for subtickets? I'd like to file separate design tix.

**Comment by edrushka** [comment]
@cassiemc ideally design will be complete by May 8, and the build will be complete by May 22

**Comment by cassiemc** [comment]
Sorry, I meant a label @edrushka

**Comment by edrushka** [comment]
@cassiemc I use the mozfest label when I work in the /plan repo
I've been labeling subtickets filed in the /mozillafestival.org repo like this: https://github.com/mozilla/mozillafestival.org/issues

**Comment by edrushka** [comment]
Update: UI work is well underway and on schedule. View the details [here] (https://github.com/mozilla/mozillafestival.org/issues/17).

**Comment by edrushka** [comment]
Moving to next milestone as this work is ongoing. Progress is in the UI ticket in prev. comment.

**Comment by edrushka** [comment]
This heartbeat we'll finish design and start (and hopefully finish!) the build.

**Comment by cassiemc** [comment]
@edrushka @ScottDowne Where is the build ticket for this? Want to add the svg assets from Adil's files. In the meantime, find them here: https://www.dropbox.com/sh/woqt8g4oaq72ad0/AAAEYtaZbh2ocSTunjEtpTZua?dl=0

**Comment by edrushka** [comment]
Build ticket is here: https://github.com/mozilla/mozillafestival.org/issues/38 
I added the assets.

**Comment by cassiemc** [comment]
thanks @edrushka!

**Comment by OpenMatt** [comment]
status?

**Comment by edrushka** [comment]
Scott's got most of this on staging. Blockers have been identified here: https://github.com/mozilla/mozillafestival.org/issues/38#issuecomment-105477933

We plan to ship next week.

**Comment by edrushka** [comment]
Update: 
- Site is ready on staging: https://mozillafestival-org-2015.herokuapp.com/
- QA has started should be done by EOD June 5: https://github.com/mozilla/2015.mozillafestival.org/issues/81
- Launch early next week.

**Comment by edrushka** [comment]
Done and done :)

**Comment by iamjessklein** [comment]
:+1:

**Comment by Saallen** [comment]
:fireworks: :boom:
