### ISSUE TITLE
Move webwewant.mozilla.org to a MoFo-managed AWS setup

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#375]
The https://webwewant.mozilla.org domain is no longer useful to MoCo folks, but MoFo (specifically @davesteer) still wants it.  We need to simplify it (decouple it from the realtime download data), move it to AWS, and make sure we can keep it up.

### Audience
People that @davesteer needs to reach.

### Success
* https://webwewant.mozilla.org is up, simple, fast, and useful in our policy & advocacy work.
* MoCo doesn't need to worry about it
* Hopefully MoFo doesn't need to worry about it because it just works =)

### Vision
There are some tasks that MoCo need to do (I don't have details).  We should understand those and figure out the overlap with the tasks needed to move it to AWS (as that move may make some of the pending actions unnecessary).

I suggest an information gathering with @simonwex, @jdotpz, @pmclanahan, where clarity can be brought and todo lists built.

It's important to me that this transition can happen cheaply in terms of dev-hours.  If this becomes a Big Project, we may have to reconsider it.  So first step is just to understand the work needed.

### Measurement
Google Analytics w/ MoFo credentials, so we can understand usage.  Not sure if we can transfer old data to new profile.

### Roles
 * Phase: 
 * Driver: @edrushka
 * Decision Maker: @DaveSteer
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by davidascher** [comment]
Note: current design has dots on a map whenever someone from that location downloads firefox.  That seems like a coupling that would be hard to maintain over in AWS, what with sending packets out of the Mozilla subnet to AWS.  And not critical for @DaveSteer, as per:

> If removing the geoip dots would make this much easier to deploy, then I think we can remove it. It adds for a nice flair (conveys activity...motion), but I don't think it needs to be a 'real time' look at who is answering/downloading. Perhaps there is a way to keep the imagery as a symbol, without the need to tie it to the back end. Something we can work on with Foundation devs/designers.

Given that, we may need a simple design "fix" for the absence of live data.

**Comment by davidascher** [comment]
Forgot to cc @bensternthal

**Comment by edrushka** [comment]
Clarifying: it's https://webwewant.mozilla.org

**Comment by edrushka** [comment]
@simonwex, @jdotpz, @pmclanahan, have you had a chance to discuss this?

**Comment by simonwex** [comment]
I've emailed Paul and Ben to see where this code lives and what's involved in hosting it elsewhere.

**Comment by pmclanahan** [comment]
He did indeed. We can discuss here though if you'd rather. Basic info is:

* Wiki: https://wiki.mozilla.org/Websites/Glow_2014
* Mana: https://mana.mozilla.org/wiki/display/websites/webwewant.mozilla.org
* Github: https://github.com/mozilla/mrburns/
  * Readme for worker daemons: https://github.com/mozilla/mrburns/blob/master/smithers/README.md

**Comment by simonwex** [comment]
Thanks for hopping in here, @pmclanahan. How do the raw logs get from download.mozilla.org into smithers/bart right now?

**Comment by pmclanahan** [comment]
the load balancer sends the d.m.o logs to rsyslogd on the primary web server, which formats and sends the output to a file. bart.py moves that file to a timestamped file and sends SIGHUP to rsyslogd every minute to get a minute's worth of logs, then gets the IPs and throws them onto the queue in Redis. lisa.py then processes that log.

**Comment by edrushka** [comment]
What is the next step, here?

**Comment by bensternthal** [comment]
@simonwex do you need anything additional to make a decision. I would like to decide on a path forward this week.

**Comment by jdotpz** [comment]
cc'ing @jbuck  for transition

**Comment by simonwex** [comment]
I'm happy for us to take this over. I think we'll download some canned "download activity" data to simulate it, which will require some dev time.

 @edrushka, could you get this on your list and we can figure out rough timing?

**Comment by floatingatoll** [comment]
For paper trail purposes, I cc'd @simonwex and @edrushka on the MoCo IT bug 1138691 regarding this.

**Comment by bensternthal** [comment]
@edrushka can you provide an update on timing, rough timing is fine.

**Comment by edrushka** [comment]
I haven't forgotten about this :) Will report back when I have a better idea of the timing.

**Comment by edrushka** [comment]
@bensternthal Would it work if we planned to do the handover later this summer. Say August?

**Comment by bensternthal** [comment]
This is fine from my perspective however there may be some pressure to do this sooner due to all the IT migrations and shutdowns that are looming.

Richard mentioned in the original bug that he was watching this issue. Richard can you comment on the proposed date?

**Comment by OpenMatt** [comment]
@edrushka status?

**Comment by edrushka** [comment]
@floatingatoll - are you Richard? :) Any thoughts on the proposed date?

**Comment by fox2mike** [comment]
Hello @edrushka and @bensternthal - Chiming in for @floatingatoll here. From our viewpoint, earlier is better. We're still working on finalizing the migration plans (for the datacenter that webwewant is hosted in) and I don't have concrete dates as of now. If that changes, I'll keep you posted on here and in the meantime we can continue supporting the OS side with security updates etc.

**Comment by floatingatoll** [comment]
The existing webwewant deployment is running in *two* datacenters. Do we need to keep both datacenters live between now and the eventual migration later this year? If we can decommission PHX1, that removes our timeline concerns.

**Comment by edrushka** [comment]
@simonwex @davidascher need your guidance here ^

**Comment by simonwex** [comment]
@floatingatoll it's fine if we're only in one datacenter for a bit. I presume you guys have monitoring on that site enabled?

**Comment by OpenMatt** [comment]
status?

**Comment by OpenMatt** [comment]
@simonwex will updated -- @edrushka is blocked here and needs help.

**Comment by jbuck** [comment]
https://webwewant.mozilla.org is currently not loading any data - I filed this in https://bugzilla.mozilla.org/show_bug.cgi?id=1168576 . This is because data collection has been turned off.

**Comment by edrushka** [comment]
Closing this for now. May reopen when Advocacy team is at full capacity again.

**Comment by bensternthal** [comment]
@edrushka can you provide some more info? If your team does not pick this up in Q3 we will to make sure IT is aware in case anything has to done for the PHX1 exit.

**Comment by edrushka** [comment]
@davidascher or @simonwex do you think we'll be able to take this on for Q3?

**Comment by Melechuga** [comment]
I'm adding @brettgaylor to this as the website sits under the Ford grant at the moment.

**Comment by bensternthal** [comment]
so... no updates here for quite awhile.. we will assume you will not be taking this until we hear otherwise.

We will move this to our AWS infra so we have visibility and monitoring.

**Comment by pmac** [comment]
Hi all. Remember this one :)

I'm here to ask if anyone is still interested in keeping webwewant.mozilla.org alive? It [needs some maintenance work](https://observatory.mozilla.org/analyze.html?host=webwewant.mozilla.org) to bring it up to par with our security guidelines, so we're faced with the decision to keep it up as an archive like it is now and do the work to fix it, or decommission it. Our thought currently is to go with the latter unless someone here objects and would like to take over hosting and maintenance. Someone can always stand up an instance if this or something else at that domain in the future even if this one is taken down.

Interested in your thoughts. Thanks for your time.

**Comment by brettgaylor** [comment]
I would vote for decommissioning, since it is no longer current with branding or Internet Health framing.

**Comment by simonwex** [comment]
I agree on decommissioning. It'd be good to invest some time to make sure that the documentation is complete. It'd be a great thing to relaunch one day aligned with our issues agenda.
