### ISSUE TITLE
Celebrate Errietta's Birthday!

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#376]
I'll start the dance party!
![Version 21 Dance](http://i.giphy.com/12m5srHYOriGwU.gif)

**Comment by LucyeoH** [comment]
Happy birthday Errietta!

![birthdaygif](https://cloud.githubusercontent.com/assets/8070833/6578573/5cde6c58-c71b-11e4-94fe-1cc20cd90128.gif)

**Comment by toolness** [comment]
Woooo happy birthday Errietta!

<img src="http://media.giphy.com/media/FRQfYwOKdEaTS/giphy.gif">

**Comment by jdotpz** [comment]
Have a foxy birthday E!
![fox-too-quick](https://cloud.githubusercontent.com/assets/1373628/6578911/fefe7d0e-c714-11e4-8af5-610919020792.gif)

**Comment by Saallen** [comment]
Happy Birthday!
![happybirthdayto me](https://cloud.githubusercontent.com/assets/10194015/6579015/799e7f12-c73f-11e4-824e-3ebd24d936ca.gif)

**Comment by alicoding** [comment]
Happy Birthday!! http://i.giphy.com/KTVOOk1Rgc0Eg.gif

**Comment by cadecairos** [comment]
Happy Birthday!

![happy birthday](https://cloud.githubusercontent.com/assets/438003/6579622/b2e88862-c721-11e4-961b-a6e4ad6b60a3.gif)

**Comment by amirad** [comment]
Happy day of birth! 
![bday](https://cloud.githubusercontent.com/assets/10170768/6579741/8ad33ef2-c722-11e4-80e4-3cd0db4932a3.gif)

**Comment by errietta** [comment]
![img_20150310_124422](https://cloud.githubusercontent.com/assets/134585/6579807/8201295c-c744-11e4-98a0-a7d2d6638a13.jpg)

**Comment by errietta** [comment]
:heart: you guys i hadn't seen this then someone mentioned it to me thanks so much :grinning:

**Comment by secretrobotron** [comment]
# ᕕ( ᐛ)ᕗ

# (╯ ᐛ）╯︵ ┻━┻

# ♪┏(・o･)┛♪

**Comment by gesa** [comment]
![](http://snaps.akibraun.com/highest-of-fives.gif)
