### ISSUE TITLE
Complete UI and explore "Tinker Mode" for unified tool

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#377]
The new Webmaker platform aims to offer a premier experience for creating and viewing webby content. 

### Audience
 - Firefox users on desktop and Android
  - Users on Webmaker who want to create content
  - People who view content on Webmaker

### Success
 
By the end of this heartbeat, we would like to have:
 - UI prototype
 - annotated docs for implementation
 - prototype of 3-4 "tinker" experiences  
  - ex: rgb/hex color, link style & destinations, image source https://github.com/mozilla/webmaker-desktop/issues/10

### Vision

UI prototype - tool should feel clean, approachable, and fun. Aesthetics of the experience should be unified across mobile & desktop/tablet. Interface should clarify the relationship between various views, zoom levels, and editor states.  

Annotation - to enable quality implementation, notes should clearly indicate interactions, transitions, and responsive styles.  

Tinker - to differentiate Webmaker from the pack, this platform strives to embed hints about the underlying technology in the making process. The best solutions will immediately increase a user's ability to make something better in their project. 

### Roles
 * Phase: Design
 * Driver: @xmatthewx 
 * Decision Maker: @thisandagain
 * Design Lead: @flukeout @sabrinang 
 * Development Lead: @simonwex
 * Quality Verifier: @iamjessklein

**Comment by thisandagain** [comment]
To be clear, is this is a request for an additional sprint dedicated to adding learning features to the prototypes developed to date? This would be in lieu of doing the UI pass on the prototypes developed in #365?

/cc @cassiemc @xmatthewx

**Comment by cassiemc** [comment]
Not in lieu; want to see the UI advance quickly, but I think given the skills needed & our team composition we could do this in parallel. It will largely depend on what else needs resourcing in the next heartbeat.

**Comment by thisandagain** [comment]
To clarify from our meetings last week, the scope of this sprint is to build out the UI for the unified prototypes based on the work done by @xmatthewx @flukeout and @sabrinang last heartbeat. In addition, we need to dig in deeper on the "Tinker Mode" features for the MVP. @xmatthewx can you please fill in the details and refine the description above? I'd like to track both of these in one planning ticket.

**Comment by cassiemc** [comment]
I assigned @sabrinang and @flukeout to carry on the work from last heartbeat, and have added @iamjessklein for quality due to her learning design experience. I'd like to be kept in the loop though, please!

**Comment by xmatthewx** [comment]
I've updated the description above. This ticket now tracks:
 - UI work
 - Annotation
 - UX for tinkering

Note that UX for tinkering will need to keep a narrow scope if we hope to tackle everything else.

**Comment by thisandagain** [comment]
Sounds good. Let's try to just focus on Tinkering mode in the "Link" and "Color" areas. That seems reasonable for MVP.

**Comment by iamjessklein** [comment]
:+1:  let me know when there's something to look at :)

**Comment by xmatthewx** [comment]
Two best places to track this work 

 - Notebook: Feature scope, WIP screens, link to benchmarks
  - http://bit.ly/webmaker-ui-notebook
 - Issue Milestone: 
   - https://github.com/mozilla/webmaker-desktop/milestones/Unified%20UI

**Comment by thisandagain** [comment]
Tracking next SOW in #405

**Comment by xmatthewx** [comment]
We developed a direction for the UI and pushed the UX forward on two key intersections for learning and making (color and links).

### UI direction

![screenshot 2015-03-30 11 38 11](https://cloud.githubusercontent.com/assets/53411/6903924/6a695074-d6eb-11e4-9a73-459444a51846.png)
![screenshot 2015-03-30 11 36 35](https://cloud.githubusercontent.com/assets/53411/6903925/6a6a72c4-d6eb-11e4-9cb5-938b97ee932e.png)

### UX & prototype for tinkering with color

 -  [prototype](http://jsbin.com/yeheru/)

![tinker with color](https://cloud.githubusercontent.com/assets/25212/6836629/25b57450-d301-11e4-8920-6ce2d2d88ee4.png)

### UX for tinkering with links
 
![ux-tinker-links](https://cloud.githubusercontent.com/assets/53411/6903951/9cd3d21e-d6eb-11e4-92c4-fcc6161482d3.png)

cc @OpenMatt and @edrushka 's
