### ISSUE TITLE
Update MozFest site with Save the Date banner

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#379]
Driver: @edrushka
Design: @Roberto-Cruz 
Dev: @ScottDowne 
Decision-maker: @Saallen 

### MVP
1) replace text on current banner http://2014.mozillafestival.org/ with : 
Save the Date for MozFest 2015
November 6-8
Ravensbourne College, London
2) replace button with:
'Sign Up For Info' button --> links to email signup to receive further updates about the festival.

### Nice to Have 
3) 'Add To My Calendar' button for users to add dates to their personal iCal or Google Calendar

**Comment by Saallen** [comment]
Hey
Banner choice would be the darker banner with the photo background under the Nav bar.

**Comment by Roberto-Cruz** [comment]
Hey, I have made a Redpen for this issue. 
Please take a look. 

https://redpen.io/p/ag4d245f69346c7879

**Comment by Roberto-Cruz** [comment]
Hi, 
Here is the latest update on the redpen project
https://redpen.io/pj38df7e097269e249

**Comment by Roberto-Cruz** [comment]
Please, visit one more time the Redpden project. I recently update it according to the last round of feedback 

https://redpen.io/pj38df7e097269e249

**Comment by edrushka** [comment]
@alicoding We've finalized the design. @Roberto-Cruz will get you the design file.

**Comment by Roberto-Cruz** [comment]
@alicoding here is the file. If you need anything else please let me know. 

https://drive.google.com/a/mozilla.com/file/d/0B4q3TCz6z_aJNjFxX3hUUkkxQ2c/view?usp=sharing

**Comment by alicoding** [comment]
@edrushka @Roberto-Cruz the only thing I'm still unclear about is where the form should submit to. Not sure if you guys have any technical information about that available for me to start working on this?

**Comment by edrushka** [comment]
The form should link to this page, updated for 2015 https://sendto.mozilla.org/page/s/mozfest2014-save-the-date

This looks like a BSD thing to me. I'm tagging @valianttry who has hired a BSD contractor who can hopefully take care of the details. Not sure of his (the contractor's) actual start date, so @Saallen if you can help, that might speed things along.

**Comment by edrushka** [comment]
The comment above is incorrect! Signing up on the MozFest site should not link to a second signup page. Sorry for the confusion!

**Comment by Saallen** [comment]
Last year, you clicked on a button  "Save the Date" and it brought you to the BSD page. @thornet are you able to confirm the actions for Save the Date last year and how we captured peoples email address?

**Comment by alicoding** [comment]
@edrushka how do I get access to the current wordpress site? I just finish installing Wordpress on my local machine but still lots to setup to make it look the same as mozfest live site.

**Comment by edrushka** [comment]
@alicoding I just made you an account. Will PM you the password. Also, have you seen this ticket that Mavis completed. It contains epic amounts of WP info: https://github.com/MozillaFoundation/movement-building/issues/22

**Comment by valianttry** [comment]
@edrushka our contractor is mostly just helping with email production, Mavis is probably the best person to help stand up a new email opt-in.

**Comment by edrushka** [comment]
I chatted with Andrea and she can create the BSD group.

@Saallen or @thornet can you please outline if you simply want a clone of the 2014 "more info" group (if there was one) or if you want something different. Andrea's reachable on Skype (Pacific time) if you need to connect with her directly.

**Comment by Saallen** [comment]
Last year we emailed all those who signed up for festival updates 2014 key pieces of info along the Mozfest timeline- such as Call for Proposals going live, a reminder when the call closed and we let them know when tickets went on sale.

I would like to email those who signed up for Updates in 2014 about the new 2015 dates for this years festival.  
I would like to point them to this years website asking them to resign up for updates this year. But I would not contact update 2014 list again then. I am not sure what @andreas thoughts are about this action.

**Comment by edrushka** [comment]
Did you mean Andrea? @valianttry

**Comment by valianttry** [comment]
@Saallen it's totally fine to target last year's mozfest attendees segment in BSD with mozfest 2015 emails. Do you feel like you have the know-how to set up an email in BSD? I can help ID the correct audience segment.

**Comment by Saallen** [comment]
Sorry, I was not watching predictive text @valianttry :disappointed: 
I will set up a new new email now in BSD and send you both a draft copy and get your feedback.
I believe I know the audience but will double check eveything with you pre-send. Thanks

**Comment by Saallen** [comment]
I have cloned a new Save the date form http://mzl.la/Mozfestdate-2015-
I created a new BSD email to send to a list of receipients which @thornet @valianttry @edrushka all recieved a draft copy of.

**Comment by edrushka** [comment]
@alicoding do you have the information you need to complete this ticket?

**Comment by alicoding** [comment]
Sorry I got super distracted with the login heartbeat. I don't know if I'm going to be able to finish this today though?

cc @simonwex

**Comment by simonwex** [comment]
@alicoding don't sweat it, I'll get it assigned next week. We resourced this Heartbeat before we acknowledged that we have a lot of miscellaneous work to do.

**Comment by OpenMatt** [comment]
@simonwex: are we moving this to April 10 Heartbeat then?

**Comment by edrushka** [comment]
Yes. We need to. This remains a P1.

**Comment by edrushka** [comment]
@alicoding Are you able to prioritize this ticket? It'd be great to have the site updated asap.  Please let me know if there are any remaining blockers.

**Comment by simonwex** [comment]
Hey @edrushka, this won't be @alicoding, this will be @ScottDowne.

**Comment by edrushka** [comment]
@ScottDowne can you please prioritize this over Teach stuff this week? I cleared this with Wex. We just need to get this one done. Thanks!

**Comment by ScottDowne** [comment]
Cool, can do.

I have read through the ticket history.

I'll bug @alicoding and look through https://github.com/MozillaFoundation/movement-building/issues/22 for my wordpress woes.

I'll implement this design based on earlier comments: https://redpen.io/pj38df7e097269e249
if that's not the right one, now would be a good time to correct me :)

@edrushka @valianttry @Saallen I am a bit fuzzy on what we do with the user emails. It sounds like it's going somewhere in BSD, but that's not a complete picture for me.

**Comment by Saallen** [comment]
Hi- hopefully I can outline the process for emails.
If people click on the updates Button this would link them to a [BSD sign up] (https://sendto.mozilla.org/page/s/mozfest-2015-save-the-date) form where they would enter their email address in order to receive updates about the festival over the coming months. The email addresses are keep in the savethedate2015 constituent group on BSD. Happy to jump on a 5 mins vidyo chat to talk through this if need :smile:

**Comment by ScottDowne** [comment]
Ok, that's super simple.

**Comment by edrushka** [comment]
Just to clarify, @Saallen  if they try to sign up directly on the homepage as per this design https://redpen.io/pj38df7e097269e249 do you want them to get redirected to another form or can the action just be completed there on the homepage?

**Comment by ScottDowne** [comment]
Linking to [BSD sign up] (https://sendto.mozilla.org/page/s/mozfest-2015-save-the-date) is super easy.

Doing it right in the page, I'm not familiar with, so I'll need to spend time researching that. It's probably a BSD thing I need to dig up. If anyone has done it before, help would be nice. I'm sure it's possible and I'm sure I can figure it out, but just so we all know, it's an unknown.

**Comment by ScottDowne** [comment]
Actually, thinking about doing it right in the page.

It's worth investigating and giving it a try. It might be easy, and would be a much better UX.

**Comment by Saallen** [comment]
If the action could be done on the page- then awesome, I think that would be a way nicer experience than sending people to BSD- but like Scott said above, it is not something we have done before.

**Comment by edrushka** [comment]
We just talked this through and agreed in the interest of getting this done quickly, we'll do a version without that UX (so we'll just have a button that links to the form Sarah already created), and later, if we have time, we'll try to make it happen right on the page.

**Comment by Saallen** [comment]
:+1:

**Comment by ScottDowne** [comment]
So, because we have just a button to link to the form for now, a few things need to change.

1. I'm proposing we move the button into the header.
2. remove the red date circle (it conflicts with the button and pulls attention away)
3. add more context to the header without adding more copy.

This is what I have now, looking for review/feedback.

![save-the-date](https://cloud.githubusercontent.com/assets/197334/6971700/5f7b8534-d94c-11e4-909f-dcb16ed04924.png)

If this is good, we can land it today!!!

I have been bugging Jess getting feedback. I know it's fairly different than the original, but with the sign up form not being there, i felt too much info was scattered so I wanted to push to have it in one spot and still be clear.

**Comment by edrushka** [comment]
@ScottDowne and @iamjessklein - thanks for collaborating on a solution.

@Saallen should make the final call on this. However, she's gone for the day since she's on UK time, and tomorrow is a holiday for her, so let's just go ahead and land this. Sarah, please feel free to comment in this ticket if you're not happy with what we've done, and we'll try to rectify. Thanks.

**Comment by ScottDowne** [comment]
@edrushka yeah, it sounds reasonable to land it and if @Saallen has suggestions we can iterate :)

I'll bug the people I need to bug to land this, then update/close this ticket when that's done.

**Comment by iamjessklein** [comment]
:neckbeard: + :scissors: = :smile:

**Comment by ScottDowne** [comment]
It's done! http://2014.mozillafestival.org/

You might need to do a hard refresh if you get dark blue colour for the nov date bit.

:heart: :tangerine: :full_moon: :four_leaf_clover: :dolphin: :cherry_blossom:

**Comment by iamjessklein** [comment]
I don't mean to be a pain because it's up and it works - but I think that "Nov" should be changed to "November" :mag:

**Comment by edrushka** [comment]
Hurray! Thanks guys!! I will let @Saallen make the decision on Nov vs. November and close this ticket when she's ready. :cherry_blossom: + :tulip: + :rose: + :sunflower: + :hibiscus: + :leaves: = :bouquet:

**Comment by Saallen** [comment]
Looks awesome, so thanks all. Happy with the decisions to lose the separate red circle.
I am looking at the link on my mobile and you can see last years date on the page, above this year's dates, which is confusing. I cannot seem to attach a screen grab so will email you all the link. I think it should be November as we have never shortened the month before.  : :) :

**Comment by alicoding** [comment]
I agree it's confusing and we should remove that. I've tried to attach the
screenshot here using my phone, so let see how it goes...

**Comment by alicoding** [comment]
I agree it's confusing and we should remove that. I've tried to attach the
screenshot here using my phone, so let see how it goes... 


![](https://cloud.githubusercontent.com/assets/4368149/6982640/80aa97c2-d9e2-11e4-9849-ce17da56a7a4.png)

**Comment by ScottDowne** [comment]
I can easily change the header.

Do we want to update the date to 2015 or just remove it?

**Comment by iamjessklein** [comment]
@ScottDowne we should remove the outmoded copy (Oct 2014 etc.) and update the date to 2015.
Do we know if it will be at Ravensborne again?

**Comment by Saallen** [comment]
I agree with @iamjessklein: Yes to removing old date.
The venue is Ravensbourne once again but we might use additional venues this year.  Very much still in the early stages of planning though .

**Comment by ScottDowne** [comment]
@Saallen Date was updated but not removed. This was because it looked empty and misaligned, and changing the date was really quick and easy but removing it would require more work (which can still be done later)

**Comment by Saallen** [comment]
@ScottDowne Thanks for doing that, it looks great. On the desktop version now the date looks very faded above the Save the Date button- is this for any particular reason? 
![screen shot 2015-04-08 at 10 33 51](https://cloud.githubusercontent.com/assets/10194015/7042597/d9ed457c-ddda-11e4-993b-7e55f7c2bbc0.png)

**Comment by ScottDowne** [comment]
@Saallen The grey is some cache nonsense, because you recently loaded the old one and now the new.

Clearing cache or a hard refresh should drop the cache.

**Comment by Saallen** [comment]
This has worked- Awesome work everyone- thanks for the help. Closing ticket now

**Comment by iamjessklein** [comment]
:balloon:
