### ISSUE TITLE
Take down Studio Mofo site while keeping calendar

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#380]
Driver: @edrushka
Dev: tbd
CC: @mmmavis @sabrinang 

Now that Studio Mofo is no more, http://studiomofo.org/ shouldn't be live. 

@jdotpz  Should we keep the domain?

@HPaulJohnson and @KevZawacki still use the Engagement Calendar on the homepage. Can we move that somewhere else? Or, since it won't really be shared much, it can stay on the domain if the other content is removed.

**Comment by mmmavis** [comment]
FYI, here's the [repo](https://github.com/mozilla/studiomofo).

**Comment by mmmavis** [comment]
@jdotpz 
If I remember it correctly, the calendar is built entirely on front-end so I guess a `gh-pages` can work?

**Comment by edrushka** [comment]
@davidascher Would http://build.webmaker.org/ be a suitable home?

**Comment by edrushka** [comment]
@thisandagain says we can move this to build.webmaker.org! Next step, I think, is for @simonwex to assign a dev. She/he can connect with @KevZawacki who is maintaining the calendar.

**Comment by OpenMatt** [comment]
status?

**Comment by jdotpz** [comment]
I scaled it away about 11 days ago.  The infra is still there if we need to spin it up.

**Comment by edrushka** [comment]
Thanks, @jdotpz Closing this. @KevZawacki, let's file another ticket if you want the calendar live on build.webmaker.org.
