### ISSUE TITLE
Get design feedback on Open Web Fellows swag

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#382]
The Open Web Fellows program is about to launch. We need a bit of swag designed. Melissa has done some initial mockups. Some feedback from a designer would be great.

Driver: @Melechuga 
Designer: @iamjessklein 
Dev: Not needed
Decision maker: @Melechuga 

The swag needs to be ready by end of April.

**Comment by edrushka** [comment]
@Melechuga - I'm pasting @cassiemc's  suggestions for design review that she wrote in #374 

>Usually for design review, just pick someone and mention them in a comment for design review, so... "Design R? @cassiemc". If you're not sure who to pick, you can always tag me and I'll try to find someone if I'm not available.

>OR you can message the group in #mofodesign on IRC,

>OR you can join our weekly design crit on Wednesday afternoons. Though your time for feedback might be limited in that venue b/c there are 6 people's work to get through. Lots of options though!

**Comment by Melechuga** [comment]
Thanks @edrushka!
@iamjessklein: Any chance you have some time soon to look at some Advocacy swag mock-ups I put together? Would def appreciate any/all suggestions!

**Comment by iamjessklein** [comment]
Sure @Melechuga ! Can you direct me where to look?

**Comment by cassiemc** [comment]
Keeping @iamjessklein here since she's on it!

**Comment by iamjessklein** [comment]
Pinging @cassiemc as I am overbooked with my P1 and P2s

**Comment by cassiemc** [comment]
Cool thanks for the headsup Jess. Assigning @flukeout since he's the 'on-call' designer this heartbeat. @Melechuga / @edrushka Can you please ping us with a link to review?

**Comment by flukeout** [comment]
Hey @edrushka - let me know where to look and I'll get right on it!

**Comment by edrushka** [comment]
Awesome! Thanks, Luke. @Melechuga has the files.

**Comment by Melechuga** [comment]
Hey @flukeout  thanks! Just sent you an email with images. Let me know if I can provide any more details! M

**Comment by flukeout** [comment]
@Melechuga Replied - let's connect on Monday if you need any help with the suggestions I made.

**Comment by Melechuga** [comment]
@flukeout Fab; just pinged you with more questions. If it's more convenient to go through this on IRC or Skype, let me know. M

**Comment by Melechuga** [comment]
Hey @edrushka Just wondering if Studio MoFo has access to vector versions of Moz Advocacy logos, and if so, if you could please share them with @flukeout.  I see that we have stuff on the Mozilla Assets site (https://assets.mozillalabs.com/Brands-Logos/Mozilla%20Advocacy/) but they're restricted. Any idea what's there, and if we can make them accessible? Thanks.

**Comment by edrushka** [comment]
Hmmm. Those logos definitely shouldn't be restricted. I wonder if that error message is due to that assets page being transferred to the DAM (Digital Assets Management system). I tried searching for the Advocacy assets from the DAM here https://assets.mozilla.org/portal/assets/#category/16 but couldn't find anything. @sabrinang any idea where the logos are? I can contact someone from the DAM team if they are lost in the ether.

**Comment by sabrinang** [comment]
You can download logos here: http://people.mozilla.org/~smartell/advocacy/mozilla-advocacy_branding-assets.zip

Darn, I guess they haven't transferred everything to DAM yet. (Let me know if it doesn't work I have it backed up on the ol' studiomofo dropbox as well)

**Comment by OpenMatt** [comment]
status?

**Comment by flukeout** [comment]
@OpenMatt Working on this first thing today - hoping to close my work EOD

**Comment by Melechuga** [comment]
Thanks @flukeout for the newest logo designs! We should figure out a place where these can live for future use. Other than that, this issue is solved.

**Comment by edrushka** [comment]
FYI @sabrinang @flukeout here's how to add stuff to the DAM: https://mana.mozilla.org/wiki/display/EN/DAM+Employee+Guide
