### ISSUE TITLE
Design graphics for Learning Pathways whitepaper

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#383]
### RACI
Driver: @hannahkane
Design lead: @sabrinang 
Whitepaper project lead: @dajbelshaw 

See https://github.com/mozilla/teach.webmaker.org/issues/131

**Comment by cassiemc** [comment]
Assigning @sabrinang. It is a p2 but hopefully we can make some progress here.

@hannahkane are you driving this?

**Comment by hannahkane** [comment]
Thanks, @cassiemc. Added a RACI to the description. I can drive.

**Comment by dajbelshaw** [comment]
Great, thanks @cassiemc & @hannahkane. Meeting with @smithisgeneric and we'll talk graphics. :)

**Comment by hannahkane** [comment]
Closing this here since it's covered in the teach repo.
