### ISSUE TITLE
Recruit Regional Coordinators

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/plan#384]
Being tracked here: https://github.com/mozilla/teach.webmaker.org/issues/172

We need to recruit at least 5 Regional Coordinators (volunteer leadership positions) to support and onboard Web Club leaders in Q2. 

See more: http://mozilla.github.io/webmaker-curriculum/about/#success

### Audience
Staff organizers, future Web Club leaders, and by extension their learners 

### Success
5 amazing Regional Coordinators tapped and happily joining the team

### Vision
- [ ] A transparent selection process
- [ ] Qualitative interviews
- [ ] Group kick-off meeting scheduled

### Measurement
5 Regional Coordinators signed up

### Roles
 * Phase: Implementing
 * Driver: @thornet
 * Decision Maker: @thornet
 * Design Lead: N/A
 * Development Lead: N/A 
 * Quality Verifier: @chrislarry33

**Comment by ldecoursy** [comment]
Moving this to next milestone

**Comment by ldecoursy** [comment]
Made progress this heartbeat, identified target list and pitch. Recruiting kicks into gear next heartbeat.

**Comment by OpenMatt** [comment]
* Are we increasing this target from 5 to 10? 
* @thornet got any documentation on what Regional Co-ordinators are, or our theory of change / impact behind them? (helpful to explain to colleagues why we're making this a key goal this quarter)

**Comment by OpenMatt** [comment]
* Regional co-ordinators have a recruitment goal: 10 clubs each
* Tracking will be done manually to start (e.g., spreadsheets vs. databases to start)
* Need to feed these new requirements into updated roadmap

**Comment by thornet** [comment]
Update: 13 confirmed RCs. Anticipated total: 15

Kickoff call scheduled for May 5.
