### ISSUE TITLE
Update Web Journey illustration

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#387]
Continued from #89

**Goal**: Finish the Web Journey illustration (that @iamjessklein started in https://github.com/MozillaFoundation/research/issues/2#issuecomment-77642248) to replace the diagram in the India field report, and on build.webmaker.org/audience.

#### RACI
Phase: Research / Build / Ship
Owner: @secretrobotron 
Decision: @LauraReynal 
Lead design: @iamjessklein 
Lead dev: n/a
Quality: @thisandagain

**Comment by cassiemc** [comment]
@iamjessklein still assigned here since the work is started.

**Comment by secretrobotron** [comment]
Latest:
![](https://cloud.githubusercontent.com/assets/535012/6621655/39a612ba-c8ae-11e4-96c7-de201a441c2b.png)

**Comment by iamjessklein** [comment]
:+1: I was commenting on the old ticket. I will comment on here from now on.

**Comment by iamjessklein** [comment]
Based on the conversation with @LauraReynal here is a new iteration:

![journey2](https://cloud.githubusercontent.com/assets/535012/6710545/d97da43a-cd57-11e4-8655-53aa1f637112.PNG)

**Comment by LauraReynal** [comment]
Hey @iamjessklein I love the new direction ! thanks for working on it :smile: :cat: 
A few notes : 
- Title : The Web Journey 
- Replace "Aware" by "no use" 
- Move basic use further down, so it does not stand at the same level as those who dont use the web
- Remove the consumption 
- keep leverage and creation at the same level

**Comment by secretrobotron** [comment]
> Replace "Aware" by "no use"

How about "inexperienced" or something like that?

> Remove the consumption

Replace with something better?

**Comment by secretrobotron** [comment]
Hahaha also, @iamjessklein the *Aware* lady looks straight-up upset.

**Comment by LauraReynal** [comment]
Just did another call to check in with @iamjessklein 
We should have the final version today, including motivators. 

- The woman will look less upset 
- @secretrobotron Keeping "no use" as in the report - we describe it like this everywhere. 
- Consumption just goes out since its implied in leverage and described in the report anyway :) 
Its just going to be leverage and creation

**Comment by LauraReynal** [comment]
@iamjessklein could you make the final version on a white or transparent background ? It will be easier to insert it into the report this way. Thanks !

**Comment by LauraReynal** [comment]
Hey @iamjessklein here is the picture 
![webjourney sketch](https://cloud.githubusercontent.com/assets/8261945/6712535/f969bb44-cd84-11e4-857f-2bd62883a350.jpg)

**Comment by iamjessklein** [comment]
so much clearer :wink:

**Comment by iamjessklein** [comment]
Here you go - this has a transparent background. 

![webjourney-final](https://cloud.githubusercontent.com/assets/535012/6718019/ea0d799a-cd86-11e4-9a5e-c90e67623c07.png)


@LauraReynal @secretrobotron

**Comment by LauraReynal** [comment]
Tracking progress here : https://github.com/MozillaFoundation/research/issues/2
