### ISSUE TITLE
Complete Web Literacy Basics 1 Curriculum Repackaging

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#388]
RACI

* Driver - @LauraHilliger 
* Decision Maker - @thornet 
* Consulted - @ldecoursy
* Dev Lead - NA
* Design Lead - NA
* Quality Verifier - @chrislarry33 

Incorporating edits to first Clubs curriculum module - Web Literacy Basics 1
Includes six activities in three categories - reading, writing, participating on the web

Tracking work here: https://github.com/mozilla/teach.webmaker.org/labels/curriculum

**Comment by LauraHilliger** [comment]
[updated] meta ticket from the teach repo https://github.com/mozilla/teach.webmaker.org/issues/100
