### ISSUE TITLE
Content management solution for running promotions on webmaker.org

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#389]
Today, swapping in/out promotions on webmaker.org requires engineering support which is not only slower than it needs to be but also serves as a distraction from core engineering work. 

Marketing/engagement would like a solution where dedicated promotional space can be turned on/off easily and templatized content can be swapped in at "campaign" speed. 

### Audience
Visitors to webmaker.org and other target audiences for various engagement campaigns. 

### Success
The marketing/engagement team has the ability to quickly add, update or remove promtional content from webmaker.org without support from engineering. 

### Vision
Light-weight CMS, or "ad serving" platform, that marketing can access directly for promotional content. And/or a faster process for adding/removing contnet. 

### Measurement
The speed at which content can be added/removed. The frequency at which we are able to use webmaker.org to run promotional content. 

### Roles
 * Phase: 
 * Driver: 
 * Decision Maker: @HPaulJohnson
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by hannahkane** [comment]
Teach site will be making a similar request at some point. Don't want to slow down this process, but if this is a two birds / one stone type of scenario, I'd love to contribute requirements.

**Comment by thisandagain** [comment]
:+1:

**Comment by chrislarry33** [comment]
+1 @hannahkane

**Comment by davidascher** [comment]
Yes, good.

**Comment by edrushka** [comment]
Closing for now as we don't have H1 plans to run promos on Webmaker.org.
