### ISSUE TITLE
Miscellaneous Dev tasks for March 27 heartbeat

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#390]
**What is this?** During today's TPS call, we decided miscellaneous and small tasks should be consolidated into a single ticket to keep the Plan repo from getting clogged up. One dev will be assigned each heartbeat to address these smaller tasks

**How do I add my ticket?** Create your ticket in whatever repo it belongs in, and link to it as a comment in this ticket. If it's too big, Simon or I will reach out and ask you to file it in /plan

Driver: @edrushka
Dev: tbd
Quality: @simonwex

**Comment by edrushka** [comment]
Take down Studio Mofo site while keeping calendar #380

**Comment by thisandagain** [comment]
Fix search engine results w.r.t. localization https://github.com/mozilla/webmaker.org/issues/1157

**Comment by thisandagain** [comment]
Popcorn makes "disappearing" https://github.com/mozilla/popcorn.webmaker.org/issues/596

**Comment by edrushka** [comment]
Tweak 'Foundation Opportunity' dashboard in Salesforce https://github.com/MozillaFoundation/Engagement/issues/5

**Comment by secretrobotron** [comment]
What about triage? e.g. 308 open issues in https://github.com/mozilla-appmaker/appmaker/issues

**Comment by secretrobotron** [comment]
Goggles:
* [Can't Publish Goggles Make on Chromebook  ](https://github.com/mozilla/goggles.webmaker.org/issues/197)
* [Clicking on username in publish dialog breaks experience](https://github.com/mozilla/goggles.webmaker.org/issues/194)

**Comment by edrushka** [comment]
Agree: we'll likely need to triage if decide to roll with this idea.

**Comment by LucyeoH** [comment]
Reports of the key not working: https://github.com/mozilla/login.webmaker.org/issues/313

**Comment by LucyeoH** [comment]
Re-directing from defunct badge pages: https://github.com/mozilla/webmaker.org/issues/1326

**Comment by LucyeoH** [comment]
Goggles not working properly on IE: https://github.com/mozilla/goggles.webmaker.org/issues/199

**Comment by OpenMatt** [comment]
Update strategy link on build.webmaker.org https://github.com/mozilla/webmaker.org/issues/1382

**Comment by simonwex** [comment]
@LucyeoH there's ongoing work to replace the key system in login. It's working for me, so is not a complete system outage.

**Comment by simonwex** [comment]
@edrushka I think this group of issues is already too much for this milestone. -- mostly because we hadn't planned on this during prioritization and don't have a "full-time" person this HB. We need a better way of triaging issues across all of our projects to make good use of this ticket.

**Comment by edrushka** [comment]
Agree. The number of issues that have been added indicates that perhaps we're not triaging properly in our Monday calls. Should I close this ticket for now so people don't continue adding to it?

**Comment by cassiemc** [comment]
Would like to get this taken care of as soon as we can. @simonwex? https://github.com/MozillaFoundation/plan/issues/352 ( see also https://github.com/mozilla/webmaker.org/issues/1385) 

Is there a milestone we can add that issue to? What's the best process for this @OpenMatt @edrushka ?

**Comment by edrushka** [comment]
Placing this here until we sort out a different system for misc tasks https://github.com/MozillaFoundation/movement-building/issues/23

**Comment by OpenMatt** [comment]
Here's another misc ticket that would be *extremely* helpful to me this Heartbeat, as part of roadmapping work: https://github.com/mozilla/webmaker.org/issues/1391

**Comment by edrushka** [comment]
Closing this ticket, as this system is no longer in use.
