### ISSUE TITLE
Metrics : Extract quantitative data from exisiting research 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#391]
Goal : combine metrics from exisiting research for our future report with GSMA 

Phase: Research / Build / Ship

Team: @adamlofting @LauraReynal 
Consulted : @secretrobotron 
Lead design: n/a
Lead dev: n/a
Quality: @thisandagain

Tracking in  https://github.com/MozillaFoundation/research/issues/21

**Comment by secretrobotron** [comment]
@LauraReynal do you mind throwing in a "Goal" statement for context (or is it just that same as what's in https://github.com/MozillaFoundation/research/issues/21?)?

**Comment by LauraReynal** [comment]
Updated the initial ticket - but its the same as what's in MozillaFoundation/research#21

**Comment by thisandagain** [comment]
@LauraReynal Can you provide an update?

**Comment by LauraReynal** [comment]
India is complete 
Bangladesh is started but unfinished 
Kenya is 0% 
This will all be done by thursday - @adamlofting will be able to take over at that time

**Comment by OpenMatt** [comment]
@LauraReynal @adamlofting status?

**Comment by adamlofting** [comment]
We still need to back-fill the spreadsheets for Kenya and Bangladesh, but with Chicago research happening this week, I think this task will be pushed back a bit. 

@LauraReynal is Apr 24 realistic, or is Chicago going to be 100% of the time for the whole of this heartbeat?

**Comment by LauraReynal** [comment]
Updated to May 8th, Sorry Folks, really impossible to finish while in Chicago.

**Comment by LauraReynal** [comment]
Hey @adamlofting Although the previous research is incomplete to date. I have the Chicago data ready for you to analyze. I Added the document in our folder. It will be interesting to compare both Emerging and developed so feel free to start by Chicago

**Comment by jgmac1106** [comment]
Can't lie, little giddy to see what happens when you two get together to
play with numbers and ideas.

**Comment by OpenMatt** [comment]
@LauraReynal status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by LauraReynal** [comment]
Work in progress - its a P2 
Will sync with @adamlofting and post status update here.

**Comment by OpenMatt** [comment]
moving to next Heartbeat

**Comment by OpenMatt** [comment]
will become a higher priority in late June.
@thisandagain may close until then.
