### ISSUE TITLE
Dashboard active users KPI

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#392]
Our dashboard shows traffic, conversion and retention. Which rolls up into the number of active users. Active users (aka relationships) is the number we are reporting on in out joint MoCo reports so we should surface this on our dashboard too.

### Audience
1. Staff who care about these numbers
2. Community invested in the success of Webmaker

### Success
This number is included on our dashboard.

### Vision
I will add this to metrics.webmaker.org

### Roles
 * Phase: 
 * Driver: @adamlofting
 * Decision Maker: @thisandagain
 * Design Lead: n/a
 * Development Lead: @adamlofting
 * Quality Verifier:

**Comment by OpenMatt** [comment]
status?

**Comment by adamlofting** [comment]
Still open. Bumped to new heartbeat.

**Comment by adamlofting** [comment]
Note to self, that this data is currently visible in the MoFo KPIs under the people heading: http://build.webmaker.org/dashboards

**Comment by OpenMatt** [comment]
@adamlofting so this is done? Please close if so.

**Comment by adamlofting** [comment]
I think this is fine under the MoFo KPIs heading where it is right now. 
http://build.webmaker.org/dashboards
