### ISSUE TITLE
Socialize the new metrics.webmaker.org dashboards

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#394]
We have a selection of dashboards in use, and in development at https://metrics.webmaker.org - the people these dashboards were built for know they exist, but we should surface them more broadly for the rest of the team and integrate them more closely into build.webmaker.org

### Audience
1. Program owners and Managers
2. All staff working towards these KPIs
3. Interested staff and contributors

### Success
- [ ] Ensure people know they exist. 
- [x] Link to them from build.webmaker.org. 
- [x] Figure out which ones we can make public vs private (e.g. RIDs includes partner data). 
- [x] For future development, switch the default state to Open, unless there is a reason to keep something private.
- [x] check w. Program Managers (e.g, Lainie for Learning Networks, Drushka for Engagement, Andrew for Product) to ensure they're cool w. this data being public

### Vision
Adam to further tweak metrics.webmaker.org and build.webmaker.org to join these things up.

### Measurement
Dashboards will be accessible on build.w.o
Further comms around this (blog + email update to staff) once it's in a state that program managers are happy with

### Roles
 * Phase: 
 * Driver: @adamlofting
 * Decision Maker: @thisandagain @ldecoursy
 * Design Lead: n/a
 * Development Lead: @adamlofting 
 * Quality Verifier: @OpenMatt

**Comment by OpenMatt** [comment]
- this is some absolutely outstanding work from @adamlofting that I encourage everyone to take a look at. 
- @thisandagain @ldecoursy @edrushka  as Adam outlines above, right now https://metrics.webmaker.org is password-
protected. But we'd like to make as much of it as possible open by default.
- Can you have a look and flag anything that you think needs to be kept private?
- @adamlofting: right now, there's a mechanism for Learning Networks to manually update their metrics. I assume we'd just keep that behind password protection, and expose the rest, right? 
- cc @hannahkane: for ideas around dashboarding teach.mozilla.org metrics here eventually as well.

**Comment by OpenMatt** [comment]
@adamlofting : for updating the link on build.webmaker.org, is the proposal simply to replace the current "dashboards" link from https://mozillafoundation.geckoboard.com/dashboards/F62088172D822E2A to https://metrics.webmaker.org ?

**Comment by adamlofting** [comment]
Thanks @OpenMatt :smile: 

> for updating the link on build.webmaker.org, is the proposal simply to replace the current "dashboards" link from https://mozillafoundation.geckoboard.com/dashboards/F62088172D822E2A to https://metrics.webmaker.org ? 

I think there's some discussion to have here about whether we want a single MoFo dashboard with the KPIs for all teams together, and/or team specific views which dig into more detail. The existing dashboard is just for product metrics at the moment. There's a case for a really clean and crisp version for a cold audience to grasp quickly too. 

> right now, there's a mechanism for Learning Networks to manually update their metrics. I assume we'd just keep that behind password protection, and expose the rest, right? 

Yep, that will be simple enough to implement.

**Comment by OpenMatt** [comment]
Ok thanks Adam. I'd still advocate for just making a straight swap at this point. Then adding to / forking https://metrics.webmaker.org as we go. But let's see what others thing.

**Comment by hannahkane** [comment]
This is so great, @adamlofting. 

Re: the Learning Networks KPIs, I'm curious about how we will count Cities and People (see https://github.com/mozilla/teach.webmaker.org/issues/323 for a relevant conversation). 

I hope to get to a point where Hives and Clubs (as well as Maker Parties, and Groups - which is a new concept we're discussing) are automatically counted via the Teach site, with little need for manual additions.

We may eventually also want to add badges data to the dashboard.

**Comment by edrushka** [comment]
Wow...this is amazing!!! I never use emoji, but here, please accept this dromedary camel :dromedary_camel: and sweet potato :sweet_potato: as tokens of my admiration.

I like the idea the team-specific views, although if you want to add a single Mofo-wide metric that might be helpful for Mark and Ops.

I did not see anything that should remain private.

2 questions:
- I imagine once these dashboards are fully populated, they will be quite information-dense. Would it be possible to use a colour coding system (green = 100%, yellow = within 80% of goal, red >79%) to see problem areas at a glance?
- Why are we including only opt-ins and not opt-outs for email metrics?

**Comment by OpenMatt** [comment]
These are all good questions -- but also: let's not increase the scope here or inundate poor Adam with too much complexity... :) We're mostly just trying to ship what already exists. This is version 1.

**Comment by OpenMatt** [comment]
* Hannah: thanks for referencing that ticket. I believe the questions you raise around how to data for the cities KPI will be one of the questions for discussion in the Learning Networks program review.

**Comment by adamlofting** [comment]
@edrushka that's a good combination of emjoji and ideas :panda_face: I've filed the color coding as a future enhancement here: https://github.com/mozilla/webmaker-metrics/issues/26

@hannahkane we've talked this through since, but I think we're on the same page with this. The teach site will automate most of this. :bear: 

:smile:

**Comment by hannahkane** [comment]
:rabbit: :hatching_chick: :tulip:

**Comment by adamlofting** [comment]
* These are now public by default at https://metrics.webmaker.org/dashboards
* I've added a [MoFo report](https://metrics.webmaker.org/dashboard/mofo-kpis) with Cities and People to match https://wiki.mozilla.org/Foundation/2015/Q1
* The only restricted report is the RIDs report. Though there's no data visible currently, this includes traffic from partner sites which they might prefer us not to share.

I'll look at adding this into build.w.o next

**Comment by chrislarry33** [comment]
Whoa, thanks so much @adamlofting !!!! Really feeling the progress here in how the thinking and tools are progressing. Please know that while I am not in all the meetings I am in constant dialogue with my team, following these tickets and excited about the progress.

**Comment by adamlofting** [comment]
This will be embedded in build.webmaker.org soon. 

There is a Pull Request open that just needs a review: https://github.com/mozilla/build.webmaker.org/pull/68

**Comment by OpenMatt** [comment]
status?

**Comment by adamlofting** [comment]
This got merged and is live on build.w.o. I think we can close this. :smile: 
Promoting this will be an ongoing effort.
