### ISSUE TITLE
Figure out how to effectively measure and dashboard our "cities" KPI

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#395]
Our primary KPI for Learning Networks Team is "number of cities". But we don't currently have a way to measure this in a simple and automated fashion. Being able to measure this is an important step in being able to manage/grow this number over the course of the year. 

### Audience
1. Learning Networks Team
2. Ops and Board and MoCo Reporting
3. MoFo staff and Contributors

### Success
Learning Networks Program and Product roadmaps aligned around this topic in a way that gives us the numbers we need to understand and manage the growth of the program.

### Vision
A clear plan documenting:

* what data we need to collect
* where this will be stored
* theory on how volunteers can manage this data themselves in a way that gives them value (the 'virtuous cycle of participation')
* an emphasis on relationship building over simple logging for the sake of counting
* how this data will be analysed / exposed for inclusion in public dashboards

### Measurement
Agreement on the plan.

### Roles
 * Phase: 
 * Driver: @adamlofting
 * Decision Maker: @ldecoursy @hannahkane 
 * Design Lead: n/a
 * Development Lead: n/a
 * Quality Verifier: @chrislarry33

**Comment by adamlofting** [comment]
@ldecoursy @hannahkane @thornet and I just started this conversation on a call today. But we will dig into these questions and the details in the next heartbeat

**Comment by chrislarry33** [comment]
Thanks Adam, big help. We really want to get better at this and do it right.

**Comment by thornet** [comment]
Continuing to refine with @ldecoursy @adamlofting @hannahkane @chrislarry33 

https://teach.etherpad.mozilla.org/metrics

Current definition of what it mean to be "active in a city." At least ONE of the following: 

* Hive - networked activity driving towards innovation, collaboration and the adoption of connected learning practices/principles
* Clubs - facilitating clubs/programs that teach web and digital skills
* Events - regular meet-ups/workshops/convenings, Maker Party, Hive Pop-Up 
* Groups - affinity groups aligned by location or interest area

Next: discussing with Salesforce Cloud peeps what our CRM needs are to see if their tools helps track.

**Comment by adamlofting** [comment]
See also:  Spec out phase 1 of the Learning Networks Directory project #407

**Comment by adamlofting** [comment]
Just an update that I haven't started on this yet. 
I hope to on Tues, and will book in a check-in call for later next week.

**Comment by adamlofting** [comment]
After saying that, I had some time to take a pass at this this afternoon.

This is how I propose we count 'being active in a city':
* https://etherpad.mozilla.org/how-to-count-cities

@thornet @ldecoursy @hannahkane @chrislarry33 - please comment / edit / push-back or +1 on the etherpad, or in this issue.

I think the two biggest points to debate are:

1. Do we want a current active total (I've suggested this is on a rolling 90 day basis), or a total count of who were active anytime in 2015 even if they lapse before the end of the year. 
  * The first is harder to hit for a big EOY total, but probably a better indicator of 'how well are we doing right now'.
2. Is there anything to count for Group activity other than events and meetups?

**Comment by hannahkane** [comment]
This seems very sane. I added some comments to the etherpad, including some about how to measure Group activity.

Re: the rolling vs total, I would think the total count throughout the year would be what we'd measure for the KPI. But they're not mutually exclusive, right? I'd like to also have the "currently active" count displayed on the dashboard.

**Comment by adamlofting** [comment]
Thanks @hannahkane and whoever responded in the blue text in the Etherpad. I've added some replies and this looks like it's coming together now.

---

The other question open now is *how much activity is required to be active?*. I'm happy to model this on the 'once a quarter' = active level that has been mentioned. But we need to factor in `sustained` as well as `active`. Which would look more like: 

* Three or more activities in a city = active
* At least one of which in the last 90 days = currently active

**Comment by adamlofting** [comment]
> Re: the rolling vs total, I would think the total count throughout the year would be what we'd measure for the KPI. But they're not mutually exclusive, right? I'd like to also have the "currently active" count displayed on the dashboard.

Yes, that's a good point, and sounds like a sensible option.

**Comment by ldecoursy** [comment]
That was me in blue, sorry ;) I know @chrislarry33 was also planning to weigh in on this...

**Comment by adamlofting** [comment]
I've combined the feedback so far and come up with this: https://etherpad.mozilla.org/how-to-count-cities

Which I think is getting close...

#### How the Learning Networks Team Defines, Counts and Reports on:
## 'Number of Active Cities'

**'Active'**
In 2015, we want Mozilla Learning Networks to be 'Active' in 500 cities, on a sustained basis. A city is counted as 'Active' if three or more 'Activities' take place on three separate dates in 2015. 

**'Currently Active'**
To focus our efforts on long-term retention, we will also report on the number of 'Currently Active' cities. A city is 'Currently Active' if three or more 'Activities' have taken place, at least one of which was in the last 90 days. 

**'Activities'**
Several types of 'Activity' can count towards the 'Active' definitions above, but they are similar for all happening at a specific time and place. Any combination (of three or more of these) can add up to make a city count as 'Active':
* A maker party (mostly one-off, but there can be more than one per city)
* A group meetup (hopefully recurring by nature)
* A club event (recurring by design, but perhaps timebound)
 * Club sub-activities that indicate it is active (e.g. issuing new badges every few days)

Some of these activities will be identifiable in an events database, or via clubs tools, and some will be self-reported (with strong tooling and encouragement in our teach.mozilla.org product design).

**'Hive Cities'**
A city will also be counted as 'Active' if it is a 'Hive City'. These will by definition be running more than three 'Activities' on a regular basis. We will report on number of 'Hive Cities' as a distinct KPI alongside the 'Active' cities.

**Why 'Active Cities' is a good metric**
* It encourages breadth and diversity of the Learning Network via geographic distribution
* It measures a level of engagement beyond 'flash in the pan' by requiring a minimum number of activities

**Limitations of the 'Active Cities' metric**

* Cities are not equal, and three events in a small city versus a capital city are not equivalent
  * This can be managed by also reporting on total number of clubs, groups and events regardless of location
* Three unrelated un-sustained events in a city counts as active
  * Making this measure more complex would make the overarching goal more complex relative to the usefulness.
* We could hit our 2015 target with 500 cities in the summer who all lapse into an inactive state by the end of the year.
  * Reporting on 'Currently Active' helps to counteract this.

**Suggested todos:**

Set specific targets for:
- [ ] Number of 'Currently Active' Cities at the end of 2015
- [ ] Number of 'Active Clubs' 2015 total
- [ ] Number of 'Currently Active' Clubs at the end of 2015

**Comment by hannahkane** [comment]
@adamlofting - this is fantastic and very clear. I also appreciate that it provides some very useful directives for the site roadmap (e.g. adding the concept of a group meetup; allowing Clubs to award badges to their members).

**Comment by OpenMatt** [comment]
@adamlofting +1 this is great -- could you publish as a blog post for easier reference? I'd like to share this with Ops, other program managers, etc.

**Comment by adamlofting** [comment]
This needs @chrislarry33 sign-off once back from PTO, but then absolutely yes.

**Comment by hannahkane** [comment]
Should we move this to the current milestone?

**Comment by adamlofting** [comment]
@chrislarry33 any last minute thoughts? If not I'll write this up in a blog post somewhere easier for @OpenMatt to reference.
