### ISSUE TITLE
Play game of tic-tac-toe

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#396]

**Comment by simonwex** [comment]
| :x: | :white_large_square:  | :white_large_square:  |
|---|---|---|
| :white_large_square: | :white_large_square: | :white_large_square: |
| :white_large_square: | :white_large_square: | :white_large_square: |

**Comment by secretrobotron** [comment]
| :x: | :white_large_square:  | :white_large_square:  |
|---|---|---|
| :white_large_square: | :white_large_square: | :white_large_square: |
| :whale: | :white_large_square: | :white_large_square: |

**Comment by simonwex** [comment]
| :camel:  | :white_large_square:  | :camel: |
|---|---|---|
| :white_large_square: | :white_large_square: | :white_large_square: |
| :whale: | :white_large_square: | :white_large_square: |

**Comment by secretrobotron** [comment]
| :camel:  | :facepunch:  | :camel: |
|---|---|---|
| :white_large_square: | :white_large_square: | :white_large_square: |
| :whale2: : | :white_large_square: | :white_large_square: |

**Comment by simonwex** [comment]
| :camel:  | :facepunch:  | :camel: |
|---|---|---|
| :white_large_square: | :white_large_square: | :white_large_square:  |
| :whale2: : | :white_large_square: | :camel: |

**Comment by secretrobotron** [comment]
| :camel:  | :whale2:  | :camel: |
|---|---|---|
| :white_large_square: | :white_large_square: | :facepunch:  |
| :whale2: : | :white_large_square: | :camel: |

**Comment by secretrobotron** [comment]
:(

**Comment by simonwex** [comment]
:shipit:
