### ISSUE TITLE
Figure this out

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#397]
`_  ___'_   _______   _   ____   ____   ___   __   ___ - ___ - ___`

TRIES: 12

**Comment by secretrobotron** [comment]
github is bad at hangman

**Comment by simonwex** [comment]
I was just about to say...

is it `_   ___'_   _______   _   ____   ____   ___   __   ___ - ___ - ___`?

**Comment by simonwex** [comment]
`"i"`

**Comment by secretrobotron** [comment]
:eyes: `___'_`   `___I___` :eyes:    `____ ____ ___ __   _I_ - ___ - ___`

**Comment by LauraHilliger** [comment]
"n"

**Comment by davidascher** [comment]
Always start with E.

E?

**Comment by LauraHilliger** [comment]
@secretrobotron this is a P1! I can't imagine there is neither e nor n!

Next letter is "a"

**Comment by LauraReynal** [comment]
N ?

**Comment by simonwex** [comment]
This issue needs a driver.

**Comment by secretrobotron** [comment]
Actually, it needs to be rescoped.

I discovered a [wheel-of-fortune spinner](http://wheeldecide.com/wheel-fortune-spinner/) which will increase the whimsy here.

**Comment by OpenMatt** [comment]
can we close? :)
