### ISSUE TITLE
[OPS] Media Release form creation

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#398]
Please advise if I should be filing this in Bugzilla?

We need a simple media release for for Clubs organizers to download and print. Conversation started here:

https://github.com/mozilla/teach.webmaker.org/issues/313

Maybe something like this already exists from legal?

**Comment by ldecoursy** [comment]
@edrushka Do you happen to know best way to find out?

**Comment by davidascher** [comment]
I'd file a bugzilla bug under Legal.

**Comment by edrushka** [comment]
And / or search closed tickets on Bugzilla.

**Comment by LauraHilliger** [comment]
see: https://github.com/mozilla/teach.webmaker.org/issues/313
