### ISSUE TITLE
Update advocacy site with NN win graphic

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#399]
This ticket https://github.com/MozillaFoundation/movement-building/issues/18 got stalled with the Advocacy team and was languishing in /movement-building. Needs a tiny bit of design (tweaking Jess' design) and then the build.

Driver: @edrushka
Dev: 
Design: @flukeout 
Decision-maker: @valianttry
Consulted: @HPaulJohnson @DaveSteer @melechuga

**Comment by edrushka** [comment]
### To Do:
Based off this redpen https://redpen.io/mj6366fbe60426efd6 please do the following:
1) change background to white
2) if the building needs a background coloured square, that's fine. Try to minimize the red/white/blue American vibe as much as possible.
3) Remove the Read More button. That should be a hyperlinked 'Read more' line of text at the end of the the paragraph.
4) Overall, this banner should take up less space vertically. Removing the Read More button should solve for that.
5) Align the buttons in the Take Action section.

**Comment by flukeout** [comment]
@edrushka Do you know where I can get the source files to make the changes?

**Comment by edrushka** [comment]
@iamjessklein should have them

**Comment by flukeout** [comment]
Okay - I pinged Jess for the files, stay tuned!

**Comment by flukeout** [comment]
@iamjessklein I got your link with source files, but don't see anything that matches the graphic in the redpen link posted by @edrushka -> https://redpen.io/mj6366fbe60426efd6

Do you have source files for this specific redpen image. Is this a screencap of a site that already exists?

These are the Net Neutrality source files I have, but don't see that specific banner in there: https://www.dropbox.com/sh/5j9bun6w066sz6m/AAAvT7mFZ2jHv1MkJmVxMVeaa?dl=0

Help plz!

**Comment by flukeout** [comment]
@edrushka You asked to...

```5) Align the buttons in the Take Action section.```

In the redpen image I don't see any buttons in the Take Action section, it cuts off right below the title. I feel like I'm missing something. Here. Hit me up on IRC or Vidyo.

**Comment by edrushka** [comment]
https://www.dropbox.com/s/47tkyhsdzgc5wzr/Screenshot%202015-03-25%2015.41.16.png?dl=0

**Comment by Melechuga** [comment]
@flukeout Link to download the MozAdv assets (same link as on the other issue): http://people.mozilla.org/~smartell/advocacy/mozilla-advocacy_branding-assets.zip

**Comment by flukeout** [comment]
@edrushka https://redpen.io/rocd1eddab94645c2a

**Comment by edrushka** [comment]
Nice! This looks good to me. Only change would be a period after the Read more. @valianttry can you please sign off so we can move to the build?

**Comment by valianttry** [comment]
@edrushka This redpen is approved (by @DaveSteer as well), as long as the "take action" buttons are also aligned (that section was cutoff in the redpen image).

**Comment by OpenMatt** [comment]
Status update on this one?

**Comment by edrushka** [comment]
@flukeout has done the design and is hoping to implement today.

**Comment by flukeout** [comment]
@edrushka @OpenMatt I'm having trouble setting up the dev environment for this locally and don't think I'll be able to get the work done today. Trying again tomorrow morning.

**Comment by valianttry** [comment]
@flukeout -- @ScottDowne might be able to help with dev enviro Qs

**Comment by flukeout** [comment]
I think I managed it, thank you!

**Comment by flukeout** [comment]
PR is waiting for review now - https://github.com/mozilla/advocacy.mozilla.org/pull/10 
When it gets merged, I'll make the corresponding content changes via the Wordpress CMS

**Comment by flukeout** [comment]
Published new graphic and content and aligned the buttons - https://advocacy.mozilla.org/

@edrushka Please look over and close if all is good.

**Comment by edrushka** [comment]
Awesome. Thanks @flukeout 

One question: is the font lighter in that banner than in the 'Take Action Now' banner below? It looks that way on my screen on both FF and Chrome. https://www.dropbox.com/s/nhcdvhtghzt122j/Screenshot%202015-04-02%2010.49.20.png?dl=0 --> hard to tell in this screenshot.

**Comment by flukeout** [comment]
@edrushka - it's actually the same color, the bottom may look darker because of the slight white highlighting on the bottom of the text. I can adjust the copy on the white banner to be a little darker.

Previously, the header text in the white area was bold - so changing it maybe have added to that effect.

**Comment by edrushka** [comment]
Ah interesting - thanks for explaining. I'm fine with leaving as is. @valianttry can you take a look and close this ticket if you're happy with the site?
