### ISSUE TITLE
[OPS] Delete Asana workspaces and accounts

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#400]
Adam's recent email reminded me to clean up my data trail across the web, and today I found our old Asana workspaces and deactivated, then permanently deleted my data from their service. Might be a good idea for Mofo to delete the Foundation workspace, as well as user data (which includes stuff from late 2012 & 2013)

Whomever set that up must have access (perhaps @OpenMatt ?), otherwise, I can reach out to Asana and ask them to delete Mozilla Foundation data.

**Comment by davidascher** [comment]
I think that's on me.

**Comment by OpenMatt** [comment]
status?

**Comment by davidascher** [comment]
Done, I believe.
