### ISSUE TITLE
Conduct usability and qualitative tests on v1 of teach site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#401]
### RACI ###
Driver: @hannahkane
Responsible: @hannahkane and @iamjessklein 
Consulted: @adamlofting 

Once the site is on production, we plan to conduct two kinds of tests:

1) Usability tests with a small handful of Club leaders.

2) Collect general impressions from a random sample of users via usertesting.com

The plan is outlined here: https://docs.google.com/a/mozillafoundation.org/document/d/11TZH_HBmCo4D9MaYcAW-eHz4cXRVnAxfap0rRBa4O0s/edit#

**Comment by iamjessklein** [comment]
It would be nice to test with internal staff from the Teach team, so that they can possibly go on to lead their own user tests with their constituents. :bulb:

**Comment by hannahkane** [comment]
I have two usability tests scheduled, and @iamjessklein is following up on another possible user tester.

**Comment by iamjessklein** [comment]
Yes I am.

**Comment by hannahkane** [comment]
Closing this because we've done some (see http://hannahgrams.com/2015/04/10/user-testing-the-teach-site/). We'll continue to do more next heartbeat and beyond, but I don't think we need to track with tickets.
