### ISSUE TITLE
Check Discourse install for S3 image uploading

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#402]
Discourse is deprecating support for storing uploaded images on S3:
https://meta.discourse.org/t/warning-amazon-s3-is-deprecated-in-1-3-for-image-attachment-storage/26594

Dirk sent me a note, but I'm not sure if that was how we setup our discourse forum, so I'm hoping someone can check.

cc @jdotpz

**Comment by cassiemc** [comment]
Super old, so closing.

**Comment by jdotpz** [comment]
![chrsgiphy](https://cloud.githubusercontent.com/assets/1373628/11963960/ee6ef31a-a8af-11e5-8783-b8b3606bff98.gif)
It was the best of times....
