### ISSUE TITLE
Ship new login system on teach.mozilla.org

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#404]
Continuation from #53 to ship on teach.mozilla.org.

Todos:
- [x] Design QA
- [x] Copy QA
- [x] Functionality QA
- [x] Test coverage
- [x] Staging
- [x] Prod

Milestone:
https://github.com/mozilla/id.webmaker.org/milestones/Teach%20QA%20and%20Launch

### RACI
Phase: QA / Ship
Owner: @secretrobotron
Decision: @davidascher 
Lead design: @cassiemc
Lead dev: @jbuck
Dev: @cadecairos
Quality: @simonwex 
Metrics: @adamlofting

**Comment by adamlofting** [comment]
- [ ] Metrics QA

**Comment by cassiemc** [comment]
@secretrobotron where are these tasks being tracked?

**Comment by secretrobotron** [comment]
@cassiemc in the QA milestone. I'll put it in the description.

**Comment by simonwex** [comment]
How has no one made a "Not Found" joke in this ticket yet?

**Comment by OpenMatt** [comment]
@secretrobotron : status?

**Comment by secretrobotron** [comment]
Made substantial progress last heartbeat, but still have quite a few more things to cover: https://github.com/mozilla/id.webmaker.org/issues?q=is%3Aissue+milestone%3A%22Teach+QA+and+Launch%22+is%3Aopen

Nothing is at 0%, but many bugs, QA and finishing touches.

**Comment by davidascher** [comment]
What's the new target ship date?  We're 2 weeks late already.

**Comment by OpenMatt** [comment]
@simonwex and @davidascher will make a plan and update this ticket.

**Comment by secretrobotron** [comment]
staging: id.mofostaging.net
prod: id.webmaker.org
use from teach.mofostaging.net and teach.mozilla.org
