### ISSUE TITLE
Prototype new Webmaker navigation and "tiles" feature

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#405]
#### Goals
- Prototype new features on desktop and mobile
- Prepare user tests for @LauraReynal's Chicago research trip
- Produce documentation and architectural diagrams for the next phase of work. Need to make a few decisions regarding the tech stack:
    - Services
        - Publishing
        - Discovery
        - DB (Firebase?)
        - Offline
    - Application
        - Android strategy
        - Analytics
        - Gestures

#### Needs
- Clarify research goals
- Update paper prototype to reflect the tiles paradigm
- Prepare desktop prototype [@flukeout's desk8](flukeout.com/examples/desk8/) 
- Prepare mobile app

### Details
- [Desktop milestone](https://github.com/mozilla/webmaker-desktop/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Chicago+Research%22)
- [Mobile milestone](https://github.com/mozilla/webmaker-app/milestones/Prototypes)

#### RACI
Phase: Build / Ship
Driver: @secretrobotron, @xmatthewx
Decision:  @thisandagain
Design: @flukeout @vazquez 
Dev: @gvn
Dev: @Pomax
Dev: @k88hudson 
Quality: @LauraReynal
Metrics: @adamlofting

**Comment by xmatthewx** [comment]
Related mobile milestone https://github.com/mozilla/webmaker-app/milestones/Prototypes

**Comment by OpenMatt** [comment]
Can someone add a link or mock-up here to help explain what this is to people who are unfamiliar?

**Comment by xmatthewx** [comment]
Recap posted to previous planning ticket #377

**Comment by simonwex** [comment]
@secretrobotron what are the needs for the database?

**Comment by simonwex** [comment]
@secretrobotron could you include @jbuck on the talks around the publishing service?

**Comment by secretrobotron** [comment]
@simonwex :+1: will do

**Comment by xmatthewx** [comment]
@OpenMatt - The goal is to iterate on the existing mobile app and the [desk8](https://github.com/MozillaFoundation/plan/issues/flukeout.com/examples/desk8/) prototype to create a unified Webmaker experience across devices. Best summarized by these mockups for [desktop](https://cloud.githubusercontent.com/assets/53411/6904604/055f3f68-d6f0-11e4-95c8-af49942c564f.png) and [mobile](https://cloud.githubusercontent.com/assets/53411/6904646/658864c8-d6f0-11e4-888a-69db73869004.png).

**Comment by simonwex** [comment]
The work being done here will be in React and the components will see use in both the real Webmaker 2.0 and Webmaker app. We won't be further iterating on Luke's prototype code as this needs to work on more than Chrome and it's time to start building "for real".

It's my assumption that things like code test coverage and standard development practices are to be followed here.

This likely raises some questions about the tech stack of the app, but this team is stacked with the people to solve those problems.

@thisandagain, does this still sound right to you based on our conversations last week?

**Comment by xmatthewx** [comment]
@simonwex - There's definitely no need to retain any code from the desktop prototype. We will iterate on the experience while setting the stage for real things to follow.

**Comment by thisandagain** [comment]
Yup! Right on @simonwex . We'll start the process for making some decisions on the tech stack tomorrow during kickoff. :+1:

**Comment by OpenMatt** [comment]
@secretrobotron @xmatthewx : status update?

**Comment by xmatthewx** [comment]
Heartbeat was largely a success. 

 - Engineers made good progress on setting up hybrid Android app, scaffolding many of the core features. 
 - Designers built two prototypes on UI (http://marvl.in/ee2f0e) and UX (http://flukeout.com/examples/tiles-nav-3/)

Work toward Alpha release will continue in #429.
