### ISSUE TITLE
Discuss CRM opportunities with MoFos

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#406]
MoCo is currently investigating the broad adoption of a CRM. Let's discuss how the Foundation can be a part of this: what's the vision, what's possible, what are the steps and how you can help.

Andrea and I are currently planning a series of brownbags. Please stay tuned for more.

drivers: @edrushka and @valianttry

**Comment by davidascher** [comment]
Drivers also include @adamlofting, because of the across-the-org data
impact.

**Comment by OpenMatt** [comment]
cc @ldecoursy @chrislarry33

**Comment by OpenMatt** [comment]
@davidascher had a useful way of scoping and dividing up this CRM work. Three categories:

1) partner data. (e.g., leads, etc.)
2) email management. (e.g., BSD migration) 
3) product and learning networks requirements (e.g., integration w. teach.moz.org and webmaker.org)

**Comment by valianttry** [comment]
@OpenMatt #2 would be better described as "digital supporter engagement" since it encompasses fundraising, forms, etc in addition to email. But this makes sense otherwise. There are entanglements / integrations x all 3, so we should be careful not to silo these 3 areas (that's the opposite of what we're trying to do with a CRM / shared source of truth).

**Comment by edrushka** [comment]
@OpenMatt I'm actually going to change the title back closer to the original. What Andrea and I are trying to accomplish here is socializing the technology. I received feedback last week that indicated people feel "pushed" into adopting this technology. We'd like to take a step back, present some of the opportunities a CRM can help us take advantage of, and have this be a more open discussion. Documentation can be a part of that, but this effort isn't about assigning owners and getting down to integration; We're not there yet.

**Comment by edrushka** [comment]
Moving this to the CRM repo: https://github.com/MozillaFoundation/mofo-crm/issues/11
