### ISSUE TITLE
Cred.ly badges proposal

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#408]
### RACI ###
Drivers: @hannahkane and @simonwex 
Consulted: @davidascher and @chrislarry33 

Draft started here: https://docs.google.com/a/mozillafoundation.org/document/d/1dw1Do5tVdgLd4NahIHj6xqS0CX093eIDcjQP6TrrdQs/edit#

**Comment by simonwex** [comment]
Meeting with Credly Monday at 1:00pm PDT.

**Comment by simonwex** [comment]
Meeting was rescheduled over the weekend for 8:00am today. It went well, I'm waiting on answers for two outstanding questions related to regional hosting and then I'll summarize here. Pricing is roughly per-user (earner). What are we expecting for numbers there?

**Comment by hannahkane** [comment]
cc @chrislarry33 to help answer the question about numbers of badge earners.

**Comment by hannahkane** [comment]
Moving this to April 24th, since we didn't do this. @simonwex, I believe there are a couple things for you to fill in on the proposal before we share it with Ops.

**Comment by OpenMatt** [comment]
@simonwex I believe the outstanding items are things like: "what will cred.ly cost?"

**Comment by simonwex** [comment]
Updated costs in doc.

**Comment by OpenMatt** [comment]
* Next steps on this: discuss the document with @chrislarry33. 
https://docs.google.com/a/mozillafoundation.org/document/d/1dw1Do5tVdgLd4NahIHj6xqS0CX093eIDcjQP6TrrdQs/edit#

* Hannah: will start thinking about implementation & resourcing. (e.g., contractor?)

**Comment by hannahkane** [comment]
Assigning this to @simonwex who is handling the negotiations.

**Comment by OpenMatt** [comment]
* I believe next step on this is @simonwex meeting w. MoFo Finance team.

**Comment by simonwex** [comment]
Correct. Also, Credly is working on the questionnaire for the vendor review process.

**Comment by simonwex** [comment]
Met with Pamela today. I'm going to file a legal bug and we'll be off to the races.

**Comment by simonwex** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1159064

**Comment by OpenMatt** [comment]
@hannahkane @simonwex I understand there's a new blocker here. what's the best way to update this ticket?

**Comment by simonwex** [comment]
Credly has finished their vendor questionnaire, we're now ready to kick off the vendor security review. Closing this ticket, work will continue here: #461
