### ISSUE TITLE
Value Prop Testing w/ Adwords and Facebook, Phase II

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#409]
With initial Adwords campaign setup for value proposition messaging tests, we want to expand number of message variations we are testing, add in Facebook ads and complete initial analysis. 

### Audience
Potential audiences for the new Webmaker product. 

### Success
Directional insights on versions of messaging that will be most compelling to support the go to market for Webmaker. 

### Vision
We will be running expanded adwords tests and setting up Facebook ads to do more demographic and localized targeting. 

### Measurement
Clicks and conversions on existing Webmaker.org

### Roles
* Phase: II
* Driver: @HPaulJohnson
* Consulted: @adamlofting @KevZawacki 
* Informed: @thisandagain @xmatthewx @xmatthewx

**Comment by HPaulJohnson** [comment]
* re-assess Adwords results on Monday, 3/30 and adjust approach if impressions have not increased
* develop 2 additional tests for "learners vs. makers" and "fun vs. utilitarian" 
* expand testing into FB
* discuss using dedicated landing page for ongoing testing to 1) improve Google quality scores and 2) to set appropriate expectations and capture interest in future Webmaker product/features. 

See Adam's background doc for reference on campaign: https://docs.google.com/a/mozillafoundation.org/document/d/16WT50NzQziOjunUPZhS-oIaVNVJgVNhifzQsCZihJxs/edit#heading=h.xiatjpx1ptib

**Comment by adamlofting** [comment]
Copying these notes from @HPaulJohnson's email so it's easier to track:

2 new Google Adword variations

* "Learn" or "Make"
* "Fun" or "Utilitarian"
* Current test of "maker" language is using 10 ad variations so we can use that for guidance. Let's create up to 10 versions for each of the above that cover the full spectrum of things we want to learn.

Facebook Ad
* Let's get this setup with variations on the Adword test that is up and running (testing "maker" language). We'll fold in other variations once setup is verified.
* Image specs: 1200 x 628 pixels
* Images for initial Mozilla and/or Webmaker logos
* Could test Moz vs. WM logo now or later
* Could do additional image testing later (ex. people using the app)
* Headline is 25 chars max
* Text is 90 chars max

**Comment by adamlofting** [comment]
/cc @KevZawacki for this ticket.

Plus, some more notes from me:

* The goal of the ~10 variations is to avoid hidden subtleties in one particular ad or another that make it work, or not. So, if we have 5 quite different 'fun' variations, and 4 of them outperform 5 quite different 'utilitarian' variations, then it's a strong sign that the broader concept is what drove the results.  
* For Facebook images, we could also test the prototype / concept visuals of the UI as it currently stands
* For branding tests (Moz vs. WM etc, we can segment against existing Mozilla and/or Firefox fans to understand the difference).

**Comment by KevZawacki** [comment]
Suggested AdWord variations for LEARN vs MAKE and FUN vs UTILITARIAN are here: https://foundation.etherpad.mozilla.org/adwords

**Comment by HPaulJohnson** [comment]
Thanks, @KevZawacki, I made some tweaks and added a few variations based on our conversation today.

@adamlofting, I think we are ready to load up round 2, "learn" vs. "make" (line 33-97) and "fun" vs. "utilitarian" (line 100-179). If there are too many variations for each theme feel free to cut those you think are the least interesting.

**Comment by thisandagain** [comment]
@KevZawacki can you make that pad public?

**Comment by adamlofting** [comment]
I've setup:

* Market Testing 2: Learn vs Make
* Market Testing 3: Fun vs Utilitarian

Most of the headlines were a bit too long so I've trimmed them down. Sometimes this made them less catchy, but I kept the focus on the elements of each test. 

You can see those made it into the test in the Google Doc: https://docs.google.com/a/mozillafoundation.org/document/d/16WT50NzQziOjunUPZhS-oIaVNVJgVNhifzQsCZihJxs/edit#

**Comment by KevZawacki** [comment]
@thisandagain Sure -- pad is now public

**Comment by adamlofting** [comment]
I dropped some AdWords screenshots into the working doc:
https://docs.google.com/a/mozillafoundation.org/document/d/16WT50NzQziOjunUPZhS-oIaVNVJgVNhifzQsCZihJxs/edit#heading=h.xiatjpx1ptib

Things we see so far:

* Including the word “Maker” significantly reduces the impressions, and therefore total clicks versus equivalent ads that don’t use the word “Maker”.
* The ads that used the word ‘App’ outperformed those that used the word ‘Website’. The Generic ‘Maker and Webmaker’ ads failed.

The other tests don't have much data yet, but there seems to be a slight bias towards Learning rather than Making, and Fun rather than Utility. But that's more an indication of existing search intent.

**Comment by thisandagain** [comment]
Excellent! Thanks for the update!

/cc @LauraReynal @xmatthewx @secretrobotron

**Comment by HPaulJohnson** [comment]
thanks, @adamlofting 

Other updates on this ticket: 
- Small FB ad to test setup successfully running
- Adam and Paul setting up larger ad sets today to go live by 4/13; we will be targeting the market segments we've outlined in our go-to-market planning and we'll be running a copy of the Adwords Learn vs. Make campaign.
- Adam and Paul to revisit results from all campaigns on 4/15 to determine what insights should be included in initial gtm documentation.
- Next week determine what additional tests from original Adwords plan we want to add to this campaign. 
- Finally, once we've run through these initial tests to determine which words/themes work best, we'll move into creating and testing real, consumer-ready ads that have more punch and appeal for a marketing launch campaign. Aiming for early May for this part so we have a good month to develop ideas before launch.

**Comment by OpenMatt** [comment]
looks good guys. want to close this one? file a new one?

**Comment by adamlofting** [comment]
I think there's some useful content / context in here for the ongoing work. I suggest we just update the Milestone. @HPaulJohnson that OK with you?

**Comment by HPaulJohnson** [comment]
Agree with @adamlofting - let's keep this one open and update milestone.

**Comment by adamlofting** [comment]
I've written up the results from the remaining two Adwords Tests, and also the Facebook Test.

I was able to slice the Learn vs Make Ad themes from the Facebook results by Age / Gender / Location to see if any of those demographic attributes were driving the results. These were remarkably consistent but the process highlighted that our ads were almost exclusively being seen by the developing-markets segment of our list of target countries. 

https://www.dropbox.com/s/lj2q9uapxroyoaa/Screenshot%202015-04-21%2014.03.55.png?dl=0

I'm going to file a new ticket to get started on Phase III of this now, which will be 'consumer ready' copy. Once I've done that, we can close this and move the work across to there.

**Comment by adamlofting** [comment]
Just a note in case you're reading this in your email, I pasted the wrong URL into that last comment. I've updated it now on the site.

**Comment by adamlofting** [comment]
Closing this. Next phase is #438
