### ISSUE TITLE
Clean up data in preperation for migration off BSD

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#410]
We need to tidy up our current BSD data in preparation to move to another solution.

Driver @edrushka
Dev @simonwex 
Consulted @valianttry 
Informed @jbuck @ScottDowne @jdotpz 

CRM conversations are underway: https://github.com/MozillaFoundation/plan/issues/406
Scoping has been started here: https://github.com/MozillaFoundation/2015-fundraising/issues/4

**Comment by edrushka** [comment]
Adding @adamlofting

**Comment by adamlofting** [comment]
Moving this ticket into the new granular repo for the BSD migration project:
https://github.com/MozillaFoundation/mofo-crm/issues/3
