### ISSUE TITLE
Promote teach.moz.org to webmaker.org users

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#411]
After we release the new Teach site, we'll want to let Wm users know it's there.

### RACI ###
Driver: @hannahkane
Design Lead: @iamjessklein (UX) & @sabrinang (UI)
Copy Lead: ?
Engineering Lead: ?
Decision Makers: @thisandagain ?
Consulted: @chrislarry33 @ldecoursy @cassiemc @davidascher 

### Deliverables ###
 * Some sort of promotional ad and/or referral from Webmaker.org

### Timing ###
 * Not sure when we'll actually want to implement this, but I'm hoping we can design it during the April 10th heartbeat, so that it's ready to go

**Comment by jgmac1106** [comment]
This is where you folks bring you epic gif battles to bear and just keep having fun blasting us with #gifwars of why the new teach site is here and how awesome it is.

**Comment by hannahkane** [comment]
Design is wrapping up. Moving this to April 24th for implementation, after the release.

**Comment by OpenMatt** [comment]
teach team will assign their resources to do the work. @hannahkane will co-ordinate w. Webmaker product team.

**Comment by xmatthewx** [comment]
@hannahkane - One way to frame this: think about how to promote teach via content made on Webmaker rather via a link in the footer. It would help us fill the shelves with exemplar projects and help pull people to teach via specific opportunities.

**Comment by iamjessklein** [comment]
@xmatthewx - are you thinking via linking or promoting directly from existing projects? I was under the impression that this content will be replacing like-minded content that is currently on Webmaker. 

I suspect that I am confused by the roll-out or to be more accurate roll-up timing on the content migration/ switching/ etc. @hannahkane

**Comment by hannahkane** [comment]
In https://github.com/mozilla/teach.webmaker.org/issues/469 we designed an ad to temporarily live in the promo space on webmaker.org. It will live there until the Webmaker homepage design changes and can no longer accommodate it, or something else takes precedence for that spot, whichever comes first.

For long-term promotion, we definitely need to think about how to promote Teach concepts and ideas from within the new Webmaker paradigm, but I think we need to wait and see what the opportunities are, as both the new Webmaker and new Teach platforms evolve.

**Comment by xmatthewx** [comment]
> I think we need to wait and see what the opportunities are, as both the new Webmaker and new Teach platforms evolve.

Agreed. I just wanted to plant a seed. The new Webmaker will have minimal content besides the stuff that gets made by the tool. The best real estate for promotion will likely be featured projects with content shaped for a mass market audience. This could link back to content on Teach focused on people with an intent to teach and learn.

**Comment by jgmac1106** [comment]
Could you not make an app or something with the new webmaker tool that
points folks to (and possibly explains the new paradigm). There are
hundreds of posts and a few dead tree articles pointing folks to
webmaker.org as the place to go first.

Maybe there is a way to redirect while also showing off the new webmaker
tool.

**Comment by xmatthewx** [comment]
@jgmac1106 - We will have a short video and splash page later in May. For now, the best intro is http://bit.ly/webmaker-intro

**Comment by jgmac1106** [comment]
+1

**Comment by OpenMatt** [comment]
@hannahkane is looking for approval from @thisandagain to push ahead w. this

**Comment by thisandagain** [comment]
R+ :+1:

**Comment by hannahkane** [comment]
Live on webmaker.org. Yay!
