### ISSUE TITLE
Add curriculum to teach.moz.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#412]
### RACI ###
Driver: @hannahkane
Design Lead: @iamjessklein (UX) @sabrinang (UI)
Decision-maker: @chrislarry33 
Consulted: @cassiemc @thornet @LauraHilliger 

The v1 of the Teach site displays the Clubs Curriculum here: http://teach.mofostaging.net/clubs/curriculum/

We specifically designed the page to show off the first module (module = six activities) that was thoroughly tested by community members.

We know that we'll soon have an additional module of tested activities to add to the site. In fact, you can see here that we expect to have several new modules eventually: http://mozilla.github.io/webmaker-curriculum/

We need to be ready for the addition of new curriculum with a more scalable design solution.

### Design considerations ###
 * The Clubs Curriculum modules and activities are meant to be followed in a sequential order, rather than the "grab what you need" model of the Teaching Activities page (http://teach.mofostaging.net/activities/). The design should highlight the cumulative, sequential nature of the Curriculum.

**Comment by jgmac1106** [comment]
I would add **be remixable** as a design consideration.

I understand some degrees of freedom have to be lost when you are trying to
scale a project this rapidly and with such a large scope. Fidelity is key
if your metrics are going to matter.

There are three basic ways to fork curriculum: content, process, and
product. We need to give web  clubs the option to remix curriculum for
their context. This has to mean more than "its on Git just submit a pull
request."

The data collected by the #teachtheweb teams showed most mentors listed
their skills as basic to proficient. Getting the curriculum off of Git will
be impossible for many.

Is it possible to have a link to a version of the curriculum that is very
light weight in terms of css/html? All the external style sheets make it
hard for mentors to host the curriculum. Having a link to a version as
plain text as possible maybe helpful to some.

**Comment by OpenMatt** [comment]
@hannahkane: will we consider potential third-party solutions as part of this? Learning Networks team has direct experience here that can help. Even if we do design our own approach, would be good to review other curriculum platforms and tools out there. To see what's working / spot best practices etc.

**Comment by cassiemc** [comment]
Assigning this to @iamjessklein for UX and to @sabrinang for UI. Feel free to use @vazquez for design review.

**Comment by hannahkane** [comment]
Hey @jgmac1106 and @OpenMatt - thanks for your comments. I've just edited the title of this ticket to make the scope more clear. While I agree that we need a better solution for managing the curriculum itself, this ticket was intended to be more narrowly scoped. It's just about the page on the Teach site that points to the curriculum.

Implementing a better solution for Clubs is a little further along down the (ever-changing) roadmap, which you can see here: https://wiki.mozilla.org/Learning/Networks/Product-Roadmap

**Comment by jgmac1106** [comment]
@hannahkane Thanks for the link to the roadmap. Pretty cool stuff and much of the thinking already done for a plan, and what journey is worth it if you can't change your map.

**Comment by hannahkane** [comment]
Moving this to April 24, since it didn't get completed this heartbeat.

**Comment by iamjessklein** [comment]
:+1:
