### ISSUE TITLE
Determine solution for integrating Webmaker blog into Teach site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#413]
### RACI ###
Driver: @hannahkane
Design lead: @iamjessklein 
Decision maker: @chrislarry33 
Consulted: @ldecoursy @LucyeoH @amirad @thornet 

### Deliverable ###
 * A decision about whether to link, integrate, or build

**Comment by OpenMatt** [comment]
* Would love to advocate for link / integrate. And also: happy to give more / all editorial control over the Webmaker blog to this group. We *want* that content to be relevant to this audience. (if it isn't, we're doing it wrong.)

**Comment by chrislarry33** [comment]
All sounds good, still tripping on branding/naming conventions

**Comment by iamjessklein** [comment]
I just commented [this issue](https://github.com/mozilla/teach.webmaker.org/issues/458) on where we should consider the blog sitting within the context of the sitemap.

**Comment by hannahkane** [comment]
Decision has been made. See https://github.com/mozilla/teach.webmaker.org/issues/458
