### ISSUE TITLE
Implement Google OAuth2 on Discourse

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#414]
Goal : upgrade Google's OpenID authentication on Discourse. Google will be ending support for OpenID by April 20, 2015. We need to start using Google OAuth2 as soon as possible. See this guide to learn more: https://meta.discourse.org/t/configuring-google-oauth2-login-for-discourse/15858

Driver: @hannahkane 
Decision:@laurahilliger
Lead design: n/a
Lead dev: @toolness 
Quality: @laurahilliger 

Whomever takes on this task – I can give you the admin rights in Discourse if you don't already have them.

**Comment by OpenMatt** [comment]
* @simonwex  says this is a fairly small task -- about one afternoon of configuration effort

**Comment by simonwex** [comment]
@LauraHilliger could you share the admin account with @jbuck so he can get it in our shared vault?

**Comment by LauraHilliger** [comment]
We don't have an admin account like that, if we have a dummy email we use for that kind of thing, I can set it up. Otherwise, I can set @jbuck, but I need you to login once so I can set your new user as an admin.

**Comment by jbuck** [comment]
@LauraHilliger I've created my account called "jbuck"

**Comment by LauraHilliger** [comment]
done! And @toolness closed this yesterday https://github.com/mozilla/teach.webmaker.org/issues/461
