### ISSUE TITLE
Development priorities for [Heartbeat#]

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#415]
GSMA Local content research: agree on new scope of research
https://github.com/MozillaFoundation/Engagement/issues/15

World Bank S4YE RFP: Agreement on scope of work
https://github.com/MozillaFoundation/Engagement/issues/13

World Bank S4YE RFP: Sub-divide research and writing
https://github.com/MozillaFoundation/Engagement/issues/17

World Bank S4YE RFP: Final submission
https://github.com/MozillaFoundation/Engagement/issues/20

Gates Foundation FSP: Agreement on scope of work
https://github.com/MozillaFoundation/Engagement/issues/14

Gates Foundation FSP: Sub-divide research and writing
https://github.com/MozillaFoundation/Engagement/issues/17

Finalize plan for Souktel Phase 2
https://github.com/MozillaFoundation/Engagement/issues/12

Finalize MOU with Dnet
https://github.com/MozillaFoundation/Engagement/issues/18

Feedback on June delegation to Bangladesh
https://github.com/MozillaFoundation/Engagement/issues/21

Orange Partnership - Finish Orange proposal for CSR group 
https://github.com/MozillaFoundation/Engagement/issues/7

**Comment by benrito** [comment]
Experimenting with a bug in /plan that summarizes development priorities for Heartbeat. Probably doesn't need all issues logged separately but hopefully helps visibility. Work logged / taking place in the /engagement repo.

**Comment by hannahkane** [comment]
@benrito - is this ticket still useful? Can we assign to a milestone, or close it?

**Comment by benrito** [comment]
can close
