### ISSUE TITLE
Publish Q1 retrospective and Q2 goals

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#416]
Driver: @OpenMatt
Consulted: @ldecoursy @thisandagain 
Quality: @chrislarry33 @davidascher 

Publish Q1 retrospective and Q2 goals. By sharing quarterly data and content assembled for Program Review. 

Now that Q1 is wrapping, we'll want to:
1) publish a status update on how we did against our plans and KPIs
2) socialize our top-line goals for Q2

Audience: Learning Networks and Learning Products teams and communities

Success: A clear sense of how we did and what's next. Published in a range of ways that make the most sense of each audience. Plus a clear canonical home, linked from build.webmaker.org 

Solution:
1) blog posts. surfacing the publicly shareable data from Program Review slide decks 
2) book.webmaker.org
3) dashboard. ensure the relevant data will eventually appear on metrics.webmaker.org

**Comment by OpenMatt** [comment]
cc @thornet , who is going to work on a blog post and some public reflection here as well.

**Comment by OpenMatt** [comment]
Last deliverable here is Learning Networks post -- working with @ldecoursy on getting that out today.

**Comment by hannahkane** [comment]
Is this ticket done?

**Comment by ldecoursy** [comment]
Yes, thanks, posted on Webmaker blog.
