### ISSUE TITLE
Q2 / Q3 roadmap: draft 2.0

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#417]
**Goal:** produce a big picture view of upcoming work for the quarter and year, for more long-terms resource planning. 

Decision-Maker: @OpenMatt
Driver: @OpenMatt 
Consulted: program + product managers. support teams. @edrushka @ldecoursy @hannahkane  @thisandagain @davidascher 
Quality: @simonwex @cassiemc (for resourcing)

**Comment by OpenMatt** [comment]
Design resourcing here: http://cl.ly/aRYk
@simonwex do you have an engineering document we should look at as well?

**Comment by simonwex** [comment]
Learning Product (Desktop)
 * Gavin
 * Pomax

Learning Product (Mobile)
 * Kate
 * Cade

Teach (inc. website, badges, and Directory build):
 * Atul
 * Mavis

Engagement (inc. Advocacy, MozFest, Fundraising):
 * Scott
 * Ali

Devops & System maintenance:
 * JBuck & Simon

**Comment by OpenMatt** [comment]
Program Managers compiled documentation. This Heartbeat will be about more cross-team co-ordination and synthesis. Producing a shared document we can use together across the org.

**Comment by OpenMatt** [comment]
This has come pretty far here:
http://mzl.la/roadmap

Will be adding some polish and demoing tmrw.

**Comment by edrushka** [comment]
@OpenMatt I've added Advocacy, Fundraising and CRM to this doc. Most of it is vague, but it should give an indication of where we'll be asking for dev and/or design resources. Will update as I gather more details.

**Comment by OpenMatt** [comment]
* Draft 1.0 is completed here: http://wiki.webmaker.org/Main_Page
* I'll be working on Draft 2.0 this Heartbeat. Includes:
** resolving key discussion questions that emerged from 1.0 
** breaking down into Heartbeats for more granularity 
** adding more detail on Fundraising

**Comment by OpenMatt** [comment]
this is done http://mzl.la/plan
