### ISSUE TITLE
Build landing page to support value prop testing in Adwords & Facebook

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#418]
Recent campaign to test different value proposition for new Webmaker tool point to existing Webmaker.org splash page. As features and other elements of the new tool that we will be testing/promoting as part of this test don't exist on webmaker.org today we are suffering from low quality scores in Adwords and losing out on the opportunity to capture early interest in the new product. Landing page intends to better reflect new features and product (to increase quality score) and have a mechanism to capture email addresses for future product announcements (capture early interest). 

### Audience
Users clicking through from Adwords or Facebook advertising campaigns. 

### Success
Higher quality scores in Google and a list of interested users we can market to at launch of new Webmaker. 

### Vision
A simple landing page that allows for Paul and Adam to easily add new content as well as test in Optimizely. Must have an email capture function as well. 

### Measurement
Google quality scores, page visits and number of email addresses collected. 

### Roles
 * Phase: Design
 * Drivers: @HPaulJohnson @adamlofting 
 * Consulted: @thisandagain @davidascher

**Comment by HPaulJohnson** [comment]
Landing pages to support #409. 

Next steps: Outline/draft content for new landing page before assigning to design. Copy to be completed by 4/1

**Comment by adamlofting** [comment]
**Notes on process**
as we want to keep this process as light and nimble as possible.

1. We can reuse some of this landing page layout / styling to save time: https://webmaker.org/app
1. We can reuse some of the code / deployment / BSD email capture integration from: https://github.com/mozilla/webmaker-landing-pages/
  * This get's deployed to welcome.webmaker.org which is probably fine for a testing domain name (as the user doesn't ever need to type this in it won't be noticed by most people) 

**Notes on measurement**

1. As a longer view measure of success once we have a strong testing process in place
  - [ ] Build a new value proposition that relates to the new tool, and converts at at least our 5% UV to AU conversion rate (our target) and ideally keeping up with our current 8%

**Comment by adamlofting** [comment]
Just adding milestone and P2 so this shows up in the planning meeting. Better labels can be assigned then.

**Comment by OpenMatt** [comment]
@HPaulJohnson @adamlofting status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by adamlofting** [comment]
Implementation is being tracked here: https://github.com/mozilla/webmaker-desktop/issues/30

Work is still in progress so I've updated the milestone.

**Comment by thisandagain** [comment]
This should be done today. Keeping in the May 8th milestone.

**Comment by thisandagain** [comment]
Site is live and integrated into optimizely / GA here:
https://beta.webmaker.org

**Comment by HPaulJohnson** [comment]
Nice - looks great!

**Comment by adamlofting** [comment]
:metal:
