### ISSUE TITLE
Transition plan for Full Discourse Integration

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#420]
Realized b/c of https://github.com/mozilla/teach.webmaker.org/issues/461 that we're going to need a transition plan for Discourse becoming embedded into the teach site (@hannahkane's roadmap has this in Q3). 

There might be a wider strategic decision to be made here because https://github.com/mozilla/teach.webmaker.org/issues/452#issuecomment-88011098

**Comment by hannahkane** [comment]
Closing for now. Will likely likely open a new ticket at some point in H1, when there's more clarity on the reqs.
