### ISSUE TITLE
Move Engagement calendar to build.webmaker.org

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/plan#421]
Driver: @KevZawacki
Dev: tbd
CC: @edrushka 

Context: This calendar was designed for the Studio Mofo site. The visualization, created by @mmmavis  is populated by Google Spreadsheet (http://goo.gl/niumZ2), which Kevin updates. It provides a good overview of both MoFo and MoCo activities from large (all channels) to small (local events).

**Comment by edrushka** [comment]
Hey @KevZawacki. @davidascher works on build.webmaker.org when he has time. David, is it cool if I assign this to you? It is a non-urgent task, and one that fits nicely with the long-term forecasting we discussed in yesterday's TPS call.

**Comment by davidascher** [comment]
Sure, I have followup questions but i'll write them up.

**Comment by mmmavis** [comment]
I'm back from PTO!  Let me know what I should supply. :smile:

**Comment by davidascher** [comment]
@mmmavis can you show me what y'all are talking about (both the visual and the code you built for studiomofo?)

**Comment by mmmavis** [comment]
@davidascher 
original studiomofo repo: https://github.com/mozilla/studiomofo
i extracted the viz bits and put the code here: https://github.com/mmmavis/mofo-calendar-viz, it should look like http://mmmavis.github.io/mofo-calendar-viz/

**Comment by davidascher** [comment]
@mmmavis, if you're game, adding this to build.webmaker.org would be a
great thing for you to do to get familiar with some of the tools we're
using in mofo-style (although that specific site has drifted a bit from the
standard).  I'd suggest you look at
https://github.com/mozilla/build.webmaker.org/ and in particular Adam's
latest additions as a recipe for how to add new pages.  We could start w/
just a new "schedule" sidebar item that would load this calendar in a new
page at the /schedule endpoint.

/cc @simonwex from a prioritization POV.

**Comment by simonwex** [comment]
@mmmavis, FYI - this'll probably fall to Ali or Scott since they're helping @edrushka for the rest of the quarter.

**Comment by edrushka** [comment]
Closing as this hasn't been touched since April.
