### ISSUE TITLE
Agree upon Teach site l10n strategy

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#422]
Even as we iterate on the EN version of Teach.m.o, we'll want to have a plan and strategy for localizing the content (and, indeed, we've already started with the curriculum).

I realize that much thinking has already been done by others, so this might be superfluous, but I started a document capturing many of the issues and decisions that I think we ought to discuss. Would love to talk through this with people who know more than me in an upcoming heartbeat. :)

http://mzl.la/1GJySeG

Nothing specific to do now, but would welcome all kinds of feedback at any point (including the, "hey, this has already been documented elsewhere" kind of feedback).

cc @alicoding @secretrobotron @chrislarry33 @ldecoursy @davidascher @OpenMatt @simonwex @thisandagain

**Comment by hannahkane** [comment]
Thanks to @thornet and @LucyeoH who have already commented on the doc.

**Comment by thisandagain** [comment]
Thanks for sharing @hannahkane. Left a few notes in the doc.

**Comment by simonwex** [comment]
@hannahkane, @edrushka, I spoke with @alicoding about this today. We need to spend a bit of time figuring out an l10n strategy for React-based sites. This is going to have implications for all the sites we build this year. If we start looking good for the launch of the teach site, it'd make sense to have Ali dig into this this <img src="https://cloud.githubusercontent.com/assets/25260/6935113/9828a410-d7f4-11e4-9d8d-7192c207958a.png" width="32" height="32">

**Comment by hannahkane** [comment]
OK, I can put a ticket in /plan specifically for the technical aspects of l10n, and we can pitch it at the next TPS meeting.

**Comment by simonwex** [comment]
+1

**Comment by hannahkane** [comment]
Closing in lieu of #642
