### ISSUE TITLE
Document Services design for Webmaker

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#427]
**Goal**: Produce documentation for the tech stack for Webmaker services (e.g. data storage, moving away from Firebase, etc.)

Documents to produce:
 - Logical diagram of project storage
 - Document integration with id.wm.o
 - Articulate tech stack for storage API

**Milestone**: TBD

### RACI
Phase: Design
Driver: @xmatthewx 
Decision: @thisandagain 
Dev: @jbuck
Dev: @cadecairos 
Dev: @k88hudson 
Lead design: @xmatthewx
Quality: @simonwex 
Metrics: @adamlofting

**Comment by k88hudson** [comment]
@simonwex and @jbuck to document Oauth2/authentication work
@k88hudson and @gvn to document questions impacting service design here: https://etherpad.mozilla.org/servicetechquestionswebmaker

**Comment by xmatthewx** [comment]
I answered questions in the pad, though this will definitely need review by @flukeout and @thisandagain. Some of it is TBD since design of social won't even begin until Q3. 

I added [a slide in the build deck](https://docs.google.com/a/mozillafoundation.org/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g97d20baa5_7_41) to summarize and start a diagram on this. Edit freely.

**Comment by xmatthewx** [comment]
cc @Pomax

**Comment by simonwex** [comment]
We should also do an inventory of the fields currently in the MakeAPI to see if there are easy wins for supporting future social features. -- What comes to mind is `remixedFrom`

**Comment by xmatthewx** [comment]
@k88hudson is going to start a spanking new repo where we can track questions, answers, and decisions.

**Comment by simonwex** [comment]
May I suggest api.webmaker.org?

**Comment by simonwex** [comment]
May I suggest api.webmaker.org?

**Comment by cadecairos** [comment]
> May I suggest api.webmaker.org?

:+1:

**Comment by cadecairos** [comment]
I just created https://github.com/mozilla/api.webmaker.org

**Comment by OpenMatt** [comment]
@xmatthewx status update?

**Comment by xmatthewx** [comment]
Success 
 - plans documented on https://github.com/mozilla/api.webmaker.org in the [alpha miletone](https://github.com/mozilla/api.webmaker.org/issues?q=is%3Aopen+is%3Aissue+milestone%3AAlpha)
 - @cadecairos set up test server with docs running at https://skittles-api.herokuapp.com/docs

@thisandagain & @secretrobotron - moving forward, do we want a separate planning ticket for services? Or, should we include it in #443?

**Comment by xmatthewx** [comment]
Merging with the Alpha milestone #443. We can open a separate planning ticket if needed.
