### ISSUE TITLE
Begin build of Webmaker Alpha 

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#429]
Continue the prototypes in #405 to build the foundation for Webmaker's Alpha release. 

### Goals

Primary goals:
 - Finalize UI on Alpha features
 - Begin UI on Beta features
 - Implement primary views for Map, Page, Element
 - Implement Android wrappers
 - Scaffold services

Secondary goals:
 - Support research trips
 - Develop user testing plan
 - Complete UX for Beta features
 - Begin UX on RC features
 - Begin UX on desktop coding features

### RACI

Phase: Build
Driver: @secretrobotron, @xmatthewx
Decision: @thisandagain
Design: @flukeout @vazquez 
Dev: @gvn, @Pomax, @k88hudson
Quality: 
Metrics:

**Comment by xmatthewx** [comment]
We met to kickoff the heartbeat. 

On Dev, @Pomax, @gvn, @k88hudson will:
 - unify their segments of the platform
 - tackle alpha [roadmap](https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1ZvdNJLHuW0fIBt_-WcR7Ns6OhZgaMy6MI9kfjlXF-9o/edit#gid=0) items flagged as heartbeat 1
 - @Pomax will wrangle instructions/demo so more team members can contribute and review progress prior to release. 

On UX, @flukeout will: 
 - continue to refine the play experience 
 - document interactions and transitions
 - provide feedback to devs on front-end implementation
 - time allowing, he'll proceed with beta features, tinker mode, code editor with Drexel

On UI next week, @vazquez will:
 - finalize views for alpha release
 - begin work on views for beta release

In parallel, we will
 - KIT w/ researchers in Chicago
 - Support services work
 - Support @secretrobotron's content plan
 - Track @HPaulJohnson's go to market strategy
 - Plan research with Drexel

**Comment by OpenMatt** [comment]
@secretrobotron @xmatthewx: status update?

**Comment by xmatthewx** [comment]
Big heartbeat with lots of progress:
 - Engineers completed a build to unify the app's front, back, and middle on Android. 
 - @flukeout refined UX and executed a round of user tests https://github.com/mozilla/webmaker-app/issues/1548
 - @vazquez finalized UI minutiae posted to [invision](minutiae) 
 - full team got up and running with Android studio

Work plan continues in #443
