### ISSUE TITLE
Communications plan for legacy tools

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#430]
### Roles:
* Phase: Plan
* Owner: @HPaulJohnson 
* Decision-Maker: @HPaulJohnson 
* Design Lead: n/a
* Dev Lead: n/a
* Consulted: @KevZawacki @ldecoursy 
* Quality: @chrislarry33 @davidascher 

Create a plan to document/broadcast the future of legacy tools, including which will continue to be supported (where and how), which won't (with options for saving existing content), etc.

Also outline channels for communicating these changes (ie email notifications, webmaker.org, social, blog, etc.)

Draw from planning in #339

**Comment by ldecoursy** [comment]
@KevZawacki drafted blog post, FAQ and email, and reviewed with @HPaulJohnson @ldecoursy and @amirad. 

To come: Updated draft with few remaining q's for @davidascher and @chrislarry33, as well as a timeline and list of relevant communications channels.

**Comment by HPaulJohnson** [comment]
A few additional deliverables @adamlofting and I discussed this morning to support this: 

- A list of "active" Webmaker users (logged in last X days) for direct outreach
- A list of top ~20 referring sites (ex. Made with Code) so that we can reach out to specific partners who may be linking to these tools and driving traffic.

**Comment by adamlofting** [comment]
We should generate the list of "active" users when we get close to sending the email.

Excluding our sites, news sites, social shares and content hosted on makes.org that points to our tools (teaching kits etc), these are the top sites referring traffic to us in the last year:

-  madewithcode.com
-  developer.mozilla.org
-  code.org
-  classroom.google.com (this is teachers linking to the tools - mostly during maker party)
-  vide0.org.ua
-  backpack.openbadges.org
-  whatcanidoformozilla.org
-  edmodo.com
-  commonsensemedia.org
-  canaldoensino.com.br
-  formacion.educalab.es
-  mousesquad.org
-  graphite.org
-  skilledup.com
-  makethingsdostuff.co.uk
-  mrjacob.net
-  oncourse.iu.edu
-  porvir.org

Some of these are educational platforms where we can't communicate with the end user though.

And there are some partnerships that drive people direct to the tools at events or via printed materials and those won't show up in this list.

**Comment by jgmac1106** [comment]
Google Classroom did not debut until August 2014 and is only available in
#GAFE schools. These may be teachers in formal education who regularly use
the tools.

It may not have been Maker Party but teachers setting up their LMS in same
time frame.

They could be an important contact point for recruiting club captains.

Also means we may want to communicate legacy tool plan on popular #GAFE
networks.

**Comment by jgmac1106** [comment]
Same with Edmodo. Probably a few key groups to cross post blogs that can
get message out.

**Comment by HPaulJohnson** [comment]
A few open questions remain on this ticket, including some technical details and timing specifics. Beyond those, gating issue is when teach site is ready to be more publicly promoted. 

Planning is complete and we should be able to start communicating by the end of the next sprint.

**Comment by chrislarry33** [comment]
@ldecoursy and @hannahkane can correct me if i am wrong, but my sense next week we are ready for some kind of traffic and have it going a few layers more public. I'd hate to be a blocker to the comms. Can we add a piece that says teach site still evolving?

**Comment by hannahkane** [comment]
+1 both to being ready and to including language about the evolving nature of the site.

**Comment by HPaulJohnson** [comment]
Sounds good. We'll tweak the language and try to get it up next week (targeting 4/30), assuming we resolve a few of the other technical details needed for the FAQ.

**Comment by HPaulJohnson** [comment]
Most recent plan: https://docs.google.com/document/d/1PLfNVWv67OFNt-bSzl7Lv08eImK_LfIHMv8T2WhWg3c/edit

**Comment by OpenMatt** [comment]
* note that April 31st is a key deadline (flexible) -- we're tying the plan for legacy tools to announcing the launch of teach.moz.org

**Comment by HPaulJohnson** [comment]
Update: Received few, last technical details that were outstanding this afternoon. I've incorporated them into a final draft below. 

https://docs.google.com/document/d/1PLfNVWv67OFNt-bSzl7Lv08eImK_LfIHMv8T2WhWg3c/edit

I'd like everyone to give it a final review and signoff, including technical review by @simonwex and @davidascher, Webmaker app language by @thisandagain and teach.mozilla.org language by @ldecoursy, @chrislarry33 and @hannahkane 

The original plan was to post tomorrow, 4/30. Given we are just now finalizing I'm recommending we move that to Monday, May 4. If that's cause for concern please let me know.

**Comment by thisandagain** [comment]
@HPaulJohnson I left a few suggestions and comments in-line.

**Comment by thisandagain** [comment]
I'd prefer to not put this on the splash page of webmaker.org. Generally, I'd consider it best practice to have a new product in-place before you start announcing feature / product-line deprecations. While I 100% appreciate that we have a special circumstance here with power users and specifically mentors who are teaching with the tools, putting this transitional messaging on the splash page doesn't seem necessary or even relevant to most users. 

What I recommend instead is adding a dismissible modal to Popcorn and Appmaker that links to the blog post. This focuses our messaging on active users of the two tools that are being effected without presenting confusing messaging to other users that will either a) be transitioned to a new resource in `teach.mozilla.org` which we are already getting ready to promote on the splash page or b) new to Webmaker (the *VAST* majority). 

As the number of engaged user's on Popcorn and Appmaker is quite low, there is an argument for us to just leave it be and focus on other priorities as well. I'd appreciate any thoughts.

**Comment by HPaulJohnson** [comment]
Thanks for the review @thisandagain. This makes sense to me too, so we'll refrain from putting any messaging on webmaker.org.

**Comment by hannahkane** [comment]
I think the modal on Popcorn and Appmaker, in lieu of a splash page announcement, is a sensible idea. R+ on the language in the blog post and emails.

**Comment by adamlofting** [comment]
@HPaulJohnson : There is a constituent group setup in BSD now: `2015May_WebmakerUsersActive_Last6months`

This is everyone who has published a make in the last 6 months who has also opted in to email comms from us.

**Comment by davidascher** [comment]
BSD question: is this a rolling 6 months, or is this group now frozen?

**Comment by adamlofting** [comment]
This is frozen, as it requires a manual process for me to query the several tools databases to see who is using the tools, generate a CSV and import to BSD.

I can repeat for high value activities, but I'm looking forward to solving this with integrated CRM in the future :smile:

**Comment by davidascher** [comment]
Wfm.

**Comment by HPaulJohnson** [comment]
Post is live at https://blog.webmaker.org/whats-next-for-webmaker-tools

Email sent to most active users of tools and mentor list (total 20K) and @ldecoursy is messaging Hive directly. She and I are also going to be reaching out to partners with inbound links to webmaker tools in the coming weeks. 

Closing this one as it's a wrap.
