### ISSUE TITLE
Collaborate with Drexel on Code editor

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#432]
We're collaborating with a team at Drexel University. They've compiled some interesting [research](http://openhtml.org/#research) on the experience of new coders. There's an opportunity to prototype and test features of a code editor that support learning, features that could be integrated into Webmaker.  

Conversation is tracked here: https://github.com/mozilla/webmaker-desktop/issues/17

**Comment by xmatthewx** [comment]
Bumping to next milestone to continue work. cc @secretrobotron @thisandagain

**Comment by secretrobotron** [comment]
:+1:

**Comment by OpenMatt** [comment]
(note: Humph is looped in here)

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
No big updates. Bumping to next heartbeat.

**Comment by OpenMatt** [comment]
Drexel will be sharing prototype in today's Webmaker demos call

**Comment by hannahkane** [comment]
@xmatthewx - is this ticket still useful?

**Comment by xmatthewx** [comment]
Gone stale. Closing.
