### ISSUE TITLE
FreePolicy

### ISSUE THREAD

**Issue by AJaySi** [MozillaFoundation/plan#436]
Insurance Policy Sector in india. 
Insurance web aggregators in india are setting a wrong trend where they are hassling users for insurance data. There is misselling in which the agent sells the insurance policy for higher commission than user's requirement. They are then biased. 
We aim to provide a platform for all insurance data without any user details. 
There is no signup Or logging user data in anyway. 
We do not intend to 'sell' insurance so the platform remains neutral. 

We intend to provide information to everyone to help them make right insurance policy decision.
Insurance is a subject matter of solicitation.
 

### Audience
All indian end-users who feel the need to look up insurance data on the net. 

### Success
Mis-selling in insurance is a big deal. Policy lapsation is a also a big problem. 
Most of the problems are because are not made aware and they end up buying an insurance they never asked for. 
There is a need to aggregate the insurance information from Govt sites and then present to the people. 

Insurance is a big sector in india, but people over the years have lost faith as they all feel cheated because of information gap. The policy brokers and agents have been taking advantage of this gap for decades. 

### Vision
There are web aggregators who provide the similar services. 
They ask for log-in and mobile mandatory. These web aggregators are selling 'Leads" to the banks. 
They also sell policies which gets the commission. 

We will not do singups, No selling, just policy data so users can benefit
There will be a forum for people to talk to each other and solve their doubts about insurance.

### Measurement
There is trend in india, where engineers are dishing out 'Apps' to monetize data. 
Internet is not free. Its resembles a hoarding board. it has become difficult to mine for information. 

Indian populace is not well educated in matters of computer and 'Apps' and insurance web aggregators are setting a trend in which technology is for money . If one can collect some information on the internet, they look it behind sign-ins. They then sell your details as leads. 

We measure our success as being competitor to 'Policybazzar.com' and proving to people that same services/Data can be made available for Free. 
Maybe, then a lot of people and 'Apps' will not be made with the sole purpose of getting rich. 

There is also a 'social' responsibilty. 

### Roles
 * Phase: 
 * Driver: 
 * Decision Maker: @acabunoc
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by cassiemc** [comment]
This is a great idea @AJaySi but it isn't aligned with Mozilla's plans in 2016. We are going to close this for now. Here's a blog post from our Executive Director Mark Surman if you'd like to digest the plans and offer any other thoughts: http://marksurman.commons.ca/2015/12/21/mofo2020/
