### ISSUE TITLE
Value Proposition Testing, Phase III

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#438]
This work continues from [Phase II #409](https://github.com/MozillaFoundation/plan/issues/409)...

We want to develop a compelling value proposition for the new Webmaker App, with language that draws people into the site, and ultimate convinces them to install and/or sign-up.

### Audience
We are targeting potential users of the Webmaker App. 

This work will inform, and be informed by, our Go To Market (GTM) strategy.

### Success

1. A single value proposition, and/or collection of 'ad-length' marketing phrases that best appeals to our target audience and drive people to use the product.  
2. A shared data-set of ads and language that we tested, but which failed to perform as well as our control
3. A process by which we can continue to measure and test the performance of our value proposition over time

### Vision

1. Review the results of our testing to date to learn from early indicators
2. Review our existing list of test ideas about content we think could be important in this offering
3. Write many 'consumer ready' ads using any combination of language and benefits we think will appeal and test for results
4. Make whichever ad performs the best our 'Control' messaging and continue to pitch 'Challengers' against this up until product launch

### Measurement

1. Initially, we will be relying on Click Through Rate (CTR) data in Google and Facebook Ads, which requires us to be aware that the text of the ads has to relate as closely as possible to the vision of the Webmaker App as it is being built. (Otherwise we can generate copy that gets a high CTR, but doesn't connect with the product).
2. Next we will build a marketing landing page where we can capture interest before the product launches. This will allow us to test ads for sign-up conversion rate rather than just CTR, which is a better measure

### Roles
 * Phase: Live / Ongoing Testing
 * Driver: @HPaulJohnson
 * Decision Maker: @HPaulJohnson / @thisandagain 
 * Quality Verifier: @thisandagain 
 * Metrics: @adamlofting

**Comment by adamlofting** [comment]
cc'ing from previous tickets: @thisandagain @KevZawacki

**Comment by adamlofting** [comment]
Reference Material
* [Our previous testing results and list of content ideas](https://docs.google.com/a/mozillafoundation.org/document/d/16WT50NzQziOjunUPZhS-oIaVNVJgVNhifzQsCZihJxs/edit#)

Next step is for @HPaulJohnson and @KevZawacki 
- [ ] Prepare initial consumer ready ad copy for use in Facebook and Adwords

**Comment by HPaulJohnson** [comment]
Adding @edrushka for her assistance in developing ad copy. We'll aim to have some ideas ready by 4/23.

@thisandagain ideally we can get design/dev resources for the landing page into the next sprint?

**Comment by thisandagain** [comment]
@HPaulJohnson Getting design resources shouldn't be a problem, but I'm a little short on devs right now. We've got a scheduling / roadmap meeting tomorrow and will try to find a way to get this done with @xmatthewx and @secretrobotron.

**Comment by adamlofting** [comment]
To support the resourcing conversations, this ticket `Build landing page to support value proposition testing in Adwords and on Facebook` #418 should give an idea of scope.

**Comment by thisandagain** [comment]
Added to @vazquez and I's SOW for the next sprint. @xmatthewx is going to take a crack at an IA early next week.

**Comment by HPaulJohnson** [comment]
In addition to landing page work, going to convene a group of creative thinkers to help develop next phase of ads. Kickoff meeting for that to come early next week.

**Comment by HPaulJohnson** [comment]
Lots of thinking and progress made during the sprint. Notes and ideas from the process here: https://etherpad.mozilla.org/launchads

This is still a WIP and there is more to do this sprint and therefore bumping it out to May 22 (will likely go all the way up until launch). Next steps:

* Relaunch FB campaign in conjunction with app landing page launch, using top 3-4 concepts we've come up with to-date.
* Continue to convene small creative group regularly over the course of this sprint to refine ideas and add new ones to the testing queue.

**Comment by adamlofting** [comment]
I've setup 10 variations of these ideas in AdWords to start collecting data. We can still continue coming up with new ideas, but we might as well start collecting data now (and hopefully finding people interested in hearing when the app launches).  :hatching_chick:

**Comment by HPaulJohnson** [comment]
Facebook campaign is running with the same 10 variations across 5 ad sets (BD, IN, KE, BR, US) = 50 ads. 

Next steps for next sprint: 
* Analyze results across Google and FB for this campaign
* Develop 5-10 new ad variations to begin testing
* Setup localization plan for winning ads for final phase of testing before launch.

**Comment by adamlofting** [comment]
Subject to capacity, we should think about promoting the beta sign-up page across the existing webmaker properties now that we're in the countdown to launch phase. Maybe even switching out the homepage sign-up form?

What do you think @thisandagain?

**Comment by thisandagain** [comment]
That seems reasonable to me. I'm happy to take a crack at it as a P2. @k88hudson, @Pomax  and @vazquez are out next week so I'm really light in terms of design / dev capacity.

**Comment by OpenMatt** [comment]
status update?

**Comment by OpenMatt** [comment]
rolling over

**Comment by adamlofting** [comment]
Quick note. We're getting some traffic through on these ads now (~5k visits), but conversion rate for the page is really low (~0.5% for email signup). This might just be the audience, and we don't have similar campaigns to compare with, but we should try and get this page in front of any warm audiences that we can.

So we might want to up the priority of testing with existing audiences. Even if it's just a few tweets or fb posts from our channels to say 'new app coming soon', we can get a better sense of the data.

**Comment by thisandagain** [comment]
Thanks for the update. Agreed ... @HPaulJohnson is this something you can handle this week?

**Comment by HPaulJohnson** [comment]
Yep. @KevZawacki can you come up with a few sample tweets and FB posts?

**Comment by KevZawacki** [comment]
Definitely:

++Twitter++

Coming soon: Webmaker, Mozilla's mobile content creation tool that empowers you to create anytime, anywhere: [link]

Next month, Mozilla is unveiling Webmaker: the free, open-source tool for creating and sharing online. Learn more: [link]

++Facebook+

Making and sharing cool things online is about to get easier. This June, Mozilla is unveiling Webmaker -- the free mobile platform for creating local content. [link]

Have you heard of Webmaker? Mozilla's new mobile tool for creating and sharing with friends is coming this June. [link]

**Comment by OpenMatt** [comment]
* Phase IV coming soon!

**Comment by OpenMatt** [comment]
@HPaulJohnson will update here with results and next steps
