### ISSUE TITLE
Migrate CRM Services from BSD to Salesforce/Exact Target

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#439]
This is a meta ticket for the large task of moving our data off BSD and onto Salesforce/Exact Target

Project lead: @adamlofting 
Project manager: @edrushka
Consulted: @valianttry @davidascher 

Wiki: http://wiki.webmaker.org/CRM

Sub-tickets to come...

**Comment by adamlofting** [comment]
Sub-tickets are being filed in the mofo-crm repo, using the tag `BSD Migration`:
* [See existing tickets here](https://github.com/MozillaFoundation/mofo-crm/labels/BSD%20Migration)

**Comment by adamlofting** [comment]
And for reference this is the migration plan as it currently stands:
* https://docs.google.com/document/d/1d386Yqsc4UO214Wy3BZcstPze8640r8xvmpGrfq-3V0/edit#

**Comment by adamlofting** [comment]
I've filed one upcoming piece of work for this project in `plan` as it `needs-dev`: https://github.com/MozillaFoundation/plan/issues/455

**Comment by edrushka** [comment]
Moving ahead to next milestone as this work is ongoing.

**Comment by adamlofting** [comment]
I've updated the scope of #455 to reflect what we can start work on right away.

**Comment by adamlofting** [comment]
Closing this as we're sticking to more granular tasks (2 week commitments) in Heartbeat Planning.
