### ISSUE TITLE
Prepare Discourse install for localization

### ISSUE THREAD

**Issue by LauraHilliger** [MozillaFoundation/plan#440]
https://github.com/mozilla/teach.webmaker.org/issues/802 established the need for Discourse to support multiple languages. The project is localized [using Transifex](https://www.transifex.com/projects/p/discourse-org/) and includes [dev documentation](http://blog.discourse.org/2013/03/localizing-discourse/) on how we build this in. Starting with Portuguese will support Club activities in Brasil.

**Comment by soapdog** [comment]
Will ping our L10N community to help with localization.

**Comment by simonwex** [comment]
Stale ticket, ping me if we need to re-open.
