### ISSUE TITLE
Make decicion on MozFest scheduling tool

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#442]
We're nearing completion on the MozFest site design. It's time to make the final decision on which tool we'll use for the schedule.

driver: @edrushka
decision-maker: @Saallen 
consulted: @simonwex @davidascher @alicoding @ScottDowne 
informed: @iamjessklein @cassiemc @thornet

**Comment by simonwex** [comment]
I'm happy to help make that decision. Could we link to all the relevant designs and requirements docs here?

**Comment by edrushka** [comment]
Yes!
* @iamjessklein is finalizing UX today and should have something posted by Monday. 
* a contractor will finalize UI during the May 8 heartbeat
* Much of our thinking has been documented here: https://studiomofo.etherpad.mozilla.org/MozFest-2015-site-plans and 
* Roberto put a fair amount of thought into the schedule tool's functionality here: https://projects.invisionapp.com/share/AY2GUNPXU#/screens/68403758?maintainScrollPosition=false

**Comment by Saallen** [comment]
Which ever tools are shortlisted I would really like the Space Wranglers to test pre confirmation.
@davidascher suggested https://sched.org/ which I really liked for its mass functionality but very happy to hear about and test other options.

**Comment by thornet** [comment]
+1 to having the wranglers test our shortlist favs. They'll help us determine what's going to work well during the call for proposals, scheduling and on-site editing.

**Comment by Saallen** [comment]
I asked some Space Wranglers to help test some tools when we have a shortlist
Including @misty A @kaitlinT @secretrobotron @erikao

**Comment by Saallen** [comment]
I created an [etherpad] (https://festival.etherpad.mozilla.org/2015scheltool) \o/  which outlines feedback from last year and this years review process.

**Comment by edrushka** [comment]
Update:
We met this morning and created a shortlist to test (line 55 of this pad https://festival.etherpad.mozilla.org/2015scheltool?)

Sarah will wrangle the wranglers to help us test. We'll bring this list down to 2 or 3 and have Ali and Scott review for ease of integrating into the MozFest site and then we'll make a final decision.

**Comment by edrushka** [comment]
We've narrowed the shortlist down to two contenders:
#### 1) [Sched] (https://sched.org/) 
This will be used at Whistler coincidental workweek, so we'll get to see it in action with time to make adjustments. Examples: https://juneworkweekwhistler2015.sched.org/  and  https://juneworkweekwhistler2015.sched.org/mobile/#schedule-type:Meals


#### 2) [Attendify] (https://attendify.com/how_it_works/) 
(Sarah has a login and can screenshare)

@ScottDowne @alicoding do you want to take a quick peek at these two and see if anything jumps out at you. Keep in mind the Github integration we're considering to organize the proposed sessions.

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by OpenMatt** [comment]
um... weird spam

@edrushka status?

**Comment by edrushka** [comment]
Just waiting to see if Ali or Scott has anything to add re: our shortlist. Decision coming soon.

**Comment by ScottDowne** [comment]
So far Sched is the clear winner.

I'm having a hard time figuring out how Attendify imports sessions from a spreadsheet (or something else) or how to embed it.

On the other side, Sched can import multiple ways and even has an import API so I can do it myself from anything (github issues?). It also clearly supports embed with the pro account.

Sched pro cost is still cheaper than attendify basic. Sched basic account is 99 which doesn't support embed, the pro account is 499 which does. Attendify's cheapest is 999 and from what I can tell, doesn't support embed or import.

On top of that, my test app for Sched went up in seconds and Whistler is using it.

I also found someone who has used both and asked questions.

**Comment by jgmac1106** [comment]
We use sched for the Literacy Research Association conference and it is a
smooth tool for both the end user and admin.

Our target audience has 0% webby skills and most can figure it out with
ease.

**Comment by Saallen** [comment]
@ScottDowne 
I agree with you Scott- Sced is extremely easy to use, the backend very user friends and the cost is great.
Attendify is an spreadsheet upload when I worry about the functionailty of the backend and app build.
Scedul can be synced with calendar of choice and is very low tech for new users

**Comment by edrushka** [comment]
@Saallen do you want to negotiate pricing with Sched, and if that works we can lock down this decision?

**Comment by Saallen** [comment]
Yes. I take it we want White Label Integration?

**Comment by ScottDowne** [comment]
@Saallen I am unfamiliar with White Label?

**Comment by Saallen** [comment]
I had to look it up! So that we can intergrate the schedule into our website.....i think?
Someone please correct me if I am wrong

**Comment by ScottDowne** [comment]
Ahh, white label is embedding thingy.

Weird, they gave it a name? Is that a thing? Anyway, yes, White Label :D

**Comment by ScottDowne** [comment]
Ah, white label allows us to style the embed.

I thought it was dewar's white label.

**Comment by Saallen** [comment]
I have had a look through the pricing and I will be able to talk to Brianna from MoCo about their pricing plan, but from what I have seen is that we can just purchase the basic application and add on white Label. @ScottDowne do you think you will need anymore add-ons?

**Comment by edrushka** [comment]
Closing this as we've decided on Sched.
