### ISSUE TITLE
Complete build of Webmaker Alpha

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#443]
Continues work from #429 to build Webmaker's Alpha release.

Goals:
 - Build core end to end experience on Android with refined UI
 - Implement and connect to services API
 - Iterate on design based on remote testing and field research. 

Links:
 - [http://bit.ly/webmaker-intro](http://bit.ly/webmaker-intro)
 - [http://bit.ly/webmaker-build](http://bit.ly/webmaker-build)
 - [Roadmap](https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1Zv)
 - [Milestone issues](https://github.com/mozilla/webmaker-app/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Alpha+2%2F2%22)

### RACI

Phase: Build
Driver: @secretrobotron, @xmatthewx
Decision: @thisandagain
Design: @flukeout @vazquez 
Dev: @gvn, @Pomax, @k88hudson
Services: @jbuck @cadecairos 
Quality: 
Metrics: @adamlofting

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Webmaker Alpha launched after some heroic work by the team over the past couple weeks (and by @k88hudson @thisandagain @cadecairos over the weekend). 

 - Install on Android 5 (Lollipop) - https://webmaker-dist.s3.amazonaws.com/v1/app-release.apk
 - Brief video demo: https://vimeo.com/127446372

Work on Beta begins in #444.
