### ISSUE TITLE
Begin Webmaker Beta

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#444]
Continues work from #443 to build Webmaker's Beta release.

[Roadmap](https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1ZvdNJLHuW0fIBt_-WcR7Ns6OhZgaMy6MI9kfjlXF-9o/edit#gid=0)

### RACI

Phase: Build
Driver: @secretrobotron, @xmatthewx
Decision: @thisandagain
Design: @flukeout @vazquez 
Dev: @gvn, @Pomax, @k88hudson
Services: @cadecairos 
Quality: 
Metrics:

**Comment by xmatthewx** [comment]
Beta 1 of 2 milestone in [webmaker-android](https://github.com/mozilla/webmaker-android/milestones/Beta%201/2) repo.

This heartbeat will focus on: 
 - adding features (links, image upload, sharing, ...) 
 - adding user accounts

**Comment by secretrobotron** [comment]
With the features that should be completed by the end of this milestone, I'd love to schedule a day or two near the end for the team (and some select others) to create content with it.

Also, I'm going to try to work with @cadecairos on starting details and implementation for community management tools.

**Comment by OpenMatt** [comment]
should maybe add Cade to this list...

**Comment by thisandagain** [comment]
Work landed in nightly build. Will be releasing a new preview build on Monday.

**Comment by jgmac1106** [comment]
Question: If I sideloaded the apk do I have to reinstall to get updates or
do they come OTA?

**Comment by thisandagain** [comment]
Good question @jgmac1106 ! For now you'll need to re-install to get the updates. Once we release to Google Play (just a few weeks away!) you'll be able to get updates over-the-air.
