### ISSUE TITLE
Pre-Maker Party Comms

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#446]
We need to prime internal/external audiences about Maker Party in 2015.

### Audience
Mozillians, Webmaker/Teach community and past Maker Party participants.

### Success
Success is people being aware that Maker Party 2015 is happening from July 15-31, getting them excited enough to participate and introduce the idea of how MP relates to the newly created Mozilla Clubs. 

The objective here is to develop the initial comms to start priming this awareness and interest.

### Vision
This pre-Maker Party phase will consist of initial internal and external communications: 

- Internal: Staff email, update on project call and webmaker blog post
- External: Targeted "save the date" email, social media promotion and webmaker blog post (same post can be used for internal/external). 

### Measurement
Completed email, social promo and blog post that can be sent later in May. Goal of the project is to develop assets only; deployment to come later in the month, under a separate ticket. 

### Roles
 * Phase: 
 * Driver: @HPaulJohnson
 * Decision Maker: @HPaulJohnson
 * Design Lead: 
 * Consulted: @KevZawacki @amirad @ldecoursy

**Comment by OpenMatt** [comment]
* question for @ldecoursy : re Maker Party landing page

**Comment by ldecoursy** [comment]
Here's the ticket for MP landing page on teach.mozilla.org: https://github.com/mozilla/teach.webmaker.org/issues/736

We'll just want to sync up timing.

**Comment by HPaulJohnson** [comment]
Updated in https://github.com/MozillaFoundation/plan/issues/446, copying here (not sure we need both issues): 

* Blog post, internal email and update on project call on 5/18. @KevinZawacki and I will put together messaging for this next week.
* Save the date email and social promotion on 5/21.
*  All other dates stay the same.

**Comment by ldecoursy** [comment]
All posted - thanks @HPaulJohnson and @KevZawacki!
