### ISSUE TITLE
Meeting to discuss supporting Thimble moving forward

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#447]
Since we're preparing to debut the shiny, new Thimble and house it on the Teach site, let's figure out how we're going to support the Thimble team moving forward.

Deliverables:
 * clear roles for Mofos involved in Thimble work
 * timeline for re-debut and integration into Teach

**Comment by OpenMatt** [comment]
* question: who's liasing with Humph's team? 
* @davidascher met with humph last week. he wants a backlog of tasks.
* proposal: @hannahkane will manage and prioritize the backlog. and review it with humph's team / set process for going forward.

**Comment by OpenMatt** [comment]
next step: Hannah will rescope this ticket and meet w. Humph

**Comment by hannahkane** [comment]
Scheduled for tomorrow.

**Comment by hannahkane** [comment]
This happened. Follow up with @humphd will happen next week to start prioritizing a backlog. This is officially in motion, so I'm closing.

**Comment by humphd** [comment]
A note on one of our decisions: going forward we'll file bugs related to the Thimble work in https://github.com/mozilla/thimble.webmaker.org and devs will file upstream bugs in related repos.  For purposes of our community, this can be the canonical repo for all "Thimble" related work.
