### ISSUE TITLE
Tweak current instance of Salesforce

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#449]
The partnerships teams is currently using Salesforce. This instance was set up in late 2014, and can be considered a kind of MoFo Salesforce 1.0.

This is meta-ticket for tweaks and adjustments.

driver @edrushka
dev @alicoding 
informed @benrito

**Comment by edrushka** [comment]
* First we need to get dev access: https://github.com/MozillaFoundation/mofo-crm/issues/1
* Next, the first set of adjustments is outlined here: https://github.com/MozillaFoundation/Engagement/issues/5 (note that future tickets will be filed in https://github.com/MozillaFoundation/mofo-crm)

**Comment by OpenMatt** [comment]
@edrushka status?

**Comment by edrushka** [comment]
I'm pressing pause on this because Lynn and Ben are debating if it's even needed.
