### ISSUE TITLE
Finalize goals, event intake and incentives for Maker Party

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#450]
We need decisions around Maker Party event goals, including what information we want to collect, how we'll collect it, and what incentives we can offer. I'll set up a kick-off call ASAP.

cc @amirad @HPaulJohnson @adamlofting @chrislarry33 @OpenMatt @hannahkane

**Comment by ldecoursy** [comment]
Re: Goals - We’re not setting specific goals for # of events this year due to the fact that the new Maker Party strategy is in service of reaching our goals for # of clubs and # of cities. Given that it is a two-week campaign, it would be difficult to draw YOY comparisons. 

What’s important to us this year, regarding MP and in general, is having a way to know who is interested, where they are, what they’re most interested in, and how we can build and track relationships with them. Also important, is honing our CTA and messaging around this as an established campaign to activate people as a first step. We’re currently finalizing a more general intake form for teach.mozilla.org that will help us know this information, as part of a “Join Us” CTA. 

We can work with @adamlofting to analyze how the information we collect helps us address the idea that Maker Party as a campaign can help us seed clubs. 

PS I did check in with legal about contest/sweepstakes incentives as an option, and they’re not. Lotteries are illegal, sweepstakes are too problematic, and contests have skill requirements (not just for data collection) and would have to exclude several countries.

**Comment by amirad** [comment]
Great! Thanks for the update Lainie. We can look further into digital certificates as incentives.
