### ISSUE TITLE
Privacy module prepared for testing

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/plan#452]
In progress in the Learning repo: https://github.com/mozilla/teach.webmaker.org/issues?utf8=%E2%9C%93&q=is%3Aopen+privacy

**Comment by OpenMatt** [comment]
* includes 6 45-minute activities. will be packaged into Clubs format and tested w. key partners (EFF + others)

**Comment by LauraHilliger** [comment]
content is packaged, testing running parallel. See https://github.com/mozilla/teach.webmaker.org/issues/838
