### ISSUE TITLE
Address id.webmaker.org bugs

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#454]
Milestone:
https://github.com/mozilla/id.webmaker.org/milestones/QA

RACI
Driver: @thisandagain
Dev: TBD @simonwex 
Quality: @simonwex

**Comment by OpenMatt** [comment]
@secretrobotron status?

**Comment by secretrobotron** [comment]
Made a bunch of progress last heartbeat on tracking down elusive bugs, monitoring, and producing a design for lost usernames. Need to implement in this heartbeat.

Will leave needs-* labels on here to discuss in tps.

**Comment by thisandagain** [comment]
@secretrobotron @simonwex Status?

**Comment by OpenMatt** [comment]
status update?

**Comment by OpenMatt** [comment]
@thisandagain will follow up with @simonwex on a few loose threads here

**Comment by simonwex** [comment]
It looks like we just need to get this work assigned and prioritized.

**Comment by OpenMatt** [comment]
@simonwex : this one is slipping due to resource constraints. need to understand how this is impacting users. may need to resched to post beta release.

**Comment by OpenMatt** [comment]
can we close this?

**Comment by secretrobotron** [comment]
There are more bugs that were filed within the past few weeks: https://github.com/mozilla/id.webmaker.org/issues

Need to make sure those still get addressed somehow.
