### ISSUE TITLE
MoFo Hosted Donation Pages (+ new payment processor)

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#455]
Re-scoping this ticket:

* Move the front-end hosting of our donations forms to a MoFo owned environment
* Get code into a repo to manage this in a MoFo best practices way
* Make consistent with the rest of our engineering best practices
* Setup testing and deployment workflow
* Switch out current Credit Card processing for new provider (TBC, maybe Stripe)

### Audience
Donors who use our pages, Engineers who build our pages, Fundraisers who test and iterate on the design of our pages.

### Success
- Sec review and vendor review completed for our new setup
- New pages are live
- Switch all fundraising traffic to new version of the forms

### Roles
 * Driver: @adamlofting
 * Decision Maker: @adamlofting
 * Development Lead: @ScottDowne 
 * Quality Verifier: @simonwex

**Comment by OpenMatt** [comment]
* Adam and Erika to connect re: Scott's allocation

**Comment by adamlofting** [comment]
We're moving this task to the next heartbeat until we can clone @ScottDowne

**Comment by ScottDowne** [comment]
@adamlofting You mind filing a ticket to clone me?

Pretty sure the solution looks something like this:
![calvin-and-hobbes-duplicator](https://cloud.githubusercontent.com/assets/197334/7592588/2bbda8c4-f8a2-11e4-90dc-c384941b0fc9.jpg)

**Comment by adamlofting** [comment]
I've re-scoped this ticket as we have a specific project to start on in the next heartbeat.

The goal is to move the fundraising forms, and developer workflow off of BSD and into an environment we own: See [EOY Tech planning](https://docs.google.com/presentation/d/1XbjA8X9GgBTGgdiCcrOnN7T-6pVFQUsYcwoGJu4Qa44/edit#slide=id.p)

We should also dig out the etherpad we wrote at the end of EOY reviewing the things we want to make better this year. This is our chance to make those things better.

**Comment by adamlofting** [comment]
After chatting with @edrushka and @valianttry today, there will be a number of other engagement tasks needed in the June 5 heartbeat, so we're going to push this ticket to June 19.

Before that starts though, I will meet with @ScottDowne to talk through the project, and I'll work on the Stripe Vendor review so that we're ready to implement. 

Let's think about shipping this as a Whistler project.

**Comment by simonwex** [comment]
Thanks for championing this, @adamlofting. I feel so much better about the life, the universe and everything now.

**Comment by ScottDowne** [comment]
This was my stripe test: https://github.com/ScottDowne/donation-form-stripe

**Comment by adamlofting** [comment]
Met with @alicoding, @jbuck and @ScottDowne to talk this through.

For this heartbeat we will:
- Setup a fresh repo to manage the code
- Setup a staging environment
- Setup a dev workflow to build the HTML and minify JS and CSS files
- Copy existing sequential form, and thank-you page(s) into the new repo
- Improve the code for those forms as required
- Switch to React.js where appropriate
- Setup localization in the repo, rather than copy pasting content
- Decide what needs static versus dynamic hosting based on which Stripe API we use
- Have the email opt-in page hosted on the new system, but it will still talk to BSD to store the subscriptions
- Work on improving page load times globally (CDN etc)
- Switch to the PayPal transaction flow where 100% of donors get routed back to the thank you page to improve analytics
- Copy the coinbase donation page into new system
- Copy the 'static' [currency pages](https://wiki.mozilla.org/Ways_to_Give#PayPal) into the new system
- Decide how we want to do automated testing

We think this can be done in two weeks as a P1.

After this heartbeat, the remaining tasks will be:
- Vendor review for Stripe
- Sec review for new pages
- Setup prod hosting, domain, SSL
- Redirect existing donation pages in a soft roll-out

**Comment by jbuck** [comment]
Filed a [RRA](https://bugzilla.mozilla.org/show_bug.cgi?id=1170623)

**Comment by adamlofting** [comment]
@ScottDowne and @alicoding - FYI this is confirmed for the next heartbeat (starting on Monday).
