### ISSUE TITLE
review platform for advocacy site

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/plan#457]
Currently the site is hosting on Wordpress Platform which is not ideal in our use case or specifically for this site since we are not really doing any dynamic content or anything that Wordpress meant to be.

### Audience
Developers who need to work on this site in general always having a hard time working on this project or any project on Wordpress because local development really takes much time and not always easy to get it run the exact same as production site (content)

### Success
Should be easy to develop/update the site without having to go under Wordpress development restriction or knowing PHP to develop stuff for our simple need which could just be static site.

### Vision
Should be a static page which will make it easy to develop and run locally easily.

### Roles
 * Phase: discussion
 * Driver: @edrushka
 * Consulted: @simonwex, @davidascher @alicoding

**Comment by edrushka** [comment]
Some context for this ticket: we are about to make some [significant changes] (https://docs.google.com/document/d/11NKbq1qWijHBZh2JDFq-KtbGINj0QAhJwdsfkUSK-xs/edit) to the [advocacy site] (https://advocacy.mozilla.org/). @davidascher @simonwex curious as to your thoughts on switching to static HTML, as we decided to do with the MozFest site.

**Comment by davidascher** [comment]
We should in general use the same stack for all our sites. That's the point
of mofo-style.  Exceptions may be needed, as in sites that need a lot of
author-delegated authoring systems (aka blogs).  Haven't had a chance to
look at the attachments, sorry.

**Comment by edrushka** [comment]
@simonwex any chance you could look at the current advocacy site and help estimate how much time it would take to recreate that in static HTML. Are we talking 2 days, or 2 weeks?

**Comment by alicoding** [comment]
So, I just look through the site myself and I don't see any thing that looks complicated nor we have anything that would takes up time to do at all. I suspect this shouldn't take any longer than 2 days to do the exact same thing using plain static HTML template since all the CSS and layout it's been done on Wordpress site and all we have to do here is copy paste and make sure we host everything ourselves and create a script for deployment and call it a day :dancers:

**Comment by edrushka** [comment]
Well that seems doable! Let's discuss this with the advocacy team when we meet on Friday. We'll leave this ticket open for now in case Wex or David have any further advice or suggestions.

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!
