### ISSUE TITLE
Develop Webmaker Launch Playbook cont'd

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#460]
**Goal**: Continue work last heartbeat's work on developing a playbook for launching Webmaker, including content, marketing, community, QA, and partnerships.

ToDos:
- [ ] get feedback on first draft and finish it
- [ ] finalize launch schedule
- [ ] start contacting community by making playbook [plan] part of upcoming events

### RACI
Phase: Design
Driver: @secretrobotron
Decision: @HPaulJohnson 
Consulted: @thisandagain, @adamlofting, @benrito, @cecilepompei, @LauraReynal, @chrislarry33, @amirad @xmatthewx 
Quality: @davidascher

**Comment by chrislarry33** [comment]
Can we have learning network team/clubs person in consulted to stay connected as aspects of this work start to interject, how about me and Amira?

**Comment by secretrobotron** [comment]
:+1:

**Comment by thisandagain** [comment]
Toronto team meetup scheduled for next week where this work should be wrapped-up.

**Comment by OpenMatt** [comment]
status?

**Comment by secretrobotron** [comment]
This is *well* underway. @LauraReynal is in BD right now, executing :).
