### ISSUE TITLE
Conduct vendor review of Credly

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#461]
Legal ticket here: https://bugzilla.mozilla.org/show_bug.cgi?id=1159064

**Comment by OpenMatt** [comment]
Note: there's some questions from @toolness  re: authentication experience.

**Comment by simonwex** [comment]
Legal review still in-progress, security ticket here: https://bugzilla.mozilla.org/show_bug.cgi?id=1165123

**Comment by simonwex** [comment]
Bumping to next milestone so this remains on my desk.

**Comment by simonwex** [comment]
Review completed, +1 from opsec.

**Comment by simonwex** [comment]
also +1 from legal
