### ISSUE TITLE
Publish fact sheet for "What is a Mozilla Club"

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/plan#463]
To be used in updates to teach.mo.org site and in recruiting more clubs. 

In progress: https://docs.google.com/document/d/19yk3ZW1Mtjf3oUwspCiXPeNJ_zD63UYGpfEn3BdNxS0/edit#

**Comment by ldecoursy** [comment]
Posted here: http://mozilla.github.io/learning-networks/clubs/

**Comment by OpenMatt** [comment]
Done?

**Comment by ldecoursy** [comment]
Yes, closing now!
