### ISSUE TITLE
Redesign advocacy.mozilla.org

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#464]
This is the meta-ticket for the redesign of the Advocacy site: https://advocacy.mozilla.org/

Individual tickets will be tracked in [/movement building] (https://github.com/MozillaFoundation/movement-building)

Driver: @edrushka
Design lead: @lovegushwa 
Design QA: @cassiemc 
Dev lead: @alicoding 
Decision-maker: @DaveSteer 
Consulted: @Melechuga @valianttry 

- [ ] Kickoff
- [ ] ~~Brand~~ Asset audit 
- [ ] User research (?)
- [ ] Initial wireframes
- [ ] UX design
- [ ] UI design
- [ ] Final design QA
- [ ] Design complete! Ready to build!

**Comment by cassiemc** [comment]
@edrushka Great ticket, excited about kicking off this work! I'm wondering which pieces of this you're hoping to have complete by June 5? Also, what are you thinking is the deliverable for the brand audit, and what is the question around user research? The scope of things has me wondering if we want another UX resource here but that depends a lot on timelines. Maybe we can discuss on Monday or later today.

**Comment by edrushka** [comment]
I'd say Kickoff and Brand Audit by June 5.

For Brand Audit, I'm simply thinking of reviewing the assets we already have in place (logos and icons, forms etc.). Perhaps a better term would be "asset audit" ;) @lovegushwa and I already have plans to walk through this together.

I hope to pose the question about user research when we have the kickoff meeting. It remains to be seen how the larger advocacy team envisions the site as a hub for our advocacy activities. If we want to make the site a more active place, we likely want to find out what the community would like to do there.

There is no firm deadline on this project, and no urgency at the moment, so for now I don't think we need more UX horsepower. Let's discuss, though, in case you feel otherwise.

**Comment by OpenMatt** [comment]
* Let's ensure we understand the motivation / resource allocation here and have consensus around priority before we start work. 
* Next step: get buy-in from Ops before proceeding.

**Comment by DaveSteer** [comment]
@OpenMatt Makes sense to get Ops buy-in. Is it best for @valianttry and I to present this at an upcoming ops meeting? If so, what's the best way to get on the agenda? ( @davidascher - perhaps you can guide us on the best format).

I think we'll still need a call/planning in advance so that we can get a sense of the # of resources needed for this project as part of the recommendation to Ops. But we can keep this to 'scoping' vs. 'building'.

--Dave

**Comment by davidascher** [comment]
@davesteer -- my recommendation is to come to ops with a
distributed-previous-to-the-meeting 2-3 page document articulating the
goal, the targets, the resources needed, and the timelines, and a specific
set of questions you need answered.  We will read the document before the
meeting, and then can use the meeting to discuss the details of the goals
(e.g. are the targets you set the right ones, ambitous enough, connected
enough to other things, etc) and we are more likely to get to a stronger
statement around "yes, we agree, this is the right plan,and this
schedule/resource allocation makes sense.

Happy to help outline that doc if useful.

**Comment by DaveSteer** [comment]
Very helpful @davidascher. The doc will start from the baseline we set with the Mozilla Advocacy program review. We plan to have a few meetings with the team to get a better understanding of the scope/resources required/timeline to inform the document which we share with ops. More on this soon.

--Dave

**Comment by OpenMatt** [comment]
* Sounds like we agree that the next step is to write up a project brief. To be presented to Ops. @DaveSteer and @valianttry: can you produce that this Heartbeat?
* I know @valianttry has talked w. @DaveSteer about scope here -- want to ensure her thinking gets captured in the project brief.
* Main thing the brief should stress: return on investment. This site currently doesn't get much traffic. And as far as I know, we don't have plans to push a lot of traffic at it. (vs.: pointing at petition / campaign pages, for example)

**Comment by edrushka** [comment]
Update: 
Dave is working on a Creative Brief to present to ops.
Dave, Andrea and I have met with Jen Bertch to discuss how re-design of Moz.org may (or may not) include the update of Advocacy.

I am going to close this ticket for now until we clarify the plan with MoCo and will file granular tickets as needed.
