### ISSUE TITLE
Add deprecation message to Popcorn tool page

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/plan#465]
Let's update https://popcorn.webmaker.org with a banner message/link noting upcoming deprecation.

Copy: "Mozilla's tools for teaching the Web are evolving. Beginning June 19, you will not be able to create or edit Popcorn Maker projects. To learn more, read our blog post [http://mzl.la/1ACom34]."

Driver: @kevzawacki
Dev lead: TBD @simonwex 
Consulted: @HPaulJohnson

**Comment by OpenMatt** [comment]
status?

**Comment by thisandagain** [comment]
Ran out of time to get this done. Moving to the next heartbeat.

**Comment by secretrobotron** [comment]
Related: https://github.com/mozilla-appmaker/appmaker/issues/2412

**Comment by OpenMatt** [comment]
@simonwex to assign a dev -- rolling up these deprecation related tickets into one larger ball of work.

**Comment by simonwex** [comment]
This is something that fell through the cracks this HB. I've bumped the milestone to make sure it's reviewed again. I'll work on scheduling and assigning this work today.

**Comment by OpenMatt** [comment]
@KevZawacki status?

**Comment by OpenMatt** [comment]
* PTO is making this one a challenge this week. @secretrobotron : can you try to tap a dev to implement?

**Comment by secretrobotron** [comment]
@errietta is going to try to help us out here. Working with her now.

**Comment by KevZawacki** [comment]
We've been receiving lots of queries on Twitter/help-webmaker@ about Popcorn's issues with YouTube links. This banner can help allay some of that confusion.

When we implement the banner, we'll want different copy than above. Likely:

"Our tools for teaching the Web are evolving. Moving forward, Mozilla will no longer provide support for Popcorn Maker. To learn more, read our blog post [http://mzl.la/1ACom34]." 

(Blog post has some out-of-date info in it — we're updating that now.)

**Comment by secretrobotron** [comment]
@errietta ^^ (https://github.com/MozillaFoundation/plan/issues/465#issuecomment-119734381)

**Comment by errietta** [comment]
@secretrobotron will do, i guess the same message goes to appmaker?

**Comment by secretrobotron** [comment]
:+1: @errietta that's right: https://github.com/mozilla-appmaker/appmaker/issues/2412

**Comment by errietta** [comment]
Please 2 ARRR-QUESTIONMARK @secretrobotron  https://github.com/mozilla/popcorn.webmaker.org/pull/618

**Comment by secretrobotron** [comment]
Thanks @errietta :shaved_ice:
