### ISSUE TITLE
Prepare Bangladesh Participation Meet - up material 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#466]
Goal: Having some material ready for the Bangladesh meet-up to tell the Webmaker + Club story
Timeline: by June 4th 
Meetup dates: June 5-6 

--

Driver : @hpauljohnson 
Team involved: @secretrobotron @amirad 

-- 

1 .   Presentation 

- Tell our story : Mozilla Foundation // Learning = Webmaker + Clubs + Community
- What is Webmaker ? 
 - Vision 
 - Demo 
- What is clubs 
 - Vision 
 - Demo ? 
- Call to action for Bangladesh ? What are we looking for + Why its interesting for you?

2 .  Workshop material 
- needs GTM templates for people to fill out 
- Isolate the roles and have the role desc ready printed on a 1 pager
 {Outcome of the workshop 
* 4 people part of the GTM team 
* Campaign outline 
* Scheduled meeting with team }

**Comment by OpenMatt** [comment]
old ticket -- closing
