### ISSUE TITLE
build donor processing systems between Finance and Fundraising

### ISSUE THREAD

**Issue by RebsD** [MozillaFoundation/plan#467]
Currently, there's limited integration between donation processing, receipting, and gift acknowledgment, from any of the MoFo offices worldwide and our Fundraising department in Toronto (except, of course, for instit grants and small dollar). We need to build systems to be able to serve our donors better, and make reporting easy for both Finance and Fundraising at MoFo, and also how it integrates with CRM. 

Driver: @RebsD
Consulted: Pamela Hewitt, Angela P., @valianttry, @adamlofting, @davidascher

**Comment by OpenMatt** [comment]
* @RebsD is meting w. Ops now to discuss next steps.

**Comment by OpenMatt** [comment]
@edrushka where did this one end up?

**Comment by adamlofting** [comment]
Ops and Fundraising met in Whistler and kicked off conversations.

IIRC the next step is to document the experience we want for a donor (e.g. who receives what kind of thank-you and when, and then review the existing systems to see what work we need to do).

Given the focus on 2-week tickets for this heartbeat process I think this will end up being broken down into smaller tasks and we can close this ticket, but I'll wait until @edrushka is back to confirm.

**Comment by edrushka** [comment]
Step one is to identify where money comes in, and what happens to money from each source. That ticket is here: https://github.com/MozillaFoundation/2015-fundraising/issues/8
