### ISSUE TITLE
MoFo plans and prep for Whistler Work Week

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#468]
Driver: @openmatt
Next step: email from Angela to all-mofo (this week). With more detailed instructions re: themes, scheduling, etc.

**Comment by edrushka** [comment]
@OpenMatt is this where we should list what we hope to accomplish at Whistler? Or is there already a place for that?

**Comment by OpenMatt** [comment]
* initial version shipped here: http://mzl.la/whistler
* follow-up around scheduling coming in a new ticket
