### ISSUE TITLE
Get clear about our overall localization strategy

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#469]
This arose in our Heartbeat planning call today -- need to ensure we step back and get clear on our overall l10n strategy, which is becoming more urgent.

## Roles
PM: @secretrobotron 
Decision-maker: @davidascher 
Stakeholders: @thisandagain , @simonwex  (+ @toolness , @hannahkane ), @xmatthewx 

## Short-term urgency:
* High quality l10n for product launches (inc: sample project content & marketing collateral)

(Some context / previous thinking done for teach site: https://github.com/mozilla/teach.webmaker.org/issues/916)

**Comment by OpenMatt** [comment]
@secretrobotron : assigning to you as PM -- can you take next steps from here? Including I assume: scheduling a kick-off?

**Comment by secretrobotron** [comment]
:+1: 

- Good set of recommendations and followup from @k88hudson here: https://github.com/mozilla/webmaker-android/issues/1599#issuecomment-103712914
- We need a string freeze on Friday (for Webmaker cc @xmatthewx)
- Need to make development of this stuff a priority this week (and next cc @simonwex)
- Bugs filed for Webmaker:
  - Desktop: https://github.com/mozilla/webmaker-desktop/issues/66
  - Mobile: https://github.com/mozilla/webmaker-android/issues/2002
- Localization QA is part of launch team for Webmaker (i.e. a team of people that checks and corrects)
  - Will augment Transifex

@hannahkane let's make sure we chat this week.

**Comment by OpenMatt** [comment]
Thanks Bobby! Just to note: I believe the main urgency here, from @davidascher and @thisandagain's perspective, was more on the Product launch side than on the Learning Networks / teach.moz.org side. (So, digging into that piece is probably more of a priority than you connecting with @hannahkane). Will leave it with David and Andrew for any follow-up here, beyond what Bobby has listed above.

**Comment by thisandagain** [comment]
Recap from 1:1 w/ Bobby:
- Bobby to file outstanding implementation tickets within the [webmaker-android](https://github.com/mozilla/webmaker-android) repo. This will be to break down the strategy defined in https://github.com/mozilla/webmaker-android/issues/1599
- @davidascher @simonwex @secretrobotron and I to meet tomorrow to iron out expectations and review gaps.

**Comment by OpenMatt** [comment]
* any status update on this one? 
* cc @hannahkane @ldecoursy , as we talked about a related goal for Whistler: clarity on our l10n plan for all MoFo (including teach.moz.org) etc. going forward

**Comment by OpenMatt** [comment]
* initial urgnency around Webmaker app launch has been curbed
* still need longer-term plan -- will dig in at Whistler
* (@secretrobotron : does that mean we can close this one?)

**Comment by secretrobotron** [comment]
@OpenMatt i think so. Can you just link Whistler planning here before we do?

**Comment by OpenMatt** [comment]
http://mzl.la/whistler

**Comment by simonwex** [comment]
@secretrobotron let's plan a session and invite these folk:

* George Roter
* Lucy Harris ( @LucyeoH )
* Pierros Papadeas
* Francesco Lodolo - Localization Engineer 
* Ahmed Nefzaoui - Contributor for RTL
* Rami Khader - Contributor for RTL
* @alicoding 

Here are a few times we can meet:
https://sunrise.am/m/jKtlPB8V5i

**Comment by OpenMatt** [comment]
Cool. You guys can just add your session to the schedule here when you're decided:
http://mzl.la/whistler_schedule

**Comment by hannahkane** [comment]
Closing this ticket, which is Webmaker-centric. Localization effort lives on, though!
