### ISSUE TITLE
Webmaker - 1.0.1

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#472]
Final stretch toward Webmaker launch. 

Release – http://mzl.la/webmaker-release
Nightly – http://mzl.la/webmaker-nightly

Focus of this heartbeat:
 - squash bugs
 - stabilize features
 - localize
 - prep Webmaker.org for launch

### RACI

Driver: @secretrobotron, @xmatthewx
Decision: @thisandagain
Design: @flukeout @vazquez 
Dev: @gvn, @Pomax, @k88hudson
Services: @cadecairos 
Metrics:  @adamlofting 

Roadmap: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1ZvdNJLHuW0fIBt_-WcR7Ns6OhZgaMy6MI9kfjlXF-9o/edit#gid=0

Beta release tracked in #445

**Comment by OpenMatt** [comment]
* This will also require some co-ordination with teach.moz.org team for re-directs and deprecation @hannahkane @ldecoursy

**Comment by thisandagain** [comment]
Shipping release to Google Play today (in prep for Whistler demo) but keeping this open to track the remainder of work needed for the marketing launch.

**Comment by xmatthewx** [comment]
Play store release: https://play.google.com/store/apps/details?id=org.mozilla.webmaker&hl=en

Work continues in #488
