### ISSUE TITLE
Webmaker marketing assets

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#474]
Webmaker requires a suite of assets designed for marketing. These include digital, print, email, video, schwag. 

Big list linked below identifies priorities and items that should be done in-house to set the tone and style. Producing the remaining items will likely require an external consultant.

All this work is happening in the Launch milestone in the Webmaker-launch repo. Link: https://github.com/mozilla/webmaker-launch/milestones/Launch

### RACI

Driver: @HPaulJohnson
Decision: @HPaulJohnson
Design: @lovegushwa and @jaykappa
QA: @cassiemc
consulted:  @secretrobotron @xmatthewx
 
*On PTO: @thisandagain @edrushka*
Original list of assets here: https://etherpad.mozilla.org/webmaker-marketing-deliverables

**Comment by OpenMatt** [comment]
* Notes from today: Jordan may be free to tackle much of this. Or: contractor. (And there's budget for this)
* Kick-off needed: @edrushka @cassiemc @secretrobotron @xmatthewx @HPaulJohnson

**Comment by cassiemc** [comment]
All this work is happening in the ```Launch``` milestone in the Webmaker-launch repo. Link: https://github.com/mozilla/webmaker-launch/milestones/Launch

Have updated the raci since @edrushka is on PTO this week, please correct if wrong! @HPaulJohnson

**Comment by OpenMatt** [comment]
@HPaulJohnson status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by HPaulJohnson** [comment]
We are in great shape with all the P1's complete and a few final P2's close to completion in the next few days. 

Outstanding items include (all in process): payment processing for printed assets and schwag, email template, and video.

**Comment by hannahkane** [comment]
Can we close this ticket?

**Comment by xmatthewx** [comment]
oh yes. closing.
