### ISSUE TITLE
UI/UX for Thimble landing page/gallery

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#477]
Next phase of Thimble UI/UX project.

Focus of this heartbeat:
 * Design a Thimble landing page that provides context for new users
 * Landing page will prominently feature galleries - both public and personal
 * Design solution for navigating between landing page and project editor

We'll also be building prototypes of the work that was done in the previous heartbeat (project navigation and publishing flow) so that we can test with users.

**Comment by cassiemc** [comment]
This is all @flukeout :)

**Comment by flukeout** [comment]
@hannahkane I've added a ticket to track this with more detail in the thimble repo...
https://github.com/mozilla/thimble.webmaker.org/issues/555

**Comment by simonwex** [comment]
@hannahkane will move on this by end of day, likely moving to next HB.

**Comment by hannahkane** [comment]
We got a good start on this this heartbeat, but we'll need to finish up next heartbeat.

**Comment by hannahkane** [comment]
Very close to finished, but moving to next heartbeat to completely finalize.

**Comment by OpenMatt** [comment]
There's still some question about @flukeout's allocation this heartbeat -- @cassiemc will update here.

**Comment by OpenMatt** [comment]
@hannahkane : @cassiemc says @flukeout is good to go.

**Comment by hannahkane** [comment]
UX is done for this, though implementation is still needed.
