### ISSUE TITLE
Update Webmaker style guide on assets.mozilla.org

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#480]
Fledgling list of properties: https://github.com/mozilla/webmaker-launch/issues/38

Driver: @xmatthewx

**Comment by simonwex** [comment]
Assigning to @xmatthewx. @xmatthewx, let us know if you need any additional resources here.

**Comment by xmatthewx** [comment]
Nope. No progress here. Wait, yes. Just made some last minute progress. Proof of it here: https://github.com/mozilla/webmaker-launch/issues/38#issuecomment-118897136

Moving to next heartbeat to continue.

**Comment by OpenMatt** [comment]
* some of this could be included into updated style guide, design debt, etc.

**Comment by xmatthewx** [comment]
@lovegushwa @KevZawacki - I'd welcome your help driving this. We have a good list and a handful of specific bugs filed to get it all done.

**Comment by KevZawacki** [comment]
Gladly. How can I best help? Filing bugs for P2 and beyond? 

https://docs.google.com/spreadsheets/d/19v3SW-oX68t4R8uZ9NMkRS36beyKAXIzHS0d3zgU26I/edit#gid=0

**Comment by lovegushwa** [comment]
I can help, let me get these print assets out and then we can maybe talk though it over Vidyo @xmatthewx 

cc @KevZawacki

**Comment by xmatthewx** [comment]
Great. Yes. The trick is to file each item in a meaningful place, cc'ing someone who can help make it happen. It's obvious for some items, not for others. 

After you file something, add it to the checklist here: https://github.com/mozilla/webmaker-launch/issues/38#issuecomment-118897136. We can revisit the list next week. I'll be on PTO Monday and Tuesday.

**Comment by cassiemc** [comment]
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1159016 we do need to ensure that the old webmaker favicon is updated on all pages. Would be awesome if this could happen asap, legal requested it over a month ago. cc @xmatthewx @secretrobotron

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Logo has been updated across p1 and many p2 locations. The notable exception is mozilla assets and style guide. As a branding/MoCo task, it probably deserves a planning ticket of its own under @cassiemc's wing. Let's discuss.

**Comment by cassiemc** [comment]
Am quite happy to drive this after I'm back from PTO. I defer to @HPaulJohnson if he wants to drive though, as he has with other branding stuff. Sounds like it's Moco properties so Paul may be the better contact here.

(FYI the Bugzilla thing above is resolved)

**Comment by hannahkane** [comment]
Is this ticket closeable?

**Comment by OpenMatt** [comment]
status?

**Comment by cassiemc** [comment]
@xmatthewx This will require help from @vazquez to sort out. @lovegushwa should be consulted. Reassigning.

**Comment by OpenMatt** [comment]
@xmatthewx can you close or push to a different milestone

**Comment by OpenMatt** [comment]
@xmatthewx will check in with @cassiemc on next steps / whether still needed

**Comment by xmatthewx** [comment]
@cassiemc @lovegushwa - do you know who in MoCo has access to make updates on assets.mozilla.org? This should be a quick task, but I don't know who holds the keys.

**Comment by vazquez** [comment]
Ty Flanagan has access to assets.mozilla.org. What are we looking to change again? We just updated the logos: https://assets.mozilla.org/portal/assets/#category/29

**Comment by xmatthewx** [comment]
Excellent. Thanks @vazquez! I just saw that files were updated. If we update the logo on the landing page too, we should be good to go. https://assets.mozilla.org/portal/assets/#category/16

**Comment by xmatthewx** [comment]
Closing. Tracking the very last bit here: https://github.com/mozilla/webmaker-core/issues/912
