### ISSUE TITLE
Open Web Fellows 2016 Recruitment

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#483]
Design and build 2 updates to use the advocacy.mozilla.org/open-web-fellows page as a recruiting tool, first for host organizations, and later for fellows.

### Audience
Civil society organizations and Fellows candidates.

### Success
Recruit 10s of international civil society organizations to become hosts for our 2016 Open Web Fellows, and later recruit 440 quality applicants for the Open Web Fellows candidate pool.

### Vision
Recruiting Host Organizations: Aug 3 - Sept. 11
We want to put out an open call for host organizations to apply on our site during the above 6 weeks. This would require a page with information regarding responsibilities, and an application form.

Recruiting 2016 OWF Fellows: Oct. 19 - Jan 17, 2016
Once the host organization decisions are made (Sept. 30), we'll need to update the OWF program page with information regarding the 2016 host organizations' projects, upload a recruitment video (plus the FAQ and Benefits page), and have a new application form for the Fellows. 

I think design can be the same for both host organization and Fellows recruitment; content would of course be different. 

I've spoken to Simon Wex about this process; he has offered to advise on best PM-ing strategies, and help delegate the work.

### Measurement
Numbers of applicants to both open calls. Adam will consult regarding the metrics tools to use to capture data for future story telling and recruitment.

### Roles
 * Phase: 
 * Driver: 
 * Decision Maker: @Melechuga
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by OpenMatt** [comment]
@Melechuga: I want to make sure we're clear on the specific deliverables you need this month. 

## Deliverable
* *Create a new "become a host organization" page.* The page will contain some copy and an application form. We'll link to the page in outreach to potential partner organizations. It can be something like: "https://advocacy.mozilla.org/organizations"
* *Deadline: Aug 3.* This page needs to be ready for an open call that launches Aug 3. That means it will need to ship either this heartbeat (July 17) or next (July 31).
* The other deliverables are not due until late September / early October. And they are mostly light page updates and content. So we don't have to worry about them too much right now. 

@Melechuga: Have I got this right?

**Comment by OpenMatt** [comment]
@Melechuga : do you have preferences on how you want the form to work? I'm working if a Google Form or Wordpress add-on would work, passing the data to you in a spreadsheet or via email. Given the small number of applicants, would that work?

**Comment by Melechuga** [comment]
Thanks @OpenMatt! I'm adding @adamlofting onto this so he can advise about the form/data collection format.

**Comment by OpenMatt** [comment]
@alicoding : can you show @Melechuga how to create her own draft page on the advocacy site?

**Comment by alicoding** [comment]
@Melechuga @OpenMatt we no longer use Wordpress for Advocacy site, so to create draft you can simply follow the following steps:

1. Fork the repo https://github.com/mozilla/advocacy.mozilla.org/
2. Clone the repo to your local machine if you are using Mac then you might want to use this https://mac.github.com/ otherwise you can use command line to do so.
3. Copy one of the page structure for example: (Open Web Fellows page)[https://github.com/mozilla/advocacy.mozilla.org/tree/gh-pages/open-web-fellows] then you will have a template to create your draft and view them on your local machine.
4. Once you have your draft completed you can push it to your forked version on github to share link for someone to review.
5. After it has been review you can make a pull request for code review to merge it on production if you want to do that.

I'm happy to go through with you in details. Please note that this process will be easier once you have step 1 & 2 done and believe me it is actually easier than you might think :P

**Comment by OpenMatt** [comment]
@HPaulJohnson @valianttry @KevZawacki FYI re: process for updating advocacy site, above.

**Comment by Melechuga** [comment]
@alicoding Thanks! I got steps 1 & 2 done, no problem, but am slightly confused by the UI of github for mac. I've built a page using a different editor, but am not sure how to integrate it; do you think you have time for a quick tutorial some time next week? Would really appreciate it!

**Comment by alicoding** [comment]
For sure! Send me an invite on Google calendar the time you're free and I'm
happy to go through with you step by step :D

**Comment by adamlofting** [comment]
Though we have a longer deadline for the fellow application form, I'd like to get @Melechuga @kaythaney and @sinker (or someone from each team) together to talk about what the consistent needs are for the fellows application forms across teams. 

(in the Whistler spirit of *let's not all keep building new versions of the same thing*).

This can probably fall into the 'CRM' category of work.

**Comment by OpenMatt** [comment]
@adamlofting sounds good.
@Melechuga and @alicoding : were you able to meet and get Melissa to a place where she can edit pages easily?

**Comment by OpenMatt** [comment]
@Melechuga may have requirements that require more dev support. But we also need to ensure that simple page edits can be made by non-technical staff easily. Let's start with that. 
@edrushka : can you take over PM-ing this ticket now that you're back from PTO?

**Comment by edrushka** [comment]
Apologies, but I don't have the capacity to PM this at the moment.

**Comment by OpenMatt** [comment]
@adamlofting : any update on how you want us to set up the form?

**Comment by OpenMatt** [comment]
* Prototype version of the page: https://melechuga.github.io/advocacy.mozilla.org/2016-host-organization-application/

**Comment by OpenMatt** [comment]
@alicoding: to do's for you (or some other dev)
1. **add a button.** For "Apply Now." (@melechuga will update here with the link to use for the button. it's a simple link -- no form required.)
2. **add blue background.** around "Host Organization Responsibilities" and "Mozilla Responsibilities" 
3. **fix up the bullets.** under 'Specifically, the goals of the Open Web Fellows program are...". Increase the indent.

**Comment by OpenMatt** [comment]
next step: @Melechuga will provide the correct screen door link here.
* Drop dead deadline for these three fixes and pushed to live is: July 30.

**Comment by adamlofting** [comment]
@OpenMatt : If Screen Door works for everyone, that's excellent. I'll take this task off my list :+1: Someone should work through a vendor review if we haven't already though.

**Comment by sinker** [comment]
I believe Simon Wex is already working through the vendor review.

**Comment by Melechuga** [comment]
1) Screendoor link: https://screendoor.dobt.co/mozilla-foundation-2/2016-ford-mozilla-open-web-fellows-host-organization-application . I already gave this to @alicoding, but am including it here for documentation. 

2) Looks like we need a small update on the advocacy.m.o landing page to lead to the host organization application page. I suggest a) getting rid of the Fellows' pictures, b) putting in the dots/vector design that is on the Fellows page (https://advocacy.mozilla.org/open-web-fellows/), c) changing the wording to "Apply to be a 2016 Open Web Fellows Program host organization", d) keep the vector arrow but have it link to the host organization application page. @OpenMatt @alicoding Is that doable? Thank you!

**Comment by Melechuga** [comment]
@alicoding thanks for the live link to https://advocacy.mozilla.org/2016-host-organization-application/. Would it be possible to increase the indent around the bullet points, as per @OpenMatt 's notes in the ticket above? Thank you!

**Comment by alicoding** [comment]
@Melechuga those changes I'm afraid I can't get this done very soon until I get the stuff for Webmaker Android completed.

**Comment by Melechuga** [comment]
Thanks for letting me know @alicoding. @OpenMatt, is there someone else available to do this? There are still a few things we need to get done before pointing people to the site on Monday (Aug. 3):
1. Fix the bullet point alignment (make the indent bigger)
2. Update the landing page (advocacy.m.o) so it points to the application:
    a) remove the Fellows' pictures, 
    b) put in the dots/vector design that is on the Fellows page (https://advocacy.mozilla.org/open-web-fellows/), 
    c) change the wording to "Apply to be a 2016 Open Web Fellows Program host organization", 
    d) keep the vector arrow but have it link to the host organization application page.
3. Navigation/menu: figure out where to put the page under "Open Web Fellows" navigation option.

/cc @brettgaylor

**Comment by OpenMatt** [comment]
@simonwex : given that @alicoding is busy and the deadline for this is Monday, are you able to assign another dev to make these final light changes?

**Comment by brettgaylor** [comment]
Hai!  I might be able to do this if someone can walk me through how the repo is set up.

**Comment by alicoding** [comment]
I have updated all of them except that last point https://github.com/mozilla/advocacy.mozilla.org/pull/24

**Comment by simonwex** [comment]
@brettgaylor I'd be great to enable you to make changes. Once we know what we're doing with the nav menu, I'd be more than happy to help set you up.

**Comment by brettgaylor** [comment]
I think this should be settled by this
https://github.com/mozilla/advocacy.mozilla.org/pull/26

**Comment by hannahkane** [comment]
Is this ticket closeable? (Just trying to clean up past milestones)

**Comment by Melechuga** [comment]
This ticket includes the larger product management milestones needed for recruitment through early 2016. Next steps are:

- Update "Host a Fellow" page to "Apply to be a Fellow" with host organization projects, benefits/FAQ info + application for fellows.

**Comment by OpenMatt** [comment]
@simonwex : needs a dev this Heartbeat for the Oct 9 deliverable
@cassiemc : Nov 6 requires design work

**Comment by cassiemc** [comment]
@Melechuga Is it possible to make this new work a new design ticket with a tighter scope? Finding this one quite sprawling and difficult to get the gist of what needs to be done.

Also a heads-up, we need a completed design brief to start new design work. You can make a copy of the template here if you want to get started, or once a designer is assigned they can also go through it with you (I should know more about @lovegushwa's time after today). Requires about 30 minutes (or less) of your time. https://docs.google.com/a/mozilla.com/document/d/1H4rDTT7zdvOFhGlgMDIuRLlTRlAxMsU_-mUehv_iEZU/edit?usp=sharing

**Comment by brettgaylor** [comment]
Closing in favour of this:

https://github.com/MozillaFoundation/plan/issues/571

**Comment by OpenMatt** [comment]
@brettgaylor I'm closing this one as per your comment
