### ISSUE TITLE
Concept and logistics for Thimble promotional materials

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#485]
Driver: @KevZawacki 
Help to Execute: @ldecoursy @cassiemc @flukeout @hannahkane
Consulted: @humphd @chrislarry33 @HPaulJohnson 

Once we complete the MVP release for the new Thimble, we'll need to tell the story to our community, and generate new interest. This might look like a short video, some shareable assets for social media, and a blog post.

For this heartbeat, the outcome could be:
 * agreement on deliverables
 * agreement on concepts 
 * secure budget
 * secure any additional contract help

See: https://github.com/mozilla/thimble.webmaker.org/issues/643 for more details / brainstorming

**Comment by hannahkane** [comment]
@KevZawacki - is it okay for me to assign this to you?

**Comment by hannahkane** [comment]
@chrislarry33 to provide details on budget and ideas re: contractors

**Comment by KevZawacki** [comment]
Happy to drive!

I've put together a draft comms plan here — please jump in to provide feedback/answer questions: https://goo.gl/NvcEJX

**Comment by chrislarry33** [comment]
@KevZawacki plan looks fantastic. Lets talk/think about video some, but love the plan. Back to school theme/time for sure.

**Comment by hannahkane** [comment]
Scheduling a meeting for this week to put together a marketing/comms plan

**Comment by KevZawacki** [comment]
Latest comms plan here: https://goo.gl/fQ24sX

**Comment by OpenMatt** [comment]
@KevZawacki status?

**Comment by KevZawacki** [comment]
@hannahkane, @HPaulJohnson and I are working on a value prop for the new Thimble. Once we have that squared away (next week), we can start charting a course for promotional materials and comms.

**Comment by hannahkane** [comment]
Moving to July 31 milestone, as per @KevZawacki's comment.

**Comment by hannahkane** [comment]
hey @KevZawacki and @HPaulJohnson - any movement on the value prop or video resourcing conversation?

**Comment by HPaulJohnson** [comment]
@hannahkane - working on value proposition at this very moment. plan to review with @KevZawacki tomorrow and send something your way.

re: video, we are still we've been pretty distracted trying to get the Webmaker videos finished up; when those are in a better place we'll have that conversation with that team.

**Comment by HPaulJohnson** [comment]
Here's a draft version of Thimble value prop. Apologies that it took us a bit longer to get to. We should edit/add/subtract from this and it can help inform key messages and copy for marketing and other public facing promotion of the tool. 

https://etherpad.mozilla.org/thimble-valueprop

**Comment by hannahkane** [comment]
I think this is fantastic. Thanks for putting it together.

**Comment by ldecoursy** [comment]
+1 Left a few suggestions in the pad. Thanks @HPaulJohnson and @KevZawacki :+1:

**Comment by hannahkane** [comment]
Do we need to reconvene to figure out next steps, @KevZawacki @HPaulJohnson @ldecoursy?

**Comment by KevZawacki** [comment]
That'd be great. I'd like to pin down specific dates for the "Timeline and Tactics" section of the comms plan (https://goo.gl/9ZeY7V). Hopefully @cassiemc can join us, too, re: art for social media. 

Maybe a 15-minute meeting on Thursday?

**Comment by hannahkane** [comment]
WFM

**Comment by cassiemc** [comment]
I'll be there!

**Comment by OpenMatt** [comment]
@hannahkane rolling over to next Heartbeat then?

**Comment by hannahkane** [comment]
Or maybe this can be closed in light of #518. @HPaulJohnson ?

**Comment by hannahkane** [comment]
Closing b/c this ticket feels superfluous.
