### ISSUE TITLE
Update build.webmaker.org/design

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#487]
We made a lot of progress in Whistler toward identifying good and bad processes and working out some of those details. Now we need to document that progress in an accessible place, build.webmaker.org/design.

**Design Brief** is here: https://github.com/MozillaFoundation/Mofo-Design-Handbook/issues/21

We are using the [```July-17``` milestone](https://github.com/MozillaFoundation/Mofo-Design-Handbook/milestones/July-17) in the Design-Handbook repo.

Driver: @cassiemc
UI: @cassiemc 
UX: @xmatthewx 
Dev: ? (maybe @cassiemc)
Consulted: @flukeout @sabrinang @lovegushwa @vazquez and PMs as needed

**Comment by cassiemc** [comment]
Update: This is pretty on track as far as bugs we committed to this heartbeat. We will have to implement the design and content in the next heartbeat.

**Comment by OpenMatt** [comment]
@cassiemc move to July 31 milestone?

**Comment by cassiemc** [comment]
Done!

**Comment by OpenMatt** [comment]
@cassiemc status?

**Comment by vazquez** [comment]
Page was designed by @cassiemc and coded by me. It's up on http://build.webmaker.org/design.

Tweaks will need to be made, but I'm comfortable with closing this issue and filing new as needed.

**Comment by cassiemc** [comment]
+1, thanks @vazquez!
