### ISSUE TITLE
Create research plan for MLN site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#489]
Beginning sketch of plan is here: https://etherpad.mozilla.org/teachresearch

Would love input from @LauraReynal and @thisandagain 

Outcomes of heartbeat:
 * Agreed upon plan for research, including timeline and roles

**Comment by OpenMatt** [comment]
@hannahkane I maked this one p2 -- but don't know if that's actually right. please fix as needed.

**Comment by hannahkane** [comment]
sync up with @edrushka around collecting user stories project

**Comment by hannahkane** [comment]
Moving this to July 31 heartbeat, so that we can benefit from @thisandagain and @LauraReynal, who are on PTO.

**Comment by LauraReynal** [comment]
Hey @hannahkane im back from PTO and happy to help. Had a look at the pad - lots of exciting questions :smile: 

I added some comments in salmon pink in the pad, feel free to edit.

A few thoughts / questions:
- I have some existing data from the Chicago research projects with several educators that we talked to, it could be used as a starting point. Happy to go through it with you before we finalize this plan. 
- When is the focus group happening about Web Literacy Map ? How will this focus group be conducted?
https://etherpad.mozilla.org/webliteracy2-0
- When do you want to have the research completed ?

**Comment by hannahkane** [comment]
Thanks, @LauraReynal! Really appreciate the comments/questions.

I want to get some guidance from @chrislarry33 regarding our research plan and timeline. As @anmechung and I talked about, we think many of these research questions can be explored via the Web Lit Map focus groups (@anmechung - can you share the timeline for those?)

@chrislarry33 - wondering if you can help give shape to add'l research we might want to do. 

Should we set up a meeting to discuss the timeline moving forward?

**Comment by anmechung** [comment]
Focus groups to inform WebLit 2.0  begin week of July 20 and will wrap up mid-August.  Some of the questions https://etherpad.mozilla.org/teachresearch can definitely be incorporated into the focus groups, particularly those collecting basic demographic and tech level info. Some of the questions are specific to those already using Mozilla Learning tools and should happen as follow-up.  A good portion of the questions are more about surveying needs. I would suggest two types of data collection is needed: 1) ongoing information important for continuous improvement and 2) data for impact with methodology ranging from  ongoing online surveys and in-person surveys and data collection during meet-ups and/or events.

**Comment by anmechung** [comment]
and ... whatever is data is collected for whatever purpose should align with what the Impact Working Group is planning (yet to be determined)

**Comment by chrislarry33** [comment]
I suggest we maybe hit pause on this until September (Note not the web lit research)

**Comment by anmechung** [comment]
Sounds like a good plan.

**Comment by hannahkane** [comment]
Cool. Removing from milestone, and adding to roadmap for September.
