### ISSUE TITLE
Ship "Feature Complete" Webmaker app

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#49]
In preparation for final QA and refinement prior to MWC, we need to ship a "feature complete" build of Webmaker App by the end of this sprint. Any additional gaps need to be identified and either filled or bypassed by Friday morning on February 13th. Existing UX gaps:

*Edited @k88hudson*
### What we're building
- Integrate app directly with device gallery / camera applications on Android & Firefox OS to allow users to upload image assets directly. Requires work within Cordova (Beaker) and services engineering.
- Application detail view (https://redpen.io/wy5af842444b6a2667)
- Sharing flow (https://redpen.io/fn6bd4b0dbeaf8e985)
- Consumptive ("install") flow & remix (https://redpen.io/tg20fe8562fe6ff39d)

### Important notes
- Since we are demoing on **Android 4.4 and Firefox 2.1** for MWC we will temporarily be suspending the requirement for the app to run on Android 4.2. Note that this is temporary
- Please develop/test on device whenever possible. See http://webmaker-mobile-guide.mofodev.net/_docs/get_started/android.html. However since we are targeting 4.4 for this release,  you can use [Chrome for remote debugging](https://developer.chrome.com/devtools/docs/remote-debugging)
- Andrew and Ricardo are working on a UI sprint in parallel. Ping them if you need design clarification or support

#### https://github.com/mozilla/webmaker-app/milestones/Ship%20Feature%20Complete%20App
*Old milestone was ["Device Integrations"](https://github.com/mozilla/webmaker-app/milestones/!Device%20Integrations)*

### Quality
* Check in next Monday
* QA script being written in parallel

### RACI
Phase: Design / Build / Ship
Owner: @k88hudson
Decision: @thisandagain
Lead design: n/a
Lead dev: @jbuck 
Dev: @gesa 
Dev: @cadecairos 
Quality: @davidascher

**Comment by simonwex** [comment]
Hey @k88hudson, @jbuck is also going to lend a hand with this P2. When he or @Pomax have some bandwidth they'll ping you to schedule a kickoff.

**Comment by davidascher** [comment]
Note: We probably need to also consider something like
https://github.com/jimmynicol/image-resizer to make sure that we don't
serve high-res images to people on low-res (and low/expensive bandwidth
phones).

**Comment by k88hudson** [comment]
@Pomax, @jbuck issues are https://github.com/mozilla/webmaker-app/milestones/Image%20Uploading

**Comment by simonwex** [comment]
@k88hudson do you have an updated list of those issues? ^

**Comment by k88hudson** [comment]
@simonwex yes, it's in the first comment

**Comment by simonwex** [comment]
Groovy, thx.

**Comment by k88hudson** [comment]
We managed to ship an s3 uploader + some basic, first-pass UI + device integration. The upload service is shipped but right now the images are written as base64-encoded data to firebase directly.

We still need to:
* adding s3 upload hook on publish 
* adding compression to FFOS
* some ops follow-up for IRC bot

Will follow up on these myself with @jbuck's help early Monday morning

**Comment by OpenMatt** [comment]
* sounds like this work is ongoing, so updating to Feb13 milestone. please correct if that's wrong.

**Comment by thisandagain** [comment]
Cleaned up the scope a bit to cover the last few UX gaps. @k88hudson can you review and update the milestone / tickets?

**Comment by OpenMatt** [comment]
@simonwex says: may be light on dev resources?

**Comment by k88hudson** [comment]
@thisandagain yep on it

**Comment by thisandagain** [comment]
Will review and confirm with @k88hudson today.

**Comment by thisandagain** [comment]
After talking, we are going to include some Login / Sign-up refinement here, but we feel having a 3rd dev would be best. Updated original comment. 

/cc @simonwex

**Comment by simonwex** [comment]
@cadecairos can help out once #240 is shipped. @alicoding will need to take over #263 as ScottDowne is PTO this week.

**Comment by thisandagain** [comment]
![screen shot 2015-02-13 at 12 38 28 pm](https://cloud.githubusercontent.com/assets/747641/6194896/a202ab0c-b37d-11e4-95a1-8dc26dc8820f.png)
