### ISSUE TITLE
Design new Clubs content and workflows for MLN

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#490]
This is for the next iteration of Clubs content.

Worked being tracked here: mozilla/teach.webmaker.org#1086

**Comment by OpenMatt** [comment]
@hannahkane I marked this one p2 -- but don't know if that's actually right. please fix as needed.

**Comment by thornet** [comment]
count me in!

**Comment by hannahkane** [comment]
Work being tracked here: https://github.com/mozilla/teach.webmaker.org/issues/1086

**Comment by hannahkane** [comment]
Also includes https://github.com/mozilla/teach.webmaker.org/issues/1104

**Comment by OpenMatt** [comment]
status?

**Comment by hannahkane** [comment]
We have tickets for an interim solution in the next heartbeat, so we can close this one.
