### ISSUE TITLE
Create Thimble makes and teaching kits for landing page at launch

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#493]
#### DARCI
Driver: @hannahkane
Accountable: @chrislarry33 
Responsible: @hannahkane
Consulted: MLN team

Tracking in https://github.com/mozilla/thimble.webmaker.org/issues/685

**Comment by hannahkane** [comment]
In progress. Would love feedback from @chrislarry33 @ldecoursy @thornet and others.

**Comment by chrislarry33** [comment]
@hannahkane I am catching up on a lot, what do you need my feedback on?

**Comment by hannahkane** [comment]
Sorry, @chrislarry33, still getting the hang of tracking things in two places. :)

It's this that I'd love feedback on: http://bit.ly/1gr28xo

**Comment by hannahkane** [comment]
Moving this to next heartbeat, since it won't be completed by tomorrow

**Comment by hannahkane** [comment]
Pushing to next heartbeat, since it's dependent on pushing Thimble to production server (see #511)

**Comment by hannahkane** [comment]
First is in progress here: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/28/
Second is here: https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/32/

**Comment by jgmac1106** [comment]
If there was a paper prototype for the comic strip I would think about something like this:
![comic graphic organizer](https://goo.gl/photos/HW27chsaTTaGxDnD9)

This is based on the Take a Stand plan. I left the last square for an author so the selfie feature could be used (saw the selfie mode objective).

My only question would be if we get real explicit (like including bottom caption, top caption, speech) or leave it more open (with no prompts) like I did under "Evidence"

There could also be just a blank six frame storyboard. I just think the default position should be to provide a paper prototype print out for all projects (minus the alliteration).

**Comment by jgmac1106** [comment]
I wonder if we should add a few bullet points in the introduction to CSS
section about external style sheets.

When I asked new users to start a new project (which mean,t all had
webmaker accounts, went to old Thimble and cut-and-pasted) two people got
stuck  at linking to the CSS file. They knew to cut and paste into separate
HTML and CSS files but almost expected the CSS to be automatically applied.

Maybe something like "There are three ways to style a with CSS: internal,
external, and inline. This project uses external styling which means we
link to another file. Such as, <link rel="stylesheet" type="text/css"
href="style.css">.

I looked for the appropriate page in MDN to link to but I could find one.
Could link to http://www.w3schools.com/css/css_howto.asp or edit
https://developer.mozilla.org/en-US/Learn/CSS/Using_CSS_in_a_web_page. I
think linking tutorials to MDN (even updating if necessary) would make more
sense.

**Comment by hannahkane** [comment]
Great suggestion, @jgmac1106. Will add this.

**Comment by hannahkane** [comment]
Just met with @ldecoursy and @chadsansing, and we have a plan for finishing these up. Win!

**Comment by hannahkane** [comment]
Makes and Teaching Kits are here:

 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/26/ [Keep Calm make]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/28/ [Keep Calm teaching kit]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/40/ [Comic Strip make]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/32/ [Comic Strip teaching kit]
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/61/ [Postcard make] 
 * https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/62/ [Postcard teaching kit]

Still need some polish, but they're in pretty good shape.
