### ISSUE TITLE
Build a fundraising template for user impact stories

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#494]
### Goal
Create a template and system for collecting user stories across MoFo. To support a specific piece of work Fundraising Team needs to get done in Q3: building a case for support, showing the impact we're having on user's lives.

* Next step: for Rebecca's team to draft / document to a template we can ask Program Leads and staff to fill in.  That way, we can ensure the stories we collect are in a format that helps make the case for support.  And that includes the kind of data funders care about.   

### Roles
Decision-maker: @RebsD 
Project Manager: @OpenMatt (while @edrushka is on PTO)
Consulted: @ldecoursy @adamlofting @benrito Bhuvan

**Comment by OpenMatt** [comment]
@RebsD : I can project managed this while @edrushka is on PTO, if that's helpful. I believe the next step is with you or a member of your team to write a first draft in an etherpad or google doc and paste the link here.

**Comment by OpenMatt** [comment]
@ldecoursy and I talked about the fact taht the presentation Sam and Leah did in the last staff meeting probably contains a lot of relevant data for this. Lainie will post that as a blog post link here when it's published.

**Comment by OpenMatt** [comment]
Bhuvan: you mentioned you had some template examples of other orgs (like Ashoka) that have done this well. Please paste those links here?

**Comment by bhuvanshri** [comment]
Sure.

Some high level (quantative focused) examples:
1. https://www.shuttleworthfoundation.org/reports/2013/
2. https://hourofcode.com/ca

Impact stories focused examples:
1. https://www.ashoka.org/sites/www.ashoka.org/files/2013-Impact-Study-FINAL-web.pdf
2. http://www.righttoplay.com/moreinfo/aboutus/Pages/Stories.aspx

**Comment by OpenMatt** [comment]
* Thanks Bhuvan! 
* @edrushka there were some other template examples circulated in our Whistler meeting -- maybe you can post them here for others to review as well? 
* @RebsD @edrushka : I think the ball is in your court on this one next. We'll await further instructions from you.

**Comment by RebsD** [comment]
It is, thanks. We'll get back to you.
RD

**Comment by edrushka** [comment]
I'm on it! This is my P1 for the next heartbeat.

**Comment by edrushka** [comment]
Update: @RebsD and I have determined that soliciting stories via a template is no longer in scope for our current project, [Creating a 2014 Impact Report for donors] (https://github.com/MozillaFoundation/plan/issues/510). We'll likely revisit this idea for our next Impact Report.

I'm going to unassign myself and close this for now, but if anyone else would like to pick this up, please ping me for my notes (they're in the FR repo, which is private)
