### ISSUE TITLE
Create on-boarding documentation & process for "Open Product Developer" volunteers

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#495]
### Goal for this Heartbeat:
* GOAL: We want recruit more "Open Product Developers," as per https://github.com/MozillaFoundation/plan/issues/482#issuecomment-121115240
* FIRST STEP: was to clearly describe the role and value proposition for volunteers. Which we have now mostly completed. https://github.com/MozillaFoundation/plan/issues/482#issuecomment-121115240
* NEXT STEP: make sure we have a good on-boarding process once we recruit them.

### Deliverable for this heartbeat: 
- [ ]  1) **Pull together on-boarding documentation.** That we can share with new potential Open Product Developers. To help them get up to speed.
- [ ] 2) **Design and document the process.** Write down the steps in the process. What happens from the new prospective Open Product Developer's experience at each step in the process? Who does what, when? Write this down. 
- [ ] 3) **Test and refine the product description page.** A draft prototype is here -- but the copy needs to be tested, edited and updated.  https://github.com/MozillaFoundation/plan/issues/482#issuecomment-121115240

### Assets 
*  @acabunoc and @kaythaney have already been working on an on-boarding process we can learn from: http://mozillascience.github.io/leadership-training/index.html
* @cecilepompei also shared this link for an on-boarding template for someone working on Clubs and Webmaker: https://docs.google.com/document/d/1RuWp4KRLgTCSXzOxe60-ndatqIX_auu93QxAVvYjBWE/edit

cc @benrito Bhuvan @cecilepompei @LauraReynal @thisandagain @secretrobotron

**Comment by OpenMatt** [comment]
@thornet wasn't sure whether to include RCs in this, since you already have your own on-boarding process in place? but please share what you have so we can co-ordinate / copy from what you're already doing?

**Comment by bhuvanshri** [comment]
+ myself.

**Comment by OpenMatt** [comment]
@secretrobotron do those three deliverables make sense to you for this Heartbeat?

**Comment by secretrobotron** [comment]
@OpenMatt :+1:

> Pull together on-boarding documentation

Would like to "test" that a bit too. Could use perspective of people we interviewed (like Ina) to see what's missing.

**Comment by OpenMatt** [comment]
* may need to come up with a better title than "Open Product Developer"

**Comment by OpenMatt** [comment]
* I failed to get my work on this done, because of some competing work on Mozilla Learning Planning. 
* I've got a blog post about 75% drafted that outlines what we've done on this so far, with suggested next steps.
* Will get it done next Heartbeat

**Comment by ldecoursy** [comment]
@OpenMatt should we move this to the next heartbeat?

**Comment by hannahkane** [comment]
@OpenMatt - what's the status of this ticket?

**Comment by ldecoursy** [comment]
@OpenMatt

**Comment by cassiemc** [comment]
@OpenMatt status update?

**Comment by cassiemc** [comment]
Moving to the next heartbeat.
