### ISSUE TITLE
Choose a provider for Push notifications

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#496]
In order to deliver push notifications to users of the Webmaker Android app, we plan to use a 3rd party provider.

This ticket is to find possible providers, review on features and cost, and then initiate a Vendor Review (legal, security, privacy) before we can build this function into the app.

### Audience
All users of Webmaker Android App who agree to receive push notifications (users can opt-out)

### Success
Preferred Vendor Selector and Vendor Review completed.

### Vision
Gather list of potential suppliers
Review together as a team
Pick a winner
Initiate Vendor Review

### Measurement
* App will be able to deliver push notifications
* We will be able to measure the effectiveness of those notifications individually and see the impact they have on user retention rate

### Roles
 * Phase: 
 * Driver: @adamlofting
 * Decision Maker: @thisandagain
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by adamlofting** [comment]
Please add options to this thread:
* http://urbanairship.com/
* https://mixpanel.com/notifications/

**Comment by adamlofting** [comment]
cc @thisandagain @HPaulJohnson @davidascher @simonwex

**Comment by adamlofting** [comment]
Done. 

This will be Amazon SNS. https://aws.amazon.com/sns/

@jbuck @thisandagain @simonwex and I just met to decide on architecture and systems needed for managing notifications (email, push and SMS) and given the need to manage logic and content in our own systems (in part for localization) the push notification provider doesn't' need the content management features of a tool like Urban Airship.

Notes from that call are here:
* https://etherpad.mozilla.org/notifications-service-and-vendors

**Comment by OpenMatt** [comment]
@adamlofting if this is done, ok to close?

**Comment by adamlofting** [comment]
Yep, I meant to click that button :stuck_out_tongue_closed_eyes:
