### ISSUE TITLE
Clubs layout and copy changes

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#503]
Copy still to be finalized

Relevant tickets:
 - [x] https://github.com/mozilla/teach.webmaker.org/issues/1086
 - [x] https://github.com/mozilla/teach.webmaker.org/issues/1104
 - [x] https://github.com/mozilla/teach.webmaker.org/issues/1136

**Comment by thornet** [comment]
@thornet is blocking, so working on not doing that. ^^

**Comment by hannahkane** [comment]
https://github.com/mozilla/teach.webmaker.org/issues/1086 and https://github.com/mozilla/teach.webmaker.org/issues/1104 are done

https://github.com/mozilla/teach.webmaker.org/issues/1136 is blocked on not having Teach API access

**Comment by hannahkane** [comment]
Didn't get finished, so moving to next heartbeat.
