### ISSUE TITLE
Update Webmaker presence on SUMO

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/plan#505]
We need to update Webmaker's presence on SUMO, per https://github.com/mozilla/webmaker-launch/issues/38.

See current presence: https://support.mozilla.org/en-US/

Driver: @kevzawacki

Some proposals to start the conversation:
-Swap out old Webmaker logo for new one
-Remove Popcorn Maker help topic
-Remove 'Get the most from Webmaker.org' help topic
-Update 'Events and help for mentors' copy with teach.mozilla.org-centric copy
-Begin compiling Webmaker app FAQs. In August, create Webmaker help topic
-Be aware that we'll need to update the Thimble help topic when v2 arrives

cc @HPaulJohnson @xmatthewx @secretrobotron 

When we have a consensus, I'll take the plan + assets to the SUMO team for implementation.

**Comment by cassiemc** [comment]
@xmatthewx Possible to squeeze this in this heartbeat?

**Comment by KevZawacki** [comment]
@cassiemc @xmatthewx 

Pardon -- most of this work has [already been done](https://support.mozilla.org/en-US/). 
We can build out Webmaker's SUMO presence further if we like, but I think we're OK to close this ticket.

**Comment by cassiemc** [comment]
Great thanks @KevZawacki!
