### ISSUE TITLE
Infrastructure and Security testing for new Donation Pages

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#506]
In recent heartbeats we have been building our new Donation Pages and setting up our deployment and hosting platforms. 

In this heartbeat we want to thoroughly test these new pages before they are used in production.

### Audience
Mozilla Foundation Online Donors (~300k per year)

### Success
* All planned tests and processes executed
* Weaknesses identified and systems hardened
* Comprehensive documentation on all failover plans and systems

### Vision
We have met and identified 28 tasks we want to complete in this sprint, which have been filed here:

* https://github.com/mozilla/donate.mozilla.org/milestones/Infrastructure%20and%20Security%20Testing

### Measurement
P1: All current planned tasks completed

P2: Another proposed measure of success is: 

* @valianttry has enough confidence in the new system, that she would (with some training) feel happy deploying a copy change to our production server without an engineer on stand-by. << This isn't something we expect to happen, but is a good indicator of the robustness of our new setup. 

### Roles
 * Phase: Testing
 * Driver: @adamlofting
 * Decision Maker: @adamlofting
 * Design Lead: n/a
 * Development Lead: @jbuck 
 * Quality Verifier: ?

**Comment by adamlofting** [comment]
Filing this Plan ticket to put this work on the radar for the next heartbeat. Granular work is in [donate.m.o](https://github.com/mozilla/donate.mozilla.org/milestones/Infrastructure%20and%20Security%20Testing)

@wex are you happy to be quality verifier for this? Or to suggest someone else?

@edrushka let's check dev resources and make sure this works

The majority of this work is DevOps, so falls to @jbuck . @wex and @jbuck can we check this is reasonable given other projects, and that we can ring-fence enough time for this.

cc: @valianttry @ScottDowne @alicoding

**Comment by edrushka** [comment]
@adamlofting is there a hard deadline for this? Do @ScottDowne and/or @alicoding owe @jbuck anything in order for him to complete this work?  I just want to take into account the fundraising meetup which takes place next heartbeat.

**Comment by adamlofting** [comment]
I put this in the Aug 15 heartbeat as this testing would be required before we can use the new pages in a production campaign (i.e. the imminent German campaign).

The tasks assigned to @jbuck can almost all be completed independently, so the fundraising meetup should not be a blocker.

*Note:* this requires the current tasks assigned to @ScottDowne and @alicoding for [this heartbeat](507) to be completed in this current heartbeat.

**Comment by OpenMatt** [comment]
@adamlofting note that @jbuck has a full plate at the moment...

**Comment by OpenMatt** [comment]
@simonwex suggests @ScottDowne could potentially be mentored on this

**Comment by adamlofting** [comment]
@jbuck was able to start on some of these tasks near the end of the heartbeat.

But, the date for the DE fundraising campaign has moved back, so we've spaced out the remaining testing and infrastructure tasks across the following heartbeats in donate.m.o. https://github.com/mozilla/donate.mozilla.org/milestones
