### ISSUE TITLE
New Donations Pages - Setup Deployment and Testing Processes

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#507]
Filing this bug for TPS visibility as I hadn't caught up on ticket admin before the last call.

We're doing another sprint this heartbeat on our new donation pages:

* Integrating Stripe as a new Payment Provider
* Setting up hosting
* Setting up automated testing
* Setting up deployment processes
* Improving localization in our code

Work is being tracked in: https://github.com/mozilla/donate.mozilla.org/milestones/31%20July%20-%20Pre%20FR%20Meetup

The following heartbeat, we will be stress-testing these new pages and processes ( #506 )

**Comment by OpenMatt** [comment]
@adamlofting status?

**Comment by adamlofting** [comment]
Just reviewed with Scott and Ali, and this heartbeat has gone well. 

* Shipped [these bugs so far](https://github.com/mozilla/donate.mozilla.org/issues?q=is%3Aissue+milestone%3A%2231+July+-+Pre+FR+Meetup%22+is%3Aclosed) - and expect to close the remainder today.

Summary for the heartbeat:

> "New donation platform: Setup new codebase, built development workflows, and setup staging server".
