### ISSUE TITLE
Move Goggles to a new home

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#508]
Goggles can't live on webmaker anymore, so we need to find it a new home. 

@xmatthewx - can you clarify whether there's urgency around this? For how long can it continue to live on webmaker?

#### DARCI
Driver: @hannahkane
Accountable: @simonwex 
Responsible: TBD
Informed: @chrislarry33 @ldecoursy

**Comment by hannahkane** [comment]
Seems like this isn't going to happen this heartbeat. @xmatthewx - can you clarify if there's a timeline we need to adhere to?

**Comment by xmatthewx** [comment]
We are in limbo between webmaker.org and beta.webmaker.org until after the snippet launches. Lingering too long won't look good, but I realize there are a lot of dependencies. We should set a timeline with Simon, since it's mostly an engineering lift.

**Comment by hannahkane** [comment]
This is clearly not happening this heartbeat. Will move to next. :)

**Comment by simonwex** [comment]
@hannahkane we should get together and figure out a domain name for this. We can then get on purchasing it.

**Comment by hannahkane** [comment]
Decision made, but moving to next heartbeat for implementation

**Comment by hannahkane** [comment]
Closing this, in lieu of one master Goggles ticket.
