### ISSUE TITLE
LOGIN: Launch login v3

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#51]
Ship login to production. :cat2: :cake: :boom: 

Phase: Build / Ship
Owner: @simonwex 
Decision: @thornet 
Lead design: @xmatthewx
Lead dev: @jbuck 
Dev: @cadecairos
Quality: @thisandagain

## Issue management

We're killing the old bugs in bugzilla and creating new ones in Github under the Dec24 milestone.

* Github Milestone: https://github.com/mozilla/webmaker-login-ux/milestones/Ship%20Login!%20-%20Heartbeat%20Dec24
* Bugzilla master ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1049943
* Bugzilla whiteboard: [login3][dec24]

## What's the scope of this sprint?

Release the new login (v3) over the properties that currently uses Webmaker Login
 * appmaker
 * popcorn maker
 * thimble
 * goggles
 * webmaker.org
 * webmaker events
 * webmaker profile 

#### What is the problem that we are trying to solve?

Address ux disruptions to converting visitors to users. Analytics show a very low conversion rate. 
Persona confuses users. 

#### Who is this for?
All users with Webmaker accounts and new Webmaker users

#### What does success look like? 
Zero bugs filed, zero tweets about it being broken, no user-noticed service disruption (Tweets that the new login is weird are fine).

#### What are the risks associated with producing a solution to the problem?
**Think short term and long term.** What kind of assets will be attached to legacy tools? How much time will be needed to maintain what we make? How much money will it cost? Is it resource-intensive?

 * updated makerstrap
 * updated webmaker-login-ux

Any hard partnerships, commitments, or events that depend on the solution?

## Whiteboard

 * No whiteboarding during this Heartbeat. 
 https://redpen.io/p/wx4a8f231f86820627

## Follow-up
- Team decided to use #login tag on idonethis, no interactive daily stand-ups
- Mid-point meeting scheduled in Simon's vidyo room at 10:00 EDT Monday Dec 22.

## Test Script:
https://webmaker.etherpad.mozilla.org/login-3-testing

**Comment by thisandagain** [comment]
Couple blockers remaining. Tracking here:
https://github.com/mozilla/webmaker-login-ux/issues

**Comment by simonwex** [comment]
^ Blockers are those tagged "critical"

https://github.com/mozilla/webmaker-login-ux/issues?q=is%3Aopen+is%3Aissue+label%3Acritical

**Comment by simonwex** [comment]
@jbuck is going to tackle the remaining issue today and then it's time to :shipit: <( :ship: )

**Comment by xmatthewx** [comment]
Exciting stuff. @adamlofting - ready with your abacus?

**Comment by thisandagain** [comment]
Awesome folks. :smile: x :100:

**Comment by jbuck** [comment]
And we're now deployed.
