### ISSUE TITLE
Create a 2014 donor impact report

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#510]
Driver: @edrushka
Copy: @KevZawacki 
Design: TBD (Jordan?) *need to discuss design capacity for Aug with TPS*
Metrics: @adamlofting 
Signoff: @RebsD 
Consulted: Mark, @valianttry and MoCo Leadership (tbd)
Informed: Ops, @HPaulJohnson 

Due: Report will be mailed and emailed in early September.

Context: As part of the donor stewardship program, one of the fundraising team's first major efforts is to report on Mozilla's activities to people who gave us money last year by sending them a donor report. 

The report will feature 2 stories:
- a human-level, human interest story about one person whose life has been directly improved by Mozilla's web literacy efforts
- a higher-level story about Mozilla's recent efforts in policy/advocacy

Work tracked here:
- [Shortlist human interest stories] (https://github.com/MozillaFoundation/2015-fundraising/issues/28) (erika)
- Write copy for both stories (kevin)
- Write/get brief Firefox update (kevin)
- [Identify donors and method of contact] (https://github.com/MozillaFoundation/mofo-crm/issues/24) (adam)
- Determine printing/mailing budget (rebecca)

**Comment by OpenMatt** [comment]
Love this. Are there examples of how other organizations have done this that we can share? (So that people have a sense of what it may look like.)

**Comment by OpenMatt** [comment]
Mark's year-end email is a good recent example as well.

**Comment by edrushka** [comment]
Yes, I've already shared Mark's email with Rebecca. Here are some examples of Donor Impact Reports:
- [WWF] (http://wwf.panda.org/about_our_earth/all_publications/living_planet_report/) Extremely dense, very long and lots of text. Individual stories indicate threats/dangers if action is not taken, and solutions correspond to WWF's "one planet" goals. Report has a complementary video with WWF's director, which is cool.
- [Greenpeace] (http://www.greenpeace.org.uk/sites/files/gpuk/AR2014_v08_web.pdf) Stories are mostly from staff.
- [MSF] (http://cdn.msf.ca/sites/canada/files/msf_impactreport_2014_eng_0.pdf) Nice balance of graphics, facts/stats, and stories from staff. Not too long. I like this one.
- [Wikimedia Foundation] (https://meta.wikimedia.org/wiki/Communications/State_of_the_Wikimedia_Foundation) As expected, this is in wiki format, so text-heavy. No stories, this is pretty 'factual'. Includes 2015 goals, and 2014 'failures'.
- [Dogwood Initiative] (https://dogwoodinitiative.org/aboutus/annual-reports/2013-14) Very visual. Stories from staff. Includes forward-looking goals and 'hard lessons'.
- [Change.org] (https://www.change.org/impact) Web-based and locale-specific. Video and links to illustrative petitions they call 'Victory Highlights' - this format could work for us.
- [Shuttleworth] (https://www.shuttleworthfoundation.org/reports/2013/) - short, clear, more graphics than text, created for web vs. print. I like this one.
- [Ashoka] (https://www.ashoka.org/sites/www.ashoka.org/files/2013-Impact-Study-FINAL-web.pdf)
- [Right to play] (http://www.righttoplay.com/moreinfo/aboutus/Pages/Stories.aspx)

I should clarify that we will not be doing anything quite so elaborate as the above examples for our first report, since we need to get this out in September.

**Comment by LauraReynal** [comment]
@edrushka I sent you all I have on Suchita.
Also, I'm thinking I have other portraits to show the *need* for us to be doing our programs, but they don't show impact yet. Let me know if this is something you could need. Happy to chat further.

**Comment by edrushka** [comment]
Incredibly helpful, @LauraReynal! Thank you :hibiscus: @KevZawacki are going to circle up to chat messaging, so I'll get back to you on the 'need' piece.

**Comment by OpenMatt** [comment]
* time sensitive for early Sep, and may require additional design resrouces (cc @cassiemc)

**Comment by edrushka** [comment]
Progress: we've identified our individual story. I've filed [a ticket] (https://github.com/MozillaFoundation/2015-fundraising/issues/30) for @KevZawacki and I to get the first draft written.

**Comment by edrushka** [comment]
Update:  Meeting on Monday, August 17 with @RebsD and @valianttry to discuss audience, method of delivery and format (and to ensure we're not duplicating efforts with other 'impact' work).

@KevZawacki good to contact Suchita as her story will be used regardless of the outcome of Monday's meeting.

**Comment by edrushka** [comment]
Due to time constraints and what we are currently able to pull from the database, this will be email only (to people we're allowed to email, obvi). There will be no printed mailer. 

Kevin has connected with Suchita and is hoping to speak with her next week.

**Comment by OpenMatt** [comment]
@edrushka status?

**Comment by edrushka** [comment]
This work is paused for the moment. I'm going to remove the milestone.

**Comment by edrushka** [comment]
Closing as this didn't happen in 2015. However, we did manage to widely share some great impact stories like Suchita's on the snippet, and in the November impact email. We also published the annual State of Mozilla 2014 report which highlighted some major org-wide achievements.
