### ISSUE TITLE
Deploy new Thimble to Thimble-beta

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#511]
The CDOT team is planning to deploy the new Thimble to production next week (week of August 3)  so we can begin testing, as well as start working with a stable database (which is necessary for creating the "starter" content we'll have on the new Thimble landing page).

Will need devops support, if possible.

### DARCI
Driver: TBD
Accountable: @simonwex 
Responsible: TBD
Consulted: @humphd 
Informed: @hannahkane

**Comment by hannahkane** [comment]
Relevant tickets:
https://github.com/mozilla/thimble.webmaker.org/issues/732
https://github.com/MozillaFoundation/mofo-devops/issues/133

**Comment by OpenMatt** [comment]
* time pressure here is around having Thimble ready for "back to school" comms in early Sep

**Comment by hannahkane** [comment]
Believe this is done. @jbuck or @humphd to verify?

**Comment by hannahkane** [comment]
I am closing, because this is done. :)
