### ISSUE TITLE
Build tool to provide makes to old webmaker tool users

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#512]
GOAL: Build a small tool to provide existing makes to webmaker users after Popcorn Maker and Appmaker are decommissioned on September 30th.

Worked with @simonwex a bit on a design for this:
- build set of JSON files — one per webmaker user — comprised of metadata for list of makes from scraping MakeAPI
- (make sure there aren't other makes to be collected)
- put all of those JSON files on S3; add cloudfront
- build a two page front-end lookup tool to let users type in their username and receive a list of makes they made
- put links to this tool on relevant websites (e.g. teach, blogs, etc.)

Questions:
  * Can we make the list of makes available by username *and* email? (@simonwex @jbuck)
  * Where should we put a link to this tool? (@amirad @KevZawacki @HPaulJohnson)

**Comment by secretrobotron** [comment]
Added messaging to tools:
- https://github.com/MozillaFoundation/plan/issues/465
- https://github.com/mozilla-appmaker/appmaker/issues/2412

e.g. https://popcorn.mofostaging.net/

**Comment by amirad** [comment]
Can there be a link to this on the Webmaker page still? Whether in an FAQ or in a banner?

Also, @ldecoursy sounds like this is something we should have under the tools section of the teach site? And perhaps communicate out in community calls.

**Comment by KevZawacki** [comment]
+1 @amirad. Copy and a link on https://teach.mozilla.org/tools/ would be a nice fit.

"Searching for past makes created with our tools? Find them here [link]."

If we know a) that old makes will definitely be available and b) where the link will live, I wonder if we can move forward with communications.

**Comment by amirad** [comment]
FYI @hannahkane

**Comment by ldecoursy** [comment]
@secretrobotron, can you confirm this includes existing Thimble makes too?

**Comment by simonwex** [comment]
@ldecoursy, it would include everything that users can currently find in their profiles.

**Comment by OpenMatt** [comment]
* Why this is a P1 for this Heartbeat: has been kicked down the road for a while -- lots of temporary measures
* This is a blocker for: deprecating the tools for real. It's how people will access their previous makes.
* @thisandagain proposal: move this to late Sep / tackle through navigation change. 
* next step: @thisandagain will file and drive a new ticket for this. This week. Potentially working with @xmatthewx

**Comment by KevZawacki** [comment]
@simonwex Wondering if we've determined what the archive tool will look like/where it will live. If so, we can start communicating it to users alongside our deprecation messaging.

**Comment by simonwex** [comment]
@KevZawacki we should continue to use the `/me` URL. The page design and the ability to remix Appmaker and Popcorn makes will change, but it should still be referenced for users.

**Comment by simonwex** [comment]
Remix of old thimble makes will maybe be possible in new thimble, can be tracked here: https://github.com/mozilla/thimble.webmaker.org/issues/793

**Comment by simonwex** [comment]
Relate: #527

**Comment by hannahkane** [comment]
Duped by #561
