### ISSUE TITLE
Deploy blog post and tools changes to disseminate tool transition information

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#513]
GOAL: Deploy blog post and associated changes tools to tell people that Popcorn Maker and Appmaker are being decommissioned.

* @KevZawacki is preparing a blog post which will point to a new tool (#512)
* Popcorn Maker and Appmaker are both ready to go **on staging**. They need to be pushed to prod at the right moment (roughly when @KevZawacki has his blog post published)

Related to #512

**Comment by KevZawacki** [comment]
Blog post is live: http://mzl.la/webmaker-tools-transition 
@jbuck, any chance you can push the banners to prod?

**Comment by jbuck** [comment]
@KevZawacki Yep, popcorn is live now, but broken compared to staging: https://popcorn.webmaker.org/

Need to figure out how to push appmaker without breaking anything....

**Comment by jbuck** [comment]
@KevZawacki Okay, popcorn is looking good now.

So is Appmaker: https://apps.webmaker.org

**Comment by KevZawacki** [comment]
Thank you kindly, @jbuck!
