### ISSUE TITLE
Build transactional email service for Webmaker & Teach users

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#514]
GOAL: Build service to send out transactional emails to users 3 days after they install Webmaker.

Tracking:
* Changes to login (service): https://github.com/mozilla/login.webmaker.org/issues/365
* Change to webmaker-mailroom (email): https://github.com/mozilla/webmaker-mailroom/issues/43

@jbuck @simonwex @HPaulJohnson @KevZawacki

**Comment by OpenMatt** [comment]
@thisandagain volunteers to PM this one

**Comment by OpenMatt** [comment]
@thisandagain says dev work is unlikely to occur on this this Heartbeat.

**Comment by HPaulJohnson** [comment]
@thisandagain - not sure when we will get to this one but we have some sample copy to start with when we do: https://docs.google.com/document/d/1kiuGPLX5Me6Jr7lWw1J13AXez9Q7rT9ELs9bynpCbh8/edit

To finalize email we need some content and app screenshots:
- A sample "tutorial" project that walks through all the major features
- Screen shots of remix, steps to edit text and sharing. (preferably, all these screenshots are based on the tutorial project). 

@secretrobotron was going to tackle the tutorial but don't believe he was able to pre-PTO. If this isn't going live until after launch we can wait for his return, but if there's a chance it a can happen for launch we'll need some help with the content above.

**Comment by xmatthewx** [comment]
Not yet possible given services resources. @HPaulJohnson and @secretrobotron have drafted content and plans for doing this manually in the interim. Bumping to the next milestone.

**Comment by OpenMatt** [comment]
status?

**Comment by OpenMatt** [comment]
@simonwex what is the next step here?

**Comment by hannahkane** [comment]
Thinking we should close this, and re-open when we're ready. @simonwex ?

**Comment by simonwex** [comment]
Agreed.
