### ISSUE TITLE
Webmaker v1.2.0

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#516]
Prep for Webmaker marketing release in Bangladesh, Indonesia, and Brazil as well as global access to the Snippet.

#### Goals
- Resolve critical user facing bugs
- Land and QA batch updating of project data (performance)
- L10N fixes / tweaks
- General QA and hardening

#### Nice-to-have
- First time use improvements (contextual guides)

#### RACI
Driver: @thisandagain
Decision: @davidascher 
Design: @vazquez 
Dev: @gvn @Pomax @k88hudson 
Services: @cadecairos @ashleygwilliams 
Metrics: @adamlofting 

#### Resources
Milestone – https://github.com/mozilla/webmaker-core/milestones/1.2.0%20-%20Snippet
Roadmap – https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1ZvdNJLHuW0fIBt_-WcR7Ns6OhZgaMy6MI9kfjlXF-9o/edit#gid=0
Play store – https://play.google.com/store/apps/details?id=org.mozilla.webmaker&hl=en
Nightly – http://mzl.la/webmaker-nightly

**Comment by thisandagain** [comment]
Release candidate for v1.2.0 is up on nightly:
http://mzl.la/webmaker-nightly

Scheduled for release to Google Play tomorrow morning after final QA.

**Comment by xmatthewx** [comment]
Planning ticket for 1.3.0 https://github.com/MozillaFoundation/plan/issues/538
