### ISSUE TITLE
Create marketing deliverables for Thimble

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#518]
@HPaulJohnson and @KevZawacki to add specific details and list of deliverables

### DARCI ###
Driver: @HPaulJohnson 
Accountable: @HPaulJohnson
Responsible: @hpauljohnson, @KevZawacki
Design: @sabrinang 
QA: @cassiemc
Consulted: @ldecoursy @chrislarry33 @hannahkane

### Must Have Deliverables ###
 - [x] Blog post
 - [x] Email assets
 - [x] Email template
 - [x] Email copy
 - [ ] 3-4 Facebook posts w/ graphics
 - [ ] 5-6 Twitter posts w/ graphics
 - [x] Digital Assets partner kit (no additional design work needed)

### Nice to Haves ###
 - [ ] ~~Video~~ not going to have this in time for launch
 - [x] teach.mozilla.org promo
 - [x] mozilla.org tile
 - [X] Directory tile

**Comment by cassiemc** [comment]
I started a pinterest for inspiration here: https://www.pinterest.com/cassiemc/thimble-back-to-school/

**Comment by KevZawacki** [comment]
Comms plan here, updated thoroughly after today's call: https://docs.google.com/document/d/1axAmOwVVdvW_mwy9IfnW8sJlaJ4m6kDd4MHVzEMSboc/edit

**Comment by OpenMatt** [comment]
* Next steps: deliverables are listed and ready in Kevin's link for @cassiemc to review and assign a resource.

**Comment by hannahkane** [comment]
@cassiemc - let me know how you want to staff this. If you'd like to give this to Sabrina, I'll remove the other tickets that I'd been planning to assign to her this heartbeat so she can focus on this.

**Comment by cassiemc** [comment]
@hannahkane Yes, I am thinking @sabrinang and I can tackle this together

**Comment by cassiemc** [comment]
Have updated the RACI.

**Comment by HPaulJohnson** [comment]
Kickoff today. 
Design brief: https://docs.google.com/spreadsheets/d/1SjMHlBZj7uGfQEV6KTaUMAMBvsjUbc9Rz78bkIX8EBw/edit#gid=0
Master list of deliverables: https://docs.google.com/spreadsheets/d/1sj6GrVHPMiuj7SdPBK7X84Y_KNM-qMvDw8XalviCmmk/edit#gid=0

**Comment by cassiemc** [comment]
@HPaulJohnson @hannahkane is there a milestone perhaps in the teach repo we should use for tracking individual bugs?

**Comment by hannahkane** [comment]
Hmm...not sure if it fits better in the Teach repo or the Thimble repo. If we go with the Teach repo, we can put stuff in the August 14, 2015 milestone. I'm going to take most of what's currently in that milestone out, since we are focused on this project instead.

**Comment by ldecoursy** [comment]
Here's the latest draft of the back-to-school focused teaching kits for launch, in case helpful for informing design/copy: http://bit.ly/1gr28xo

**Comment by mmmavis** [comment]
Hellooo there, 

Not sure if this is the right ticket for this, but regarding the email "template" we are about to build, do we want a general **reusable template/wrapper** that Paul or anyone can just apply and insert content on BSD in the future **OR** a **one-time email**?  (I will have some follow-up questions)

Either way I would strongly advocate for a very simple single column design(no floating elements as well) so the layout will always work regardless the screen resolution. Or if we really want to add some spices to it, we will have to decide what email clients we want to support  --- as the rendering engines vary A TON across email clients (think about all the email clients * OS * browsers * resolution combo that a email can be viewed on :weary: )... a email could look pretty on one email client but completely broken on another.  FYI, the popular Gmail and Outlook are on the top of the hard-to-please list.  :no_mouth: 


@HPaulJohnson @sabrinang thoughts?  :hamster:

**Comment by sabrinang** [comment]
Hey @mmmavis thanks for flagging - I am unsure if it is a unique email or should be made a template for future use but @HPaulJohnson will have more details on e-mail strategy itself. 

As for design, I posted some comments and some visuals on redpen here: https://redpen.io/hvfd4ccb70b75e90c6 and I highlighted what sections may be good to be reused again and comments that I would love your suggestions. Any feedback to move forward making the emails appear best for as many email clients as possible is appreciated!

**Comment by HPaulJohnson** [comment]
This will be used as more of a one-off than a template. The promotional strategy might include a series of 2-3 emails over the course of a few months but long term, the main template should be Mozilla Learning Networks and not Thimble specific. 

We could either keep it simple with this in mind or design a MLN style template that allowed some type of dynamic space (something like a subhead) that allowed for campaign or product-specific promotion. 

Not sure if this is a helpful answer but happy to chat more if you'd like. I think because we eventually will need to create some new emails in Exact Target we should keep the design of these pretty simple as they will only be used for the next few months.

**Comment by mmmavis** [comment]
Yup this is helpful! Thanks @HPaulJohnson @sabrinang ! 

Code used in email usually has to be formatted in a **very special way** for it to work.  Processing my code with an email format helper is always the last step before I paste my code onto BSD.  One thing I found with [the BSD's WYSIWYG Editor](https://cloud.githubusercontent.com/assets/2896608/9181707/3fe14f40-3f5b-11e5-896b-8d52d0e98a00.png) (or probably WYSIWYG Editors in general) is it will automatically inject redundant or unsupported HTML tags which often cause our emails to break.

If we can have email content ready **few days before** we send out the email, I think the best way to cope this is to avoid using that WYSIWYG Editor at all. :grin: In other words, 

1. devs build the email with *real* content included in code
2. devs process code with the email formatter
3. devs upload email code onto BSD
4. devs create a new mailing on BSD by filling out [these fields only](https://cloud.githubusercontent.com/assets/2896608/9182040/281bc384-3f5d-11e5-91f6-f76066003b33.png) (leaving the WYSIWYG editor **untouched**)
5. devs run tests on [Emails on Acid](https://www.emailonacid.com/email-testing)
6. comms people verify fields on BSD are filled correctly and send sample email to themselves to double check
7. comms people send out email

These steps are kinda tedious but I think this flow will reduce the chances of breaking our email layout... :no_mouth: :no_mouth: :no_mouth: 

Let me know if this makes sense :bowtie:

**Comment by sabrinang** [comment]
### Directory Tiles

![mozilla-thimble_directory-tile-preview](https://cloud.githubusercontent.com/assets/2492510/9184920/10bef7dc-3f6d-11e5-9ac8-5dfe1bdbce66.png)

**Main Tile:** Mozilla Thimble (original lockup) on dark green (#289761) background.
**Rollover Tile:** Copy - “A code editor for the classroom.” on green (#47AC65) patterned background.


Asset folder: https://drive.google.com/open?id=0B4Q8pzCpDS_efnFiQWpXb1R4VFN3SmhUeUxhSW0xZGNEcW9rM2luR1VRTnd3M29HTWxBMVk

**Comment by hannahkane** [comment]
All - updated the ticket description with the list of deliverables. Feel free to check stuff off as we knock 'em out!

**Comment by ldecoursy** [comment]
Lots of progress, still a few pieces to work on.

**Comment by sabrinang** [comment]
For the mozilla.org tile, do you need the thimble logo exported in a specific format?

**Comment by OpenMatt** [comment]
status?

**Comment by HPaulJohnson** [comment]
Wrapping up a couple of the social media assets today and then this will be complete.

**Comment by OpenMatt** [comment]
@HPaulJohnson done?

**Comment by HPaulJohnson** [comment]
Yes, done!
