### ISSUE TITLE
On-boarding Design

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#52]
Direct user's into a first-time use (FTU) experience within X-Ray Goggles (best retention metrics). Goal is to A/B test on-boarding messaging an increase engagement off of sign-up. The scope of this sprint is to design an initial on-boarding experience that can be built and deployed within the next 2 week sprint.

Phase: Design / Build / Ship
Owner: @secretrobotron 
Decision: @thisandagain
Consulted: Paul
Lead design: @iamjessklein 
Lead dev: n/a
Quality: @cassiemc

**Comment by iamjessklein** [comment]
I just updated redpen with two more mockups. 

[One](https://redpen.io/pwb1c1c8eeff624e89):
![landing3 5](https://cloud.githubusercontent.com/assets/535012/5615157/80488e6c-94c6-11e4-85df-3445a4c21b94.png)

[Two](https://redpen.io/kfdf87e263b5bf7762):

![landing-goggleson](https://cloud.githubusercontent.com/assets/535012/5615162/870feaec-94c6-11e4-9199-f6e2f55459be.png)

Also - I blogged about the work up to this point for this heartbeat [here](http://jessicaklein.blogspot.com/2015/01/shall-we-dance-on-boarding-webmakers.html).

**Comment by xmatthewx** [comment]
awesome work @iamjessklein
