### ISSUE TITLE
Conduct interviews with first 100 Club Captains 

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/plan#520]
Tracked in more detail here: https://github.com/mozilla/learning-networks/issues/200

Success is: By August 7, 100 people interviewed and pledged to host at least 3 Mozilla Club sessions by Mozfest.

Scope/constraints: Club Captains have a relationship with regional coordinators.

**Comment by ldecoursy** [comment]
Made good progress last heartbeat, RCs and Staff Organizers continuing outreach. Also finalizing the "pledge" with legal. Moving to next heartbeat.

**Comment by OpenMatt** [comment]
status?

**Comment by ldecoursy** [comment]
Just changed assignee to @amirad. Should wrap this up in next heartbeat.

**Comment by ldecoursy** [comment]
RC's have been helping us vet/interview existing backlog of Club Captains. Interview responses are being logged. 

@amirad Can you add more detail so we can close this ticket?

**Comment by amirad** [comment]
Yes! Emails with interview questions have been sent to all club applicants. For those that have responded, we have identified and talked through club process with them and they are pledging to run a club in their community. As a result, 100+ club captains are now logged in our system.
