### ISSUE TITLE
Identify and invite next cohort of Regional Coordinators

### ISSUE THREAD

**Issue by thornet** [MozillaFoundation/plan#521]
Our goal for Q3 is to on-board 15 more Regional Coordinators, expanding our capacity to support clubs. 

This heartbeat, we'll: 
- [ ] circulate the regional coordinator [volunteer job description](http://mozilla.github.io/learning-networks/clubs/regional-coordinator.html) 
- [ ] identify 20+ candidates (ca. 3 recommendations per staff organizer, rest from other RCs)
- [ ] send invitation emails to set up recruitment calls

cc @ldecoursy @amirad

**Comment by ldecoursy** [comment]
Still in progress, have about 10 identified, planning some outreach in next heartbeat.

**Comment by OpenMatt** [comment]
status?

**Comment by OpenMatt** [comment]
@thornet @ldecoursy status?

**Comment by ldecoursy** [comment]
Re-assigned to Amira. Based on staff transition, moving this to next heartbeat to wrap up.

**Comment by ldecoursy** [comment]
Next cohort is identified, planning for initial on-boarding call within the next few weeks. 

@amirad ok to close?

**Comment by amirad** [comment]
Next round of RCs have been identified here: https://teach.etherpad.mozilla.org/clubsscratchpad (line 26-41). Email will be sent for on-boarding which will begin in next 1-2 weeks.
