### ISSUE TITLE
Maker Party Wrap-Up

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#522]
In this heartbeat we'll:

[x ] Publish closing blog post on Webmaker (and maybe on Mozilla blog pending Windows 10)
[x ] Send campaign wrap-up email to various BSD lists and communities
[x] Make updates to teach.mozilla.org/events page https://github.com/mozilla/teach.webmaker.org/issues/1135
[x] Share a recap on earned media efforts
[x] Debrief with key stakeholders

cc @amirad @KevZawacki

**Comment by amirad** [comment]
Link to Webmaker blogpost: http://mzl.la/1eGAaMA
Emails sent to mofo, reps and listserv.

**Comment by KevZawacki** [comment]
cc @HPaulJohnson, who will oversee the campaign wrap-up email.

**Comment by ldecoursy** [comment]
@KevZawacki's marcom summary is here: https://www.macfound.org/annual-report/2014/essay/?page=4 
Also had debrief today: https://teach.etherpad.mozilla.org/MP2015debrief
