### ISSUE TITLE
Recover discourse.webmaker.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#523]
Driver: @simonwex
Accountable: @ldecoursy @simonwex- help with comms
Responsible: @simonwex
Consulted: @ldecoursy @chrislarry33 @hannahkane

[more details to be entered by @simonwex]

**Comment by ldecoursy** [comment]
@simonwex Any update on ETA for this? Still on track to have something today with recent data in tact?

**Comment by simonwex** [comment]
Update: Our new production discourse version is up and running. Tomorrow we'll add the customizations that the previous version had including SSO. 

@ldecoursy previously the accounts were created using the system on https://directory.hivelearningnetworks.org/ . Do you see any problem with using the same account system as teach.mozilla.org?

**Comment by ldecoursy** [comment]
@simonwex The accounts on discourse.webmaker.org shouldn't have been connected to the Hive directory - that has a separate instance of Discourse.

**Comment by simonwex** [comment]
@ldecoursy let's chat about this tomorrow, I think connecting it to the same account system (webmaker.org) as teach.mozilla.org makes sense.

I also figured out that we can't use a subdirectory (http://teach.mozilla.org/community) as discourse doesn't support this. http://community.teach.mozilla.org work for you?

**Comment by ldecoursy** [comment]
@simonwex that URL works for me. Definitely need to discuss the Hive Directory as that has other implications that are not connected to Discourse but are connected to http://hivenyc.org/community/

**Comment by simonwex** [comment]
Cool, let's chat Monday about it.

**Comment by simonwex** [comment]
It took longer than expected, but we're ready to go live with this tomorrow (Friday). Recovery will follow incrementally.

**Comment by OpenMatt** [comment]
nice! @simonwex : sounds like we'll be able to close this out shortly.

**Comment by jgmac1106** [comment]
yipee
