### ISSUE TITLE
Webmaker Navigation Audit and Deprecation Comms

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#524]
We need to do an audit of the user experience for existing users of: Appmaker, Popcorn, Thimble, and X-Ray Goggles. This may require some updates to the navigation on http://beta.webmaker.org and existing tools to ensure a good experience between now and the release of the full browser version of Webmaker.

#### RACI
Driver: @xmatthewx, @hannahkane, @simonwex 
Decision: @davidascher 
Dev: @jbuck 
Consulted: @HPaulJohnson @ldecoursy

**Comment by xmatthewx** [comment]
No progress while focused on the launch. 

We need to huddle (me, @hannahkane, @simonwex) to identify the dependencies and blockers between deprecated tools, teach site, Webmaker site, and services. The loose threads are slowing us down and making it more difficult to enjoy the success we've had in narrowing and refining our focus.  

It's not fun work, but having it done will be fun.

**Comment by hannahkane** [comment]
I summarized my questions + the related outstanding tickets I could find here: https://etherpad.mozilla.org/mofotoolsdeprecation

Please comment + should we schedule a huddle for next week?

**Comment by xmatthewx** [comment]
Added a few notes. Glad to discuss with @hannahkane and @simonwex

**Comment by hannahkane** [comment]
Just sent a calendar invite for next week.

**Comment by xmatthewx** [comment]
Met and discussed with @hannahkane @simonwex @ldecoursy

Next step: 
 - @simonwex / @jbuck to file issues for the services team as listed below. 
 - @hannahkane to plan a "can't remix" landing page for appmaker and popcorn with @cassiemc 

Key discoveries: 
 - We can retire wm.org and launch beta.wm.org _after_ rewriting the /me tool 
 - Connecting old makes with new thimble requires some UX and tech planning
 - Appmaker & popcorn need a landing page & message for attempted remixes

Order of tasks to be done:
 - shutdown events.wm [ @jbuck ]
 - turn off "new" appmaker button [ @jbuck ] 
 - create "can't remix landing page" for Popcorn and Appmaker [ @hannahkane  ]
 - move /me to beta.webmaker [ @jbuck ]
 - retire wm.org [ @jbuck ]
 - launch beta.webmaker [ @jbuck ]

Thimble and goggles have their own tasks, but they are disentangled from the other projects. 

More details in https://etherpad.mozilla.org/mofotoolsdeprecation

**Comment by cassiemc** [comment]
Is @HPaulJohnson involved already? i imagine some of this will require some email comms with our users. 

Feel free to loop me in at any stage if you need an extra set of UX eyes. We've never done stuff like this well so it won't hurt to have a good review process in place.

**Comment by xmatthewx** [comment]
Thanks @cassiemc. I think design can help in two areas: 
 - Popcorn & appmaker projects will remain available, but can't be remixed. We should design a landing page that explains why and points people to other tools. 
 - Old Thimble projects will be remixable in new Thimble. @simonwex will engineer the most fluid experience possible given tech limitations, but we should diagram the UX and share that with key stakeholders who have created lots of curriculum. 

I think that most of the comms and notifications on tools is done.

**Comment by OpenMatt** [comment]
@xmatthewx ongoing work? roll into next heartbeat?

**Comment by OpenMatt** [comment]
* question for @simonwex on who is going to do this work going forward.

**Comment by xmatthewx** [comment]
rewrite and move /me happening here: https://github.com/MozillaFoundation/plan/issues/561

**Comment by xmatthewx** [comment]
Details of this work is now tracked in https://github.com/MozillaFoundation/plan/issues/569
