### ISSUE TITLE
Prepare for Aug 18 staff meeting on Mozilla Learning phase 2

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#526]
**Home for this work:** https://wiki.mozilla.org/Learning
**Goal:** move from Phase 1 to Phase 2 of the planning process. Beginning with the Aug 18 staff meeting. 
* Discuss the process with staff. Invite everyone to get involved. 
* Clearly outline *how* to get involved in each Working Group and the overall process. 
* Make sure staff have enough time to read in advance

**Comment by OpenMatt** [comment]
### Deliverables needed for Aug 10:
- [ ] A third draft of the wiki: https://wiki.mozilla.org/Learning (Matt)
- [ ] A better graphic for the top of the wiki (Bhuvan)
- [ ] A "partnerships" page, linked from the wiki (Bhuvan) 
- [ ] Draft an email to staff that can go out week of Aug 10 (Matt)

**Comment by OpenMatt** [comment]
### Deliverables needed for Aug 18:
- [ ] Fourth draft of the wiki: https://wiki.mozilla.org/Learning (Matt)
- [ ] An updated FAQ page (Bhuvan)
- [ ] A Mozilla Learning community call page (Matt) 
- [ ] Working Group Deliverables: each Working Group has a clear, vetted list of Phase 2 deliverables

**Comment by OpenMatt** [comment]
cc @bhuvanshri

**Comment by bhuvanshri** [comment]
Additional Deliverables for Aug 18:
- [ ] WGT(Women & Girls in Tech) Task Force plan review with Angela and Mark
- [ ] WGT plan added and linked through on the Learning Wiki
- [ ] Partnerships framework developed (Mark w/ support from Bhuvan)

**Comment by bhuvanshri** [comment]
Link to the document Lynn and I created yesterday for the WGT task force: https://docs.google.com/document/d/1IzjPIKg9q1DuBkW0FkbXGJC9KfvYmmYM8JasEloP8cw/edit

**Comment by OpenMatt** [comment]
@ldecoursy can you add your partnership criteria document, so we can include it on Partnerships page?

**Comment by bhuvanshri** [comment]
Learning Networks Partner Criteria: https://docs.google.com/document/d/1qukGywwh1zY8eIPa75_AnS8Piu9KUxWGXpgu4N6gGAY/edit

**Comment by bhuvanshri** [comment]
Update on Item: Publish public version of Mark's last board slides (Bhuvan:
Angela doesn't seem to have this version available either. Will ask Mark directly for them once he returns from PTO

**Comment by bhuvanshri** [comment]
@OpenMatt: Here's the link to mark's slides. https://dl.dropboxusercontent.com/u/877257/MozLearn%20Slides%20-%20Blog%20Post%20Version.pdf

I am having trouble posting them on the wiki so they are visible. Would love to capitalize on your wiki skills in doing so!

**Comment by hannahkane** [comment]
@OpenMatt - we can close this, right?

**Comment by OpenMatt** [comment]
yes.
