### ISSUE TITLE
Address non-remixability in Popcorn and Appmaker makes

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#527]
Options include:
1) Remove "Remix" as an option from existing makes
2) Provide a landing page that explains these tools no longer exist, therefore the make can't be remixed - **this is the winning option**

### DARCI ###
Driver: @hannahkane
Designer: TBD
Engineer: @cadecairos

**Comment by hannahkane** [comment]
@simonwex - do we have anyone who can do this this heartbeat?

**Comment by hannahkane** [comment]
Moving this to next heartbeat. Will assign myself as Driver, but need design support.

**Comment by OpenMatt** [comment]
@hannahkane status?

**Comment by hannahkane** [comment]
Didn't get to this. Moving to next heartbeat.

**Comment by OpenMatt** [comment]
@cassiemc and @simonwex will follow up with @hannahkane

**Comment by simonwex** [comment]
@cadecairos I think this is going to fall in as some of the deprecation work. Do we have this on our radar anywhere there?

**Comment by cassiemc** [comment]
@hannahkane It seemed you used team resources (was it @sabrinang?) for the me page updates, can you do the same here?

**Comment by cadecairos** [comment]
> @cadecairos I think this is going to fall in as some of the deprecation work. Do we have this on our radar anywhere there?

@simonwex I don't think so, doesn't appear in MozillaFoundation/plan#569

**Comment by simonwex** [comment]
Thanks, @cadecairos!

**Comment by hannahkane** [comment]
@cassiemc - ok, will use Teach design resources. Removing label.

**Comment by hannahkane** [comment]
Actually, if others are okay with the idea described in [this ticket](https://github.com/mozilla/teach.mozilla.org/issues/1252) I don't think we even need design resources.

**Comment by cassiemc** [comment]
WFM!

**Comment by OpenMatt** [comment]
@hannahkane status?

**Comment by OpenMatt** [comment]
will probably close today / early next week

**Comment by hannahkane** [comment]
Done
