### ISSUE TITLE
Conduct Pledge conversion experiments

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#532]
We'd like to design an experiment to see if we can optimize the pledge conversion rate on the Teach site.

Deliverables for this heartbeat:
 - [x] Install Optimizely ???
 - [x] Design variations + copy
 - [x] Implement and begin running tests

**Comment by hannahkane** [comment]
"Needs dev" label specifically refers to identifying someone familiar with Optimizely, ideally

/cc @adamlofting since this is metrics-y

**Comment by hannahkane** [comment]
Mid-heartbeat update: Design work is done. Work remaining: install optimizely and implement test.

**Comment by hannahkane** [comment]
Meeting with @adamlofting and @mmmavis scheduled for Thursday to take Optimizely next steps.

**Comment by OpenMatt** [comment]
status?

**Comment by hannahkane** [comment]
Meeting happened, but tests aren't running yet, AFAIK.

**Comment by chrislarry33** [comment]
What is the blocker on the tests?

**Comment by hannahkane** [comment]
No specific blocker, just didn't get to meet until the end of the week. Will resolve shortly.

**Comment by hannahkane** [comment]
forgot to say this is done. will report on results shortly.
