### ISSUE TITLE
Clubs page iteration

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#533]
We started this work in a previous heartbeat, but tabled it in order to focus on Thimble launch materials.

Relevant tickets:
 - [x] Design: https://github.com/mozilla/teach.webmaker.org/issues/858
 - [x] Dev: https://github.com/mozilla/teach.webmaker.org/issues/1142

**Comment by thornet** [comment]
cc @amirad 

We may not be able to ship any new language around the tiers just yet. Still some important program design and community consultation in progress. 

Will ask @amirad if she can help keep this tickets updated as we move through.

**Comment by amirad** [comment]
Not sure if I know what iterations you both mean

**Comment by hannahkane** [comment]
I think we're covering this in https://github.com/mozilla/teach.webmaker.org/issues/858

**Comment by OpenMatt** [comment]
status?

**Comment by hannahkane** [comment]
WIP, but not on production just yet.

**Comment by hannahkane** [comment]
oh man, this is totally done.
