### ISSUE TITLE
Badges implementation

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#534]
- [x] Hire contractors
 - [X] Badge workflow wireframes
 - [x] [Badge workflow mockups](https://github.com/mozilla/teach.webmaker.org/issues/1257)
 - [x] [Badge design](https://github.com/mozilla/teach.webmaker.org/issues/1242)
 - [ ] [Build MVP](https://github.com/mozilla/teach.mozilla.org/milestones/Badges%20MVP)

**Comment by hannahkane** [comment]
Contractors not hired yet. Moving to next heartbeat.

/cc @simonwex

**Comment by OpenMatt** [comment]
note: christina will be doing the design work on this.

**Comment by hannahkane** [comment]
We've started design work, but have some technical questions. @simonwex - sent you a meeting request. Looks like engineering work will not begin this heartbeat, as contract has not been signed.

**Comment by OpenMatt** [comment]
* @simonwex please update on hiring. 
* also: @cassiemc suggests this would be a good fit for design contractor

**Comment by cassiemc** [comment]
To clarify, I meant the design of the badges themselves would be good for a contractor if we are doing custom work. I'm not sure where @kristinashu has gotten in that process, though. @hannahkane we also have an intern starting Monday Sept. 28 and this could be a good piece for her, but I need to understand the timelines so I can coordinate with other work.

**Comment by hannahkane** [comment]
Seems like @kristinashu has gotten pretty far! There might be some good Thimble stuff that would be a good learning experience for an intern.

**Comment by hannahkane** [comment]
Moving this to the next heartbeat. We've done what we can, but now we're stalled on hiring Souktel and needing to understand if we can move forward with new badge designs, or if we have to stick to the existing design concepts. /cc @davidascher @cassiemc @simonwex

**Comment by OpenMatt** [comment]
* should be unblocked now

**Comment by hannahkane** [comment]
this is unblocked? Can we start working with Souktel, @simonwex ?

**Comment by hannahkane** [comment]
Continues to be stalled by #448

**Comment by hannahkane** [comment]
This is moving forward. Kick-off meeting held + follow up docs sent by @simonwex. Next step is to to hear back from Souktel with implementation plan.

**Comment by hannahkane** [comment]
@simonwex - did we get the implementation plan yet?

**Comment by hannahkane** [comment]
@simonwex - can you provide an update on where we are with this when you have a chance? Thanks!

In the meantime, this ticket will span several heartbeats. Rolling to the next.

**Comment by OpenMatt** [comment]
sounds like @Pomax will pitch in on this this Heartbeat

**Comment by OpenMatt** [comment]
* @Pomax says major workflows now implemented; next step = integrate w. our codebase and put on staging.
* @Pomax: can you update?

**Comment by OpenMatt** [comment]
* would be nice to give Sooktel something to do while we're in Orlando -- but they're blocked on this

**Comment by hannahkane** [comment]
Just spoke with @Pomax and @simonwex. This is looking good—Souktel will be working on the cred.ly API part of this work next week, and we'll make ourselves available to remove any urgent blockers if needed. Rolling to next heartbeat.

**Comment by cassiemc** [comment]
@simonwex Can you give an update here please?

**Comment by cassiemc** [comment]
@hannahkane @simonwex Who owns this one? Feels uncomfortable to leave a P1 without an assignee.

**Comment by hannahkane** [comment]
Realistically, this is @simonwex. I'd be happy to take on more project management work, but so far this has been largely a technical lift.

**Comment by simonwex** [comment]
We have two PRs that represent the Souktel work to date:

https://github.com/mozilla/teach.mozilla.org/pull/1427
https://github.com/mozilla/teach-api/pull/25

These complete most of the MVP badges work, but are still in-progress. Souktel is continuing work over the next couple weeks and should have this complete by the new year.

**Comment by hannahkane** [comment]
Rolling into next heartbeat.

**Comment by hannahkane** [comment]
@simonwex - do you have an update on this?

**Comment by Pomax** [comment]
We got an email update from souktel on this, it sounds like they're close to having a heroku deploy almost ready to go for online testing by us.

**Comment by hannahkane** [comment]
hooray! cc @anmechung @chrislarry33

**Comment by simonwex** [comment]
Moving to next HB, I believe we'll close and open a user-acceptance issue shortly.

**Comment by hannahkane** [comment]
@simonwex @Pomax - any update on this?

**Comment by simonwex** [comment]
Souktel are struggling to do the final integration for us to do acceptance testing. Pomax and jbuck have been helping them finish it off. The ball is currently in their court. If they don't have this resolved next week, I suggest we take it over for what is probably a HB to finish it off.

**Comment by hannahkane** [comment]
Flagging based on lack of updates

**Comment by simonwex** [comment]
Communication with Souktel has stalled. I've communicated that we'll be moving on and completing the work ourselves. I'll file the issues for next week's HB.

**Comment by simonwex** [comment]
:-1:
