### ISSUE TITLE
Design MLN Site research project

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#535]
Background doc here: https://etherpad.mozilla.org/teachresearch

### DARCI ###
Driver: @LauraReynal 
Accountable: @davidascher 
Responsible: @LauraReynal 
Consulted: @hannahkane, @anmechung
Informed: @chrislarry33

**Comment by LauraReynal** [comment]
Hey @hannahkane how is this related / different from #520  ?

I'll prepare something before our meeting next friday and will update you on this ticket.

**Comment by hannahkane** [comment]
@davidascher has comments about scope of work to include

**Comment by LauraReynal** [comment]
\o/ Excited !

**Comment by hannahkane** [comment]
Hey @LauraReynal - sorry I didn't answer your question. #520 is specifically about Club Captains, which are part of the broader Mozilla Learning Network, but not inclusive. MLN also includes Hive leaders, Maker Party hosts, MozFest leaders, and anyone who self-identifies as part of the network (could include both formal and informal educators who are currently unaffiliated with any of our official programs). Looking forward to talking more on Friday.

**Comment by hannahkane** [comment]
Had a good meeting this morning. More specific project description to follow.

**Comment by OpenMatt** [comment]
@hannahkane status?

**Comment by hannahkane** [comment]
@LauraReynal - status? :)

**Comment by LauraReynal** [comment]
Currently working on a proposal - Will share the progress asap

**Comment by LauraReynal** [comment]
I have made progress and shred a draft with Hannah. Reaching out to other folks for choosing location and move this forward. Will paste full proposal here when ready.

**Comment by OpenMatt** [comment]
Moving to this Heartbeat

**Comment by hannahkane** [comment]
Adding @anmechung as a "Consulted" on this ticket, since she has led some MLN research efforts so far

**Comment by LauraReynal** [comment]
cc / @amirad @thornet @chadsansing feel free to ping here if you have any question. 
I'll update this ticket once the dates are sorted out.

**Comment by amirad** [comment]
Great. Thanks Lau! I'll organize the raw data and get back to you with new club locations soon

**Comment by OpenMatt** [comment]
status?

**Comment by LauraReynal** [comment]
Good progress --- The project kicks off on the 27th. Leaving this planning ticket opened until then.

**Comment by ldecoursy** [comment]
@LauraReynal Would you be free to join next week's MLN team call to share the proposal? It's on Wed at 4pm GMT

**Comment by LauraReynal** [comment]
Folks, 

The project is planned to take off on the 27th
- Indonesia : 28th-10th - focus on volunteer community
- NYC : 12-21th Oct - focus on Hive member audience

- We are using the research repo to track our to do lists 
here https://github.com/MozillaFoundation/research/issues/67
and here https://github.com/MozillaFoundation/research/issues/66
If you are interested feel free to cc yourself, but is very detailed planning. 

Closing this ticket.

**Comment by LauraReynal** [comment]
The dates are in the webmaker calendar
