### ISSUE TITLE
Pre-Germany Fundraising design tasks 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#536]
Driver: @edrushka
Design: @lovegushwa 
QA: @cassiemc 
Consulted: @valianttry @adamlofting 

Context: We're launching a localized campaign in Germany at the end of September. There are a number of design tasks, some specific to Germany and some to test/build capacity for the big US-EN push later this year.

Design tasks for this heartbeat include:
-  [Improve Facebook share content] (https://github.com/mozilla/donate.mozilla.org/issues/168)
- [Design wireframes for donation form variations] (https://github.com/mozilla/donate.mozilla.org/issues/227)
- [Identify components of start-to-finish design experience] (https://github.com/mozilla/donate.mozilla.org/issues/236)

as well as consulting on:
- [Make snippet graphic decisions for Germany campaign] (https://github.com/mozilla/donate.mozilla.org/issues/228)
- [Finish brainstorming the January Thank You] (https://github.com/mozilla/donate.mozilla.org/issues/235)

**Comment by cassiemc** [comment]
@lovegushwa Have you guys been through the design brief questions? Maybe you are far past that, but if not this would be good to do in a kickoff. Template questions here: https://github.com/MozillaFoundation/Design/issues/20

**Comment by lovegushwa** [comment]
@cassiemc @edrushka 
We covered most of the brief organically during work week, I just did a quick mental run through of the questions and realized many are product focused. Will do some thinking about how to open up the questions a bit (as assigned by @xmatthewx ). Then perhaps @edrushka and I can do a quick run through.

**Comment by edrushka** [comment]
+1 - Happy to integrate this work into the design team's process as much as possible.

**Comment by edrushka** [comment]
Closing this. @lovegushwa made awesome progress!!! :) :)
