### ISSUE TITLE
donate.mozilla.org Product Enhancements

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#537]
Coninued engineering work on donate.mozilla.org:

This work is part of our migration from BSD to a self-hosted platform, but most of the tasks now represent new and improved functionality on top of what we could do in BSD before.

There are 17 engineering tasks currently assigned to this heartbeat ( after estimation with @alicoding @jbuck @ScottDowne ):

* https://github.com/mozilla/donate.mozilla.org/issues?q=is%3Aopen+milestone%3A%22Aug+28+-+Product+enhancements%22+label%3Aengineering

New product features include:
* A DE mailing list and email opt-in (to date we've only taken email sign-ups for EN users)
* Testing a new mobile donation form, inspired by Wikimedia
* Giving users the ability to switch currencies
* Ability to customize default price prompts / donation arrays based on prior giving or referral source
* Localizing bitcoin and share pages

**Comment by OpenMatt** [comment]
@adamlofting status?

**Comment by adamlofting** [comment]
Great work by @ScottDowne and @alicoding this heartbeat.

Another 2 heartbeats worth of work left before the German Fundraising campaign is live.

**Comment by adamlofting** [comment]
Also great work by @jbuck to make those new features actually visible to the outside world :+1:
