### ISSUE TITLE
change the Webmaker logo on firefox tiles

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#541]
Sorry this is probably not the right place to file this, but I dont know where else. 

The Webmaker logo on the firefox tile is the old one
it also says "we teach the Web" which can be confusing 

@lovegushwa @KevZawacki 

![screen shot 2015-08-21 at 14 47 08](https://cloud.githubusercontent.com/assets/8261945/9409647/e5663672-4813-11e5-83ea-4d5bbe91f534.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/mozilla/webmaker-launch/issues/38
