### ISSUE TITLE
Launch new Thimble

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#542]
This is planned for the first day of the heartbeat  (Monday)

Tasks include:
 - [x] Push to thimble.mozilla.org (planned for ~12pm ET) - @jbuck 
 - [x] Announce at All Hands call (@hannahkane, w/ support from @KevZawacki)
 - [x] Blog post (@KevZawacki)
 - [x] First social media posts (@KevZawacki)
 - [x] Email partners (@ldecoursy)
 - [x] Update relevant FAQs (@hannahkane)

**Comment by OpenMatt** [comment]
* @simonwex  @adamlofting Do we have Google Analytics on the site?
* @davidascher may ask @humphd to write a technical post
* look at Hacker News questions re: privacy policy questions and make sure we have answers for Thimble as well

**Comment by adamlofting** [comment]
> @simonwex @adamlofting Do we have Google Analytics on the site?

Based on the staging site: https://bramble.mofostaging.net - There is no GA in place yet. (it looks amazing though).

There are open tickets related to GA here: 
* https://github.com/mozilla/thimble.webmaker.org/issues/653
* https://github.com/mozilla/thimble.webmaker.org/issues/749

**Comment by hannahkane** [comment]
The new Thimble is live! :fireworks: :tada: :cake: 

Check it out at thimble.mozilla.org. 

Please note: thimble.webmaker.org will continue to be accessible to users for the time being. We added a banner notification, providing a path to the new Thimble for those who want to try it. 

Promotional and comms work to begin shortly. (@humphd's technical post is here: http://blog.humphd.org/thimble-and-bramble/ )

/cc @HPaulJohnson @KevZawacki @ldecoursy @cassiemc @simonwex @davidascher @sabrinang @chrislarry33

**Comment by jgmac1106** [comment]
Congrats to all. Such an amazing job. Thanks to @humphd and the rest of team.

FYI the remix on the old thimble is broken you get this error when you hit remix or try to edit an existing make: 500: TypeError: Object [object Promise] has no method 'success'

**Comment by xmatthewx** [comment]
Congrats everyone. It's a truly beautiful upgrade and it'll be great to sunset the legacy code.

**Comment by humphd** [comment]
@jgmac1106 that's odd, shouldn't have caused any issues in old Thimble. Do you want to file that in the Thimble repo?

**Comment by jgmac1106** [comment]
I will do. I didn't realize they were different repos.

**Comment by KevZawacki** [comment]
Blog live, and Thimble posts up on Twitter and FB.

**Comment by hannahkane** [comment]
FAQ updated

**Comment by hannahkane** [comment]
Donezo!
