### ISSUE TITLE
Webmaker 1.4.0

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#543]
#### Goals
- Monitor content and feedback
- Remedy tech and UX bugs
- Housekeeping

#### RACI
Driver: @xmatthewx
Decision: @davidascher 
Design: @vazquez 
Dev: @gvn @k88hudson 
Services: @cadecairos @ashleygwilliams 
Metrics: @adamlofting 

#### Resources
Milestone – https://github.com/mozilla/webmaker-core/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.4.0
Play store – https://play.google.com/store/apps/details?id=org.mozilla.webmaker&hl=en
Nightly – http://mzl.la/webmaker-nightly

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Need a few days to wrap up this release.

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Shipped to play store for beta testing.
