### ISSUE TITLE
Webmaker Planning

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#545]
#### Goals
 - Learn from Webmaker launch
 - Prep to update strategic plan, product/marketing roadmap 

#### RACI
Driver: @xmatthewx
Decision: @davidascher 
Marketing: @HPaulJohnson 
Community: @secretrobotron 
Research: @LauraReynal 
Metrics: @adamlofting 
Consulted: @simonwex @cassiemc @hannahkane

**Comment by OpenMatt** [comment]
Meeting f2f week of Oct 5 in NYC

**Comment by chrislarry33** [comment]
Is this confirmed to be in NYC?

**Comment by davidascher** [comment]
I hate to say it, but it's possible i have to be in taipei that week.
Finding out ASAP.

**Comment by OpenMatt** [comment]
status of this one? roll over to next milestone?

**Comment by xmatthewx** [comment]
Good progress. Rolling over to continue.

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Launch debrief completed with @HPaulJohnson and team. Draft planning deck prepared. To be reviewed today with @davidascher today and shared out soon after. Elements of both will be included in program review next week. Gathering in NYC planned for week of Oct 12th.

**Comment by xmatthewx** [comment]
reopening to track next phase of planning

**Comment by OpenMatt** [comment]
@xmatthewx shall we close this one, and file a new ticket for any further follow-up?

**Comment by xmatthewx** [comment]
Yes. Debrief is done. Product review is done. Team trip is a planned and starting next week.
