### ISSUE TITLE
Donate.mozilla.org - Getting Production Ready

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#546]
Ongoing work on new donation system by: @alicoding @jbuck @ScottDowne 

This work is part of our migration from BSD to a self-hosted platform, but most of the tasks now represent new and improved functionality on top of what we could do in BSD before.

Some highlights for this heartbeat:

* Feature complete
* Load Testing
* Performance and Optimization Testing
* Security Review
* Stripe Vendor review complete
* And a number of small product enhancements

Follow along here:
https://github.com/mozilla/donate.mozilla.org/issues

**Comment by OpenMatt** [comment]
status?

**Comment by adamlofting** [comment]
Ongoing - we didn't hit all these yet, but have another two weeks of work to do before launch. 

Rolling to next heartbeat to maintain visibility.

**Comment by OpenMatt** [comment]
@adamlofting status?

**Comment by adamlofting** [comment]
Shipping was de-railed by the advocacy campaign, so continues into the next heartbeat.

**Comment by OpenMatt** [comment]
@adamlofting status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by adamlofting** [comment]
Good progress on the development side of this, but blocked on the Stripe Vendor review. I'll close this tracking ticket for this heartbeat though.
