### ISSUE TITLE
Ship "impact statements" 2.0

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#547]
http://mzl.la/learning
As part of Mozilla Foundation 3-year strategic plan, we need to update the draft impact statements and impact milestones. Taking the feedback we got in the last Mozilla Learning call, synthesizing it, and using it to make them stronger.

Project manager: 
* @adamlofting is supporting Advocacy WG
* An-me is supporting the Leadership WG

Consulted: Impact working group. Working with the Advocacy and Leadership working groups. 
cc @RebsD @adamlofting + an-me (does she have a Git Hub account?)

**Comment by OpenMatt** [comment]
Notes from email sent to WGs:

Our next task is to create the impact milestones for our efforts which we can share with the broader group.  It seems to me that our overall impact statement is Good Enough™ ("Many more people understand and care about the internet"), but our impact milestones are not yet tied to dates our numbers, and probably too abstract to relate to our tactics.

Please jump into the document here mzl.la/advocacy_doc under "Possible Impact Milestones" and add or suggest tweaks to the milestones listed.  We can have up to 40, and we'll use that list to provoke discussion, and explain the scope of the tactics we have in mind.

Try to be as specific as possible, and treat these as non-exclusive *options*, but it's fine to be hyper specific to make the point (we can do many of these and they will evolve over time).

If you want to discuss what makes a good impact milestone, Adam stands ready to help.

DEADLINE for this is next Tuesday 9am PT, at which point we'll meet and review.

**Comment by adamlofting** [comment]
Just a note that the text above was sent to the Advocacy WG, but can be translated easily enough to the Leadership group who's doc is here: http://mzl.la/leadership_doc

**Comment by OpenMatt** [comment]
@adamlofting I would say this is done. We may want a "3.0" sprint as well, but let's mark this one done, unless you think that's wrong.

**Comment by adamlofting** [comment]
:+1: agreed, thanks.
