### ISSUE TITLE
Make petition creation silly easy

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#548]
Recently, @ScottDowne created a Sandstone template for petitions: http://lit-scrubland-2076.herokuapp.com/
(code is here: https://github.com/ScottDowne/petition-template)

Now, we can make it extremely easy to create & launch petitions:
1. Make each piece of the template `contenteditable` so that anybody (read: someone who doesn't want to look at code) edit the fields and write the copy or insert the images (?) that they want
2. Have a "request" button that saves the data entered on the page and files a bug to have it hosted.

@jbuck thinks we could make this particularly easy if we grab petitions.mozilla.org (or similar). We can host what we want from there which, for the most part, would be almost-identical petition node apps.

cc @simonwex @valianttry 

(came from thinking about standing up https://github.com/MozillaFoundation/plan/issues/544)

**Comment by xmatthewx** [comment]
What a weird cool idea for a frontend mockup maker.

**Comment by valianttry** [comment]
I :heart: you @secretrobotron

**Comment by valianttry** [comment]
Something to consider: When possible, we want to capture form data in our CRM, including which form was submitted by a specific individual. That way we can target future communications by campaign or topic.

**Comment by secretrobotron** [comment]
> we want to capture form data in our CRM

:+1: i think that'd be the default functionality

**Comment by jbuck** [comment]
We also need to decide a URL where the petitions would live at. Suggestions:

* petitions.mozilla.org
  * @valianttry recommended we not use this because we may not always use a petition format
* takeaction.mozilla.org
  * I suggested this because it's more verby
* actnow.mozilla.org
* act.mozilla.org

@valianttry also pointed out that we should see if there are any naming considerations we need to take into account.

cc @davidascher @simonwex

**Comment by edrushka** [comment]
@jbuck we just decided to keep it on sendto.moz.org. We can use mzl.la to make something snappier for the campaign (if we need it). That cool?

**Comment by jbuck** [comment]
@edrushka for the DE petition that's fine, but this issue is more about petitions in the future. Basically having a non-BSD option available for the next thing that comes up

**Comment by edrushka** [comment]
Great. I should have posted my earlier comment in #544. Sorry!

**Comment by ScottDowne** [comment]
@jbuck petitions.mozilla.org seems the logical choice to me.

**Comment by secretrobotron** [comment]
@alicoding just made me aware that this should plug easily into exacttarget. @adamlofting that sound possible?

**Comment by jbuck** [comment]
@secretrobotron anything is possible, given enough time!

**Comment by adamlofting** [comment]
This project is next on the CRM plan once we finish with the work on https://github.com/mozilla/donate.mozilla.org/issues

See 1:Many Supporter Relationships section here: http://wiki.webmaker.org/CRM

* The email subscriptions opt-ins will live in Exact Target.
* The petition activities will eventially live in Salesforce CRM (which is linked to, but not the same as ET). 
* But there may be some other databse TBD that lives between the front-end UX and Salesforce as the system of record.

We want to build on what we're doing first for donation forms to enable a similiar developer experience / work-flow / shared codebase for many types of online forms.

**Comment by adamlofting** [comment]
Also, this isn't going to happen as part of the CRM project by Sep 11 Milestone.

**Comment by OpenMatt** [comment]
* who's the PM for this? @secretrobotron ?
* status?

**Comment by OpenMatt** [comment]
status of this one?

**Comment by hannahkane** [comment]
@secretrobotron - can we close or update/change milestone?

**Comment by secretrobotron** [comment]
Just spoke a bit with @shaghdoosti. This isn't useful (right now) as a tool for community/others to submit petition requests, but it is useful for us to set up petitions internally very quickly (remove some dev time).

@adamlofting @simonwex did you think about this any more after Sept? What do you think this would look like from a forking standpoint? Can we use some cloning mechanism right inside ET, or could we automatically clone and edit @ScottDowne's repo when a request is made?

**Comment by adamlofting** [comment]
I think we should close this ticket. The Advocacy work kicking off in the new year will determine the scope for what we need to build and when. There will definitely be a petition thing at somepoint, and hopefully it will also be 'silly easy', but let's let that roadmap define the work.
