### ISSUE TITLE
Plan and document roadmap of login.webmaker.org, api.webmaker.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#549]
###  Refactor api.webmaker.org to resolve some problems we introduced in haste to get webmaker shipped for the snippet

api.webmaker.org is the service behind Webmaker Android, Webmaker Desktop, and several administrative clients.

In this roadmap, we’d like to refactor api.webmaker.org to have a significantly more modular architecture as well as adopt new tooling to make the service more maintainable and stable. This will also greatly improve developer experience. Additionally, we’d like to standardize and improve the API response interface to eliminate the need for features such as the bulk endpoint in the short term, while making the requests the API can handle more extensible in the long term.

https://docs.google.com/document/d/1jYj2byLIoHVGx5-_ej6udS2J1LsCcSsrmwBz2yDRUc8/edit#

## RACI
Driver: @simonwex
Accountable: @ashleygwilliams 
Devops/Engineering: @jbuck 
@cadecairos is out this week, but has already contributed to the documents attached

**Comment by xmatthewx** [comment]
Nicely detailed plans. Question: will this be rolled into Webmaker in stages? Or will we switch over all at once? Either way, might be good to identify key moments for communication into the roadmaps.

**Comment by ashleygwilliams** [comment]
hey @xmatthewx, great questions!

we are planning a migration roadmap for api and id, a deprecation roadmap for login. currently, we will be working on these without affecting any of the supporting clients.

for those roadmaps, we'd love to have you involved. i'll be sure to let you know when they happen.

**Comment by seeschwein** [comment]
Hallo. I can't sign in or sign up for Webmaker because I have an account for Thimble/transifex. Is there something I can do? Thank you.

**Comment by xmatthewx** [comment]
@seeschwein - sorry that you're having problems. You can email help@webmaker.org for support. It's possible you will need to [add a password](https://id.webmaker.org/reset-password/).
