### ISSUE TITLE
Get Research Reports online

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#552]
MVP – maybe this is a simple blog post that has all the research reports (and a visual of their covers or insides) with a couple compelling points about each. @laurareynal does this exist already? 

Longer-term it'd be great to see the content from all the research reports actually living online, so that the learnings are more searchable and shareable. Ideally this would live somewhere like research.mozilla.org (does something this exist already? that url has nothing on it), and it would be very visual and human, with lots of stories.

cc @LauraReynal @secretrobotron @HPaulJohnson

**Comment by LauraReynal** [comment]
@cassiemc yes this is in the plans !! I'm glad you are bringing it up. 
@secretrobotron and I have been talking about it this week, and we came out with this plan: 
1. Put everything on a wiki 
Organize content, write some copy etc.
2. Once the content is ready we could see if we can have resources to build research.mozilla.org 

I wanted to document the following content: 

A. Research at Mofo
What we do, why we do it, what we discovered, our published reports and our next projects 
B. Methods 
How we do things, from working with the community to running design workshops 
(lots of people have been asking for this)
C. Personas 
Putting all the user portraits on the same page + user segmentation + user journey etc 
D. The Web journey and other frameworks 


... At the moment im working on B. and for now, the research reports can be found here: 
http://lauradereynal.com/research-reports/

**Comment by xmatthewx** [comment]
This will be highly valuable, and coincidentally something I was thinking about [earlier today](https://github.com/MozillaFoundation/research/issues/64). Glad to see 3 other people thinking about this. I'd suggest using build dot webmaker (which probably needs a new name and URL) to leverage a single platform with related goals. 

This task deserves a RACI

**Comment by jgmac1106** [comment]
I vote for a link in the footer which points to  the subdomain eventually
and to @laurareynal's tagged blog posts until then.

People are looking for the white papers and research.

**Comment by LauraReynal** [comment]
@kristinashu

**Comment by LauraReynal** [comment]
Update for everyone: Kristina and I will be working on an MVP as new d-buds :smile: 

Step 1 : make a single page for research.mozilla.org where we will reference the reports and some other elements. Simple, fast. 

Step 2: define our vision for a website and start working on it.

Closing this ticket so we can organize.
