### ISSUE TITLE
PHASE 1 of the research website.

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#553]
Goal: Create a very simple page where people can download our research reports and other assets. 

**Team:** 
Accountable: @secretrobotron 

Lead Design: @kristinashu 
Lead Dev: @gvn 
Quality: @cassiemc 
Consulted : @LauraReynal

**Comment by LauraReynal** [comment]
@simonwex  can we use research.mozilla.org ?

**Comment by LauraReynal** [comment]
What's in the MVP:

Introduction
Links to reports 
Research Map 
Web Journey Framework 

We will start from there and then add the content as we figure out the website: personas, stories, findings etc.

**Comment by cassiemc** [comment]
Another option for the address is build.webmaker.org/research. The 'webmaker' part of the url isn't correct but it is more inline with how mofo is organized.

**Comment by LauraReynal** [comment]
I was under the impression that build. Webmaker. Org was more for internal audience. 
I think we are looking for something more external facing.  For example,  when we send the reports to partners or potential partner organizations.

**Comment by LauraReynal** [comment]
Pasting here an email with @kristinashu for the bigger part of the work (post-MVP)

>I found a few example of long form digital storytelling to spark some inspiration:
http://www.washingtonpost.com/sf/wp-sports/2013/02/27/cyclings-road-forward/?hpid=z1
http://sports.espn.go.com/espn/eticket/story?page=Dock-Ellis
http://www.nytimes.com/interactive/2014/us/the-way-north.html#p/39
http://www.nytimes.com/newsgraphics/2013/10/13/russia/?partner=rss&emc=rss&smid=tw-nytimesworld
http://pitchfork.com/features/cover-story/reader/daft-punk/
http://pitchfork.com/features/cover-story/reader/panda-bear/

**Comment by jgmac1106** [comment]
Here is an example of how some NGOS in the education place handle the
research page...often called publications:
http://edexcellence.net/publications
http://www.edutopia.org/about/lucas-education-research/publications
http://connectedlearning.tv/case-studies
http://dmlhub.net/publications/

**Comment by LauraReynal** [comment]
@kristinashu here is my very first attempt at a wireframe for an MVP. I guess I would need to do it with real proportions ? We can review it during our d-buds tomorrow !

In order of appearance:
- Image 
- intro text 
- Reports (Title + clickable picture)
- Web Journey (Title + intro)
- Image 
- Get in touch (contact and social or other footer we use)

![img_20150914_202427](https://cloud.githubusercontent.com/assets/8261945/9859529/ff46333a-5b1e-11e5-94ed-17bdfb182bfd.jpg)

**Comment by LauraReynal** [comment]
Ps: I am glad we have 6 reports - it will make aligning easy. 
Ps2: the reports arent aligned but when on the computer, I will align them better.

**Comment by kristinashu** [comment]
@LauraReynal looks great! 

Yeah, don't worry about alignment at this stage. The 6 reports work well but we should plan for future reports and also for other responsive states (as the screen size gets smaller the reports can stack to 2 across and then just 1 across on mobile).

For each report I think we could have: an image, short description, link to PDF, and a link to Flickr.

For the Web Journey and Framework, are you referring to this https://www.flickr.com/photos/laura_nk/21026200550/in/album-72157657717613019/

I like the idea of having social links but I'm just wondering what they would be? 

Talk to you tomorrow!

**Comment by LauraReynal** [comment]
Next steps from our meeting 
- Copy and images = Laura 
- Wireframes = Kristina

**Comment by kristinashu** [comment]
Note, this is the framework referenced above https://www.flickr.com/photos/laura_nk/21214307385/in/album-72157657717613019/

**Comment by kristinashu** [comment]
@LauraReynal here's where I'm at with the wireframes https://redpen.io/p/oj84c5335720112e06
Talk to you tomorrow!

**Comment by simonwex** [comment]
RE: research.mozilla.org – we can try, when you're ready work with @jbuck to get the cname set up.

**Comment by xmatthewx** [comment]
Has this project utilized the project brief? It might reveal a few things.

**Comment by LauraReynal** [comment]
Currently chatting with Kristina, we are thinking Mozfest would be a good and important milestone.

- Goal: Have the page live by mozfest 
  We propose thursday 29th for launch. 

Tentative schedule 
- [ ]  Wireframes done by Friday 25th September 
- [ ] Copy done by Tuesday 29th of September 
- [ ] Kristina will show first round of comps on the October 2nd 
- [ ] Refine and revision  
- [ ] Approved by the 9th 
- [ ] Dev woud starts on the 12th 

What do you think @simonwex @cassiemc ? We outlined something but waiting on your input to finalize. 

@xmatthewx We have done the project brief verbally following the template. Because this is a solution until we get the "real" website going, we will focus on filling the full project brief for the website.

**Comment by kristinashu** [comment]
@LauraReynal I've updated the wireframes https://redpen.io/p/oj84c5335720112e06
Web Journey section now looks more like the pdf version and I've added a 'learn more' link to the Web Journey intro (will link to Chicago report).

**Comment by LauraReynal** [comment]
@secretrobotron is going to lead this task

**Comment by smithisgeneric** [comment]
There may be some additional reports that live else where in Mozilla that may be useful to include.  I.e., the Hive Toronto privacy badges report from last year: http://hivetoronto.org/wp-content/uploads/2014/09/CoDesigningBadgesFinalReport-30March2015.pdf

**Comment by LauraReynal** [comment]
@secretrobotron I added some comments on the copy. Thanks for the first pass !

**Comment by secretrobotron** [comment]
Having a domain conversation here: https://github.com/MozillaFoundation/research/issues/98

**Comment by OpenMatt** [comment]
@simonwex will follw up here

**Comment by OpenMatt** [comment]
* design is complete
* blocked on engineering bandwidth

**Comment by secretrobotron** [comment]
(Next phase in https://github.com/MozillaFoundation/plan/issues/564)

**Comment by secretrobotron** [comment]
WIP here: secretrobotron.github.io/research-website
Desperately needs review, proper responsive code, and a blog to live in.

**Comment by cassiemc** [comment]
@simonwex ^^^

**Comment by simonwex** [comment]
Gavin is going to help get this squared away. I updated the team section above.

**Comment by secretrobotron** [comment]
:boom:!! @gvn, let me know how I can help. Available on IRC/Skype/tin can and string throughout the week.

**Comment by edrushka** [comment]
When TPS regroups in January, let's try to give this ticket one of the orange labels so we can understand where it fits in the grand scheme of things.

**Comment by cassiemc** [comment]
Looks like first comment didn't get updated with team. So I'll assign @gvn and remove the ```needs-dev``` label. Please update if that is no longer accurate.

**Comment by secretrobotron** [comment]
@gvn here's the latest redpen form @kristinashu: https://redpen.io/p/opdb303c31041d13b6

**Comment by gvn** [comment]
@kristinashu Can you hook me up with the PSDs for this page?

**Comment by cassiemc** [comment]
@gvn I'm afraid @kristinashu is off for the holidays already. Check out the drive folder I just shared with you, also at https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLYWw2SjRreFhTYWc&usp=sharing. I believe they are .ai files.

**Comment by kristinashu** [comment]
@gvn do you everything you need? 

@secretrobotron and I were working more out of this ticket https://github.com/MozillaFoundation/research/issues/105#issuecomment-160065908 

Redpen comps: https://redpen.io/p/opdb303c31041d13b6
Illustrator file: https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLeXV0WGtrZmJxQmc/view?usp=sharing

I think all the styling is done for desktop but the narrower screens like mobile still need to be styled. Differences between desktop to mobile:
- title and intro text over the banner image is now down below the image (grouped with the other intro text)
- stack each report text below its image
- reduce font sizes
- stack footer content

Let me know if you have any questions or need any other assets.

**Comment by gvn** [comment]
Yeah I got the comps and am working on building it out as a responsive layout. :+1:

**Comment by OpenMatt** [comment]
@gvn should we move this to the next Jan 15 milestone?

**Comment by secretrobotron** [comment]
Still need a blog for it to sit on. Desperately need that to happen before we leave for Kenya (very, very soon). Think that can still get done in the short term?

**Comment by gvn** [comment]
I'm still working on squaring away the main page, but I hope to move on to the blog portion this afternoon.

**Comment by gvn** [comment]
@OpenMatt I should have this page done today if there's no further design feedback.

**Comment by OpenMatt** [comment]
Thanks @gvn. Let us know if you could use an extra set of hands / any help?

(@simonwex , this one is time-sensitive.)

**Comment by gvn** [comment]
I'm good w. the page build. If anyone wants to pitch in with propping up a Ghost blog that's very welcome.

**Comment by secretrobotron** [comment]
Thanks @gvn. @cadecairos is stepping in to get a Ghost blog up inside our infra.

**Comment by cadecairos** [comment]
I've deployed https://mozilla-foundation-research.herokuapp.com/ using https://github.com/cobyism/ghost-on-heroku

To update the theme we can clone it locally `heroku git:clone --app mozilla-foundation-research` and modify the content directory, then push it back to the app.

**Comment by cadecairos** [comment]
Also, if we ever want to bump the Ghost version, there's instructions here: https://github.com/cobyism/ghost-on-heroku#updating - but it might be better to do it manually, depending on conflicts http://support.ghost.org/how-to-upgrade/

**Comment by secretrobotron** [comment]
Considering the move away from build.webmaker.org, and the fact that doing some sort of redirect from build.webmaker.org/research will be hard, it might be best to host the blog on research.webmaker.org until we have a better grasp on https://github.com/MozillaFoundation/plan/issues/661.

@davidascher @hannahkane: what do you think? Any wiser ideas? @LauraReynal and I can dream up a simple .org domain name this weekend instead if that makes sense for now.

@cadecairos is that simple to do, or will it just cause more mess when we have to tear it down later?

**Comment by cadecairos** [comment]
We might as well wait until we have a final choice for a domain name, and use the heroku domain.

**Comment by gvn** [comment]
Code is ready to deploy once we determine our target for production. It can be pulled verbatim from my gh-pages branch. No special backend setup is needed because it's all static web assets:

https://github.com/gvn/research-website/tree/gh-pages

**Comment by hannahkane** [comment]
+1 on @cadecairos's point—I'm not sure what the immediate need is, but could it be solved by just using the mzl.la link shortener to make a pretty link that points to heroku?

**Comment by secretrobotron** [comment]
@hannahkane @cadecairos ok, we'll go with that for now. Happy to be part of the wider conversation.

**Comment by secretrobotron** [comment]
@gvn can we move your code over to the MozillaFoundation org?

**Comment by secretrobotron** [comment]
Looks awesome: https://mozilla-foundation-research.herokuapp.com/globalweb/

**Comment by jessiekeating** [comment]
This is gorgeous and so great to have all this info in one place! Photos by Laura are stunning.

Jessie Keating
Fundraising Associate, Institutional Grant Writer
Mozilla Foundation
Jessie@Mozillafoundation.org
Skype: Jessie.KeatingNY

**Comment by davidascher** [comment]
I think something's not quite right w/ the bold fonts on Chrome Canary:
<img width="1003" alt="screenshot 2016-01-09 11 41 33" src="https://cloud.githubusercontent.com/assets/51278/12217988/398e4b9c-b6c6-11e5-9869-289595e62718.png">

**Comment by davidascher** [comment]
This is due to a cross-origin restriction in Chrome Canary I think:

<img width="490" alt="screenshot 2016-01-09 11 44 18" src="https://cloud.githubusercontent.com/assets/51278/12217997/5c8e64c4-b6c6-11e5-9c78-bdee0400cbc7.png">

**Comment by secretrobotron** [comment]
@davidascher That's pretty weird. I don't see what you're seeing yet though. What's in your URL bar?

**Comment by davidascher** [comment]
Note this is only with the Canary version of Chrome (i.e. their nightly
build).

**Comment by secretrobotron** [comment]
Indeed, that's where I tried it. Lemme try another machine entirely.

**Comment by secretrobotron** [comment]
Ah, found it. Looks like it might be a bit of a Canary problem, but I fixed the font weight at 600 for those, and it... looks fine.

**Comment by davidascher** [comment]
That's weird (font weight tweak getting around a origin restriction).  But
whatever =)
