### ISSUE TITLE
Mozfest site and app work

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#555]
Deliverables for this milestone are:
- [x] UX/UI changes to schedule app - https://github.com/mozilla/2015.mozillafestival.org/issues/180

**Comment by hannahkane** [comment]
Design/UX work in progress is here: https://redpen.io/jn4056df4f0d941bd9

**Comment by OpenMatt** [comment]
@hannahkane status?

**Comment by hannahkane** [comment]
UX/UI changes are done, but "Our Submission Process" page has been moved to Oct 1, per MozFest team's request.
