### ISSUE TITLE
Disable current badge application flow

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#558]
Users are somehow finding the badge application flow (I'm not sure how) and applying for badges that we are no longer supporting.

Can we prioritize this ticket this heartbeat? https://github.com/mozilla/webmaker.org/issues/1418

**Comment by hannahkane** [comment]
Need some guidance on this. @davidascher - what do you think is the most efficient way to prevent people from applying for Webmaker badges?

**Comment by davidascher** [comment]
1) find where the links are to old badge flow
2) remove them =)

--da

**Comment by hannahkane** [comment]
I don't know how to find the links to the old badge flow. Can somebody grep this, @simonwex?

**Comment by OpenMatt** [comment]
@simonwex question for you here.
@hannahkane move to next heartbeat?

**Comment by hannahkane** [comment]
We didn't do this. Could still use help determining where the links to the old badge flow currently exist.

**Comment by jgmac1106** [comment]
https://webmaker.org/badges/webmaker-super-mentor
https://webmaker.org/badges/webmaker-mentor

This seems to be the pathway I found. I kept trying different words in the
URL and you eventually hit badges with a workflow.

**Comment by OpenMatt** [comment]
@simonwex will assign

**Comment by simonwex** [comment]
I did a bit more digging and it seems we have a few more that are being actively used.

|url | number of visits in the past month |
|-------------------------------------|-----|
| /badges/webmaker-mentor             | 632 |
| /badges/webmaker-super-mentor       | 414 |
| /badges/navigation-maker            | 274 |
| /badges/coding-maker                | 193 |
| /badges/hive-community-member       | 144 |
| /badges/event-host                  | 127 |
| /badges/search-maker                | 131 |
| /badges/fsa-maker-party             | 112 |
| /badges/skill-sharer                | 109 |
| /badges/community-maker             | 100 |
| /badges/open-practices-maker        | 109 |
| /badges/teaching-kit-remixer        | 87  |
| /badges/sharing-maker               | 87  |
| /badges/web-mechanics-maker         | 85  |
| /badges/collaborating-maker         | 76  |
| /badges/composing-maker             | 79  |
| /badges/design-maker                | 66  |
| /badges/security-maker              | 52  |
| /badges/privacy-maker               | 34  |
| /badges/credibility-maker           | 32  |
| /badges/infrastructure-maker        | 35  |
| /en-US/badges/skill-sharer          | 19  |
| /en-US/badges/webmaker-super-mentor | 23  |
| /en-US/badges/webmaker-mentor       | 17  |
| /badges/remixing-maker              | 13  |
| /en-US/badges/event-host            | 10  |
| /badges/                            | 12  |
| /badges                             | 9   |
| /en-US/badges/hive-community-member | 9   |
| /en-US/badges/navigation-maker      | 7   |
| /en-US/badges/coding-maker          | 5   |
| /ru/badges/infrastructure-maker     | 5   |
| ... | ... |

The sources are from a few different places:

 * /StudentAmbassadors/Recognition
 * /activities/web-lit-basics/
 * /demos
 * /learn/beyond
 * /teach-like-mozilla/web-literacy/
 * Various Thimble makes

@hannahkane any comment knowing the additional information?

**Comment by hannahkane** [comment]
@simonwex - thanks. Are all of those sources with webmaker.org as the root? /activities/web-lit-basics/ and /teach-like-mozilla/web-literacy/ seem like they're coming from the Teach site, but I don't see the links to badges from those pages.

Regardless, this is why I don't think removing all the links is the right solution. I think we need to turn off the ability to apply for badges on the badge pages themselves. Is there a simple way to do that?

**Comment by hannahkane** [comment]
@simonwex - could use some more guidance on this. See my questions above.

**Comment by OpenMatt** [comment]
@simonwex we still don't have a plan here.
* question: why not just remove the "apply" button from all pages?

**Comment by simonwex** [comment]
I think removing the "apply" button from all badge pages would stop people from technically being able to apply to badges, but would only leave them abandoned and confused. I think we should do this in two phases.

1. Remove the apply button as Hannah's suggesting
2. track down busy sources and try to turn them off, too

**Comment by hannahkane** [comment]
What if we remove the button AND add explanatory text?

**Comment by simonwex** [comment]
WFM

**Comment by Pomax** [comment]
tracking dev work on this in https://github.com/mozilla/teach.mozilla.org/issues/1253

**Comment by hannahkane** [comment]
Believe this is done. @Pomax - can we close?

**Comment by Pomax** [comment]
forgot this crosslink - yep.
