### ISSUE TITLE
Webmaker Post-Launch Planning & Optimizations

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#559]
There are handful of items that would benefit our retention and optimization efforts even while we are evaluating initial launch results and determining next steps on roadmap and exanded marketing. These items are: 

+ Webmaker.org home page update
+ Automation of retention email(s) 
+ Push notifications
+ FTU experience
+ Improving discovery (via tagging, username, etc) 
+ Tracking/Analytic improvements (tbd) to get better source data in Play store

**Comment by HPaulJohnson** [comment]
cc: @secretrobotron @xmatthewx

**Comment by xmatthewx** [comment]
Good list. I'll have a few additions and clarified priorities for in the app this next heartbeat.

A few notes:
 - First iteration of FTU is done and in review
 - Webmaker.org launch has one blocker remaining:  https://github.com/MozillaFoundation/plan/issues/561
 - Please add analytics needs to https://github.com/mozilla/webmaker-core/issues/573

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Rolling over to next heartbeat to continue this work as we focus on planning process.

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Some progress. We'll have a new release to the play store early next week. We'll plan Q4 roadmap while together in NY. Bumping this to next milestone.

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
Planning is done. Many optimizations are unlikely unless we decide to reinvest. Work for Q4 continues here https://github.com/MozillaFoundation/plan/issues/623
