### ISSUE TITLE
Plan deprecation of login.wm.o

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#560]
We're in a strange state with the dual-login system.

This roadmap will prescribe the steps we’d like to take to remove the last dependency all of our applications and services have: login.webmaker.org. 

https://docs.google.com/document/d/1RnveKYEjfrZRrmR4G6SP5hGzEN-xFt81NsqQqNEaV3Q/edit#heading=h.yahs2pd41tgi

**Comment by simonwex** [comment]
We worked on the deprecation of old services this heartbeat. Moving to next.

**Comment by OpenMatt** [comment]
@simonwex but the milestone still says Aug 14?

**Comment by simonwex** [comment]
Thanks @OpenMatt I went back in time.

**Comment by simonwex** [comment]
Work continuing in #570. This is good to close.
