### ISSUE TITLE
Rewrite /me for project access

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#561]
Webmaker.org includes a tool at /me that allows users to access their makes post-transition of tools. This needs to be rewritten and relocated. 

This blocks the launch of the new webmaker.org site.

### RACI

Driver: @hannahkane 
Decider: @simonwex
Dev: @Pomax 
Designer:

Two opinions open for debate:
 - Tool should probably be located on the teach site. Open for debate. 
 - Design should be absolutely minimal since the tool will gradually drift from essential to dusty relic. 

## TODOs
 - [x] [design ticket](https://github.com/mozilla/teach.webmaker.org/issues/1265)
 - [x] [Implement](https://github.com/mozilla/teach.mozilla.org/issues/1276)
 - [x] Redirect url?

**Comment by hannahkane** [comment]
Assigning myself, not because I'm going to do the work :), but because I'm listed as the driver.

**Comment by OpenMatt** [comment]
next step: @hannahkane and @cassiemc will follow-up on how to assign design resource. Probably half a day of design work.

**Comment by xmatthewx** [comment]
reiterating:

> Design should be absolutely minimal since the tool will gradually drift from essential to dusty relic.

**Comment by cadecairos** [comment]
Can we get some design time put in on mozilla/teach.mozilla.org#1265 ? I'm hoping to get started on the implementation ASAP

**Comment by hannahkane** [comment]
Hey @cadecairos - will bring this up at Teach stand-up today and see if we can prioritize. If you want to attend, it's at 3:30pm ET in my vidyo room.

**Comment by cadecairos** [comment]
Thanks @hannahkane, I'll try to join!

**Comment by hannahkane** [comment]
Design is done, but will likely need to wrap this up in the next heartbeat.

**Comment by OpenMatt** [comment]
* @simonwex will take dev lead on this
* probably can be completed in one Heartbeat (pending review)

**Comment by OpenMatt** [comment]
Status?

**Comment by hannahkane** [comment]
donezo!

**Comment by xmatthewx** [comment]
Yay congrats. And... we need to forward traffic from webmaker.org/me to teach/me. Is that filed somewhere? I think that's the last blocker to launching the new webmaker site.

**Comment by hannahkane** [comment]
@xmatthewx - bleev the ticket you're talking about is here: https://github.com/mozilla/webmaker-core/issues/672

**Comment by hannahkane** [comment]
Who is able to do the forwarding? @jbuck?

**Comment by jbuck** [comment]
Yeah, @cadecairos already landed this feature in https://github.com/mozilla/webmaker-browser/commit/0c577114e0acd8828aae554b129071e68f55a74d, we're just focusing on the thimble migration work right now. I think the only other potential blocker was the [X-Ray Goggles landing page](https://webmaker.org/goggles), which @Pomax is working on and maybe has landed already?

**Comment by Pomax** [comment]
@jbuck goggles prod lives on x-ray-goggles.herokuapp.com now, so we can put the relevant redirects in place to make sure things point to the location.

I assume we'll want to do that as a goggles.mozilla.org domain, pointing to heroku, and then have both webmaker.org/goggles and goggles.webmaker.org point to that domain instead.

**Comment by jbuck** [comment]
Yes, lets get that rolling. I filed https://github.com/MozillaFoundation/mofo-devops/issues/228

**Comment by hannahkane** [comment]
I don't think this has happened yet, so moving to next milestone.

**Comment by OpenMatt** [comment]
@xmatthewx will organize quick IRC chat with @jbuck + @simonwex on this

**Comment by xmatthewx** [comment]
Is there anything blocking a redirect from webmaker.org/me to its new home on the teach site?

**Comment by OpenMatt** [comment]
@simonwex says @cadecairos will do the re-direct

**Comment by xmatthewx** [comment]
@cadecairos - is this something you can tackle before the holiday break?

**Comment by cadecairos** [comment]
Nope, we're blocked on shipping the new goggles by an RRA (Rapid Risk Assessment) by moco infosec. It's scheduled for the week of January 4th.

Once that's done we can move beta.webmaker.org to webmaker.org, completing the redirect.

**Comment by hannahkane** [comment]
RRA is now scheduled for the 15th, I believe, so this is still blocked. Moving to next heartbeat.

**Comment by hannahkane** [comment]
I believe this is unblocked now. Correct, @cadecairos?

**Comment by cadecairos** [comment]
indeed it is!

**Comment by xmatthewx** [comment]
Unblocked now. Moving to next heartbeat for implementation.

**Comment by hannahkane** [comment]
@cadecairos - are you able to do this this heartbeat?

**Comment by hannahkane** [comment]
@simonwex - suggest moving to next heartbeat as a P2, given the many other priorities. What do you think?

**Comment by simonwex** [comment]
Will update for tomorrow.

**Comment by simonwex** [comment]
[Done!](https://github.com/mozilla/webmaker-browser/pull/228/files)
