### ISSUE TITLE
Migrate recovered Discourse data to new instance 

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#562]
New Discourse is live, but we still need to transition the recovered data. Waiting for @simonwex to share staging site so I can start identifying what to migrate, and where existing posts/threads will live in the new category taxonomy.

**Comment by ldecoursy** [comment]
@simonwex Can you share an update on next steps please?

**Comment by chrislarry33** [comment]
@simonwex let us know how to proceed?

**Comment by simonwex** [comment]
Hey folks, I just finished TRIBE and am heading home this aft. I'll find some time to write in a meaningful update this eve.

**Comment by ldecoursy** [comment]
Checking in @simonwex

**Comment by OpenMatt** [comment]
@simonwex status?

**Comment by simonwex** [comment]
I made minimal progress here because of some unforeseen events. I've got the styling and posts data exported and will see if the community team has time to take this over next week.

**Comment by OpenMatt** [comment]
@simonwex move to Oct 9 milestone?

**Comment by ldecoursy** [comment]
Moving to next milestone to determine status/next steps.

**Comment by ldecoursy** [comment]
@simonwex status? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by ldecoursy** [comment]
@simonwex ensures that data is not lost, but still some work to do.

**Comment by ldecoursy** [comment]
Moving to next heartbeat so we can consider if/how to resource given current priorities.

**Comment by ldecoursy** [comment]
Requires one dev for a full week

**Comment by OpenMatt** [comment]
Next step: make a final decision about how best to proceed in this heartbeat, after Orlando

**Comment by simonwex** [comment]
@ldecoursy let's chat about this in Orlando. I think it'd be worth looping Amira in to also talk about the loss of Minigroups and how valuable old data is.

**Comment by ldecoursy** [comment]
Spoke with @chrislarry33, and current decision is not to move forward with trying to migrate the old data. This is based on the fact that it would require too many resources (time + money) and we just don't have a clear enough picture of how relevant/valuable the recoverable data is. @simonwex assures me our current instance of Discourse is  stable so this shouldn't happen again.
