### ISSUE TITLE
Create an umbrella page / website about our fellowships 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#565]
Goal: create an umbrella page to guide visitors through our different fellowship programs

http://fellows.mozilla.org/

would be a place to describe our work, our mission and link to:
- Science Labs fellowship program
- Advocacy 
- Open news 
- Design Research (TBD)
- Others 
...

Thoughts ? @chrislarry33 @brettgaylor @thornet @kaythaney @Melechuga 
@HPaulJohnson

**Comment by chrislarry33** [comment]
May want to open up dialogue with MDN to about their fellowship program.

**Comment by LauraReynal** [comment]
This might be a huge work, but it would be harmonious to have something like

fellows.mozilla.org/advocacy
fellows.mozilla.org/design
fellows.mozilla.org/news
fellows.mozilla.org/MDN

etc. 

Just wanted to throw this out there for discussion.

**Comment by cassiemc** [comment]
closing, no longer up-to-date with new strategy
