### ISSUE TITLE
Mine grant reports for impact stories

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#567]
## Goal
* comb through our last five years of grant reports to collect a list of achievements to fuel a) our Mozilla Learning plan, and b) 5-year MoFo retrospective story / chronicle https://github.com/MozillaFoundation/plan/issues/566
* we include great impact stories in these reports (e.g., Ford Web We Want grant report) but don't do enough to re-purpose / leverage them 
* could even just be a lists of good annotated headlines as a start. Well organized and annotated repos that we can use often is something we need to get better at as an org.

## Roles
* Decision-maker: @msurman 
* Project manager: @OpenMatt
* Responsible: @benrito 
* Informed: @chrislarry33 

## Questions
* can @bhuvanshri help with this? 
* should we also hire a contract researcher who knows us well? 

## Next steps 
This work will be a three-step process: 
1) discovery of reports, 
2) contextualization of the many reports, then 
3) normalizing into a impact reporting template. 

@benrito 's will try to squeeze this into his upcoming Toronto trip (dates?)

**Comment by bhuvanshri** [comment]
Yes, I will help @benrito on this while he is in Toronto

**Comment by bhuvanshri** [comment]
+ @metaphorista, are there other sources you would suggest we consider for this ticket?

**Comment by benrito** [comment]
We’ve scheduled an initial block for Monday. Don’t think we’ll want to hire anyone to help with this at this stage.

**Comment by cassiemc** [comment]
Would be interesting to brainstorm this with the design team to see what format this could take. Happy to help set that up @OpenMatt if it sounds interesting to you, whenever you're ready.

**Comment by benrito** [comment]
What we have talked about for a while is a refresh of mozilla.org/foundation <http://mozilla.org/foundation>, which is currently terrible.

A sort of governance and impact reporting brochure site, which it’s amazing that we still don’t have.

I actually think some advice from design would be helpful to keep in mind as we capture the information.

For instance, could we imagine a grant reporting template that has like:

•big beautiful image
•key accomplishment
•secondary accomplishment
•description of work
•links

And make sure there’s a simple page or <section> for each?

**Comment by HPaulJohnson** [comment]
RE: refresh of mozilla.org/foundation, there was a complete overhaul of the entire mozilla.org site planned earlier this year but that's been put on the shelf until early 2016. In the mean time, we are in the process now of at least updating the copy on that page.

**Comment by benrito** [comment]
Awesome, good to know—is there a ticket to track that work?

**Comment by HPaulJohnson** [comment]
Yes, copy update happening here: https://github.com/MozillaFoundation/plan/issues/378

Larger redesign project is being led by MoCo with us as a stakeholder (and isn't in github).

**Comment by metaphorista** [comment]
I'd love for us to track and share how our lives on beyond the project period.
This is an old article, but this kind of data would be incredibly useful describing the sustained impact of our work (especially this quote "  The fellows have created more than 50 software projects, including the popular Tabula (a tool for taking data out of PDFs), which is used by more than a dozen news organizations from ProPublica to The New York Times. The project’s training programs and workshops have further brought together developers and reporters across the world to collaborate on problem-solving. Additionally, Source, an OpenNews Web publication, has allowed developers to share code and journalism tools with tens of thousands of people."
http://www.knightfoundation.org/press-room/press-release/knight-mozilla-effort-foster-newsroom-innovation-4/

**Comment by metaphorista** [comment]
Also wondering if it makes sense to use MSC as the structure of telling our story.
illustrative impact on Hive a student https://www.youtube.com/watch?v=sclPDZglZ-g
Illustrative impact on educators https://www.youtube.com/watch?feature=player_embedded&v=L2bvc7o5ipo
combined with this sort of data https://blog.webmaker.org/infographic

**Comment by metaphorista** [comment]
FWIW - set up google doc of impact stories I use - it's https://docs.google.com/a/mozilla.com/document/d/1oByebPoObfsEVJrhsdc0qrIhZH5e9lCcHJv_tDGqzfY/edit?usp=sharing

**Comment by chrislarry33** [comment]
@OpenMatt this might be a good thread to re-paste that article you shared a few months ago on the power of stories as viable metrics

**Comment by OpenMatt** [comment]
* @cassiemc design work would be much appreciated. Esp: to highlight human element. But the ticket for that is this: https://github.com/MozillaFoundation/plan/issues/566
* This ticket is about mining stories that will feed into that article / chronicle piece

**Comment by OpenMatt** [comment]
@chrislarry33 @metaphorista : "Most Significant Change" = a way to turn human narratives into a methodologically rigorous form http://betterevaluation.org/plan/approach/most_significant_change
* key question it raises is: what's the right template to use for these stories? To get maximum methodological bang for buck. 
* @metaphorista : proposals? Already baked into your google doc?

**Comment by OpenMatt** [comment]
* Moving this to Oct 9
* @bhuvanshri : what is the status of this work?

**Comment by bhuvanshri** [comment]
The work plan has a detailed scope now. Quoting @benrito here from his email for status update:
"Here’s our intention for the Chronicle project getting started next week. The meat of this is ~25 profiles ala “faces of Mozilla” or CC’s “Team Open.” Each profile will be 400-600 words + headshot/action shot. Some will be pairs or groups (i.e., Jess & Atul) to highlight collaboration.

The list of names is getting good: https://docs.google.com/spreadsheets/d/1Kai28T3rdKqT6fNxqY7InBQy1WJA701lKjxYs50wpRM/edit#gid=0 (tab #3)"

**Comment by OpenMatt** [comment]
* Let's close this ticket and push ahead with the work in: https://github.com/MozillaFoundation/plan/issues/577
