### ISSUE TITLE
Open Web fellows - close host org and update mobile

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/plan#571]
On October 9th we'll close applications for host orgs so will need to take down the open call.

We've also discovered some issues with the site on mobile that we'd like to fix at the same time.

Driver: @brettgaylor

**Comment by cassiemc** [comment]
@brettgaylor @Melechuga Does this need design?

**Comment by brettgaylor** [comment]
No

**Comment by OpenMatt** [comment]
@simonwex please assign a dev? (@brettgaylor which dev worked on this in past?)

**Comment by simonwex** [comment]
Who will be the driver on this? What sort of mobile issues? I think Alan can help here.

**Comment by OpenMatt** [comment]
@brettgaylor blocked on some more detail from you on scope of work

**Comment by brettgaylor** [comment]
So what we need to do here is:
-Fix the layout issues on mobile as seen in this screenshot (Firefox for Android)
-Remove the link on the front page, and each child page, to the 2016 host org application
![screenshot_2015-10-08-16-13-08](https://cloud.githubusercontent.com/assets/345974/10382337/ce5ac60c-6dd7-11e5-961a-6370dd3863d2.png)

**Comment by brettgaylor** [comment]
@OpenMatt @simonwex do you think we could fix this stuff by next Monday the 12th (or 13th if Thanksgiving is an issue)

**Comment by OpenMatt** [comment]
this one's all @simonwex

**Comment by OpenMatt** [comment]
@simonwex will follow up w. @brettgaylor on this

**Comment by simonwex** [comment]
@alicoding is going to give this a go. Thanks, @alicoding!

**Comment by brettgaylor** [comment]
@alicoding this page also has different formatting issues on mobile:
https://advocacy.mozilla.org/get-involved/

Could you have a look?

**Comment by cassiemc** [comment]
@brettgaylor can you close or update this please?
