### ISSUE TITLE
Page break on Landscape Pages of Chicago Report

### ISSUE THREAD

**Issue by jgmac1106** [MozillaFoundation/plan#572]
More of a personal preference than an issue but for the Chicago Report can you break up the pages for the Online PDF rather than using the "print preview." It makes reading and annotating easier.

![page break](https://cloud.githubusercontent.com/assets/10534566/10020070/f302a25c-610e-11e5-833b-5eb7ae254e0e.png)

**Comment by LauraReynal** [comment]
Ahhhh I see. 

This is intentional. I think it helps the structure and perception of the information. 
Also, I use it a lot in the past for having text on the left and picture on the right to illustrate the point. 

But I know @cassiemc also wanted to break the spreads.

**Comment by cassiemc** [comment]
Page by page is a good idea for online viewing. Readability trumps context in this case, and the redesign broke out the pages so they were still sensible page-by-page. I've uploaded new files so this should be resolved when @LauraReynal updates the links, via https://github.com/MozillaFoundation/Design/issues/96

**Comment by cassiemc** [comment]
@jgmac1106 I lied – @LauraReynal and I decided to tackle a page-by-page design in the next report, as this one has some layout concepts that tend to break without the spread view. It'll be top priority for next report though!
