### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by bhuvanshri** [MozillaFoundation/plan#574]
#### Roles
* Project manager: @openmatt
* Decision-maker: @msurman 
* Accountable: @bhuvanshri 
* Consulted: @geroter

File to track the process: http://mzl.la/benchmarks

### Orgs to benchmark
for October board meeting: 

P1
- [x] Engineers Without Borders: http://mzl.la/EWB
- [x] World Economic Forum: https://docs.google.com/a/mozilla.com/document/d/17ml-BxvUiybetkE5SuC5sUWS3kv5gvqh-uPO0h-YQmA/edit?usp=sharing
- [x] 350.org: https://docs.google.com/a/mozilla.com/document/d/1IkBHbjTVkXDsiJ4aYXytbMwdnPnaIk0EJwU3WsAdxLQ/edit?usp=sharing
- [x] Consumers Union: https://docs.google.com/a/mozilla.com/document/d/1eIdxIUTcSeATMw3_tIgEMjCKn7LNYLcrJuGXAszZvsI/edit?usp=sharing

P2
* Teach for America
* Change.org (Andrea)

P3
* Ashoka
* Shuttleworth
* Earth University
* Habitat for Humanity
* Greenpeace (including: their Mobilization Lab / Participation Lab) 
* WWF
* Sierra Club

#### Others to consider:
* McKinsey (George)
* Aspen (Mark)
* One.org (George)

**Comment by bhuvanshri** [comment]
Cc: @OpenMatt, @benrito, @msurman @chrislarry33 @davidascher @thornet

**Comment by bhuvanshri** [comment]
Cc @brettgaylor - Based on our last conversation about looking at some other orgs and how they think about leaders, I assume you would like to track this ticket as well.

**Comment by OpenMatt** [comment]
From Mark via email: 

George has offered to help w/ design and feedback on some of the benchmarking work. He might also be able to do one on one interviews w/ leaders from orgs in question where is knows people.

On practical first step idea in this: do a case on Engineers Without Borders, doing quick desk research into a template and then 'interviewing' George as an outside CEO.

Can you guys reach out to George to figure out the best way to manage?

- ms

PS. Some specific inputs from my conversation w/ George this morning:

1. Potential benchmark data gathering template

Model (one line)
Impact
Influence
Offering
Secret sauce
Staff (# and who are they?)
Volunteers (# and who are they?)
Budget (all)
Leadership dev budget (only)
Alumni network
Events
Publication

2. Suggested main set of benchmarks w/ person who can help w/ each:

McKinsey (George)
WEF (Mark)
Aspen (Mark)

One.org (George)
350.org (Mark or Natalie)
Change.org (Andrea)

**Comment by geroter** [comment]
Adding myself!

**Comment by OpenMatt** [comment]
## 1. Benchmark data-gathering template

* Model (one line)
* Impact
* Influence
* Offering
* Secret sauce
* Staff (# and who are they?)
* Volunteers (# and who are they?)
* Budget (all)
* Leadership dev budget (only)
* Alumni network
* Events
* Publication

## 2. Suggested main set of benchmarks w/ person who can help w/ each:

* McKinsey (George)
* WEF (Mark)
* Aspen (Mark)

* One.org (George)
* 350.org (Mark or Natalie)
* Change.org (Andrea)

**Comment by OpenMatt** [comment]
Key question: what is the deadline for this work? Before Oct 14 board meeting? Or for phase 3 business plan?

**Comment by OpenMatt** [comment]
@bhuvanshri next step: set up a meeting w. George and fill in the template.

**Comment by OpenMatt** [comment]
@bhuvanshri has this meeting been scheduled?

**Comment by OpenMatt** [comment]
Time is running out for this. Given the need to book interviews w. busy executives, @bhuvanshri this should be your top priority. 

### Next steps
* finalize the list. of comparable orgs we want to benchmark against. in this ticket.  
* book the executive interviews (Bhuvan + Phia) 
* take notes during those calls (Bhuvan)
* write them up (Bhuvan) 
* pull relevant data / insight into board deck (Mark)

**Comment by OpenMatt** [comment]
### List of orgs
need to finalize this:

#### Leadership 
P1
* Engineers Without Borders
* World Economic Forum 
* Ashoka
P2
* Shuttleworth
* Earth University

#### Movement
P1 
* 350.org (w. a big focus on their leadership dev work and how it ties)
P2
* Greenpeace (including: their Mobilization Lab / Participation Lab) 
* WWF
* Sierra Club

**Comment by bhuvanshri** [comment]
Interviewing @geroter tomorrow afternoon. Will link the results here EoD tomorrow.

**Comment by OpenMatt** [comment]
Next steps:
* ensure we agree on the fundamental designs that we want to share with the board as different options
* and do we have the right P1 benchmark tied to each

**Comment by thornet** [comment]
In Dec 2014 @amirad Simona @ldecoursy An-Me and I interviewed a number of orgs that might benefit this benchmarking: 

https://docs.google.com/spreadsheets/d/1JvIm1nAVBqtbOTwEpwzc_WyGL11Sx3QG5zSGUy1SQk8/edit#gid=0

* Free the Children
* Code Club 
* Coder Dojo
* Hour of Code/Code.org
* Organizing for America:
* Code for America Brigades

**Comment by bhuvanshri** [comment]
Interview with @geroter on EWB: https://docs.google.com/a/mozilla.com/document/d/1AkKGkXEI0lKhs98KZwDScH9YqILblBJTSBvYf5-_jg4/edit?usp=sharing

**Comment by OpenMatt** [comment]
@msurman can you review this sample to see if it's in line w. what you want? http://mzl.la/EWB

**Comment by OpenMatt** [comment]
@bhuvanshri see updated P1 org list above

**Comment by OpenMatt** [comment]
@bhuvanshri also note: some 350.org bechmark data is already here: http://mzl.la/more_benchmarks

**Comment by OpenMatt** [comment]
@bhuvanshri status update?

**Comment by OpenMatt** [comment]
Some 350.org stats:
• Global Power Shift Groups: 600 youth activists from 135 countries
• 132 clubs worldwide: http://350.org/map/
• 188 cities involved in 350.org club organization
• Annual Report: 350.org/about/2013-annual-report/
• 77 staff members globally, main headquarters located in Brooklyn, NY
• Before any group starts a club they must read and agree to the 350 Manifesto: http://350.org/350-manifesto/"

**Comment by OpenMatt** [comment]
* if WEF is hard, consider swapping in Aspen@bhuvanshri another route

**Comment by bhuvanshri** [comment]
@OpenMatt Budget numbers are not an issue. Both have annual financial reports I can refer to.

**Comment by bhuvanshri** [comment]
P1s are all done. Have emailed Mark the links as well.

**Comment by OpenMatt** [comment]
Marking this as done.
