### ISSUE TITLE
Update Demos info

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#575]
We need to update the info at the top of this page: http://book.webmaker.org/demos.html

- New etherpad: https://etherpad.mozilla.org/
- New Vidyo room: #MoFo
- New Public Vidyo link: http://bit.ly/mofodemos
- Remove the calendar link
- waiting on a Service Now ticket for a new airmo link

The text below re. demos structure can stay the same.

@simonwex @OpenMatt What's the easiest way to do this?

**Comment by simonwex** [comment]
@cassiemc super easy to change, let me know when you have the updated info. If you feel comfy, you can change it here: 

https://github.com/MozillaFoundation/book.webmaker.org/edit/master/demos.md

**Comment by cassiemc** [comment]
For sure, I can definitely do that. :+1: Thanks for the link!

**Comment by cassiemc** [comment]
This is done, can be seen here: https://github.com/MozillaFoundation/book.webmaker.org/blob/master/demos.md
