### ISSUE TITLE
Leader Stories

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#577]
#### Goal: Collect a highlight reel of leadership development impact stories for the board deck. 
* Showing how the Mozilla Foundation's past 5 years of work have impacted individuals, organizations, and the world. 
* Goal is to produce about 10-12 great stories. So that Mark can pull about 5. Using the criteria and guidelines below. 
* Grist is gathered in this spreadsheet: http://mzl.la/stories 

#### Next steps
- [ ] Produce a short-list.
- [ ] Produce one model story. Try to get done by tomorrow (Wed): do *one* model story. To show what we're thinking.

**Comment by OpenMatt** [comment]
### Three levels of impact
1) individuals (p1) 
2)  organizations (p2) 
3)  the world (p3)

### Diverse mix
Ideally, we want a diverse mix of: 
* teaching / web lit 
* advocacy 
* tech / innovation

#### Bonus points: 
* stories that include numbers / evidence (not essential -- just bonus). stuff that *statistically* shows participation. (e.g., Mozfest had x participants, y facillitators, etc.) 
* a story or through-line you could pull through all three categories: individual, org, world. 
* non b.s. stories that are a little surprising
* not staff (past or current) (some staff stories are ok; but those are less likely to make it into the board deck)
* make the case we have introduced a new set of volunteer-driven activities / participation areas into Mozilla 

#### Narrative
*   These people graduated from the Mozilla Leadership network and have a better career / have done something awesome that *they* care about...
* ...and that Mozilla cares about
* they could read like Mozillian profiles / fake news stories

**Comment by OpenMatt** [comment]
Pulled from Chronicle / successful leaders / Octogenarian thread http://mzl.la/chronicle
Partners / orgs / Hive / MozFest org partners, etc
5 - 8 orgs we could choose from
Our network has grown stronger. A bunch of our practises have changed. 
how does leadership dev work affect Mozilla as org and other orgs? describe that change. 
 e.g, open work practises (open calls, etherpads, transparent planning / goal-setting, git hub moz fest planning, etc) 

The world (social change) (p3)
Established web literacy field
Won some victories in Net Neutrality
Something about a coalition? Convening / bringing together a different coalition?  
What else? (And how does it tie back to leadership dev?)
How many people talking about web / digital lit now vs. then? 
Examples of people spending money based on our advice?

**Comment by OpenMatt** [comment]
## Next steps
* We're gathering this stuff in too many places. We need to establish a single canonical home for this.
* @benrito suggests using this spreadsheet: http://mzl.la/stories
* @benrito @bhuvanshri can one you take the lead on making sure everything in the "Octogenarian" email thread is captured in that spreadsheet? 
* @chrislarry33 @thornet @ldecoursy Learning Networks has solid gold on this stuff that we need to make sure we include. I know some of it is already in blog post / slide deck form. Let's get it captured in this thread then figure out best way to integrate?

**Comment by benrito** [comment]
Bhuvan, if you have time, I’ve compiled it all here: https://etherpad.mozilla.org/octogenarian <https://etherpad.mozilla.org/octogenarian>

Lynn @metaphorista has consulted with a few of the Learning networks folks to help here

**Comment by OpenMatt** [comment]
Next step:
* Matt will schedule a kick-off for Monday

**Comment by ldecoursy** [comment]
@amirad An-Me too.

**Comment by OpenMatt** [comment]
* Next step: @benrito will schedule a meeting w. key stakeholders here. As per his email. @bhuvanshri can help.

**Comment by OpenMatt** [comment]
* What we need by Friday: 8 - 10 quality stories, meeting the criteria listed above. 
* Next step: turn the 120+ names in the spreadsheet into a short list of 10 -15 that we think we can have ready for Mark to choose from by EOD Friday. 
* Matt will schedule a meeting to tackle this together as a sprint.

**Comment by OpenMatt** [comment]
@benrito I sent a calendar invite out for this on Wed

**Comment by OpenMatt** [comment]
Try to get done by tomorrow (Wed): do *one* model story. To show what we're thinking.

**Comment by OpenMatt** [comment]
This report in progress from Katilin has more: [20150904_mozilla_fellowship_programs_report.pdf](https://github.com/MozillaFoundation/plan/files/5152/20150904_mozilla_fellowship_programs_report.pdf)

**Comment by benrito** [comment]
My understanding is that it’s Jeff’s report—would be great to mine and also get Kaitlin’s feedback (as she’s not been consulted to my knowledge)

**Comment by bhuvanshri** [comment]
@OpenMatt Stories in https://etherpad.mozilla.org/octogenarian etherpad have been added to the spreadsheet

**Comment by OpenMatt** [comment]
Lots of new stories added by various staff. Next step: @OpenMatt will review and edit Monday morning.

**Comment by OpenMatt** [comment]
### Next steps
* whittle down the list further (Matt + Ben) 
* write two-bullets for each
* these are people who: caught the mozilla bug. have been an important ally. impacted their career. 
* represent our three tiers. from student to champion. 
* also: need one strong leadership example from the Policy side. (Matt: email Andrea + Jochai) (ideally: an executive director. Kevin Banks? Gene Killman?)

**Comment by OpenMatt** [comment]
###Tiers
* Champions
* Executives
* Professionals
* Emerging Leaders
* Young Leaders

**Comment by OpenMatt** [comment]
### Next steps
@msurman : can you take a look at this "short short list" of five / six proposed leader stories? http://mzl.la/very_short_list
* proposal is to show the range all the way from "young leader" to "executive" 
* with the right mix of diversity and key boxes ticked
* could do 2/3 on "professionals" category, to show breadth and add more diversity
* still need to wordsmith / fact-check bullets. just want to check and see if ballpark approach seems right.

**Comment by OpenMatt** [comment]
### Feedback from Mark 
* This is in the right direction. 
* Do two stories at each level

#### Thing we want to show is: 
- Initial state
- What they learned
- What they are doing now that contributes to our agenda, either directly or indirectly. 
* We need that kind of arc for everyone. Good personal outcome. 
* What's there is uneven on this front right now.

#### Stories:

Executives
* For Executives, do Gene and Connie. Also, Darren Walker. 

Champions
* For champions, I vote Massimo Banzi. + a woman at the champion level.

Professionals
* For Humph, he started CDOT before MoFo. Need to have slightly different copy. 
* Also, at this level, what about some of best Hive *members* or program leads. Feels like that's rich and missing. E.g. Lesser. 

Emerging Leaders
* Emerging leaders level seems weak. What did Livia actually do? How is she moving our agenda forward now? Maybe it's there but I don't see it in the copy. Maybe Harlo instead?

**Comment by OpenMatt** [comment]
@benrito status update on this one? This ticket is the one I'm most worried about getting right in time.

**Comment by OpenMatt** [comment]
* Needs final copywriting work.

**Comment by benrito** [comment]
Closing. Final work will take place in https://github.com/MozillaFoundation/plan/issues/608
