### ISSUE TITLE
Gear Store content and creative for autumn push

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/plan#579]
Driver: @HPaulJohnson (is this right @valianttry?)
Dev: <-- is this needed?
Design: @natalieworth (with QA from @cassiemc)
L10N: n/a
Decision-maker: @valianttry 
Consulted: @cassiemc @KevZawacki Todd Lido

--------

List of issues can be found here: https://github.com/MozillaFoundation/2015-fundraising/labels/Gear%20store

--------

Gear.mozilla.org has great new merchandise, but we haven't done much marketing for over a year.

We want to do a big holiday push ahead of Christmas shopping season across many channels. We have all the gear professionally photographed and the photos are available for us to use. Here's a quick list of things we would need:

-- Social graphics (twitter and FB)
-- Graphic email design
-- Mozilla.org homepage graphic (MoCo may take this)
-- Facebook ads (we want to test paid ads)
-- MoCo will likely take on some of the creative for their own channels
NOTE: The gear store is managed by our vendors (gear.mozilla.org) and we don't need to do anything in terms of design or dev to the store itself.

There's a lot of new gear we can promote, we've basically more than doubled the inventory available:

- New women's T-shirts:https://www.evernote.com/l/AMoVYE_S0zZIe7NZgcRmDHBkpFbPtzyD58kB/image.png
- Firefox plushie: https://www.evernote.com/l/AMoNWcT71nNKO5fvi2MECATjx_t89mAyqAsB/image.png
- New Firefox cap
- New hoodies coming to the store shortly

Here is a sample promotion from Firefox+You:
![firefox_t-shirts_are_here__-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/10103951/c2c6d2f8-635b-11e5-92c7-aa86bff3b75a.png)
cc @cassiemc @KevZawacki

**Comment by cassiemc** [comment]
Great! This needs a RACI (below) Also @valianttry what is the proposed timing?

Driver: 
Dev:  
Design: 
L10N: ?
Decision-maker: 
Consulted:

**Comment by valianttry** [comment]
The holiday shopping push is for Canada and US only (so, EN) because shipping to other locales is much less predictable. Also, the store is only in EN at the moment.

Last ship date to receive before Christmas would be December 14, but let's aim for launch mid-November, then do some repetition of promotions (or cycle in new more urgent "order in time for holidays" designs) in early December.

**Comment by valianttry** [comment]
cc @HPaulJohnson @KevZawacki

**Comment by valianttry** [comment]
This folder shows the new gear that we have not marketed to the community, also included is a zipped folder of images of new hoodies that are set to land in the store within weeks.

https://drive.google.com/open?id=0B_VT8vv8uni5YllpWFpMNlZiQVVwVV9Ha0hVREhxY1VKeDNJ

**Comment by KevZawacki** [comment]
@valianttry Once the new gear hits the store, OK to use the photos across social?

**Comment by valianttry** [comment]
@KevZawacki the photos are ours and approved to use however we want.

@cassiemc and @natalieworth I found an old redpen with a bunch of designs @sabrinang worked on here:
https://redpen.io/p/ofa2032bab34154728

**Comment by cassiemc** [comment]
Let's start tracking individual bugs in the Fundraising repo: https://github.com/MozillaFoundation/2015-fundraising/labels/Gear%20store

Assigning @HPaulJohnson as driver, I believe that's what we agreed in our Sept 29 kickoff.

Also assigning the November 20 milestone. We talked about mid-November and that was the corresponding heartbeat and seems most realistic given Mozfest. @valianttry can you confirm this works with our holiday fulfilment dates?

**Comment by edrushka** [comment]
This project is un-paused and is moving ahead! :dancers: Meeting on Tuesday Oct 20 to finalize the timing of the campaign (Black Friday? Holidays Season?), define the scope of work, and create a list of design deliverables.

**Comment by HPaulJohnson** [comment]
Update: 
* New items live in Store
* Promotional banners on Gear.mozilla.org updated/live
* MozFest promo distributed
* Social Media assets are complete and will move into rotation starting this week
* Directory Tile will be live this week and run through end of year. 
* Mozilla.org Tile live
* Email being finalized, on track for 11/30 send. 
* Internal comms communicating discount to happen week of 11/30.

**Comment by OpenMatt** [comment]
* Moving to Dec 4
