### ISSUE TITLE
Bangladesh Field Report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#58]
Release field report from Bangladesh research trip. :earth_asia: 

Phase: Research / Build / Ship
Owner: @laurareynal
Decision: @davidascher 
Lead design: @thisandagain
Lead dev: n/a
Quality: @cassiemc

**Comment by LauraReynal** [comment]
Report is live on the blog : http://blog.mozilla.org/m4d/2015/01/06/webmaker-bangladesh/
cc @benrito @davidascher @HPaulJohnson @edrushka @thisandagain @secretrobotron @cassiemc 
Thank you very much for your contributions !
