### ISSUE TITLE
Tiers

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#580]
#### Goal: take the "tiers" work the LD group and others have been doing and ship it in shiny "2.0" version. So that Mark can pull from it for board deck. 
2.0 version (new) http://mzl.la/tiers_updated
1.0 version http://mzl.la/tiers

### Roles
* Project manager: @openmatt
* Decision-maker: @msurman 
* Copy-writer: @KevZawacki @HPaulJohnson
* Design: @cassiemc @lovegushwa 
* Accountable: @brettgaylor

**Comment by OpenMatt** [comment]
#### Next steps
* Cleaner copy: maybe Kevin / Paul can help with this?
* Better visuals: @cassiemc maybe we can assign a designer? 
* Still some substantive content questions to work out 
** The role of Network(s) and community(s)
** Refinement of Leadership types + actions
** Benchmarking with other orgs

**Comment by OpenMatt** [comment]
Next step: @chrislarry33 @brettgaylor + mark to huddle on final content updates before design / copy work begins.

**Comment by OpenMatt** [comment]
@brettgaylor : you're responsible for making that meeting happen. Phia can help w. Mark's calendar.

**Comment by OpenMatt** [comment]
@brettgaylor deadline for your next version is Friday Oct 2. Cool?

**Comment by HPaulJohnson** [comment]
@brettgaylor let me know when you all have the content finalized and are ready to talk about polishing the copy.

**Comment by OpenMatt** [comment]
@brettgaylor has a new spreadsheet he's working on. Brett can you add here?

**Comment by OpenMatt** [comment]
* Updated tiers stuff is here: http://mzl.la/tiers_updated

**Comment by brettgaylor** [comment]
https://docs.google.com/spreadsheets/d/1Z3GKLUiQZCYD8CAj-gTnKhpMw1v2C6T_42sdnpc-qgw/edit#gid=0

**Comment by OpenMatt** [comment]
@HPaulJohnson have a look and see what you think. May not need a lot of copy love -- but would be good to get your take.

**Comment by OpenMatt** [comment]
@msurman: do you want design to turn this into something that looks like a thing? http://mzl.la/tiers_updated

**Comment by msurman** [comment]
@openmatt, no need to turn into a thing yet. I think we want to do design work next week once we have the thinking more locked.

**Comment by HPaulJohnson** [comment]
@OpenMatt I think it probably makes the most sense to work on the copy at the same time as the design work. So I'm holding off on adding a lot of comments until that work starts. 

One quick comment in the mean time: I think the "Executive" naming feels a bit off putting and for some might not be particularly inspirational. Something like "Business Leaders" or "Organizational Leaders" could fit better with the other tiers.

**Comment by cassiemc** [comment]
FYI @lovegushwa has some availability next week, he and I will tag team this to make sure it all gets done in time. Have edited the RACI.

**Comment by OpenMatt** [comment]
For the board meeting, this work will merge with the "Leader Stories" piece ticketed here: https://github.com/MozillaFoundation/plan/issues/577
* those leader stories will illustrate the 5 "tiers", with an example for each
* we should come back to this next heartbeat or two, to turn this spreadsheet into something that looks more like a real thing / a canonical slide we can use to explain.  http://mzl.la/tiers_updated
