### ISSUE TITLE
Mozilla / MoFo Strategy Map graphic

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#581]
#### Goal: create a graphic that shows how MoFo fits into larger Mozilla strategy map

**Comment by OpenMatt** [comment]
Impact Group will meed today to discuss

**Comment by OpenMatt** [comment]
Impact Group met today. Will produce a draft ToC for 2016+ and email to Mark w. key questions by EOD Tues (Sep 29)

**Comment by OpenMatt** [comment]
What we need most is clear thinking *behind* each of the three options we present
* therefore, probably needs 3 theories of change 
* focused on real set of *outcomes* we're optimizing for in each model 
* we don't necessarily need to tie to those three specific long-term impacts (access, privacy, web literacy), but the ability to have an opinionated agenda we can set year by year

**Comment by OpenMatt** [comment]
* Impact group is going hands-off this spreadsheet now.
* Handing over to @msurman to pull from this and feed into board deck.

**Comment by OpenMatt** [comment]
* Logic model / Major Grants work: http://mzl.la/major_gifts

**Comment by OpenMatt** [comment]
### Next steps
* focus on how MoFo fits into larger Mozilla strategy map
* @msurman can you send me the SYP strategy map for Mozilla you mentioned?

**Comment by OpenMatt** [comment]
* blocked. won't receive MoCo strategy map for a couple more days.

**Comment by OpenMatt** [comment]
Want to make sure I understand from @msurman what the MoFo pieces of this are likely to be, so we can prep them in advance.

**Comment by OpenMatt** [comment]
don't think we're doing this. moving to Phase 3

**Comment by ldecoursy** [comment]
@OpenMatt Can we close this?

**Comment by hannahkane** [comment]
Can we close this now?
