### ISSUE TITLE
Develop plan for Web Lit Basics l10n campaign

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#583]
Document program design for l10n campaign/sprint to localize Web Lit Basics module into 5+ languages. Campaign would run from end of October through end of November, with opportunities to tie in and do some in-person sprinting at MozFest

* Decision-maker: @chrislarry33 
* Accountable: @ldecoursy
* Responsible: @soapdog @chadsansing 
* Consulted: @KevZawacki @amirad @hannahkane 
* Informed: MoCo Participation, Clubs/RCs

**Comment by hannahkane** [comment]
Wondering if this could also include localizing the Thimble homepage content into the same 5+ languages. 

/cc @humphd

**Comment by soapdog** [comment]
I am working on porting the content of each activity to the current markdown based template we have on github. Will add an update here as this work progress.

**Comment by OpenMatt** [comment]
@ldecoursy status?

**Comment by ldecoursy** [comment]
Had a call about this yesterday. Still a few bits to iron out, but 1-pager will come next week. Moving to next heartbeat.

**Comment by ldecoursy** [comment]
Going to focus on Web Lit Basics 1 for now. @soapdog is working on some documentation, @chadsansing is going to help migrate content into markdown.

**Comment by soapdog** [comment]
Linking https://github.com/mozilla/learning-networks/issues/271#issuecomment-149372591 here. The technical side is basically done. We're working to move our content and create better docs so that by the end of this week we're ready.

**Comment by ldecoursy** [comment]
Overview of campaign plan is here: https://docs.google.com/document/d/15D57m-8dqpCvVX8e0M5oNH95ptwXgAMYXezsVkFuu7Y/edit

**Comment by OpenMatt** [comment]
@ldecoursy status?

**Comment by ldecoursy** [comment]
Plan is approved, closing and will file new ticket for kick-off.
