### ISSUE TITLE
Develop plan for unified MLN community engagement

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#584]
Develop plan to consolidate monthly MLN community calls, newsletters, etc. 

Will likely include the following, each once per month:
* MLN community call (vs. individual Hive city monthly calls)
* Work-with-me hangout
* Tweet chat
* Newsletter

**Comment by jgmac1106** [comment]
Hoping the #teachtheweb podcast, even if its monthly, gets revived. The first two episodes were good.

**Comment by ldecoursy** [comment]
cc @kgorr

**Comment by OpenMatt** [comment]
@ldecoursy status?

**Comment by ldecoursy** [comment]
Moving to next heartbeat. Pieces are coming together - will synthesize into one plan over the next week.

**Comment by ldecoursy** [comment]
Moving final time - to ship by MozFest

**Comment by ldecoursy** [comment]
Aim is to kick this off in January. Still some details to iron out re: branding and how this works in support of the strategic plan.

**Comment by ldecoursy** [comment]
Set up meeting with @HPaulJohnson @edrushka @secretrobotron and others.

**Comment by ldecoursy** [comment]
Closing this.  @HPaulJohnson set up a Comms Council to address things like this and how we can streamline across teams. We had our first meeting and will reconvene after Orlando.
