### ISSUE TITLE
Design Mozfest print and wayfinding assets

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#586]
driver: @cassiemc 
design: Adil (contractor), @natalieworth, @lovegushwa, Beth (contractor)
QA: @cassiemc & @lovegushwa 
consulted: @HPaulJohnson @thornet
decision-maker: @Saallen  

Print assets needed for mozfest listed here: https://docs.google.com/spreadsheets/d/1J4LS4ILtG5x-jxwHEwGuDzXHRHC9IQM4t9fg2OUeRBs/edit#gid=0

Wayfinding tickets are being tracked here: https://github.com/mozilla/2015.mozillafestival.org/labels/wayfinding

**Comment by cassiemc** [comment]
Festival Guide ticket is here: https://github.com/mozilla/2015.mozillafestival.org/issues/212

**Comment by cassiemc** [comment]
Festival Guide was pushed back as there were other more imminent print needs. But we are on track with this heartbeat's tasks, half-way through the tickets here, as expected: https://github.com/mozilla/2015.mozillafestival.org/milestones/9%20October

**Comment by cassiemc** [comment]
These are on track! Rolling over to the next heartbeat, since the work is ongoing. 
https://github.com/mozilla/2015.mozillafestival.org/milestones/23%20October

**Comment by cassiemc** [comment]
On track, and on-going. Amending this ticket to include wayfinding materials.

**Comment by hannahkane** [comment]
I think we can close this.
