### ISSUE TITLE
Ship board slides + book

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#587]

**Comment by OpenMatt** [comment]
@msurman if you want design help at some point, let us know.

**Comment by cassiemc** [comment]
@OpenMatt Any word on if @lovegushwa and I can begin this design work? Is this the right ticket?

**Comment by OpenMatt** [comment]
* @cassiemc probably not the right ticket -- I'll carve it into smaller pieces and create new specific tickets. More coming later today. Sorry for delay.

**Comment by OpenMatt** [comment]
### Key question on this is: 
* what are we sending in advance to the board? 
* and when?

**Comment by OpenMatt** [comment]
* Mark will want to book some time w. the designer on Friday
* Completed deck will need to be sent Monday. 
* So: may require some work over the weekend. With accompanying gratitude / compensatory time off etc. @cassiemc will discuss and update this ticket.

**Comment by cassiemc** [comment]
Just emailed this to @OpenMatt – but glad to work it out in the bug! Is there any way we can get a draft of the slides ahead of Friday? This will let us work out a style, start gathering assets and get comfy in Keynote, so even if content changes and there is design we ultimately have to throw away, this will give us a healthy head-start. @lovegushwa is (and I am) ready to go on this now.

**Comment by OpenMatt** [comment]
## Deliverables / Timelines

### What are we sending to the board? 
1) Presentation deck 
* PDF version w. out builds

### 2) Supporting reading materials:
Mark has already started trickling them things. Won't go out in board book.

### 3) Ops update 
* Contents: a) updated high level 2015 KPIs b) Q3 highlights c) Q4 look ahead d) one fundraising slide e) financial update

### 4) Board business
• minutes from last meeting
• any comp stuff Michael Durham wants to put in
• possibly conflict of interest item
• any grants to approve (Mark: Don't think there are grants to approve.)

### When are we sending these things? 
Monday night or Tuesday morning.

**Comment by OpenMatt** [comment]
Back of board book: http://mzl.la/back_of_book

**Comment by cassiemc** [comment]
@OpenMatt Didn't let me open it, just requested access.

**Comment by cassiemc** [comment]
The only page so far that seems to need @lovegushwa's hand is p5 – 2015 board workflow. If that? @OpenMatt I assume there's more coming?

**Comment by OpenMatt** [comment]
* @cassiemc @lovegushwa there's nothing there for you guys. That's just for me and Angela's planning purposes.
* Jordan + Mark will be meeting later today.

**Comment by lovegushwa** [comment]
@OpenMatt Mark mentioned having me look at all the decks since last October. It will help me understand the strategy narrative and to double check were not saying something we already said in a clearer way. Can you send me a link to these decks?
