### ISSUE TITLE
Update Mozilla Learning wiki

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#589]

**Comment by bhuvanshri** [comment]
Sections to Edit / Add:
- "Things We Read" - Frameworks and Readings that we considered
 - http://ssir.org/articles/entry/the_secret_of_scale
 - https://medium.com/life-learning/the-number-one-predictor-of-career-success-according-to-network-science
 - http://ssir.org/articles/entry/creating_high_impact_nonprofits
- "Our Analysis" - Framed in a coherent way
 - LD SWOT Summary + Etherpad link
 - Leadership Tiers
 - All Advocacy blog posts

**Comment by OpenMatt** [comment]
Bhuvan will start working on an update /staging version of the wiki

**Comment by bhuvanshri** [comment]
First pass on the narrative complete: https://wiki.mozilla.org/Learning/Staging

Next Steps: 
- Need to add some images.
- Move some content from the wiki to archive.
- Link up Staging narrative to the archived details.

**Comment by OpenMatt** [comment]
@bhuvanshri don't worry about images for now -- we'll pull those from the design work being done for the posters, etc.

**Comment by OpenMatt** [comment]
more coming on this -- including slides, blog post from Mark w. @KevZawacki , etc.
