### ISSUE TITLE
Finalize & distribute Kenya field report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#59]
Distribute first draft of field report from Kenya research trip. :earth_asia: 

Phase: Research / Build / Ship
Owner: @laurareynal
Decision: @davidascher 
Lead design: @thisandagain
Lead dev: n/a
Quality: @cassiemc

**Comment by LauraReynal** [comment]
@cassiemc @secretrobotron @davidascher @thisandagain @benrito 

The Kenya Report is ready for its first review! 
https://www.dropbox.com/s/87r8bqi2bml8jxz/kenya_7-01-14.pdf?dl=0

I propose we do edits like @cassiemc did last time => comments on a pdf that we post here. 
Just let me know how I can help !
Thansk

**Comment by LauraReynal** [comment]
Hey all copy-reviewers and quality-verifiers, @cassiemc @secretrobotron @davidascher @thisandagain @benrito 
Would thursday be okay for your different reviews? Would be great to have the final version for next Monday, the 19th, for publishing. 
Thanks

**Comment by cassiemc** [comment]
Hey @LauraReynal and @thisandagain – great report. It's beautiful. I left some copy and design suggestions here: https://www.dropbox.com/s/t178nqsu5rdqkpm/kenya_7-01-14%20-cm%20edit.pdf?dl=0 The biggest thing I think might be simplifying the two large diagrams. A spell check would probably catch other things I probably missed. Again, great work!

**Comment by LauraReynal** [comment]
Hey @cassiemc thanks a lot for a wonderful review.

A few questions:
- What Is Camel Case ? ( Mentioned in page 4 ) 
- I understand that couple of quotes have odd grammar, but I am uncomfortable changing them, given the fact that they are quotes. What do you think for a decision? Remove or modify?
- What does "hang the initial quotation" Means? You mention this for all quotes

Other than that thanks for all the comments, it is very helpful !

**Comment by cassiemc** [comment]
Hey Laura, glad it was helpful. It was pretty detailed!

* camel case  – each word in a phrase is capitalized
* quotes – I'd take editorial license to adjust them, so long as the meaning is intact, if it helps make them more accessible/readable.
* hang quotes – more a comment for Andrew who asked me to review design as well. It means slightly indenting the first line of a quote so that the quotation mark "hangs" just outside the text, and the text aligns perfectly to one side. http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2 I assumed you'd just have to adjust it on the one style and hopefully it fixes all the pull quotes.

**Comment by LauraReynal** [comment]
Thanks @cassiemc 
Agreed for the grammar quotes, will do as you suggest ! 

Also maybe we could come up with a Research Report Check-List Pre-Launch aka *RRCLPL* :smile: 

- [ ]  Is the report clear and easily readable by all audiences (Webmaker team, partners, Teach teams etc)
- [ ]  Is the message understandable / understood ?
- [ ]  Are there some elements that needs a voice explanation ? => not good
- [ ] Is is *useful* for our audiences ? ie does this have an impact ?
- [ ] Are the personas well structured?
- [ ] What could we do better next time?

@thisandagain @secretrobotron  @HPaulJohnson  Any thoughts?

**Comment by davidascher** [comment]
The dropbox link no longer works. New version?

**Comment by LauraReynal** [comment]
Hi @davidascher here is another link to the report without review https://www.dropbox.com/s/7h74uk7envjywyc/kenya_14-01-14.pdf?dl=0
And here is the one annotated by Cassie : https://www.dropbox.com/s/t178nqsu5rdqkpm/kenya_7-01-14%20-cm%20edit.pdf?dl=0

**Comment by secretrobotron** [comment]
Just dove through this and added a billion more comments: https://dl.dropboxusercontent.com/u/7054348/kenya_7-01-14%20-cm%20edit.pdf

Mostly spelling/grammar/structure though, with some comments about stuff making sense.

I'll try to go through it again with your ^^ checkboxes in mind.

**Comment by thisandagain** [comment]
@cassiemc and @secretrobotron Thank you X :100::100: for all the notes. :smile:  Latest changes for intro - findings is available here:
https://www.dropbox.com/s/qhty52eixabb3ni/kenya_150119.pdf?dl=0

More work is needed on the personas and the frameworks as per your feedback, but wanted to get the latest out to everyone this evening. /cc @LauraReynal

**Comment by LauraReynal** [comment]
Hey @thisandagain It says the PDF is damaged. It weights 0 :smile: 
Huge thanks to you three for the reviews and the design work !!

**Comment by thisandagain** [comment]
Fixed!

**Comment by thisandagain** [comment]
Alright. Draft v2 is ready for review:
https://www.dropbox.com/s/lyzw4e8wjrmjhws/kenya_150120.pdf?dl=0

I made a few major changes to the end of the report in addition to the grammar, content, and design edits from @secretrobotron and @cassiemc:
- Created type treatment for how to display motivations & threshold zone consistently
- Removed the web journey diagram from each persona and tied it into the description copy directly
- Removed recommendations as they don't make much sense for a general audience (this section should be included along with more detailed about the product in the final report however!)
- Expanded the appendix

/cc @davidascher @benrito @edrushka @HPaulJohnson

**Comment by LauraReynal** [comment]
Hey @thisandagain  Thanks for the great design pass :smile: 

I initially included the product recommendations to show how we learn from all of this when creating the product. It's a question almost everyone ask me.

:+1: on including a product section with more general information on MWC. I'll add this in the plan. Thanks again !

**Comment by benrito** [comment]
Suggestions:

In inner intro, replace "aims to" with "highlights"

remove " project in Kenya is the progression of our
study in Bangladesh in October 2014. It is part of the Mobile Opportunity Initiative" and go straight to "This research is part of a 6 month..." (would recommend making these changes for Bangladesh one too, if we have time—trying to minimize public branding of this as an initiative, rather than a core thing we do in Webmaker

"Are people willing to be makers?" —> can we reformulate somehow? Make it more of a pull than a push? "What experiences would persuade people to become makers" or etc

Agree with removing the product-centric stuff (esp recommendations) to the extent possible (at least for public version)

pages 26-29 phenomenal

lastly: think we should consider removing the "next step" pages for these, at least for the publication versions. internally they can help tell a story of what we're learning, but it would be good if the publication versions could stand alone. would recommend this change for bangladesh one too if we have cycles.
i love seeing this work get streamlined and optimized, it's amazing!

**Comment by thisandagain** [comment]
Awesome. Thanks Ben. :+1: on these changes. I'll get these into an updated draft ASAP.

**Comment by LauraReynal** [comment]
Thanks @benrito for the feedback !

**Comment by thisandagain** [comment]
Alright! Latest edits available here:
http://mzl.la/kenya

**Comment by thisandagain** [comment]
Few additional notes from Alex (GSMA):

```

General: I understand the use of codes (INT01- M01) if it is to preserve the anonymity of the interviewee. However, in the personas section, these are used next to a photo of a named individual. Why?
 

Page 4 (of .pdf): Assume that the TOC will have associated page number?
 

Page 11: The following sentence “this ethnical diversity is a source of conflicts, but also of vibrant culture, and language compendium.” Doesn’t really make sense. I would suggest:
This ethnic diversity is a source of conflict, but also gives the country a vibrant culture and compendium of languages.
 

Page 13: The icons on the map won’t make sense to people unless there is a key. Also, some of the icons are obscuring others.
 

Page 15: “Participants perceive a lack of esthetism…” I think you mean aestheticism. I would suggest you say ‘aesthetic quality’ instead.
 

Page 17: “One of the questions we ask in each interview is “What does Internet meet to you?”.
 

Page 21: “all micro business owners are hustlers and struggle to develop.” Not sure that this means.
 

Page 23: “Entering into the digital era, our society evolved from a Red-Only culture where people passively consumed content pushed by an author, to a growing Red & Write culture.”
 

Personas: Are they in a random order? It was not clear to me why it was structured like this. 
```

Lastly, he requested that we remove the "Partner" page (5) from the report as to avoid GSMA review and because the report is focused on Webmaker.

**Comment by thisandagain** [comment]
Hmm... looks like these notes are from v1 of the report.

**Comment by LauraReynal** [comment]
@thisandagain I took care of his note on the personas. 
Do we want to add pages to the TOC? it might look crowded.

**Comment by thisandagain** [comment]
@LauraReynal Page numbers added to the Table of Contents. Latest updates published at:
http://mzl.la/kenya

Unless we have any objections I propose that this is ready for release. :+1: 
/cc @davidascher @benrito @HPaulJohnson @edrushka

**Comment by benrito** [comment]
+1

**Comment by edrushka** [comment]
Can you fix the inconsistencies in Web/web (should be lower-case unless referring to Webmaker) Internet/internet (should be upper-case)? Also, web page is two words, no hyphen. https://www.mozilla.org/en-US/styleguide/communications/copy-rules/

P. 37 "They give farming technics..." Do you mean "techniques"?

Also: why is this dated November 2014 when we're releasing now? Intentional?

**Comment by davidascher** [comment]
I see a weird artifact on page 5:

![screenshot 2015-01-26 11 29 15](https://cloud.githubusercontent.com/assets/51278/5906713/a19c8030-a54e-11e4-8bd9-cdb9ca4ac6ef.png)

**Comment by davidascher** [comment]
"“I use to just take money
from my business
whenever I needed. Now
I take a salary every two
weeks instead.”

That should read "I used to …"

**Comment by davidascher** [comment]
Orphan on p. 73: "secondary education"
same on p. 77: "him find different work opportunities"
p. 82: "receipes" -> "recipes"
butchery -> butcher, except if that's actually what she said and maybe a local dialectical variation.

Other than that, really nice report.  Want to see it printed out and glossy!

**Comment by HPaulJohnson** [comment]
Looks awesome, sorry to be a bit late in the review process. Minor edits noted below. When it's final, final we should put together a blog post for blog.mozilla.org/m4d. 

- pg. 5: "expectency" should be "expectancy" 

- pg. 10: this questions reads a little awkward to me: "Does Webmaker provide the web with
a competitive advantage? How?" Makes it sound like is in competition with some other alternative. Might make more sense if it read "the open web..."

- pg. 15: websites is misspelled in the last paragraphs of column 1: "Participants deplore the lack of
aesthetics of Kenyan webistes, and prefer international content which has a higher quality standard."

- pg. 21: I would choose a different word than "hustler" to describe micro-business owners: "all micro-business owners are hustlers and struggle to develop." This word shows up in other places later on - I get the intention but it comes across awkwardly in the context of this report. 

- pg. 24: Is "mean" supposed to be "need" here: "Makers are innovators, proud to
create so as to address a specific mean, to learn or simply to have fun."

- pg. 29: missing ":" after "In boarding school"

- pg. 30: should "aspiration" be "inspiration" in this sentence: "are looking for aspiration and are at a point..."

- pg. 35: delete "is" in this sentence: "She is was able to leverage the Internet, and particularly Facebook to learn new skills."

**Comment by thisandagain** [comment]
Great finds @edrushka @davidascher and @HPaulJohnson. Thank you.

@edrushka Made "web" lowercase everywhere except for "The Web Journey", "Webmaker", and headlines. Date (November) used to denote when the research was conducted vs. the release of the report.

@HPaulJohnson Any ideas to replace "hustler" in the micro-business section? I agree that it is a little awkward but I liked how it conveyed a bit of attitude / spirit.

Updated version available here: http://mzl.la/kenya

**Comment by HPaulJohnson** [comment]
Alternatives to "hustler" - "all micro-business owners are.. "industrious" or "enterprising" or "assiduous"

**Comment by thisandagain** [comment]
@HPaulJohnson Ok... updated (still in the quote).

R? @davidascher @cassiemc

**Comment by davidascher** [comment]
Personally I miss the implications of hustler which I think are spot-on
("debrouillard" in French), so would argue for "go-getter" or "keen
entrepreneurs" or other, but wha'ever.

r+

**Comment by LauraReynal** [comment]
@thisandagain @HPaulJohnson Could  we keep Hustler please ? 
None of the alternative express what I saw and wanted to express.

**Comment by HPaulJohnson** [comment]
Ok by me to leave "hustler" in the report if everyone feels strongly it's the right word.

**Comment by LauraReynal** [comment]
Hey Guys ! @HPaulJohnson @thisandagain 

What is the status/next steps of this?
I have strated to share the report to interested people, and I wanted to share it more massively, with Equity, Mozilla Kenya and all-mofo, and other partners/people who are asking for it. 

Do we need a blog post on m4d for this ? 
@HPaulJohnson do you want me to write it ?

Thanks :smile:

**Comment by HPaulJohnson** [comment]
Let's blog about it! If you want to do that go for it. I'm happy to give it a quick copy review before you publish.

**Comment by OpenMatt** [comment]
@LauraReynal sounds like next step is with you to write that post? You good to go?

**Comment by LauraReynal** [comment]
Hey @HPaulJohnson Here is a draft for copy review, Let me know https://m4d.etherpad.mozilla.org/BangladeshReport

**Comment by HPaulJohnson** [comment]
@LauraReynal, @edrushka  and I both reviewed your post and made some edits. There are also a few questions for you. It's all in the etherpad. 

Let us know if you need anything else let us know. Otherwise, feel free to post when you feel like it's ready.

**Comment by LauraReynal** [comment]
Thanks Paul, I added text where you had listed questions !

Thank you everyone for reviews and help :smile: 
 The report is live here. http://blog.mozilla.org/m4d/2015/02/03/webmakers-field-research-report-from-kenya/
