### ISSUE TITLE
Add missing data to board book

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#590]
### Fill in all blanks in the board deck for missing numbers.  
Here: http://mzl.la/facts
- [ ] Financial data
- [x] Benchmark data
- [x] Leadership data. Total number of leaders in our network.

**Comment by OpenMatt** [comment]
@bhuvanshri status?

**Comment by bhuvanshri** [comment]
In progress today

**Comment by bhuvanshri** [comment]
@OpenMatt, please review and communicate. Assigning to you.

**Comment by OpenMatt** [comment]
Over to Angela to fill in her pieces.

**Comment by OpenMatt** [comment]
* Next step: @chrislarry33 has thoughts on how to slot the leader numbers into tier estimates.
In this spreadsheet: http://mzl.la/facts
* @chrislarry33 any chance you and @ldecoursy could take a pass at doing that in the spreadsheet?

**Comment by OpenMatt** [comment]
* Need to discuss w. Angela next steps on final missing financial data

**Comment by OpenMatt** [comment]
closing
