### ISSUE TITLE
Branding Audits

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#591]
I'm starting this ticket because a bunch of design audit work has been happening to streamline brands/styles and it's time to start triaging.
* [Mofo-wide design audit](https://github.com/MozillaFoundation/Design/issues/94)
* [MLN design audit](https://github.com/mozilla/teach.mozilla.org/issues/1260) 

We need to figure out a way to push this work forward; if properly carried through the consequences of this work will be far-reaching and awesome. My task this week is to help break this work into chunks that are discrete, digestible and conquerable, and that happen in a logical order. Note: It is hard to fit this type of holistic design work into the heartbeat system but we are going to try our darndest.

**For discussion:**
* the RACI below
* who is the ultimate owner/decision-maker
* who can we count on to work with from Moco

### RACI:
driver: @cassiemc 
design: TBD
QA: @lovegushwa @sabrinang
consulted: @davidascher, other PMs, other designers, frontend devs via @simonwex, and someone from Moco (TBD)
decision-maker: @HPaulJohnson? (may depend on the property)

**Comment by cassiemc** [comment]
The MLN Audit is complete, new tickets are filed. Still needs discussion wrt to overall mofo branding audit.

**Comment by OpenMatt** [comment]
@cassiemc status update? stale?

**Comment by cassiemc** [comment]
yep, stale. Brand audits continue on the Moco side, outcomes from the MLN audit are already being implemented, next step will be to figure out branding for Mofo stuff but that won't happen until after EOY.
