### ISSUE TITLE
MozFest poster

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#592]
### Goal
show the impact MozFest has had as a leadership development network. In a large-format graphic poster style that can be in the room at the full-day board meeting.  

### Roles
Project manager: @openmatt
Designer: @lovegushwa 
cc @cassiemc @chrislarry33 

### Deadline: eod Friday Oct 9
We should only start on this if we think it's doable by then. If not, let us know here and we can kill it. 

### Message
The main idea we want to drive home here is that MozFest is an engine that produces a) leaders and b) networks in c) spaces we care about.

### Size
* 24" x 36" 
* full color
* landscape

**Comment by OpenMatt** [comment]
@thornet : what do you think about something like this? 
https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/srp_bvru.png
![mozfest graphic 001](https://cloud.githubusercontent.com/assets/1007376/10321197/6b0ead86-6c45-11e5-9683-b3f7b45dfcfc.jpg)

### Basic idea
* **Numbers.** The cumulative number of participants, countries, and *leaders.* In the form of volunteer session facillitators. 
* **Highlighting the key themes** / hills / impact areas (in plain language) 
* Using a high-res version of the MozFest crowd shot we use on the web site. To emphasize the human element. 

# Next steps
- [ ] Sign off on approach / update copy 
- [ ] Design team. Signal whether this could get done by eod Friday + what more you'd need.
- [ ] Design first pass (eod Thurs)
- [ ] Design final pass / output file (Friday aft) 
- [ ] Send to SF printer for printing (Monday) 
- [ ] Ready for picking up in SF (Tuesday)

**Comment by OpenMatt** [comment]
Assets I pulled from: 
* https://www.dropbox.com/s/uagsmtoebaxx8b0/MozillaFestival2014_WrapUpGraphic_Web_1240x4733.jpg?dl=0
* @edrushka also has previous a MozFest infographic we created, for potential re-use or inspiration

**Comment by edrushka** [comment]
There's also this to pull from: http://intangible.ca/2015/03/02/infographic-2014/

**Comment by lovegushwa** [comment]
@sabrinang @edrushka do you know where I can find a .ai of the MozFest info graphic?

**Comment by edrushka** [comment]
I'm sorry, I don't know.

**Comment by edrushka** [comment]
waaait! @lovegushwa I found it! https://www.dropbox.com/sh/0vgp2zogo8e2544/AAB_R1fwTlP78V7ANctJYe5Ua?dl=0#/

**Comment by OpenMatt** [comment]
@thornet main thing in terms of content is: stress 'networks' and 'leadership' as core themes.

**Comment by thornet** [comment]
Working on the content now. Sending in 1hr or so.

**Comment by OpenMatt** [comment]
@thornet @lovegushwa : check out this updated mock-up based on feedback from Mark:
![mozfest poster graphic 001](https://cloud.githubusercontent.com/assets/1007376/10341301/2a825e96-6ce2-11e5-98a5-2b9356c5c796.jpg)
* Emphasis on developing leaders and networks in key spaces
* Could use same colored background crowd image currently on web site
* Needs updated numbers and copy from Michelle
* Could re-purpose icons for each of the core thematic areas

**Comment by cassiemc** [comment]
@OpenMatt Do you have an idea of what size you'd like this to be? Should it be a standard 18x24" poster? The background graphic might not be resuable at hi-res print but I'll see if we can find the source.

**Comment by thornet** [comment]
Asset, fresh off the press: https://blog.webmaker.org/the-journey-to-mozfest-2015

@OpenMatt I suggest the following data: 

"7,000 participants catalyzed by 1500 facilitators building networks and community leaders with 182 wranglers" 

Data from: http://2014.mozillafestival.org/wp-content/uploads/2014/02/Mozilla_infographic_D6.jpg and BSD lists.

**Comment by thornet** [comment]
Facilitator #s:

* 2010: 40
* 2011: 60
* 2012: 150
* 2013: 350
* 2014: 550
* 2015: 550+

**Comment by OpenMatt** [comment]
@lovegushwa : here's an update mock-up. Let's go with this approach. ![mozfest graphic 3 001](https://cloud.githubusercontent.com/assets/1007376/10344536/c60f80c8-6cf1-11e5-8411-178d22e0b4d4.jpg)

**Comment by OpenMatt** [comment]
The main idea we want to drive home here is that MozFest is an engine that produces a) leaders and b) networks in c) spaces we care about.

**Comment by OpenMatt** [comment]
@cassiemc I was thinking 24" x 36". Does that work? If not, smaller is fine.

**Comment by OpenMatt** [comment]
Super high-res photo version should be somewhere on the MozillaEU flickr account. But if it's hard to find, abandon and go with a plain background instead. 
https://www.flickr.com/photos/mozillaeu
https://www.flickr.com/photos/mozillaeu/albums

**Comment by OpenMatt** [comment]
Cleaned up the ticket above.

**Comment by cassiemc** [comment]
@OpenMatt that size works, same for all posters? And we'll still with landscape. cc @lovegushwa

**Comment by OpenMatt** [comment]
Yup.

**Comment by OpenMatt** [comment]
p.s. the printer prefers PDF files at actual size.

**Comment by OpenMatt** [comment]
@lovegushwa the other thing @cassiemc set me straight on for this and all the other posters is: "infographic" is the wrong word. These are really just blown-up slides or posters.

**Comment by lovegushwa** [comment]
@OpenMatt @cassiemc cool, print production should be a snap. Thank you.

**Comment by lovegushwa** [comment]
@OpenMatt @cassiemc This still needs some work but here is a screenshot so you can see where it's headed.
![screen-shot-2015-10-08-at-11 58 28-am](https://cloud.githubusercontent.com/assets/12228435/10376781/a0e1cacc-6db4-11e5-9143-c17cda19b331.jpg)

**Comment by OpenMatt** [comment]
@lovegushwa love this.
1) can we make it clearer this is "Mozilla Festival 2010 - 2015?" Maybe those date ranges belong w. the logo? instead of floating top left?
2) remove comma after "from"
3) remove space after "in" and ellipsis (like this: "in...")
4) possible to make the themes at right a bit larger? 
5) swap placement of "web of things" and "education"

**Comment by lovegushwa** [comment]
great feedback @OpenMatt will make these changes.

**Comment by cassiemc** [comment]
@lovegushwa I dig this layout a lot. Gives a strong feeling of upward and outward growth. I think the design could be a bit stronger with a couple small tweaks in addition to matt's. 
* Would get rid of the white background behind the logo and just use the white knockout logo, as per https://2015.mozillafestival.org/. That should make it cleaner / simpler.
* I agree the dates could be bigger and more closely associated with the title. If you're going to use them in a rounded-corner-rectangle, try to match that shape with those you've used for the other themes.
* The orange fade on the image feels thick. Would saturate the photo orange on the left side of the image, again per https://2015.mozillafestival.org/, rather than placing a fade over it.

I'm sure I'm comments on some placeholder elements, so ignore what's now irrelevant!

**Comment by lovegushwa** [comment]
@OpenMatt @cassiemc please see the updated version. We can still change if needed but I'm going to shift my attention to the 5year history poster. 

![screen-shot-2015-10-09-at-9 46 22-am](https://cloud.githubusercontent.com/assets/12228435/10400467/c95b6d50-6e6d-11e5-90db-e87e06508cb4.jpg)

**Comment by cassiemc** [comment]
Two layout options – one with Mozfest logo at the top, other at the bottom. First is probably informationally stronger; second might be stronger conceptually.
![admin_board-posters_12-cassie-is-the-bomb-sm](https://cloud.githubusercontent.com/assets/1186326/10405104/cc2c0bd4-6ea4-11e5-8121-dc841f498773.jpg)
![admin_board-posters_12-cassie-is-the-bomb2-sm](https://cloud.githubusercontent.com/assets/1186326/10405106/ce594f98-6ea4-11e5-83da-dff278dfac94.jpg)
@lovegushwa ping pong! Source file is here if you need to update this. I'd have loved to get to wavey flags but didn't have the time. Also, I didn't get to deleting that innermost concentric circle, so that would need to be done if we go with that layout. https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1T2JMU0tFcE1CQ2M/view?usp=sharing

**Comment by OpenMatt** [comment]
@ love this:
* correction: years should be 2010 to 2015
* once that's done and @lovegushwa is happy let's consider this one done

**Comment by cassiemc** [comment]
Update: We're going with the one that has the logo at the top. Repasting here for clarity:

![admin_board-posters_12-cassie-is-the-bomb-v2](https://cloud.githubusercontent.com/assets/1186326/10405677/86d6e33e-6ea8-11e5-9c54-6160ffd94683.jpg)

@lovegushwa if you need to make any more adjustments, the source file is here: https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1ZjYyZWFoY0dYVlE/view?usp=sharing

**Comment by benrito** [comment]
Moving this to https://github.com/MozillaFoundation/plan/issues/607 to finalize.
