### ISSUE TITLE
Thimble l10n work and support

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#594]
Localizing the new Thimble is a product priority, and @humphd has been working on the infrastructure. We'll need support on the Moz side if we want to maintain a localized product.

Some discussion here: https://github.com/mozilla/thimble.webmaker.org/issues/475

### DARCI ###
Driver: @hannahkane
Accountable: @simonwex 
Responsible: @humphd, TBD (likely Ali)
Consulted: @humphd 
Informed:

**Comment by OpenMatt** [comment]
* @simonwex this will likely need @alicoding + a new hire or someone from @xmatthewx 's team
* next step: @hannahkane + @simonwex should schedule a follow-up

**Comment by simonwex** [comment]
We don't have the resources to do this until post-mozfest. This will be a high-priority once we have new hires on the Engineering team. Coming soon!

**Comment by hannahkane** [comment]
Moving to next heartbeat.

**Comment by OpenMatt** [comment]
@simonwex will provide hiring update

**Comment by hannahkane** [comment]
@simonwex - I'm thinking we should close this for now, and open a new ticket when we have a specific plan in place. Feel free to re-open if you disagree.
