### ISSUE TITLE
Leader posters

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#595]
### Goal 
* These are like baseball cards. Showing a hero leader. With a 3-bullet story. And a scale on the side that shows where they fit in a larger framework.

**Comment by OpenMatt** [comment]
### Mock-up

![leader template 001](https://cloud.githubusercontent.com/assets/1007376/10348580/cd720352-6d07-11e5-924a-48732bda9617.jpg)

**Comment by OpenMatt** [comment]
@lovegushwa @cassiemc how does that work for you guys? I will work on getting high-res images and copy for all. Once this template is built, I'm hoping it will be easy to crank out 2 - 6 of these.

**Comment by OpenMatt** [comment]
@ldecoursy is working on getting a high-res image of Lesser. Let's go full speed ahead on this first one.

**Comment by chrislarry33** [comment]
Love it. Make it "New York City" under name, not "Brooklyn"

**Comment by ldecoursy** [comment]
Here are two options. He asked if we could share the final version with him when it's done. 

![fav_4069](https://cloud.githubusercontent.com/assets/4885898/10351391/4d5722d2-6d17-11e5-97cc-c0e15688216c.jpg)
![fav_4059](https://cloud.githubusercontent.com/assets/4885898/10351395/5280038c-6d17-11e5-8432-5fb95f0190ab.jpg)

**Comment by lovegushwa** [comment]
@OpenMatt @cassiemc thanks for the mock-up Matt. The content will totally work. The image composition is good. The focus is soft. These may look fine across the room. The important question is will we be able to get 5 more decent images for the other profiles by tomorrow?

<img width="842" alt="screen shot 2015-10-07 at 3 20 51 pm" src="https://cloud.githubusercontent.com/assets/12228435/10352912/2194dff0-6d07-11e5-8b55-946ceb9fd244.png">

**Comment by OpenMatt** [comment]
* @ldecoursy you're a rockstar! Thank you! 
* @lovegushwa this should give you everything you need to produce the first template?

**Comment by OpenMatt** [comment]
### Images
- [ ] Massimo Banzi, Arduino 
http://makezine.com/wp-content/uploads/2013/04/massimo-banzi.jpg
- [ ] Gene Kimmelman, Open Knowledge
- [ ] Dave Humphrey, Seneca College
- [ ] Connie Yowell, LRNG
- [ ] Jess Weichler, Maker Box
- [ ] Joe Dytrch, Erase All Kittens
- [ ] Jon Sussman, Adagio, Hive Chattanooga

**Comment by OpenMatt** [comment]
@lovegushwa can you review the photos above to see if they'll work?

**Comment by lovegushwa** [comment]
@OpenMatt @cassiemc 
I'm still working on the composition and colors. But this amount of content should work perfectly if we want to make more of these.
![screen-shot-2015-10-08-at-11 58 47-am](https://cloud.githubusercontent.com/assets/12228435/10376831/e68843f8-6db4-11e5-97e6-ec7f8e560064.jpg)

**Comment by OpenMatt** [comment]
@lovegushwa This looks great. 
* My main question is about connecting the 5 leadership tiers more strongly to "Mozilla Leadership Network." In the mock-up, the connection between these was a bit clearer. The visual logic was like: "Mozilla Leadership Network = what kinds of leaders? *These* kinds of leaders.
* If that's hard to do or doesn't make sense, let's drop it and just keep pressing ahead.

**Comment by OpenMatt** [comment]
* Other note is: these posters and the slides should look roughly like they come from the same place / have a unified look and feel. I'm not sure I've seen us use that color before -- good to pick something that "looks like us."

**Comment by lovegushwa** [comment]
@OpenMatt 
- Let me dig into your first point about the leadership tiers.

- Totally agree about the blue, it's a placeholder color (just a value that contrasts with the orange red) and I'll replace it with something officially Mozilla soon.

- There will be more color in the posters than the deck (it's charcoal gray). I'll figure out how to tie them together. Don't worry, there may be some contrast but they wont be disconnected.

**Comment by OpenMatt** [comment]
@lovegushwa : Love all that. Thanks Jordan. You're killing this. Thank you!

**Comment by lovegushwa** [comment]
thanks @OpenMatt !

**Comment by lovegushwa** [comment]
@OpenMatt @cassiemc 

Here is a revamped version, I borrowed the Mozfest blue and gray (the gray should tie into the presentation deck nicely).

@OpenMatt if this is going to go I can knock out the other 4 if the copy and images are ready.

![screen-shot-2015-10-09-at-10 02 57-am](https://cloud.githubusercontent.com/assets/12228435/10400413/5789e2c4-6e6d-11e5-950f-1134aad3a8fe.jpg)

**Comment by cassiemc** [comment]
@OpenMatt I'm leaning toward this being closer to the Teach palette than to the Mozfest palette, what do you think? Maybe the overlapping area is in the pink and blue (a slightly deeper blue than what's here).

@lovegushwa the grey seems at odds with the gradient below. Wonder if making Marc's name way more dominant would help this feel like it is about a real person.

**Comment by OpenMatt** [comment]
* Freakin love this.
* Mark will like MozFest color palette / tie-in. It's a big part of his board story. But whatever you guys decide is fine. 
* +1 to making the name larger / more pride / real human
* Maybe it's just me but there's something about omitting the blue circle from the ladder on "professional" that makes it feel less integrated / part of a seamless whole. But now I'm hair-splitting.

**Comment by OpenMatt** [comment]
@lovegushwa I'd hold off on cranking on any others until I get the copy and list of names 100% finalized, which I'm working on now

**Comment by ldecoursy** [comment]
Re copy for Marc's - it should say New York City, instead of Brooklyn. Also, for the first bullet, I'd say "nonprofit org focused on youth development and technology."

**Comment by cassiemc** [comment]
@ldecoursy Is the last point "Added kids teaching web dev to other kids to Mouse,
Contributed to our curriculum." – should that be two different bullets?

**Comment by cassiemc** [comment]
@OpenMatt @ldecoursy Also, should we streamline the tenses or order them so they tell a story – so: 

* Runs programs at a nonprofit org focused on youth development and technology.
* Learned agile, open practices in the New York City Hive.
* Added kids teaching web dev to other kids to Mouse. [not sure what this means]
* Contributed to Mozilla Learning Network curriculum.

Feel free to tweak that, just seemed to need some attention...

**Comment by ldecoursy** [comment]
Thanks Cassie - few suggestions:

* Runs programs at Mouse, a nonprofit focused on youth development and technology.
* Was founding member and learned agile, open practices in Hive NYC.
* Added web literacy as a core component to Mouse Squad Certification program.
* Contributed to Mozilla Learning Network curriculum.

Anything missing @chrislarry33?

**Comment by cassiemc** [comment]
A few more options. Best viewed alongside the poster design in https://github.com/MozillaFoundation/plan/issues/592, trying to use colors to get to your comment @OpenMatt about them feeling like this person was picked out of the crowd.

![admin_board-posters_12-cassie-is-the-bomb4](https://cloud.githubusercontent.com/assets/1186326/10404995/2506702e-6ea4-11e5-86bb-e1726ffe7c05.jpg)
![admin_board-posters_12-cassie-is-the-bomb4](https://cloud.githubusercontent.com/assets/1186326/10404996/26bccddc-6ea4-11e5-96c1-017e70bd778f.jpg)
![admin_board-posters_12-cassie-is-the-bomb3](https://cloud.githubusercontent.com/assets/1186326/10404998/27ed4cae-6ea4-11e5-97c6-af41fe25a632.jpg)
@lovegushwa ping pong! Here are the source files if you need to tweak again: https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1T2JMU0tFcE1CQ2M/view?usp=sharing

**Comment by cassiemc** [comment]
@lovegushwa Also the text will need updating as per @ldecoursy's comment in https://github.com/MozillaFoundation/plan/issues/595#issuecomment-146980962

**Comment by omnignorant** [comment]
@chrislarry33 photos of Jackie Moore
![dsc_0899](https://cloud.githubusercontent.com/assets/6335874/10405336/cfc6a67a-6e9d-11e5-932e-be2138325f02.jpg)
![dsc_0898](https://cloud.githubusercontent.com/assets/6335874/10405337/cfc8cfa4-6e9d-11e5-971f-eccec1f4156a.jpg)

**Comment by OpenMatt** [comment]
@cassiemc @lovegushwa those designs are great. These are awesome
* Let's go w. dark blue, instead of light blue
* I can't tell the difference btwn open 1 and 2. You guys decide and let's push ahead.
* Working to get you a final final set of names and copy now

**Comment by cassiemc** [comment]
@OpenMatt mistake, there was no diff between the 1st & 2nd. I deleted the extra one.

**Comment by cassiemc** [comment]
Update with just the dark blue option and @ldecoursy's revised text:
![admin_board-posters_12-cassie-is-the-bomb-v22](https://cloud.githubusercontent.com/assets/1186326/10405632/25f57bac-6ea8-11e5-814b-3ae59b14506b.jpg)

Latest source file is here: https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1ZjYyZWFoY0dYVlE/view?usp=sharing
The psd for editing the profile images is here: https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1cGFkSHFfWU9nVTA/view?usp=sharing

**Comment by OpenMatt** [comment]
### Notes from Mark

* 1) Palette: Try to use "one Mozilla-ish" palette where possible. (e.g., Martell's pallette) To signal: compatibility / future focus w. core Mozilla brand for this work. 
* 2) Switch leadership categories at bottom from horizontal to vertical.  To communicate a hierarchy.

**Comment by OpenMatt** [comment]
### Final list of names
#### Champio
Massimo Banzi, Arduino
* invented Arduino, gateway for a generation of open hardware hackers
* attended first-ever Mozilla Festival in Barcelona

#### Executive
* Gene Kimmelman, Public Knowledge
* Connie Yowell, Collective Shift

#### Professionals
* Jackie Moore, Level Up Youth Maker Space
* Marc Lesser, Mouse
* Dave Humphrey, Seneca College

#### Professionals

**Comment by OpenMatt** [comment]
### Images
- [ ] Massimo Banzi, Arduino 
http://makezine.com/wp-content/uploads/2013/04/massimo-banzi.jpg
- [ ] Gene Kimmelman, Open Knowledge http://api.ning.com/files/rRUWEC*XQHwewLvMV3Aj8ox6eU5Q3OFfPZcncqRGVEif632LLLygHdj1HddIfdP897JmMNKQxI6d7ZEuwkAljt2*NX287ebH/gene_kimmelman.jpg or buy here http://www.alamy.com/stock-photo-consumer-protection-advocate-gene-kimmelman-discusses-net-neutrality-72546726.html
- [ ] Dave Humphrey, Seneca College http://fsoss.senecac.on.ca/2014/sites/fsoss.senecac.on.ca.2014/files/Dave-Humphrey.jpg or http://www.senecacollege.ca/news/gallery/d-humphrey.jpg
- [ ] Connie Yowell, LRNG http://i.vimeocdn.com/video/349487496_1280x720.jpg or https://redefineschool.files.wordpress.com/2013/02/connie-yowell-bw.png?w=313&h=314 or https://i.vimeocdn.com/video/167622201_1280x720.jpg
- [ ] Joe Dytrych, Erase All Kittens http://www.thechildrensmediaconference.com/wp-content/uploads/2015/06/Joe-Dytrych.jpg
- [ ] Harlo Holmes http://www.niemanlab.org/images/harloholmes.jpg
- [ ] Dina http://www.agalauskunst.no/bilder/Kunst/Mahendra/XL/dian_kvad.jpg or https://pbs.twimg.com/profile_images/455896473624776707/vppUhjgK.jpeg

Still need: 
* Simeon Oriko, Jam Lab
* Tiffiny Cheng, Fight for The Future

**Comment by OpenMatt** [comment]
* @lovegushwa This should give you what you need to crank these out. 
* I would do all 11. Then Mark can pick which ones he wants printed. And have the rest on hand as slides -- these will be great assets even if we don't print as posters
* We can update and provide final text bullets later. I'm having trouble getting people to write good copy. Will probably be Mon or Tues before we get it.

**Comment by msurman** [comment]
@lovegushwa @OpenMatt in the end, Jordan and I decided to use just one leader for each category. 

Also, I've decided to lower the bar / change the champion category to be more people like category. We can still reserve the Mozilla Award idea for people like Massimo.

**Comment by msurman** [comment]
@lovegushwa @OpenMatt 

Final choices and copy for the leaders that Jordan will put on the posters is this:

Champion

Connie Yowell, CEO, Collective Shift

* key supporter of Mozilla leadership and education work 
* provided $xM in funding while at MacArthur
* just launched LRNG platform using Mozilla’s badges tech and web literacy curriculum
* co-chairs the Badge Alliance with Mozilla

* champions play a central role in promoting Mozilla and building our influencer network

“Mozilla has been real ally over the past five years, helping shape the new platform for learning that we’re building at Collective Shift." 

Executive

Gene Kimmelman, Executive Director, Public Knowledge

* original member of Mozilla’s Public Policy Module group
* helped Mozilla establish itself as member of US internet advocacy coalition 
* current host of a Mozilla Open Web fellow and advisor for overall program
* key ally on net neutrality campaign 

* executives lead organizations that play a key role in Mozilla networks

“This is a critical moment in Internet policy in America. We need partners like Mozilla — both in Washington."

Professional

Jackie Moore, (title) Level Up Youth Maker Space

* transitioned from corporate IT to teach tech to young people
* turned urban shopping mall shop into a robotics lab for youth
* this work supported in part by grant from Hive Chicago
* regular participant in MozFest and Hive Chicago community

* professionals leverage Mozilla tools, content and practices as part of their everyday work

"Teens are already hanging out in malls looking for something to do. Creating interactive items keeps them engaged because it empowers them to do something *they* control." 

Emerging leader

Harlo Holmes, The Guardian Project

* put her security skills to work through Open News fellowship at the New York Times 
* post fellowship: creating secure open source apps to protect journalists and human rights workers 
* divides time between coding and teaching forward by educating others
* still active in Mozilla and Open News networks

* emerging leaders are exceptional individuals who contribute to the broader Mozilla community in exchange for a unique, high impact career experience

* "Once you're a Knight-Mozilla fellow, you're carrying quite a brand behind you. It grants you access to people and organizations you never would have dreamed of."

Young leader

Dian Ina Mahendra, Mozilla Indonesia Community

* regional Coordinator for Mozilla Clubs.
* received leadership training from Mozilla Clubs and participation teams
* pioneered ways to teach coding / web literacy in public parks without devices or wifi
* led Webmaker launch in 13 cities (community teams, localization, marketing, comms)

* young leaders learn valuable skills while working on Mozilla programs, giving them valuable experience to bring into their lives and careers

"There are still many people living with limited resources in Indonesia, preventing them from pursuing higher education. I see the web as an unlimited resource for everyone."

**Comment by msurman** [comment]
@lovegushwa as you'll see above, I'm suggesting a slight change to the format. Now there are three types of data:

* the bullets about the person
* a description of the archetype / category
* a quote

Can you play with the design so that works across the board?

**Comment by lovegushwa** [comment]
thanks @msurman, cranked this out. Will post tomorrow once I have more posters to give some context.

**Comment by chrislarry33** [comment]
@lovegushwa @msurman @OpenMatt I think we need to find a way to get our current total of leaders in the network in here somehow. Or somewhere else that might be better in the assets. But 4903 leaders is real, and I'd be comfortable saying an even 5000.

Here are the numbers: https://docs.google.com/spreadsheets/d/1pmHonTWB9IWHdKRkec2d9t1u5E3KqX-gSC0dxg3s2KQ/edit#gid=827538420

**Comment by lovegushwa** [comment]
<img width="1156" alt="screen shot 2015-10-12 at 1 15 12 pm" src="https://cloud.githubusercontent.com/assets/12228435/10437647/5b7cfe3e-70e3-11e5-8086-48eae2156279.png">

**Comment by benrito** [comment]
@openmatt according to @thornet Dian might not fit the young leader category entirely; not a big problem except for when we may decide to release this publicly. At minimum we should fix this post board-meeting. Any thoughts?

**Comment by OpenMatt** [comment]
@lovegushwa there's a typo in Connies quote

**Comment by OpenMatt** [comment]
@benrito yeah let's revisit post board meeting. I think it's fine for now.

**Comment by OpenMatt** [comment]
closing this one, as I believe this work is now happening in another ticket
