### ISSUE TITLE
Grants poster

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#596]
## Goal
* Create a poster that shows all the grant money we raised and how it fed into which networks

### Next step
* Get data from Angela

**Comment by OpenMatt** [comment]
An old grants graphic we created:

![grants graphic 001](https://cloud.githubusercontent.com/assets/1007376/10347359/70cbac08-6d01-11e5-8da2-f790616a9034.jpg)

Note: this is no longer how we count grants money, so will need re-thinking.

**Comment by OpenMatt** [comment]
Networks would likely include:

MozFest 

Hive
Gigabit Hive
Clubs
Maker Party

News
Science
Open Web

**Comment by chrislarry33** [comment]
@OpenMatt hive/gigabit hive are the same dont need to be separated out

**Comment by OpenMatt** [comment]
Angela says
* it’s doable to get you this info as long as the definition of networks is clear. 
* We now have a list of grants from 2010 onwards (data from 2008  and 2009 is hard to break out from grand totals - we don’t have that specific info).
* We could just use the same bubbles per year and instead show the amounts raised for networks (instead of total grants secured).

**Comment by OpenMatt** [comment]
@ Angela: let me know if you still want to do this? Or if we should set aside, given that you're ill?

**Comment by aplohman** [comment]
If getting the data tomorrow is too late for design, ok to set this one aside. I can make sure to have the numbers on hand next week in case we want to talk about them or show them in a table or on a slide in a non-graphic way.

**Comment by OpenMatt** [comment]
@aplohman if you want to post the data here Fri we will do the best we can. Especially since the design won't be complicated.

**Comment by OpenMatt** [comment]
closing
