### ISSUE TITLE
Find a new home for community etherpads

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#599]

**Comment by simonwex** [comment]
Meeting scheduled for Oct 10; https://public.etherpad-mozilla.org/p/aetherpad

**Comment by simonwex** [comment]
Most of these have been archived and/or hosted on the new public etherpad-lite instance. Bumping as work continues as we track down team site owners.

**Comment by ldecoursy** [comment]
Teams have been provided with links to their previous team etherpads. Planning to provide alternate space  - more to come. Closing.

**Comment by ldecoursy** [comment]
A few science communities still outstanding.
