### ISSUE TITLE
MozFest Site Ready

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#6]

**Comment by edrushka** [comment]
Studio Mofo is beginning this work now. Creative brief to be posted soon.

**Comment by edrushka** [comment]
@davidascher can I close this ticket? Sarah and I will map out the site creation bugs if/when that project is a go for 2015.

**Comment by davidascher** [comment]
Hey you're in charge. Make the tickets work for you!

**Comment by edrushka** [comment]
###### I'm in charge?
#### I'm in charge.
## I'm in charge!
# **I'M IN CHARGE!**

![Take that!] (http://media.giphy.com/media/BGohxabK7BbmU/giphy.gif)

(Could not resist this golden opportunity to practice my markdown.)
