### ISSUE TITLE
Build and ship new webmaker.org on-boarding experience

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#60]
Build and ship the initial on-boarding experiment based on X-Ray Goggles

Phase: Design / Build / Ship
Owner: @secretrobotron 
Decision: @thisandagain
Consulted: @adamlofting, @iamjessklein, @HPaulJohnson
Lead design: @xmatthewx  
Lead dev: @ScottDowne 
Quality: @cassiemc 

_(continued work from #52)_

**Comment by secretrobotron** [comment]
ping @simonwex @thisandagain if we want to provide a real build for this task in this heartbeat, we need a dev, yes?

**Comment by cassiemc** [comment]
I'm assigning the UI here to @xmatthewx . I'll support / design review as needed but the main challenge will be his!

**Comment by secretrobotron** [comment]
@HPaulJohnson after this goes live, we can shut off the Optimizely test we have running, and just use the winning variant. Let's have a new test to measure impact between that variant and the on-boarding experience.

**Comment by HPaulJohnson** [comment]
@secretrobotron sounds good. just let me know when to pause it.

**Comment by adamlofting** [comment]
I'm just catching up on the work so far this year, but I'm excited about this on-boarding piece :smile:  

The Goggles workflow isn't tracked in Google Analytics in the same way as the other apps so we'll want to give some thought into how we measure this. 

However, as there isn't currently any guided on-boarding I don't think we need to A/B test this against what we have. Instead we treat this new flow as the future control, look at how it performs, and then how we can make it even better over time with testing.

**Comment by thisandagain** [comment]
:+1:

**Comment by HPaulJohnson** [comment]
good to have you back, @adamlofting!

**Comment by iamjessklein** [comment]
:+1:  @adamlofting also this now gives us the opportunity to layer on additional interactions and test that  - a la the snippet.

**Comment by thisandagain** [comment]
Hey @secretrobotron @ScottDowne could we get a status update?

**Comment by secretrobotron** [comment]
@thisandagain: spoke with @ScottDowne. Some ie11 and login bugs/reviews stopped progress on Friday. Should be wrapped up today.

**Comment by secretrobotron** [comment]
Done!

**Comment by thisandagain** [comment]
:boom: Wonderful job folks. Thanks for pulling this off @ScottDowne and @xmatthewx. :smile:
