### ISSUE TITLE
Curriculum template design review

### ISSUE THREAD

**Issue by chadsansing** [MozillaFoundation/plan#600]
* **Current status:** Our current teaching activity template is a combination of Thimble templates from the previous two years migrated into GitHub as a prototype earlier this year. 
* Now that we have a Curriculum Developer for Web Literacy creating materials at a steady pace, we want to think through design and a process for moving forward. 
* **New curriculum template?** We believe we need a stronger, more horizontal template for curriculum, as well as basic design guidelines to share with community members to help them develop any contributions that use our templates.

### Project Brief
See specifics here: http://mzl.la/curriculum_template

cc @zee-moz

**Comment by OpenMatt** [comment]
#### Next steps
* Set up kick-off meeting w. Design (@cassiemc + ) to work out next steps

**Comment by hannahkane** [comment]
We can probably start this this heartbeat. Might be good to add to the brief some of the questions in the [Design Brief](https://docs.google.com/document/d/1H4rDTT7zdvOFhGlgMDIuRLlTRlAxMsU_-mUehv_iEZU/edit)

**Comment by chadsansing** [comment]
@hannahkane, can do, but will ask for help w/ a few prompts to make sure I'm including what's helpful. Today or Monday I'll also send a calendar invite for a kick-off. I'll include @cassiemc, @hannahkane, @zee-moz, and whom else?

**Comment by cassiemc** [comment]
This will be great, looking forward! Thanks for all the awesome thinking in the design needs doc, @chadsansing. Maybe we can go through the design brief together during our kickoff... good to talk through that in person and ask questions / get clarifications. 

We have the teach triage meeting later this afternoon then I should have a better idea of whether @sabrinang or @kristinashu can attend as well.

**Comment by hannahkane** [comment]
Also, I might not be able to attend b/c I'll be at the Webmaker work week, but don't want to slow down progress on this, so please feel free to meet without me.

**Comment by chadsansing** [comment]
@cassiemc, @hannahkane: took a run here https://docs.google.com/document/d/1HJ2vrsFffg4yd0-RugSuKxlf9oZEffLqrnEitGRNz04/edit & commented @hannahkane for a few assists; please edit whatever seems unhelpful or lacking in specificity and we can talk through it soon.

Once we know if @sabrinang or @kristinashu can participate, I'll set up an invite.

**Comment by hannahkane** [comment]
@chadsansing - awesome job with the doc. I added my two cents. both @kristinashu and @sabrinang will participate, so feel free to schedule a time that works for all of you, and I'll try to attend as well!

**Comment by hannahkane** [comment]
actually - given what's going on this heartbeat, maybe we should schedule the kickoff for Monday, the 19th, and then we could devote the second half of the heartbeat to it?

**Comment by chrislarry33** [comment]
This is a piece of work that when completed will really be of benefit and will help us grow web lit curriculum rapidly internally and with our networks.

**Comment by hannahkane** [comment]
The kick-off meeting happened on Friday. Can someone who attended (@chadsansing or @kristinashu?) please clarify what the deliverable for the end of the heartbeat should be? Maybe this heartbeat is about design, and the next heartbeat is about implementation?

**Comment by kristinashu** [comment]
@hannahkane not sure I'll be able to finish design this heartbeat. Can we say 'wireframes' are due for this heartbeat? This will help determine the content structure before getting into the actual design, and then implementation.

**Comment by hannahkane** [comment]
Sounds reasonable to me. I'll update [relevant Teach ticket](https://github.com/mozilla/teach.mozilla.org/issues/1319).

**Comment by hannahkane** [comment]
Nice work from @flukeout here: https://github.com/mozilla/teach.mozilla.org/issues/1360

Will finalize in next heartbeat.

**Comment by flukeout** [comment]
@hannahkane I've updated the template with a few icons and a 'narrow mode'...
http://flukeout.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-kraken.html#overview

![image](https://cloud.githubusercontent.com/assets/25212/10892058/4a2bb318-8156-11e5-8439-da11fafaa54d.png)

Next up, converting to a Remixable Thimble project.

**Comment by hannahkane** [comment]
@flukeout - looks nice in the image you included! When I tried it from your github link, the menu got weird at the smaller size:

![screen shot 2015-11-02 at 2 52 28 pm](https://cloud.githubusercontent.com/assets/8389648/10896851/7bf53ce6-8171-11e5-9f6d-81b2c01d412c.png)

**Comment by chadsansing** [comment]
Let's also consider a good print CSS a requirement for educators and clubs in lo-fi/no-fi settings. Those educators will want to print materials to use and to share as noted in Laura's latest research share.

**Comment by hannahkane** [comment]
+1

**Comment by hannahkane** [comment]
Good progress on this, but since we've just added a new requirement (print version), rolling into next heartbeat.

**Comment by hannahkane** [comment]
Going to close this one and will add more specific follow-up steps including: creating a plan for implementing the new styles across existing curriculum including localizations; resolving "Remix" button conflict in the Thimble versions
