### ISSUE TITLE
Finalize poster spread for board meeting

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#601]
New meta-ticket to track all production & printing items. Here's an updated spread:

<img width="853" alt="screenshot 2015-10-12 17 19 26" src="https://cloud.githubusercontent.com/assets/541325/10439067/8b51cafa-7105-11e5-9f6a-ed330cf84af0.png">

@openmatt and @msurman, we need to know from Phia the size of the room so @lovegushwa can finalize the dimensions.

< @lovegushwa will add dimensions for 9 side-by-side posters so we can determine correct dimensions for printer >
 
A - D are advocacy-related. E - H are leadership related. We will have a center slide summarizing the two-sided strategy proposed in the board deck.

Sub-tickets:

A. Intro slide for advocacy https://github.com/MozillaFoundation/plan/issues/602
B. List and revenue growth, 2010 - 2015 https://github.com/MozillaFoundation/plan/issues/603
C. Grassroots organizing and partners https://github.com/MozillaFoundation/plan/issues/604
D. Evolution of advocacy program + partners, 2010 - 2015 https://github.com/MozillaFoundation/plan/issues/605 
E. Intro slide for leadership https://github.com/MozillaFoundation/plan/issues/606
F. Mozilla Festival 2010 - 2015 https://github.com/MozillaFoundation/plan/issues/607
G. Who is part of the leadership network? https://github.com/MozillaFoundation/plan/issues/608
H. Evolution of leadership networks, 2010 - 2015 https://github.com/MozillaFoundation/plan/issues/609 
Center slide https://github.com/MozillaFoundation/plan/issues/610

**Comment by lovegushwa** [comment]
<img width="1255" alt="screen shot 2015-10-12 at 4 32 14 pm" src="https://cloud.githubusercontent.com/assets/12228435/10441536/ddeccd70-70fe-11e5-8451-3f5c876046a9.png">

@openmatt We need to confirm the available space in the room

**Comment by OpenMatt** [comment]
Phia emailed them to find out.

**Comment by OpenMatt** [comment]
[Mozilla Floorplan with Measurements.pdf](https://github.com/MozillaFoundation/plan/files/12101/Mozilla.Floorplan.with.Measurements.pdf)

**Comment by lovegushwa** [comment]
@OpenMatt  good they will fit. Not sure who is installing these but it would seriously do the masking tape to the wall (a long piece of tape so it has some sticking power) then double sided foam tape on the posters. 

Any news on the printing drop dead time? (you more time you can buy us for proofing and corrections the better.)

**Comment by OpenMatt** [comment]
### Printing drop-dead times
for files to be delivered
* for foamcore: 3pm PT Tues
* for paper satin finish 9:30am PT Wed

@lovegushwa understood?

**Comment by OpenMatt** [comment]
### Dimensions
* We just confirmed that the "window wall" -- the wall at the bottom -- is 23.38ft wide. 
* @lovegushwa how does that impact your plans?

[Mozilla Floorplan with Measurements.pdf](https://github.com/MozillaFoundation/plan/files/12580/Mozilla.Floorplan.with.Measurements.pdf)

**Comment by OpenMatt** [comment]
#### Final tweaks

##### Leadership
1) Leadership Network
Connie Yowell -- spelling = "ally"

**Comment by OpenMatt** [comment]
2) Leaddership Network
Dian
* upper case "Regional Coordinator"

**Comment by OpenMatt** [comment]
3) Evolution of Leadership Network
a) change title of this poster to: "Evolution of Leadership Network". Try to fit on one line.
b) Typo w. line break: "Since 2010, we’ve been building networks with..."
c) boldface the first paragraph

**Comment by OpenMatt** [comment]
4) Advocacy
a) We have **** a **** strong relationship with Mozilla policy team in MoCo.

**Comment by OpenMatt** [comment]
5) Email List and Revenue Growth 
* Copy should read: 
"Mozilla has more than doubled the size of our list since 2013 (10x the NGO benchmark)"

**Comment by OpenMatt** [comment]
6) Grassroots Organizing
and Partnerships
a) (fix the line break so that "and Partnerships" are together on the second line
b) boldface the first paragraph

**Comment by OpenMatt** [comment]
7) Evolution of Advocacy Program and Partnerships
a)  cut the first paragraph
b) boldface the (new) first paragraph
c) update last paragrph to: 
"Over the next few years, we can continue evolving Mozilla as a global advocacy organization—one that's responsive to global open internet issues that can quickly emerge, is representative of its global community, and proactively advances its vision and agenda for an open internet."

**Comment by OpenMatt** [comment]
7) Evolution of Advocacy Program and Partnerships
d) add a period after "Win".  "Win. FCC votes to protect Net Neutrality."
