### ISSUE TITLE
Finalize A. Intro slide for advocacy

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#602]
This is an opening slide for advocacy. Needs text from @benrito

**Comment by lovegushwa** [comment]
@benrito @OpenMatt  ... 50 words or so for intro slides is perfect. 
<img width="579" alt="screen shot 2015-10-12 at 3 01 18 pm" src="https://cloud.githubusercontent.com/assets/12228435/10444949/dfc3ed14-7120-11e5-8149-e43115264a4b.png">

**Comment by OpenMatt** [comment]
@benrito @lovegushwa given that we may be pressed for space in the room (and time) we could kill both these two "intro" slides

**Comment by lovegushwa** [comment]
@OpenMatt @benrito I'm ok with that.

**Comment by benrito** [comment]
your call, however time not a problem. i think they might be helpful for summarizing the strategy. i will put text now and we can decide.

**Comment by lovegushwa** [comment]
@OpenMatt @benrito we would also print this small, like letter size.

**Comment by OpenMatt** [comment]
@lovegushwa given that:
1) we don't have approved copy from @msurman (which he's likely to have strong feelings about) and 
2) that we are short on space in the room, I vote for killing the intro posters.

**Comment by benrito** [comment]
This is straight from Mark's deck:

ADVOCACY

We've developed a real ability to mobilize people, tapping into growing concern about internet issues.

We have strong relationship with Mozilla policy team in MoCo. Our shared policy + advocacy model seems to be working.

Also, we’ve gotten on the public radar as an advocacy brand. We have ~1.7M people on our advocacy and fundraising list.

Building on the mobilization capacity we have now, we will: Grow a global network of millions of people who want to protect the open web and sustain the internet as a global public resource. We need to invest in new staff and infrastructure to do this.

**Comment by benrito** [comment]
if you drop the last paragraph (i.e., next steps which will already be on center slide), we're at 50 words

**Comment by OpenMatt** [comment]
ok. given that we have copy, let's do it. Mark can make a real time call whether to include or not.

**Comment by OpenMatt** [comment]
@lovegushwa let's do it.

**Comment by lovegushwa** [comment]
@OpenMatt @benrito 
<img width="1157" alt="screen shot 2015-10-13 at 12 37 24 pm" src="https://cloud.githubusercontent.com/assets/12228435/10466096/36ca1332-71a7-11e5-819f-6203794a9785.png">

**Comment by OpenMatt** [comment]
Wrong title. Should read: "Advocacy"
