### ISSUE TITLE
Finalize  B. List and revenue growth, 2010 - 2015

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#603]
This is mock 1 from #593, done Mark's way to combine list growth and revenue growth on the same graphic.

"I want to make the argument to the board that small dollar fundraising and advocacy work are related, and that there is some rough correlation both in terms of supporter growth and growth in our capacity.

Part of the reason is because I think this is true :). But, also, it's a good way to make the argument that this is a place for us to invest significant additional $$"

**Comment by benrito** [comment]
![9a4bb964-6ec4-11e5-9d0a-b683e788604b](https://cloud.githubusercontent.com/assets/541325/10439374/6f8a09f2-7107-11e5-811d-b85a917c60a4.jpg)

**Comment by benrito** [comment]
Should find a way to include this data point as well:

![2ac90496-7029-11e5-84aa-8a400268a606](https://cloud.githubusercontent.com/assets/541325/10439439/ebf346b6-7107-11e5-9b2f-c2017ebf16ac.png)

**Comment by lovegushwa** [comment]
<img width="861" alt="screen shot 2015-10-12 at 1 45 49 pm" src="https://cloud.githubusercontent.com/assets/12228435/10439669/49d84122-70f0-11e5-8457-617d5245a025.png">

**Comment by msurman** [comment]
@lovegushwa can we make this one chart rather than two? The idea is to show the number of people on list and amount of money in direct relationship to each other.

**Comment by lovegushwa** [comment]
@msurman @benrito @OpenMatt check out the draft here, we need to pin down any other copy we want to include. https://redpen.io/p/cz74da0f9085226545

Will probably change yellow to purple.

<img width="1294" alt="screen shot 2015-10-13 at 3 02 19 am" src="https://cloud.githubusercontent.com/assets/12228435/10451901/df09c8e4-7157-11e5-98b2-5945ae089e41.png">

**Comment by benrito** [comment]
Hey @lovegushwa, could we get a stripped down, monochrome version of this that would look good on a board deck slide?

I.e., just the trend lines and labels?

**Comment by lovegushwa** [comment]
Final, check the redpen: https://redpen.io/p/cz74da0f9085226545

<img width="1285" alt="screen shot 2015-10-13 at 9 51 05 am" src="https://cloud.githubusercontent.com/assets/12228435/10461804/03c2d76a-7190-11e5-8f39-d2bf9c900b7d.png">

**Comment by lovegushwa** [comment]
@benrito 

![deck-chart](https://cloud.githubusercontent.com/assets/12228435/10461939/a9455d66-7190-11e5-8db4-678ce4a400cf.jpg)

**Comment by OpenMatt** [comment]
@lovegushwa 
copy should read:
* "Mozilla has more than doubled our list size since 2013 (10X NGO benchmark)"
* I would delete the other note about having the largest email list. The ways its worded now is clunky.

**Comment by benrito** [comment]
@OpenMatt @lovegushwa let's keep the bit about largest email list (it's a hot story) but remove "likely"

"Mozilla now has the world's largest email list focused exclusively on open web issues"

@OpenMatt do you need the background removed from monochrome version above?

**Comment by OpenMatt** [comment]
Yes let's remove background

**Comment by lovegushwa** [comment]
@benrito  the "likely" came from @valianttry 
I can remove but wanted to make sure you saw this:

#593 4th from last post.
"I told @OpenMatt I'm not 100% comfortable saying that we are "the largest list focused on web issues" because it is not really possible to confirm that, even though I think it's probably true. I would say "We are likely the largest and growing".

**Comment by jgmac1106** [comment]
There is a 0.94 Pearson correlation between your email list and the funds
raised (using the two closest data points as product-moment... So it
probably means nothing (since the data points do not align petfectly in
timeline) but was a fun thought exercise.

That is almost a perfect 1:1 match.

**Comment by lovegushwa** [comment]
@benrito @OpenMatt 

![deck-chart](https://cloud.githubusercontent.com/assets/12228435/10462246/85be9202-7192-11e5-9b53-3c75b0cd788d.jpg)

**Comment by benrito** [comment]
@valianttry any final amendments before we close the ticket?

can we find the least awkwardly worded way to unambiguously claim credit for our email list accomplishment? :)

**Comment by benrito** [comment]
@lovegushwa should we add header on this (and others?)

**Comment by lovegushwa** [comment]
@benrito that's what I'm thinking. Can do when I drop into indesign. What should be say?

**Comment by benrito** [comment]
Let's use the titles in the tickets—for this one it's "List and revenue growth, 2010 - 2015"

**Comment by valianttry** [comment]
@benrito love the enthusiasm, but i'm (again) uncomfortable saying we have the largest list. there's no way to verify and getting caught in a lie sux. "One of the largest email lists for the Web" or "Probably the biggest email community fighting for the Web". The accomplishments stand on their own in most circles, we don't need to embellish :smiley_cat:

**Comment by benrito** [comment]
ok, noted! @openmatt can make the call on what goes on the slide.

**Comment by OpenMatt** [comment]
* @lovegushwa kill the "largest list" comment. 
* just go with: "Mozilla has more than doubled our list size since 2013 (10X NGO benchmark)"

**Comment by lovegushwa** [comment]
@benrito @OpenMatt final:

<img width="1252" alt="screen shot 2015-10-13 at 12 41 26 pm" src="https://cloud.githubusercontent.com/assets/12228435/10466192/c7a803dc-71a7-11e5-9136-a33605ef8bcd.png">

**Comment by benrito** [comment]
hey @lovegushwa! please add the header?

**Comment by OpenMatt** [comment]
@lovegushwa should be: "$6.5M cumulative total"
