### ISSUE TITLE
Finalize C. Grassroots organizing and partners

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#604]
This is mock 4 from #593 done Mark's way, which is to put most of the emphasis on the map:

    Copy should put stronger focus on advocacy and 'teach-in' side of things
    -> Want to show that teaching is on action people can take in grassroots campaigns
    -> And, make the point that Maker Party is our most successful ftf / grassroots campaign so far

    Still focus on leaders, but shine a bigger light on number of cities and countries
    -> This shows that we can organize at grassroots when we have a clear CTA
    -> And, should set up why to invest in doing more systematically (e.g. Sara's work + Amira's work)
    -> That said, keep the 'young leaders' emphasis -- the youth piece here is strong and worth keeping

    On visuals, make the map bigger and have half the number of photos (or something like that)
    -> Just less busy than right now

And merging mock 2 onto the map:

Can we make this more of a 'partners' network map? And mix partner orgs from both maker party and political advocacy? Maye show different colour for each of those two?

Simple approach would be:

Network map that roughly spans regions, like a spider web
Small icons for partners in each category tied to their region

Here are options from Amira:

 Dnet = Bangladesh
NWP = USA
CoderDojo = Global (but we can pin them to Ireland/London)
School of Open = East Africa (can pin to Kenya)
Code for Cape Town/Creative Commons = South Africa
Girls Learning Code/ Toronto Public Library/Textile Museum of Canada/YWCA = Toronto
NYC Department of Education/Brooklyn Public Library = NY
Institute of Museum and Library Services = USA
P2PU = Global
National Service Citizen/Think Big/Wikimania = London
Digital Harbour Foundation = Baltimore
Sproutfund = Pittsburgh
St Albert Public Library = Alberta
Xinjiang Lake Xudong Community - China
Song of Priya - Mumbai
CERN Webfest = Switzerland
Telecenter = Europe
Code Rise = Columbia
Code for Nepal = Nepal

Other data we could include:

    2014 Global MP Partners: 300 organizations
    I'd be comfortable saying 500+ Global partners from Summer Code Party-2015 MP

**Comment by benrito** [comment]
For design inspiration:

![64ec5e06-6ee0-11e5-9549-57c6e5d25d2d](https://cloud.githubusercontent.com/assets/541325/10439470/137b84d2-7108-11e5-8ece-30e479c6ffb1.png)
![01083928-6ee0-11e5-93bb-5db20ae7a60d-2](https://cloud.githubusercontent.com/assets/541325/10439469/137852c6-7108-11e5-862a-02629613fa6e.jpg)

**Comment by benrito** [comment]
![9a56822c-6ec4-11e5-9461-639c751cd676](https://cloud.githubusercontent.com/assets/541325/10439691/a6430280-7109-11e5-88d0-f2ca3677fe8b.jpg)

**Comment by lovegushwa** [comment]
@msurman @OpenMatt @benrito 

<img width="1281" alt="screen shot 2015-10-12 at 8 29 28 pm" src="https://cloud.githubusercontent.com/assets/12228435/10444999/b1d90280-7121-11e5-9577-6cf14ea6a9d0.png">

I'm just finishing up the grassroots partners, I'll be adding the coalition logos, some stats and a key next. I'll continue to post updates and any questions as I progress tonight.

**Comment by msurman** [comment]
@lovegushwa loving where this is headed.

**Comment by lovegushwa** [comment]
@msurman if your still awake here is an update. Going to ad some photos and copy next.
<img width="1289" alt="screen shot 2015-10-13 at 12 05 08 am" src="https://cloud.githubusercontent.com/assets/12228435/10447988/486acda2-713e-11e5-8f64-5e31518b7818.png">

**Comment by lovegushwa** [comment]
@benrito @OpenMatt @msurman Please review on the redpen here:
https://redpen.io/p/qg435229249b6eebd9

**Comment by OpenMatt** [comment]
* @lovegushwa I left comments in RedPen. To fix up some typos. Otherwise: let's ship.

**Comment by lovegushwa** [comment]
@OpenMatt @benrito Final ?
https://redpen.io/p/qg435229249b6eebd9

<img width="1291" alt="screen shot 2015-10-13 at 10 11 53 am" src="https://cloud.githubusercontent.com/assets/12228435/10462350/1dc4904c-7193-11e5-9e0a-4bff9af76ebe.png">

**Comment by benrito** [comment]
@lovegushwa can you add a partner in rio de janiero: "ABCID"

**Comment by benrito** [comment]
@valianttry and last comments before we close this?

**Comment by OpenMatt** [comment]
* One typo. Should be: "Sprout Fund"

**Comment by valianttry** [comment]
Squinted and tried to read it all, but i think it's OK? There are a load more grassroots orgs we could list, but i think the original graphic by @OpenMatt only had room for 5-6 so that's all I provided. Probably not a big deal but if you want a bigger list that provides more weight to matche the maker party weight on this map i can.

**Comment by OpenMatt** [comment]
thanks Andrea. @lovegushwa we're out of time: let's ship.

**Comment by benrito** [comment]
per @msurman request i'm going to peck out a few explanatory sentences here

**Comment by benrito** [comment]
Text for the poster:

Mozilla brings brand weight and influence to a global coalition.

Mozilla is also a global grassroots movement that mobilizes to teach, shape and defend the internet.

Maker Party, for instance, is Mozilla’s “teach the web” campaign with 5,327 events taking place in 450 cities since 2012.
