### ISSUE TITLE
Finalize D. Evolution of advocacy program + partners, 2010 - 2015

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#605]
Current mockup:

![red-pen-860205e2-a9d9-4275-c12c-9d3828d1ab71](https://cloud.githubusercontent.com/assets/541325/10439532/843de750-7108-11e5-8469-9e4bfe5c9b09.jpg)

Redpen: https://redpen.io/fgb6061fa355d07fb9

Will be incorporating mock 3 from #593 

![9a8594d6-6ec4-11e5-94c0-91619357abe7](https://cloud.githubusercontent.com/assets/541325/10439543/92772a20-7108-11e5-92ad-27f4fa7754dd.jpg)

**Comment by lovegushwa** [comment]
Still editing this, will post a new version after I finish in the morning.

**Comment by OpenMatt** [comment]
@lovegushwa let me know when there's a version I can proof

**Comment by lovegushwa** [comment]
@OpenMatt pulling this together next.

**Comment by lovegushwa** [comment]
@almost done with this, last big design push, stay tuned.

**Comment by lovegushwa** [comment]
@benrito @OpenMatt please proof:
https://redpen.io/p/apae82f9b0296147e6

<img width="1290" alt="screen shot 2015-10-13 at 12 32 50 pm" src="https://cloud.githubusercontent.com/assets/12228435/10465997/9b2421ac-71a6-11e5-8748-511a4fdc977c.png">

**Comment by OpenMatt** [comment]
@benrito can you help?
* "Collusion / Lightbeam" arrow is in wrong spot
* "expert consensus for cyber policy" (not: "experts")
* @benrito is Lightbeam logo int the right spot? Not sure why its there
* check order of advocacy row. This has "winning" first -- and *then* launching a campaign. Looks wrong.

**Comment by benrito** [comment]
good finds matt—fixes and additional comments in the redpen.

**Comment by benrito** [comment]
Explanatory text for the top:

Mozilla has not historically been an “advocacy” organization that mobilizes and enables supporters to run campaigns for the open internet. Nor has Mozilla been a cause that accepts donor support, in the way that other non-profits, campaigns, and social enterprises do.

Since 2010, we’ve slowly and organically implemented the foundations for a powerful global advocacy program—one that can affect public opinion and grow an important constituency.

Over the next few years, we can continue evolving Mozilla as a global advocacy organization—an organization which is responsive to the global open internet issues that can quickly emerge, is representative of its global community, and proactively advances its vision and agenda for an open internet.

**Comment by lovegushwa** [comment]
<img width="1284" alt="screen shot 2015-10-13 at 1 59 44 pm" src="https://cloud.githubusercontent.com/assets/12228435/10468222/b86069d6-71b2-11e5-9b87-8d6244269aa6.png">
