### ISSUE TITLE
Finalize E. Intro slide for leadership

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#606]
This will introduce the leadership slides. Needs text from @benrito

**Comment by OpenMatt** [comment]
@benrito status? Drop dead time for file delivery is 6pm ET, so will need asap!

**Comment by benrito** [comment]
This is straight from Mark's deck:

LEADERSHIP

Starting with Drumbeat in Barcelona, we've become skilled at convening people and building networks.

This is our special sauce. We have a hands-on, “hacker spirit” convening style keeps people coming back.

We now have a rich and diverse global network of over ~5,000 community leaders closely tied to Mozilla.

Evolving the networks we’ve already built, we will: Grow a global network of highly talented leaders who want to tackle the big issues of the web (‘hills’) and sustain the internet as a global public resource.

**Comment by benrito** [comment]
if you drop the last paragraph (i.e., next steps which will already be on center slide), we're at 50 words
