### ISSUE TITLE
Finalize  F. Mozilla Festival 2010 - 2015

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#607]
source file is here: https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1ZjYyZWFoY0dYVlE/view?usp=sharing

![86d6e33e-6ea8-11e5-9c54-6160ffd94683](https://cloud.githubusercontent.com/assets/541325/10439711/ca01b752-7109-11e5-976a-a7e57ec1ec27.jpg)

**Comment by OpenMatt** [comment]
@lovegushwa if the version above is still most current, I'm signed off on proofing. This one can be output to PDF and closed.
