### ISSUE TITLE
Finalize G. Who is part of the leadership network?

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#608]
Was: https://github.com/MozillaFoundation/plan/issues/577

**Comment by lovegushwa** [comment]
<img width="1292" alt="screen shot 2015-10-12 at 12 01 07 pm" src="https://cloud.githubusercontent.com/assets/12228435/10439732/db72da5c-70f0-11e5-879e-7686c36e4fe5.png">

**Comment by benrito** [comment]
Opening up a quick conversation based on touchpoints with Mark, Michelle and others.

@thornet and @laurareynal object to portrayal of Dian as a young leader.

"This isn't quite right, as she's a professional museum curator and brings her networking, fundraising and event organizing skills to Mozilla and is definitely benefiting from learning open practices, how to teach, and how to collaborate as a network."

At the same time, Mark has a desire to represent the capability of the leadership network to collaboratively produce software and resources. Will be tough to add a new poster on our timeline, so here's a possible "two birds" solution.

@omnignorant could we sub in a young leader / collection of young leaders from the Ride with Me team? If so, could you help provide content per the template above?

@msurman @chrislarry33 @OpenMatt do you approve the above? Mark, this would help tell the "software through participation in networks" story a bit.

**Comment by LauraReynal** [comment]
For young leader portraits, I think we could also portrait Raj or Suchita. @KevZawacki has a story ready for Suchita

**Comment by chrislarry33** [comment]
Hi all,

At this stage I think we roll with what we have for the board meeting. We can and should fix post board meeting when we use in more public ways.

**Comment by omnignorant** [comment]
I'm with @chrislarry33 on this, but will keep my eyes open for a final call.

However, if it's decided we need to make an immediate change, when do you need this by? For reference, we have an 18 year old girl (recent blog on Webmaker) and a 20-ish guy who's got a blog post in the queue.

**Comment by benrito** [comment]
Seems consensus is to fix after board meeting. Let's stick with what we have unless @msurman wants to pursue a software related story.

**Comment by msurman** [comment]
Yes, let's fix post board meeting.

**Comment by msurman** [comment]
Thanks all -- these are great!

**Comment by OpenMatt** [comment]
@lovegushwa can we output a final version for proofing?

**Comment by OpenMatt** [comment]
@lovegushwa mistakes to correct in poster above:
For all:  delete the last bullet in each story. It's a duplicate from what's above. 

1) Connie Yowell
* fix typo in her quote. "Mozilla has been a real ally..."
* update the "x" to ~$10.8M

2) Jackie Moore
* add title. Jackie Moore, Founder, Level Up Youth Maker Space

3) Harlo
* Italicize "the New York Times"

**Comment by lovegushwa** [comment]
Final version:
https://redpen.io/p/xube5a3be657f760de

<img width="1161" alt="screen shot 2015-10-13 at 10 53 02 am" src="https://cloud.githubusercontent.com/assets/12228435/10463328/e0a9fba6-7198-11e5-9d46-569d117bed80.png">

**Comment by OpenMatt** [comment]
Connie:
Typo. Should read:
* "Mozilla has been a really ally..."

Jackie
* Should say: "Professional" (not Profession)

Harlo
* should say "Emerging Leader"

**Comment by omnignorant** [comment]
Not a major thing, but just want to note for due diligence: I checked Jackie's official Hive designation and it's "Jackie Moore, Executive Director, Agape Werks, Inc | LevelUP IRL"

LevelUP IRL is their maker space in the mall. Agape Werks is her org name. It's up to you how much you need to tweak polish that.

**Comment by OpenMatt** [comment]
thanks @omnignorant. What's there now is fine for the poster, but good to know.

**Comment by lovegushwa** [comment]
<img width="1159" alt="screen shot 2015-10-13 at 2 02 33 pm" src="https://cloud.githubusercontent.com/assets/12228435/10468284/19dd4d50-71b3-11e5-928f-293c2be8590d.png">
