### ISSUE TITLE
Finalize H. Evolution of leadership networks, 2010 - 2015

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#609]
This is where we finalize the leader stuff from #576 

Current mock:

<img width="1292" alt="red-pen-ae359e51-60ca-4e35-aa41-7822ad2f3ff5" src="https://cloud.githubusercontent.com/assets/541325/10439582/db64213e-7108-11e5-8a83-9d96d308d191.png">

Redpen:
https://redpen.io/oy93f96f8fefe63aa2

**Comment by lovegushwa** [comment]
@msurman @benrito ... Check out the updated final version on Redpen. Still need to drop into indesign and add text.  https://redpen.io/p/apae82f9b0296147e6

<img width="1290" alt="screen shot 2015-10-13 at 3 01 54 am" src="https://cloud.githubusercontent.com/assets/12228435/10451838/7415af94-7157-11e5-9417-07f165ff91e2.png">

**Comment by cassiemc** [comment]
This looks *fantastic* guys, great work @lovegushwa, much simpler and easier to understand. My only question is why some lines are broken / dashed, but I'm also okay with that ambiguity. I figure it means something about peripheral projects or influences outside the Foundation.

**Comment by lovegushwa** [comment]
@cassiemc yes your right about the broken line, outside the foundation, Or in the case of the yellow line our involvement is phasing out.

**Comment by OpenMatt** [comment]
@lovegushwa are we ready to mark this one closed + output PDF? (Looking to start closing tickets given final deadline for file delivery is 6pm ET today.)

**Comment by lovegushwa** [comment]
@OpenMatt I think this is ready to close, we need to proofread everything together later today.

**Comment by OpenMatt** [comment]
@lovegushwa is the version above still current? Can I go ahead and proof it?

**Comment by benrito** [comment]
Just need numbers. These will suffice for board meeting but could be refined after.

Badges: $~4.5m
Software: nothing (remove label)
Hive: $~9.5m
OpenNews: $6.6m
Open Web Fellows: ~$4.5m
ScienceLab: $3.2m

**Comment by OpenMatt** [comment]
@benrito do you have the missing financial data to plug in?

**Comment by OpenMatt** [comment]
* one copy thing: "Open News" is two words
* rest of the copy in the design version above looks good

**Comment by benrito** [comment]
Explanatory text is here:

Since 2010, we’ve been building networks with public interest and philanthropic organizations that share our interest in open web issues.

These networks draw new people into Mozilla’s mission—and enable us to cultivate leaders, catalyze new innovations, and wield influence.

What is common across these networks is an open, collaborative, networked way of working. People come through Mozilla networks and have an opportunity to be recognized for meaningful work with a supportive, global community. This “network of networks” is something we can grow and strengthen in our next 5 years.
