### ISSUE TITLE
Finalize Center slide

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/plan#610]
This is a center spread for #601.

A restyling of these two slides:

<img width="842" alt="screenshot 2015-10-12 17 46 52" src="https://cloud.githubusercontent.com/assets/541325/10439639/4394d65e-7109-11e5-8c01-eaab458f612a.png">
<img width="826" alt="screenshot 2015-10-12 17 46 48" src="https://cloud.githubusercontent.com/assets/541325/10439640/439b85bc-7109-11e5-85c5-ab9842723f9c.png">

**Comment by OpenMatt** [comment]
@benrito still needed?

**Comment by benrito** [comment]
I say let’s do it

**Comment by OpenMatt** [comment]
@lovegushwa : need any further help / direction on this one?

**Comment by benrito** [comment]
New text to accompany the graph:

Building on MoFo’s last five years, we will:

1. Strengthen thought leadership, using platforms like MozFest and ‘State of the Web’.

2. Establish Mozilla Leadership Network, building on our existing fellowships and networks.

3. Build a world class advocacy engine, getting more people involved in taking our ‘hills’.

(this is pulled from Mark's deck).

Along with the graph, we might consider arrows or other iconographic elements to flow into the poster series that will be displayed on either side.

**Comment by OpenMatt** [comment]
@lovegushwa work for you?

**Comment by OpenMatt** [comment]
We're killing this one. Out of time and space.
