### ISSUE TITLE
Moz spaces - kiosks for Webmaker & Thimble

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#611]
The Webmaker work week revealed what seems like an easy opportunity for learning products. Kiosks in Moz spaces could help gather MoCo support for our work and offer visitors the chance to experience a more full range of Mozilla's offerings.
  
Is this a good idea? Does the reward outweigh the cost for setup and maintenance?

 - What's required to set this up?
 - Which office would be the best for a pilot?
 - What's required to support this longterm?
 - Is there a MoCo team that can execute this with our guidance & support?

cc @davidascher @hannahkane

**Comment by hannahkane** [comment]
Is the idea to let visitors play with Webmaker and Thimble, or is it to show live usage data? (Sorry, I forget which idea we talked about.)

**Comment by davidascher** [comment]
I'd like to understand what the success criteria would be.  Are we looking
for devs to become code contributors? To promote Thimble in their own
comms?  The more specific we can be, the sharper the program design can be.

**Comment by xmatthewx** [comment]
@secretrobotron to explore this

**Comment by secretrobotron** [comment]
Yep. Pretty interested in the flavour of this. Less focus on tools. Have a few ideas about where this can go. Will write about it soon :).

**Comment by OpenMatt** [comment]
@secretrobotron status update?

**Comment by secretrobotron** [comment]
I think I'll re-scope this ticket. Talked *very* briefly about this topic with @thornet, @LauraReynal, and @davidascher in Orlando, but in the context of IoT and software as art. Worth noting: the participation team's plan includes growing moz spaces around the globe.

Interesting opportunity to have prototypes and other mechanisms for feedback present in spaces that highlight audiences for particular projects (specifically IoT, likely). I've also been interested in featuring research results, profiles, and other things to think about or play with ambiently (e.g. an empathy card game featuring profiles from research).

Success condition: a place to collect real-world feedback from many different places and people in the world.

**Comment by OpenMatt** [comment]
status?

**Comment by OpenMatt** [comment]
@secretrobotron this ticket is cool. want to move it? re-file?

**Comment by secretrobotron** [comment]
It is, @OpenMatt! I've moved it; easiest way for me to keep it in mind for now.

**Comment by hannahkane** [comment]
This ticket is a milestone that has passed. Should we roll into current or future milestone?

**Comment by hannahkane** [comment]
I'm pulling this out of the milestone, so we can close the milestone.
