### ISSUE TITLE
Prepare a brief on AMP and Instant Articles

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#614]
Google's [AMP](https://googleblog.blogspot.com/2015/10/introducing-accelerated-mobile-pages.html) and Facebook's Instant Articles have big implications on how publishers build and deliver content to people on mobile. 

As new tech, it'd be useful to prepare an internal memo on the risks to the open web. Might also be a chance to flex some thought leadership muscle. 

cc @simonwex @davidascher

**Comment by davidascher** [comment]
Talking to Myk Melez last week there are some concerns around AMP really
making google-hosted content first-class.  I don't have details, this is a
watercooler comment.

**Comment by OpenMatt** [comment]
@xmatthewx will update

**Comment by xmatthewx** [comment]
@benrito - maybe something here worth exploring for the state of the web?

I don't think this requires a planning ticket unless someone wants to take this on.
