### ISSUE TITLE
Mobile & touch devices for staff - create a plan

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#615]
We need an Ops approved device plan. Unlike laptops, it seems like staff and managers currently carry the burden of ad hoc decisions. 

A few opinions:
 1. We should stop issuing **Nexus 4** devices today. That hardware is old and will become obsolete soon. It was discontinued 2 years ago and it will not run the latest version of Android released this month. It’s good to have a couple on hand for testing, but not as a primary device moving forward. 
 2. The **Nexus 5** was released 2 years ago, discontinued last spring. It’s sufficient _for now_, but the Nexus 5x might be a better investment in the near future. 
 3. Staff need devices to test all of our sites and tools (not just Webmaker), and to understand current user experiences and paradigms. Given our emerging leadership & advocacy strategy, we will likely need **iPhones** in 2016. 
 4. I recommend that **each office** have at least one current Android and iPhone device as a shared resource. We should probably consider tablets as well. Remote designers and engineers should be a issued a device upon hire.
 5. We aren't at risk of shifting too much attention  toward our mobile tools and content. 

cc @simonwex @davidascher @cassiemc @jlin @aplohman

**Comment by gvn** [comment]
It would be valuable for people to have a Nexus 4 *and* 5x so that it's possible to test on multiple versions of Android. :+1:

**Comment by cassiemc** [comment]
I <3 this ticket and it seems reasonable to me wrt to an overall focus on quality of work and user experience, so long as we don't have a dedicated QA team.

**Comment by davidascher** [comment]
I'd like to encourage folks to get a bit specific, both in terms of:

 - who actually needs what devices
 - what budget this requires.

We have a lot of phones and tablets lying around Mozilla that end up unused
99% of the time, so also maybe a process for routing devices to where
they're needed.

**Comment by xmatthewx** [comment]
@simonwex to investigate

**Comment by simonwex** [comment]
I think we should delay this until we figure out priorities and staffing of webmaker app in the new year.

**Comment by gvn** [comment]
IMO we should consider this request beyond the immediate needs of the Webmaker team. Mobile needs to be a priority amongst our entire org, and access to devices is crucial. :iphone:

**Comment by simonwex** [comment]
I didn't have time to focus on this in this HB. Bumping to next.

**Comment by simonwex** [comment]
Our specific need for Android devices no longer exists. I'm going to work with @jlin to make sure we have a few tablets available in our offices for testing purposes of touch interactions. Other requirements for devices is covered by emulators and personal devices.
