### ISSUE TITLE
Proposal assessment tool

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#616]
During the Webmaker work week, @hannahkane began a tool for evaluating proposals and their alignment with strategy, resources, and our network of people. 

@hannahkane - do you think it's worth turning this into a spreadsheet or document we can use again? If so, I'm glad to lend a hand (notes are [in here](https://docs.google.com/a/mozilla.com/document/d/1AOj3nF-wn8uAWGXpzLr8kGHrQxpjvBlRJwW85R63YIo/edit?usp=sharing)). If not, let's close this issue.

**Comment by hannahkane** [comment]
Happy to work on this, but moving to next heartbeat.

**Comment by hannahkane** [comment]
https://docs.google.com/spreadsheets/d/1jEkoyT6VaoxGEOlj-3D7jcXp7rRY4gq1OtE5pjilzHg/edit?usp=sharing

Wondering if this might be useful as part of the phase 3 planning process for Leadership Development. @chrislarry33? For context, this is something we worked on at the Webmaker work week to help decide between different Webmaker strategy options. Could it be adapted to help make decisions about Leadership Development priorities?

If not useful, feel free to disregard. I'm closing this ticket.
