### ISSUE TITLE
Clubs updates

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#617]
- [x] [Update auto-email](https://github.com/mozilla/teach.mozilla.org/issues/1359)
 - [x] Advance work on [Clubs Report functionality](https://github.com/mozilla/teach.mozilla.org/issues/1357)

**Comment by hannahkane** [comment]
Waiting on final email copy, and will solicit some feedback on Clubs Report wireframes during MozFest.

**Comment by hannahkane** [comment]
Didn't happen this heartbeat. Rolling to next.

**Comment by ldecoursy** [comment]
Auto-email now live! :dancers:

**Comment by hannahkane** [comment]
We made progress this heartbeat. Closing ticket to make room for more specific next steps in 2016.
