### ISSUE TITLE
Ongoing Gear Store marketing campaign work

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#622]
Tickets are being tracked here: https://github.com/MozillaFoundation/2015-fundraising/labels/Gear%20store

@HPaulJohnson, @KevZawacki, @natalieworth, @valianttry and @edrushka (peripherally) are involved in this work. I seem to be driving (but am on PTO Nov 1-18 except for Mozfest). :)

Dropdead for this campaign is Nov 20.

**Comment by ldecoursy** [comment]
Redundant with another ticket.

**Comment by HPaulJohnson** [comment]
being tracked here: https://github.com/MozillaFoundation/plan/issues/579#issuecomment-157920147
