### ISSUE TITLE
Ship a draft H1 roadmap for Leadership and Advocacy

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#626]
* Decision-Maker: Matt
* Accountable: Sara (Advocacy) + @ldecoursy (Leadership)
* Responsible: DARCIs for Leadership + Advocacy

**Comment by OpenMatt** [comment]
Next step: Matt will start a spreadsheet template and some next steps w. Sara + Lainie

**Comment by ldecoursy** [comment]
@OpenMatt Can we consider draft shipped and close this ticket?

**Comment by OpenMatt** [comment]
digging into this together in Mozlando

**Comment by cassiemc** [comment]
DONE!

**Comment by hannahkane** [comment]
Roadmappy spreadsheet: https://docs.google.com/document/d/1xhEH2cyz7jkSNnemZwgPCstWQ9yqpeHOtDY43E6yQoI/edit#heading=h.l3h1d3f1oh7i

**Comment by brettgaylor** [comment]
Business plan
https://docs.google.com/document/d/1OipsGu8eWuTaT8J3T2-0CR3zB79SysATBLiTTBDGS5I/edit
