### ISSUE TITLE
Open call for 2016 fellows on advocacy.mozilla.org

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/plan#629]
We will need to adjust the advocacy.mozilla.org page for the 2016 cohort.  This will mean:

* Adjust the front page by adding an "apply" button, while keeping the "meet the 2015 cohort" as is
* Changing the 2015 "apply to be a fellow" page with new copy

**Comment by OpenMatt** [comment]
@simonwex can you assign a dev to do this before Dec 18? no design required.

**Comment by OpenMatt** [comment]
* @simonwex and @hannahkane say @mmmavis may be able to do this

**Comment by mmmavis** [comment]
@brettgaylor yup yup I can update the site after Mozlando.  Do you mind adding the new copy in [this ticket on advocacy.mozilla.org repo](https://github.com/mozilla/advocacy.mozilla.org/issues/32) instead? :bowtie:

**Comment by cassiemc** [comment]
Replacing with #641

**Comment by mmmavis** [comment]
Hey @brettgaylor ! :smile: 

Just wanted to see if updates mentioned in the this ticket are still needed. Or we want to hold off until we figure out what the plan is for https://github.com/MozillaFoundation/plan/issues/641.

**Comment by Melechuga** [comment]
Hi @mmmavis!  I think we've replaced this ticket with #641. We're meeting early in the new year to figure out wireframes and such, then will bring everyone in as needed.

Thanks for staying on top of it!

**Comment by mmmavis** [comment]
:tada:
