### ISSUE TITLE
APP: Improve Webmaker mobile app templates

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#63]
Improve templates for mobile application as per feedback from field research and latest bricks (data, image, phone, etc). Goal is to improve the FTU experience for new users.

Phase: Design / Build / Ship
Owner: @k88hudson
Decision: @thisandagain
Consulted: @LauraReynal 
Lead design: @vazquez 
Lead dev: n/a
Quality: @cassiemc 

*Edit by @k88hudson:*
Tickets here: https://github.com/mozilla/webmaker-app/milestones/Improve%20templates

**Comment by k88hudson** [comment]
I'm going to start triaging for this

**Comment by thisandagain** [comment]
Thanks @k88hudson. We should have a designer assigned by EOD via @cassiemc and should be able to schedule a kickoff for tomorrow. I'll send along an email once we have the team finalized. In the meantime, can you start to put together a milestone with details on the scope of work for this?

**Comment by k88hudson** [comment]
@thisandagain yep

**Comment by cassiemc** [comment]
Assigned @vazquez for design.

**Comment by k88hudson** [comment]
@cassiemc thanks!

**Comment by thisandagain** [comment]
We got through all of these issues minus the final design review. Moving review to the UX sprint. Go @vazquez go! :smile:
