### ISSUE TITLE
Copy updates to Gigabit site

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#632]
@hannahkane will update

**Comment by hannahkane** [comment]
@mmmavis filed a PR for this today: https://github.com/mozilla/bedrock/pull/3667

**Comment by hannahkane** [comment]
Moving to next heartbeat to close out.

**Comment by OpenMatt** [comment]
event happening at Whitehouse Jan 26

**Comment by OpenMatt** [comment]
@KevZawacki ^ just an fyi

**Comment by hannahkane** [comment]
This is done.
