### ISSUE TITLE
How can we be greener & more socially responsible?

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#633]
Fewer plane tickets? Fewer printed assets (or soy ink, recycled paper)? Ideas, please!
@edrushka @davidascher @thornet @LauraReynal @secretrobotron and others, very welcome

**Comment by cassiemc** [comment]
Other ideas: 
* create a green team
* look at WWF recommendations
* can we collect data on what our effect actually is
* does Moco have anything like this?

**Comment by secretrobotron** [comment]
cc @secretrobotron

I'm a "member" of Living Planet at Work (from WWF) in Toronto. Would love to make that much huger.

**Comment by secretrobotron** [comment]
Find people in WPR, event planning, etc. who can be allies.

**Comment by edrushka** [comment]
Creating a working group.
Collecting data on our impact (likely candidates will be travel, offices, data-centers)
Deciding where we can have impact. Won't necessarily be there ^

**Comment by cassiemc** [comment]
^^ + events to @edrushka's comment

**Comment by secretrobotron** [comment]
:heart:  the "giving back" aspect (not the same as being green)

**Comment by secretrobotron** [comment]
want to have impact (vs. reception).

**Comment by cassiemc** [comment]
cc @adamlofting @xmatthewx @HPaulJohnson

**Comment by edrushka** [comment]
Giving Back opportunities could include dedicated time to volunteer in the All Hands communities (e.g. field trip to walk dogs at an animal shelter. This could be linked to Ministry of Fun. Obviously would require serious coordination ahead of time).

**Comment by edrushka** [comment]
I volunteer to convene a team to work on this for London. Please edit this comment (use the little pencil in the upper right corner) to add your name to the "interested" list. Stage One will be discussion and brainstorming - you are not committing your time in London by participating in this.

### I am interested:
- ErikaD
- Cassie

**Comment by xmatthewx** [comment]
I can craft a message to Ops regarding socially responsible piggy banks for our funds and retirement benefits. :pig:

**Comment by jgmac1106** [comment]
@thornet did a post on making efforts to #teachtheweb greener. For example could we encourage smaller page and image sizes (less bandwidth=less download=less charging).

Maybe a curriculum kit on greening the web.

**Comment by brettgaylor** [comment]
Perhaps bring in outside consultant who can help with measurement and planning?  Working group is awesome but taking it seriously will require day to day.
Very good friend here: http://www.naturalstep.ca/sarah-brooks

@xmatthewx in our Canadian retirement funds, there are options for ethical investments.  Might want to look at 401k equivalents?

**Comment by bhuvanshri** [comment]
* Measuring our carbon footprint as an organization (office space, travel / commute, events)
* Coming up with recommendations on how to reduce it across various "sinks" mentioned above
* Informing ourselves of industry standards (their must be more out there - like LEED certification for office spaces)

London could be good way of establishing baseline w.r.t events specifically.

**Comment by adamlofting** [comment]
Some good context setting here:
* http://wwf.panda.org/what_we_do/how_we_work/businesses/

And I'd love to show up on the right side of this issue:
* http://www.greenpeace.org/international/en/publications/reports/How-dirty-is-your-data/

**Comment by omnignorant** [comment]
Just want to chime in with support! But also some rambling thoughts ;) 

I agree we need a more professional approach to this. With an organization this utterly complex, even just the MoFo side of the house, the contributing factors are very difficult to identify and assess. 

For example, how does our work-from-home culture counteract our flights? Or the energy savings on light and heat? Do I count my personal home use? What about our water usage? When I drink from my tap at home, am I improving our water use profile? 

Just noting that there are multiple vectors here, and then there are a number of strategies along each vector. For example, given the above, would a home-improvement benefit like health and wellness do more than flight resrtictions?

Re flights: I've always wanted to do the math problem of calculating the optimal location to have our all-hands, which would minimize the aggregate, joint cost and flight miles across the org. Fingers crossed that's in the South Pacific or the Caribbean, but it's probably Cleveland ;)

**Comment by gvn** [comment]
I'd love to see us do a campaign around e-waste reduction. :+1: 

PS: AFAIK the Magic Band is a good (bad?) example of an electronic product meant for single usage and subsequent disposal. The battery is designed to be non replaceable. I might have missed it, but I don't think there was a way to opt out of getting one in your welcome package. This is the kind of thing we can do to be "greener"!

**Comment by stephwright** [comment]
You can actually use the Magic Band on return trips to Disney World.  When I bought extra tix for my family, they did not get Magic Bands, they came as plastic cards.  I did end up buying the bands though because for the kids it was easier to not get lost, though I do intend to keep them and use them again in the future... Not that this negates what you are saying about e-waste reduction.  I would definitely prefer the battery be replaceable.

**Comment by edrushka** [comment]
An interesting article on this topic was posted in the Atlantic yesterday: [The Environmental Impact of a Netflix Binge] (http://www.theatlantic.com/technology/archive/2015/12/there-are-no-clean-clouds/420744/). 

This quote is particularly compelling to me:
> While it might be a little hyperbolic to declare the Internet as civilization’s greatest achievement (I’m personally a fan of vaccinations), there’s no shortage of VCs and CEOs who believe and evangelize that position. But embracing such a grandiose statement about the network also means taking a radical responsibility for it and recognizing that how we build the future frankly determines whether we have a future at all.

**Comment by metaphorista** [comment]
COUNT ME IN!
Could we create a carbon dashboard?
Love the idea of doing/making something as our all hands celebrations, rather than just consuming food/booze/toxin spewing fireworks

**Comment by stephwright** [comment]
:heart: :heartbeat: the idea of carbon dashboard!  We could all put in carbon offsetting points to offset the carbon of the whole event!

**Comment by edrushka** [comment]
We're meeting Monday December 21 to kick off this conversation and brainstorm some ideas both for the London All Hands and for longer-term implementation. Everyone is welcome, or feel free to jot some notes in this pad: https://public.etherpad-mozilla.org/p/social_enivro_reponsibility

Erika D's Vidyo
9:00am PT  12:00pm ET  5:00pm GMT

**Comment by edrushka** [comment]
Update: We met this morning and started brainstorming some ideas for London and beyond. [Notes here] (https://public.etherpad-mozilla.org/p/social_enivro_reponsibility)
Next, we'll reach out to MoFos with a survey #655 and connect with Brianna about how we can help in London.
