### ISSUE TITLE
[Jan 22] Chicago Buzz schedule app

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#634]
Hive Chicago would like to use the Schedule app at their annual conference on Jan 22nd. 

It'd be great for us to deploy another iteration with incremental improvements. Both SourceCon and Mozfest would benefit. I'd be glad to help facilitate that effort if @ryanpitts, @mmmavis, or another engineer can contribute. cc @simonwex 

**Question**: How much engineering time did the Mozfest fork require?

We might also like to test a new feature that extends engagement as discussed in Orlando. It's just two solid weeks, so the scope would need to be small. Could be blocked by other `p1` tasks in the queue. cc @davidascher

### RACI

Driver: @edrushka
Consulted: @omnignorant, @xmatthewx 
Developer: @ScottDowne 
Designer: @vazquez

**Comment by ryanpitts** [comment]
Getting the app ready for MozFest was a decent chunk of my time for a few days to a week, plus the bugfixes and updates during MozFest itself. Not sure how much time @mmmavis invested, but I'd guess it was more than that. But we're in a good starting place to keep working now that there are multiple people more familiar with the code.

My January is looking pretty stacked with Python work, so I wouldn't count on me for any kind of primary dev work. If there was a specific date where I could set aside some time to help out, that could work.

**Comment by davidascher** [comment]
It'd be good to get someone who has never worked on the schedule app to try
a deployment on heroku to document the hurdles to deployment, and file bugs
on those.  That will help make it easier to work on by anyone, not just the
'founders' ;-).

That 'trial deploy' is a thing that I could imagine volunteers might be
particularly well suited for as they are less likely to know 'secret'
things.

**Comment by omnignorant** [comment]
Hmmm, I might be able to solicit some local volunteers to help us deploy this if it's a) well documented and b) simple enough python code. There are a ton of folks from my Chi Hack Night crew who don't have anything to do for the next two weeks.

I wanted to provide a couple more specs on the event so that we get a clearer sense of scale/complexity. Perhaps there is a way to simplify things?

* 100-200 attendees;
* all sessions in a single bldg, on a single floor;
* four types of sessions: plenaries, 45 and 90 min workshops, 4 hour working groups;
* 7 tracks/categories/labels/tags/etc. to sort sessions;
* 2 day event

**Comment by xmatthewx** [comment]
@omnignorant - let us know if you're able to wrangle a developer to drive this. I'm glad to provide support, but we won't be able to lead this internally.

**Comment by omnignorant** [comment]
@xmatthewx just to be clear: if I can't ID a volunteer to do this, then it's not happening? In which case, where is the shed app repo? Is there any documentation? I can see what I can do.

Also FYI @Saallen

**Comment by mmmavis** [comment]
It took me a while to migrate session data between Google Spreadsheet and Github.  Tweaking the Schedule app itself was pretty straightforward and did not occupy much of my time compared to the data migration part.

Agree that it'd be nice to get someone who has never worked on the Schedule app to fork it and file tickets along the way.  One thing to mention is that the [loader script](https://github.com/mozilla/mozfest-schedule-loader) that @ryanpitts wrote is in Python.  So maybe finding a dev with some Python knowledge would be ideal (so we don't have to ping Ryan every time a change needs to be made :smile:).

**Comment by omnignorant** [comment]
Thanks for the clarifiacation @mmmavis and also want to note that we're definitely not curating anything in GitHub. We'd going straight to Google Sheets through a Form, so that might simplify things.

**Comment by Saallen** [comment]
Hey- if we are happy for community to hack on this I might have someone in mind if @omnignorant cannot mind anyone local to him

**Comment by omnignorant** [comment]
Cool... we can work on finding a local contributor. So um, where's the code live?

**Comment by xmatthewx** [comment]
Thanks everyone. 

Mozfest: https://github.com/mozilla/mozfest-schedule-app
SRCCON: https://github.com/OpenNews/srccon-schedule

**Comment by mmmavis** [comment]
and https://github.com/mozilla/mozfest-schedule-loader to pull data from Google Spreadsheet and feed it to the Schedule app.

**Comment by edrushka** [comment]
Picking this up again. I'm happy to drive this if I can get a technical lead to help me. @simonwex any devs available in the next 2 weeks?

**Comment by omnignorant** [comment]
FYI, this is the session data we've got in the can: https://docs.google.com/a/mozilla.com/spreadsheets/d/14q_MfxaUVDZ19YfNWf6fGMkHj8P7q7u0zM9tBX3XHFU/edit?usp=sharing

More to come from the still-live form.

**Comment by OpenMatt** [comment]
@mmmavis says this may need a design treatment first
* event is Jan 23 -- so may be too rushed
@edrushka will update here w. an alternate proposal

**Comment by edrushka** [comment]
@omnignorant - without a design treatment it would be MozFest branded. Have you considered Sched? @Saallen and I looked into this for MozFest (and it's used for our coincidental workweeks).

**Comment by xmatthewx** [comment]
Design shouldn't be a blocker. It is minimal. I can swap the logo and adjust the styles. But, without a committed engineer to lead this, the timeline is very tight.

**Comment by edrushka** [comment]
@simonwex - any dev availability?

**Comment by cassiemc** [comment]
I talked to @vazquez yesterday and he is also available to advise on UI.

**Comment by edrushka** [comment]
@davidascher - is there any dev availability for this?

**Comment by davidascher** [comment]
@simonwex can answer this, not me.

**Comment by simonwex** [comment]
In transit right now, will figure this one out this eve

**Comment by simonwex** [comment]
Between PTO and other projects, there is no one available to do this. @edrushka, @omnignorant, it's flagged as a P2, is that appropriate?

The bug also hints at new features, but isn't clear about the requirements. What's the basic task here to provide a schedule app for next week? If it's just about deploying it, I can make it happen.

**Comment by ScottDowne** [comment]
Talked to Wex, and I think the timing for the advocacy changes might mean I can fit this in from now until Friday.

**Comment by xmatthewx** [comment]
Great. Thanks @ScottDowne.

### Proposal

Schedule a meeting with @ScottDowne @omnignorant and @edrushka or me.

Determine if we can:
 1. Provide an app that serves the event well ...AND...
 1. Use this as an opportunity to make incremental improvements to the app and how we deploy it. 

If we can't answer YES to both, then we should probably skip this and apply our energy elsewhere.

**Comment by ScottDowne** [comment]
@xmatthewx works for me.

I'll start by setting everything up to get a feel for it, while we figure out the specifics for what I'll be doing :D

**Comment by edrushka** [comment]
@ScottDowne Thanks for volunteering!!  I booked a call for us tomorrow to discuss.

**Comment by vazquez** [comment]
@edrushka Can you add me to the call tomorrow? There might be the need for design tweaks.

**Comment by edrushka** [comment]
@vazquez absolutely!

**Comment by edrushka** [comment]
Update: I've assembled a crack team including @omnignorant @vazquez @ScottDowne and @xmatthewx to work on this :zap: :zap: :zap:

#### Goals:
- stand up a version for Hive Chicago Buzz
- optimize the app for future events (e.g. explore who could set up a theme directory. Chicago Hive content, styles, configurations (incl spaces or tracks?) would be added there.)
- continue collecting prototyping and test ideas for how to deepen participant engagement through the app (hopefully to be applied for our next big event cc @ryanpitts)

**Comment by omnignorant** [comment]
@edrushka thanks for loading the bases, now let's hit a grand slam! (oh, man, I'm really not comfortable with sports analogies).

**Comment by xmatthewx** [comment]
Extending to the next milestone. Reassigning to @edrushka's capable hands.

**Comment by edrushka** [comment]
The schedule worked beautifully! Thanks so much :sparkling_heart::sparkling_heart:@ScottDowne and @mmmavis :sparkling_heart::sparkling_heart: I'll write specific feedback and suggestions for next iteration during the next heartbeat.

**Comment by omnignorant** [comment]
Thanks to everyone who worked on this. It was one of those rare pieces of work that does exactly what it needs to do. no more, no less, no fuss.

**Comment by ryanpitts** [comment]
> no more, no less, no fuss

:raised_hands: :fireworks:
