### ISSUE TITLE
Design templates for "Guides"-style learning content

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#636]
We've refined our [templates for Teaching Kit-style content](https://github.com/mozilla/teach.mozilla.org/issues/1360), but we have other content types that still need to be addressed including the Clubs Guides and the 101 Guides from MSL.

Wondering if we can provide a shared template that can be slightly modified for different audiences/sub-brands.

### DARCI
D: @hannahkane
A: @cassiemc 
R: TBD
C: @amirad @zee-moz @stephwright
I: @chrislarry33 @kaythaney

**Comment by kaythaney** [comment]
thanks, @hannahkane ! don't think steph and zannah are part of this group, but their handles are @zee-moz and @stephwright

**Comment by amirad** [comment]
Oh my goodness. Yes yes. Can that be adapted for a quick Clubs Guide? cc: @soapdog

Here are some examples of what we do know but we have soooo many google docs that we want to quickly through into github pages for community to use. 
https://docs.google.com/document/d/1lKjPm-k3GGtz66Lor_kRpX68HNaPj-T47tmZ540WY_w/edit
Branding guide - http://mozilla.github.io/mozilla-club-guides/branding-guidelines/
Your first month as a Club Captain - http://soapdog.github.io/your-first-month-as-a-club-captain-guide/ 
Afterschool program - https://docs.google.com/document/d/1rUivWQybJymNlfZZHWkSJqFN5TNDVuPRSH_YCObALeM/edit
Community Meet-Up - https://docs.google.com/document/d/1gzbC5Q_XeHeii66v_Z4py6QrqYin5j1ozNhdeKJ-Ssg/edit
Neighborhood with low connectivity - https://docs.google.com/document/d/18DwRtmttN_EUlp1PUsQJWrDgUwMpCf5ipKG-TGfN1Rc/edit
PR guide https://docs.google.com/document/d/1bqpO6uZ6o1l4DftqvFdV97j1eyhE6fbOKUnp16rcteU/edit 
Social Media guide https://docs.google.com/document/d/1UIukayevaotjBNtn_sRO3ozPPvlrghFs6mGbHjhTCs0/edit

**Comment by soapdog** [comment]
Hey folks,

Loving the threads and new templates! Want to adapt them to our work as soon as possible. We may need to rework a lot of our content to fit it but I believe it is worth it.

As for the guides, we do have some of them in non-gdoc format as well, all using the same template as http://soapdog.github.io/your-first-month-as-a-club-captain-guide/ which I am reworking after reading a great book on web typography. I would love to have "real designer" eyes look into the new guides template soon.

**Comment by cassiemc** [comment]
@hannahkane Do you have an idea of when this work should be completed?

**Comment by hannahkane** [comment]
I don't think this is urgent, given the many other design priorities. Can we consider it a P2 in an upcoming heartbeat?

**Comment by cassiemc** [comment]
Sounds like a plan.

**Comment by hannahkane** [comment]
Is this essentially what @flukeout and @acabunoc have been working on this heartbeat? See http://flukeout.github.io/science-template/

Possible to adapt same templates to Club guides?

cc @amirad

**Comment by cassiemc** [comment]
Quite likely. Between those templates and the other teaching kits, feeling like something will work for this. Are there requirements about whether or not these need to live on github or otherwise? ie. how often will they be remixed, and what is the git skill level of those doing the remixing (likely different from the MSL audience as onboarding to Git is an intentional part of their onboarding.) Also, is there a single document that would serve as a good place to start?

**Comment by hannahkane** [comment]
I think github pages would be good. It will be mostly staff editing.

@amirad linked to several docs above. Maybe the social media guide would be a good, representative one to start with: https://docs.google.com/document/d/1UIukayevaotjBNtn_sRO3ozPPvlrghFs6mGbHjhTCs0/edit

**Comment by cassiemc** [comment]
@hannahkane It'd make sense to keep @flukeout looking at all these materials. Does that work for you guys?

**Comment by hannahkane** [comment]
WFM!

**Comment by amirad** [comment]
I do like those science templates and am totally open for something in that realm. Git-level with vary within our team but github is the best option IMO. Some guides we will rarely edit, unless to add links or other info, and some guides I edit on monthly basis. 

@hannahkane I didn't know if it was easier so I pulled out guides and resources into this doc: https://docs.google.com/document/d/1qLwEJZXF6Dz1wZ71AIC8t8n1LHPC6n99kZdFTuvB-LQ/edit

**Comment by hannahkane** [comment]
Met with @flukeout and @amirad today. Filed tickets: https://github.com/mozilla/learning-networks/issues/332 and https://github.com/mozilla/learning-networks/issues/333

**Comment by hannahkane** [comment]
Going to close this out, and sync this project up with the CMS project here: https://github.com/mozilla/mofo-cms-experiment/issues/21
