### ISSUE TITLE
Prepare research phase for Curriculum Database

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#637]
See [Project Brief](https://docs.google.com/document/d/1f5AYLbenXmzTCg2mkvABjeUHAFXyhC2l1evC0wEpybg/edit#)

Research might include:
 - [ ] Interviews
 - [ ] Focus Group

### DARCI ###
Driver: @hannahkane 
A: @davidascher ?
R: @hannahkane, @flukeout ? @sabrinang ?
C: @LauraReynal @secretrobotron @cassiemc 
I: @chrislarry33 @chadsansing

**Comment by hannahkane** [comment]
Perhaps some of this research could happen at Chicago Hive Buzz

**Comment by hannahkane** [comment]
Have made progress on this. See https://github.com/mozilla/teach.mozilla.org/issues/1522 and https://github.com/mozilla/teach.mozilla.org/issues/1523. Stretch goal is to complete the interviews/observations within this heartbeat.

**Comment by OpenMatt** [comment]
I'd love to track this work...

**Comment by flukeout** [comment]
@OpenMatt Let me know what you need to know/have access to to track it.

**Comment by hannahkane** [comment]
Actually, since this ticket is about preparing the research, I'm going to say we've done it. Research is in progress. Tickets for next steps to come.
