### ISSUE TITLE
Gigabit site redesign

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#638]
In addition to [urgent copy changes](#632), the Gigabit site could also use a visual refresh.

@sabrinang started this work [here](https://github.com/mozilla/teach.mozilla.org/issues/1473).

### DARCI
Driver: @hannahkane
A: @cassiemc 
R: @sabrinang 
C: @LindseyFrost 
I: @chrislarry33 @HPaulJohnson

**Comment by cassiemc** [comment]
@hannahkane Would love to talk to you about timelines and the potential for doing #643 first?

**Comment by hannahkane** [comment]
Definitely seems smart to do #643 first. +1

**Comment by cassiemc** [comment]
Good to keep this with @sabrinang since she has started the work.

**Comment by LindseyFrost** [comment]
@cassiemc @sabrinang We'd really love to be guinea pigs in consolidating and finding shared needs! We really don't have capacity to maintain individual city sites (hive KC, hive CHA, new cities coming online next year) and would love to build out a new, better site that meets project and city-level needs in one place.

**Comment by cassiemc** [comment]
@LindseyFrost Excellent, thanks for that bit of background! We'll try to kick this off in the new year.

**Comment by hannahkane** [comment]
Closing this as it's become obsolete in light of the new bootstrap theme + process @cassiemc is working on to retro-fit said theme to existing web properties.
