### ISSUE TITLE
Technical spike on technology for Clubs Portal

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#640]
(See [definition of spike](http://agiledictionary.com/209/spike/))

Goal is to evaluate Reps Portal to determine if it can be adapted to meet the needs of Clubs Reporting.

**Comment by hannahkane** [comment]
After conversation with @amirad, @carotejada, @mmmavis and @sabrinang, we've defined many of the requirements for the Clubs Portal. 

### Requirements ###
 * localizable
 * some content needs to be updated by staff members regularly—i.e. links to new resources
 * granular permissions  
 * allows for the following features:
  * interactive map of existing Clubs
  * Club profiles (individual pages maintained by Club Captains)
  * Facilitate communication between CCs, RCs, and staff (for now, let's consider this forum integration, though specific needs are likely to emerge over time)
  * Event reports, submitted by Club Captains, and associated with Club profiles

**Comment by hannahkane** [comment]
@simonwex - is the above content enough information for a developer to begin evaluating the Reps Portal as a possible solution to the Clubs Portal?

**Comment by hannahkane** [comment]
I don't think it was realistic to put this AND the CMS work in the same heartbeat. Will move this to the next one, but, @simonwex, hoping we can prioritize this.

**Comment by simonwex** [comment]
I think the requirements listed above are enough to do the investigation. This feels like one day of work to me. This is how I'd imagine it going:

1. Understand the requirements, investigate additional details where needed
2. Organize a call with Pierros and/or Tasos on the participation team (organize through Pierros) to discuss details and get pointers on the reps codebase
3. Do extra homework to synthesize that meeting for discussion on the Monday mofo-eng call.

I'd like @pomax to have a look at this.

**Comment by hannahkane** [comment]
@Pomax - assigning this to you, if that's alright. Let's talk on Monday so I can brief you on this work. @simonwex - want to be there?

**Comment by Carotejada** [comment]
![tumblr_m3ppvemgu71r4lux2](https://cloud.githubusercontent.com/assets/14875631/12721144/3f564062-c8cc-11e5-9eaa-de1578ba8a62.gif)

**Comment by hannahkane** [comment]
Changing to P2 in order to:
 * respect a reasonable P1 limit
 * reflect reality (this is unlikely to get done at this point in the heartbeat)
 * acknowledge that this project is in flux in terms of scope (i.e. need to understand if we're forking or expanding the portal, and whether we should just add Clubs or also other local groups)

cc @chrislarry33 @davidascher @ldecoursy

**Comment by hannahkane** [comment]
Officially moving this out of the milestone.

**Comment by hannahkane** [comment]
Closing this since this is part of @davidascher's overarching innovation strategy work..
