### ISSUE TITLE
[Jan 29] Design/Build Open Web Fellows landing site

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#641]
### Roles
 * Driver: @cassiemc
 * Decision Maker: @brettgaylor @Melechuga
 * Design Lead: @kristinashu 
 * Development Lead: @ScottDowne 

**Granular issues listed here:** 
https://github.com/MozillaFoundation/movement-building/labels/webfellows

---------------

The Open Web Fellows section needs to move off of advocacy.m.o, set up a new site (a lá https://www.mozilla.org/en-US/gigabit/), and link to the candidate application. This will be the preferred landing page for the program until the Leadership team as a whole comes to consensus on the website experience for visitors.

### Audience
Host organizations (years 1 & 2), current fellows, prospective fellows (through the application process), and others interested in the program.

### Success
Success is having a new Open Web Fellows landing page that is easy to edit and add to as the program grows. For this particular heartbeat, it would mean having a site up with the narrative, a link to the application, a link to benefits information, and a link to current fellows' narrative.

### Vision
Skin https://www.mozilla.org/en-US/gigabit/

### Measurement
Having a working website.

**Comment by hannahkane** [comment]
Hey @Melechuga - wanted to draw your attention to plans to redesign the Gigabit page. Check out https://github.com/mozilla/teach.mozilla.org/issues/1473, and be sure to click the redpen link. Does that redesign align with your vision for the Fellows site?

**Comment by Melechuga** [comment]
Yes! The general design will work nicely for what we need. I'm assuming there's room for more/other pages, color changes, etc? Thanks!

**Comment by Melechuga** [comment]
Perhaps the bigger issue is changing the URL to something like mozilla.o/openwebfellows, and changing up the advocacy.m.o site. Who would I speak to about that?

**Comment by hannahkane** [comment]
cc @simonwex for URL issue and heads up @cassiemc regarding similar design needs—perhaps we can streamline (though, yes, the designs don't have to be identical in terms of content, color, etc.)

**Comment by cassiemc** [comment]
I suspect this is a good design exercise for creating a generic 'initiatives' page that accounts for many projects that will be nested under the MLN site. I'm curious first if that actually makes sense, and second how that might fit into the new IA plans, @hannahkane, ie. if we look across all the initiatives, what are the common design needs. And do we really need an interim step in setting up bespoke websites or pages before we go through that somewhat larger initiative? I'm actually going to file this as a new issue. #643

@Melechuga are there any external deadlines that are prompting this work to happen now? The need and use cases are clear to me, just trying to understand timelines now.

**Comment by hannahkane** [comment]
@cassiemc - I'm going to answer your question on #643, so that this ticket stays specifically about OWF.

**Comment by cassiemc** [comment]
The open call will be posted on [...] 
(@brettgaylor)

**Comment by cassiemc** [comment]
This is still a big question mark about who to assign and the scope of work. I'd suggest @brettgaylor, @Melechuga and I have a catch-up very early in the new year and draft a rough wireframe. I'll schedule!

**Comment by cassiemc** [comment]
Meeting scheduled for Jan 4. Also included @simonwex for dev resourcing, and @kristinashu for design input.

**Comment by simonwex** [comment]
@ScottDowne will be taking this one.

**Comment by cassiemc** [comment]
I'm driving this update. We had a kickoff yesterday, notes here: https://public.etherpad-mozilla.org/p/webfellowsupdate I'll be filing followup issues under the ```webfellows``` label here: https://github.com/MozillaFoundation/movement-building/labels/webfellows

**Comment by cassiemc** [comment]
We've made good progress on this front this heartbeat, and are planning to add the advocacy.mozilla.org homepage to this scope. The plan is to finalize the designs for open web fellows next week. Any structure to the site will be finalized by early next week so @ScottDowne can begin building. Redpens by @kristinashu so far are here: https://redpen.io/p/wt1d64bfb93fa6a6b8

**Comment by cassiemc** [comment]
Designs are complete, dev should be underway. On track!

**Comment by Melechuga** [comment]
@cassiemc @kristinashu @ScottDowne There was a question in the redpen design about linking a blog somewhere, but I can't find the comment any more. All the links are in the googledoc (https://docs.google.com/document/d/1WRLUoMaoWvG1z_ASsQ0_WJ7NYj8E2W0Aqc6dHpZlM1U/edit) I see some wording differences between the doc and redpen design (for example, it says "stipend" instead of "grant" under Financial Terms; please use the text in the Gdoc. Thank you!

**Comment by cassiemc** [comment]
@Melechuga Let's do a thorough content review once @ScottDowne has the staging site up and file any new issues in the [movement-building](https://github.com/MozillaFoundation/movement-building/labels/webfellows) repo. I think the blog issue you're thinking of is this: https://github.com/MozillaFoundation/movement-building/issues/75

**Comment by cassiemc** [comment]
This has launched, great job team! advocacy.mozilla.org
