### ISSUE TITLE
Set up infrastructure to Localize Teach site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#642]
The content has stabilized, so we're likely in a position where we can begin asking volunteers to localize the static content. 

Note: this is distinct from the curriculum localization effort.

### DARCI
D: ?
A: @simonwex 
R: ?
C: @alicoding @soapdog
I:

**Comment by cassiemc** [comment]
@simonwex to update with dev resource

**Comment by hannahkane** [comment]
@simonwex - do we have anyone who can start working on this in this heartbeat or an upcoming one?

**Comment by hannahkane** [comment]
This is not happening this heartbeat, so moving to the next. Conversation scheduled to talk about resourcing upcoming MLN engineering needs, including this one.

**Comment by hannahkane** [comment]
Removing this from any milestone; pending conversation about engineering resources

**Comment by hannahkane** [comment]
@simonwex - any thoughts about whether to put this into an upcoming milestone or close?

**Comment by hannahkane** [comment]
Putting this in April 8 so that it's not milestone-less.

**Comment by hannahkane** [comment]
Closing this because it's not on the immediate roadmap. Will revive when we're closer to doing the work.
