### ISSUE TITLE
Draft a branding / templatization plan

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#644]
It's clear that there are lots of shared design and engineering needs across initiatives. We need a plan for doing this systematically, which should help us move faster and more efficiently, and better use contractors or other contributors to fill in resource gaps.

I'll volunteer to take point on starting a draft of the plan before the holidays, but will need help!

cc @davidascher @simonwex @hannahkane and many more others to come.

**Comment by cassiemc** [comment]
cc @HPaulJohnson This is something the Comms Council could help enormously with.

**Comment by cassiemc** [comment]
Moving this to the first heartbeat of the year, as it's difficult to convene a group of brains before then. I'll start a doc though, here: https://docs.google.com/document/d/1lBQuH__Q_2Dkb0Lbn2WQ4SB7w1HUEzuJ-V1nVDaDpL4/edit

**Comment by cassiemc** [comment]
Meeting scheduled for Jan 6

**Comment by cassiemc** [comment]
I'd like a better name for this plan. 'Templatization and branding' seem to encapsulate sub-parts of this plan, but not the macro vision. And I'd like to remove the 'branding' from the name, since it's a bit loaded. 

Ideas that come to mind are...
* cleaning house
* telling our story
* synthesis, structure & tooling

These all kind of suck. :)

@OpenMatt @davidascher @hannahkane @HPaulJohnson @chrislarry33 @xmatthewx Do you guys have any ideas?

**Comment by cassiemc** [comment]
Settling on the ```betterfaster``` label for now until I hear any better ideas.

**Comment by hannahkane** [comment]
I'm not 100% clear on the business reason for linking all of these pieces together, so I don't have a good naming suggestion. (I do think they are all things that make us "betterfaster," though, so that works for me.)

Once all of the different pieces are ticketed, I'm not sure I understand the value of keeping this parent ticket open. It doesn't feel like a single project that needs to be driven by a single person. Rather it feels like a collection of several projects, owned by different people, that will be completed on different timelines.

**Comment by cassiemc** [comment]
My rationale for looking at these things holistically is a design one – we can design better solutions if we understand all the different needs upfront and design deliberately where there are connections and overlaps. Business/team-wise, the objectives are, I believe, 3-fold:

1. Streamline our presence online through variables like URLs, branding and frontend styling so that our programs and offerings reflect our new strategy.
2. Streamline the number of design / content / dev types (perhaps by reducing the number of platforms or design templates), so that they are easier and faster to update and manage independently
3. Present ourselves in a way that is true to our strategy, and that make sense externally. This one has to do with addressing our known issue of brand soup, which dilutes the impact we could have with a better designed brand architecture and implementation.

Sounds good to me to treat this as a collective goal, collectively owned. I agree, it probably needs to be! The plan is to close this ticket once the "plan" generally makes sense and then [use that label](https://github.com/MozillaFoundation/plan/labels/betterfaster) to track the meta objective.

All good thoughts and questions @hannahkane.

**Comment by hannahkane** [comment]
All makes sense to me. Thanks for explaining.

**Comment by cassiemc** [comment]
I've met with quite a few stakeholders to round out the Better Faster plan, noting issues that are happening or that need to happen across lots of different projects. Some excellent work has emerged from these conversations already, such as filling out the Comms inventory, exploring tech solutions, and moving quite rapidly on this front on MLN initiatives. We've even got @acabunoc looking ahead with us to help make this a part of their RFP for redesigning the Science site. :boom: 

It's worth noting the objectives from [the planning document](https://docs.google.com/document/d/1lBQuH__Q_2Dkb0Lbn2WQ4SB7w1HUEzuJ-V1nVDaDpL4/edit#) here:
#### Objectives:
* Streamline our presence online through variables like URLs, branding and frontend styling so that our programs and offerings reflect our new strategy.
* Streamline the number of design / content / dev types (perhaps by reducing the number of platforms or design templates), so that they are easier and faster to update and manage independently.
* Present ourselves in a way that is true to our strategy, and that make sense externally. This one has to do with addressing our known issue of brand soup, which dilutes the impact we could have with a better designed brand architecture and implementation.

I'll review the doc with @davidascher on Monday, but in the meantime seems like a few key strategies have emerged.

#### What's next
1. As @hannahkane mentioned above, this task is large, covers many projects and will be run by several people. A good strategy will be to encourage connections between projects (ie. what we've been doing with MLN initiative templates) and plan for opt-in – design and build so that proposed solutions work better than what we currently have, and so that people want to use them.
2. It will be useful to collect a 'council' of drivers who are aware of this issue as a whole, who could meet every other week or so – I'd suggest me (design), @simonwex (dev), @lovegushwa (advocacy), @davidascher (ops), @xmatthewx (tooling), @hannahkane (MLN), @ldecoursy (comms), @OpenMatt (PMs & advocacy). Others welcome, and I'm happy to schedule these followups.
3. I will file issues that have emerged from this process in this repo with the ```betterfaster``` label. It'll still be hard to track all the issues across repos, and there will be some repetition, so we'll need to use the above council and TPS triage calls and demos to stay aware of all these related tasks.

Going to call this issue closed. If we need something more specific we can file it.

**Comment by cassiemc** [comment]
Issues from the planning doc have been filed here: https://github.com/MozillaFoundation/plan/labels/betterfaster

If anything is missing, please file it! I'll continue to triage that list.
