### ISSUE TITLE
Encryption Campaign

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/plan#645]
Develop campaign for an educational advocacy campaign around encryption. Campaign will kickoff in early February and continue throughout February with a weekly series of content beats. 

## Full project brief + details
Is here: http://mzl.la/encryption
Repo: http://mzl.la/encryption_issues

## Roles
Project Manager: @openmatt
Responsible: @shaghdoosti
Accountable: @valianttry 
Supporting: @brettgaylor, @HPaulJohnson, @KevZawacki, Jochai (policy)
Design: @lovegushwa + @natalieworth 
Dev: TBD @simonwex 
Consulted: @davidascher, Mark S, @adamlofting 

### (Tentative) List of Deliverables: 

- Design brief and content "playbook"
- Landing page
- 4 videos
- "send an encrypted email" page
- Email series
- Social media assets (Facebook, Twitter, 1-2 channels)
- Comms plan, including PR push and blog series to accompany each content beat
- Other design assets tbd (infographic, .gif's)
- Other owned media tbd (snippet, directory tile, moz.org tile, FF&You promo)
- Wrap-up survey

**Comment by HPaulJohnson** [comment]
Flagging need for Project Manager on this campaign

**Comment by HPaulJohnson** [comment]
Working list of assets and deliverables: https://docs.google.com/spreadsheets/d/1OE_j1x3bm0vZmCJ_YoGsP8fTL5syvoHObjEJBZJXMCg/edit#gid=1677471962

**Comment by cassiemc** [comment]
Assigning @lovegushwa and @natalieworth to this work in the new year. Let me know if you need additional resources.

**Comment by OpenMatt** [comment]
This is proceeding full speed ahead, tracked here: http://mzl.la/encryption

**Comment by OpenMatt** [comment]
removing "needs dev" label, as I don't think there's any developer work needed next week

**Comment by simonwex** [comment]
@OpenMatt does ^ this statement still stand? I think you may have forgotten to actually remove the label. LMK if we're good on dev resources here.

**Comment by OpenMatt** [comment]
yep, we're good!

**Comment by OpenMatt** [comment]
* @simonwex actually, in our stand-up meeting yesterday it came up that @ScottDowne and @mmmavis might be unclear about the fact that they may need to do some work on this beginning next week. So I wanted to check in w. you. 

* Apologies if my comment above was unclear. We don't need dev resrouces for the first week of this heartbeat. But we will need them for the second week. (Jan 26 onward)

* we will have work ready by Mon or Tues (Jan 26) that will require dev resources. All of it is listed here:
https://github.com/MozillaFoundation/encryption_campaign/labels/dev

* specifically, we will need dev resources to turn those design tickets into builds. For the snippet and landing page. 

* @lovegushwa is working to have those designs ready to hand over to build by eod Monday or Tues

* @simonwex does that work?

**Comment by simonwex** [comment]
@OpenMatt ah, I thought we were good for this HB for peeps on my team. I'll need to check in with my folk to see who's got the bandwidth. Mind inviting me to the stand?

**Comment by OpenMatt** [comment]
Just talked to @simonwex -- we're all good.

**Comment by OpenMatt** [comment]
Work is pushing ahead fast and furious. Tracked here: http://mzl.la/encryption
Let's ensure we're clear on dev resources needed for next two weeks.

**Comment by OpenMatt** [comment]
note: @ScottDowne goes on PTO Feb 9
@alicoding + @alanmoo will also be pitching in

**Comment by simonwex** [comment]
@OpenMatt could you involve @alanmoo in the kickoffs next week?

**Comment by OpenMatt** [comment]
Work is ongoing. 

#### Design
Design tasks: https://github.com/MozillaFoundation/encryption_campaign/issues?q=is%3Aissue+is%3Aopen+label%3Adesign
@lovegushwa: can you provide an update on what design resources are needed this Heartbeat? e.g., @natalieworth 's time allocation, etc.?

#### Dev
Dev tasks are here: https://github.com/MozillaFoundation/encryption_campaign/labels/dev
@alanmoo is still finishing up some work on the micro-site. @simonwex we should touch base on what's required in terms of dev resources for next two weeks. We've made some changes to the campaign timeline as of yesterday, so that will impact resource planning in ways that I haven't fully understood yet.

**Comment by cassiemc** [comment]
@OpenMatt Does this still need discussion? Not sure what the outstanding questions are, other than needs-dev?

**Comment by OpenMatt** [comment]
Nope this is all good -- we are rolling.

**Comment by OpenMatt** [comment]
### Feb 26 update 
* The campaign continues into Beats 3 and 4. The main thing to flag for this upcoming heartbeat is: we could use some additional design help. 
*  In part because of the huge success in social + added attention the campaign is getting — we could really use some additional design help on social media assets in the next Heartbeat, in addition to @lovegushwa  and @natalieworth 
* I gave @cassiemc a heads-up yesterday that this request would be coming

Next step: @lovegushwa can you provide any additional details or sub-tickets here, so that we have more detail on the work that's needed?

**Comment by cassiemc** [comment]
Plans is for @sabrinang to help out here, I spoke with @hannahkane yesterday.

**Comment by lovegushwa** [comment]
@OpenMatt 

Beat 3 email (next week)
Design any necessary email assets
https://github.com/MozillaFoundation/encryption_campaign/issues/141
https://github.com/MozillaFoundation/encryption_campaign/issues/148

Beat 4 video: (next week)

Finalize all motion and typographic video elements with Brett (Natalie, Me)
https://github.com/MozillaFoundation/encryption_campaign/issues/184
https://github.com/MozillaFoundation/encryption_campaign/issues/166
https://github.com/MozillaFoundation/encryption_campaign/issues/164
https://github.com/MozillaFoundation/encryption_campaign/issues/160
https://github.com/MozillaFoundation/encryption_campaign/issues/158

Beat 4 social:
https://github.com/MozillaFoundation/encryption_campaign/issues/144

Beat 4 video landing page and video variants (these need tickets):
- create posters / all necessary image assets
- compress video for landing page AND social
- identity any new / additional CTAs 
- a little dev work updating the site

Beat 5 video:
Same as beat 4 above, need to ticket these items.

**Comment by OpenMatt** [comment]
@sabrinang thanks for helping with this! can you co-ordinate w. @lovegushwa and dig into the work he outlined above?

**Comment by sabrinang** [comment]
@OpenMatt - Sure thing, I'll reach out to @lovegushwa today and get filled in on what needs to be done.

**Comment by edrushka** [comment]
Rolling this over since the campaign has been extended at least a week.

**Comment by xmatthewx** [comment]
@lovegushwa - please let us know if you expect to borrow any MLN designer time.
