### ISSUE TITLE
Clean up labels in plan repo

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#646]
I liked what @hannahkane did to create new labels that mapped to our new strategy. Anyone want to take a half hour with me to help clean these up? 

@hannahkane @edrushka @simonwex others?

**Comment by hannahkane** [comment]
I can help!

**Comment by cassiemc** [comment]
Meeting scheduled for Jan 4 with @hannahkane, but I could do this sooner, today or tomorrow. Ping me on IRC if you find a moment Hannah! Otherwise am updating the milestone.

**Comment by edrushka** [comment]
Can I join the Jan 4 meeting?

**Comment by cassiemc** [comment]
Yes, definitely! Invite coming.

**Comment by cassiemc** [comment]
Labels have been cleaned up, with the very excellent unexpected addition of lots of unlabeled and backlogged issue triage. Final step here is to:
- [ ] document the work in this repos readme, and (me)
- [ ] send an email to all@mofo saying what we did. (@hannahkane)

**Comment by cassiemc** [comment]
@hannahkane @edrushka The readme has been updated, could you guys review when you get a chance? https://github.com/MozillaFoundation/plan/blob/master/README.md

**Comment by edrushka** [comment]
Dang, we picked a nice palette ;)

Looks great @cassiemc :+1:

**Comment by hannahkane** [comment]
Sweet. Nice job, @cassiemc. I'll work on the email now.

**Comment by hannahkane** [comment]
Email sent.
