### ISSUE TITLE
[Jan 11] - Creation of Promotional Materials for BU Study Groups

### ISSUE THREAD

**Issue by zee-moz** [MozillaFoundation/plan#648]
Flyers - 8.5 x 11
 Large Posters - 13 x 19 
 Giant Poster - Working on - but huge. 
 BU BUS - 17.5 x 11.125
Possible nice visual email template, if it’s workable? 

Due 1/11/2016, will need review with BU community lead.  

Design brief is here:
https://docs.google.com/a/mozilla.com/document/d/1dIkUnp-0neJ12JTDAXh0bdsMWTpZ39CrofRvAaLQVlI/edit?usp=sharing

**Comment by cassiemc** [comment]
Actual due date is Jan 11.

**Comment by cassiemc** [comment]
I will update this afternoon.

**Comment by OpenMatt** [comment]
@vazquez any status update on this one?

**Comment by vazquez** [comment]
We are 90% done. I'm making small tweaks to the colour output at this point. I will be able to deliver the posters to Zannah and Tom from Boston University by today EOD.

**Comment by vazquez** [comment]
Files have been handed over :cow: :star:

**Comment by cassiemc** [comment]
@vazquez Would be good to post final files – end result and source folder – here (or somewhere!)

**Comment by vazquez** [comment]
Source folder available in Google Drive on the Design Repo: https://drive.google.com/open?id=0ByIoeeW0a3R_MmFIMU9MczMwUVE

#### 8.5" x 11" Flyer

![bu-flyer copy](https://cloud.githubusercontent.com/assets/1119821/12237062/ddf99c24-b84a-11e5-8dc6-96cb15e244d7.png)

---

#### 11" x 17" Bus Ad

![bu-bus copy](https://cloud.githubusercontent.com/assets/1119821/12237354/4084a400-b84c-11e5-881e-a7bf631ef93d.png)

---

#### 13" x 19" Poster

![bu-poster-bleed copy](https://cloud.githubusercontent.com/assets/1119821/12237403/78f10eb4-b84c-11e5-825f-1aa70d236649.png)


---

#### 50" x 70" Poster

![bu-giant copy](https://cloud.githubusercontent.com/assets/1119821/12237061/ddf64790-b84a-11e5-91e2-9e97588411da.png)
