### ISSUE TITLE
Conduct first field trip in Kenya [ DSO ] 

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#649]
For the Digital Skills Observatory Project, we will run a first research trip in Kenya in January. We are running a bootcamp and community event with volunteers on the weekend of the 15th, which will kick off the research effort in partnership with an organization called DDD.

Dates of the trip: 10th-21st of January
Team: @secretrobotron + @lauraReynal

There is a [repo](https://github.com/MozillaFoundation/digital-skills-observatory/issues) to keep track of issues for the team (not just MoFos) and a [slide deck](https://docs.google.com/presentation/d/1TnJk4bBLetG1KQvVoTb17wvQdt5o_JveLUOvVIIAhOQ) to introduce and explain various aspects of the project.

**Comment by LauraReynal** [comment]
@davidascher can you reach out to Praekelt and make an intro?

**Comment by hannahkane** [comment]
This ticket is a milestone that has passed. Should we roll into current or future milestone?

**Comment by LauraReynal** [comment]
This is done ! Closing.
