### ISSUE TITLE
10K Contributor Engagement

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#65]
Re-engage the 10K contributors by offering to "skill up as a mentor". Plan to go out as part of a New Year's Resolution test. Likely a well produced call with supporting online assets.

Phase: Design / Build / Ship
Owner: Lucy
Decision: @thornet 
Consulted: Amira, Paul
Lead design: n/a
Lead dev: n/a
Quality: @thornet

**Comment by thornet** [comment]
This evolved into the Teach the Web talks and shipped on Dec. 14 and Jan. 28. http://discourse.webmaker.org/category/meet/community-calls
