### ISSUE TITLE
Create and participate in the IoT Caravan in India

### ISSUE THREAD

**Issue by LauraReynal** [MozillaFoundation/plan#650]
**Goal** : design, plan and execute the IoT Caravan in India, from the 29th to the 14th of February

Core team:
* @thornet
* @secretrobotron
* @LauraReynal

Participants:
* @davidascher 
* @simonwex 
* + 1 designer 
* + 2 Mocos 
* + 1 volunteers 

Useful documents:
* [Introductory slide deck](https://docs.google.com/presentation/d/1z6ZOCwJ4wQRDf8fKvxARsZiuXEY1aah16ubkylroFu0)

#### TO DO 
We are tracking things in the [research repo](https://github.com/mozillafoundation/research) but here is a general list:
- [ ] get visas, flights and accommodation
- [ ] get budget + cash 
- [ ] get participants finalized: @davidascher for MoCos and @cassiemc for designer
- [ ] get agenda in place
- [ ] get material 
- [ ] execute 
- [ ] document and share (@secretrobotron)

**Comment by LauraReynal** [comment]
@cassiemc when do you think we can have a design decision made ?

**Comment by cassiemc** [comment]
@LauraReynal - Workin' on it today. I think this does hinge a bit on the possibility to bring a moco designer. cc @davidascher

**Comment by cassiemc** [comment]
@LauraReynal @secretrobotron I'm hoping you guys can find a moco designer to come with, as unfortunately none of the Mofo designers are available this time. Folks are very up for participating on future trips, though. I'll try to help out as much as possible with any design guidance / prep work leading up to the trip.

**Comment by hannahkane** [comment]
This ticket is a milestone that has passed. Should we roll into current or future milestone?

**Comment by LauraReynal** [comment]
Currently happening. Can close.
