### ISSUE TITLE
Wrap up leftover EOY dev tasks

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#651]
There are a number of engineering issues for EOY to wrap up. These include documentation, non-urgent security issues, and stewardship pieces that shouldn't take long to implement (we just didn't have capacity in Dec). Many of these will relate to the advocacy work in Q1.

They are currently documented here but will need to be reviewed and triaged in early Jan: https://github.com/mozilla/donate.mozilla.org/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Bluesky+%28nice+but+out+of+scope%29%22

cc @davidascher @simonwex

**Comment by OpenMatt** [comment]
adding a priority label so this doesn't fall through the cracks -- not sure if p2 is the right one.

**Comment by OpenMatt** [comment]
@simonwex over to you for next steps

**Comment by simonwex** [comment]
@ScottDowne has made progress on a bunch of leftover tasks. The rest will be worked on during the next campaign if they're still valid.
