### ISSUE TITLE
Follow up on Orlando work group proposals

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#652]
Let's start the year off acting on lessons learned from last year. And following up on the great "work group" proposals made in Orlando:
* Orlando proposals: https://docs.google.com/a/mozilla.com/document/d/15NVMqr4unr1HNDO_esGpMfHXm-Q7p7J56CplBtqtsis/edit?usp=sharing
* Ideas for potential heartbeat improvements: https://docs.google.com/document/d/15j9E0qdfQsKZkknLZ7UvNZ6aAmxABfSYVIxbqrRdxFE/edit

Interested in collaborating on this? Add your name here:
 - @OpenMatt 
 - @xmatthewx
 - @edrushka 
 - @hannahkane

### Next steps:
schedule a kick-off meeting for week of Jan 11

**Comment by OpenMatt** [comment]
I'm totally up for this. Angela is up for being the executive team champion for this work as well.

**Comment by OpenMatt** [comment]
+ Jessie Keating

**Comment by OpenMatt** [comment]
Going to schedule a kick-off meeting this week w. Angela

**Comment by OpenMatt** [comment]
@aplohman has next steps on this one, and will discuss in next staff meeting. Going to mark closed for now.
