### ISSUE TITLE
Localize Spectacular Snippet Copy

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#654]
Please expose the string as soon as possible through the fundraising project and send an email to dev-l10-web.

This is copy that will be tested to run in the fundraising snippet on our biggest days of the year: Dec 29, 30 and 31.

We only need it localized in DE, FR, ES, PT-BR and IT. Other languages will not be used.

**Comment by alicoding** [comment]
Where is the copy?

**Comment by edrushka** [comment]
ha sorry https://docs.google.com/document/d/1wQU-7LNZwncc4qDVPN-DHZZFDc2s5ASAbsub6DIT60M/edit

**Comment by edrushka** [comment]
@valianttry -- Flod thinks IT will be no problem. DE and FR should be ok. But ES and pt-BR might be a little harder. You might want to flag Kontextor for these last 2.

**Comment by edrushka** [comment]
oops. wrong repo!
