### ISSUE TITLE
Create an enviromental impact survey for MoFos

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#655]
This is an action item from our kickoff discussion #633.

Questions/topics are being collected here:  https://docs.google.com/a/mozilla.com/document/d/1H41T5FvOOdcnD89k0AgX6LlWUt3aJR0PtBY4uWzsksE/edit?usp=sharing

cc @secretrobotron @stephwright

**Comment by stephwright** [comment]
@zee-moz asked if she could be a part of this, as well

**Comment by edrushka** [comment]
Of course! Everyone is welcome! :dancers:

**Comment by cassiemc** [comment]
Let's review a first draft of questions in that doc mentioned above at our next meeting, Jan 7.

**Comment by edrushka** [comment]
Oopsies. I accidentally duplicated this in #663. Closing this one.
