### ISSUE TITLE
Update build.webmaker.org and book.webmaker.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#656]
Some things looks a little out of date, including: 
 - [ ] urls are no longer reflective of our terminology and scope - https://github.com/mozilla/build.webmaker.org/issues/95
 - [ ] "Our Audience" page on build uses "Webmaker" as the overarching connecting term
 - [ ] "File a Bug" page on build could be expanded to include other repos
 - [ ] "Introduction" on book - mission statement needs to be rewritten
 - [ ] Provide update/summary of 2015 plan to book
 - [ ] Add 2016 plan to book
 - [ ] Consider re-writing "Roles" page on book. (Have we been using DARCI more frequently than the roles described on that page?)
 - [ ] Add detail or remove "Sign-offs" page
 - [ ] Update names of people on "What should I do if I'm stuck?" re: github
 - [ ] Update "how to use labels" section of Top Tips: https://github.com/mozilla/build.webmaker.org/issues/96
 - [ ] Update "Where to File?" page
 - [ ] Update "Planning tickets" page
 - [ ] Update FAQ

**Comment by hannahkane** [comment]
@OpenMatt - should this be assigned to you? I'm happy to help.

**Comment by cassiemc** [comment]
I am also happy to help. I think there are lots of granular things in this, so I'll start a new milestone for these issues in the build repo here: https://github.com/mozilla/build.webmaker.org/labels/2016-cleanup

**Comment by OpenMatt** [comment]
I'll volunteer to PM this if it needs a driver.

**Comment by OpenMatt** [comment]
@cadecairos I'd like to start by moving "build.webmaker.org" to "mofo.build" (which I have registered). @simonwex mentioned you'd be able to help with this. Is that something you can start on?

**Comment by OpenMatt** [comment]
I'd also love to get some UX and design help to refresh the page a bit. @xmatthewx I know you have some ideas about UX / product thinking for this. Would you be able to help a bit next week?

**Comment by cadecairos** [comment]
@OpenMatt http://mofo.build points to the app, but we're going to need SSL for that domain.

@simonwex How should we get that?

**Comment by cassiemc** [comment]
@OpenMatt If @xmatthewx is unable to help, I can. So going to remove ```needs design```

**Comment by OpenMatt** [comment]
work is ongoing

**Comment by cadecairos** [comment]
@OpenMatt Since we're unable to transfer domain ownership of mofo.build to Mozilla (And thus, cannot obtain MoFo signed SSL certs), @simonwex and I agree that we can use `build.mozillafoundation.org` and `book.mozillafoundation.org` until we're allowed to transfer.

Does that seem like a good alternative?

**Comment by OpenMatt** [comment]
sounds good. let's do it.

**Comment by OpenMatt** [comment]
sounds good. let's do it.

**Comment by xmatthewx** [comment]
It's a great alternative. We should avoid the use of "MoFo". It dilutes our brand and confuses new staff and people in the network.

**Comment by cadecairos** [comment]
Alright, working on getting the DNS set up and the certs signed and installed on Heroku.

**Comment by OpenMatt** [comment]
This one is going to carry over into the next heartbeat. Good progress. Will aim to ship before the early Feb staff meeting.

**Comment by OpenMatt** [comment]
rolling over again

**Comment by OpenMatt** [comment]
Chris and I made some good progress here, but will need one more heartbeat to finish up.

**Comment by hannahkane** [comment]
Should we roll this one over again?

**Comment by OpenMatt** [comment]
Yes. I suck.

**Comment by OpenMatt** [comment]
Sam and I have a plan to launch this as part of a concerted effort / package w. the internal comms work she's doing on the strategy. Later in April / early May.

**Comment by hannahkane** [comment]
Rolling this over. @OpenMatt - feel free to change if this is wrong.

**Comment by hannahkane** [comment]
Rolling over to May 20.

**Comment by hannahkane** [comment]
Is this ticket still useful, or should we close?

**Comment by xmatthewx** [comment]
Work seems to have stalled. There is, however, some broken/lost design content that I would like to recover. Unsure how to proceed. https://github.com/mozilla/build.webmaker.org/issues/104

**Comment by OpenMatt** [comment]
hey Matthew. I'm working on it this week and after All Hands. Need to check
in on state of Calypso / CMS.

**Comment by hannahkane** [comment]
@OpenMatt - can we close this ticket since we have a new home for this content? Moving out of July 1 heartbeat for the time being.
