### ISSUE TITLE
Design the Chronicle – showcase last 5 years of Mozfest

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#658]
There was a lot of great work that happened in https://github.com/MozillaFoundation/plan/issues/566

I am wondering if there are next steps for the design, and if we're hoping to do this internally or hire a contractor? When this work is slated to be completed? Don't want it sneaking up on us in the new year if possible!

cc @benrito @OpenMatt and probably @edrushka

**Comment by benrito** [comment]
We have a meeting tomorrow and this will probably be on the agenda—can post an outlook then.

Thank you!
Ben

**Comment by OpenMatt** [comment]
@benrito any updates?

**Comment by cassiemc** [comment]
I thought I heard we were not doing this. Might've been something else. @benrito?

**Comment by benrito** [comment]
Yeah we are on hold, but possibly resurrecting around MozFest.

(Thought I responded to Matt's note here—weird)

**Comment by cassiemc** [comment]
Ok, thanks @benrito! I will close this in favour of opening a new one when it's more relevant.
