### ISSUE TITLE
[Feb 19] Design new swag for upcoming events

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#660]
We have some events coming up and are nearly out of swag here in the Brooklyn office.

@cassiemc Can we get any help designing some generic swag (thinking Dapper Fox buttons, patches, stickers)

Might even be good to do X-Ray Goggles and Thimble stickers - we can do simple logo + URL or something fun ;)

**Scope:**
- [x] Dapper Fox patches
- [x] Dapper Fox stickers
- [x] X-Ray Goggles stickers – simple logo + URL or something fun
- [x] Thimble stickers – simple logo + URL or something fun
- [x] Generic #teachtheweb button

**Comment by cassiemc** [comment]
@ldecoursy This should definitely be doable. Let me catch up with the designers on Monday at our regular triage call and I'll see who can help.

**Comment by cassiemc** [comment]
@ledecoursy It might be helpful in the meantime to know your ideal scope. Wonder if you wouldn't mind finding out a design brief – http://bit.ly/mozdesignbrief – and I'll schedule a follow call with you+me on Monday as well.

**Comment by cassiemc** [comment]
@ldecoursy and I met earlier this week and scoped out some requirements: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

This doesn't need to be done quite yet, so I am going to push this out a heartbeat.

**Comment by ldecoursy** [comment]
Sounds like @flukeout is already working on a Thimble sticker ;)

**Comment by ldecoursy** [comment]
Tracking here: https://github.com/MozillaFoundation/Design/issues/125

**Comment by cassiemc** [comment]
@ldecoursy Let's keep this open. I'll assign it to me, but @vazquez is driving this with @my-le. I'll schedule a kickoff early next week unless anyone has already done that?

**Comment by cassiemc** [comment]
Here are the main things that need doing, from a list I created with @ldecoursy here: https://docs.google.com/spreadsheets/d/1X6AhlnutTL6M3xMZ-8DSIU0AI8166pz4YlXY4DODUm4/edit#gid=0

- [ ] Dapper Fox patches
- [ ] Dapper Fox stickers
- [ ] X-Ray Goggles stickers – simple logo + URL or something fun
- [ ] Thimble stickers – simple logo + URL or something fun
- [ ] Generic #teachtheweb button

We'd like to have these assets printed and delivered to the Brooklyn office by the first in a series of events beginning February 26.

Going to track these issues in the design repo via a ```swag``` label here: https://github.com/MozillaFoundation/Design/labels/swag

**Comment by cassiemc** [comment]
Kickoff scheduled for Monday.

**Comment by cassiemc** [comment]
Note: @ldecoursy @vazquez @my-le I elevated this issue to a P1 since it's My's only task this heartbeat, and I added the assets checklist to the first issue so we can track progress.

**Comment by OpenMatt** [comment]
status?

**Comment by vazquez** [comment]
We are done! Just closed our last issue.

**Comment by cassiemc** [comment]
All done! Great work @vazquez @my-le.

@ldecoursy All the files you need should be here: https://drive.google.com/a/mozilla.com/folderview?id=0BzfN9sXlOXt1SG9wVDY5TzdLUWs&usp=sharing
