### ISSUE TITLE
Determine overarching Information Architecture for Leadership / Advocacy web properties

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#661]
The conversation in #643, which is ostensibly about designing a common theme, has veered into a larger conversation about IA.

@sabrinang's [visualization](https://cloud.githubusercontent.com/assets/2492510/12096773/91bd9ed8-b2cc-11e5-956f-2330e9be2ce0.png) is a great starting point, and @cassiemc's [viz](https://redpen.io/jx5db8131a9b2deea3) offers add'l clarity.

Questions to resolve:
* What is an overarching IA system that a) allows us to adapt and grow our programmatic offerings, and b) speaks to users' mental models, not just our own internal structure?
* What rules make up that system? e.g. "We create a new top level page (mozilla.org/[name]) when X criteria are met," and "We create a new subdomain ([name].mozilla.org) when circumstance Y occurs."

Process:
We might be very close to having this system, but I think it would be good to formalize it and run it through a QA process where we confirm it works for all existing and planned web properties and programs.

Idea! In order to make sure that it speaks to users' mental models, I'd suggest we do a card sorting activity with members of our target audiences.

If this ticket is redundant, please close, but my sense is that answering IA questions is a prerequisite to the design, branding, and tech questions surfaced in the templating conversation.

/cc @cassiemc @davidascher @HPaulJohnson @ldecoursy @sabrinang @edrushka @xmatthewx @OpenMatt @simonwex and probably lots of other people

**Comment by OpenMatt** [comment]
@hannahkane P1 or P2? I'll make it a P2 for now, just so it shows up in our lists and doesn't fall through the cracks Please update if that's wrong.

**Comment by hannahkane** [comment]
Agree. Only put it in this milestone so we would discuss at today's planning meeting, but need input from others about where this fits in.

**Comment by hannahkane** [comment]
Drafted a proposal. Needs input. https://docs.google.com/a/mozilla.com/document/d/1A7o2wnQBBOKnVqIUvXDS9UHspBFSSbLSSkp0Na2ics4/edit?usp=sharing

**Comment by xmatthewx** [comment]
kudos to you @hannahkane for tackling this spaghetti monster. Added a few comments.

**Comment by hannahkane** [comment]
Thanks, @xmatthewx.

I think this still needs feedback from several other people.  @davidascher - who is the Decider for this? Is it you?

**Comment by cassiemc** [comment]
@hannahkane I'm planning to look & comment this afternoon

**Comment by davidascher** [comment]
In terms of 'deciding', I suggest:

a) iterating w/ the comms council.  IA & websites are critically communication tools
b) when there's agreement and really need to decide whether to implement, I suggest a presentation to the executive team, as all are involved.

-da

**Comment by hannahkane** [comment]
Sounds like a good plan.  Who can I assign this ticket to?

**Comment by cassiemc** [comment]
@hannahkane You can assign this to me but I don't see the whole conversation / approval process wrapping up by end of week. Still working on #644

**Comment by cassiemc** [comment]
Needs a dev for some consulting, could be you @simonwex? Will also need a designer to drive some of this visualization.

**Comment by cassiemc** [comment]
Assigning @sabrinang for design.

**Comment by simonwex** [comment]
Happy to be the consulted dev on this one.

**Comment by cassiemc** [comment]
Thanks Simon!

**Comment by cassiemc** [comment]
I suggest a few deliverables to close out this bug: 
- [ ] A revised version of Sabrina's internal program map
- [ ] Another version of Sabrina's program map that is more user-facing. The differences in these two maps should be clearly delineated.
- [ ] A UX flow, similar to my map, that shows what these changes might look like in a single program.
- [ ] List of proposed URL and architecture changes.

We can use the comms inventory to inform this work. #678 And when we're ready to close this issue, let's review with the executive team.

@sabrinang and I are meeting later today to go over what we need to do. Have also just invited @hannahkane if you're available.

**Comment by cassiemc** [comment]
As @sabrinang and I build this out here: https://docs.google.com/presentation/d/1OkKopl37qGCyvlylpgDSC0yjusuAlxA78Ka0_kDEIAs/edit#slide=id.g821d6ef90_6_184
We are referencing the slides from 2020 strategy docs.
<img width="799" alt="screen shot 2016-01-21 at 2 43 26 pm" src="https://cloud.githubusercontent.com/assets/1186326/12492303/9539c576-c04d-11e5-941b-8a93c0842ba1.png">
<img width="797" alt="screen shot 2016-01-21 at 2 43 43 pm" src="https://cloud.githubusercontent.com/assets/1186326/12492304/953a0662-c04d-11e5-9127-6160c4df9d51.png">

**Comment by cassiemc** [comment]
@sabrinang A new goals doc I saw from @chrislarry33 labels the "I" under MLN as "Innovation", not "Incentives".

**Comment by ldecoursy** [comment]
Those slides you posted above are early drafts from Oct. The [business plan from Phase 3](https://docs.google.com/document/d/1OipsGu8eWuTaT8J3T2-0CR3zB79SysATBLiTTBDGS5I/edit#) (pages 14 and 23) has the updated buckets for MLN and Advocacy

**Comment by cassiemc** [comment]
Thanks so much @ldecoursy. I thought I was posting slides that Surman emailed everyone at Mozlando. Here are updated screengrabs:
<img width="639" alt="screen shot 2016-01-22 at 11 20 18 am" src="https://cloud.githubusercontent.com/assets/1186326/12516192/329f0482-c0fa-11e5-9266-7c1703aa19ec.png">
<img width="627" alt="screen shot 2016-01-22 at 11 20 35 am" src="https://cloud.githubusercontent.com/assets/1186326/12516191/329bdf00-c0fa-11e5-9d68-2b60f1d33b07.png">

**Comment by sabrinang** [comment]
@cassiemc David mentioned to reach out to Sam Burton - she is working on articulating the strategy plans so it could be informative to help understand the system better to visualize the IA

**Comment by cassiemc** [comment]
Working session set up with @sabrinang, @samanthaburton and I for tomorrow.

**Comment by cassiemc** [comment]
This is ongoing, so moving to the next heartbeat. Hoping to result in a set of actionable items within the next heartbeat.

**Comment by hannahkane** [comment]
Just chatted with @sabrinang. Between the Web Lit Map and the Style Guide, it's likely she won't have time to work on this next week. @cassiemc - ok to roll to next heartbeat? Web Lit Map and Style Guide feel more urgent.

**Comment by cassiemc** [comment]
Yes, wfm @hannahkane.

**Comment by kristinashu** [comment]
Working with @sabrinang we came up with this table https://docs.google.com/a/mozilla.com/spreadsheets/d/1BeB8bZG2LX2aYPFZyyo57a1J0nn5-9SG-GsCdUJD-r8/edit?usp=sharing

We're trying to point out similarities in both the vertical columns (ex news, science, education...) and the horizontal columns (ex fellowships, convenings, blogs...). 

This should help us determine URLs in a structured way and find opportunities to share templates/resources internally.

**Comment by cassiemc** [comment]
@davidascher @chrislarry33 Can you guys review this IA proposal doc, and leave any outstanding questions? There are a few open questions you can probably help with too. And we've arranged a meeting with Claw, @ldecoursy, @hanasun, @sabrinang, @kristinashu to talk about education vs. MLN vs. teach, etc.
https://docs.google.com/spreadsheets/d/1BeB8bZG2LX2aYPFZyyo57a1J0nn5-9SG-GsCdUJD-r8/edit#gid=0

Next step is to translate this doc into more traditional, high-level IA docs for each property.

**Comment by cassiemc** [comment]
As part two of this exercise I'd like to clarify in this doc what the proposed changes / additions are from @kristinashu. I think there was an (perhaps unnessecary) assumption that we would be building a Mozilla Foundation site. I'd actually like to avoid that if possible, because I don't think its beneficial to us or users to split the mozilla brand, but I do think we should consider building landing pages where it makes sense for specific audiences, ie a fellows or mln learning page (exact details tbd). @xmatthewx could you also review this doc? I'll invite you and @hannahkane to a review meeting soon as well)

**Comment by hannahkane** [comment]
Would love to attend a review meeting. I may have misread the doc, I thought the second column was referencing a Mofo-wide site. 

Curious to understand better if the first column is suggesting standardizing the navigational items on all properties. If that's the case, I have a couple concerns/questions. Would love to talk more!

**Comment by cassiemc** [comment]
Yes, let's review!

**Comment by secretrobotron** [comment]
@cassiemc @hannahkane can I come too?

**Comment by cassiemc** [comment]
@secretrobotron it happened yesterday! But I liked your additional points in the doc and we're continuing to hack it. Notes from yesterday's meeting here: https://public.etherpad-mozilla.org/p/IAmtgnotes 

Bobby I'd love to pick your and @LauraReynal's brains about if research is reinforcing some of these suggestions. I'll find a time for that next week if that's cool – I think we'll have more to show then too.

**Comment by secretrobotron** [comment]
@cassiemc yes, please!

**Comment by cassiemc** [comment]
Made awesome progress on this. Here's a new externally facing doc from @kristinashu: https://docs.google.com/presentation/d/1MOhf0PSvCU2flniNsbl1FW0xPi0ZnJHJJEZ3qlyAcrE/edit#slide=id.g11b2897a1a_2_0

Going to close this in favor of https://github.com/MozillaFoundation/plan/issues/751
