### ISSUE TITLE
Explore Prototype of MoFo-wide CMS Stack

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#662]
The requirements are coalescing for:
 * Custom one-off high-polish web pages with ~quarterly update frequencies
 * MoFo-managed content-focused websites requiring frequent content updates
 * MoFo-managed blogs
 * Tools and services to enable clubs to manage their content similarly

Let's build a prototype to understand what and how we should deliver on these requirements.

https://github.com/mozilla/mofo-cms-experiment

Owner: @simonwex
Decision Maker: @simonwex
Consulted: @hannahkane @amirad @cassiemc  ...
Design Lead: 
Development Lead: 

### Constraints:
 * We will not roll our own CMS
 * We want to deliver a high-value editing environment for the CMS
 * Content should be able to be surfaced in a platform-agnostic way
 * We must support l10n

### Related:
 * #643 
 * #644

**Comment by simonwex** [comment]
One approach could include:
 * A new-generation of makerstrap
 * Wordpress.com as the data-store (to be self-hosted later)
 * A custom-themed [Calypso](https://github.com/Automattic/wp-calypso) as the editing environment
 * A boilerplate app in React written to link Makerstrap V2 with WP-API.

**Comment by acabunoc** [comment]
cc: @acabunoc -- I'd like to know what happens here! Also happy for science to act a guinea pig on this if you need one :)

**Comment by simonwex** [comment]
@acabunoc I'd love for you to be involved in this project! The output will be a prototype, so `s/guinea pig/collaborator/` :smile:

**Comment by hannahkane** [comment]
Love this idea. Also flagging local Hive sites as a possible test case.

**Comment by acabunoc** [comment]
@simonwex sounds great -- would love to be involved!

**Comment by simonwex** [comment]
Another idea would be to use [Django CMS](http://www.django-cms.org/)

**Comment by omnignorant** [comment]
+me as :hamster: / :pig2:

**Comment by simonwex** [comment]
@omnignorant, you want to be a hamster-pig?

**Comment by omnignorant** [comment]
@simonwex, we can't all be so clever using file hierarchy humor and emoji is a woefully limiting form of linguistic expression (tho, richly poetic). Use your powers of deductive reasoning to get my gist.

**Comment by hannahkane** [comment]
:fire:

**Comment by omnignorant** [comment]
:heart:

**Comment by simonwex** [comment]
oh, you mean hamster/pig. 10-4

**Comment by secretrobotron** [comment]
cc myself

**Comment by cassiemc** [comment]
On design side, would be great to include @flukeout @vazquez @natalieworth @ScottDowne @gvn or some subset of this group. Want to make sure we don't get roped into prohibitive design solutions, where making design changes is overly difficult, and would also suggest that one criteria for assessment is the solution's portability to other platforms should we choose to change CMSs later down the road.

**Comment by cassiemc** [comment]
+ @cadecairos

**Comment by gvn** [comment]
I don't want to be a buzzkill, but it's really not possible to have a CMS without any limitations on design. That's the nature of the beast. If we do go down the CMS road we have to create fairly rigid templates. You're never going to get the level of control over design with a CMS that you would with hand coding.

It's also sadly never going to be trivial to change out a CMS down the road. Every CMS does things differently and migrating is going to require at least some refactoring if not a *lot*.

**Comment by ScottDowne** [comment]
I think I agree with @gvn about design limitations.

My limited understanding of a traditional CMS is that it's not publishing webpages, but filling a webpage, or template, with content.

The act of adding style to that content is totally not what a CMS is really optimised to do, and from from my experience a CMS actually makes that harder. Doing design work in a CMS is making a new template, which is different from adding content. You don't want to be making templates very often... if ever!

**Comment by ScottDowne** [comment]
So talking with other people right now, and something Abby has experience, that we can use a CMS as a content back end/admin interface, but we have a front end that is separate from that.

In would probably work well.

**Comment by gvn** [comment]
To more specifically address the 4 areas in question:

> Custom one-off high-polish web pages with ~quarterly update frequencies

A CMS is not great for this purpose. I'd suggest a lightweight templating language that's easy to perform copy edits (such as [Jade](https://github.com/mozilla/research-website/blob/develop/source/index.jade)) or using markdown to be transformed into HTML. We should do more research into static site generators for this purpose (eg: Jekyll, Wintersmith, etc).

> MoFo-managed content-focused websites requiring frequent content updates

Again, probably not a good fit for a CMS unless the content is very structured and fits neatly into predefined templates.

> MoFo-managed blogs

There are many CMSs that are decent for blogs as long as content is fairly basic (eg: a standard text-heavy article with a title, date, and author to be displayed). This is also a place where static site generators shine both for performance (speed and SEO particularly) and ease of modification. 

> Tools and services to enable clubs to manage their content similarly

I'm not fully aware of what clubs need, so hard for me to comment. :dancers:

**Comment by mmmavis** [comment]
+1 on what @gvn said! :grin:  I'm also wondering if we have specs for the Clubs site  that can be shared here. Even if it's still in the draft state it can still help us determine whether CMS can be a good approach.

I haven't started doing any research yet so I can only speak from my experience with WordPress. Even if we are going with a hybrid solution (using CMS for admin interface only) I'm worried it would just mean adding an extra layer of complexity to development as we will then need to build the hooks to communicate between CMS and the build systems. We will still have to build and maintain the custom theme that used to power the CMS - which indeed is very troublesome & time consuming from my experience with WordPress. :confounded:

**Comment by gvn** [comment]
If anything, we should look at CMS's that are decoupled from the presentation layer, which is I believe what @simonwex is advocating. If the managed content is unaware of its destination container (eg content is served via a REST API) then that's much cleaner than editing content "in place". When styling and content management are conflated it's a world of pain.

I'm not convinced we can find a one-size-fits-all CMS that will serve all our use cases. However, I think we can standardize a service oriented architecture for delivering content, which will serve us well. :+1:

**Comment by mmmavis** [comment]
Before we start building the prototype, I think it will help a lot if we could go through the site specs with non-dev site admins. It's important for the devs to understand how admins' expectations of our CMS solution are and for them, to understand the techical/editing constrains. If we don't do well in the communication process there will be pain on both ends afterwards. :sob:

**Comment by simonwex** [comment]
Hey @gvn & @mmmavis things to look at before tomorrow's meeting:

 * https://github.com/Automattic/Picard
 * http://v2.wp-api.org/
 * https://github.com/Automattic/wp-calypso

**Comment by simonwex** [comment]
We'll be doing our work here: https://github.com/mozilla/mofo-cms-experiment

**Comment by OpenMatt** [comment]
@simonwex is there a potential test case for what the first web site / property to use this might be?

**Comment by OpenMatt** [comment]
e.g., we know we're aiming to ship a shared curriculum platform in H1. Is that a potential customer for this? something sooner?

**Comment by gvn** [comment]
FWIW: I think we'll have multiple prototypes. 

It sounds like @mmmavis is working on a React + WP prototype along the lines of what @simonwex proposed. I'm working on making the Research site editable via a purely JS/JSON based approach.

We might even have a 3rd prototype, but I'm not sure. Regardless, this should allow us to weigh pros and cons of the various approaches.

I don't think we should prototype on anything that's mission critical since we are still trying to discover what we want our unified approach to be... :mag:

**Comment by hannahkane** [comment]
cc @flukeout and @acabunoc who I believe are working on a project with similar goals—making it easy to create Science learning materials with just markdown. Not a CMS, but achieving the same goal of making it easy to create/edit content.

**Comment by flukeout** [comment]
Indeed - the plan (so far) is to host the content as markdown files on github, but also to render them into prettier HTML via some front-end code, I'll let @acabunoc chime in - we'll be experimenting with the first piece of content soon.

**Comment by gvn** [comment]
@flukeout @acabunoc @simonwex @mmmavis – We should probably all sync up some time soon. It sounds like between all of us we're trying 3 approaches, which is totally cool, but it'd be nice to share insights sooner than later! :+1:

**Comment by simonwex** [comment]
We have explored two prototypes as a part of this research. Both are promising and address a different set of problems identified by our use-cases. We'll be demoing them tomorrow and continuing work on the calypso-based prototype with a focus on the Science site in the following heartbeat.

**Comment by cassiemc** [comment]
Science site probably won't be ready for implementation for a couple heartbeats (unless you're thinking of doing something prior to re-IA, UX, UI of the site #704 

Demos were awesome though! Were they recorded? Is it possible to do a written recap of the two options in the meantime? Would love to include it in the better-faster update #699

**Comment by hannahkane** [comment]
Hive sites could be ready for implementation I think. Could we push on that, @simonwex ?

**Comment by cassiemc** [comment]
I'd want to know if it makes sense to push forward on getting Hives into a templating system prior to any potential redesign work. Definitely don't want to be a blocker, so we can let the tech implementation drive design constraints as well, but worth asking now.

**Comment by hannahkane** [comment]
Should we close this ticket in lieu of #716?
