### ISSUE TITLE
Prepare Encryption campaign for Jan 28 launch

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#664]
Project Manager: @openmatt
Project Team: Brett, Paul, Andrea, Sara, Jordan
Project Brief: http://mzl.la/encryption
Repo: http://mzl.la/encryption_issues

**Comment by OpenMatt** [comment]
GOAL: Reset conversation around “encryption”.  Starting with an initial explainer video and educational CTA launching Jan 28. This includes plans to:

    Deliver a staged roll-out of 5 key deliverables, or ‘beats’ 
    Engage email list of 2m+ users 
    De-mystify encryption and make it a “thing worth caring about” 
    Turn email list subscribers into advocates ready to mobilize 
    AB Test copy and create approaches for future campaigns

**Comment by jgmac1106** [comment]
Beyond the interactive website that will be built and the cryptography game in the last beat much of this seems consumption based.

People have been asking all over the Web how to install Let's Encrypt. Why not have a "live demo" followed by a 2-day distributed hack-a-thon where we try to get people to use LE.

Not sure of the technical lift. I assume the process will be different based on server/hosting. But if we had a community driven event where people pay it forward by "staffing office hours" after they get help it might be a cool thing to do.

**Comment by OpenMatt** [comment]
@jgmac1106 we're still trying to figure out the call to action. But we know we want it to include some aspect of explaining to others / teaching it forward -- so this is a good idea.

**Comment by OpenMatt** [comment]
whoops -- just noticed that this ticket is a dupe! Will close this and work here:
https://github.com/MozillaFoundation/plan/issues/645
