### ISSUE TITLE
Set up a blog for IoT

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#665]
GOAL: Stand up a blog so that we can publish casual updates from the IoT project. Serves as a single source of information concerning the project.

* Audience: Small. Any major updates/publications will be raised in the courts of the CommsCouncil™.
* Design: Doesn't need *any* for now beyond picking a cool template.

Needs:
- [ ] URL
- [ ] A ghost blog instance

DARCI:
- Consulted: @secretrobotron, @LauraReynal, @thornet
- Dev: @simonwex

cc @HPaulJohnson @thornet @LauraReynal @simonwex

**Comment by simonwex** [comment]
Hey @secretrobotron! I'm going to be doing this one. Do you have a URL you'd like it to live at?

**Comment by secretrobotron** [comment]
Güd question.

@hannahkane and I decided that the research blog could live safely at https://mozilla-foundation-research.herokuapp.com/ for now, and I assume we could do the same for this blog (e.g. mozilla-foundation-iot or something).

We're using mzl.la/research for the research blog, and could also do the same here. Maybe mzl.la/iot for now until we understand the MoFo IA a bit better. @thornet @LauraReynal?

**Comment by secretrobotron** [comment]
@simonwex TL;DR as long as the machine is up and we can use it to write, I don't think it matters.

**Comment by simonwex** [comment]
It's live here:
https://mozilla-foundation-iot.herokuapp.com

I copied over all the accounts from the research site. Let me know if you need anything by re-opening this boog.

**Comment by thornet** [comment]
＼（＾▽＾）／

On Tue, Jan 19, 2016 at 7:36 PM, Simon Wex <notifications@github.com> wrote:

> It's live here:
> https://mozilla-foundation-iot.herokuapp.com
>
> I copied over all the accounts from the research site. Let me know if you
> need anything by re-opening this boog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/plan/issues/665#issuecomment-172944691>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by secretrobotron** [comment]
:heart::heart::heart::heart::heart:
