### ISSUE TITLE
Clarify mandate of convenings team

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#666]
MLN has a brand new team: convenings!  

Step one is to clarify our mandate and communicate it to MoFos.

**Comment by edrushka** [comment]
Work is happening on this but it's not done. Moving to next milestone.

**Comment by edrushka** [comment]
Aaaaaaalmost done! Meeting with Chris on Monday for his signoff and then we can share publicly.

**Comment by OpenMatt** [comment]
@edrushka status?

**Comment by edrushka** [comment]
Sarah, Claw and I have finished the Convenings 2016 plan and will be distributing it for review on Monday Feb 15. Closing this.
