### ISSUE TITLE
Set up Mattermost instance and modify for basic MoFo needs

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#667]
Our plethora of IRC channels are mislabeled for our 2016 efforts. Instead of continuing with a technology that is often cited as being unwelcoming and antiquated, let’s replace it with an open-source alternative to Slack.

An example of why we want to move away from IRC and to a different real time communication environment https://make.wordpress.org/chat/

Driver: @simonwex
Dev: @alanmoo 
DevOps: @cadecairos 

Advantages include:
* Available for access from mobile devices
* More welcoming to new contributors (easier to start chatting)
* Questions asked by contributors remain persistent until someone is available to answer
* Search history
* Potential for reduced “all-mofo” email
* Functions as an IRC server for those stuck in their ways
* Easy asynchronous conversation

Potential drawbacks to be aware of:
* Cultural shift from ephemeral messages to logged history could result in another stream from the firehose to keep track of

Initial Goal: Move all MoFo IRC channels to Mattermost

Technical Needs:
- [x] URL (chat.mozillafoundation.org)
- [x] Hosting
- [x] Deployment process

Process
- [x] Set up instance(s) of self-hosted Mattermost 
- [x] Determine channels to be created in Mattermost
- [ ] Bridge Mattermost channels to corresponding IRC channels
- [ ] Set IRC channel topics to direct people to Mattermost
- [ ] Find all the places from which we're currently directing people to IRC channels and prepare to push updates directing them to the Mattermost instance.
- [x] Investigate integrations needed/desired by MoFos

**Comment by alanmoo** [comment]
@simonwex I've added some high level stuff, how specific should this be?

**Comment by simonwex** [comment]
This is a great start. What do you think we should do for existing channels? Leave a bot behind? Change the topic?

**Comment by alanmoo** [comment]
Yeah, both. I played around with the bridge today and it's...ok. Since everything is repeated by one bot, following a conversation between IRC and Mattermost users can be a little odd, but if we get a critical mass of people switching over I think it'll be an infrequent enough use case that it won't be confusing.

**Comment by simonwex** [comment]
We're all set up and it's a thing of beauty. We're going to roll this out to engineers and designers as a beta release in the following HB. 

http://chat.mozillafoundation.org/mofo/

**Comment by alanmoo** [comment]
Updated your comment with the proper link, @simonwex
