### ISSUE TITLE
Solve for bugzilla security bug

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/plan#668]
it's locked because it's sensitive. I have added @adamlofting to the cc so he can see it. I suspect he probably knows the most about fixing it.

https://bugzilla.mozilla.org/show_bug.cgi?id=1172325

Not sure what to do with it.

More info in the bug itself. Given that it's locked, and github is not, I'm not talking details in here.

**Comment by OpenMatt** [comment]
@scottdowne status?

**Comment by ScottDowne** [comment]
@OpenMatt Same status as when I opened this. I added you to the secure bug, so you should be able to see updates in there.

**Comment by simonwex** [comment]
I'm bumping this to next HB. @adamlofting could you schedule something to discuss this? We should get it sorted asap.

**Comment by adamlofting** [comment]
@simonwex I've just sent a meeting invite.

**Comment by simonwex** [comment]
Hey @adamlofting, we never rescheduled our meeting. I'm going to bump this to next HB, can you still PM it then? Do you have an idea for what you'll need from a resource perspective?

**Comment by adamlofting** [comment]
This would benefit from an engineer who can push a bunch of small changes across many systems (that's vague because sec bug) but I think you know what I mean by that. 

I can scope out the list of tasks.

**Comment by adamlofting** [comment]
flagging in #728

**Comment by adamlofting** [comment]
Status: TBC - I'm checking in with @alicoding today

**Comment by adamlofting** [comment]
This is very nearly done. Just a couple of PRs to land now.

**Comment by adamlofting** [comment]
All shipped!

Thanks @ScottDowne for flagging, and @alicoding for working through this.
