### ISSUE TITLE
User Account Risk Management

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#669]
Review recommendations as described in security assessment https://bugzilla.mozilla.org/show_bug.cgi?id=1239499 (locked).

Impacts: uses of teach, goggles, webmaker, thimble.

### RACI
Driver: @simonwex
Dev: @jbuck @cadecairos

**Comment by simonwex** [comment]
Meeting scheduled for when @jbuck is back. In this HB, we'll synthesize the recommendations into work to be completed in a follow-on HB.

**Comment by cadecairos** [comment]
File VA bugs in bugzilla (restricted to Mozilla accounts):

api: https://bugzilla.mozilla.org/show_bug.cgi?id=1243167
id: https://bugzilla.mozilla.org/show_bug.cgi?id=1243170
publish: https://bugzilla.mozilla.org/show_bug.cgi?id=1243172

**Comment by jbuck** [comment]
* https://github.com/mozilla/api.webmaker.org/issues/195
* https://github.com/mozilla/id.webmaker.org/issues/410
* https://github.com/mozilla/publish.webmaker.org/issues/219

**Comment by simonwex** [comment]
Ticketing complete, follow-on ticket here: #701
