### ISSUE TITLE
Develop plan and take initial steps to localize Thimble

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#670]
Create plan and begin l10n of thimble.

### DARCI ###
Driver: @simonwex
Accountable: @simonwex 
Responsible: @gideonthomas
Consulted: @humphd, @alicoding 
Dev: @alanmoo, @gideonthomas
Design: @flukeout

Meta bug in Thimble project: https://github.com/mozilla/thimble.webmaker.org/issues/1318

Related: https://github.com/mozilla/thimble.webmaker.org/issues/475

**Comment by simonwex** [comment]
@cassiemc we need some help with design here for the language-picker UI/UX. – I don't think it's a lot of work.

**Comment by cassiemc** [comment]
If it's okay with @hannahkane, it makes much sense for @flukeout to help.

**Comment by hannahkane** [comment]
yup

**Comment by simonwex** [comment]
Perfect. Thanks, Cassie!

**Comment by flukeout** [comment]
Good stuff, I'll get on it.

**Comment by simonwex** [comment]
Great work has been done here. We have a plan and have started to implement the approach in the thimble project. We'll be reviewing the plan with l10n team members next week.
