### ISSUE TITLE
Thimble: Erase P1 technical debt and prepare for l10n

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#671]
https://github.com/mozilla/thimble.webmaker.org/milestones/Jan%2029%20Heartbeat%20-%20Erase%20Technical%20Debt

### DARCI ###
Driver: @simonwex
Accountable: @simonwex 
Responsible: @gideonthomas
Consulted: @humphd 

Dev: @cadecairos, @gideonthomas
Design: No significant design resources required

**Comment by gideonthomas** [comment]
@simonwex https://github.com/mozilla/thimble.webmaker.org/issues/1329 and migrating projects from old-thimble (deferred till after l10n) are the only issues left.

**Comment by simonwex** [comment]
Done barring something that has to happen post-l10n. Tracking that work here: 711
