### ISSUE TITLE
Summarize results of curriculum research

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#672]
We'll finish up the interviews we're doing with educators around finding and evaluating teaching materials, and distill the findings in a useful way. We'll also iterate on the decks we have in order to present one or two proposals for what we might build.

Relevant tickets:
 - [x] [summarize findings](https://github.com/mozilla/teach.mozilla.org/issues/1546)
 - [ ] <s>[create deck](https://github.com/mozilla/teach.mozilla.org/issues/1523)</s>

### DARCI ###
Driver: @hannahkane
Accountable: @hannahkane
Responsible: @flukeout @sabrinang @vazquez 
Consulted: @chadsansing, Curriculum Working Group
Informed: @chrislarry33

**Comment by hannahkane** [comment]
@flukeout - do you think this is likely to finish this heartbeat, or perhaps early next, since the last interview isn't until Friday?

**Comment by flukeout** [comment]
Early next seems like a better bet!

**Comment by cassiemc** [comment]
Hm. There are three designers on this (albeit I know only partially) – can we get some idea of the interview results – even if rough bullets – ready to go by end of tomorrow to inform the work in the next heartbeat? I thought I heard @sabrinang @flukeout @vazquez already had some discussion, so might just be a matter of recapping those insights here. We can add to it after tomorrow's interview if that changes anything.

If the results need to be disseminated more widely, maybe @hannahkane you could help pull it into a deck while designers move on to the next phase?

**Comment by hannahkane** [comment]
indeed. happy to help create a deck to let designers focus on the prototypes/wireframes. don't want to lose momentum on this project.

**Comment by xmatthewx** [comment]
Is this on your list of benchmarks? [TeachersPayTeachers](https://medium.com/bright/millions-of-teachers-minting-millionaire-teachers-decc4fe41604#.i3w8442op). Some interesting insight in the article.

**Comment by hannahkane** [comment]
Wow, yeah, lots of good stuff in that article. Thanks for sharing. I added it to https://github.com/mozilla/teach.mozilla.org/issues/1443 where we're tracking benchmarks.

**Comment by hannahkane** [comment]
Updated title and first comment to reflect that this ticket is now just about the summary of findings; a deck is no longer needed

**Comment by hannahkane** [comment]
This will close tomorrow.

**Comment by hannahkane** [comment]
This is done. See the research findings here: https://github.com/mozilla/teach.mozilla.org/wiki/Curriculum-Database-Research-Findings
