### ISSUE TITLE
Cassie needs cookies

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#673]
Cassie is very hungry

### Audience
Cassie

### Success
A full tummy

### Vision
Something with chocolate chips

### Measurement
Enough to share with everyone.

### Roles
 * Phase: 
 * Driver: @cassiemc
 * Decision Maker: @cassiemc
 * Design Lead: 
 * Development Lead: 
 * Quality Verifier:

**Comment by ryanw-se** [comment]
:cookie: :cookie: :cookie:

**Comment by cassiemc** [comment]
Got 'em. Nom nom.
