### ISSUE TITLE
Determine next steps for Discourse (TOS, URL, etc.)

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#674]
It was brought to our attention that the MLN Discourse forum needs a customized TOS. See https://discourse.webmaker.org/t/editing-of-terms-of-service/445

I reached out to legal and it turns out a legal review has been underway on behalf of Advocacy, but is stalled. I'm hoping to pick it back up and look at this more holistically vs on a case-by-case basis.

Also would like to address updating the URL (currently discourse.webmaker.org).

**Comment by OpenMatt** [comment]
cc @simonwex @davidascher

**Comment by OpenMatt** [comment]
* @cadecairos might be able to move / re-direct the URL in the short term (@simonwex?)
* the larger issues will need more work and discussion

**Comment by simonwex** [comment]
Once we have the updated tos from Abigail, I can coordinate with Yousef to get this updated. No need to assign @cadecairos

**Comment by ldecoursy** [comment]
@simonwex  Last week I shared you on a Google Doc to collect some info for legal to help with the TOS. In the meantime, can we add links to Mozilla Website and Comms Terms of Service https://www.mozilla.org/en-US/about/legal/terms/mozilla/ and Privacy Policy https://www.mozilla.org/en-US/privacy/websites/ to a footer on our Discourse page?

**Comment by OpenMatt** [comment]
@ldecoursy and @simonwex will discuss next week

**Comment by ldecoursy** [comment]
@simonwex and I just chatted. Going to file separate tix in the devops repo to move the URL, add TOS to the footer, and gain access to the welcome/start guide copy. 

Closing this now.
