### ISSUE TITLE
Cassie needs more cookies

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#675]
I'm going to need a recipe from @vazquez 
I'm going to need some oven mitts from @simonwex

**Comment by vazquez** [comment]
I have a great family recipe!

**Comment by simonwex** [comment]
srsly y'all :+1:

**Comment by metaphorista** [comment]
These are the bomb  -- and guilt free --
http://www.theburlapbag.com/2012/07/2-ingredient-cookies-plus-the-mix-ins-of-your-choice/

**Comment by gideonthomas** [comment]
![giphy](https://cloud.githubusercontent.com/assets/5816130/12357539/615bf980-bb76-11e5-9184-8eb46c2561e9.gif)

**Comment by cassiemc** [comment]
@metaphorista Yum yum!
