### ISSUE TITLE
Clarify teams, DARCI and next steps towards MLN Q1 deliverables

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#677]
Working with @chrislarry33 on the next phase of MLN roadmapping, to include identifying teams/DARCI and Q1 priorities towards our H1 deliverables. 

Draft plan coming soon for feedback.

**Comment by edrushka** [comment]
I'm tracking my work here: #666 (ohh nice ticket number!)

**Comment by ldecoursy** [comment]
Making progress but still need a bit more time before we have something to share more broadly.

**Comment by hannahkane** [comment]
@ldecoursy - is this likely to close tomorrow?

**Comment by ldecoursy** [comment]
Nope. We've made progress identifying current work happening towards H1 goals, and have a better sense of what's happening in Q1 vs. Q2, but there are still a few bits of work that don't yet have owners - that's the next phase. I'm going to move this back a bit and remove P1 label for now.

**Comment by ldecoursy** [comment]
Link to latest doc is here: https://docs.google.com/document/d/17f716JYejkSJC1GO4asxkk0dvKw-A-cq7m9BfB_qeF4/edit

This includes the breakdown of work happening in Q1 and Q2 (but note this is a living doc that we'll update in early April as some work will certainly roll over into Q2). 

Let me know if you have any questions!

**Comment by hannahkane** [comment]
Wow, doc looks great. Lots of progress!

**Comment by ldecoursy** [comment]
Closing this ticket, however this will be a working doc we'll continue to update and reference throughout H1.
