### ISSUE TITLE
Visual/Design Resources for MSL's Working Open Workshop

### ISSUE THREAD

**Issue by zee-moz** [MozillaFoundation/plan#679]
At MSL we're planning for a series of upcoming workshops about Working Open for scientists, researchers, and study group leads.  

Here is our Working Open Workshop (WOW!) [planning repo](https://github.com/mozillascience/working-open-workshop) and [roadmap](https://github.com/mozillascience/working-open-workshop/blob/master/roadmap.md).
 
We'd like help on the following (understanding we likely won't hit our February deadline for the first workshop, as we are still in content production mode):

Ready for design now:
* some kind of MSL/WOW branded slide template for visuals for our short talks and presentations (could this be done in time for February?)
* some designed and attractive template for our handouts/tear sheets (print and digital versions)
Probably ready for design next week:
* some spot illustrations or diagrams/graphs for the handouts/tear sheets, or some strategy to make these materials visually appealing and less text-heavy

We plan to hold workshops in March/April and again in the Summer.

**Comment by cassiemc** [comment]
First event happening end of the first week of Feb in Berlin (the 5th?), but content for spot illustrations likely won't be ready by then. Is that right @zee-moz?

**Comment by zee-moz** [comment]
Workshop is Feb 6 & 7th.

We know [generally the content](https://github.com/mozillascience/working-open-workshop/blob/master/wow-schedule.md)-- building community, introducing your project to collaborators, roadmapping, codes of conduct, holding events etc. And we'll have more specific content by Jan 22. So if know the topic is roadmapping, could some sort evocative of illustration be created for that? Our new science fox could be put to use... 

We are giving short talks on about a half a dozen or more topics, and the talks come with handouts (print/digital) for activities which people work through in collaborative work sessions after the talk... So any way the handouts and slide decks can feel unified and be visually interesting... that would make a huge difference.

**Comment by cassiemc** [comment]
Thanks for more info here @zee-moz. I'll bring this up at design triage on Monday afternoon and see who might have cycles for it, if not this heartbeat then the next.

**Comment by cassiemc** [comment]
@zee-moz I'm going to assign this one to you for now. Will keep you posted on available resources!

**Comment by flukeout** [comment]
I'm interested in doing the spot illustrations and would like to understand the requirements a bit better. 

* How many illustrations?
* What are they about?
* Where and how will they be presented?

**Comment by cassiemc** [comment]
@zee-moz @flukeout I'm going to schedule a kickoff for this work so we can go through these questions and others in person. We're man-down this week with @vazquez off to Hive Buzz on Wed, so might need to bring in another designer mid-way through the heartbeat, but at least we can get started with a plan.

**Comment by flukeout** [comment]
:+1:

**Comment by zee-moz** [comment]
https://public.etherpad-mozilla.org/p/WOW-personas-pathways-handout

**Comment by cassiemc** [comment]
We had our kickoff and @flukeout is assigned design on this. Woot!

**Comment by OpenMatt** [comment]
status?

**Comment by cassiemc** [comment]
@zee-moz I believe the P1s are finished, with @flukeout having handed over assets to @acabunoc. Last thing to do is the P2 presentations template, which we're aiming to finish today, right?

**Comment by zee-moz** [comment]
yes! that's my understanding as well.

**Comment by flukeout** [comment]
Indeed!

**Comment by cassiemc** [comment]
Last bug... https://github.com/mozillascience/working-open-workshop/issues/12
