### ISSUE TITLE
Look at stats & gain better holistic understanding our audiences

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#680]
This is an important part of the research phase of the ```betterfaster``` plan. The overall objective is to have a better holistic understanding of our audiences (users) and our stakeholders. Potential results of this issue might be a

* Survey / staff questionnaire
*Note:* Let’s figure out if/how we want to do this. Seems like there are a lot of surveys in the works right now, and don’t want to create survey burnout.

**A start to a list of some questions to answer:*
* how are people using existing mofo properties? 
* what properties are missing? 
* how does branding affect needs?
* how does alignment with moco or mofo affect the needs of your program? ie. advocacy messaging on moco channels.
* inventory of tools / what people like, don’t like – David / Mw / Simon

Useful resource: Comms Inventory https://github.com/MozillaFoundation/plan/issues/678

**Comment by OpenMatt** [comment]
main next piece of work is getting access to Google Analytics data for these sites.

**Comment by cassiemc** [comment]
I'll drive but might lean on some designers and @adamlofting for a bit of help.

**Comment by cassiemc** [comment]
Let's try to complete the purple "Impact of Change on Audience" section in this doc: https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=2008361845

**Comment by adamlofting** [comment]
I've filled in all the data we/I have from Google Analytics . Some of the other sites might have their own GA which I don't have access too, but the big stuff is covered.

**Comment by jgmac1106** [comment]
There is also this issue:
https://github.com/mozilla/participation-org/issues/247 happening.

Thought I would share in case there is overlap.

**Comment by cassiemc** [comment]
Awesome, thanks a bunch @adamlofting. Thanks for pointing that out @jgmac1106

**Comment by cassiemc** [comment]
Left a bunch of comments for folks across Mofo to help fill in some of the gaps.

Here are some of the things I'm noticing.

* **I've highlighted our top website properties in yellow.** Webmaker.org at 150k monthly visitors was a surprise to me, and it might be worth considering how to better tap into that audience, or how we could potentially transition users to other properties. cc @adamlofting @xmatthewx  There are several social properties for WM that should be shut down / redirected.
* **Other top properties were teach.mozilla.org, Advocacy.mozilla.org, and Source**. Source has regular consistent publishing, so that doesn't surprise me, and I would venture to say that the teach and advocacy audiences are deep/super loyal, but I would need to dig into Source stats to say that wasn't true there too. Curious about bounce rates.
* **Lots of properties have no tracking**, which seems like an oversight, so I filed some tickets albeit it's reasonable to guess that those audiences are small.
* **Many of our blog properties have terrible numbers.** 200/mo for many, compared to a benchmark of newly launched blogs based on an individual's network that get 200/day, seems poor. Curious if we don't do a good enough job of cross-promoting content, if these properties aren't highlighted or a clear part of our comms strategies, if we get something less tangible from them, or if we really shouldn't be focusing on these (if we even currently are).
* **Our most popular tools are some of our most valuable assets, reach-wise**. 65k users for Thimble. 10k for Webmaker. Goggles has no tracking currently (Oops – filed https://github.com/mozilla/x-ray-goggles/issues/277). The latter is disappointing as we've made bets on this property based on how positively our community has received the tool, and it'd be nice to have stats that back this up. Wondering @hannahkane if anything like this exists for old Goggles?

I think there is another step to this research and we should dig deeper particularly on the top properties, email, and blogs.

We also need to continue filling out the design audit fields for the remaining properties / blogs. @kristinashu

**Comment by hannahkane** [comment]
Nice overview, @cassiemc.

Very curious to know more about that webmaker.org traffic—where are people arriving from, where are they landing, and what are they doing.

cc @Pomax to answer question about analytics on old Goggles.

**Comment by xmatthewx** [comment]
For the Webmaker site, we could investigate the top _meaningful_ referrers, identify strategic opportunities, and then adjust the MakerParty ad space (#749) without burning too much time and energy. We might also reach out to a few referrers to update their links (e.g. [awwwards code editors](http://www.awwwards.com/10-html-css-online-code-editors-for-web-developers.html)). 

While it's unfortunate to see this traffic leak away, I don't think recapturing it should be a top priority. We have new priorities that require new messages for new audiences.

**Comment by davidascher** [comment]
Happy to see this level of data & digging.  Keep going!

**Comment by adamlofting** [comment]
As

**Comment by adamlofting** [comment]
As a general rule across our properties. The most consistent source of traffic has historically been whatever we work on promoting on the mozilla.org homepage. This is a lever we can adjust to match our priorities and where we want to guide traffic. It's not sudden traffic like a snippet campaign, but it adds up over time.

> Wondering @hannahkane if anything like this exists for old Goggles? 

Interestingly, the old goggles page still accessible (but not promoted) at https://webmaker.org/goggles is still getting ~35k visits per month. I've added this into the spreadsheet.

**Comment by cassiemc** [comment]
I'll close this today and file followup issues.
