### ISSUE TITLE
[Jan 22-23] Run Hive Chicago Buzz

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#682]
[Hive Chicago Buzz] (http://www.hivechicagobuzz.org/) is Mofo's 3rd largest annual, public event. Now in its second year, the event is MozFest-inspired hack day with local participants. 

#### Goal
The goal of HCB is to create an environment where participants can activate and co-create solutions to transform the learning landscape with Chicago educators and youth.

#### DARCI
    Decider - Sam
    Accountable - Robert, Erika D.
    Responsibles (MoFo team + Event Implementation) – 
    ErikaD – Convenings Strategy 
    Sarah – Convenings Strategy
    Meghan – MoFo Strategy
    Hannah – Platform
    Ricardo – Platform
    Hana – Portfolio Strategy
    Janice – Portfolio Strategy
    An-Me – Web Literacy
    Aurelia – Cross-MLN Alignment
    Rafi Santo – Hive Research Plan
    Consulted - Chris, Meghan, Erica, Michelle
    Informed - MLN Team

#### More Information
This event [etherpad] (https://public.etherpad-mozilla.org/p/hcb16) contains links to all the details.

**Comment by omnignorant** [comment]
:heart_eyes: Thanks for posting here @edrushka :+1:

**Comment by edrushka** [comment]
Done! :balloon: :confetti_ball: :balloon: 
Read all about it here: http://hivechicago.org/hive-chicago-buzz-2016-recap/
