### ISSUE TITLE
Streamline footer designs

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#686]
Some design audit of footers across our web properties has already been happening in https://github.com/MozillaFoundation/Design/issues/42

In this issue we can take that a step further and implement some strategic changes. As part of this task we will need to identify which sites are in scope.

**Comment by kristinashu** [comment]
This is an easy win so lets go for it!

Footer will be on: 
- Science
- Learning
- Tools (goggles, thimble, webmaker)
- Fundraising
- Advocacy

Might be on:
- Coral project
- IoT
- Women

cc @hannahkane @sabrinang @xmatthewx

**Comment by kristinashu** [comment]
Planning is done, we will open a design ticket in the design repo to finalize the look.

@sabrinang please link design ticket here ones you have it

**Comment by hannahkane** [comment]
Note: fundraising might be an exception to this

**Comment by xmatthewx** [comment]
Note: 
 - Webmaker should leverage this as well. 
 - Thimble and other might utilize a minified version of this
