### ISSUE TITLE
Identify shared needs for blogs

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#687]
We can audit the existing blogs, find out what new ones need to be created, and generally get a better understanding of what is desired of Mofo's blogging platforms.

Related to https://github.com/MozillaFoundation/plan/issues/662

**Comment by cassiemc** [comment]
Note: There is a plan in the works from Jascha for having a Medium-like platform for Mozilla & contributors. @HPaulJohnson and @adamlofting might know more about that.

**Comment by adamlofting** [comment]
^ That is the extent of my knowledge on this topic :smile:

**Comment by hannahkane** [comment]
Summary of next steps:
 * Leading with Science blog -> this drives getting styles into Onesie
 * Follow up with Learning blog -> see https://github.com/mozilla/teach.mozilla.org/issues/1668
 * Other blogs (e.g. Research, Fundraising) may want to follow suit

**Comment by hannahkane** [comment]
This ticket is out-of-date at this point, so closing.
