### ISSUE TITLE
Streamline how we sunset

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#689]
Every sunset is gloriously different, but maybe it shouldn't be in Mofo-land.

Are there common tasks / pages / language / processes that need doing when we end-of-life something we've made, that probably still has users?

**Comment by KevZawacki** [comment]
My two cents, having played a part in the Popcorn / Appmaker / Gear Store sunsets:

-- Comms should play a large role. Our [comms plan](https://docs.google.com/document/d/1cZ6A-_eQf1go1C3WbhoDAMYjYcG2-k2UKpdn22TDYpg/edit) for the Gear Store sunset is a good template for future sunset work. 

-- There will be many moving parts, from site banners to internal emails to SUMO updates. So, all copy should exist in a single doc. 

-- We should set up an email (eg, gear@mozilla.org) for affected users and promote liberally during sunset comms. We should have it feed into Desk.com.

@cassiemc What are the next steps here. A sunset playbook? (Seems a bit superfluous.) Perhaps just circulating the knowledge that comms can/should help drive sunsets?

**Comment by hannahkane** [comment]
Closing, though we likely have some sunsets coming up, so this may become relevant again
