### ISSUE TITLE
Streamline shared needs for MLN initiatives

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#690]
This is a meta bug tracking:

- [ ] Theme for MLN initiatives: https://github.com/MozillaFoundation/plan/issues/643
- [ ] Gigabit redesign: https://github.com/MozillaFoundation/plan/issues/638
- [ ] Possible hive event sites or pages (related: https://github.com/MozillaFoundation/plan/issues/683)

Objective here will be to identify needs and design a series of templates and tech solutions that work for a variety of use cases.

Will add like issues as they arise. cc @hannahkane @simonwex

**Comment by hannahkane** [comment]
@cassiemc - I think we can close this ticket. Feels covered by other tickets.
