### ISSUE TITLE
Provide list of Mofo-owned URLs

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#691]
@simonwex and I spoke about pulling a list of existing urls that we own that we can compare against the Comms Inventory #678. Simon can you do this early next week?

cc @ldecoursy

**Comment by simonwex** [comment]
This is likely the most exhaustive list we have: https://docs.google.com/spreadsheets/d/1FbJ48mJ644yctfmIj7s4GfL4at1ySTrqV78EDlVujAM/edit#gid=0

**Comment by simonwex** [comment]
Cassie, I've got some time I can spend on this Friday (Tomorrow). Shall I just merge my list into the comms inventory?

**Comment by cassiemc** [comment]
@simonwex This list is great, all we need. I can have a look at merging the appropriate ones. Thanks!

**Comment by mmmavis** [comment]
Didn't see these two in the Overview tab in that Google Spreadsheet

- https://hivelearningnetworks.org/ 
- http://blog.webmaker.org/

Both are WP instances.

**Comment by cassiemc** [comment]
Thanks @mmmavis! I think those are covered in the [communications inventory doc](https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=0), which I'll use as the master. Feel free to review that and add anything that may be missing there...

**Comment by omnignorant** [comment]
wondering if domains we've purchased in Chicago should be added to this list, for example: http://hivechicagobuzz.org or http://ridewit.me

**Comment by cassiemc** [comment]
@omnignorant that would be awesome, can you add them?

**Comment by omnignorant** [comment]
@cassiemc I put that in the comms inventory right?

**Comment by cassiemc** [comment]
yes please, @omnignorant – right here: [communications inventory doc](https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=0) Wherever you think it makes sense, and the more columns you can fill out the better. Thanks so much!
