### ISSUE TITLE
Set Q1 goals for BetterFaster

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#693]
Let's tackle this in our kickoff, scheduled for this Friday.

cc @davidascher

**Comment by OpenMatt** [comment]
@cassiemc status? The kick-off was great. Did we get to a clear-ish set of next steps?

**Comment by cassiemc** [comment]
Kickoff notes are here: https://public.etherpad-mozilla.org/p/betterfaster

Q1 goals we discussed are:
* Present and approve an IA plan for Mofo properties
* Understand goals/strategies around tech improvements
  * Settle on technology for CMS / blogs
* Continue ongoing work
  * Make templates for curriculum guides `
  * Emails
* Let's implement a part of this plan, see if it works.
* Shared understanding of common vs. unique needs regarding "content" workflow and surface across MoFo, esp. across hubs

Are we agreed on these? If so we can close.

**Comment by cassiemc** [comment]
@OpenMatt @davidascher @simonwex @HPaulJohnson @hannahkane @xmatthewx @lovegushwa @ldecoursy  R? of the Q1 goals above? Anything to add / change before closing this issue?

**Comment by hannahkane** [comment]
Goals look good. Would love a written summary of what @simonwex shared after both @gvn and @mmmavis's demos today - about the use cases he sees each of those prototypes applying to.

Might add as part of this project that we need better processes for designating P1s (ideally something that takes into account available resources).

**Comment by ldecoursy** [comment]
+1 thanks @cassiemc!

**Comment by xmatthewx** [comment]
+1. +2 on the "shared understanding of common vs unique needs regarding content..." We have a lot to gain from a limited scope on the most common use cases.

**Comment by cassiemc** [comment]
Cool, I'll figure out how to document and share these in #699. Thanks all!
