### ISSUE TITLE
Setup a Thunderbird donation process

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/plan#696]
We want to be able to accept donations specifically for Thunderbird.  This bug will articulate the high-level goal and plan, especially as this will touch on a variety of topics from accounting to website and content.

Overall, the goal is to setup an infrastructure flow whereby the Thunderbird project can elicit donations that get managed specifically for Thunderbird needs. 

The first milestone will be to have a donation page with a similar flow to the general donation flow (Stripe & Paypal), which articulates the call for donations, and whatever systems are needed in the back-end to make the accounting of those funds straightforward.

Specific sub-tasks:

- [ ] understand what mofo accounting needs in the paypal/stripe donation data to identify restricted donations
- [ ] create a localizable page at donate.mozilla.org/thunderbird with copy & design TBD which lets potential donors understand why they would donate, and flow through our usual Stripe & Paypal flows. 
- [ ] create a mechanism with Exact Target whereby donors can opt-in to notifications about what Thunderbird is planning on doing with the money raised.

In the meanwhile, Angela and I will work with the Thunderbird folks to figure out the processes we need to determine who needs to draft the copy on that page for example.

@edrushka has agreed to PM this when she's back from Chicago, but it'd be good to get a staging setup working soon.

**Comment by simonwex** [comment]
Hey @ScottDowne, can you leave your thoughts here on what would need to be done? Specifically, the segmentation of funds as they will need to be used only for Thunderbird projects.

**Comment by ScottDowne** [comment]
This'll make a few people I know in Toronto happy :)

Anyway, my gut reaction is to put those funds in separate paypal/stripe accounts.

Swapping out the accounts is easy: https://github.com/mozilla/donate.mozilla.org/blob/master/sample.env#L5-L12

**Comment by davidascher** [comment]
Can we make sure we have the same terms on these new accounts?

**Comment by ScottDowne** [comment]
I'm poking around the internet looking for docs.

Some people report something in paypal about donation categories, but not able to find anything official on it. There docs are not the best so there might be something hidden. It's reported it doesn't work with recurring payments though.

https://www.paypal-community.com/t5/How-to-use-PayPal-Archive/Non-Profit-Multiple-Donation-Categories/td-p/35018
http://kb.dojiggy.com/questions/180/Can+I+earmark+funds+received+through+my+Donations+website+for+specific+programs+or+campaigns%3F

Pretty sketchy sources...

We already looked into a separate account for micro payments but didn't get it finished because of a lack of time.

I also think sending an email directly to paypal and stripe would be a good idea.

**Comment by simonwex** [comment]
@ScottDowne could you send that email?

**Comment by ScottDowne** [comment]
Done, both stripe and paypal said they would get back to us in 24 hours.

**Comment by edrushka** [comment]
@cassiemc I'll connect with you on the Jan 29 TPS call. We can look at assigning design resources for the following heartbeat.

**Comment by cassiemc** [comment]
@edrushka – sounds good. Sorry for the confusing notifications, I was playing with this issue for the Github training. :)

**Comment by simonwex** [comment]
@alicoding I'm going to need you to do the work on this. @ScottDowne thanks for doing the research on this one, could you fill in the details on the forking approach we discussed?

**Comment by alicoding** [comment]
@ScottDowne can you fill in the details on what they've respond to you on the email (PayPal & Stripe) ?

**Comment by ScottDowne** [comment]
Nothing super useful yet, they both basically responded as if it's not a common usecase, by either directly saying it's never been requested, or responding as if I asked something else.

I've been going back and forth with them for a few days. It's ongoing.

Stripe mention that you could link two accounts to one, and easily manage them from one dashboard, but wasn't specific. I can only assume they can both be setup to send the funds to separate bank accounts, otherwise it would be pretty pointless, but they were not specific.

PayPal rambled on about something called a reserve and savings. I think they got confused. I'm now being more specific.

Also, I have a question for @simonwex @edrushka or @davidascher, whoever can help. What would be ideal for us? The funds initially go into a single stripe or paypal account, and are somehow flagged or tagged for thunderbird or generic usage. From here it's easy for us (or automatic) to move those funds into a specific bank account separate from each other?

**Comment by alicoding** [comment]
My thinking on this is also to setup this thunderbird donation page under the same repo for [donate.mozilla.org](https://github.com/mozilla/donate.mozilla.org) as long as it doesn't interfere with the current donation flow. The benefit of doing this would be:

1. Don't have to setup another SSL
2. Same domain
3. Solving most of the server scalability and load balancing issue 

I'm sure there are more, but these are the things that's currently in my mind.

Thoughts @simonwex @ScottDowne @jbuck ?

**Comment by ScottDowne** [comment]
I don't have a grasp as to how hard 1 and 3 would be, so I'll let others weigh in.

My only goal for having a fork was less moving parts. Nothing too critical.

**Comment by jbuck** [comment]
I would also like to hear from accounting to see what needs to be done before we move forward on a solution, but I'd generally agree with standing up a new page on our existing codebase, rather than forking it specifically for thunderbird donations.

**Comment by davidascher** [comment]
I think all we need is to be able to do reports that tell us what $ came
from Thunderbird-specific pages. We can do that by filtering based on
source URL if that's easier.

**Comment by ScottDowne** [comment]
For what it's worth stripe allows you to link another account to one, and switch between them in the dashboard. The money can go into separate bank accounts, and they'll have separate api keys. So Stripe is kinda covered, actually.

@davidascher where would we do the filtering? In our analytics maybe?

**Comment by cassiemc** [comment]
Is this for the next heartbeat [Feb 12]? What design is needed here?

**Comment by edrushka** [comment]
@cassiemc I think we'll need a bit of design help here, but it will be minimal. We'll more or less clone the existing donation flow, so the design work will be adding a logo and maybe changing the colour palette to make it look more 'Thunderbird'. I anticipate the designer will be needed towards the end of the Feb 12 heartbea. I'll file specific tickets for that work.

**Comment by edrushka** [comment]
Moving this work to the donate repo.

Copy ticket: https://github.com/mozilla/donate.mozilla.org/issues/1280
Build tickets: https://github.com/mozilla/donate.mozilla.org/issues/1281 and https://github.com/mozilla/donate.mozilla.org/issues/1282
Design tickets: https://github.com/mozilla/donate.mozilla.org/issues/1283 and https://github.com/mozilla/donate.mozilla.org/issues/1285

**Comment by gerv** [comment]
In the initial discussions of this feature, @davidascher also mentioned the ability for people donating to sign up for a low-traffic notification mailing list. Is that still in scope?

**Comment by davidascher** [comment]
Yeah I'd forgotten that bit. @edrushka I'm thinking for now we just setup a
list in exact Target and we can manage that tool to send messages that will
be conveyed by the Thunderbird point of contact. Seems reasonable given
that it'll be low frequency?

**Comment by gerv** [comment]
WFM.

**Comment by edrushka** [comment]
Exact Target ticket filed here: https://github.com/mozilla/donate.mozilla.org/issues/1289

**Comment by edrushka** [comment]
@alicoding @ScottDowne please note that this got upgraded to a P1. We did this with @simonwex on the TPS call.

**Comment by alicoding** [comment]
Encryption first then this one, correct?

**Comment by edrushka** [comment]
Yes. Encryption has priority over this.

**Comment by cassiemc** [comment]
I'd like @vazquez to add this to his list (noting it's a P1, and should be prioritized over CMS or Mattermoz work). 

@edrushka – he'll be on PTO this Friday the 5th and Monday the 8th, does that timing still work?

**Comment by edrushka** [comment]
Yes, that timing should work. @gerv - do you have an eta for the final copy? That will dictate any font size/spacing changes we need to make on the forms.

**Comment by gerv** [comment]
Wow, you guys work fast. No, no ETA on final copy. Not even sure who in the TB community is working with me on it yet! They don't move as quick as you do. I'll poke them.

**Comment by simonwex** [comment]
Moving this to our next Heartbeat. @gerv do you have an update from your end?

**Comment by gerv** [comment]
@simonwex: the work is going on in the copy ticket, mozilla/donate.mozilla.org#1280.

**Comment by OpenMatt** [comment]
@edrushka can you list final dev tasks required to close?

**Comment by edrushka** [comment]
All thunderbird tickets are tracked here: https://github.com/mozilla/donate.mozilla.org/issues?q=is%3Aopen+is%3Aissue+label%3AThunderbird

**Comment by OpenMatt** [comment]
moving to p2 as per @simonwex

**Comment by edrushka** [comment]
Just clarifying that the 'Status: At risk' label simply means we won't finish this piece of work this heartbeat, not that the overall project is at risk.

**Comment by vazquez** [comment]
We designed this feature in the browser for speed. Here are screenshots of the latest progress:

### Simple Layout
![simple](https://cloud.githubusercontent.com/assets/1119821/13359668/6cd90f72-dc83-11e5-8700-cad3ff91948f.png)

### With Context Layout
![about](https://cloud.githubusercontent.com/assets/1119821/13359681/782c5244-dc83-11e5-962f-0e7babca8de1.png)

**Comment by davidascher** [comment]
In second layout, I'd add the wordmark to the right of the icon.

**Comment by vazquez** [comment]
@davidascher Done :+1:

**Comment by edrushka** [comment]
Update -  just finishing up the final details:
- getting the Mailchimp account hooked up
- proper text in the thank you email.

Almost done!

**Comment by edrushka** [comment]
There are a few bits and pieces that need tweaking, but this has shipped! 

https://donate.mozilla.org/en-US/thunderbird/

Please file any follow-up tickets here: https://github.com/mozilla/donate.mozilla.org/issues/new

Thanks so much to everyone that helped on this!
