### ISSUE TITLE
Cassie needs more cookies

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#698]
- [ ] research cookie recipes
- [ ] secure ingredients
- [ ] bake bake bake
- [ ] eat

:cookie:

**Comment by acabunoc** [comment]
:mailbox: :cookie:

**Comment by kaythaney** [comment]
:yum:

**Comment by kaythaney** [comment]
@acabunoc and @kaythaney also like cookies.

**Comment by lovegushwa** [comment]
:cookie:  :cookie:  :cookie:  :cookie:

**Comment by samueledyson** [comment]
Nom nom

**Comment by acabunoc** [comment]
:cookie:

**Comment by kaythaney** [comment]
@samueledyson what sort of cookies do you like? do you bake?

**Comment by cassiemc** [comment]
@vazquez I heard you have an awesome recipe.

**Comment by samueledyson** [comment]
Oatmeal raisin with white chocolate.  Never made that, but might have to now.

**Comment by kaythaney** [comment]
now, am hungry. :(

On Tue, Jan 19, 2016 at 2:51 PM, Sam Dyson <notifications@github.com> wrote:

> Oatmeal raisin with white chocolate. Never made that, but might have to
> now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/plan/issues/698#issuecomment-172966197>
> .
>



--  [[unflagged]](http://plzkthx.herokuapp.com)
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by CaptainCalliope** [comment]
I really really really like the Fudge Ecstasies from page 7 of [Diana Keuilian's '21 Healthy Treat Substitutes'](http://www.realhealthyrecipes.com/fffbmdownloads/21%20Healthy%20Treat%20Substitutions.pdf).

**Comment by cassiemc** [comment]
Thanks @CaptainCalliope I think you solved this bug :)
