### ISSUE TITLE
Internal comms strategy for sharing finished work

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#699]
How do we socialize work that has been relegated as important, is in progress, or gets finished – how do people then use it? For devs & designers, how do we talk about and learn from this process?

One good idea:
* make it easy for people to find the resulting pool of resources

cc @lovegushwa if you want to add any thoughts.

**Comment by cassiemc** [comment]
@OpenMatt my thought is we should work together on this. I can own it if you'd like.

**Comment by cassiemc** [comment]
Let's include this in our first share-out: https://github.com/MozillaFoundation/plan/issues/693

**Comment by cassiemc** [comment]
Am thinking to start with a wrap up email at the end of every heartbeat. I'll with one intro to the better/faster initiative, links to resources, and high-level status updates on the CMS / Calypso activity, IA plans and design audit, + any other in-progress better/faster bugs (will need to look). 

@OpenMatt is it helpful if I put this together? I can send this on Friday or Monday.

**Comment by cassiemc** [comment]
Here's the outline I'm thinking for an email I'd like to sent to all@mofo Tues 16th (Monday is Family Day in ON). Suspect I will need to update this after a meeting with @hannahkane @simonwex in a bit.

* **[What is Better/Faster](https://github.com/MozillaFoundation/plan/issues?utf8=%E2%9C%93&q=label%3Abetterfaster+)**
 - Overview
 - [Q1 goals](https://github.com/MozillaFoundation/plan/issues/693)
* **[What’s already happened](https://github.com/MozillaFoundation/plan/issues?q=label%3Abetterfaster+is%3Aclosed)**
 - [Communications Inventory](https://github.com/MozillaFoundation/plan/issues/678)
 - [Mofo Design Audit](https://github.com/MozillaFoundation/plan/issues/681) (closing Feb 12)
 - [Inventory of things made by our network](https://github.com/MozillaFoundation/plan/issues/705) (closing Feb 12)
 - [Plan for creating 'Convening' templates](https://github.com/MozillaFoundation/plan/issues/683) (closing Feb 12)
* **[What’s happening this heartbeat – Feb 26](https://github.com/MozillaFoundation/plan/issues?q=label%3Abetterfaster+milestone%3A%22February+26%22)**
 - Continue [Calypso / CMS experiment](https://github.com/MozillaFoundation/plan/issues/716)
 - [Trial move from IRC to Mattermoz](https://github.com/MozillaFoundation/plan/issues/712)
 - Communications plan – will probably leave this to @samanthaburton to publicize separately but let me know if I can help
 - Guides – Science & Teach
 - Style guide for teach.mozilla.org
* **What’s happening next (TBD by heartbeat planning tomorrow)**
 - Look at audiences / stats to understand change impact
 - Email audit
 - [IA for Leadership/Advocacy properties](https://github.com/MozillaFoundation/plan/issues/661)
 - Beginning the Science site redesign
 - Possibly Convenings templates
* **Where to find resources / get involved**
 - Link to better/faster tickets in Plan
 - How to fork Science curriculum templates
 - How to fork Teaching templates
 - Design resources (UX, UI, annotation templates, styleguides)
 - Have an idea? File it & label better-faster

Obviously this is an outline and not the email itself, which I'll try to make as digestible as possible. Might choose to hold on talking about some of these things, but this is currently everything I'm aware of.

@xmatthewx @ldecoursy @davidascher @OpenMatt @edrushka @samanthaburton @HPaulJohnson @simonwex @hannahkane Is there anything you'd like to add or adjust?

**Comment by edrushka** [comment]
Looks good to me, Cassie!

**Comment by OpenMatt** [comment]
@cassiemc I think this is great, and timing is great. Staff meeting happening Feb 17, so that will be a chance for us to link to some of this from the agenda as well.

**Comment by OpenMatt** [comment]
@cassiemc note also that we are hiring a new internal comms person soon that should be able to provide additional help on issues like these.

**Comment by cassiemc** [comment]
Sounds good, thanks @OpenMatt. Will update this bug after TPS today.

**Comment by samanthaburton** [comment]
Looks good @cassiemc! Thanks for including the comms piece.
RE: internal comms for 2020 business plan - filed as ticket #729 & will likely be sharing more detail at the Feb 17 staff meeting

**Comment by cassiemc** [comment]
Rolling this over to make sure I send it on Feb 16.

**Comment by cassiemc** [comment]
Sent!
