### ISSUE TITLE
Ship google docs template + board slides

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#702]
From @msurman:

Is there someone on the design team who could help develop a simple MoFO google docs template this week or early next (by Tuesday?).

The goal would be to have something like the template we're now using for board slides, but for strategic planning docs, reports, grant proposals. It would be subtle but have a similar feel, be easy to use (style sheets!) and keep us consistent. See below for more.

The doc we'd want to use as a test case is this:

https://docs.google.com/document/d/1BlC4sCtgTCzT60z0pRMjZdHjS4s10gUOWgy28vAHDX0/edit#

... which is what we'd want to pretty up / do style sheets and footers etc on by Tuesday. We could refine into a re-usable template from there.

**Comment by cassiemc** [comment]
@vazquez says he can help on this today and tomorrow. Woohoo, thanks Ricardo!

**Comment by msurman** [comment]
Ricardo: let me know if you want to chat through quickly. I'm in the office all day today and tomorrow.

**Comment by vazquez** [comment]
Thanks @msurman! I will take you up on that offer. In the meantime, I have requested access to the Google Doc

**Comment by cassiemc** [comment]
Let's take stock of what templates we already have available. If there is a smart way to build on these (rather than redesign similar elements, except where necessary b/c of a different audience, etc) let's do it. I added [a folder of these](https://drive.google.com/a/mozilla.com/folderview?id=0BzfN9sXlOXt1THlmZVBIRDhZRFE&usp=sharing) on the Design Assets drive.
* Board templates (not actually sure where this lives, @flukeout @lovegushwa ?)
* [Mozfest presenter templates](https://docs.google.com/a/mozilla.com/presentation/d/1ce0FxNJ1XnBbT6ZECdEJ1St87u86PL5kByBXohrSAE4/edit?usp=sharing)
* Mozilla templates (from Tim Murray's team): [Red](https://docs.google.com/presentation/d/1CG5eZqDiGqk31NywA0maXt5CE815MZbt4msl5KfntfE/edit#slide=id.ga39cad493_0_10), [Grey](https://docs.google.com/a/mozilla.com/presentation/d/1SSiFUfaHMRpezC_F8BDLKAIq59O4647G3uiiJdoydHs/edit?usp=sharing), [Dark blue](https://docs.google.com/a/mozilla.com/presentation/d/1M2kiP9FcMMYKNErLz90sUlh6g4Qa9GFhfqXgZ5LaVfY/edit?usp=sharing), [Blue](https://docs.google.com/a/mozilla.com/presentation/d/1OKEoa_RWBGMxPfPs32cjB9R3SgYvhURNCcahLTVcI-s/edit?usp=sharing)
* Science lab templates [in-progress here](https://github.com/mozillascience/working-open-workshop/issues/12) (will be finalized today and tomorrow)

Any others you guys know about? @sabrinang @kristinashu @natalieworth @lovegushwa @flukeout

**Comment by vazquez** [comment]
Thanks! This is what I've been digging for as well. The 2020 Strategy slides are available here:

https://docs.google.com/presentation/d/1yPhg7ilRgAjHn41w3jGjvTzcEOCknBh8YaUq0gOc7rg/edit?usp=sharing

**Comment by msurman** [comment]
Shared both the slides and doc. Jordan did the work behind the slides, I think, if you want to know about thinking behind them.

**Comment by vazquez** [comment]
I would love to spend a few minutes with @msurman or @OpenMatt to talk about the Doc and how we can begin making the transition into a slide format.

**Comment by lovegushwa** [comment]
(I sent these to you @vazquez earlier today)

Here is Luke's template: looks like some one messed up the first few slides:
https://docs.google.com/a/mozilla.com/presentation/d/1iNKTFP-h6TJAWbHuAb5T1zkiIcZnxrdeYqcI9GwxuOc/edit?usp=sharin

Presentation poster files are here: https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvODBPVko4WG1aOGM/view?usp=sharing

**Comment by OpenMatt** [comment]
* @vazquez I just scheduled a meeting w. you to discuss the slides
* instead of using the template links @lovegushwa shared, we can just have you work directly on the board slides themselves: https://docs.google.com/presentation/d/1GSAw7cYggWRQ22NaOGja9sJYLgHdjhWrfvkGRAZCs1s/edit#slide=id.g108c3afb22_1_91
* we can review the individual slides that need design work together in our meeting, but go ahead and take a look now.

**Comment by OpenMatt** [comment]
#### Deliverables
* 1) Slides
* 2) KPI document 
* 3) Business Plan (Updated version 0.9)
* 4) Board Book title pages 

@vazquez I will add links for all of the above

**Comment by OpenMatt** [comment]
@vazquez links added for all of the above

**Comment by OpenMatt** [comment]
Thanks for all your great work on this @vazquez ! I think we're done.
