### ISSUE TITLE
Finalize reqs / get team up to speed on mozillascience.org refresh

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/plan#704]
This issue is taking a stab at the first phase of a design refresh of mozillascience.org (WIP)

**problem**
mozillascience.org was created when Mozilla Science was a very different program. Since then, we've added several offerings (fellows, study groups, more), some of which are represented on the website, but difficult to get to.

**main goals**
creating an *easy to navigate* site with *clear ways to get involved*

We're particularly eager to update:

1. our [home page](https://mozillascience.org/) and 
2. [/training](https://mozillascience.org/training) page
  * Can we fold in some of the learning resources @zee-moz & @stephwright are generating

**Full design brief**
*note: this brief is for a much larger piece of design work. However, the personas and user stories may be helpful*
https://docs.google.com/a/mozilla.com/document/d/1Z2jNumwfLM0d4cgpeF5-N-mEwiGmcWYo4NXHIUIXr7w/edit?usp=sharing

cc: @kaythaney @cassiemc 

DARCI TBD...
D: @hannahkane ?
A: ?
R: @kristinashu 
C: ?
I: ?

**Comment by cassiemc** [comment]
Thanks for filing @acabunoc! Added it to this milestone but we can discuss whether it would fit better this heartbeat or next. Ideally I'd love to start with a small brand exploration exercise. Your [pinterest board](https://www.pinterest.com/aure_moser/website/) is great so whenever we have a kickoff we can use that to talk about next steps.

**Comment by acabunoc** [comment]
Brand exploration sounds great -- Looping in @auremoser who make the moodboard :)

**Comment by auremoser** [comment]
Oh thanks @acabunoc ! let me know if you need any clarifications @cassiemc, I love making moodboards, and would be happy to participate in the exercises.

**Comment by cassiemc** [comment]
@kristinashu should be able to help with design/moodboard/exploration this heartbeat. Also had a brief chat with @hannahkane today and she might be willing to PM this. I'll schedule a kickoff and we can all agree on a scope and roles for this heartbeat. 

@acabunoc who from your team needs to attend, other than yourself?

**Comment by hannahkane** [comment]
I'd be excited to PM this, if that role is needed. Will attend the kickoff.

**Comment by acabunoc** [comment]
Hey all, the team is work week-ing and running workshops in Berlin this week -- might be tough to schedule a kickoff soon (sorry!)

**Comment by cassiemc** [comment]
I've rescheduled for next week.

**Comment by cassiemc** [comment]
Sorry to reschedule again, but seeing that Monday Feb 8 is a BC holiday, we'd only have a bit of @kristinashu's time next week anyway, so I think it would be better to start fresh with the next heartbeat. Any objections to this plan @acabunoc @hannahkane ?

**Comment by acabunoc** [comment]
That works better for me, too! No objections here :)

**Comment by cassiemc** [comment]
If @hannahkane can drive this, does it make sense for you to dev @acabunoc? If so, we can remove the 'needs dev' label. cc @simonwex

**Comment by acabunoc** [comment]
Can we clarify the scope on this first? Maybe when we meet next week?

I was hoping to interface with the design team like I would an external agency. I'm happy to take on dev work in the short term, but I think we'll definitely need help past phase 1. I do want to be involved on the development side, but we just launched a mentorship program that will take a significant amount of my time.

Let me know if that makes sense -- happy to talk more when we meet @cassiemc, @hannahkane @simonwex

**Comment by OpenMatt** [comment]
@cassiemc @simonwex are we planning to take a more templated / reusable approach to this site, as opposed to custom one-off, in the spirit of betterfaster?

**Comment by hannahkane** [comment]
@OpenMatt, yes, @simonwex @cassiemc and I discussed yesterday, and this is a candidate for the CMS project, but we're going to take a heartbeat to prep this project and then revisit at the end of the heartbeat to see where we are. In the meantime, we'll be prototyping other projects with Calypso.

**Comment by hannahkane** [comment]
Had a kick-off meeting today:
 * [Notes](https://public.etherpad-mozilla.org/p/mozsciencekickoff)

Filed tickets capturing deliverables for this heartbeat:
 * [Collect community input on IA](https://github.com/mozillascience/site/issues/81)
 * [Iterate on moodboard](https://github.com/mozillascience/site/issues/80)
 * [Finalize content for About page](https://github.com/mozillascience/site/issues/82)
 * [Wireframes for About page](https://github.com/mozillascience/site/issues/83)

**Comment by hannahkane** [comment]
Changing focus from About page to Homepage. Had a meeting this morning to discuss requirements. Subscribe to https://github.com/mozillascience/site/issues/86 to follow along. 

IA, moodboard, and community input are all in progress.

**Comment by hannahkane** [comment]
This ticket is feeling out-of-date. I'm going to close and open up new ones, more reflective of what we're working on now.

**Comment by hannahkane** [comment]
Note: I think we did achieve the milestone goal of getting the production team for this project up-to-date and defining the work to be done. But...more detailed tickets to follow.
