### ISSUE TITLE
Inventory things created by our network

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#705]
An effective Mozilla network should yield leaders who shape the internet through innovative or impactful "artifacts" that align with Mozilla’s principles and priorities. Artifacts, products, or creations – these include campaigns, software, legislation, reports, think pieces, tools, and curricula released to the world.

#### **Problem**
We don't have a comprehensive view of things created by network members that cuts across programs and events. Our members don't have a view of what other members create outside their niche. 

#### **Task**
Take inventory of 2015. Do this as a prototype for capturing 2016 as it happens. Discuss with staff and network members to explore the relationship between a creation and the network. *Does the network know about it or utilize it? Did the network contribute toward its creation?*

#### **Goal**
**This heartbeat**: better understand what the network creates and how the network enables that work. **Long-term**: Amplify the best work of our members. Foster collaboration, prototypes, and innovation created across the network. Contribute toward @adamlofting's network strength indicator.  

#### **Deliverable**
Report on the findings. Build a simple method to gather, store, and share info about the artifacts. 

Driver: @xmatthewx
Consulted: @adamlofting, fellowships, hive cities, etc

**Comment by OpenMatt** [comment]
Other threads we want to potentially connect:
1) Simon's "Planet MLN" prototype
2) Shared curriculum database

**Comment by edrushka** [comment]
Curious what you envision for the final "report". Is this something static and printed like Laura DR does? Or something web-based with links to the "things"?

**Comment by adamlofting** [comment]
If this `inventory` becomes an `artifact` in itself, let's put aside some future time to think about promotion and integration into network working practices. I.e. How does the inventory feed then network and vice versa.

**Comment by omnignorant** [comment]
super interested in this! let me know how I might support. I'm particularly curious about the participation `pathways` or enabling conditions (`resources`) that lead to each `artifact`

**Comment by edrushka** [comment]
As an easily digestible, public "report", this is an interesting format: https://ca.warbyparker.com/year-in-review-2014 via @benrito

**Comment by benrito** [comment]
@xmatthewx we're a similar inventory of research + issues, see for instance: https://docs.google.com/spreadsheets/d/1AmAufOHeo7akmfZlzD0e7_tmQBzk6DNVO5pI3fNcNZU/edit#gid=227852233

Can we get together to share notes? Would love to co-develop a single inventory.

**Comment by OpenMatt** [comment]
@xmatthewx status?

**Comment by xmatthewx** [comment]
What do Agate, Flexbox Froggy, and Command Line bootcamp have in common? Wouldn't we all like to know?

Good progress on this. I've completed a range of conversations with staff and built a light-weight prototype. I will pull together a summary of observations and recommendations as conversations continue next week.  

I'll bump this ticket to next heartbeat with plans to close it and file followup up.

**Comment by hannahkane** [comment]
@xmatthewx - wasn't sure whether to label this with production or program label. (or both!)

**Comment by cassiemc** [comment]
@xmatthewx Why remove the better-faster label?

**Comment by xmatthewx** [comment]
Wasn't  intentional @cassiemc. In transit now and can't add it back. Nice work on the email update!

**Comment by xmatthewx** [comment]
This first phase of work is done. It'd be great to get feedback from this group on my [observations and recommendations](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.1jw5xbbg838).

Check out the [Prototype inventory stream](http://xmatthewx.github.io/network-pulse/), and see the breadth of things created by peers in the network. Contribute to the WIP [precedents deck](https://docs.google.com/presentation/d/10QvAb_utE6KXgIucuQiJ65NW3frmq85XTBgo76r_AvY/edit#slide=id.gef9484f12_0_0) and help answer the question: _How can we best capture, share, and amplify the work by our network?_

**Comment by xmatthewx** [comment]
I invite everyone to capture the story February in the prototype (shout out to @bhuvanshri for the idea), adding anything made by us or members (reports, software, campaigns, etc). Works-in-progress welcome. 

[<img width="1296" alt="screenshot 2016-02-25 16 48 35" src="https://cloud.githubusercontent.com/assets/53411/13335546/a401c2f4-dbdf-11e5-969b-39100ea17000.png">](http://xmatthewx.github.io/network-pulse/)
