### ISSUE TITLE
APP: Complete publishing & contacts UI for Webmaker App

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#71]
Completion of the publishing flow as per spec for the Webmaker App. Includes building an SMS contact list view using the "contacts" API via Cordova.

Phase: Build / Ship
Owner: @k88hudson
Decision: @thisandagain
Lead design: n/a
Lead dev: @gvn 
Quality: @thisandagain 

*Edit by @k88hudson:*
Tickets here: https://github.com/mozilla/webmaker-app/milestones/Publishing%20&%20Contacts%20UI%20

**Comment by cassiemc** [comment]
Wondering if @thisandagain can cover quality on this issue, to give myself a bit more breathing room this heartbeat?

**Comment by thisandagain** [comment]
Sure. I can take it @cassiemc

**Comment by thisandagain** [comment]
We got through quite a bit of this. Remainder moved to https://github.com/MozillaFoundation/plan/issues/49
