### ISSUE TITLE
Thimble: Transition fully from thimble.webmaker.org to thimble.mozilla.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#711]
After localization we're ready to transition fully off of https://thimble.webmaker.org

Tracking milestone here: https://github.com/mozilla/thimble.webmaker.org/milestones/Erase%20Technical%20Debt,%20Deprecate%20oldthimble.

**Comment by OpenMatt** [comment]
@simonwex size estimate?

**Comment by hannahkane** [comment]
Moving this to current heartbeat

**Comment by hannahkane** [comment]
Rolling this to current heartbeat

**Comment by xmatthewx** [comment]
depends on these dev-ops tasks: https://github.com/MozillaFoundation/mofo-devops/issues/302

**Comment by cadecairos** [comment]
@hannahkane Any thoughts on how much design effort we might want to put into a deprecation landing page for thimble.webmaker.org?

My simple suggestion would be to explain that Webmaker Thimble has been shut down as of <date of shutdown> and that all projects will be migrated to the new Thimble app in <TBD amount of time>, where they can be republished. 

It could also be noted that makes.org makes will remain available. (for ever? we're paying a lot of money for that wildcard makes.org certificate.)

**Comment by hannahkane** [comment]
Wondering if it makes sense to use the same design elements from http://popcorn.webmaker.org/, but change the message, as you described. @flukeout - does that sound ok to you?

Flagging @ldecoursy and @KevZawacki to help with messaging considerations.

**Comment by KevZawacki** [comment]
+ @KGorr 

Happy to help. Sounds like something that should be communicated via:

-- MozTeach newsletter
-- @MozTeach
-- blog.webmaker.org
-- Discourse

Most effective might be an email to active users. Do we have that capability?

**Comment by flukeout** [comment]
@hannahkane I think we'd need to change the branding and feel of that page to match Thimble, as it's very webmaker-app focused. I don't expect most of our thimble users to be familiar with that look and feel. I don't think it would be a lot of work though, we can change the background color and put a Thimble logo in there somewhere.

I don't fully understand the process of how people would migrate their work over to the new Thimble though. Is there a process for that and what does it look like from a user's perspective - it might inform our approach to this page.

**Comment by KGorr** [comment]
@KevZawacki & all - happy to help however I can!

**Comment by hannahkane** [comment]
thanks, all. I could also use some clarity on the migration process. @cadecairos - can you shed some light on how it will work?

**Comment by cadecairos** [comment]
@hannahkane I've put some details in this issue: https://github.com/MozillaFoundation/mofo-devops/issues/302

I can clarify more tomorrow if you need more details.

**Comment by cadecairos** [comment]
I'd like to wrap up this work this heartbeat if possible. If I can get a standalone HTML page, I can deploy it and start redirecting thimble traffic, and get started on the migration of project data.

**Comment by hannahkane** [comment]
Moving to June 3 heartbeat to reflect devops triage.

**Comment by hannahkane** [comment]
Moving to July 1 heartbeat, as per earlier discussion.

**Comment by hannahkane** [comment]
Closing this, as it's DONE!
