### ISSUE TITLE
Release beta of Mattermoz instance to engineers and designers

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#712]
Follow-on from #662

We have staging and production Mattermost instances running. We've contributed upstream some basic fixes and features we deemed important to the adoption of Mattermost for MoFo. We're going to trial its use as an IRC replacement and central communication channel with our engineers and designers.

During this Heartbeat we'll also build the tooling to redirect users from existing channels and replace mentions of IRC with mattermoz.

@cassiemc, we may need some light design help fixing any UI/UX issues we discover during this process. Could you suggest someone who has a few spare cycles over the next couple weeks?

**Comment by cassiemc** [comment]
@vazquez Can you and @my-le help with this as needed?

**Comment by vazquez** [comment]
Sure thing :)

**Comment by simonwex** [comment]
Kickoff scheduled for Wed, February 3, 12:30pm – 1:30pm PDT - Sorry about the timing, @alanmoo

**Comment by cassiemc** [comment]
Just noting this may end up a P2 for @vazquez b/c of Thunderbird work kicking off next week. If we can push forward on stuff this week we might be able to get further on it this heartbeat.

**Comment by simonwex** [comment]
Our trial is underway and issues are being filed. 

Here's the email that was sent out to design and eng:

> Hey y'all!
> 
> It's my pleasure to invite you to our beta of Mattermost! Mattermost is an open source implementation of Slack. We're contributing to the project to make it easier to host, easier to localize and better suited for our needs of community communication.
> 
> Our goal is to eventually replace IRC and provide a more friendly way for contributors and non-technical paid staff to join the conversation.
> 
> Please create an account using this link:
> 
> https://mzl.la/chat
> 
> Once you're in:
> Add an avatar
> Say, "hello". –  with a gif in off-topic
> Create any channels you need to have effective discussions with your teammates
> Try to guinea pig this instead of using IRC. – If you don't prefer it, think about why and give feedback
> 
> We value and need your input! Please create issues here: https://github.com/mozilla/mattermoz/issues as well as discuss the meta in the "mattermoz-development" channel. Feel free to reach out to me if you have any questions.
> 
> See you there!
> 

If those in the TPS group would like to join the conversation, feel free! You can use the instructions above.

**Comment by xmatthewx** [comment]
works great @simonwex

**Comment by simonwex** [comment]
![image](https://cloud.githubusercontent.com/assets/25260/13000216/8ffc2a0c-d10c-11e5-9fd6-a3e9988c13d6.png)

![image](https://cloud.githubusercontent.com/assets/25260/13000222/985be3f4-d10c-11e5-9a96-ae453dc66330.png)

**Comment by simonwex** [comment]
Thanks @xmatthewx! We're happy with it so far. I think the next HB should be about collecting feedback and planning any changes required before we invite the rest of the org.
