### ISSUE TITLE
Create new YouTube account for MLN-Ed Hub

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#715]
We need to create YouTube channel for hosting Google Hangouts on Air for new, regular community calls and curriculum development workshops kicking off in March. 

@simonwex offered to help due to issues with YouTube and our enterprise google apps setup.

**Comment by ldecoursy** [comment]
Pinging @simonwex to see if you've heard back about setting this up. Or is there another option we should look into for the short-term?

**Comment by simonwex** [comment]
hey @ldecoursy, if IT hasn't figured out how to enable our accounts by tomorrow, let's create them under separate gmail accounts and have the master details in our vault.

**Comment by hannahkane** [comment]
Moving this ticket to the current milestone

**Comment by ldecoursy** [comment]
I think @simonwex got close to this on Friday, however not sure it was fully resolved.

**Comment by ldecoursy** [comment]
@simonwex Any update on this for the long term? We created a separate gmail account for the meantime.

**Comment by cassiemc** [comment]
@ldecoursy Curious what the plan is for naming the account?

**Comment by ldecoursy** [comment]
MozillaLearning - this is where we'll host the Mozilla Learning Community Call and @chadsansing's Curriculum Workshop.

**Comment by cassiemc** [comment]
Might it make sense to use the same name as twitter, @mozteach? So it creates some level of consistency between now and when we can complete the naming exercise #741. Can account name be easily changed later?

**Comment by ldecoursy** [comment]
The account was already created - I think it's still consistent with what you see when you arrive at teach.mozilla.org and what the formal @mozteach twitter account name is.

**Comment by cassiemc** [comment]
Cool thanks @ldecoursy

**Comment by simonwex** [comment]
@ldecoursy update on long-term: IT has to enable youtube, sites, google plus and a few other features for all mofo staff. They're looking into doing this and need some sort of approval.

**Comment by ldecoursy** [comment]
@simonwex OK - should we remove from this milestone then? We can just use the account we already created for now.

**Comment by ldecoursy** [comment]
@simonwex just checking if we should close this for now? Or move to future milestone.

**Comment by hannahkane** [comment]
Moving this to current milestone, so that we can close the Feb 26 milestone. Can close it if needed.

**Comment by ldecoursy** [comment]
@simonwex See my last comment above - I dont believe this is still on track. We created a new gmail account for now, but haven't connected to google enterprise.

**Comment by ldecoursy** [comment]
Changing this to P2, since we're waiting on a response from IT

**Comment by ldecoursy** [comment]
@simonwex I'm going to close this ticket. Sounds like we're blocked by IT and in the meantime, we created our own account to use for Mozilla Learning. Can reopen if/when you hear back from IT.
