### ISSUE TITLE
Push Calypso CMS prototype forward combine efforts with design style guide

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#716]
Continuing the work on the CMS prototype and start work on incorporating the style guidelines into a bootstrap theme.

Starter goals are:
* Understand good candidates for implementation of calypso
* Release first pass at Foxlight

Responsible: @simonwex
Dev: @gvn 
Dev: @mmmavis 
Design: @vazquez

**Comment by OpenMatt** [comment]
@simonwex Encryption Campaign needs a blog, ideally to go live next week. Too early? We're a willing guinea pig if you're looking for one.

**Comment by OpenMatt** [comment]
@simonwex says: too early this heartbeat.

**Comment by OpenMatt** [comment]
@simonwex says: design requirements for this heartbeat are for UX / UI prototyping

**Comment by simonwex** [comment]
@adamlofting can you spare a few moments to help us think about this? Could we use our usual Wednesday slot?

**Comment by xmatthewx** [comment]
Curious about potential partnership with Automattic. Glad to contribute. @simonwex, let's also talk about UX needs on Monday.

**Comment by xmatthewx** [comment]
Thinking about our TPS conversation on `betterfaster` and the need to do fewer things to achieve that ... A dashboard feels like a phase two of this project. Q2 or even H2.

**Comment by adamlofting** [comment]
@simonwex let's talk impact stats on Wednesday (I've sent an invite for a new time this week). Agree with @xmatthewx that it shouldn't slow down V1, but this could link closely to goals for thought leadership by MoFo and MLN so it's great to start plant those seeds.

**Comment by simonwex** [comment]
Kickoff Scheduled for 11:00am PDT, Tuesday the 2nd. Feel free to join us in my Vidyo room if you'd like to.

**Comment by cassiemc** [comment]
cc @hannahkane

**Comment by cassiemc** [comment]
I can't make this kickoff time but look forward to hearing about the first test case implementation on one of our existing sites (be that Science, Hives, or otherwise)

**Comment by cassiemc** [comment]
Assigned @vazquez for design support but realistically might end up a P2 for him.

**Comment by hannahkane** [comment]
Another possible candidate for CMS prototyping: Clubs Resources portal. @amirad and others are creating dozens of resource for Club Captains, using github pages. Would be great to have an easily updateable home for all of these resources.

**Comment by gvn** [comment]
@hannahkane can you point me to their current implementation?

**Comment by hannahkane** [comment]
@gvn - currently the resources are a list living in a [google doc](https://docs.google.com/document/d/1qLwEJZXF6Dz1wZ71AIC8t8n1LHPC6n99kZdFTuvB-LQ/edit). @amirad would love to have an attractive page somewhere that she can easily add to/edit.

**Comment by gvn** [comment]
I bet that would be a good fit for Mage. What do you think @simonwex ?

**Comment by simonwex** [comment]
I'd like to first see how much of it we could do with Calypso.

**Comment by simonwex** [comment]
https://github.com/mozilla/foxlight
