### ISSUE TITLE
Scope edits to MozFest website

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/plan#717]
Currently the 2015 website is still in 2015 festival mode and is confusing for those looking for 2016 information.
* 2015 pages is still accessible with the dates for the festival on the home page
* Buy tickets page is still visible

Would be great to alter the home page to make some small changes 
* Remove the 2015 dates
* remove ticket page on top navigation bar
* add text to say 2016 dates coming soon

Larger changes needed in the near future
* Save the date information
* Sign up for updates
* 2016 Video

Would love to chat about these changes and potential timelines with @cassiemc and @edrushka

**Comment by edrushka** [comment]
I'll add this as a P2 for this heartbeat and will schedule a meeting for discussion. Let's plan to scope the changes this heartbeat, and do the actual work the first part of the next heartbeat (since devs are totally in short supply this heartbeat).

**Comment by edrushka** [comment]
@Saallen I removed the "needs discussion" label because we use that label in the TPS calls to denote tickets that need the entire team's input. I think this ticket is small enough that we just need to secure some dev time. Feel free to re-add the label if you'd like a larger discussion.

**Comment by Saallen** [comment]
:+1:

**Comment by edrushka** [comment]
@simonwex can you please let me know which dev might be able to help with this during the week of Feb 15? That way I can invite them to the scoping call. It's a pretty minor lift.

**Comment by edrushka** [comment]
Popping in a couple more assets we may want to include. These might not work on the site, but I don't want to forget about them!
- Signs: https://www.dropbox.com/s/7tm7uckec45zu40/MLN_Signage_Spot.mp4?dl=0
- Names & connections: https://www.dropbox.com/s/0bjazipdjo3lylc/MLN_Connected_Spot.mp4?dl=0
- Marina's Journey: https://www.dropbox.com/s/2mofyusaqnnekch/MARINA_ROUGHCUT.mp4?dl=0

**Comment by edrushka** [comment]
Update: we don't have dev capacity this heartbeat so we'll likely have to push this to the end of Feb. @Saallen - can we combine all those changes into a single round of updates that will tide us over until we open "submit a session" proposals?

- Remove the 2015 dates
- Remove ticket page on top navigation bar
- Add text to say 2016 dates coming soon
- Add email sign up for updates
- Add 2016 video
- Create a banner on staging with 2016 dates that we can quickly push to prod when dates are finalized

**Comment by Saallen** [comment]
Is there anyway we can get the date removed from the main page?
As at present it doesnt even say 2015 on there is its very confusing especially with the ticket link above

**Comment by edrushka** [comment]
@simonwex can we get dev to either remove the date on the homepage, or clarify by adding "2015"?

**Comment by cassiemc** [comment]
@edrushka I would also remove the 'buy tix' section on the homepage, and take it out of the nav, no? IMO adding the year would be clearer. So, text amended to "NOVEMBER 6-8, **2015** IN LONDON"

**Comment by edrushka** [comment]
@cassiemc yes, but that's part of a larger set of changes outlined above. The very immediate need is to indicate that the dates on the site are from last year.

**Comment by simonwex** [comment]
@alanmoo could you help @edrushka to provide some technical perspective?

**Comment by edrushka** [comment]
@alanmoo - if you could change the homepage to read '2016 dates coming soon' instead of November 6-8 in London', that should tide us over for a couple weeks. Thank you!

**Comment by edrushka** [comment]
Done! Thanks @alanmoo and Wex. I'm going to close this ticket now and re-file another one for the next heartbeat.
