### ISSUE TITLE
OWF Comms Plan, 2016

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#720]
*Detailed goals in Open Web Fellows 2016 Comms Plan [Google Docs] (https://docs.google.com/document/d/1x8lUU_rUF-WfgQNjyaI-u6fQ8IG1hLrjeJai3TrZ7U0/edit)*

**RASCI:**
R: Kevin Zawacki @KevZawacki 
A: Paul Johnson @HPaulJohnson 
S: Brett Gaylor @brettgaylor  Melissa Romaine
C: Fellows, Sam Burton, host org. communications teams
I: MoFo comms

**Overview:**
The first quarter of 2016 marks a major moment for Mozilla’s Advocacy network: the first-ever cohort of Ford-Mozilla Open Web Fellows will graduate from their placement organizations. As this occurs, Mozilla will reflect on fellows’ work and impact, and fellows will embark on the next step of their careers as OWF alums. 

Starting in February, Mozilla will also open the application process for its second cohort of Open Web Fellows. This class will be more policy-focused than the last, and boast heightened reach — fellows will embed at organizations in Nairobi, Santiago, Brussels and elsewhere around the world.

The [Communications Plan] (https://docs.google.com/document/d/1x8lUU_rUF-WfgQNjyaI-u6fQ8IG1hLrjeJai3TrZ7U0/edit) (linked above) outlines strategies and tactics for communicating these developments with the world.

**Links:**
[OWF blog] (https://docs.google.com/document/d/1ArP7FlUMLPepoLExDCq7EzfdK_wjH6NsqmXRgNPhCLA/edit)
[OWF narrative] (https://docs.google.com/document/d/1WRLUoMaoWvG1z_ASsQ0_WJ7NYj8E2W0Aqc6dHpZlM1U/edit)
[OWF call notes] (https://docs.google.com/document/d/12xez8TBjn86wPFWdnxBiAlXgYqy6RPN8cj0QN79PnsQ/edit#)

**KPIs:**
- [x] 1 capstone blog spotlighting OWF program and enticing 2016 applicants
- [x] 1 email engaging unselected host orgs 2016 applications
- [x] 1-2 positive, factual stories in tech/policy/privacy press spotlighting OWF program
- [x] Strong showing on all owned channels: email, project call, social

**Calendar and Tactics:**
- [x] **Jan. 22:** Kevin and Melissa determine blog structure and content
- [x] **Jan 25:** Kevin beings interviews with OWFs and host orgs. See progress [here] (https://docs.google.com/document/d/1ArP7FlUMLPepoLExDCq7EzfdK_wjH6NsqmXRgNPhCLA/edit)
- [x] **Feb. 1:**  Application open for 2016 fellows
- [x] **Feb 1:** Melissa on all hands call
- [x] **Feb. 2:** Begin promoting application portal on social
- [x] **Feb 16:** Email to unselected host orgs (Melissa) *Sent Feb. 18*
- [x] **Feb 22:** Publish blog post on blog.mozilla.org/netpolicy and blog.mozilla.org
- [x] **Feb 22:** Pitch media
- [x] **Feb. 22:** Promote blog on social

**Comment by cassiemc** [comment]
@Melechuga you should have access now if you to move it. Looked like a great bug.

**Comment by Melechuga** [comment]
Thanks @cassiemc!
@KevZawacki @HPaulJohnson @brettgaylor: Please follow this ticket; thanks!

**Comment by KevZawacki** [comment]
@brettgaylor and @Melechuga, our blog post is coming along nicely. All that's left is dropping in sound bites from 2015 host organizations.

When you have a moment, can you [take a look](https://docs.google.com/document/d/1ArP7FlUMLPepoLExDCq7EzfdK_wjH6NsqmXRgNPhCLA/edit) and share feedback? Is the tone / content / structure on target? 

I'd also like to share the OWF bios with each of the fellows, to ensure they're accurate.  

cc @HPaulJohnson

**Comment by KevZawacki** [comment]
@brettgaylor @Melechuga 

Coverage report available [here](https://docs.google.com/document/d/1ktiCbKven4-WVOXzvGU-qLz618dm3cxxsU9XfdEy_5Q/edit).

Since we've achieved KPIs, and there's no new action for now, I'm going to close this bug. 

Future comms, like creating a publication and promoting 2016 fellows, can live in a new comms plan / bug.
