### ISSUE TITLE
Closeout Sale assets for gear.mozilla.org

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/plan#724]
We will be closing the gear.mozilla.org online store. **We have not yet announced the closing of this store to the broader community. That needs to happen thoughtfully.** There is a lot of merchandise currently warehoused that we'd like to move asap. That means a BIG SALE. We need to design a few assets for the site that advertise a deep discount sale (e.g. 50% off). I'm getting details from our vendor about what assets we'll need, but the list will be a shorter version of https://github.com/MozillaFoundation/2015-fundraising/issues/46. 

We need to move very quickly as our vendor contract is running out within 6 weeks -- and we will lose their help with customer support (for shipping, fulfillment, and troubleshooting). Purchases made now will need support / troubleshooting help for the next 4 - 6 weeks during fulfillment, so we need to launch this sale asap. Let's talk about capacity / designer availability.

Once we get rolling we also need to develop copy and messaging about the store closing and the sale (for internal and external audiences).

cc @davidascher cc @HPaulJohnson 

Driver: @cassiemc
R: @natalieworth, @KevZawacki 
A: @valianttry 
C: @HPaulJohnson @LucyeoH 
I: @davidascher 

Tracking issues here: https://github.com/MozillaFoundation/2015-fundraising/issues?q=is%3Aopen+is%3Aissue+label%3A%22Gear+store%22

**Comment by cassiemc** [comment]
Ideally @natalieworth can help with this, but I'll need to understand upcoming campaign plans & scope. We can discuss at heartbeat planning this Friday.

**Comment by elioqoshi** [comment]
Can we link this with an issue in Community Design too?
https://github.com/mozilla/Community-Design

**Comment by OpenMatt** [comment]
@valianttry for a bit of context: why are we closing the gear store?

**Comment by cassiemc** [comment]
@elioqoshi We're going to try to keep this in-house as it's a tight deadline with external dependencies and we have designers who have worked on it before.

**Comment by cassiemc** [comment]
I've added the at-risk label because of the 'needs-driver' issue. It'd also be good to clarify the list of deliverables asap so it doesn't eat too much into production time, especially given Monday's a holiday. I'm sure this is easily gotten back on track but I'd like to see those two pieces resolved quickly if possible.

**Comment by natalieworth** [comment]
@cassiemc I should have time to do this between the encryption campaign

**Comment by valianttry** [comment]
hi @natalieworth the gear store pricing has been reduced on every item by 30% (that is currently live at gear.mozilla.org). 

Our vendor provided the following files so that we can design some assets, including a Sale banner for the main page:
https://geeknet.box.com/s/r3wmfp4s3s2ti9e3u4pqzc98d0e1sqxn

We should talk about channel availability soon.

I think we should feature items in our designs that we have the MOST of in our inventory -- below is a list of the merchandise and the total # left in inventory sorted by most > least:

![closing_the_store_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/13065702/eca1026e-d413-11e5-920f-988efbeabd3f.png)

Where should we create tickets? The donate@ repo @cassiemc ?

**Comment by natalieworth** [comment]
The previous gear store push from 2015 included deliverables for social share graphics (facebook & twitter), updated banner, an email, and a directory tile on mozilla.org. Are we going to be requiring similar deliverables for the sale push? Would also be good to anticipate if we'll be doing another push after the 30% for any clear out if necessary?

I can get started on this once deliverables/ content/ what primary inventory to clear is established. Tickets were previously created in the fundraising repo: https://github.com/MozillaFoundation/2015-fundraising/issues?q=is%3Aopen+is%3Aissue+label%3A%22Gear+store%22
cc @cassiemc @valianttry

**Comment by cassiemc** [comment]
I'm concerned that this still has no assigned driver, so I'm happy to own scheduling a kickoff unless it makes more sense for @OpenMatt to do it. I suspect this will not require a lot of meeting time and that @natalieworth can run with this once we have a kickoff and a finalized list of assets.

This issue has great context – https://github.com/MozillaFoundation/2015-fundraising/issues/65 – and yes @valianttry the fundraising repo would be perfect. We can reuse the label 'gear store' as well, to track issues here: https://github.com/MozillaFoundation/2015-fundraising/labels/Gear%20store

**Comment by cassiemc** [comment]
@valianttry If I schedule a kickoff who else needs to be invited besides you, me, @natalieworth? I'm assuming you can liaise with our vendor to deliver final assets?

**Comment by cassiemc** [comment]
+ @HPaulJohnson and @KevZawacki, likely!

**Comment by cassiemc** [comment]
Adding a RACI to the top comment.

**Comment by cassiemc** [comment]
Difficult to find an open time slot for a kickoff before this week, but there is an eensy opening tomorrow morning. Sorry @davidascher if there is a conflict; not sure if you want to be there.

**Comment by hannahkane** [comment]
Possible to put a size label on this ticket? Small, medium, or large? (Will help with planning future heartbeats.)

**Comment by natalieworth** [comment]
I've added size medium, but feel free to change if anyone thinks another would fit better.

**Comment by cassiemc** [comment]
I'm going to update to large b/c it includes multiple people for the full heartbeat :)

**Comment by cassiemc** [comment]
I'm changing this to at-risk. I don't think it's a serious risk as we have a stand on Monday where we should get some clarity, but I'd like to keep it there 'til then since there's been little movement on bugs so far.

**Comment by natalieworth** [comment]
Photography for most items in inventory: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0WldocklpNkpJV2c&usp=drive_web&ddrp=1#
The only one missing is the Mozilla mug (and there is only one product photo of the Firefox mug)—but these aren't currently on the Gear Store sight. Is this an error on the product sheet @valianttry ?

**Comment by cassiemc** [comment]
Removing at-risk label. All bugs now have owners and @KevZawacki is planning to finalize copy EOD tomorrow, @valianttry will be on-hand to yay-nay, and @natalieworth is going to prioritize the gear store banner to help advertise the current 30% off sale for organic traffic. Go team!

**Comment by OpenMatt** [comment]
@HPaulJohnson will help work w. @valianttry to get final approval and close this out

**Comment by cassiemc** [comment]
SOOOO close. All design work is done, just finalizing the email copy. Last two outstanding pieces are:
- [ ] What is this other mysterious gear store that will remain open? How does that work?
- [ ] Is gear@mozilla.org actually a thing that will work and have someone receiving mail? Or is it gear@mozilla.com?

Unfortunately these issues aren't completely closed before my EOD so rolling over to the next heartbeat. Will check in on this on Monday to see if @valianttry needs anything else from me or others.

**Comment by cassiemc** [comment]
Some final details. Tickets are up-to-date on https://github.com/MozillaFoundation/2015-fundraising/labels/Gear%20store.

**Comment by cassiemc** [comment]
Just a couple emails to send then can close this completely.

**Comment by cassiemc** [comment]
I asked for updates on the last two outstanding tickets... @KevZawacki or @valianttry can hopefully fill us in on when we close this meta ticket.

**Comment by KevZawacki** [comment]
@cassiemc @valianttry 

We've swapped out the all@ email for a non-verbal project call update. And I'm all set to begin sale promotion on social next week. OK by me to close this ticket!
