### ISSUE TITLE
Preparation work for Thimble Learning Analytics project

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#725]
`Needs Dev` - I might need a small amount of engineering support to get some sample data / schema notes about Thimble during this heartbeat. No new development work required though.

Tasks:
- [x] Explore and document existing Thimle data schema (inc a sample row of data per table)
- [x] Explore API - what data is public / private
- [ ] Share Meen Chul Kim's draft research proposal with the team: https://docs.google.com/document/d/18SR0NVLi71eiZu1_EaDgRHm9JOML7wlyRUlr2Kwymgw/edit?ts=56b25f20
- [ ] Investigate contract / legal paperwork needed for sharing data with Drexel / Meen Chul Kim
- [x] Finalize budget / plan with Drexel / Meen Chul Kim

**Comment by OpenMatt** [comment]
@adamlofting can you some added context around *timelines* for this work? key deadlines, etc? (will be helpful in terms of prioritizing what needs to be done this hb vs. next)

**Comment by adamlofting** [comment]
The plan is still being worked out, but current aim is to start the project mid March.

But, there's prep work needed for the research proposal, which this ticket relates too. The dev need is to document the existing data structure to inform the research proposal.

**Comment by adamlofting** [comment]
Still had this tab open and realised my last comment didn't answer the important question:

This current heartbeat **Feb 26** is the ideal deadline for the sample data / documenting the data schema (the `needs dev` piece of the work) . But, we have to be realistic about capacity etc.

**Comment by adamlofting** [comment]
@simonwex did this documentation task make it onto any dev todo list for this heartbeat?

**Comment by simonwex** [comment]
@adamlofting, @gideonthomas can help you collect any info you need. Just ping him directly.

**Comment by adamlofting** [comment]
:+1: 

@gideonthomas I've filed https://github.com/mozilla/thimble.mozilla.org/issues/1422 to track the specific request to document our data schema(s).

**Comment by adamlofting** [comment]
Good progress on this this week. Rolling over.

**Comment by adamlofting** [comment]
Here is the documentation: https://github.com/mozilla/thimble.mozilla.org/issues/1422

I'm marking this ticket as a P2 as the rest is paperwork and we'll likely shift the timeline back a bit.

**Comment by adamlofting** [comment]
Plan is complete.

The last action is the paperwork - and bugs have been filed with Ops, and are being worked on.

I'm going to close this ticket, as the rest doesn't need visibility at the Heartbeat planning level.
