### ISSUE TITLE
Push Badges to a staging server for testing with real users

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#727]
We need to review [this](https://github.com/mozilla/teach.mozilla.org/pull/1427/files) PR and complete the final layers of integration.

Driver: @simonwex
Dev: @Pomax

**Comment by hannahkane** [comment]
Possible to put a size label on this ticket? Small, medium, or large? (Will help with planning future heartbeats.)

**Comment by hannahkane** [comment]
@simonwex - should we roll this into the next heartbeat, since it sounds like that's when the work will happen?

**Comment by simonwex** [comment]
Rollin'

**Comment by OpenMatt** [comment]
@simonwex: got a size estimate?

**Comment by hannahkane** [comment]
Rolling this into the next heartbeat

**Comment by hannahkane** [comment]
@cassiemc - adding a "Needs Design" label because we (intentionally) never provided designs for the admin side of the badge workflows, and we could provide them now if we have anyone available to assign. Not strictly necessary, though, since only staff and friends of the org will see the admin side. IOW, this ticket is a p2 for design, and a P1 for dev.

**Comment by hannahkane** [comment]
Determine acceptance criteria for this heartbeat

cc @simonwex

**Comment by hannahkane** [comment]
No design work this heartbeat

**Comment by hannahkane** [comment]
The remaining badges work has been defined in [these tickets](https://github.com/mozilla/teach.mozilla.org/issues?q=is%3Aissue+is%3Aopen+label%3Abadge-follow-up)

The work for the March 25 heartbeat is defined [here](https://github.com/mozilla/teach.mozilla.org/issues?q=is%3Aissue+is%3Aopen+label%3Abadge-follow-up+milestone%3A%22March+25%22)

**Comment by hannahkane** [comment]
March 25 work complete

Remaining work is [here](https://github.com/mozilla/teach.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Abadge-follow-up+), so rolling to April 8 heartbeat

**Comment by hannahkane** [comment]
We are down to two outstanding issues (making badges with evidence requirements work, and finalizing the login-to-credly workflow) and expect to release this to staging next heartbeat.

**Comment by hannahkane** [comment]
Updating title to reflect April 22 heartbeat work

**Comment by hannahkane** [comment]
Still missing the login-to-credly workflow, but the rest of the workflow lives here now: https://teach-with-credly-badges.herokuapp.com/badges

!!! :tada:

**Comment by hannahkane** [comment]
I'm closing this and will file follow-up issues as needed
