### ISSUE TITLE
Devops Activities for Feb 26

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#728]
- [x] Prepare advocacy.mozilla.org for snippet traffic
https://github.com/mozillafoundation/mofo-devops/issues/272 

 - [x] Replace the old goggles content with a "please get the new one" notice
https://github.com/mozillafoundation/mofo-devops/issues/270

 - [x] Create hosted zone for netgainchallenge.org
https://github.com/mozillafoundation/mofo-devops/issues/269 opened 

 - [x] Turn off or redirect welcome.webmaker.org
https://github.com/mozillafoundation/mofo-devops/issues/268 

 - [x] Create 301 for netgainchallenge.org
https://github.com/mozillafoundation/mofo-devops/issues/267

 - [x] Rehost netgainpartnership.org site on our own kit
https://github.com/mozillafoundation/mofo-devops/issues/265 

 - [x] Add SSL cert to CF distro for netgainpartnership.org
https://github.com/mozillafoundation/mofo-devops/issues/264

**Comment by hannahkane** [comment]
Possible to put a size label on this ticket? Small, medium, or large? (Will help with planning future heartbeats.)
