### ISSUE TITLE
Migrate from Vue to React

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#73]
### RACI
Phase: Build / Ship
Owner: TBD
Decision: @thisandagain
Lead design: n/a
Lead dev: TBD
Quality: @simonwex  

Port Webmaker App from [Vue.js](http://vuejs.org/) to [React](http://facebook.github.io/react/). Will require application development, testing, and documentation updates.

**Comment by k88hudson** [comment]
@thisandagain was this intentionally unassigned?

**Comment by thisandagain** [comment]
Yup! I unassigned folks past the 30th just to give us more flexibility with regards to who can be a project owner.

**Comment by thisandagain** [comment]
Closing as per discussions w/ @gvn @k88hudson and @simonwex
