### ISSUE TITLE
Plans for International Women's Day?

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#730]
Are we still intending to do a campaign for this in March? @valianttry @HPaulJohnson @shaghdoosti @brettgaylor

**Comment by OpenMatt** [comment]
@shaghdoosti says: we're not running a major campaign. Different departments are planning decentralised events etc and were coordinating but there isn't going to be a big scale engagement

**Comment by OpenMatt** [comment]
@ldecoursy has a list of other events / activities we're running around it tho
