### ISSUE TITLE
Design convenings assets (templates)

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#731]
I'll be working with a designer to get this started. Individual tickets will be filed for each asset.

**Comment by cassiemc** [comment]
Assigning to @edrushka, assuming that's correct :)

**Comment by edrushka** [comment]
I was waiting to hear what designer would be helping me so I could assign to them, but sure - I can be the proxy.

**Comment by cassiemc** [comment]
@edrushka I thought it was standard in the plan repo to assign the driver. Sub-tickets in whatever granular issues would be assigned to the designer. This one should include a DARCI that lists those responsible.

**Comment by edrushka** [comment]
Sure, that works! Just let me know when you assign a designer and I'll add the DARCI.

**Comment by cassiemc** [comment]
@sabrinang is assigned :)

**Comment by edrushka** [comment]
This work is being tracked in the convenings repo: https://github.com/MozillaFoundation/convenings/issues

D: ErikaD
A: ErikaD & Sarah
R: Sabrina
C: Cassie, Lainie, Robert, Kaitlin, Michelle
I: Claw, Design team

**Comment by hannahkane** [comment]
Possible to put a size label on this ticket? Small, medium, or large? (Will help with planning future heartbeats.)

**Comment by edrushka** [comment]
Sabrina has done some cool ideating on the lanyard. We're exploring a modular approach with options for multiple 'pages' according to the scale of the event. @ryanpitts we're just using SRCCON as an example here.

This work is still in progress but feel free to check out where we're at: https://docs.google.com/document/d/16OyJUATrh79M3Gpm8Rpj7yvxmAFgXRiBsGHyctUWHfc/edit  Comments welcome.

**Comment by edrushka** [comment]
Update: rolling this over as it's ongoing, background work. Next heartbeat we'll be focusing on the poster and handout.

**Comment by edrushka** [comment]
Hoping Sabrina will have some time to work on this next heartbeat. Rolling this over.

**Comment by edrushka** [comment]
Update: progress made on the [name tag] (https://github.com/MozillaFoundation/convenings/issues/10) and [poster] (https://github.com/MozillaFoundation/convenings/issues/2). Rolling this over as it is ongoing P2 background work.

**Comment by hannahkane** [comment]
Will you need @sabrinang for the next heartbeat? Can you provide an estimate about time?

**Comment by edrushka** [comment]
Only for the first 2 days of the heartbeat (and not even full time on that). Melissa's event is on the 29th. Continued work on the lanyard past the 29th can be background work.

**Comment by edrushka** [comment]
@hannahkane Adding 'needs discussion' tag to when I can get some more of Sabrina's time.

**Comment by hannahkane** [comment]
as discussed, we can continue to dedicate resources to this next heartbeat. let's talk specifics in the Convenings team heartbeat.

**Comment by edrushka** [comment]
Met with @sabrinang. For the April 22nd heartbeat we will:
- devise a ['photo consent' solution]  (https://github.com/MozillaFoundation/convenings/issues/10) for the name tags 
- design a [Photo Consent poster] (https://github.com/MozillaFoundation/convenings/issues/16)
- design a ["What Is Mozilla?" poster] (https://github.com/MozillaFoundation/convenings/issues/5)

**Comment by edrushka** [comment]
We didn't make much progress on this this heartbeat as Sabrina was busy with her P1. Rolling over to next heartbeat, still as a P2.

**Comment by edrushka** [comment]
Right after I updated this, @sabrina added some more designs. Wooo! So we've made progress on the [Science name tags] (https://redpen.io/sp55ffd0899f1f1807) and the [what is Mozilla context poster] (https://github.com/MozillaFoundation/convenings/issues/5)

**Comment by hannahkane** [comment]
@edrushka - can you update this ticket with what's next on our ToDo list for convenings assets and any notes about deadlines?

**Comment by edrushka** [comment]
There are no upcoming deadlines. The SRCCON team is not going to use our lanyard design, which means that piece will be on hold until closer to MozFest. I'm going to close this ticket now, and will file individual design tickets as needed.
