### ISSUE TITLE
Review cross-Mofo audit of Fellowship programs

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#732]
@kristinashu did an awesome content analysis of all the fellows programs in https://github.com/MozillaFoundation/movement-building/issues/65

Doc here: https://docs.google.com/a/mozilla.com/spreadsheets/d/1c-JsTdHUSX7Z_cOxlDZ8z3rFgZOLPt9aeYKTpwK1b4c/edit?usp=sharing

Email sent to program reps for OWF, Science & News:

>Hi folks,

>Kristina and I recently worked on updating the Open Web Fellows site, and as part of that work we audited content across the fellowship programs at Mozilla to see if there were places we could harmonize language, design, information architecture and UX, to make it easier for people engaging with Mozilla to understand what programs we offer and potentially make it easier for us to manage. 

>I’d like to schedule an hour to walk through the document and discuss the audit, whenever is convenient! Including Simon b/c not only is he a ray of sunshine on a cloudy day, he might have some interesting technical observations to make. Are you guys the appropriate folks to include from your programs on such a call?

>One caveat – we’ve approached each program as newbs and outsiders, and of course there are requisite differences between programs that we’d love to understand – so none of the suggestions in that doc are written in stone or even imminent. What we’d really like to do is present this audit to you as a data point, ask for your feedback, then you (or together, we, if you’d like) can decide if it’s worth pursuing any further work in this vein. We’re also kicking off a redesign of the science site soon, so there may be an opportunity there.

>Thanks
>cassie

Got an out-of-office reply from @kaythaney so hoping to schedule once she's back, post Feb 16.

**Comment by cassiemc** [comment]
@hannahkane Unsure which strategy label to apply here. Do the fellows programs fall under 'membership'?

**Comment by cassiemc** [comment]
@davidascher or @chrislarry33  would you like to attend this meeting, whenever it gets scheduled?

**Comment by hannahkane** [comment]
Interestingly, Fellowships don't appear in the H1 plan at all. @ldecoursy @chrislarry33 - is this an oversight? I'd guess they should fall under "membership."

**Comment by xmatthewx** [comment]
I'd like to attend (though it's not critical if calendars don't line up). This connects with my network inventory work.

**Comment by cassiemc** [comment]
:+1: @xmatthewx. Waiting for replies, yet.

**Comment by chadsansing** [comment]
Muy interested -

**Comment by cassiemc** [comment]
This was scheduled earlier this week for Wed the 24th. 

@chadsansing I'm sorry I totally missed your comment! Right now we're directing this to fellowship program owners as it's predominantly a planning meeting... curious if your interest is broad support or is based on something I don't know about? Lemme know, happy to invite you or meet with you ahead of time if you think it's relevant to something you're doing.

**Comment by chadsansing** [comment]
I dream a dream of web literacy leaders/fellows in education, @cassiemc, but don't have an immediate stake. Thanks for the clarification!

**Comment by cassiemc** [comment]
We did this. Notes here: https://public.etherpad-mozilla.org/p/fellows

It went great – although there was no representation from Open News on the call. Lots of synchronization already happening around running the programs, and we can similarly synchronize some of the web properties. We agreed that using Science Lab as a guinea pig to follow the Open Web Fellows model would be a good idea. Followup is in the ongoing IA and Science redesign work.
