### ISSUE TITLE
Schedule app - Engagement design

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#738]
#### RASCI
R: @xmatthewx
A: @edrushka 
S: @mmmavis @vazquez 
C: @ryanpitts @Saallen @simonwex 
I: 

#### Overview

The Schedule App will be used by 3+ events in 2016. The tool offers an opportunity to 
 - deepen engagement with attendees and extend a post-event experience
 - better understand the event's impact on attendees.

**Design challenge**: Create a dynamic backchannel. Feedback, discussion, session documentation, post-event surveys –– we use a variety of tools to gather, store, and share information from both facilitators and participants (etherpad, google forms, whiteboard photos on flickr, etc). The app may provide an opportunity to connect this info to specific sessions making it more accessible during and after the event. 

**Constraint**: 
 - The light-weight app provides simple utility. The design and testing of features should enhance the experience without detracting from this utility or the IRL event itself. 
 - Maintain the ease of login-free use. Aim for etherpad or redpen like participation. We should only add user accounts if there's strong, validated evidence that the benefit will outweigh the engineering cost and user experience friction.

**Deliverable**: 
 - Series of concepts that articulate an enhanced event experience
 - User-testing plan for validating the concepts

#### Links

Notes: https://public.etherpad-mozilla.org/p/schedule_app
MVP app plan: https://github.com/MozillaFoundation/plan/issues/710#issuecomment-187860819

#### Key Deadlines

- MoFo London 6/13 - low risk opportunity to test new features in production app

**Comment by xmatthewx** [comment]
@simonwex - it'd be good to have @mmmavis or another dev attend lightly, for inspiration.

@cassiemc - I'd like to hold a kickoff with a designer, even if we push back the start, to give ideas time to incubate.

**Comment by xmatthewx** [comment]
Scheduled a kickoff to get ideas flowing, but work will truly begin in a future heartbeat.

**Comment by xmatthewx** [comment]
@vazquez - let's drop a link to an empty design brief here. We can fill it out gradually as we dig into this.

 - Adding another constraint above: Maintain the ease of login-free use. Aim for etherpad or redpen like participation. We should only add user accounts if there's strong, validated evidence that the benefit will outweigh the engineering cost and user experience friction.

**Comment by vazquez** [comment]
Design brief –https://docs.google.com/a/mozilla.com/document/d/1jNvaNXnYf0dmaIfr0c5lqoBsjJ5uMM_S__cZOnpP2Ws/edit?usp=sharing

**Comment by xmatthewx** [comment]
Some nice progress. @vazquez is off for half this heartbeat, so we'll likely want to follow up in the next one. Likely with a revised scope.

**Comment by edrushka** [comment]
SUPER progress :tada::tada::tada: Some great ideas here. MW, how do you propose we move forward? More ideation, or start to discuss/prioritize/figure out how to sell ;) what's already here?

**Comment by xmatthewx** [comment]
@edrushka - it'd be great for you, me, and @vazquez to walk thru this [crazy list](https://docs.google.com/spreadsheets/d/1qbYYt-mLpnfkT-d_oj2tGR3nXrbHnAstd9lSYmPIlY8/edit#gid=0) and identify the most interesting/promise points to test an intervention. Friday if possible. Monday if not. I'll attempt to schedule.

**Comment by xmatthewx** [comment]
Will review options, set priorities, and define scope for next round of ideation.

**Comment by xmatthewx** [comment]
Any intervention we pursue should either be a link to an external tool, or have the simplicity of post-it notes.
