### ISSUE TITLE
Publish user stories / target audience personae to build.wmkr.org

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#74]
Publish user stories under a new "Audience" section on `build.webmaker.org`.

Phase: Design / Build / Ship
Owner: @secretrobotron 
Decision: @thisandagain
Consulted: @LauraReynal, @edrushka 
Lead design: n/a
Lead dev: @secretrobotron
Quality: @cassiemc

**Comment by cassiemc** [comment]
Question about scope: How will these be published? Will we be using http://personas.webmakerprototypes.org/ ? Or just a written document somewhere? I am hoping we can eventually repurpose the personas site, but we may not be ready to include photos or update those (though if we could use some real shots from @LauraReynal's field research that would be amazing). Happy to help provide design here if needed.

Question about the RACI: who is actually doing the work here? <-- @secretrobotron ? It's unclear to me since there is no 'lead design' or 'lead dev'. Perhaps we need a 'lead writer' here.  cc @thisandagain

**Comment by LauraReynal** [comment]
@cassiemc @secretrobotron We can use the pictures I have, I will give the high res one according to the personas who make it to the final cut :smile: :camera:

**Comment by secretrobotron** [comment]
@LauraReynal your pictures were perfect. Thanks!

I put together something together to illustrate a design and copy for the page: https://redpen.io/gj94460cce965df3e3

Comments @thisandagain, @cassiemc, @LauraReynal ? Too much? Too little?

The second set of profiles feel a lot less on-point and descriptive than the first three. But, I'm comfortable with that for now until Laura gets a chance to actually interview people.

**Comment by thisandagain** [comment]
Great. Just one comment on using icons for the motivator section, but otherwise this is good enough to start with. Thanks @secretrobotron !

**Comment by secretrobotron** [comment]
- [x] motivator pictures replaced with icons
- [ ] needs a design-pass follow-up to improve how personas are displayed (and probably other things)
- [ ] should break up the user journey section and make the graph more understandable/interactive

Latest design: https://redpen.io/yc4c3aba08f2c560bf

**Comment by thisandagain** [comment]
I can help out with the design this week @secretrobotron

**Comment by secretrobotron** [comment]
Thanks @thisandagain

**Comment by secretrobotron** [comment]
Note: need to add a license doc for the icons and pictures. e.g. https://github.com/vazquez/webmaker-personas/commit/35e164e0fd65a1f4722f9b3f628b840e0807788a

**Comment by secretrobotron** [comment]
Update:
- Robert, Kathryn, and Lainie are reaching out to the personas they offered to make sure they're alright being featured.
- Some persona story edits to do in the redpen
- @LauraReynal's change requests are great. Will compile them into an iteration after this is off the ground.

**Comment by cassiemc** [comment]
Left some comments on the redpen, hope it helps with the design next pass. Let me know if I can help copyedit, too.

**Comment by OpenMatt** [comment]
@secretrobotron: still prioritizing this? Seems like the kind of thing we could easily punt if needed.

**Comment by secretrobotron** [comment]
@OpenMatt needs to get done ASAP. Assets and design are in my hands. Just need to make it HTML and put it online.

**Comment by OpenMatt** [comment]
* ok. moving to Feb 13 as work is ongoing.

**Comment by adamlofting** [comment]
CC'ing myself ad this is useful for another conversation I've been having.

**Comment by secretrobotron** [comment]
I'm going to close this bug now that build.webmaker.org/audience is up. We can refine the design and content in future heartbeats.
