### ISSUE TITLE
Scope better design process for internal docs, ie. board slides

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#740]
#### DARCI
Driver: @cassiemc
A:
R:
C:
I:

Planning to meet with @OpenMatt next week to discuss. Possible better/faster ticket. 

#### Key Deadlines
April 1, my last day before mat leave

**Comment by OpenMatt** [comment]
Board meeting dates for rest of year: https://docs.google.com/spreadsheets/d/14cKWC97U_5CXyO6Dkvz8hZOsz80vu2AdiYPgE_ZvLa8/edit#gid=0

**Comment by OpenMatt** [comment]
We should ensure that the new 
1) Google slide template http://mzl.la/slide_template and 
2) Google doc template (that @vazquez created) are added here to the Google drive here: 

http://mzl.la/templates

**Comment by cassiemc** [comment]
@OpenMatt and I had a good call on this earlier this week and I need to file some followup tickets. I'll do that when I'm back next week, so rolling into the next heartbeat.

**Comment by xmatthewx** [comment]
@cassiemc - did you have a chance to file these tickets? If not, post the things you learned here, cc me, and close the ticket. I'll make sure that the lessons live on...

**Comment by cassiemc** [comment]
Was simply thinking first steps were to define an owner on the design team who can help streamline this process, gather existing assets and put them in an expected place on Drive, and define some brand guidelines for internal comms work.

**Comment by xmatthewx** [comment]
@sabrinang will follow up to make sure our templates are nicely organized, old ones deprecated. Share a link with @OpenMatt to post on Build.

**Comment by sabrinang** [comment]
I've been working on a new template for board slide decks and would love feedback on how usable it is and how we can improve this template. 

https://docs.google.com/a/mozilla.com/presentation/d/1NOkL4jxlNtV30K9Y4v1w_kmfg-SU3Lm6FZFqn2aCiY0/edit?usp=sharing

Please explore the layouts and leave your feedback with comments:
<img width="1428" alt="screen shot 2016-04-08 at 3 43 16 pm" src="https://cloud.githubusercontent.com/assets/2492510/14399349/a2c0abf2-fda0-11e5-905f-381be398d218.png">

Some other features included are theme colours, placeholder fields and tips on how to use them! Read through the slides and let me know how we use colour better and what tips we should include: 
<img width="1426" alt="screen shot 2016-04-08 at 3 51 09 pm" src="https://cloud.githubusercontent.com/assets/2492510/14399449/bf2a9dd8-fda1-11e5-80ee-f7161e871261.png">

Next steps after collecting feedback is to improve it and depreciate the existing ones people are importing from (I'm still unsure where this template lives).

/cc @xmatthewx @natalieworth @lovegushwa

**Comment by xmatthewx** [comment]
@sabrinang – bring these to demo or crit if you don't get feedback here.

**Comment by hannahkane** [comment]
@xmatthewx - what milestone should this be in? I'm moving to June 3 because it's the closest to May 31, but feel free to change it. (I'm working to remove the May 31st milestone, since it doesn't correspond to our heartbeat schedule.)

**Comment by hannahkane** [comment]
Is this ticket still needed? Moving to future milestone so it doesn't get lost.

**Comment by xmatthewx** [comment]
We should probably close and then reopen when we're ready to iterate. 

Dates for your planning from above:
 - July 7: MoFo Board Meeting
 - October 20: MoFo Board Meeting (in person) 2016 strategy

**Comment by hannahkane** [comment]
Closing for now.
