### ISSUE TITLE
Consider education hub naming & comms strategy

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#741]
#### DARCI
D: @cassiemc
A: @chrislarry33 
R: @hannahkane @kristinashu @cassiemc
C: @ldecoursy @KevZawacki @HPaulJohnson @samanthaburton @xmatthewx 
I: @msurman @davidascher 

#### Overview
In line with the IA exercise #661 and understanding our audiences #680, we've discovered that changing a url for teach.mozilla.org could have a large impact on one of our largest audiences. It may not necessarily, but since this has been handled poorly in the past we wanted some time to dig into this further. The opportunity here is to name, label, and create an IA structure that reinforces what is happening in our education hub so that it's easy to grok and connect with the Mozilla mission. For the scope of this ticket we'd like to whittle down a list of possible names, their impact, and come up with a strategy for implementing that change.

#### Links
Initial notes started here: https://docs.google.com/document/d/1ZnDw1EkHvttiyw7twrNVf2q_FpUoEqNDuUvZnIjumOE/edit

**Comment by cassiemc** [comment]
Spoke to @secretrobotron and there are certain themes / assumptions we'd like to test with 10 people that involve the overall IA approach. We are writing up thoughts and a script here: https://docs.google.com/document/d/1qhvY6kn-1pGq0EqlHCQ9fWjhoxfVDs3tDpfB1QFJdys/edit

**Comment by cassiemc** [comment]
After much thought, I think it should be called "Mozilla Learning Network" with a url of learning.mozilla.com. It's a name we are already using internally and externally, it maps well to the concept of the breadth of activities we offer and audiences we target, and the 'network' is true to the clubs / convenings & curriculum sharing approach. It also seems the second least disruptive (second to keeping teach.mozilla.org) to a community that has already been disrupted multiple times.

On the same hand, I think we should reconsider the name of "Mozilla Leadership Network" as the value prop of that concept unfolds, predominantly because we haven't used it externally and it IS disruptive to this learning community, and there are likely many other incantations of the concept that would be suitable names. 

I'll be presenting more thought process around this to exec team next Wednesday at which point I hope we can do a final R?. In the meantime, any thoughts @kristinashu @hannahkane @ldecoursy @chrislarry33 @xmatthewx before I close this ticket?

**Comment by ldecoursy** [comment]
I'd +1 to keeping Mozilla Learning Network, or even simplifying to Mozilla Learning (in case we want to reserve "Network" for the broader MLN work). Looking forward to hearing how it goes on Wednesday :)

**Comment by xmatthewx** [comment]
@cassiemc - status? 

I'd like to propose that we create a single planning ticket for related IA, comms, audit work and file granular tickets in the design repo or another home. 

While this risks reducing the visibility of this work, it'll make it easier for us to triage production during the planning meeting. It'll also make it easier for others to follow this work from a high level.
