### ISSUE TITLE
Stop removing P1 & P2 labels when tickets close

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#743]
This behaviour seems to be automated from build.mozillafoundation.org, we suspect. I believe @simonwex was going to look into it.

**Comment by cassiemc** [comment]
Guessing this is small. @simonwex can I assign to you?

**Comment by edrushka** [comment]
I'm beginning to think it's not automated. Instead, I suspect @OpenMatt loves GitHub so much that he's watching it ALL THE TIME.  Always Be Closing (tickets).

**Comment by cassiemc** [comment]
Lol. Since @simonwex is overwhelmed this heartbeat, wondering if he can delegate or maybe @davidascher can help. Of course not a huge priority, but it's annoying.

**Comment by davidascher** [comment]
I don't recall writing code to remove tickets, but I may have.  @cadecairos
has looked at this codebase more recently than I have.  It's possible his
latest code changes will break this feature anyway ;-).

**Comment by OpenMatt** [comment]
:) its not me!

**Comment by davidascher** [comment]
BTW: it's not matt ;-)  If you look at a ticket, it seems to happen
automatically and the person closing the ticket is blamed, e.g.:

[image: Screenshot 2016-02-26 10.44.09.png]

**Comment by davidascher** [comment]
@simonwex I should probably talk to @cade about the code both for book. and
for plzkthx, which is likely to blame (and obsolete I think).

**Comment by cadecairos** [comment]
@davidascher we probably shouldn't pull in @cade on this one!

I'm pretty sure I took out all the code in build that modifies Github issues.

**Comment by davidascher** [comment]
We should review the webhooks on
https://github.com/MozillaFoundation/plan/settings/hooks

My guess is we need to remove three of them.

**Comment by cade** [comment]
> we probably shouldn't pull in @cade on this one!

![player3](https://cloud.githubusercontent.com/assets/3403/13362584/0382ea36-dc8b-11e5-922c-a226d1b1fc44.gif)

**Comment by davidascher** [comment]
Apologies @cade. Feel free to unsubscribe!

**Comment by simonwex** [comment]
Fixed this! – It was a hook with waffle.
