### ISSUE TITLE
[Mar 8] Build Curriculum Workshop landing page on Teach site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#745]
#### DARCI
D: @hannahkane
A: @simonwex @cassiemc 
R: Design: @flukeout @vazquez Dev: TBD
C: @chadsansing 
I:

#### Background
@chadsansing and @amirad rad are going to begin co-hosting a monthly call focused on Curriculum development. The task here is to design and build a landing page for the series.

#### Ticket
 - [ ] https://github.com/mozilla/mofo-cms-experiment/issues/17

**Comment by ldecoursy** [comment]
PS We'll plan to use same design/build for a monthly Mozilla Learning community call - first one starts in late March.

**Comment by cassiemc** [comment]
Should we add [Mar 8] to the bug name?

**Comment by OpenMatt** [comment]
Perhaps this could push back a Heartbeat / move to p2. Especially given: the CMS work will ultimately help deliver this.

**Comment by chadsansing** [comment]
+1 to @cassiemc.

@OpenMatt, if at all possible, I'd like to begin as we plan to go (landing site in-hand), but, if need be, we can ship a hangout URL and a separate etherpad URL and support audience members in finding both as best able.

**Comment by hannahkane** [comment]
We actually did this during the March 11th heartbeat, so closing, though there are follow-up steps.
