### ISSUE TITLE
Network Pulse research & prototype

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#746]
#### RASCI
R: @xmatthewx
A: @davidascher 
S: 
C: program managers, comms team, etc
I:

#### Overview

Staff and network members create things (reports, software, tools, ...) that they _might_ share with the network if their motivations align with our incentives and potential outcomes. 

_How do we foster a comprehensive view of these things created? How do we capture these things to tell our collective story? How do we amplify the best of our network's impact?_

#### Next steps
 
 - Connect with the Affiliate Policy Group to discuss how we leverage incentives for participation
 - Prototype featuring exemplar work. _How does the stream feed our story?_
 - Prototype filtering by category etc
 - Continue conversations with staff and members on these topics

#### Links

 - [gdoc notes](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.1jw5xbbg838) - observations and recommendations 
 - [prototype #1](http://xmatthewx.github.io/network-pulse/)
 - [precedents deck](https://docs.google.com/presentation/d/10QvAb_utE6KXgIucuQiJ65NW3frmq85XTBgo76r_AvY/edit#slide=id.gef9484f12_0_0)
 - Prior planning #705

**Comment by xmatthewx** [comment]
**Theory**: if we investigate and optimize the experience of members who _might_ share with our network, we can increase visibility across programs and thereby increase collaboration, innovation, and impact.
 
<img width="968" alt="screenshot 2016-02-25 16 38 06" src="https://cloud.githubusercontent.com/assets/53411/13335268/37629624-dbde-11e5-837b-a52945c57823.png">

**Comment by cassiemc** [comment]
This is cool thinking, design team should see this. @lovegushwa @sabrinang @kristinashu @vazquez @flukeout @natalieworth

**Comment by cassiemc** [comment]
@xmatthewx it's not clear to me what you need from design team on this ticket this heartbeat, can you elaborate?

**Comment by cassiemc** [comment]
Looking further at [the prototype](http://xmatthewx.github.io/network-pulse/) it'd be cool to understand how you intend to use it. Is it for external use? Internal only? The UI is off-brand atm so we could definitely do a stricter design review, but this falls into that tricky category of 'how finished do we want prototypes to look'.  We may not be there yet!

**Comment by lovegushwa** [comment]
@xmatthewx is this a stream or do you imagine some curation (something like a web magazine for example?).

**Comment by OpenMatt** [comment]
Can we give this a more descriptive title + clearer deliverable for this heartbeat?

**Comment by OpenMatt** [comment]
suggestions: make it "small" for this heartbeat; more about spec-ing and info-gathering than production at this point.

**Comment by xmatthewx** [comment]
@cassiemc - In the next heartbeat, I hope to build 2+ new prototypes. They are disposable, and strive to test programmatic and UX concerns, so I'm not too concerned about brand at this stage – although those are Mozilla colors :smile:. I'll test Foxlight in the next round. 

It'd be great to have a designer for `p2`-ish input with design thinking.

**Comment by xmatthewx** [comment]
@lovegushwa - too early to say how this will manifest, but my thinking: we need a stream that captures most of the things, with minimal barriers to entry. From that, we curate interesting, strategic bits, and tell the deeper story. Those two things might live in one space, or curation might appear elsewhere on an org blog.

**Comment by davidascher** [comment]
additional thought: if it's indeed fun/interesting, would be good to
surface some of that feed inside of the hub-specific websites, to help
people find out about fun things happening across the network.  So maybe
e.g. the weblit hub shows a view of the feed that is 90% tagged weblit, and
10% "other".

**Comment by flukeout** [comment]
@xmatthewx While I appreciate the mobile-first approach, I doubt many of the projects that will be featured will actually work & render properly on a device. While that may change over time, it might be interesting to...
* Have a way to submit a screenshot or cover image for non-mobile work as a fallback?
* Also allow the person submitting to specify devices what it will work on?
  * And maybe filter projects based on that when you're viewing on mobile?
* Have some quick way to save and recall interesting pieces for later review at a desktop
  * I guess maybe the "Fav" star can accomplish this, wonder if there are other ways

**Comment by cassiemc** [comment]
I think @flukeout just volunteered himself. P2 though!

**Comment by adamlofting** [comment]
Without wanting to take this thread down a rabbit hole, I was wondering this morning if there's a name for this project that sounds more immediately like a magazine / gallery / feed of things to explore? It's probably my bias, but I think of Network Health KPIs when I hear see `pulse`. This is definitely a P3 question though :wink:

**Comment by xmatthewx** [comment]
Slow, but steady progress to connect this work with parallel research efforts and internal comms. Some small additions to the prototype. Rolling to next heartbeat to continue.

**Comment by xmatthewx** [comment]
Closing this meta ticket. Will file something more specific in a future heartbeat.

**Comment by OpenMatt** [comment]
* @xmatthewx can you take a look at https://openmatt.org/2016/05/09/stories-as-data/ ? 
* Would be great to think about what we can apply from that here.
