### ISSUE TITLE
Strip event-specific terminology and code from Schedule App

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#747]
This task is part of the MVP improvements decided [here] (https://public.etherpad-mozilla.org/p/schedule_app).

Problem: We have mixed event customization with app iteration. Improvements in Chicago instance might require work to bring them into SRCCON or Mozfest apps. 

Solution: move event-specific bits (e.g. branding, help link, turn on/off "spaces", highlight colour) to a settings/theme folder where we can adjust them for each event without creating an entirely new instance.

**Dev assigned is @mmmavis **

cc: @xmatthewx @simonwex @ryanpitts

**Comment by OpenMatt** [comment]
What we're planning to get done this heartbeat re: design:
* how the schedule app can be used at events to facilitate deeper engagement. 
* + key differentiators from other existing tools / apps

**Comment by edrushka** [comment]
During the TPS call we decided not to start this work this heartbeat. Instead, we'll make this a P1 for the March 25 heartbeat.

**Comment by xmatthewx** [comment]
Before we dig into the code, let's create a high-level system diagram of the app components and their inter-dependence.

**Comment by edrushka** [comment]
Looks like this needs to get pushed another heartbeat.

**Comment by xmatthewx** [comment]
I can drive this in @edrushka's PTO absence. Need to check with @simonwex on dev assignment.

**Comment by edrushka** [comment]
Would be ideal to have @ScottDowne work on this ticket this heartbeat. I don't believe it's two weeks worth of work, so he'll have capacity for some P2s.

**Comment by xmatthewx** [comment]
Assigning to @mmmavis based on conversations with @simonwex and @mmmavis and others.

**Comment by mmmavis** [comment]
systems diagrams to be added to https://github.com/mozilla/mofo-schedule-app/issues/37

**Comment by xmatthewx** [comment]
Work is coming along nicely. Here's a note to clarify our plan. 

The design work is speculative. I expect it to be awesome, but maybe it will lead nowhere. Until someone points to it and says "bingo, that's awesome, let's make it happen," we don't need to worry about it at all in terms of engineering.

Currently, Mavis is planning the architecture of a single app that can handle multiple events. 

Next heartbeat, we'll start building a single app that:
 - combines the best code from prior instances 
 - separates event specific stuff from the core functionality and styles

This will put us in a good position to use the app for Mozfest, maybe London, and any other event that pops up. In subsequent heartbeats, we can improve other aspects of the app, based on Mavis' revised architecture.

cc @simonwex @hannahkane @edrushka @vazquez @mmmavis

**Comment by xmatthewx** [comment]
plan largely in place. implementation begins next heartbeat.
