### ISSUE TITLE
Complete set-up for Mozilla Learning Discourse instance

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#748]
#### DARCI
D:
A: @simonwex 
R: @simonwex @ldecoursy
C: Abigail, @davidascher 
I: @chrislarry33, others who oversee MoFo Discourse instances

#### Overview
We re-launched the Mozilla Learning Discourse instance a few months ago, however a few pieces of work remain, and we have some new guidance from legal that requires a few minor dev adjustments.

- [x] Add footer with links to TOU and Privacy Policy
- [ ] Move to new domain (currently on Webmaker)
- [X] Update s3 server configuration (notification in admin settings)
- [ ] Need help answering a few q's from legal (see link below)

#### Links
* Ticket to add footer with links to TOU and Privacy Policy https://github.com/MozillaFoundation/mofo-devops/issues/255
* Ticket to move off of webmaker domain https://github.com/MozillaFoundation/mofo-devops/issues/253
* Notes from legal https://docs.google.com/document/d/1wBlEpJUMU36_Snebcmx4Gr7X3iuPk9pn0xEr3AOICoE/edit

**Comment by OpenMatt** [comment]
@simonwex will follow up w. volunteer

**Comment by flamingspaz** [comment]
You can safely ignore the S3 notification in the admin panel, we are using a different way of setting those credentials ("s3 use iam profile" setting)

**Comment by ldecoursy** [comment]
ping @simonwex Is this on track for this heartbeat?

**Comment by ldecoursy** [comment]
Yousef added the footer to our Discourse instance this heartbeat - yay! I'm going to close this and file a separate ticket re: changing the domain.
