### ISSUE TITLE
Remove Maker Party promo on beta.webmaker.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#749]
Will leave it to others to figure out whether to replace with something else

cc @xmatthewx

**Comment by xmatthewx** [comment]
I'd recommend adding something else ... the site gets a ton of monthly traffic. Ideally though, it's not something we need to update again any time soon. 

Take the highest bidder? 1¢ per click?

**Comment by cassiemc** [comment]
cc @HPaulJohnson Is there anything from a comms pov you want to push here? Encryption campaign is an obvious choice but not sure it suits the audience, and def. doesn't meet the 'only update once' criteria. 

I'd be interested to know how many Webmaker users are also Thimble/Goggles users, as we could try to push Webmaker audience to use our other better supported tools at this point. cc @adamlofting

**Comment by xmatthewx** [comment]
Looking at the list of referrers, a chunk of the incoming links are intended for the Webmaker of yore, the suite of tools. Advertising Thimble and/or Goggles would likely be a good use of the ad space AND wouldn't _require_ an update again in 2016. These tools will also fit some of the expectations of people who land on Webmaker via other Mozilla sites (more than 50% of the traffic).

The template Ricardo and I made should make it relatively trivial to create the asset.

Would could test Encryption, Mozfest, and fellowships in this space as well, but I'd wager it's not worth the effort.

**Comment by hannahkane** [comment]
Putting this into an upcoming milestone so it doesn't get lost. @xmatthewx - do you want to drive this one?

**Comment by xmatthewx** [comment]
Sure thing. I'd call it a P2 enhancement that isn't mission critical.

**Comment by xmatthewx** [comment]
I propose that we either remove the promo or fill the spot with Thimble. I'll connect with @vazquez to do this.

**Comment by xmatthewx** [comment]
Unlikely to land this heartbeat. @vazquez will be away 4 days.

**Comment by xmatthewx** [comment]
@vazquez – let's discuss next week during our kickoff.

**Comment by vazquez** [comment]
@hannahkane Can I get an R?

<img width="1440" alt="screen shot 2016-04-25 at 4 42 29 pm" src="https://cloud.githubusercontent.com/assets/1119821/14798276/cb10eb50-0b04-11e6-96d3-ff551cae5320.png">

**Comment by hannahkane** [comment]
R+. Looks great.

**Comment by xmatthewx** [comment]
Done and done. 💫  Closed via https://github.com/mozilla/webmaker-browser/pull/292#event-642009339.  👏
