### ISSUE TITLE
Dig deeper into mofo blogs strategy/ies

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#753]
From https://github.com/MozillaFoundation/plan/issues/680 looking at [this doc](https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=2008361845)

Many of our blog properties have terrible numbers. 200/mo for many, compared to a benchmark of newly launched blogs based on an individual's network that get 200/day, seems poor. Curious if we don't do a good enough job of cross-promoting content, if these properties aren't highlighted or a clear part of our comms strategies, if we get something less tangible from them, or if we really shouldn't be focusing on these (if we even currently are).

**Comment by KevZawacki** [comment]
Historically, we haven't leveraged smaller blog properties as a major part of comms strategies. Press / external audiences rely on a) blog.mozilla.org (highly visible, + MoFo has earned increased access there) and b) other channels like microsites and emails.

No doubt smaller blogs are handy for documenting our own work and providing a homebase for involved community members. But given we are earning increased time and space on blog.mozilla.org, it's likely not necessary to deeply invest in smaller blogs as major comms assets.

**Comment by hannahkane** [comment]
Just a note that we've decided to consolidate the gigabit blogs (https://blog.mozilla.org/gigabit/, http://hivecha.org/blog, and http://hivekc.org/blog/) into the MLN blog (currently housed at blog.webmaker.org). 

I think perhaps there's other consolidation that could happen, too.

**Comment by hannahkane** [comment]
I feel like we've made lots of progress on this front. I'm going to close, but @KevZawacki, feel free to re-open if this ticket is useful to you.
