### ISSUE TITLE
Figure out cross-promo strategy for our most popular web assets

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#755]
From https://github.com/MozillaFoundation/plan/issues/680 looking at [this doc](https://docs.google.com/spreadsheets/d/1fRMLFGTBmri_ftBjbwJQDG4MUitIUuEkO20S-XPEdI8/edit#gid=2008361845)

I've highlighted our top website properties in yellow. Webmaker.org at 150k monthly visitors wins. Other top properties were teach.mozilla.org, Advocacy.mozilla.org, and Source. Source has regular consistent publishing, so that doesn't surprise me, and I would venture to say that the teach and advocacy audiences are deep/super loyal, but I would need to dig into Source stats to say that wasn't true there too. Curious about bounce rates.

**Comment by hannahkane** [comment]
Would be good to clarify the goal of this ticket. Is it to capitalize on where we're currently getting the most traffic and drive it to some of our other web properties? Is it to make sure we're strategically cross-promoting based on audience needs?

**Comment by xmatthewx** [comment]
As we develop elements that repeat across our sites (like a standard footer), I suggest that we also look at ways to promote key initiatives. An "ad" on Webmaker.org could direct significant (and meaningful) traffic to Mozfest 2016 or to a advocacy campaign. 

I don't think that this will ever be p1 work, but having an eye on the opportunity will be useful as we build new and more unified websites.  

As Cassie preps for her leave, we should chat about how to wrap up these great betterfaster bits so that we can leverage them after their champion has settled elsewhere. If nothing else, we should migrate them to the design repo for triage.

**Comment by hannahkane** [comment]
Both Webmaker.org and Teach.m.o currently have banner space. Wm is currently promoting Maker Party (see #749) and Teach is currently promoting Encryption. I know Webmaker is a huge source of traffic for Teach, though I'm not sure how much is from that banner specifically.

Maybe that's a model we should use on all/most of our web properties. @kristinashu - how do you think a general promo banner would fit in on the new Science homepage, for example? I know we have banner space reserved for promoting Fellowships; maybe during non-Fellowship seasons, we use that space to promote other things? Seems like it might distract from the conversion goals of the page. Hmm...

Would an ad make sense on thimble.m.o or goggles.m.o?

**Comment by kristinashu** [comment]
I see the banner area on the science site promoting fellowship and events like MozFest but have trouble seeing something like the Encrypt campaign working there.

**Comment by jgmac1106** [comment]
In terms of xray goggles and Thimble I wouldn't mind an ad that connected
back to larger campaigns.

So if a banner add or pop up modal connected a make to say the encryption
or campus campaign that might be cool. Of course this means someone would
have to make something using these tools related to campaign.

**Comment by xmatthewx** [comment]
Closing this. We've updated promo on webmaker.org (our site with most traffic) to point to Thimble. Beyond this, connections between sites will be addressed through [universal elements](https://github.com/MozillaFoundation/Design/issues?q=is%3Aissue+is%3Aopen+label%3A%22MoFo+Unified+Design%22) (such as footer).
