### ISSUE TITLE
Ship first draft of Network Mapping Survey

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/plan#756]
#### RASCI
R: @chrislarry33 
A: @adamlofting
S: Science Lab, Clubs, Hive
C: Science Lab, Clubs, Hive
I: @davidascher 

#### Overview

- Continue to review survey questions with the teams involved
- Develop first working version of the survey in SurveyGizmo
- Check that data collected works for visual mapping of the Network
- Draft first version of comms content to support the survey

#### Links

- https://docs.google.com/document/d/1AA731KG6FB5lKnQi0hjUWwPoLk8kXnIFwhJ3bIYKNXs/edit#

#### KPIs

- [ ] Sign-off from hubs on survey content and dates

#### Key Deadlines

- Complete survey of at least one hub by end of Q1

**Comment by xmatthewx** [comment]
@adamlofting - status?

**Comment by adamlofting** [comment]
Didn't ship, so moving to next heartbeat.

* Final rounds of question reviews happening this week, including a couple of external reviewers

**Comment by adamlofting** [comment]
First version of this for Hive and Clubs has shipped and is currently going through user testing:
https://www.surveygizmo.com/s3/2674072/Network-Mapping-Hive-Learning-Networks
