### ISSUE TITLE
This is a test to see if P1 is cleared when this is closed.

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#759]
This is simply a test, nothing to see here.

**Comment by simonwex** [comment]
Damnit!

**Comment by simonwex** [comment]
Yay! \o/

**Comment by simonwex** [comment]
Hey, @OpenMatt! I disabled your waffle.io webhook as it was the one that was removing the `P1` labels. Do you still use it? Should we see if we can reconfigure it?

**Comment by davidascher** [comment]
i think i'm to blame for waffle.io (is anyone surprised?)

**Comment by cassiemc** [comment]
@simonwex You deserve :cake:
