### ISSUE TITLE
Tell the Mozilla story across properties

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#761]
#### RASCI
R:
A:
S:
C:
I:

#### Overview
From @hannahkane: "I think right now the Teach site has been developed for their specific audience, and the goals for the Science Lab site refresh are about getting their target audience to better understand the MSL programs. Neither of these sites has a particular focus on getting their individual audiences to understand the broader story."

This ticket is about considering if and how we should fix that.

Early ideas include an update to mozilla.org, a line in a unified footer with a Foundation tagline and possibly a link back to a single page, an entirely separate Mozilla Foundation site. All have pros & cons, let's get together and brainstorm some other ways. This seems like a continuation of the IA work, but more about storytelling and cross-promotion.

#### KPIs

- [ ] Sample KPI
- [ ] Sample KPI

#### Key Deadlines

- [ ] Sample Deadline
- [ ] Sample Deadline

**Comment by hannahkane** [comment]
Yes. This ticket is #winning. Feels like a piece we've been missing.

**Comment by KevZawacki** [comment]
Hello! Happy to help here. Perhaps as "R"?

Some initial thoughts:

-- I really like @cassiemc's idea of a universal footer. We have a good habit of promoting specific campaigns with pan-site banners. This feels like a more holistic and permanent next step. 

My first stab:

"xx is a Mozilla Foundation initiative. The nonprofit Mozilla Foundation is a global community that believes the Web should be open and accessible to all. To protect the Web as a public resource and empower its users, we create open source products, teach 21st-century skills and spur grassroots advocacy campaigns."

-- Right now the closest we have to a "Mozilla Foundation site" is mozilla.org/foundation. Good info (if a bit dated), but not pretty. Maybe we spruce up with the IA?

-- How do we reconcile this effort with Tabzilla? Seems like it pulls users in two directions.

**Comment by xmatthewx** [comment]
We should review how we show up when some lands on Mozilla.com via tabzilla, and make sure it reflects the new strategy and range of initiatives. 

<img width="902" alt="screenshot 2016-03-16 17 26 39" src="https://cloud.githubusercontent.com/assets/53411/13829255/6ac05966-eb9c-11e5-9713-c5e7fc188c89.png">

Unless /foundation gets a lot of traffic, I wouldn't put too much energy there (though a little design & hierarchy could go a long way).

In addition to a universal footer (which I also really like), we **might** think about how a footer "ad" for something like Mozfest could show up across various sites.

**Comment by KevZawacki** [comment]
@xmatthewx Good thinking. Would the footer be static, or change to reflect current initiatives?

**Comment by xmatthewx** [comment]
Tracking this work in https://github.com/MozillaFoundation/Design/issues/164 and https://github.com/MozillaFoundation/Design/issues?q=is%3Aissue+is%3Aopen+label%3A%22MoFo+Unified+Design%22
