### ISSUE TITLE
[Mar 31] Redirect http(s)://gear.mozilla.org to https://mozilla.org

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#762]
Related to #724 

#### DARCI
Driver: TBD
A: @simonwex
R: @cadecairos 
C: @valianttry 
I:

#### Overview

We will redirect gear.mozilla.org to mozilla.org on March 31 when the ThinkGeek store closes down.

#### Key Deadlines
Gear store is closing March 31 this will happen on the day.

**Comment by simonwex** [comment]
This will either be a DNS-level or HTTP-level redirect to https://mozilla.org. No design required, bumping to April 8, though will be done *on* March 31.

**Comment by cadecairos** [comment]
Moco has finished up the ticket to redirect: https://bugzilla.mozilla.org/show_bug.cgi?id=1260869.
