### ISSUE TITLE
Figure out dev approach to Science site rebuild

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#763]
#### DARCI
Driver: @hannahkane
A:
R: @simonwex @acabunoc 
C: CMS team
I: @kaythaney 

#### Overview
We'll likely be ready to start the build phase of the Science site refresh in the April 8 heartbeat (the design phase might not be entirely complete by then, but it's likely to be far enough along that it makes sense to start the build).

In advance of that heartbeat, let's have a discussion about how to approach the refresh—does it make sense to rebuild all or part within the CMS, or should we rebuild as is and plan to do a migration later (if at all)?

Let's also discuss who we might bring over to this project, in terms of engineering resources.

**Comment by hannahkane** [comment]
As per conversation with @simonwex - we'll make these decisions on a page-by-page basis, based on comps. 

Note: comps should be based on Mozmaker, regardless.

**Comment by kaythaney** [comment]
what's mozmaker? also, could you point me to more info on the comps
structure?

On Wed, Mar 9, 2016 at 4:43 PM, hannahkane <notifications@github.com> wrote:

> As per conversation with @simonwex <https://github.com/simonwex> - we'll
> make these decisions on a page-by-page basis, based on comps.
>
> Note: comps should be based on Mozmaker, regardless.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/plan/issues/763#issuecomment-194590475>
> .
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by hannahkane** [comment]
Ah, sorry...Mozmaker is the name we've given to the new Mofo-wide theme. You can see a demo here: https://mozilla.github.io/mozmaker/demo/

With comps, I was referring to the next phase of design after wireframes where we apply styles, add illustrations/photos/graphics, etc—essentially getting close to finalizing the design before the implementation happens.

Thanks for the questions.

**Comment by hannahkane** [comment]
Will aim to sketch out content for all high-level pages this week so that we can have a conversation early next week about CMS vs Not-CMS for each page.

**Comment by hannahkane** [comment]
Thanks to @kristinashu for creating the high-level wireframes we need to discuss our approach: https://invis.io/7T6HVRIB5

I did a first round of guesses about CMS-or-not via the comments (and making use of terms in the [CMS glossary](https://github.com/mozilla/wp-calypso/wiki/CMS-Principles)).

Could use input from @simonwex , @acabunoc, and maybe @gvn ?

**Comment by hannahkane** [comment]
Meeting scheduled for Tuesday to discuss

**Comment by hannahkane** [comment]
Meeting happened. It was productive: https://public.etherpad-mozilla.org/p/sciencesiteapproach
