### ISSUE TITLE
[March 21, 2016] Update OWF site, close applications

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#765]
#### DARCI
Driver: 
A:
R:
C:
I:

#### Overview
The Open Web Fellows application window closes at 11:59PT Sunday, March 20th. The application software automatically closes, however our website (adv.m.o/open-web-fellows) may need an update with some new messaging.

#### Links
https://advocacy.mozilla.org/open-web-fellows/

#### Key Deadlines

- [x] March 21, 2016: Updated website

**Comment by Melechuga** [comment]
Hi @cassiemc @kristinashu! Apologies for coming out of left-field; I should've put this on your radars a heartbeat ago. We close our OWF applications at midnight (PT) March 20th. It would be good to update the messaging on the website on March 21st to:

- Thank people for their interest
- Explain the application window is closed.
- Explain that those who've applied will hear from the Open Web Fellows team directly.

We should keep the program information available for candidates as we review applications; I think the only major changes would be in the header + footer:

1. Delete "apply now" button
2. New messaging in the footer.

Thoughts?
cc @brettgaylor

**Comment by kristinashu** [comment]
@Melechuga I can mock up the design changes at the start of the week. @ScottDowne do you think you'll be able to make the dev updates before March 21st?

cc @hannahkane @simonwex

**Comment by kristinashu** [comment]
Design is done https://github.com/mozilla/advocacy.mozilla.org/issues/114 and @mmmavis will implement https://github.com/mozilla/advocacy.mozilla.org/issues/115

**Comment by kristinashu** [comment]
This is live https://advocacy.mozilla.org/open-web-fellows/
