### ISSUE TITLE
Explore what to call people / members / directory

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/plan#767]
#### DARCI
Driver:
A:
R:
C:
I:

#### Overview
I think this depends a lot on the value prop work being done by @secretrobotron @LauraReynal @adamlofting etc. /cc @xmatthewx @hannahkane 

#### Reference

Some comments from the IA doc:

Cassie McDaniel
11:22 PM Feb 25
Not sure that members is the right word. For instance on Open News, someone is added to the directory any time they publish something on Source. Not necessarily because they became a 'member' but because they were added to a list of people (directory). Could it be called People?
	
Cassie McDaniel
12:58 PM Feb 26
Any reason why the other sites wouldn't also call that section people? I think we can really emphasize the emotion of 'joining a network' through the sign-up process.
	
Kristina Shu
12:58 PM Feb 26
I've updated the term to People for news but I think Ed is keen on the term Members. I think this is an area we need to explore more. Possibly explore using existing platforms like http://mozillians.org/
	
Cassie McDaniel
3:12 PM Mar 4
+hannah@mozillafoundation.org +lainie@mozillafoundation.org Can either of you speak to this?
	
Lainie DeCoursy
4:21 PM Mar 4
Could we call it Directory or Community? If this is a shared space I'd probably add the forums here in any case. I do think Members lends itself better to building network identity better than People does.
	
Hannah Kane
5:10 PM Mar 4
Everyone is making such good points! I was really only thinking about the network identity piece, but I do think there are lots of disadvantages to the word "member." I think People is much nicer, and Directory or Community are fairly descriptive. +1 to the Mozillians connection as well. I'm not sure we can decide this now. Needs more clarity and requirements to emerge from the "defining membership" part of our H1 strategy.

**Comment by cassiemc** [comment]
Possible that whatever this is, IS the Leadership Network?

**Comment by hannahkane** [comment]
This ticket no longer feels relevant. Closing!
