### ISSUE TITLE
Ready chat.mozillafoundation.org for inviting all-mofo 

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/plan#769]
#### DARCI
Driver: @simonwex
A: @simonwex
R: @gideonthomas @alanmoo @kristinashu  
C: @omnignorant @OpenMatt

**Comment by simonwex** [comment]
@xmatthewx as we discussed, we could use some design help here.

**Comment by xmatthewx** [comment]
Cool. Please invite me to the stand/kickoff until we have a chance to figure out who can best help this with design.

**Comment by simonwex** [comment]
`Daily stands at 10:30am PDT, 1:30pm EDT.`

**Comment by hannahkane** [comment]
rolling to current heartbeat

**Comment by hannahkane** [comment]
moving to current heartbeat. this is nearly ready to go.

**Comment by hannahkane** [comment]
hey, this is done! @simonwex - good to close?
