### ISSUE TITLE
Design & implement UX/UI improvements from testing

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#77]
Resolve UX and UI issues found during testing & QA review. Goal is to design and ship as many solutions to UX and UI concerns as possible within a single sprint.

### Milestone
https://github.com/mozilla/webmaker-app/milestones/UI%20Improvements

### RACI
Phase: Design / Build / Ship
Driver: @thisandagain
Decision: @thisandagain
Lead design: @vazquez
Lead dev: @gvn 
Dev: @Pomax 
Quality: @davidascher

**Comment by davidascher** [comment]
Is there a label/milestone to assess that workload yet?

**Comment by thisandagain** [comment]
Not yet. Waiting on draft report from @LauraReynal. Those findings will be merged with:
https://github.com/mozilla/webmaker-app/milestones/UI%20Improvements

**Comment by LauraReynal** [comment]
Will send UX feedback this weekend or early next week.

**Comment by k88hudson** [comment]
Good article about high performance animations to use as a starting point: http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

**Comment by thisandagain** [comment]
![screen shot 2015-02-13 at 12 38 28 pm](https://cloud.githubusercontent.com/assets/747641/6194892/9396236e-b37d-11e4-8b9d-70341f4c8306.png)

**Comment by LauraReynal** [comment]
:confetti_ball: :clap: :trophy:

**Comment by gvn** [comment]
![mind-blown](https://cloud.githubusercontent.com/assets/206379/6196015/effc7792-b388-11e4-8070-ad1dd6e0fcc9.gif)
