### ISSUE TITLE
Figure out process for engaging volunteers in P2s

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#770]
#### DARCI
Driver:
A:
R:
C:
I:

#### KPIs

- [ ] Sample KPI
- [ ] Sample KPI

#### Key Deadlines

- [ ] Sample Deadline
- [ ] Sample Deadline

**Comment by hannahkane** [comment]
cc @simonwex @davidascher @cassiemc @xmatthewx - I'm filing this because it was discussed at the planning meeting today and I don't want it to get lost. 

@davidascher - are you the driver? if so, can you please add the necessary info + labels to this ticket?

**Comment by hannahkane** [comment]
Flagging that this ticket needs a champion. Can anyone pick this up?

**Comment by hannahkane** [comment]
I'm closing this ticket since it never picked up steam. I think our champion is @acabunoc though!

**Comment by acabunoc** [comment]
Ohh, thanks @hannahkane!
