### ISSUE TITLE
Ship April board deck

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#772]
#### DARCI
Driver: @OpenMatt
R: Exec Team, @adamlofting 
Design: @sabrinang 

#### Overview
* Ensure we're using the correct slide template, that it looks great / is legible, etc., and that we follow good "betterfaster" protocol and process
* Board deck in progress (private): https://docs.google.com/presentation/d/1JbacigSxD2h6NobUdQpxi6f-7xJ-oV1NPtT4Y4WlxLM/edit#slide=id.g108ae68a62_0_205

#### Key Deadlines
* Board meeting: April 7

**Comment by OpenMatt** [comment]
* @cassiemc this probably won't need much in the way of design resources -- our plan is to simply follow the existing slide template
* but: it should probably go through design *review,* to ensure it's legible / looks great etc. 
* best time for design review would be at the very beginning and end of the process. So: a) anytime now, and b) April 4 or 5. 
* one piece of feedback we've been getting: the red background slides are difficult to read off of. So we've just been using those for interstititials / title slides, etc. 

* @cassiemc this sound good in terms of process, etc?

**Comment by xmatthewx** [comment]
Sounds good @OpenMatt. @lovegushwa and I will make a plan.

**Comment by xmatthewx** [comment]
@sabrinang will provide design support on this.
