### ISSUE TITLE
Update MozFest site with 2016 info

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#773]
#### DARCI
Driver: @edrushka
A: @Saallen 
R: @wex to assign
C: @KevZawacki @HPaulJohnson 
I: 

#### Overview
We need to update the MozFest site before the planning session in Berlin (May 4-7). We are actively seeking partners and community wranglers, and the site needs to display the proper info. All the content is ready to go - we just need a dev.

#### Specifics
- [ ] Add 2016 dates on landing page
- [ ] Update video on landing page with new vid
- [ ] Replace 'Buy a Ticket' CTA with 'Sign up for more information'
- [ ] Update Team page
- [ ] Hide/remove pages that aren't relevant:
 - [ ] Tickets
 - [ ] Schedule
 - [ ] Remote
 - [ ] Fringe events

#### Links
www.mozfest.org

#### Key Deadlines
- MozRetreat in Berlin is May 5-7
- we are currently approaching potential partners, so the update is needed asap

**Comment by edrushka** [comment]
@simonwex I'd love to have Mavis' help with this. If there was time left over in the heartbeat, she could get a start on the Schedule app work #747

**Comment by edrushka** [comment]
@simonwex - @hannahkane and @xmatthewx discussed this on the TPS call today. It works for all of us for @mmmavis to tackle this ticket this heartbeat. We do not anticipate it will take the entire heartbeat, so she'll still be partially available for CMS if needed. I will be PTO first week of this heartbeat, so completing this during the second week would be fantastic. **Please respond and assign her if this works for you**

**Comment by mmmavis** [comment]
( just self-assigned :wink: )

**Comment by edrushka** [comment]
This work is being tracked in more detail here: https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/19

**Comment by hannahkane** [comment]
@edrushka - should we roll this to the current heartbeat?

**Comment by edrushka** [comment]
Sure, although we should be able to close v. soon. Changes have been R+'d on staging and are going live today.

**Comment by hannahkane** [comment]
This is done! Yay!
