### ISSUE TITLE
OWF Website correction -- logo farm

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#774]
#### DARCI
Driver:
A:
R:
C:
I:

#### Overview
One of the host orgs, CIPIT, would like to add a line below their logo. Not sure if this is possible (and I've asked for an updated logo), but was given this directive: " the logo is fine, but where the website says "Centre for Intellectual Property and Information Technology Law" I'd like that to be followed by a comma and then "Strathmore University, Nairobi, Kenya"." Is this possible?

#### KPIs

- [ ] updating the host org info

#### Key Deadlines

- [ ] Asap

**Comment by Melechuga** [comment]
@kristinashu Does this seem possible within the logo farm? Thank you!

**Comment by xmatthewx** [comment]
That would break the pattern used with the rest of the logos. They could add it to the text in the logo file itself, but to be honest, nobody is likely to read text of that length and size. I'm not sure that it's in their best interest.

**Comment by kristinashu** [comment]
@Melechuga sorry for the delay! I agree with what Matthew is saying, to be consistent with the other orgs we shouldn't add it to the blue text but we could add it to their logo but their text is already very small.

Is that ok with them or is it still an issue?
