### ISSUE TITLE
Science site: More comps + engineering spin-up

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#775]
For the April 8 heartbeat of this multi-heartbeat project, we will move closer to finishing the design work, and will start prepping for the build phase. Specifically, we'll do the following:

 - [x] Comps for Project landing page
 - [x] @acabunoc will write up notes about the work to be done based on wireframes, and will work with @simonwex on a database ERD (as discussed on Tuesday)  
 - [x] engineers will be assigned and will:
  - [x] spin up a new branch
  - [x] get up to speed on Django (which is what we'll use for the databased components of the site, e.g. events and projects)
  - [ ] prototype some of the smaller data structures in wireframes, make sure they work with Onesie

**Comment by acabunoc** [comment]
Notes from the code walkthrough yesterday: https://public.etherpad-mozilla.org/p/sciencelab-code-walkthrough

**Comment by acabunoc** [comment]
Unfinished ERD

https://www.draw.io/#G0B9UZnVcaoMU6N0hNbzAxYWdXZ1E

**Comment by hannahkane** [comment]
API repo is here: https://github.com/mozilla/api.mozillascience.org

This week engineers are building scaffolding for both api server and client server.

Design and copy for Projects page are progressing. See https://github.com/mozillascience/site/issues/105 for latest. Comps might be at risk due to not yet having final copy + designer is at Tribe for part of the week. (But maybe not at risk...not sure.)

**Comment by hannahkane** [comment]
This ticket is mostly on track. ERD has been revised, comps have been reviewed by designers, but need revisions + feedback from Science team.

**Comment by hannahkane** [comment]
This is going to close. Will open a new ticket for next heartbeat's work on this project.
