### ISSUE TITLE
Release CMS v1

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#776]
CMS v1 will include the ability to publish a simple page to the Teach site.

@simonwex - please add more details if you have them, but afaik, the remaining work is:
 - [ ] Resolve Calypso hosting issue
 - [X] Create plan for soliciting feedback from Ed Hub team members (@xmatthewx and I are working on this tomorrow)
 - [ ] Would be great to also migrate two existing Teach pages to the CMS (https://github.com/mozilla/teach.mozilla.org/issues/1758)

**Comment by hannahkane** [comment]
@simonwex - could use an update on the Calypso hosting issue, please :)

**Comment by hannahkane** [comment]
sounds like this is going to roll into the next heartbeat. will keep here for now, but blocked on some stuff within our control and some stuff outside of our control.

**Comment by hannahkane** [comment]
This is definitely rolling into the next heartbeat, so reflecting that here.

**Comment by hannahkane** [comment]
As I understand it, this is still blocked.

**Comment by simonwex** [comment]
@cadecairos do you mind updating with the most recent happenings from Automattic?

**Comment by cadecairos** [comment]
The work in https://github.com/Automattic/wp-calypso/pull/4506 seems to have stalled for the moment. I'm going to try and push it to a working state once I get our prototype code up to date with upstream.

**Comment by hannahkane** [comment]
Rolling into the next heartbeat, though progress was made this heartbeat! (@cadecairos - feel free to add details here if you can)

**Comment by cadecairos** [comment]
Sure thing!

@mavis re-implemented our changes on top of Automattic's latest version of wp-calypso :tada: 

I then pulled in Automattic's WIP branch that implements OAuth, and also pulled in my Heroku compitible Docker code, made some fixes to the Oauth code, and managed to get a deployed build.

There are a few UX glitches when signing in, and the live preview needs to be re-done ( @alicoding? )

:tada: :tada: :goat: :tada: :tada:

**Comment by simonwex** [comment]
```
 __     ________  _____ _____ _____ _ _ _ 
 \ \   / /  ____|/ ____/ ____/ ____| | | |
  \ \_/ /| |__  | (___| (___| (___ | | | |
   \   / |  __|  \___ \\___ \\___ \| | | |
    | |  | |____ ____) |___) |___) |_|_|_|
    |_|  |______|_____/_____/_____/(_|_|_)
                                          
```
Thanks so much for pushing on this! @mmmavis and @cadecairos

**Comment by hannahkane** [comment]
This is very exciting!

@ldecoursy and I have started testing on the staging server. I've filed a few bugs in the [Calypso repo](https://github.com/mozilla/wp-calypso/issues), but I don't think any of them are blockers. They aren't problems with the Calypso functionality, rather they are issues related to styling and layout.

**Comment by hannahkane** [comment]
I'm going to close this ticket; it's a bit stale. Next steps have been filed:
 - https://github.com/MozillaFoundation/mofo-devops/issues/332
 - https://github.com/MozillaFoundation/plan/issues/807
