### ISSUE TITLE
Prototype for Clubs Event Report

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#777]
As per discussion with @amirad @davidascher and @xmatthewx, we will work on building a Clubs Event Reporting workflow that does the following:
 - [ ] allows CCs to fill in a form with details of their event (@amirad has specific specifications for this)
 - [ ] generates a gallery-like viewing experience for people to browse through event reports

@xmatthewx - want to file more detailed tickets for this after your meeting with @amirad on Monday? Maybe in the Teach site repo?

**Comment by xmatthewx** [comment]
@simonwex – we'll likely need a bit of engineering support toward the end of the heartbeat if we want to host this somewhere other than github pages. No complicated requirements.

**Comment by xmatthewx** [comment]
@flukeout will likely drive this design prototype

**Comment by xmatthewx** [comment]
Gathering notes and requirements here: https://docs.google.com/document/d/1KaKMpS_J285UR4fCsonwBNqclKmSKCqlDEsSNSwm_ls/edit

**Comment by xmatthewx** [comment]
cc @adamlofting to connect with other network survey wisdom

**Comment by xmatthewx** [comment]
@flukeout will create a repo. Let's a drop link here.

**Comment by flukeout** [comment]
**Links**
* Repo https://github.com/mozilla/clubs-events
* Prototype dashboard mozilla.github.io/clubs-events
* Google form http://goo.gl/forms/wDc7b8AqI3
* Spreadsheet o' fake data [link](https://docs.google.com/spreadsheets/d/1QHl2bjBhMslyFzR5XXPzMLdzzx7oeSKTbgR5PM8qp64/edit?usp=sharing)

cc @xmatthewx

**Comment by xmatthewx** [comment]
Lots of progress this heartbeat. We'll review next Wednesday with @amirad and @KGorr, and make a plan to test with a few clubs.
