### ISSUE TITLE
Move Mozilla Learning Discourse to new domain

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/plan#778]
The Mozilla Learning Discourse forum is still on the Webmaker domain but should move - to connect to teach.mozilla.org or new URL, dependent on #764 

Related ticket: MozillaFoundation/mofo-devops#253

**Comment by xmatthewx** [comment]
@kristinashu - According to your IA work, what's the ideal URL for a Mozilla Learning [forum](https://discourse.webmaker.org/)?  

@simonwex - Does Discourse need to live on its own subdomain? Or could learning.mozilla.org/forum work if that's the ideal option?

**Comment by kristinashu** [comment]
learning.mozilla.org/forum would definitely be ideal

**Comment by hannahkane** [comment]
just noting that this is blocked on https://github.com/MozillaFoundation/mofo-devops/issues/310

**Comment by hannahkane** [comment]
Since https://github.com/MozillaFoundation/mofo-devops/issues/310 is in the next heartbeat, and is a prereq for this, I'm moving this one to the next heartbeat as well.

**Comment by hannahkane** [comment]
This is now unblocked. win!

**Comment by hannahkane** [comment]
Moving this to the next heartbeat to be triaged by devops team.

**Comment by hannahkane** [comment]
Moving this to current heartbeat, which reflects the related devops ticket.

**Comment by hannahkane** [comment]
This was done.
