### ISSUE TITLE
Redirect gear.mozilla.org traffic to Blog Post: Gear Store Closed by April 1

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/plan#779]
#### Overview
The gear store is closing and all traffic to gear.mozilla.org should be redirected to:
https://fundraising.mozilla.org/the-online-gear-store-closes-march-31/

The post text will be updated to reflect gear store is closed and highlight customer service contact email. 

#### Key Deadlines

- Gear Store is set to close March 31, so the redirect should be in place by early morning EST April 1. 

cc @simonwex @HPaulJohnson

**Comment by hannahkane** [comment]
I believe this is done, so closing.
