### ISSUE TITLE
Create a wayfinding visual of the strategy overview for slide decks

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/plan#780]
Create a visual that captures the 4 engine pieces (agenda setting, leadership, advocacy and ops that support it) that include clear goals for each. This helps give broader context to the user and helps as a legend (that correspond with coloured slides) at the beginning of slide decks of what is to follow. 

/cc @OpenMatt @samanthaburton @lovegushwa

**Comment by xmatthewx** [comment]
@OpenMatt – is this still needed? High priority? Or can we close this?

**Comment by hannahkane** [comment]
Removing from April 22 milestone

**Comment by hannahkane** [comment]
I'm going to close this. Please re-open if it's still needed.
