### ISSUE TITLE
Operations: auto-populate finance contract from Google Form 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/plan#781]
Details to come from Pamela

**Comment by HolaHewitt** [comment]
[Contract Initiation Form.docx](https://github.com/MozillaFoundation/plan/files/230091/Contract.Initiation.Form.docx)

With our current contract process, people add the contract detail in no particular order in the bug.   Operations then basically cuts and pastes the detail into a contract template and formats it to make it look pretty.

What end up happening often is that there is a lot of back and forth for missing detail.  As a current solution to make the process a little easier for people is to have a form that they simply populate with the specific data outlined.

What would be awesome is if, as they filled out out this form, it populated to the actual contract.   As an FYI, as contract terms change and get tweaked, it's not ideal to have them simply fill out the contract, although that may change in the future

**Comment by hannahkane** [comment]
@OpenMatt - is this something you were going to do? Do you need engineering support?

**Comment by hannahkane** [comment]
Removing from April 22 milestone since it has passed
