### ISSUE TITLE
Build Digital Skills Observatory (static) website

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#782]
#### DARCI

Driver:
A: 
R: 
C: @secretrobotron
I: @LauraReynal

#### Overview

We would like to have a public-facing website to display information about the Digital Skills Observatory project. It will carry on throughout the rest of the year, during which @LauraReynal and I will have to explain the project many, many, many times. With a simple, static site (like https://mozilla-foundation-research.herokuapp.com/globalweb/), we can refer people to information that we're carefully designed for general consumption.

#### Links

* Temporary site: http://secretrobotron.github.io/digital-skills-observatory/
* Brief: https://docs.google.com/document/d/1k9-zuWNejeBt-2T7K9umJfoZRbERVh8o_AS4SaIPhZE

#### KPIs

- [ ] Design for single (or very few) page website that incorporates [the brief](https://docs.google.com/document/d/1k9-zuWNejeBt-2T7K9umJfoZRbERVh8o_AS4SaIPhZE) (above).
- [ ] A standalone site that we can host on our ghost blog (similar to https://mozilla-foundation-research.herokuapp.com/globalweb/)

#### Key Deadlines

- [ ] April 13 - Design draft completed for design crit
- [ ] April 15 - Final design completed
- [ ] April 29 - Website implemented
- [ ] April 22 - Website hosted
- [ ] April 28 - @LauraReynal and @secretrobotron host a workshop with DSO partners in Kenya

**Comment by secretrobotron** [comment]
For the record, this was previously brought to the design crit call, where it was torn apart by the sharp, menacing teeth of the design team: https://public.etherpad-mozilla.org/p/designcrit#lineNumber=142

(They were quite helpful.)

**Comment by xmatthewx** [comment]
Any ideas where this fits in the Mozilla information architecture? See: https://github.com/MozillaFoundation/plan/issues/764#issuecomment-201051122 and [the doc](https://docs.google.com/presentation/d/1MOhf0PSvCU2flniNsbl1FW0xPi0ZnJHJJEZ3qlyAcrE/edit#slide=id.g11d935e442_0_129).

**Comment by secretrobotron** [comment]
@xmatthewx it fits into `research` pretty easily, and perhaps `learning`. In this case, at the moment, it doesn't need to connect to much else, but it should be eventually connected to initiatives concerning Web Literacy at least.

If we're handing the site to people personally and specifically, I suspect all we need to care about is the URL, which could easily use mzl.la in the interim (which we do a lot of now).

**Comment by xmatthewx** [comment]
@secretrobotron - let's discuss how this can fit within Learning. A daisy-chain of subdomains sounds dangerous. As a sub-page, we'll want to consider how it connects to the layout and brand of the Learning site. 

Beyond URLs, we should aim to connect and concentrate resources and brand. There's a tradeoff between a bit of bespoke style and buttressing this project with its connection to our other initiatives.

Want to schedule a chat? Or discuss here?

cc @hannahkane @simonwex

**Comment by hannahkane** [comment]
@xmatthewx - are you free at 3pm ET today? Bobby and I are planning to discuss then.

**Comment by xmatthewx** [comment]
Sorry I wasn't able to join the impromptu chat. Did you talk? Discover anything? @secretrobotron – I'm eager to learn what you need and figure out how I can help you land it.

**Comment by hannahkane** [comment]
Short story is I don't want lack of capacity to be a blocker for @secretrobotron. I think if he can make the changes recommended by the design team at crit, he should feel free to continue to host it as is (heroku) for now.

I think the longer-term plan has the following dependencies:
 - [ ] CMS release (already ticketed)
 - [ ] IA changes (partially ticketed, but I don't think we've agreed on a solution for research specifically)
 - [ ] maybe a brand conversation - will follow up with specific stakeholders on this shortly

**Comment by hannahkane** [comment]
@secretrobotron - are you good to make recommended changes on the heroku site for now?

**Comment by secretrobotron** [comment]
@hannahkane yeah, definitely. Already underway. Thanks for following up.

**Comment by secretrobotron** [comment]
@Obadha and I will be putting a version of the site up, and we'll pass it around for review when it's done. Moving to next milestone.

**Comment by secretrobotron** [comment]
First rev of site is done: http://mozillafoundation.github.io/digital-skills-observatory/. @Obadha and I are going to code-review it soon. It would be great to bring to design crit too so we can improve it. cc @xmatthewx

**Comment by xmatthewx** [comment]
The site is looking nice. We'd love to have it at crit. Or, if the timing of crit isn't ideal, we can schedule something with a designer or two. I'll be out on PTO next week, so reach out to others.

Question regarding copy: "Studying the impact of digital skills on smartphones and digital financial services." Is this the impact on smartphones or impact on the people using them?

**Comment by secretrobotron** [comment]
Hahah definitely not only smartphones. I hope we have impact on people first. Thanks for catching.

**Comment by hannahkane** [comment]
hey @secretrobotron - I'm rolling this into the current heartbeat, since May 20 has passed. Do you need design or dev resources on this?

**Comment by secretrobotron** [comment]
No, I think we can close this. The site is more or less done. :)
