### ISSUE TITLE
Facilitate sunsetting of Gigabit city sites

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#783]
## DARCI
Driver: @hannahkane
Accountable: @simonwex 
Responsible: Content team (design/engineering/devops), @jenntbeard (content changes)
Consulted: @LindseyFrost @chrislarry33 
Informed: @jamjwait Katie (apologies! I don't know Katie's github name) @ldecoursy 

**Important first step**: We need to decide which pieces of this we can do this before the May 16th deadline (corresponds to Gigabit cities announcement), so that backup plans can be put in motion if necessary.

At a minimum, we must:
 - [ ] update content to reflect programmatic changes (specific changes tbd by @jenntbeard)

Additionally, we might:
 - [ ] determine a solution for displaying portfolios and calendars on main gigabit site (this is a necessary prerequisite to shutting down the individual city sites)
 - [ ] migrate blog content to main MLN blog (https://github.com/MozillaFoundation/mofo-devops/issues/300)
 - [ ] display a blog feed on main gigabit site
 - [ ] apply new bootstrap styles
 - [ ] migrate content to the CMS, so that it is editable by staff
 - [ ] move the gigabit site to new domain (learning.mozilla.org/gigabit) (dependency: moving teach.mozilla.org to learning.mozilla.org) 

## Reference Links
* [Current Gigabit site](https://www.mozilla.org/en-US/gigabit/)
* [Current Hive Chattanooga site](http://hivecha.org/)
* [Current Hive KC site](http://hivekc.org/)

**Comment by xmatthewx** [comment]
Are we looking for a full redesign or a cleanup of the current site? Can you share links to to these sites?

**Comment by hannahkane** [comment]
Thanks, @xmatthewx. Just added links to the current sites to the first comment; apologies for not doing that initially.

@sabrinang did do some design work awhile back, before we knew we were changing the IA and before we had the new bootstrap: https://github.com/mozilla/teach.mozilla.org/issues/1473. 

now that we have bootstrap and an eventual new home on the Learning hub site, we probably want to reconsider how we treat this.

**Comment by hannahkane** [comment]
Given the number of high-priority MLN items, we've decided to push this back to after London, even though it means missing the May 16th new city announcement.

**Comment by hannahkane** [comment]
This is all being tracked on the Learning site repo (with the exception of the blog migration), so closing here as an unnecessary duplicate.
