### ISSUE TITLE
(July) Design Open Web Fellows year-one report

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/plan#784]
#### DARCI
Driver: @kevzawacki
A: @Melechuga 
R: ?
C: @brettgaylor @xmatthewx 
I: @HPaulJohnson 

#### Overview

We're creating a publication to report on the first year of the Open Web Fellowship program. Geared toward an audience of direct stakeholders (Ford Foundation) and like-minded allies (Berkman Center, EFF, New America), the report will:

-- Serve as a record of the program’s genesis and first year 
-- Document program accomplishments and impact 
-- etc.

The report will be brief (~ <10 pages). The aim is to produce a first draft by May 2016, and release the final publication sometime between July and September 2016. 

Kevin is handling all copy -- but we need a designer to make it look :+1: 

#### Links

-- [Berkman Center report (benchmark)](https://cyber.law.harvard.edu/sites/cyber.law.harvard.edu/files/2015-10_fellowsreportPRINT.pdf)
-- [Publication outline](https://docs.google.com/document/d/1qkI0MW53nebpTUGSG8gQg54DpRNR2-BpkFEq3eaoxeo/edit#bookmark=id.q2j3yr83moox)

#### KPIs

- [ ] Design work for a brief PDF report

#### Key Deadlines

- [ ] TBD -- possible first draft by the end of May?

@xmatthewx Does this sound feasible?

**Comment by xmatthewx** [comment]
End of May is reasonable. Are you ready for design at this stage, or just design guidance? When might a rough draft of content be done?

**Comment by brettgaylor** [comment]
Huzzah!  Thank you for starting this.  It would be great to have this on July 18th for a meeting of host organizations, but it isn't critical.

**Comment by KevZawacki** [comment]
@xmatthewx Thanks! All we have is an [outline](https://docs.google.com/document/d/1qkI0MW53nebpTUGSG8gQg54DpRNR2-BpkFEq3eaoxeo/edit#bookmark=id.q2j3yr83moox) at the moment -- but if a designer is able to offer guidance based on that, we'd be all ears. 

We should have a rough draft in mid-May.

**Comment by xmatthewx** [comment]
@lovegushwa - do you think this falls more on your side of the aisle?

**Comment by brettgaylor** [comment]
This is leadership content fwiw

**Comment by xmatthewx** [comment]
cc @hannahkane

**Comment by hannahkane** [comment]
Changing to June 3 milestone to correspond with our heartbeat schedule, but adding deadline to title

**Comment by xmatthewx** [comment]
@hannahkane will check in to discuss scope, impact, plan, etc, and prioritize among other infrastructure projects. 

Though I don't have all the context, I wonder if this wouldn't be more efficient and effective as a webpage on the OWF site, instead of a PDF. That would require less layout design and would be more accessible in the short and longterm.

**Comment by hannahkane** [comment]
Like @xmatthewx I'm wondering if we could build this as a webpage, potentially using the CMS, which would make this easily editable by staff members. Based on the outline, it looks like we'd need to provide design support for some graphical elements (timeline, maps, treated photos), but otherwise, this could likely be achieved with existing layouts and styles (along with a few new ones - i.e. pull quotes).

Another web-based idea would be to create a template like the one we made for the [Web Literacy whitepaper](http://mozilla.github.io/content/web-lit-whitepaper/). That page is editable by staff using markdown only.

@Melechuga @brettgaylor @KevZawacki - let us know what you think of these possibilities. Also happy to talk through this over Vidyo.

**Comment by hannahkane** [comment]
ping @Melechuga @brettgaylor @KevZawacki - we're trying to get organized for the next few heartbeats. Would be useful to know what you think of the webpage idea.

**Comment by Melechuga** [comment]
@hannahkane @xmatthewx I like the idea of keeping this online. The optics of having a PDF-download option would be an interesting thing to talk about. 

Can we be intentional about building a publications section that could be updated? For reference, the Berkman Center's online version of their publication is http://berkmanlessons.net/ (not very pretty).

**Comment by hannahkane** [comment]
Thanks, @Melechuga. I think a publications section could be a good candidate for when we release the CMS tool, because it will allow you to easily update this kind of web-based content without developer involvement.

Does it make sense to talk about this early in the May 20th heartbeat (which starts on May 9th)? It sounds like we'll be closer to final content by then, and the CMS may be released by then as well.

**Comment by Melechuga** [comment]
Sure @hannahkane let's talk about this for the May 20th heartbeat. Excited to see this moving forward!

**Comment by hannahkane** [comment]
Just sent an invite. It's for later in the heartbeat, due to schedule conflicts, but I think this still gives us time to deliver for the July deadline.

**Comment by KevZawacki** [comment]
Comms update: Draft one of the report available [here](https://docs.google.com/document/d/15ozoyElpjgfhCRA9t1PgqRx-KrDtL4k2yDfn9t8Rm5s/edit) (copy ~85% of the way there)

**Comment by hannahkane** [comment]
Good discussion today. Covered the following:
 * this is a content-heavy document, with only a few design elements—a few bar graphs, a (potentially but not necessarily interactive) map, some photos, and some not-yet-in-onesie design elements like pullquotes
 * the web is a good primary place for it, but a print option is a requirement
 * ability for staff to edit without developer/designer intervention is a big plus

We talked about a couple options: using the CMS or using gh pages. Will discuss both options with the Content team at the start of the next heartbeat and will share our recommended approach with @Melechuga and @KevZawacki then. In the meantime, I'll file some tickets for the graphic work that we'll need to do regardless.

**Comment by hannahkane** [comment]
Moving this to June 17th heartbeat / moving the website updates to the current heartbeat to reflect the order of the deadlines.

Filed a ticket in the Advocacy repo to track specific tasks: https://github.com/mozilla/advocacy.mozilla.org/issues/165

**Comment by KevZawacki** [comment]
@hannahkane @Melechuga @brettgaylor 

Copy has been reviewed and revised -- I think we're ready for design!

[Here's the latest](https://docs.google.com/document/d/15ozoyElpjgfhCRA9t1PgqRx-KrDtL4k2yDfn9t8Rm5s/edit).

@hannahkane What are the next steps? And just to confirm: If we need to make copy tweaks at a later date, it should be relatively easy given the whitepaper model, right?

**Comment by hannahkane** [comment]
Thanks, @KevZawacki. The next step is to have @kristinashu start work on this, pending progress on the OWF website changes which I believe we want to implement sooner. There are some things in the [design ticket](https://github.com/mozilla/advocacy.mozilla.org/issues/165) that we still need—photos and data for bar graphs and maps.

And, yes, making changes to the copy will be possible via Github pages. We can provide training for any staff who might be making edits.

**Comment by KevZawacki** [comment]
@hannahkane Thanks! If I'm a blocker on any of the design ticket stuff, just let me know.

**Comment by hannahkane** [comment]
@kristinashu - assigning to you, but note that this will extend beyond the June 17th heartbeat (obviously, since we're going to be in London in the meantime!).

**Comment by kristinashu** [comment]
Thanks, I think we're all good for copy and I'll use the graphs from [this ticket](https://github.com/MozillaFoundation/plan/issues/789) - are these all the graphs we will need? 

Also, are there any photos we could use?

**Comment by KevZawacki** [comment]
@kristinashu There are some OWF photos in [this blog post](https://blog.mozilla.org/netpolicy/2015/10/08/4-days-in-nyc-for-the-open-web-fellows/). 

@Melechuga, aware of any others? Maybe we use screenshots from their [capstone presentations](https://www.youtube.com/watch?v=0lIoedFRBSQ&list=PLOoIZTxzMxeD3-BmQup9RD1YjsCycKWnP&index=4)?

**Comment by kristinashu** [comment]
Thanks @KevZawacki!

I've started a folder with screen caps from the presentations and the blog post:
https://docs.google.com/a/mozilla.com/document/d/1ycv1yIpt5r56IGsNCeL07hoJLjVKx5kmGVeVN32HNZo/edit?usp=sharing

I think the blog post images have been compresses a little so if anyone has the originals, or any other images, please add them here or to the folder.

**Comment by hannahkane** [comment]
Assuming this will continue into the next heartbeat.

**Comment by kristinashu** [comment]
Shared initial comps of the design https://redpen.io/p/qa0d7b5c69cd064069 and Hannah has scheduled a tentative meeting for next week to review the design and for Luke to lead a tutorial on how to create and edit the github page.

**Comment by kristinashu** [comment]
Design and content is done. Luke is updating the template https://github.com/mozilla/advocacy.mozilla.org/issues/203 then Kevin will add content https://github.com/mozilla/advocacy.mozilla.org/issues/204

**Comment by brettgaylor** [comment]
This is looking great!  I'm happy to continue to be a C on this, even though its now outside of my scope in the media work :) I'll still be the point of contact for Ford, one of the primary audiences for this.

**Comment by hannahkane** [comment]
I think we can close this now, yes? I know we'll continue to make updates, but the bulk of this work is done, so closing. Please re-open if you object. :)
