### ISSUE TITLE
Test clubs event reporting prototype

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#786]
#### DARCI
Driver: @xmatthewx
A:
R: @amirad 
C: @flukeout @KGorr 
I: 

#### Overview

We have built an event reporting tool, just about ready to test with a handful of club leaders. This heartbeat, we will finish a few features and then use it to gather real info on real events. After, we will gather feedback and iterate. 

#### Links
 - Prototype dashboard https://mozilla.github.io/clubs-events
 - Repo https://github.com/mozilla/clubs-events
 - Google form http://goo.gl/forms/wDc7b8AqI3
 - [Notes and requirements](https://docs.google.com/document/d/1KaKMpS_J285UR4fCsonwBNqclKmSKCqlDEsSNSwm_ls/edit)
 - [Project brief](https://docs.google.com/document/d/1LiAVKY_79Nl-9IuaeR4XRSweSuq9izQY3nHiWRQdHqA/edit?ts=56e85b45) (covers broader initiative)

**Comment by hannahkane** [comment]
@xmatthewx - can we close this and file follow-ups as needed?

**Comment by xmatthewx** [comment]
Sure thing. @amirad @flukeout – at some point, let's do a focused test and assessment of the tool. Maybe in July?

**Comment by amirad** [comment]
yes @xmatthewx - do we know if those edits are in the next heartbeat? I've shared the tool with some community to start testing but was waiting on the rest of the updates before doing a full share out.

**Comment by xmatthewx** [comment]
Let's be sure to discuss during our Organizing kickoff with @hannahkane and @flukeout on Monday.
