### ISSUE TITLE
Design review of Teachable module for Club Captains

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#787]
Will provide more information to designer assigned, but the tl;dr is we have an online training module we're going to offer Club Captains (it will be a mandatory part of the onboarding process). Could use a design review and potential design/branding support in terms of graphics, illustrations, and logos. 

cc @amirad

**Comment by amirad** [comment]
cc @Carotejada

**Comment by Carotejada** [comment]
Great to have you and your team [here](http://mozilla.teachable.com/) @hannahkane collaborating with some design love.

**Comment by xmatthewx** [comment]
cc @flukeout will provide design review.

**Comment by hannahkane** [comment]
@xmatthewx or @flukeout - is there another ticket somewhere where people can follow along?

**Comment by flukeout** [comment]
It lives here https://github.com/MozillaFoundation/Design/issues/162

**Comment by hannahkane** [comment]
Closing this - bulk of the work is done. Follow-up tickets to be filed in other repos.
