### ISSUE TITLE
Design review of Teachable

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#788]
#### DARCI
Driver:
A:
R:
C: 
I:

#### Overview

Hoping that @hannahkane can provide some context and scope. 

#### Links

http://mozilla.teachable.com/

cc @lovegushwa

**Comment by hannahkane** [comment]
sorry, filed a dupe ticket here: https://github.com/MozillaFoundation/plan/issues/787

**Comment by xmatthewx** [comment]
Yours has more labels and was filed 8 minutes before mine. :pineapple: Closing this one.

**Comment by hannahkane** [comment]
If we're evaluating ticket quality based on label count, I totally win. I am the master of labels. :crown:
