### ISSUE TITLE
Visualizations for Open Web Fellow statistics 

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#789]
#### DARCI
Driver: Melissa
A: 
R: @adamlofting 
C: @KevZawacki 
I: @brettgaylor 

#### Overview
Creating visualizations of the geographic and skills data from Year 2 Open Web Fellows applications. These can be used in presentations (e.g. Ford even on May 4th), and in the publication @KevZawacki is putting together about the year in review.

Will also need design help; is @kristinashu available to help with this next week?

#### Links
https://docs.google.com/spreadsheets/d/1BOm37O5cF0B4EiIWy78fdFVRW5R7Ma4fxbQSad5XPTc/edit#gid=1667159379

#### KPIs

- [ ] ~~Interactive heat map of geographic data~~
- [x] Graph of "skills" data
- [ ] Possible graph/map comparing skills + geo data.

#### Key Deadlines

- [x] April 29: Basic map to use in Ford presentation (May 4)
- [ ] June xx: Full maps/graphs depicting all things useful for larger publication (July 18)

**Comment by kristinashu** [comment]
Unfortunately I'm swamped with the science site for the next two heartbeats. @xmatthewx can you recommend someone?

**Comment by adamlofting** [comment]
I've spent some time visualizing this data in Tableau today.

These won't win any design awards, but they should be good in terms of clearly communicating the data.

# Map visual:

![applicants by continent](https://cloud.githubusercontent.com/assets/1901816/14673600/c63017ee-06f6-11e6-94c3-e880e648f223.png)

# Year on Year applicants by continent

![year on year applicants](https://cloud.githubusercontent.com/assets/1901816/14673607/cf05feec-06f6-11e6-8f07-af0139e31b12.png)

# Selection rounds by continent

![selection by continent](https://cloud.githubusercontent.com/assets/1901816/14673612/d4307406-06f6-11e6-87d8-95f3d3ebfccb.png)

# Skills split by form input type

![skills](https://cloud.githubusercontent.com/assets/1901816/14673621/d924363c-06f6-11e6-809b-f5778db09c95.png)

Image files for these can be downloaded from:
https://drive.google.com/drive/folders/0B3UkMzboH_XAVDBEc3RieDBwazA

**Comment by Melechuga** [comment]
@adamlofting These are helpful; thanks! I really like the "selection rounds by continent" graph; wondering if there's a way to show that by percentage.

For the geographic data, would it be possible to a) make it interactive -- i.e. show the number of applicants when hovering over, or just have the number in the circles? and b) could we do one with all of the individual countries colored in with color-gradation depending on the percentage of applications?

**Comment by adamlofting** [comment]
Yes to all those things (except for the interactive part).

These are the new / amended files, which have also been update in the Google Drive folder.

![applicants by continent](https://cloud.githubusercontent.com/assets/1901816/14745075/81edf040-08a1-11e6-8b68-5f58991fb0c5.png)
![countries](https://cloud.githubusercontent.com/assets/1901816/14745074/81ec5be0-08a1-11e6-9f5e-b7436963d1f0.png)
![selection by continent](https://cloud.githubusercontent.com/assets/1901816/14745076/81f11d1a-08a1-11e6-9b81-75318709f2f0.png)

**Comment by Melechuga** [comment]
Thanks @adamlofting! This is great for now; I think the last thing would be to make the countries map interactive -- if possible -- so that we could scroll over the countries and see the numbers. But that's not vital for now.

A conversation around how to best show the "skills" might be useful too, especially once we've identified the individual fellows.

**Comment by Melechuga** [comment]
cc @natalieworth 
Thanks!

**Comment by natalieworth** [comment]
@Melechuga Could you link or send the slide content google doc when you get a chance? I'm just working on formatting some basic slides, but could also add in the sections. :) Thanks!

**Comment by Melechuga** [comment]
@natalieworth Apologies for the delay! Content for my slides here: 
https://docs.google.com/a/mozilla.com/document/d/1XSdw3p-yIxw_UmSJlWvgMMb7gu1k3437HZcmmkTr4Z0/edit?usp=sharing

I think this links to the conversation about the slidedeck template [here](https://github.com/MozillaFoundation/plan/issues/794).

**Comment by natalieworth** [comment]
@Melechuga perfect, I'll send this asap today!

**Comment by hannahkane** [comment]
@Melechuga - okay to close this ticket now?

**Comment by Melechuga** [comment]
@hannahkane Yup! Thank you.
