### ISSUE TITLE
Finalize initial tool prototype

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#79]
Based on our initial user testing, the goal for this sprint is to wrap up the prototype of the unified tool. In order to do this with some confidence for moving into the build phase, we need to answer a few questions:

- How does this experience port to mobile? (Sketch / Wireframes) 
- How would we scaffold social on top of this experience? (Sketch / Wireframes)
- How does this connect with existing Webmaker pieces, like Explore? (Sketch)
- What is the UX for the component / code editor? (In prototype)
- Refinements from user testing (In prototype)
- "View mode" (prototype)

### RACI
Phase: Design / Build / Ship
Owner: @secretrobotron 
Decision: @thisandagain
Lead design: @flukeout
Lead dev: @simonwex
Quality: @cassiemc

**Comment by davidascher** [comment]
Can you clarify what is meant by "unified"?  Is it unified across mobile + desktop?

**Comment by secretrobotron** [comment]
Yeah, `Unified = Mobile + Desktop`. They've had little to do with each other hitherto in @flukeout's designs. But, the goal is to bring them together

**Comment by davidascher** [comment]
Cool.  I'd say then that we should probably do some more design on that
unification before we build too much...

**Comment by thisandagain** [comment]
Agreed. Updated SOW.

**Comment by simonwex** [comment]
Confirmed I can be dev.

**Comment by flukeout** [comment]
Here is the usertesting report from Round 1
https://docs.google.com/document/d/1X1DdCedqWdXtdBlw3HJf0ioypQQ-Nv4_gurmztTtEx4/edit

**Comment by flukeout** [comment]
@thisandagain what does ***RACI*** mean up there?

**Comment by thisandagain** [comment]
@flukeout http://lmgtfy.com/?q=raci :wink:

**Comment by flukeout** [comment]
Oh we've got a grant from the Royal Australian Chemical Institute Incorporated? Sweet!

**Comment by secretrobotron** [comment]
:boom:

**Comment by secretrobotron** [comment]
State of the art:
* http://flukeout.com/examples/desk7/
* http://flukeout.com/examples/animations/

_"Collect your jaw from the floor." -Luke_

**Comment by secretrobotron** [comment]
### *Update*
* @flukeout made some great stuff
  * animations: http://flukeout.com/examples/animations/
  * tiles: http://flukeout.com/examples/desk7/
* combining mobile and desktop is going to be difficult
  * @flukeout to make some wireframes and do a bit of testing wrt screen resolution and tile size

**Comment by cassiemc** [comment]
omg, I love the templates @flukeout! Super fun and make me want to start making right away. Nice work.

Luke and I 1:1'd today and I wanted to acknowledge that we haven't tackled how the Webmaker App and this New Tool™ coalesce into a unified Webmaker UX. Not saying we need to solve for this now in this heartbeat by any means, but we should keep it in mind before Luke gets lost down the animation-rabbit-hole. I almost wonder if some of the features Luke's working on could be broken apart into separate components. And if that might make it easier to imagine a "component builder" overlapping with the current webmaker app builder. Just a thought.

**Comment by secretrobotron** [comment]
Thanks @cassiemc. I'll let @flukeout flesh out an answer, but we spoke a little bit about that topic yesterday. Your Break-it-Apart™ idea is compelling, and it curbs some of my worry about porting that to mobile (although, it would be good to test @flukeout's work on FFOS/Android asap).

At the very least, in this heartbeat, we want to have some framing for how we get this experience onto mobile. Doesn't need to be integrated into the prototype by any means, but maybe some wireframes.

**Comment by thisandagain** [comment]
Will follow-up in 1:1s today, but my hope is that this line of discussion is the focus for our work week.

**Comment by OpenMatt** [comment]
@secretrobotron can you update status here before Heartbeat Planning meeting? (1pm ET)

**Comment by thisandagain** [comment]
Some additional prototypes / concepts:
http://flukeout.com/examples/desk7/
http://flukeout.com/examples/slidercode/
flukeout.com/examples/animations/
