### ISSUE TITLE
Production plans for State of the Web

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#793]
I believe that we have plans for State of the Web. It would be good to discuss what this plan might require from the production team in the future. 

@OpenMatt - Who might have the most knowledge to share? This may or may not also help us better understand where hub specific Research could be collated.  cc @hannahkane

**Comment by hannahkane** [comment]
I don't think anything happened on this during the last heartbeat. @OpenMatt - can you answer @xmatthewx's question above?

In the meantime, rolling into the current heartbeat for discussion.

**Comment by xmatthewx** [comment]
I think that @samanthaburton might have some insight. Sam – we're trying to predict the future and, in broad strokes, guess what we might produce in Q3/Q4 (so we can make sure we have design/dev available).

**Comment by samanthaburton** [comment]
Yes! I do have some useful info - namely that the Marketing team is going to be leading on production/design for State of the Web. They're likely going to use the same agency that's working on Mozilla branding overall. 

We're doing a bit of creative brainstorming about what this might look like with @HPaulJohnson @brettgaylor @lovegushwa later this week, which will inform the brief that MoFo + Marketing put together to get the agency rolling. If one of you would like to join you're more than welcome, just let me know.

Also, FYI most recent brief describing State of the Web [is here](https://docs.google.com/document/d/1ENJzPXCLk5-VxsR8tIisfVOO4DnUM1HQPvqLQDxznCs/edit) to give you an idea of where we're heading with the project overall.

**Comment by xmatthewx** [comment]
Excellent. Sounds like a solid plan.
