### ISSUE TITLE
Create slide deck template for Open Web Fellows @ Ford

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/plan#794]
#### DARCI
Driver:
A: Jordan
R: Natalie
C: Brett/Melissa
I:

#### Overview
This year's open web fellows, plus Melisa Brett & Ford staff, are giving a presentation at the Ford Foundation on May 4th.

We are working with a communications firm (spitfire communications) to create the talks, but we need to take care of the design of the deck.

It should follow the colour scheme that Christina started here:
https://advocacy.mozilla.org/open-web-fellows/

We would need some style direction for how to present images/photos, and have typographic choices.

Other than that requirements are broad

#### Links
https://advocacy.mozilla.org/open-web-fellows/

#### Key Deadlines

-would be great to have these available for fellows to build presentations next week

**Comment by brettgaylor** [comment]
cc @Melechuga @natalieworth

**Comment by lovegushwa** [comment]
@natalieworth can you dig into the template started by @sabrinang last week? Here's what I think we need to do based on @brettgaylor comments above:

- customize color pallet based on https://advocacy.mozilla.org/open-web-fellows/
- provide typographic hierarchy template / guidelines for a standard document page:
Headline, Subhead, Body copy, lists, Pull Quotes
- provide image treatment options: full bleed, full bleed with overlay text, large image, small image

@natalieworth can you take this on? The best way to do this is work with @Melechuga to create mini /fake presentation that a fellow might give so when using the template folks get the gist quickly. 

Questions:
- Will you need a introduction / context section before fellows present?
- Do you expect fellows to work in / share the same google slides doc? Or will they each build separate docs?

**Comment by natalieworth** [comment]
For sure, this sounds good. I can create smaller Fellow/ Advocacy themed template based on Sabrina's. @Melechuga @brettgaylor If there is past content or examples from last year that would be great. If not, maybe 6-9 pages would be useful to show as a slide demo (or more if needed) for the fellows to follow based on the suggestions from Jordan above?

**Comment by brettgaylor** [comment]
Another note: they've requested 16x9

I think we should use Keynote rather than google slides.  So they'll each build their own.

6-9 pages would be totes fine.

**Comment by lovegushwa** [comment]
@natalieworth I can close this?

**Comment by natalieworth** [comment]
Good to close @lovegushwa ! @Melechuga @brettgaylor if you need any updates to this, feel free to ping me! :)

**Comment by kristinashu** [comment]
Does anyone know where this deck is? I think some of it might be relevant for the report https://github.com/MozillaFoundation/plan/issues/784#issuecomment-224751580

**Comment by Melechuga** [comment]
Here is my presentation (not just the template): 
[Mozilla_Ford_Presentation_Melissa.pdf](https://github.com/MozillaFoundation/plan/files/314574/Mozilla_Ford_Presentation_Melissa.pdf)

**Comment by kristinashu** [comment]
Thanks!
