### ISSUE TITLE
Design common site assets

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#795]
#### DARCI
Driver: @kristinashu 
A: @xmatthewx
R: @sabrinang @flukeout 
C: 
I: @hannahkane 

#### Overview

Work to include: universal website footer, common form styles, and other bootstrap components.

Deliverables: 
 - Boilerplate Illustrator and Sketch files that include key guidelines. 
 - Comps and issues filed for any enhancements to bootstrap theme.
 - (Aim for a minimal set of things we can start and finish in this heartbeat. File other aspirations in design repo.)

#### Links

 - [ ] issue
 - [ ] issue
 - [ ] issue

**Comment by kristinashu** [comment]
Before diving in and designing components, we will make a slide deck to make sure we're all on the same page and to come up with a game plan. It will cover things like: Why should we have a universal mofo style? What's the goal?, What are the benefits?, Who does it effect?, What does it effect?, How will it be implemented?, and a list of actionable tickets.

Ticket for this is in the design repo https://github.com/MozillaFoundation/Design/issues/168

**Comment by hannahkane** [comment]
@kristinashu - I think we should roll this into the current heartbeat. Can you help me clarify what the deliverables are for this heartbeat? I believe it's to share the deck with the design team on Tuesday and then with Simon and Gavin on Wednesday, before you're off on PTO. Is that right?

**Comment by kristinashu** [comment]
@hannahkane yes that is it. We've opened up tickets for the first set of 'components' and we can try to put them into heartbeats at design triage tomorrow.

**Comment by kristinashu** [comment]
@sabrinang and I have finished the presentation deck covering why and how we will create a unified mofo design style: https://docs.google.com/a/mozilla.com/presentation/d/1fDZKei9hlHOjp3mjD5FbFYRPDB01ryUxz9iLjY92QVY/edit?usp=sharing
from https://github.com/MozillaFoundation/Design/issues/168 

@vazquez has created an initial basic Toolkit in Sketch https://github.com/MozillaFoundation/Design/issues/160

We've created an 'epic' ticket with several of the components we will be starting with https://github.com/MozillaFoundation/Design/issues/177

Next steps will be to review our plan with all of the engineers at a demo call and set up regular check-ins between design and dev.

**Comment by xmatthewx** [comment]
Great progress on this. @kristinashu can update this ticket with info from her review with engineers. I'll leave this open until she returns from PTO and we can follow up and file next steps.

**Comment by kristinashu** [comment]
Review the deck with Simon and Gavin and we are all in agreement that the key to this will be communication between design and engineering. To do this, we will attend each others weekly meetings and also have dedicated regular check-ins with the core drivers. Because science is the main focus for Gavin right now I don't think we will really be able to kick this off until after London. In the meantime, I will push forward and add as much as I can to the Toolkit MozillaFoundation/Design#177

**Comment by xmatthewx** [comment]
Great benchmark for UI components, style guides, and sharing those things. https://standards.usa.gov/

**Comment by hannahkane** [comment]
I'm moving this to a post-London milestone, but we should define a specific deliverable if we can.

**Comment by hannahkane** [comment]
Taking this out of any milestone until we clarify specific deliverables and prioritize them.

**Comment by hannahkane** [comment]
Wondering if this ticket is still useful. I feel like we're tracking all this work in other places now.

**Comment by xmatthewx** [comment]
This is tracked via universal design and UI toolkit.
