### ISSUE TITLE
Create MLN Production Roadmap visualization

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#796]
#### DARCI
Driver: @xmatthewx 
A: @simonwex 
R: @xmatthewx @hannahkane
C:
I:

#### Overview
In advance of the London All-Hands, let's prepare a visualization of the roadmap that:
 * conveys the top production priorities
 * clarifies those priorities in the context of our evolving team structure
 * provides top-level narrative about each project, as well as links to more [in-depth documentation](https://github.com/MozillaFoundation/plan/issues/797)
 * illustrates ambiguity and receding clarity (i.e. things farther away are fuzzier, this is subject to change, some things are less defined)

We might use a tool for this—ideally something that plays well with Github since this is where our backlogs live!

#### Links
 * [Roadmap as spreadsheet](https://docs.google.com/spreadsheets/d/1T_FGYeeEgxvKGcMfbOr5qC6uO0rjuCOexqe5Zq3tUsQ/edit#gid=552584918)

#### Key Deadlines

- [ ] London!

**Comment by xmatthewx** [comment]
depends a bit on #797

**Comment by xmatthewx** [comment]
This work will continue next heartbeat. 
 - Good progress with @hannahkane in this pad [defining the projects' goals, impacts, deliverables](https://public.etherpad-mozilla.org/p/roadmapdocs).
 - Some thinking in this diagram on the [relationship between hubs and production](https://docs.google.com/drawings/d/1CHB1i85RN5C4VbiCVtTBmj3MsCt5DgW0T4j3is_UVn0/edit). 
 - Here's a list of production project titles. Deck can be use to [sort projects into production themes](https://docs.google.com/presentation/d/1D50SwBfEMtMW8MPdjzxW_52bQGO_MeiVTs-TGnZZP7Y/edit#slide=id.p) for teams.

**Comment by hannahkane** [comment]
Moving into current heartbeat. Awaiting @xmatthewx's return!

**Comment by hannahkane** [comment]
dropping this here for when we talk on Thursday, @xmatthewx - https://public.etherpad-mozilla.org/p/mlnroadmap

**Comment by hannahkane** [comment]
really good progress today, but rolling into next heartbeat for further refinement

**Comment by xmatthewx** [comment]
WIP - https://www.dropbox.com/s/jtdt0elaoahgz3i/Screenshot%202016-05-19%2021.52.06.png?dl=0

<img width="1175" alt="screenshot 2016-05-19 21 52 06" src="https://cloud.githubusercontent.com/assets/53411/15414800/f3dbb5aa-1e0b-11e6-8e8d-2b878b186dbf.png">

**Comment by hannahkane** [comment]
@xmatthewx - moving this to post-London, since we want it to be informed by London. Does that make sense to you?

**Comment by xmatthewx** [comment]
Yep!

**Comment by hannahkane** [comment]
@xmatthewx - closing this, though we may want to re-open once the roadmap is approved by exec team
