### ISSUE TITLE
Create MLN Product Roadmap project documentation

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#797]
#### DARCI
Driver: @hannahkane
A: @simonwex 
R: @hannahkane @xmatthewx @simonwex 
C:
I:

#### Overview
In advance of London, we need to collect and in some cases prepare documentation corresponding to each of the foreseeable projects on the product roadmap. These will be used during the All-Hands to support H2 planning work.

#### Links
 * https://public.etherpad-mozilla.org/p/roadmapdocs

#### Key Deadlines
London!

**Comment by xmatthewx** [comment]
Can we schedule a block of time to work on this in tandem next week?

**Comment by hannahkane** [comment]
@xmatthewx and I met and hacked on some documentation. Good start. Next step is to follow up with various program leads to prep for London, including, perhaps writing some concise problem statements to help focus conversations.

**Comment by hannahkane** [comment]
This work is going to roll into the next heartbeat.

**Comment by hannahkane** [comment]
Closing this because this really an expected outcome *from* London. What we're doing now is preparing for London to be successful.
