### ISSUE TITLE
Design Webmaker app install page

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#80]
Design landing and install page for Webmaker app. This will be used during and after MWC and will link to the beta install links for WMA on Android and Firefox OS. Eventually, this content will be updated to point at the Google Play and Firefox Marketplace stores. Possible URLs:
- m.webmaker.org
- app.webmaker.org
- webmaker.org/app
- webmaker.org/install

### Benchmarks
http://timehop.com/
http://www.mailboxapp.com/
https://path.com/moments
https://www.fiftythree.com/paper
https://www.facebook.com/paper
https://www.kickstarter.com/mobile
http://www.getpennies.com/
### Milestone
*To-do*

### RACI
Phase: Build
Driver: @thisandagain 
Decision: @thisandagain 
Consulted: @HPaulJohnson @benrito @davidascher 
Lead design: @iamjessklein 
Lead dev: n/a
Quality: @cassiemc

**Comment by cassiemc** [comment]
@thisandagain can you link to the prior design sprint here? What design activities are needed for this?

**Comment by thisandagain** [comment]
Clarified!

**Comment by benrito** [comment]
Should we start sourcing a FAQ for this?

**Comment by thisandagain** [comment]
We'll construct the outline / IA tomorrow during the kickoff. I'll holler if we think a FAQ is needed!

**Comment by thisandagain** [comment]
I'll take this one! :cat2:

**Comment by thisandagain** [comment]
@cassiemc If you have a moment, some additional benchmarks from your POV would be most appreciated!

**Comment by cassiemc** [comment]
Assigning @iamjessklein for design :)

**Comment by adamlofting** [comment]
Metrics for this will be pretty simple, but let's make sure we're using the webmaker.org GA profile, and including event tracking to capture links out to external URLs or download files. 

Once dev starts and there are some files to look at, feel free to loop me in or assign the GA instrumentation part to me.

**Comment by thisandagain** [comment]
Kickoff meeting schedule for today. Agenda available here:
https://prod.etherpad.mozilla.org/gh80

**Comment by iamjessklein** [comment]
Note (to myself): go [here](http://webmaker-mobile-guide.mofodev.net/_docs/get_started/important_links.html) to try downloading

**Comment by iamjessklein** [comment]
I am building off [this wireframe](https://redpen.io/mcb6c3cdc3d50d6950) and will provide updates on the mockups. The basic flow that I am proposing is CTA > Design > Build > Share

**Comment by iamjessklein** [comment]
Here are three options for the primary cta panel - please drop feedback [here](https://redpen.io/coa402c9d9d63f3489)

![topscreenoptions](https://cloud.githubusercontent.com/assets/535012/6130651/5c88f65a-b114-11e4-93e3-b5e9e8543cc9.png)

**Comment by benrito** [comment]
Loving the aesthetic!

When thinking about marketing and copy, we should make sure to pick stuff that will localize well.

Also, would recommend reading @laurad reports to understand the memes that will work well across cultures (creating less cool than sharing, remix can be considered theft, etc)

Because of the feedback and contribution-seeking parts objective of the beta, looking forward to seeing how we message and invite that kind of help.

@drushka

**Comment by thisandagain** [comment]
Agreed re: messaging concerns. Focusing on "sharing" is likely our best course based on findings-to-date. @HPaulJohnson and @edrushka could we get some support with a headline today?

@cassiemc and @vazquez I'm concerned about the colors, typography, and illustration styles here as they feel foreign to the rest of application. The clouds, hands, hand-drawn type, use of OpenSans, and colors are all a little far off IMO. Could the three of you please connect today before our check-in at 1:30pm PST to get on the same page?

**Comment by iamjessklein** [comment]
@vasquez @cassiemc  - is there a style guide for the app? In terms of fonts etc. I was using the fonts and colors listed [here](http://mozilla.github.io/makerstrap/demo/#/),  the patterns that are on the current Webmaker landing and the illustrations on the Mobile opportunity site (minus the clouds which can be polished/redesigned if we go in that direction).

**Comment by vazquez** [comment]
The mobile style guide differs from the Webmaker Brand one. As an example, the app uses Fira Sans as the app-wide font. I started a style guide this morning, but it's going to take a little bit of time get done. 
@iamjessklein, for now the MASTER.sketch file that I shared with you has all the styles (albeit disorganized which is why I started creating the UI toolkit)

**Comment by cassiemc** [comment]
Yep, @iamjessklein has the brand challenge of uniting Webmaker and Webmaker app styles, a little above and beyond this ticket's call of duty, but probably just a few tweaks to fix 'er up. I'll leave @iamjessklein and @vazquez to connect and will check in end of day to see if I'm needed.

**Comment by vazquez** [comment]
Sharing what I have so far for the UI Toolkit: https://www.dropbox.com/s/1bduiieaop67jca/UI%20Toolkit.sketch?dl=0

**Comment by iamjessklein** [comment]
After the design critique yesterday, I updated the mockup (see below and [comment on redpen](https://redpen.io/uo271bce22d96c82d4))
Iterations:
* fonts have been adjusted - in app -> Fira 
* fonts have been adjusted - on site -> Webmaker fonts
* reduced screens from 5 callouts to 3 with a footer 
* integrated full size phone imagery 
* changed phone from iphone->android
* cleaned up some spacing issues 

To do:
* review from @HPaulJohnson on copy (particularly the cupcake ipsum parts)
* design review @cassiemc 
* animations (with @vazquez updated graphics)

![mobile 5 2x](https://cloud.githubusercontent.com/assets/535012/6171734/893af378-b2aa-11e4-9e49-6156846b9ce0.png)

**Comment by thisandagain** [comment]
Really excellent progress @iamjessklein ! :smile: 

One big change (other notes in Redpen):
We needed to make some major changes to the sharing flow last night to make it work well across platforms and integrate directly with Android's native sharing flow. Because of this, and I believe the need to show what a user "makes", I'd like to focus the last screen on an actual example app. I recommend the "business" template.

**Comment by benrito** [comment]
Hey all—

What is contemporary thinking on FAQ?

Two dimensions:

1 user feature questions—i.e., "does my friend need to install Webmaker to see my app?" "Is it available for iOS?" "what features are coming next?"

2 during the beta, contributor questions—i.e., "how can I share feedback and feature requests?" "How can I get involved in translating and testing the app?"

**Comment by iamjessklein** [comment]
great - @thisandagain I'm thinking of showing the showcase your business template ---- remix over the course of the gifs and show the evolved app in the last screen.

@benrito - that wasn't discussed in the initial scope here, but let me know if copy exists and it should be factored in. 

cc/ @edrushka @HPaulJohnson

**Comment by iamjessklein** [comment]
Update: I took a [stab at the UI for the Business template](https://redpen.io/ep35dc8782c70ac2d0) - I did the Edit and Preview screens - but still need to do the Edit - with the remixed content (showing the editing) and the Publish - showing the revised app. Would love your :eyes:  @vazquez  @cassiemc  - let me know if I followed the UI Toolkit as you anticipated. This part was a bit tricky because the headers were specified at different colors than they appeared in the Pages so I wasn't sure if that was a mistake or a different application for this particular view.  

Please put comments in the red pen. 

![businessappscrns](https://cloud.githubusercontent.com/assets/535012/6181473/64c057b6-b301-11e4-9b7a-f5f8f9f1147d.png)

**Comment by vazquez** [comment]
I'm in the process of preparing assets for Jess with updated UI:

- Business Template in Edit Mode
- Business Template in Active Edit Mode
- Business Template in Published Mode

**Comment by iamjessklein** [comment]
:+1:

**Comment by iamjessklein** [comment]
Here's a first stab at the first gif - Templates->Preview 
![templates3](https://cloud.githubusercontent.com/assets/535012/6190205/43ae9336-b36e-11e4-85cc-f7db7d920bbc.gif)

Note: The color of the + 0 - for the tea is slightly off, I will correct.

**Comment by iamjessklein** [comment]
Here is a stab at the tagline sequence - the animation style feels a little crazy with the gif right below it.  I am looking [here](http://daneden.github.io/animate.css/) for animation css. Thoughts @HPaulJohnson ?

![taglineanimation](https://cloud.githubusercontent.com/assets/535012/6191089/db692f50-b374-11e4-821f-d570b88490e6.gif)

**Comment by iamjessklein** [comment]
after mulling it over - the text + gif makes me feel sick. :speak_no_evil::mask:

**Comment by HPaulJohnson** [comment]
+1 agree, too much motion. I do really like how the scrolling subhead communicates the breadth of possibilities though

**Comment by iamjessklein** [comment]
@HPaulJohnson given that - any thought on a new tagline?

**Comment by HPaulJohnson** [comment]
@edrushka and are going to take a look at this today. without the animation in the headline "create something" is a little weak so we'll take another pass.

**Comment by benrito** [comment]
@iamjessklein @thisandagain we discussed FAQ in the kickoff but were inconclusive. latest thinking?

**Comment by thisandagain** [comment]
Doesn't feel particularly needed right now, though I'd like to add a "Feedback" link within the app proper to cover that use case. Tracking here: https://github.com/mozilla/webmaker-app/issues/1176

**Comment by iamjessklein** [comment]
@edrushka @HPaulJohnson - did you get anywhere with the copy edits?

**Comment by thisandagain** [comment]
Tracking implementation and copy edits in implementation ticket #81
