### ISSUE TITLE
Event App prep for London

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#803]
#### DARCI
Driver: @xmatthewx
A:
R: @mmmavis 
C: @edrushka 
I: 

#### Overview

The Event App has been prepped for multiple events. Cleanup on the data processing flow has started (#792). Our goal to test the app at London All Hands looks promising. 

For this heartbeat, I propose that we: 
 - Build a functioning London instance of the app with mock data. This will enable us to get all systems wired up in advance of real data. 
 - Document data loading script.
 - Prepare a handoff from @mmmavis to another dev before her time away. 

#### Links

 - https://github.com/mozilla/schedule-app-core
 - https://github.com/mozilla/schedule-app-data-processor
 - https://github.com/mozilla/mozfest-schedule-app
 - MoFo 2015 Orlando Agenda: https://docs.google.com/spreadsheets/d/1okEq3JWQ5XN2spbx5FyQFFyzdjtXGk8UvGKPQT4Iiho/edit#gid=0

**Comment by edrushka** [comment]
cc-ing @Saallen as she will have insights into the github --> spreadsheet process

**Comment by xmatthewx** [comment]
mozlando all hands schedule for reference: https://docs.google.com/spreadsheets/d/1okEq3JWQ5XN2spbx5FyQFFyzdjtXGk8UvGKPQT4Iiho/edit#gid=0

**Comment by mmmavis** [comment]
Not sure how the Ops team used to manage all hand's "session proposals".  We should check with them and see how their preference is.  I have a feeling that a Github repo as the proposal discussion platform might not be needed here.

**Comment by xmatthewx** [comment]
@mmmavis – I believe we will use Github for session proposals instead of a google form, though I'm not certain. But, since the schedule is small, we can manually populate the spreadsheet. We can skip the automation unless it is useful for practice.

**Comment by Saallen** [comment]
Hi- I would highly recommend bringing @acabunoc and Scott (not naming devs as per email request :)) into this conversation for advice.
They spent a lot time last year chatting through the process for MozFest :chart_with_upwards_trend:

**Comment by acabunoc** [comment]
I know the science fellows who made the pathway viewer last year are also keen to discuss this

http://joeyklee.github.io/mozmap2015/  (demo no longer working)
 https://github.com/joeyklee/mozmap2015

Let me know if I should flag them!

**Comment by xmatthewx** [comment]
We have ample time to prepare for London. Communication and coordination will be a little tricky with travel and PTO. I more or less won't see Mavis during May. 

| Week | Starts | Note |
|:---:|:---:|:---|
| 1 | Apr 25 | Erika retreat prep |
| 2 | May 2 | Matthew & Erika at retreat. Ricardo at conference. |
| 3 | May 9 | Matthew PTO. Erika occupied until Thurs. |
| 4 | May 16 | Mavis PTO. Hannah birthday this week!! |
| 5 | May 23 | Mavis PTO |
| 6 | May 30 | Final London prep |
| 7 | June 6 | London QA testing |

**Comment by xmatthewx** [comment]
Excellent progress last week. Focusing on the finer details this week. 

We just need to make sure we identify a dev with @simonwex to onboard before @mmmavis goes on PTO.

**Comment by xmatthewx** [comment]
We have a green light to use event app at London all hands. A few notes to track:
 - [ ] I will identify a deadline with @OpenMatt and @ldecoursy to lock activity in github before we move to the spreadsheet. 
 - [ ] I will identify a dev with @simonwex and @mmmavis available to provide midnight hour dev-ops support in London based on travel. I arrive a day or two early so I can be on point for front-end and spreadsheet concerns.

**Comment by simonwex** [comment]
Hey @xmatthewx we have a process for on-call devops so we don't need to assign a specific person. If there are any devops tasks we know about already. Let's file them now: https://github.com/MozillaFoundation/mofo-devops/issues/new

I'll email you with specific on-call details.

**Comment by simonwex** [comment]
Also... this is exciting :)

**Comment by hannahkane** [comment]
Related ticket: https://github.com/MozillaFoundation/mofo-devops/issues/325

Moving into current heartbeat.

**Comment by xmatthewx** [comment]
We're in good shape. I'll keep this open and roll forward to track integration of the fledgling all hands schedule into the app.

**Comment by hannahkane** [comment]
@xmatthewx - ok to close or move to current heartbeat?

**Comment by xmatthewx** [comment]
We're in great shape. Still a few bits to do, but good to close this. The results: http://mzl.la/mofolondon
