### ISSUE TITLE
Design Event App Documentation Feature

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#804]
#### DARCI
Driver: @xmatthewx
A:
R: @vazquez 
C: @edrushka, @mmmavis 
I: @Saallen 

#### Overview

Goal: develop UX and begin UI for an Event App feature to extend our convenings experience. Continues work from https://github.com/MozillaFoundation/plan/issues/791. 

#### Links

[concept deck](https://docs.google.com/presentation/d/1rmFd4VSiTWWHlaqMGDMQgR7XLqRQ_JLD-WKuFPHmFDY/)

**Comment by xmatthewx** [comment]
Here's a [UX Notebook](https://docs.google.com/a/mozilla.com/presentation/d/18s2KnaqQrA_ve2Fg5pGi_czM1b9X8w49bS8O7gcqTG4) co-designed by me and @vazquez. Work in progress. 

We're leaning toward calling this a `Notes` feature, labelling the button `Photos & Notes` for users to add/view notes. It's a bigger decision than it might appear – really sets the context and expectations. We explored [lots of alternatives](https://docs.google.com/presentation/d/18s2KnaqQrA_ve2Fg5pGi_czM1b9X8w49bS8O7gcqTG4/edit#slide=id.g12ce643e21_1_20) in the notebook.

**Comment by edrushka** [comment]
@Saallen and I had a thought following today's Github session curation meeting. Is it possible that the Photos and Notes button could link back to the original github ticket?

**Comment by xmatthewx** [comment]
Interesting. You mean to just use Github as the place for images, text, and conversation? Definitely worth considering. Github isn't ideal on mobile, but the flexibility could be nice.

**Comment by edrushka** [comment]
Yes, that's what we were thinking: a place for session images, notes and conversation. We're talking about this and are intrigued with the idea of all the info in one place (the github issue) from start to finish. Github is easy to upload and view images and add notes, plus the social functionality (@mentions) is baked in. Plus it has longevity (unlike dropbox where someone can just remove the file). Plus n00bs can view the images and notes without signing in if we set the permissions right (I think).

I hear you that's not ideal on mobile - are any of the options ideal, though?

**Comment by xmatthewx** [comment]
Very cool. The Github interface on mobile might make it untenable, but we could probably provide our our "add a note" feature to post a comment to github. 

We aren't thinking about using dropbox. I just mentioned that as a metaphor for dropping in notes to sessions. We would store the text and images ourselves. We are also explicitly avoiding any form of login. But yes, anyone would be able to view things on github, without needing permission.

Github is great, but for viewing purposes by others later, it's not a more friendly place to browse and view the sessions or documentation. The Mozfest website and schedule is a more approachable space for participants and the general public.

All worth discussing. No need to make a decision at this stage.

**Comment by xmatthewx** [comment]
Great progress last week. @vazquez has a shortened week, but should be able to post first draft ui/ux before he departs.

**Comment by vazquez** [comment]
@xmatthewx and I have been hard at work refining UX and UI. We are ready to show the latest iteration to the Event App!

Event App: https://invis.io/K774WYC4B#/154801556_Day_Schedule

In the process, we have also made improvements to the navigation of the Event App. This has resulted in a more refined UI.

New Navigation: https://invis.io/K774WYC4B#/155167007_Nav

**Comment by hannahkane** [comment]
Rolling to current heartbeat for continued work.

**Comment by xmatthewx** [comment]
This work is temporarily on hold. @vazquez will hand over design assets to me next Tuesday. I will synthesize to prepare for discussion in London.

**Comment by hannahkane** [comment]
@xmatthewx - can we close this ticket, or move it to an upcoming heartbeat?

**Comment by xmatthewx** [comment]
I'll close this and open anew after we make a plan in London.
