### ISSUE TITLE
Thimble: create shared artifacts with potential partner org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#806]
#### DARCI
Driver: @flukeout 
A: @simonwex 
R: @flukeout @gideonthomas 
C: @hannahkane
I: @chrislarry33 

#### Overview
Working in conjunction with partner organization, develop shared artifact illustrating possible approaches to reaching three shared goals:

1) Must be accessible to under 13s 
2) Classroom experience for teachers
3) Great experience for users making use of both toolsets (Thimble + partner's tools)

**Comment by jgmac1106** [comment]
+1 to under thirteen. If I recall correctly we collected a bunch of ToS
from orgs that allow for under 13 that could be shared with legal. I think
it exists in some google doc.

Also excited for number 2. I think the Thimble classroom experience was
waiting on other dependent issues but will be great to get back to this

**Comment by hannahkane** [comment]
First draft of user experience artifact is done. System architecture model to come.

**Comment by flukeout** [comment]
Here is the latest version of the integration diagram:
https://dl.dropboxusercontent.com/u/109902/codeorg_and_thimble.pdf

Will update based on today's meeting.

**Comment by gideonthomas** [comment]
Will add a bunch of sequence diagrams soon too.

**Comment by hannahkane** [comment]
Closing this issue. We'll make a decision tomorrow about next steps.
