### ISSUE TITLE
Integrate Calypso into Advocacy site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#807]
placeholder ticket, more details to come

This is a prereq for #784

**Comment by hannahkane** [comment]
@simonwex - we haven't assigned anyone to this. Do you think we need to push back to the next heartbeat?

**Comment by simonwex** [comment]
@hannahkane we should bump this as @ScottDowne is helping with Mozfest and formulating a plan for the next steps on the Advocacy platform. 

@ScottDowne, let's chat about where this fits within your plan. I'll add it to our 1:1.

**Comment by hannahkane** [comment]
Thanks, @simonwex.

Noting that this potentially puts the OWF One-Year report at risk, or at least, might affect a decision about whether to use the CMS for that project.

**Comment by ScottDowne** [comment]
Question, is this including a new page? Sounds like a report of sorts that'll live on advocacy.mozilla.org/something

If so, is it possible to integrate calypso for just the new page vs the whole site if that saves us work and we find the timeline tight? Might even be an ideal plan even if time isn't tight.

**Comment by ScottDowne** [comment]
Thinking about this a bit more, and we might even consider this work living in a new repo, and hosted on advocacy.mozilla.org/something similar to how we're hosting codemoji.

@cadecairos thoughts?

Probably unrelated, but I'm also curious about and thinking about how content edited in calypso works with content that we want to localize. There is a pretty significant push in advocacy to localize so a lot of our content might be tricky. I think though content that isn't being localized, like OWF One-Year report, can be integrated with calypso and separated from the rest of the advocacy code.

**Comment by ScottDowne** [comment]
Thinking about this a bit more, and we might even consider this work living in a new repo, and hosted on advocacy.mozilla.org/something similar to how we're hosting codemoji.

@cadecairos thoughts?

Probably unrelated, but I'm also curious about and thinking about how content edited in calypso works with content that we want to localize. There is a pretty significant push in advocacy to localize so a lot of our content might be tricky. I think though content that isn't being localized, like OWF One-Year report, can be integrated with calypso and separated from the rest of the advocacy code.

**Comment by simonwex** [comment]
Hey @ScottDowne, let's have a quick chat about this. I've got some spare time tomorrow, could you book  30 mins in my calendar?

**Comment by ScottDowne** [comment]
I had a chat with @simonwex

Looks like we can do the bulk of the work post mozfest.

This heartbeat I'm going to take a closer look as to what's involved.

**Comment by hannahkane** [comment]
post-Mozfest? Did you mean post-AllHands? Ideally this would be completed before the end of June, so that we can use it for upcoming Advocacy content (like the OWF one-year report).

**Comment by ScottDowne** [comment]
Ha, yes, post all hands, my bad, been juggling things and brain wires are crossing.

Yeah, I think before end of June is more than reasonable. Implementation doesn't look all that bad, and I have time to prep, so the dev isn't something that worries me.

**Comment by hannahkane** [comment]
Note: no longer planning to use Calypso for the one-year report, so this is no longer an urgent need. I'm going to close this with the expectation that the engineering team will come out of London with a clearer plan for rolling out Calypso to existing properties including the Advocacy site.
