### ISSUE TITLE
Ship install page & demo script for MWC

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#81]
Build, ship, and instrument install page for MWC.

#### Audience
Attendees of MWC, partners, and mass market traffic via PR.

#### Success
A complete, fully QA-ed, and optimized for mobile install page is ready for MWC at `webmaker.org/beta` by the end of the sprint with a demo script that matches our narrative.

#### Vision
Mobile design is ready for implementation (#80) but animations of each screen will likely need to be refined based on final QA of app. The desktop implementation is **not complete** and needs to be available for final design review on Thursday AM (19th).

A few details:
- Installation service is being tracked here: https://github.com/mozilla/webmaker-app/issues/633
- iOS users should be directed to friendly error message (TBD by @k88hudson)
- Desktop users should *not* see a download link, but be directed to their Android or Firefox OS device
- Desktop user enters phone number to receive a text with an install link

#### Measurement
% of users who click "Download"

#### Benchmarks
http://www.mailboxapp.com/
https://www.mozilla.org/en-US/firefox/android/

#### Milestone
https://github.com/mozilla/webmaker.org/milestones/MWC%20Install%20Page

#### RACI
Phase: Build / Ship
Owner: @secretrobotron 
Decision: @thisandagain 
Lead design: @iamjessklein 
Lead dev: @cadecairos 
Dev: @jbuck 
Quality: @davidascher

**Comment by iamjessklein** [comment]
I added the updated desktop and mobile views and provided a few options for what the published view could look like.  I will need a decision on the direction for that before finalizing the gifs. The photos are all CC images.

[Please drop feedback in redpen](https://redpen.io/p/od396a13bd17f4227e)

![artboard 1](https://cloud.githubusercontent.com/assets/535012/6234008/25f35356-b6a5-11e4-9e33-c30aa4f50934.png)

**Comment by thisandagain** [comment]
Let's create these using the app itself ... that should make this a little quicker to iterate on and ensure that we are being accurate.

**Comment by adamlofting** [comment]
#### Metrics spec for the build:
- [ ] Instrumentation for Measurement: (https://github.com/mozilla/webmaker.org/issues/1253)

**Comment by secretrobotron** [comment]
- Design for desktop by @iamjessklein by tomorrow
  - hand off flat png, svg, and fonts (if required)
- Send text from desktop install page to phone for mobile install
  - Is there a spam or rate limit feature as a part of Twilio API?
- Just need to update and sanity check the demo script at the end of sprint
- Get final copy from @HPaulJohnson
- Don't need to build anything for iOS (or BlackBerry or whatever) (handled by @k88hudson's install service)
- Come up with a route (webmaker.org/beta)? @HPaulJohnson 
- IMPLEMENT

**Comment by secretrobotron** [comment]
Building a set of tickets for us here: https://github.com/mozilla/webmaker.org/milestones/MWC%20Install%20Page

**Comment by HPaulJohnson** [comment]
Here's the final copy @edrushka, Kevin and I settled on: 

Become a Maker
Webmaker takes the best part of the web — creating — and strips away the complexity. 

Build the Perfect App
Create exactly what you need: A website for your business, a chat app for your friends, a lesson plan for your students. 

Share It with the World
Webmaker creations are meant to be seen, heard and used. Share your project with friends and colleagues

**Comment by secretrobotron** [comment]
Thanks @HPaulJohnson !

**Comment by cadecairos** [comment]
@secretrobotron Does this page need to have support for localization?

**Comment by secretrobotron** [comment]
> @secretrobotron Does this page need to have support for localization?

Ideally, yes.

**Comment by cadecairos** [comment]
okay, we will take that into consideration when deciding where & how  to build it
