### ISSUE TITLE
MozFest site: Complete design and begin dev of Call for Proposals 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#810]
#### DARCI
Driver: @edrushka
A: @xmatthewx 
R: @vazquez + dev??
C: @Saallen @lovegushwa 

#### Overview
As per plan outlined in #805, we need to complete the design and begin dev for the Call for Proposals, so that it can go up June 1.

@simonwex to assign a dev since @mmmavis is on PTO starting this Thursday through May 30.

**Comment by edrushka** [comment]
Sarah and I are taking Wednesday off to recover. Will dive into this on Thursday when I return. @Saallen can provide more info as she hosted the 'Call for Proposals' hackjam in Berlin, but we're not planning on doing anything TOO radical here, so the workload shouldn't be insane. More details soon.

**Comment by hannahkane** [comment]
I'm actually going to close this ticket, because it really just duplicates #805, and that's where all the conversation is.
