### ISSUE TITLE
[OWF] Host Org On-boarding, July

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#811]
#### DARCI
Driver: @vanessarhinesmith 
A: @vanessarhinesmith 
R: @melechuga @vanessarhinesmith
C: @brettgaylor 
I: Kevin, Sara, Aurelia, Kaitlin 

#### Overview
Open Web Fellows co-designing // on-boarding event for host organizations. 

Event outputs: 
- Host org 2016-2017 fellow onboarding template
- Host org 2016-2017 fellow work plan template
- Host org fellow mentor/s user manual*
- Co-create handbook about what it means to be an OWF host org 
- Shared host org calendar of campaigns and events
-  List of needs and issues; and ideas of how to work together 

*Fellows will also create a user manual to share with Host org mentor and OWF program team

#### Links
OWF16_July On-boarding Planning Call - https://goo.gl/OvEaXk
Location breather SoHo -  
>> Main room https://breather.com/locations/new-york/138-wooster-3
>> Breakout room https://breather.com/locations/new-york/138-wooster-2 

#### To Do

- [ ] Finalize hotel location and reserve room block (Su 7/17 - Tu 7/19)
- [x] Finalize co-design // onboarding location and make reservation
- [x] Email Host organizations with travel logistics and next steps
- [ ] Confirm all Host org travel arrangements to NYC by F 5/27
- [ ] Make dinner reservation for M 7/18 at Amélie (20 people at 7pm)
- [ ] Order Gunner's co-design supplies (send to hotel or Ford Foundation)
- [ ] Arrange lunch for M 7/18
- [ ] Arrange lunch for Tu 7/19
- [ ] Confirm Tu 7/19 Happy Hour even at Ford Foundation
- [ ] Schedule pre event call with Host orgs, OWF program team, and Gunner 

>> Create Doodle poll
>> Th 6/23 Gunner free all day
>> F 6/24 Gunner free except 10AM PT

#### Key Deadlines

- [ ] Host organization confirm travel arrangements to NYC 5/27/16

**Comment by vanessarhinesmith** [comment]
[Questions about Civic Hall space for an event.pdf](https://github.com/MozillaFoundation/plan/files/263659/Questions.about.Civic.Hall.space.for.an.event.pdf)
Space information from Alena Amante, Director of Events, Civic Hall

**Comment by vanessarhinesmith** [comment]
Other space options in the NYC // Brooklyn area: 

The Green Building — http://www.thegreenbuildingnyc.com/
Bat Haus — http://www.bathaus.com/
BKLYN Commons — http://bklyncommons.com/event-space/
**favorite** Breather — https://breather.com/office-meeting-rooms-for-teams

**Comment by hannahkane** [comment]
I'm moving this to the current heartbeat, so we can close out the last one.

**Comment by vanessarhinesmith** [comment]
It's actually complete. So I guess we can close it :)
