### ISSUE TITLE
[OWF] Website refresh for Year 2 launch

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#812]
#### DARCI
Driver:
A: 
R: Melissa @vanessarhinesmith @kristinashu 
C: @brettgaylor @KevZawacki 
I: 

#### Overview
In June, we will be announcing the Year 2 Open Web Fellows via the website. We'll need to make a number of changes, including the following:

**UI/UX changes**
 - **Landing page**
   - Modify current landing page to contain announcement 
   - Consider relabelling nav item from Overview to Home
 - **Info**
   - Migrate current Overview content to the Info page (will be revised and shortened)
 - **Fellows**
   - Modify Fellows page to include new fellows and alumni (following pattern on science site)

**Copy changes**
- Write copy to welcome and announce the 8 new fellows
- Write short bios of each fellow, the work they'll be doing at their host orgs (Include twitter handles of each fellow, links to host org websites)
- Possible changes needed to the fellows site to make it an alumni page

>> What am I missing??

#### Links
Current landing page: https://advocacy.mozilla.org/open-web-fellows/
Current fellows page: https://advocacy.mozilla.org/open-web-fellows/fellows
Open Science Fellowship (current site updates): https://redpen.io/p/eb9d7534bcf4dfcc17 
Google Policy Fellowship (content architecture): http://www.google.com/policyfellowship/

#### Key Deadlines

- [x] Content by May 31
- [x] Design by June xx
- [x] Build by June xx

**Comment by Melechuga** [comment]
Hi @hannahkane @xmatthewx Is it possible to talk about this ahead of the May 20th heartbeat planning meeting? Most likely @vanessarhinesmith will be joining the TPS call on May 20th, as I have a conflicting call at that time. Thanks!

**Comment by hannahkane** [comment]
Just sent a calendar invite to discuss.

**Comment by KevZawacki** [comment]
@Melechuga Happy to help with copy however I can.

**Comment by Melechuga** [comment]
@KevZawacki Awesome! Pulled together some 2015 assets and started a new issue specifically around comms: https://github.com/MozillaFoundation/plan/issues/813

cc @vanessarhinesmith

**Comment by xmatthewx** [comment]
Cool. Does this involve new design? Or just prep of assets like the new fellows photos?

**Comment by xmatthewx** [comment]
The plan is for @kristinashu to dig into design the heartbeat that begins June 6th. It's likely a week of work, though final prep for London All Hands might stretch that out a couple days. I'll add a few more details under the UI/UX changes listed above.

**Comment by hannahkane** [comment]
Added tickets to advocacy.mozilla.org repo
 * [Design](https://github.com/mozilla/advocacy.mozilla.org/issues/155)
 * [Implement](https://github.com/mozilla/advocacy.mozilla.org/issues/156)

Tag yourself in tickets to follow along.

**Comment by kristinashu** [comment]
I've also added a content ticket to gather copy and photos https://github.com/mozilla/advocacy.mozilla.org/issues/168

**Comment by hannahkane** [comment]
Design work is done. Implementation ticket is a candidate for the next heartbeat.

**Comment by vanessarhinesmith** [comment]
Thanks @hannahkane and thank you @kristinashu for your amazing work on this!

**Comment by vanessarhinesmith** [comment]
What's the best way to get a meeting invite to the next heartbeat (I'm still a newbie). TY!

**Comment by hannahkane** [comment]
We'll likely have a heartbeat kickoff meeting soon after London. I'll invite you, @vanessarhinesmith.

**Comment by vanessarhinesmith** [comment]
Thanks @hannahkane!

**Comment by hannahkane** [comment]
Hey @Melechuga and @vanessarhinesmith - we didn't have a kickoff meeting, but we did discuss this issue in our stand-up meeting today. I wanted to share a status update:
 * As you know, the design phase is done
 * We're going to focus next on implementing the content changes as soon as possible, so that we don't block any community-facing communications you have planned around this. 
 * For the design changes, we'll need to take more time. We need to build out a central repository for shared UI components that we can use across sites—right now the Science site components are not available to use on the Advocacy site. We also have work to do on the Advocacy site side to make it work with the shared components.

I wanted to let you know all of this in case it affects your external comms plans. Let me know if you have any questions.

cc @gvn @alanmoo in case I misrepresented anything above, or to answer any technical questions

**Comment by Melechuga** [comment]
Hey @hannahkane Thanks for the update!
When you say it might take some time, is there a ball-park? We had been hoping to have this up by July 1, but if that's not possible, do you know around when?

**Comment by hannahkane** [comment]
Hey @Melechuga—I'm realizing I wasn't clear in my earlier comment. We can have the content changes before July 1. Meaning, we can change the copy on the site to reflect the new fellows and new information. In fact, we're curious to know if there's a date that too _early_ to push those changes.

What we can't do before July 1st is the design and page layout changes, as these are part of a larger project to standardize design elements across all of our web properties. (@alanmoo, please correct any errors here ->) We can't, for example, change the Fellows section to be a tabbed structure like we have on the Science site. Also, for the "Meet Our Fellows" sub-page, we can't have the tabs there to distinguish between current fellows and alumni. We'll need another solution that doesn't require new design components for the interim. cc @kristinashu.

We're looking into an estimate for those changes, but this is separate from making the content changes detailed in this ticket.

Let me know if that makes sense.

**Comment by Melechuga** [comment]
Hey @hannahkane, I just spoke with @vanessarhinesmith and we think we have a workable solution.

We chose July 1st as our ideal date, since the fellows have been in the selection process for a while and we were excited to tell the world. However, they don't officially start until September 1, so that's more our drop-dead date. We don't want to create more work for a stop-gap, so we're fine with leaving the website as is until the final changes can go through.@alanmoo Do you think we can set Aug 1 as our launch date? 

Thanks all!

**Comment by hannahkane** [comment]
We discussed this at our stand today. August 1 seems like a really reasonable launch date. Thanks for the extra leeway!
