### ISSUE TITLE
Release the new science site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/plan#814]
Expectation is we'll complete this early in the next heartbeat.

Order of operations:
 - [x] Resolve blocking QA bugs
 - [x] Soft launch by putting heroku app at science.mozilla.org
 - [x] Get OK from both @acabunoc and @simonwex before...
 - [x] redirecting mozillascience.org to science.mozilla.org
 - [x] telling the community!

What am I missing? 

cc @acabunoc @alicoding @gideonthomas @cadecairos @gvn @alanmoo

**Comment by hannahkane** [comment]
QA continues today, and there are a handful of QA bugs we want to resolve before making a public announcement and redirecting the former site url to the new one. @acabunoc will give us the go-ahead, likely early next week.

We've also involved @KevZawacki to help incorporate messaging about the new site through appropriate channels.

**Comment by hannahkane** [comment]
This is done!!!!!!!

Post-All Hands, we'll come back to [Phase 2](https://github.com/mozilla/science.mozilla.org/milestones/Phase%202).

**Comment by xmatthewx** [comment]
yay! nice job everyone. congrats!! there should be a ceremony to burn that backup plan y'all wrote.

**Comment by gvn** [comment]
![itclap](https://cloud.githubusercontent.com/assets/206379/15754193/d4490b5c-28ab-11e6-8940-59f34666a57b.gif)
