### ISSUE TITLE
FancyFox for Open Web Fellows \(^.^)/

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/plan#817]
#### DARCI
Driver: @vanessarhinesmith 
A: @xmatthewx 
R:
C: Melissa
I:

#### Overview
We have a super creative and fun project for a designer! The Open Web Fellows program wants a version of FancyFox as a mascot to print stickers, etc. Something like Science's fox...

#### Links
Science Lab Fox: https://mozillascience.github.io/working-open-workshop/assets/images/science-fox.svg

#### KPIs
Stickers n t-shirts n swaaaaag

#### Key Deadlines

- [ ] Asap? We want to use the design for printing for an event in July

**Comment by Melechuga** [comment]
@xmatthewx I "assigned" you so you could redirect it to whomever you think best; thanks!

**Comment by vanessarhinesmith** [comment]
Hi friends. Just wanted to circle up on this. Thank you, thank you!

**Comment by Melechuga** [comment]
Hi @vanessarhinesmith,
If this is something you still want to push forward, please feel free to do so! I'm taking myself off this thread to avoid GitHub confusion. Thanks!

**Comment by ghost** [comment]
Thanks Mel! I am actually going to close.
