### ISSUE TITLE
Production support chart

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#824]
#### DARCI
Driver: @hannahkane 
A:
R: @xmatthewx @simonwex 
C: 
I:

#### Overview

The production team supports various programs and initiatives. Our capacity is not infinite. 

Let's clarify the types of deliverables we provide based on the type of initiative and level of MoFo's commitment to the initiative, the strategic value, and the potential impact. All of our work is important, but not equally important. 

This should cover MoFo, Hubs, Programs, Initiatives within programs ... include Design, Dev, Ops, project management. 

#### Links

Here's a MoCo table that articulates [brand support for initiatives](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=61249802#BrandandIdentityGuide(orHowtoSuccessfullyBrandYourEarlyStageProject)-BrandAssetsforTechnologyProjects(Logos,Names,Websites,etc)) as they level up from experiment to official product. 

#### Deliverable

A table or chart is likely a useful deliverable. It could live on http://mofo.build.

**Comment by xmatthewx** [comment]
I've started two tables to summarize this info. Details to add and revise. 

<img width="782" alt="screenshot 2016-07-27 10 54 42" src="https://cloud.githubusercontent.com/assets/53411/17179843/9f07bb38-53e8-11e6-976d-a274600a539c.png">

<img width="768" alt="screenshot 2016-07-27 10 54 50" src="https://cloud.githubusercontent.com/assets/53411/17179844/9f081146-53e8-11e6-87a2-e0333911c2cb.png">

**Comment by xmatthewx** [comment]
And this...

<img width="786" alt="screenshot 2016-07-27 11 16 12" src="https://cloud.githubusercontent.com/assets/53411/17180777/8b649102-53eb-11e6-9b49-bf324d787a2c.png">

**Comment by secretrobotron** [comment]
cc @secretrobotron 💥

**Comment by hannahkane** [comment]
Closing in lieu of tickets in production repo
