### ISSUE TITLE
Update mozilla.org/foundation with new pages / navigation

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/plan#825]
#### DARCI

Driver: @Lottarao 
A: @samanthaburton 
R: @Lottarao 
C: @kevinzawacki
I: -- 
#### Overview

We are updating mozilla.org/foundation once again to better reflect the 2020 strategy. Specifically, adding three more sub-pages: mozilla.org/foundation/advocacy, mozilla.org/foundation/leadership, and mozilla.org/foundation/issues
#### Links

https://docs.google.com/a/mozilla.com/document/d/15JqsTohms1eTYTg_bEbTyq6WLey5yXXer2vxMz6C_rU/edit?usp=sharing

https://docs.google.com/a/mozilla.com/document/d/177K4FQ7fi_x2UE7YIL94jUmINxt8rTGcKiQGTnuXSUI/edit?usp=sharing

https://docs.google.com/a/mozilla.com/document/d/1GK-1sLtxs0ry2OUiMmBXMosI9zqvZP9jEebybiN45Jo/edit?usp=sharing
#### KPIs
- [ ] Updated website
#### Key Deadlines

Flexible

**Comment by xmatthewx** [comment]
cc @sabrinang for a little design input

**Comment by hannahkane** [comment]
Looks like these updates were made. However, @Lottarao and @KevZawacki - does the Foundation page need another review at this point? Feel free to open a new ticket if so.

**Comment by KevZawacki** [comment]
@hannahkane The page is in good shape now -- but will likely need a refresh in Q1 2018.
