### ISSUE TITLE
Figure out final Women & Web Lit. url

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/plan#827]
A lot of amazing work/brainstorming has already been done in https://github.com/MozillaFoundation/Design/issues/194 and the outcome of that issue is going to be the current interim url for the WWL web project.

As can be extrapolated from that issue, there seems to be some questions regarding how WWL fits into the IA of MLN and what that means for the url it can be accessed at.

### Notes
Some key points of interest migrated from that issue are:
- WWL is its own hub AND is heavily rooted in learning hub (clubs + web lit)
- The IA currently defines WWL as a top-level hub
- If WWL is treated as a "sub-hub", we can potentially run into issues with respect to the url patterns as we incorporate common hub features

### Outcome
- WWL's place in the IA is clear
- Subdomain within mozilla.org for WWL has been finalized

cc @amirad, @xmatthewx, @hannahkane, @kaythaney, @simonwex, @chrislarry33, @kaythaney, @mcdermott415

Feel free to clarify anything that I might have missed/misinterpreted from the linked issue.

**Comment by xmatthewx** [comment]
@gideonthomas this is a excellent summary of the topic. Thanks for the diligence. 

I'm not sure if the last point is resolved. I could make a case for a temporary home at `learning.m.o/womenandweblit`, or a permanent home at `womenandweblit.mozilla.org`. I might be mistaken, but this decision has some tech implications. Unless we have a compelling reason to choose subdomain or subpage... 

I recommend we choose the simplest tech to get the job done well enough, and then set the URL accordingly. That's my 2₵.

**Comment by gideonthomas** [comment]
Based on the discussions from our meeting, here are some noteworthy points:
- Etherpad Link: https://public.etherpad-mozilla.org/p/wwl-ia
- As an interim solution for this product (#826), we will stick to `https://mozilla.github.io/womenandweb` as the url
- Currently WWL is very similar to the clubs model used in the Learning hub
- The future for WWL is unclear, with the possibility of expanding beyond web literacy
- We need a migration plan for the `github.io` url to a new one if the direction of WWL changes in the near future

It seems like this is an issue that is worth tackling in the future once WWL is more established and plans for it are clearer. Until then, feel free to archive this issue (by closing it) or keep in open.

cc @hannahkane, @mcdermott415, @kaythaney, @amirad

**Comment by amirad** [comment]
👌

**Comment by hannahkane** [comment]
Closing. I assume we'll open a new issue as the program evolves and new needs for the web presence emerge.
