### ISSUE TITLE
Insights - Replace image in Mozilla Strategy doc

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#828]
#### DARCI
Driver: @secretrobotron
A: @samanthaburton 
R: ~~Probably~~ @flukeout
C: @samanthaburton 
I: @Lottarao, Mark, @KevZawacki ?

#### Overview
Reformat this [MLN Programs diagram](https://docs.google.com/presentation/d/1d1n0kZeaKcsYIaTCCQmWP-vYODpSAlRkwPad2vbLgxw/edit?ts=578e5e14#slide=id.g15606e53fb_2_45) to fit into the [Mozilla Strategy: Fueling the Movement](https://docs.google.com/document/d/1KLFDzyr1jC-19TH7sI6WEBSYmo2KUyzxHzgb0j_KaUg/edit?ts=5798fcfd#heading=h.npv1noiybre4) document. It should match the [greyscale] colour scheme and the visual design of the other diagrams already present in the strategy document, and replace the diagram already in the How we Work section.

#### Links
- Existing MLN Programs diagram: https://docs.google.com/presentation/d/1d1n0kZeaKcsYIaTCCQmWP-vYODpSAlRkwPad2vbLgxw/edit?ts=578e5e14#slide=id.g15606e53fb_2_45
- Luke’s AI files in which he created the existing diagrams: (@flukeout, where are these?)
- Strategy document: https://docs.google.com/document/d/1KLFDzyr1jC-19TH7sI6WEBSYmo2KUyzxHzgb0j_KaUg/edit?ts=5798fcfd#heading=h.npv1noiybre4

#### KPIs
- [ ] Diagram is in greyscale
- [ ] Diagram matches the visual style Luke used
- [ ] Diagram replaces the one currently in the document

#### Key Deadlines
- [ ] Diagram is in place at end of next heartbeat

**Comment by secretrobotron** [comment]
Tracking progress here: https://docs.google.com/spreadsheets/d/1P-KuB0xqO4x3E5y1jYMZqCMKHVGhNAEarwdLABtvJKY/edit#gid=0

**Comment by flukeout** [comment]
ARE YOU READY??????? let me hear some noooooise....

**Comment by flukeout** [comment]
Put your hands in the air... and SCREEEEAMM!!!!

**Comment by flukeout** [comment]
I can't hear you......??? LOUDER!!!!

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/17608979/59c74b02-5fe5-11e6-97ba-5310953e30d8.png)

**Comment by flukeout** [comment]
THE CROWD JUST LOSES IT... they're going CRAAAZY!!!!!

💯 💯 🔥 🔥

**Comment by flukeout** [comment]
All assets, including this new diagram, are in the Google Drive...
https://drive.google.com/open?id=0B_CPRh4f3yyqanJLOXZfbHh1Unc

Let me know if you need any changes.

**Comment by hannahkane** [comment]
Just lurking and noticed a typo in the word "Partnerships." Looks nice!

**Comment by samanthaburton** [comment]
![giphy](https://cloud.githubusercontent.com/assets/16709293/17623439/07bfde9e-606e-11e6-9ef5-4c11a3476ade.gif)

**Comment by samanthaburton** [comment]
One small change request - can we make all of the vertical bars the same height? Just don't want the different heights to be interpreted as a difference in the programs size/age/importance...etcetc

Thanks so much @flukeout !

**Comment by ldecoursy** [comment]
+1 to Sam B.

**Comment by KevZawacki** [comment]
omg 

_(realizes @flukeout did the voice work in [NFL Quarterback Club '96](https://youtu.be/KNiIenc7ovs?t=1m53s) for SNES.)_

**Comment by flukeout** [comment]
Updated the arrows, fixed the typo and updated the files in the Google Drive.

![image](https://cloud.githubusercontent.com/assets/25212/17628968/b3d1276c-606c-11e6-87ba-b9567b1b57e5.png)

**Comment by ldecoursy** [comment]
One more change, sorry! We need to change "programs" back to "hubs."  In the headline as well as the future vertical bar.

**Comment by flukeout** [comment]
Updated. Latest source and individual files are in the [Google Drive](https://drive.google.com/open?id=0B_CPRh4f3yyqanJLOXZfbHh1Unc)

**Comment by secretrobotron** [comment]
👍 updated the progress tracker

**Comment by flukeout** [comment]
Thanks @secretrobotron - wouldn't have felt right without that.
