### ISSUE TITLE
MoFo Brown bag on Mozilla rebrand 

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#830]
#### DARCI

Driver: ??
A:
R: @xmatthewx, @HPaulJohnson, @lovegushwa  
C: ??
I:

Description and plan TBD.

**Comment by hannahkane** [comment]
@xmatthewx - would this still be useful? Please close if not.

**Comment by xmatthewx** [comment]
It would be useful. But probably after we have more resources from MoCo, templates etc for staff to use.
