### ISSUE TITLE
Build DSO exhibit for Mozfest

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/plan#834]
#### DARCI

Driver: @secretrobotron
A: @secretrobotron @LauraReynal 
R: @secretrobotron @LauraReynal @taisdesouzalessa 
C: @secretrobotron @LauraReynal 
I: @Saallen
#### Overview

We're building an exhibit within the MozEx grounds for Mozfest this year to display DSO using @LauraReynal's beautiful, high-res photography, and insights gathered from the research. We need design help to figure out how it will look exactly.

It will look a little bit like this, but will definitely change to accommodate the space (working with MozEx folks on that now).
![circle](https://cloud.githubusercontent.com/assets/403231/18725233/6b8650b6-800d-11e6-846b-3e916928c31c.jpg)

Sample photos (need review):
![28430299545_9b45e2d43f_z](https://cloud.githubusercontent.com/assets/403231/18725368/0ae0240c-800e-11e6-82e3-2876a5f129c3.jpg)
![27813765864_9bcf7cc8ee_z](https://cloud.githubusercontent.com/assets/403231/18725369/0be88934-800e-11e6-9614-27aa13cdf8f0.jpg)
#### Links
- Mozfest github ticket: https://github.com/MozillaFoundation/mozfest-program-2016/issues/655
- Laura's flickr album: https://www.flickr.com/photos/laura_nk/albums
#### KPIs
- [x] @LauraReynal goes to Ravensbourne to figure out the physical environment
- [x] @LauraReynal and @secretrobotron figure out how to print stuff
- [x] @secretrobotron & @LauraReynal choose photos and provide drafts of descriptions
- [x] @taisdesouzalessa makes a mood board or some initial sketches
- [x] @taisdesouzalessa @LauraReynal and @secretrobotron finish finals
#### Key Deadlines
- [x] Mozfest occurs on October 28th

**Comment by xmatthewx** [comment]
This is going to be beautiful. 

Also, it is a much bigger project than it seemed when we talked last week. I thought it was a few posters that needed a photo selected and text placed on it. Not an extensive collage of text and images. 

We'll have to run this by @hannahkane to see if it does or doesn't fit within the upcoming heartbeat.

@taisdesouzalessa has another priority and too much orientation on her plate to tackle this right now. The other designers are waist deep in festival wide design and session prep.

**Comment by secretrobotron** [comment]
'Twas great. https://www.instagram.com/p/BME6VtRAJlK
