### ISSUE TITLE
Board: Write MozFest piece

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/plan#836]
Responsible for copy: @steviebenton
Copy signoff: @chrislarry33 (Claw)
Responsible for design: @natalieworth 

**Context:**
We have a major board presentation coming up. (There's an entire team working on pulling together content.) We need to write content for the MozFest slide(s) that will go in the presentation deck. The audience is board members. For reference, [last year's presentation](https://drive.google.com/file/d/0B2qu3ExKWIlvaFpFUlJDQ1EyNmM/view).

**To Do:**
Write 5 _short_ blurbs that link a network story from the festival with each of our key issues.

Notes:
- there will be a separate set of stories about people, so this should focus on programs

Due Date: Wednesday Oct 12

cc @natalieworth for design constraints (wordcount)

**Comment by StevieBenton** [comment]
Thank you for the add, @edrushka 

Just as a steer, when you say network stories, can I use anything programmatical from Medium, Pulse, anything like that?

**Comment by StevieBenton** [comment]
OK, I think I have something. I'm not entirely clear on the kind of stories we want to highlight but have put together a first attempt for comment and feedback, very much with a second version in mind that will be closer to the brief. [It's here](https://docs.google.com/document/d/1mWF-fZp-W_AEnlZGCUIEmKWyFIxgQZnXF7Y2SHglC6c/edit?usp=sharing).

**Comment by chrislarry33** [comment]
Thanks @StevieBenton great start and I appreciate the speed. I think we need even another level of specificity on each issue. I.e. looking at a specific art installation that examines privacy

**Comment by StevieBenton** [comment]
That's helpful @chrislarry33 thank you. I will take another look then post here with an updated version.

**Comment by chrislarry33** [comment]
@StevieBenton glad to hear it. The key really is exciting examples about how MozFest will demonstrate the issues in action in a sexy way that will engage the board members quickly.

**Comment by StevieBenton** [comment]
@chrislarry33 I've had another go. I think the stories are quite sexy - such as a game to teach about CSS, the long term impact of an installation - but it's a little longer than before. As ever, all comments welcome!

[It's here](https://docs.google.com/document/d/1mWF-fZp-W_AEnlZGCUIEmKWyFIxgQZnXF7Y2SHglC6c/edit).

**Comment by chrislarry33** [comment]
Much closer @StevieBenton but needs to be preview of mozfest 2016 not a look back

**Comment by edrushka** [comment]
Sorry - I misunderstood. I thought it could be retrospective.

**Comment by StevieBenton** [comment]
No problem at all. I'll review what's there and see if I can find some stories that are about this year. I'll ping you with an amended version. Is tomorrow OK for a next attempt?

**Comment by StevieBenton** [comment]
Hello again everyone. [3rd draft is here](https://docs.google.com/document/d/1mWF-fZp-W_AEnlZGCUIEmKWyFIxgQZnXF7Y2SHglC6c/edit?usp=sharing) and I think this is much closer. I have chosen these examples because they tie in really well with the overall aims of the festival and include a range of session types and focuses. 

Please do let me know what you think.

**Comment by StevieBenton** [comment]
[Latest version is now available](https://docs.google.com/document/d/1mWF-fZp-W_AEnlZGCUIEmKWyFIxgQZnXF7Y2SHglC6c/edit). @chrislarry33 I've taken on board your suggestion that the blurbs could be longer and have doubled them in length. In my view they are still punchy and powerful.

In terms of images, should I move on with that, or is it best left to @natalieworth as the designer?

**Comment by edrushka** [comment]
Please leave images and design to Natalie.

**Comment by StevieBenton** [comment]
Hello again everyone. I've had another go and I think this version is the closest yet. I've tried to inject as much sizzle as possible without veering into hyperbole. 

[It's here](https://docs.google.com/document/d/1mWF-fZp-W_AEnlZGCUIEmKWyFIxgQZnXF7Y2SHglC6c/edit?usp=sharing). Again, I've kept all earlier versions in the same doc in case some of the earlier content is of use. Please do let me know your thoughts! If anyone is particularly keen I can have another look over the weekend.

**Comment by StevieBenton** [comment]
Hello @edrushka @chrislarry33 

I just wanted to check in quickly as I know that deadline is approaching. Is there anything else needed from me at this point or are you happy with the draft as it stands? 

I'm heading to the fringe event at Tate Britain now but will be back online at about 4pm BST.

**Comment by edrushka** [comment]
Thanks @StevieBenton. This looks good to me but I defer to @chrislarry33.

**Comment by xmatthewx** [comment]
@chrislarry33 – is Version 4 in the doc good and ready for design? 

@edrushka @StevieBenton – it seems like this needs to be paired with a description of the festival itself. Should we grab things from the festival guide? Or is there better language somewhere for this audience?

**Comment by StevieBenton** [comment]
Hey @xmatthewx - I defer to @edrushka but am happy to put something together if required.

**Comment by edrushka** [comment]
@xmatthewx Please grab existing MozFest copy from the guide or the website. If @chrislarry33 needs something more specific, just let us know.

**Comment by hannahkane** [comment]
Closing since this has passed
