### ISSUE TITLE
Board: Design MozFest piece

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#838]
We need a simple handout on MozFest for the upcoming board meeting. 
- Content: nearly ready: #836
- Format: simple but flexible. Could be a 2 sides of one page. Could be a folded tabloid piece. Requires branding and a little imagery for interest. Nice but simple. 
- Could use Fest Guide as template if that simplifies.  
- Printing: Likely printed in office or at a local copy-shop. Can you confirm? @OpenMatt 
- Deadline: Will be used at meeting on Oct 20th boarding. Aim to review draft Monday Oct 17th.

cc @edrushka @chrislarry33 @kristinashu

**Comment by OpenMatt** [comment]
re: printing. @xmatthewx if you provide a digital file here in this ticket, we will include it with the overall package we are delivering to the printer

**Comment by OpenMatt** [comment]
@xmatthewx thanks for filing this. Just so I'm clear: you have what you need to deliver that file by Monday? Drop dead for sending to the printer is Tuesday am.

**Comment by xmatthewx** [comment]
The plan is for a single 11x17 sheet, folded in half for 4 pages. Could shape up like this:
- cover: branding
- inside left: About Mozfest (text lifted from [fest guide intro](https://redpen.io/jr72af2223fa3f4a0a))
- inside right: Stevie's 5 issues at Mozfest ([doc](https://docs.google.com/document/d/1mWF-fZp-W_AEnlZGCUIEmKWyFIxgQZnXF7Y2SHglC6c/edit))
- back: decorative, maybe link to site and schedule

Sound good? We are neck deep in MozFest production deadlines. So this piece we be kept relatively simple.

**Comment by OpenMatt** [comment]
Yep sounds good. Thanks Matthew.

**Comment by kristinashu** [comment]
@xmatthewx here's a rough start. I tried a folded tabloid but had trouble fitting the copy in so here it is as one double sided landscape letter.

Front:
![board](https://cloud.githubusercontent.com/assets/1068783/19405173/93ab9528-9229-11e6-8b9c-4846bf7ff1f4.jpg)

Back
![board2](https://cloud.githubusercontent.com/assets/1068783/19405174/93b0d1f0-9229-11e6-96c6-e2ac3561e59d.jpg)

Alternative Front:
![board3](https://cloud.githubusercontent.com/assets/1068783/19405175/93b6fc7e-9229-11e6-93df-5b787976880f.jpg)

InDesign files are here: https://drive.google.com/open?id=0B2irLVDJivhLcVE1MzVxa0pMQ2s

**Comment by OpenMatt** [comment]
@xmatthewx any updates here? Think we can be ready to ship by EOD today? 

btw looks like there's a paragraph break missing above "Online Privacy & Security" for "Key Issues"

**Comment by xmatthewx** [comment]
@lovegushwa – can you review the [Mozfest PDF](https://drive.google.com/open?id=0B_rbDAen9prkOGlSamFUN0RUQmM)? (Download for a proper view.) This is designed to be printed as a folded sheet of 11x17. But could just be three letter-sized pages, dropping the last one.

You'll find artwork [in drive](https://drive.google.com/drive/u/1/folders/0B2irLVDJivhLcVE1MzVxa0pMQ2s) if any changes are needed.

<img width="477" alt="screenshot 2016-10-17 17 44 00" src="https://cloud.githubusercontent.com/assets/53411/19456817/5136fad8-9491-11e6-8280-20a9769f44f8.png">

**Comment by xmatthewx** [comment]
@OpenMatt @edrushka @chrislarry33 – take a minute to review handout on MozFest for the board meeting. Any errors or concerns? 

[Mozfest PDF](https://drive.google.com/open?id=0B_rbDAen9prkOGlSamFUN0RUQmM)<< download it. Google will mess things up in their preview.  

cc @kristinashu on the west coast if any changes are needed.

**Comment by chrislarry33** [comment]
Looking good @xmatthewx A few nits:
- Can you make the blurbs read in this order: Online Privacy, Digital Inclusion, Open Innovation, Decentralization and Web Lit. I think Web Lit is weakest blurb so want it last
- Cut this copy in intro text: "We’re delighted you’ve joined us. We invite you to build, debate, and explore the future of a healthy internet."

**Comment by xmatthewx** [comment]
Thanks. Edits are done in [PDF v5](https://drive.google.com/open?id=0B_rbDAen9prkc001aDJkcTRrVjA). This and artwork are in [Drive](https://drive.google.com/drive/u/1/folders/0B2irLVDJivhLcVE1MzVxa0pMQ2s).

**Comment by xmatthewx** [comment]
@lovegushwa – if this passes your eye test, I think we're good to go.
