### ISSUE TITLE
MozFest matching game! (stickers)

### ISSUE THREAD

**Issue by abbycabs** [MozillaFoundation/plan#839]
We're going to have another matching game at MozFest! 
#### DARCI

Driver: @acabunoc
A: @xmatthewx 
R: @flukeout @acabunoc
C:
I:

I may have done DARCI wrong.
#### Overview
- [x] Design stickers @flukeout 
  - ~ 24 - 40 combinations
  - Large enough to see your match in a crowd, small enough to not cover languages
- [x] Order stickers (1500 stickers)
- [x] Decide what happens when people find a match
  - Enter a raffle -- raffle box in the Open Leadership area on the 9th floor
  - ask them to tweet a picture of the match?
- [x]  [nice to have] Signs at registration explaining how to use the stickers w/ examples
  - "Draw lines connecting the nodes in your network!"
- [x] [nice to have] Posters around MozFest - explaining how to win
  - "Find your match in our network? Go to the 9th floor for a chance to win a prize"
- [x] find a raffle box
- [x] [nice to have] signage at the Open Leadership area explaining the game and pointing to the raffle
- [x] Design raffle ticket (if it's a raffle)
  - questions: name, email, "send me info on OLTS", "I'm interested in being a mentor"
#### Key Deadlines
- [x] Order stickers by Monday
- [x] MozFest

![image pasted at 2016-10-21 12-41](https://cloud.githubusercontent.com/assets/617994/19613417/6fcf9e6a-97ba-11e6-989e-80c56a1b5a7e.png)

**Comment by abbycabs** [comment]
Stickermule may not deliver in time!

While you're thinking of designs @flukeout consider printing on shipping labels from last year (or another size):
https://www.amazon.co.uk/Sheets-Shipping-Labels-White-Address/dp/B006GQ4OHC/ref=sr_1_6?ie=UTF8&qid=1446159734&sr=8-6&keywords=shipping+labels

**Comment by flukeout** [comment]
Let's get these [round ones](https://www.amazon.co.uk/Labels4u-Self-Adhesive-Circular-Printable-compatible/dp/B010TANG6K/ref=sr_1_7?ie=UTF8&qid=1477090285&sr=8-7&keywords=circular+sticker+template) - nicer & fits the brand. Will you be ordering?

**Comment by flukeout** [comment]
Damn, those circles are quite large though, 6.3cm across, this is how they'd appear...

![image](https://cloud.githubusercontent.com/assets/25212/19614280/54c35f7e-97a8-11e6-800b-e427af93a977.png)

@sabrinang @kristinashu what do you think of the above?

**Comment by kristinashu** [comment]
Yeaaah that's pretty big...

**Comment by flukeout** [comment]
If we can find something closer to 4.5cm/45mm, that would be better I think, here's how that would look...

![image](https://cloud.githubusercontent.com/assets/25212/19614308/b952ef7c-97a8-11e6-8128-c0dad59ff2de.png)

...also that would limit us to the white and light green sticker colors, since the pink sticker wouldn't show up.

**Comment by kristinashu** [comment]
Much better!

**Comment by flukeout** [comment]
WIP of a little poster / printout we can have on hand or nearby to explain how things work. Still unsure about the actual type of drawing people should make. Will keep thinking.

![image](https://cloud.githubusercontent.com/assets/25212/19614518/e0385cec-97aa-11e6-86a6-ed7bf2f0d5fe.png)

**Comment by sabrinang** [comment]
@flukeout Cool, I'm excited for this matching game! Is this specifically from Open Leadership? It would be useful to indicate it in Step 4 where to come back to or on the top you can indicate the game is brought to you by Open Leadership etc.

@kristinashu For the sizing, how large were the [language stickers](https://redpen.io/p/vfb6a99be818e00757)? It might be nice to be around that size if they were not too big

**Comment by kristinashu** [comment]
Language stickers are pretty small, 40x40mm.

**Comment by flukeout** [comment]
40mm would work for this, too - just gotta find the right sticker template. @acabunoc will you be looking into that?

**Comment by kristinashu** [comment]
I assume we could print them along with the language stickers, especially if they're the same size. We're also planning to use a more matte sticker so the pen won't smudge. I can inquire with Marc. How many are you thinking of printing?

**Comment by flukeout** [comment]
That would be great! When would you need the final designs by? The plan is to do these like the DNA stickers last year, so one per attendee. Would that work?

**Comment by abbycabs** [comment]
Amazing work here! I'm so excited to see this action :)

Printing: If we can get this printed together with the language stickers, that would be great! Otherwise, I'll look into labels and ship something today.

Colour: What color are the language stickers? Should we be a different color so to make it easier to find matches?

For step 4: I'd like to leverage the contacts we find here to get people more involved in our network. The Open Leadership mentor program seems like a good fit, but I may be biased. @xmatthewx what do you think?

Thanks so much @flukeout

**Comment by abbycabs** [comment]
Labels I can order & print on in London: https://www.amazon.co.uk/Label-Self-Adhesive-Circular-Stickers-Printable/dp/B006GP9VXA/ref=pd_sim_229_3?_encoding=UTF8&psc=1&refRID=9YEKMSEGR81E7A2CYGKN

**Comment by xmatthewx** [comment]
Open Leadership is a perfect place to host this activity. Do you have the hands to receive the traffic? Should we try and recruit? 

@kristinashu - it'd be great to do this alongside language stickers.

**Comment by xmatthewx** [comment]
Thanks @flukeout for the speedy help. I knew we could do this!

**Comment by abbycabs** [comment]
I got some space at the entrance of the 9th floor and a group of mentors willing to help out! I think we should have full coverage of if people manning the area. I'll let you know if we need to recruit more!

**Comment by mmmavis** [comment]
omg i LOVE this idea and the design looks fantastic! I like the hand drawn looking examples especially.

can't wait to play this game 👏 🎉

**Comment by edovio** [comment]
Fantastic!!! :) ahahah I can't wait to play this!!!

**Comment by abbycabs** [comment]
Game is done!

Some stats:
262 total entries
160 unique entries
105 unique entries that checked off a box
84 unique entries want follow up on open projects they can contribute to
79 unique entries want follow up on best practices Working Open & OLTS
48 unique entries want to talk to someone about joining the mentorship program

👏 👏 thanks all! Closing issue

**Comment by flukeout** [comment]
Thanks for the summary @acabunoc - did you ever get ahold of the winner?

**Comment by xmatthewx** [comment]
Awesome stuff. Is there a ticket for follow up for people who requested it?

**Comment by abbycabs** [comment]
@flukeout - I got in touch with the winner, @kaythaney is awarding the prize!

@xmatthewx I followed up on Tuesday (48 hour rule of follow up)

Email content below (each was personalized with the first name and only included sections they checked off)

---

Hi << First Name >>,

Thank you so much for playing the Sticker Match game at MozFest 2016!

You're getting this email because you indicated that you're interested in:
- contributing to open projects,
- working open, and
- our open leadership mentorship program.

The [Open Leadership program](https://github.com/MozillaFoundation/mentorship-program) uses [best practices working open](http://mzl.la/open-leadership) to strengthen our network, increase collaboration and engage contributors on the open projects in our community.

**Contributing to Open Projects**

Thanks your interested in contributing to some of the projects we're working with! You can browse through the project currently in the mentorship program:
https://mozilla.github.io/network-pulse/?keyword=open%20leadership

When you find a project you're interested in, click on the card to learn how you can get involved.

**Working Open**

The Open Leadership program uses best practices working open to engage more contributors in our work. We've collected these best practices in this guide:

Open Leadership Training Series: http://mzl.la/open-leadership

**Mentorship Program**

This program pairs community members running open projects with a mentor for 1:1 help applying best practices working open. You can read more about the mentorship program in our [GitHub repo](https://github.com/MozillaFoundation/mentorship-program).

If you're interested in learning more about this program or joining us in future rounds, I would love to chat with you! I setup a few [appointment slots](https://calendar.google.com/calendar/selfsched?sstoken=UUtxcDM0M2R3MjVDfGRlZmF1bHR8OWFhZTBmMzI3OGFhY2E1ODJlNzdjN2U5NDMzOTdhZjg) you can book. Select any slot titled **"Mentorship Program Q&A"** to book a google hangout session with me.

Appointment slots:
https://calendar.google.com/calendar/selfsched?sstoken=UUtxcDM0M2R3MjVDfGRlZmF1bHR8OWFhZTBmMzI3OGFhY2E1ODJlNzdjN2U5NDMzOTdhZjg

**Keep in Touch**

Follow us on twitter at [@MozOpenLeaders](https://twitter.com/MozOpenLeaders)

---

If you have any other questions, I'm happy to help! Please feel free to drop me an [email](abby@mozillafoundation.org) or [send along a tweet](http://twitter.com/abbycabs).

Looking forward to working more with you,
Abby

Abigail Cabunoc Mayes
Lead Developer, Open Source Engagement
Mozilla Foundation
@abbycabs / @acabunoc

**Comment by abbycabs** [comment]
If anyone's interested I used [Yet Another Mail Merge](https://yet-another-mail-merge.com/) to send out the follow-up with personalization
