### ISSUE TITLE
Unified Tool Prototypes

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#84]
Continued iteration of unified creation tool based on prior prototypes and design phase to be done at the Toronto design work week.

#### RACI
Phase: Design / Prototype
Owner: @cassiemc
Decision: @thisandagain
Lead design: Meet-up
Lead dev: n/a
Quality: n/a

**Comment by secretrobotron** [comment]
Prior work in #79.

**Comment by thisandagain** [comment]
This work will be done during the design meet-up in TOR from 23rd - 27th.

**Comment by cassiemc** [comment]
Just documenting our to-do list from this morning.

## Tiles
- [ ] mobile authoring
- [ ] zoomed tile UI
- [ ] Start
- [ ] edit
- [ ] published view
- [ ] navigate
- [ ] share/collaborate
- [ ] webby qualities
- [ ] learning aspects
- [ ] user test script (what would you make; for who)

## Timeline
- [ ] figure out content types
- [ ] UI of pathing / forks
- [ ] start
- [ ] edit
- [ ] published view
- [ ] navigate
- [ ] share/collaborate
- [ ] webby qualities
- [ ] learning aspects
- [ ] user test script

To reiterate, both prototypes need (for testing this afternoon):
* way to start
* way to edit (Sabrina & Jess)
* published view (Cass & Luke)
* navigation between zoomed in / zoomed out (Ricardo & Mw)
(extra) way to share / collaborate
(extra) way to learn

**Comment by cassiemc** [comment]
Documented some progress in my blog: http://www.cassiemcdaniel.com/blog/prototyping-a-new-webmaker-tool/ (More images and better prototype sketches to come later)

**Comment by thisandagain** [comment]
Excellent work from the design meet-up. Tracking next steps here: https://github.com/MozillaFoundation/plan/issues/365
