### ISSUE TITLE
Design the Digital Skills Observatory Final Report 

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/plan#841]
#### DARCI
Driver:
A:  
R: @flukeout
C: @lauraReynal @secretrobotron 
I: ?

#### Overview
After a year of research work, the DSO project needs to deliver a PDF report and a website to communicate the findings from the research. 
We are creating the PDF report, that will then be printed and distributed to a group of stakeholders. Because it is a big piece of work, we need help with design to: make it look good, make it easy to navigate, understand the content, and have a powerful storytelling. 

#### Links
Full design brief: https://docs.google.com/document/d/1S9w_SKom_hmnPkiz0hQcbQL5vrJlpATbn5r9z07GRH4/edit# 
with details about what needs to be done. 
Report's copy: 
https://docs.google.com/document/d/1SwFYKbBNJ_05Xg07UoJJ45_6Zsxi0ARkCjaXC24PdiA/edit# 
the actual report with indications of content structure 
Direction: https://fr.pinterest.com/laureynal/editiorial-infographics-design-inspirations/ 

#### KPIs

- 1 styling guide and content guide produced
- a set of infographics specially designed to communicate the data 

#### Key Deadlines

- [ ] Sample Deadline
- [ ] Sample Deadline

**Comment by lauradereynal** [comment]
Hey @xmatthewx @flukeout @sabrinang Thanks for talking with us last week. Here is a ticket and a summary of what is needed. Feel free to update the DARCI. 
How do you want to proceed for the project ? 

@flukeout and @sabrinang did you get a chance to think about it ?

Let us know what to do and how to help. 
Laura

**Comment by flukeout** [comment]
Ill add thoughts in a little bit.

**Comment by flukeout** [comment]
I think the best place I can help is with thinking through the various infographics & charts. In the doc they are listed as ``Lots lots lots of graphics and legends i.e. numbers and quantitative data 
`` - can we start a list that summarizes this need? Hopefully we can identify some commonalities in these so we can have a few different types.

The ultimate design of them (color / style etc) will depend on the design of the overall report, which I'm not the best person to steer / decide. It seems that the pervious design effort took about 2-3 weeks of a designer's time - so we should use that as a benchmark for the design work.

@sabrinang maybe you can take a stab at an estimate for the template design?

@LauraReynal @secretrobotron can we elaborate and expand on the diagram needs? We could do that in a new doc or issue.

**Comment by flukeout** [comment]
A few takes on the Buy vs Gift graphic from Page 18. Will post a few more ideas.

![infographic-gift-vs-buy](https://cloud.githubusercontent.com/assets/25212/21696688/f615fdc4-d343-11e6-9a83-cfd819f318a6.png)

**Comment by flukeout** [comment]
Another take.

![image](https://cloud.githubusercontent.com/assets/25212/21697517/97a989b4-d347-11e6-818a-1852286ce84f.png)

@secretrobotron @LauraReynal thoughts on these options?

**Comment by flukeout** [comment]
I'll take a crack at some of the other stats tomorrow.

**Comment by lauradereynal** [comment]
Hey @flukeout Thanks for starting this ! 

I love the 2nd and the 4th options. Because they both really highlight the information.
I would make the 3X just a bit bigger on the 4th option. 


We are using the Chicago report template for now, and hope that a contractor will be able to do a design pass when we are done. mzl.la/chicago

**Comment by secretrobotron** [comment]
Agreed. The 2nd in https://github.com/MozillaFoundation/plan/issues/841#issuecomment-270751066 is clearest to me.

**Comment by flukeout** [comment]
Okay, continuing with graphic 2 and added SIM card / carrier data.

![image](https://cloud.githubusercontent.com/assets/25212/21729266/360ea6f4-d3ff-11e6-981e-581cfe0d94a7.png)

**Comment by flukeout** [comment]
Updated with computer access & internet use stats. I think this would make up one page of info, so we can adapt it to fit that specific format next and see how it looks.

![infographic-page](https://cloud.githubusercontent.com/assets/25212/21732694/950ca092-d40f-11e6-870e-f169a977cb66.png)

**Comment by secretrobotron** [comment]
Really cool!

The only thing that kind of threw me was the computer use/ownership part. I like that the screen shows contrast, but it kind of looks like a graph that's not accurate, considering all the other bar graphs above.

**Comment by flukeout** [comment]
Oh yeah? I totally agree with you too...

![image](https://cloud.githubusercontent.com/assets/25212/21734480/745039fa-d418-11e6-81b0-d3f61ae54509.png)

**Comment by flukeout** [comment]
Yeah, maybe I can have two computers side by side maybe to alleviate that. I'll try something else out.

**Comment by secretrobotron** [comment]
That's much better, I think. See how each ice cream has a white background though? Most people erase that first to give a better illusion of layering.

**Comment by flukeout** [comment]
Two hole icecreams for you! 🍨 

![image](https://cloud.githubusercontent.com/assets/25212/21734577/f3a72628-d418-11e6-8c94-a189785551e1.png)

**Comment by secretrobotron** [comment]
![charlie brooker](https://cloud.githubusercontent.com/assets/403231/21734760/10fd1740-d433-11e6-81db-00ed04c6207f.jpg)

**Comment by lauradereynal** [comment]
Hey @flukeout any update? we are due to hand out the report by tomorrow for it's first review. 
Let us know how you are doing so we can anticipate 😄

**Comment by jgmac1106** [comment]
About time some folks bring some fun to GitHub. Been awhile.

**Comment by lauradereynal** [comment]
haha @jgmac1106 we are cooking a big report ready soon 🍰 🎉

**Comment by lauradereynal** [comment]
@flukeout are you working on in-design, illustrator, sketch or other?

**Comment by lauradereynal** [comment]
<img width="956" alt="screenshot 2017-01-12 12 06 31" src="https://cloud.githubusercontent.com/assets/8261945/21889189/962e0204-d8bf-11e6-9791-add2428ef1cf.png">

Here is what it looks like in the in-design file.

**Comment by flukeout** [comment]
Hey team, some more stuff coming your way a bit later today. I'm using illustrator to do these, so I can send you the illustrator files or a PDF? Whatever is easier. I'll do some more designs today and maybe tomorrow we can also figure out if you need adjustments / changes.

Ill try to get through 

* demographics
* financial services
* maybe learning?

The android version stuff seems boring is there a summary stat you'd like to include? Like there are "6 major versions in use" or something like that? Or "No one version has more than 25% of the market share" etc.?

**Comment by secretrobotron** [comment]
>  is there a summary stat you'd like to include?

How about a comparison to the global stats? https://developer.android.com/about/dashboards/index.html

The interesting part about that data is the fact that the window is pretty large, and the majority of people are using old systems. Sort of proof that not everyone is riding the tip this great upward wave of technology.

**Comment by flukeout** [comment]
So what about something more along those lines "only 25% are using a modern version of the operating system" or something.

That's easier to couple with an image or graphic and gets the point across? I don't think a version by version breakdown is useful? Or.. "People are using more than 10 different versions of the os, with 40% being out of date".

**Comment by secretrobotron** [comment]
Yeah, cool. Something that conveys the breadth of versions people still us, and that the majority is still far behind "modern" standards (e.g. not Android 6 or 7).

**Comment by lauradereynal** [comment]
❤️ 👍 to using illustrator because it means we can make minor edits oursleves 
which we might need to :) we had our first review today !

**Comment by flukeout** [comment]
For the age of respondents, do you have the oldest and youngest? Might be a cool bit of info.

**Comment by flukeout** [comment]
Some more stuff

![image](https://cloud.githubusercontent.com/assets/25212/21912576/a267dd44-d8db-11e6-9752-0cf7088115fb.png)

Need clarification on the married / single thing - left a comment in the google doc.

**Comment by flukeout** [comment]
I put all of the graphics into one long page for now so you can just pick and choose how to use it. I set up a DSO folder in the shared drive, you'll find the source Illustrator file there.

* https://goo.gl/XtxmXB

![infographic-long](https://cloud.githubusercontent.com/assets/25212/21939686/ce34057a-d975-11e6-8074-4fe9d96e2589.png)

**Comment by secretrobotron** [comment]
One important bit of feedback we got about the "93%" stat: they say they know how to use the internet, but we know they don't. It's hard to pin a number to how many people are overconfident, but maybe we can say, "93% of people say they can use the internet; we know this number is inflated by overconfidence" or something less.. long.

**Comment by secretrobotron** [comment]
Btw, thanks for the help 😄 !

**Comment by jgmac1106** [comment]
How about, "But We Know Many Believe Facebook is the Internet" with a
footnote to that statistic or is there any other self-efficacy or frequency
of use question in your data  that could be contrasted, "93% say they can
use the Internet, but only X% have Y (built a website, used a search
engine, believe they are good, etc)?

**Comment by secretrobotron** [comment]
> but only X% have Y

Yep, good thinking. The point we're trying to make is that the majority thought they knew how to use the internet, but they really didn't. There's no hard statistic we have about that, but we do know that their internet use is not what we expected from that kind of confidence.

I like the Facebook = Internet reference.
