### ISSUE TITLE
Production Support for Hive Chi Buzz

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/plan#842]
Background: info from @samueledyson

Given our focus on the network launch, we'll have limited resources. We might think about how to repurpose MozFest materials with simple updates for efficiency and pizzazz. 

@edrushka @simonwex @hannahkane

**Comment by samueledyson** [comment]
I think you meant to tag @samanthaburton. Hi anyway! 😃

**Comment by samueledyson** [comment]
Repurposing MozFest materials would work for us.  Using MozFest design themes might even create clearer linkages between MozFest and local MozFest-inspired events like HCB.  Let me know if you'd like to schedule a conversation to discuss what that might look like.
CC: @annmarie123

**Comment by samueledyson** [comment]
Following up on this thread, there are two elements for Hive Chicago Buzz (March 17-18, 2017; "HCB17") for which we are seeking assistance.

(1) By early March we would like to update the content within the version of the schedule app that we used last year, http://schedule.hivechicagobuzz.org/.  Ideally last year's content could be archived to http://schedule.hivechicagobuzz2016.org/.  
(2) We would love to be able to use some of the MozFest design elements for HCB17, such as posters, signage and lanyard design templates, creating clear visual connections between MozFest and HCB17.

We know you are busy with the MLN launch and we are eager to do whatever route is easiest for you. Please advise.

**Comment by edrushka** [comment]
@samueledyson I'd be happy to go through the MozFest design elements with you. The design team created a comprehensive [style guide](https://github.com/MozillaFoundation/Mozfest2016_production/issues/76) with individual elements that you might find useful to build upon. 

As for the schedule, I recommend you connect with Wex to see what is possible.

**Comment by hannahkane** [comment]
Opened a production ticket for the app here: https://github.com/mozilla/mofo-schedule-app/issues/38

**Comment by hannahkane** [comment]
Closing since this has passed
