### ISSUE TITLE
Public Beta

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#86]
Public beta release of Webmaker App at Mobile World Congress for Firefox OS 2.X and Android 4.2.

Phase: Design / Build / Ship
Owner: @thisandagain
Decision: @davidascher 
Lead design: n/a
Lead dev: TBD
Quality: @simonwex

**Comment by simonwex** [comment]
@thisandagain what is left to be done on this?

**Comment by thisandagain** [comment]
We are done! Just triaging any remaining bugs if they come in this week.

**Comment by k88hudson** [comment]
:star2: :star2: :star2: :star2: :star2: :star2: 
:dancer: :dancer: :dancer: :dancer: :dancer:
