### ISSUE TITLE
Final GSMA Field Report

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#88]
Release of *big* final field report with GSMA during Mobile World Congress.

Phase: Research / Build / Ship
Owner: @laurareynal
Decision: @davidascher 
Consulted: @benrito 
Lead design: @thisandagain
Lead dev: n/a
Quality: @cassiemc

**Comment by LauraReynal** [comment]
The GSMA pad: https://foundation.etherpad.mozilla.org/gsma-weekly
The BIG Report Outline: https://docs.google.com/document/d/1lWx7gtra8GugZEiJgs1670XgxVG4Op6YTypH_yuSC6k/edit?usp=sharing

**Comment by LauraReynal** [comment]
@thisandagain is there still work needed on the synthesis or can we close this one? 
Once we define the scope of the real big report, we could make a new issue.

**Comment by thisandagain** [comment]
All set! :cat2: :cake: :boom:
