### ISSUE TITLE
Create "Live Feed"

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#92]
For moderation (as well as *motivation*) we'll need a live feed of all projects being shared on Webmaker across both desktop / tablet and mobile platforms prior to release.

Phase: Design / Build / Ship
Owner: @thisandagain
Decision: @thornet 
Lead design: TBD
Lead dev: TBD
Quality: @simonwex

**Comment by thornet** [comment]
Is this still a live ticket? If not, propose we close it.

**Comment by thisandagain** [comment]
Still a live ticket.
