### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/plan#98]
Initial (re)-release of the Webmaker.org for desktop & tablets.

Phase: Design / Build / Ship
Owner: @thisandagain
Decision: @davidascher 
Lead design: TBD @cassiemc 
Lead dev: TBD @simonwex 
Quality: @cassiemc

**Comment by cassiemc** [comment]
More details about what design work is needed here, since @vazquez is on PTO this week?

**Comment by OpenMatt** [comment]
@thisandagain @xmatthewx thinking maybe this ticket is stale -- please advise.

**Comment by OpenMatt** [comment]
@thisandagain @xmatthewx thinking maybe this ticket is stale -- please advise.

**Comment by cassiemc** [comment]
As discussed w/ @xmatthewx, @flukeout and I can support design work that is needed this week until @vazquez's return from PTO.

**Comment by xmatthewx** [comment]
@OpenMatt - this ticket is stale. I'm going to close and continue tracking in #429
